import { bankUnit, type Q } from "../own";

// Grade 5 social studies, the Yukon First Nations units Yukon adds to the BC curriculum: Yukon First Nations
// governance and citizenship. Indigenous content is light, in the present tense, never treats all Nations as one,
// and leaves out ceremony. It needs review by Yukon First Nations partners before launch.

const FIRST_NATIONS: Q[] = [
  ["How many First Nations are there in Yukon?", "14", ["3", "40"], "There are 14 Yukon First Nations, each with its own history and territory."],
  ["Yukon First Nations are…", "living communities today", ["only part of the past", "all the same"], "Each Yukon First Nation is a living community with its own people, leaders and ways of doing things."],
  ["Which word names the place a First Nation has looked after for generations?", "traditional territory", ["tourist town", "school district"], "A traditional territory is the land a First Nation has lived on and cared for."],
  ["Is every Yukon First Nation exactly the same?", "No, each has its own history and ways", ["Yes, they are all the same", "Yes, they share one language"], "Yukon has many Nations with different histories, languages and traditions."],
  ["How many First Nations languages are spoken in Yukon?", "8", ["1", "80"], "Yukon has eight First Nations languages, such as Gwich'in, Southern Tutchone and Tlingit."],
  ["Which of these is a Yukon First Nations language?", "Tlingit", ["Cree", "Mi'kmaq"], "Tlingit is spoken in Yukon. Cree and Mi'kmaq are spoken in other parts of Canada."],
  ["Which of these is a Yukon First Nations language?", "Southern Tutchone", ["Ojibwe", "Inuktitut"], "Southern Tutchone is spoken in southwestern Yukon."],
  ["Why do many communities work to keep their language strong?", "Language carries history and ways of knowing", ["Because it is easy to learn", "Because the law says so"], "Languages hold stories, place names and knowledge, so many communities teach them to young people."],
  ["Who are Elders in a First Nation?", "Respected people who share knowledge and guidance", ["The youngest students", "Government clerks"], "Elders share teachings, stories and advice with the community.", true],
  ["Place names in a First Nation's own language often…", "describe the land or what happened there", ["are picked at random", "are invented for maps"], "Many names tell what a place is like or what people do there.", true],
  ["Which of these is part of Yukon, not a country?", "Whitehorse", ["Mexico", "Paris"], "Whitehorse is a city in Yukon, in the northwest of Canada."],
  ["Yukon is in which part of Canada?", "the northwest", ["the southeast", "the Atlantic coast"], "Yukon is a territory in the northwest, next to Alaska."],
  ["First Nations people have lived in the area now called Yukon for…", "thousands of years", ["about ten years", "only since 1900"], "Yukon First Nations have cared for their territories for a very long time."],
  ["Who knows the most about a First Nation's own history and language?", "The people of that First Nation", ["Anyone who has never visited", "A random website"], "The best way to learn is from the Nation itself, its Elders and its own materials."],
  ["Which is a respectful way to learn about a First Nation?", "Listen to the stories its people choose to share", ["Guess and make things up", "Copy things without asking"], "Respect means learning from the people themselves."],
  ["Yukon First Nations languages are…", "still spoken and taught today", ["lost forever", "only found in museums"], "Language programs and schools help young people learn them."],
  ["Which of these is a Yukon First Nations language?", "Gwich'in", ["French", "Spanish"], "Gwich'in is spoken in northern Yukon."],
  ["Which of these is a Yukon First Nations language?", "Hän", ["Cree", "Haida"], "Hän is spoken around Dawson City and the Yukon River."],
  ["Traditional territory means land that a First Nation…", "has lived on and looked after for generations", ["bought last year", "only visits on holidays"], "It is the land connected to a Nation's history and way of life."],
  ["What do many First Nations pass on to young people?", "Stories, language and knowledge about the land", ["Only toys", "Nothing at all"], "Sharing knowledge keeps culture strong."],
  ["Which statement is true?", "Yukon has many First Nations with different languages", ["All Yukon First Nations speak one language", "There are no First Nations in Yukon"], "Yukon has 14 First Nations and eight languages.", true],
  ["A river can be important to a First Nation because it…", "gives food, travel routes and a place to gather", ["is only a map line", "has no use"], "Rivers like the Yukon River have connected communities for generations.", true],
  ["Why is it important to say \"Yukon First Nations\" and not just \"First Nations\"?", "It names the specific Nations of this place", ["It is shorter", "It means a different country"], "Naming the right Nations is a way to be accurate and respectful.", true],
  ["Learning a language helps you understand…", "the way people see the world", ["nothing new", "only grammar"], "Language holds ways of knowing, doing and being.", true],
  ["Which of these shows a living community?", "A First Nation with a council, a school and young people", ["Only old photographs", "A story with no people"], "First Nations are living communities today.", true],
  ["Which one is a Yukon feature?", "The Yukon River", ["The Fraser River", "The St. Lawrence River"], "The Yukon River flows through Whitehorse and Dawson City.", true],
];

const CITIZENSHIP: Q[] = [
  ["Citizenship means…", "belonging to a group and sharing its rights and responsibilities", ["owning a house", "living alone"], "A citizen belongs to a community and helps it work well."],
  ["Can a person be a citizen of a First Nation and a citizen of Canada?", "Yes, both", ["No, only one", "Only if they move away"], "Many Yukon people are citizens of their First Nation and of Canada."],
  ["Which is a responsibility of a good citizen?", "Taking care of the community and each other", ["Ignoring the rules", "Keeping everything for yourself"], "Citizens help, share and respect others."],
  ["Which is a right?", "Being treated fairly", ["Never having to help", "Always winning"], "Rights are things everyone should be able to count on."],
  ["Many Yukon First Nations people belong to a clan. A clan is…", "an extended family group", ["a sports team", "a school grade"], "Clans connect families, and many Nations pass a clan on through the family."],
  ["Why might a family or clan share jobs like hunting, fishing and caring for children?", "People help each other and everyone benefits", ["Nobody wants to work", "It is against the law to work alone"], "Sharing the work and what is gathered builds strong communities."],
  ["Which action shows respect for an Elder?", "Listening carefully when they speak", ["Interrupting", "Walking away"], "Listening shows respect and helps you learn."],
  ["Which action shows citizenship at school?", "Following the class agreement and helping others", ["Leaving a mess", "Ignoring a classmate who needs help"], "Good citizens add to their community.", true],
  ["A citizen can show care for the community by…", "picking up litter", ["leaving it", "complaining only"], "Small actions help everyone."],
  ["Which shows respect for a classmate's turn to speak?", "Wait and listen", ["Talk over them", "Laugh at them"], "Respect means giving others a turn."],
  ["Belonging to a family, a school and a Nation means you belong to…", "more than one community", ["only one group", "no group"], "People often belong to many communities at once."],
  ["Rules in a community help…", "keep people safe and fair to each other", ["make life harder on purpose", "pick one winner"], "Good rules protect everyone."],
  ["Which is a responsibility?", "Taking care of shared spaces", ["Having a birthday", "Getting a gift"], "A responsibility is something you should do for others."],
  ["Which is a right every child has?", "Learning and going to school", ["Never sharing", "Skipping rules"], "Children have a right to learn and be safe."],
  ["What does it mean to volunteer?", "Helping without being paid", ["Getting paid to help", "Asking others to do the work"], "Volunteers give time to help their community."],
  ["A clan can help families…", "know who they are connected to", ["forget their names", "move away"], "Clans link people across families and communities.", true],
  ["Why do many communities honour Elders?", "They carry knowledge and experience", ["They are always right about sports", "They are paid to"], "Elders have lived long and learned much to share.", true],
  ["Citizenship in a First Nation can include…", "responsibilities to the community and to the land", ["only paying a fee", "nothing at all"], "Many Nations teach caring for people and the land together.", true],
  ["Which is the best example of working together?", "A family sharing jobs to prepare a meal", ["One person doing everything", "Everyone leaving"], "Sharing the work makes it lighter.", true],
  ["Two people disagree. A fair, respectful step is to…", "listen to each other and look for a solution", ["shout louder", "ignore the problem"], "Respectful talk helps people work it out.", true],
  ["Being a good neighbour means…", "being kind and helping when you can", ["never saying hello", "being noisy at night"], "Neighbours help build a caring community."],
  ["A person can be proud of their Nation and also be a Canadian citizen. This shows that identity can be…", "layered", ["impossible", "against the rules"], "People can belong to more than one community.", true],
  ["Which action helps protect land and water?", "Not leaving garbage", ["Burning plastic", "Dumping oil"], "Looking after the land is a shared responsibility."],
  ["Teamwork helps a community because…", "many hands make the work lighter", ["it takes more time", "it hides mistakes"], "Together we can do more."],
];

const GOVERNANCE: Q[] = [
  ["Governance means…", "the way a community makes decisions and looks after its people", ["a type of weather", "a kind of map"], "Governance is how decisions are made and who is responsible."],
  ["Who helps lead a First Nation government today?", "A chief and council, with advice from citizens and Elders", ["A tourist office", "A hockey coach"], "Each Nation chooses its own leaders and ways of deciding."],
  ["Yukon First Nations governed themselves…", "long before Canada was a country", ["only after 1900", "only since the year 2000"], "First Nations have governed their own people on their territories for many generations."],
  ["The Umbrella Final Agreement was signed in…", "1993", ["1867", "2010"], "In 1993, Yukon First Nations, Yukon and Canada agreed on a framework for land claims and self-government."],
  ["Who made the Umbrella Final Agreement with the Government of Canada and the Government of Yukon?", "Yukon First Nations", ["Only the Yukon government", "A mining company"], "It was negotiated by Yukon First Nations, Yukon and Canada."],
  ["A self-governing First Nation can…", "make laws about its own lands and citizens", ["decide the weather", "close the territory's airport"], "Self-government lets a First Nation make decisions for its citizens and lands."],
  ["How many Yukon First Nations have signed self-government agreements?", "11", ["2", "5"], "Eleven of the 14 First Nations have final and self-government agreements; the others are still in talks or on their own path.", true],
  ["Which city is the capital of Yukon?", "Whitehorse", ["Dawson City", "Yellowknife"], "Whitehorse is the capital, and the Yukon government meets there."],
  ["The Government of Yukon is a…", "territorial government", ["provincial government", "school board"], "Yukon is one of Canada's three territories, not a province.", true],
  ["A group listens to many voices and decides by…", "talking until people agree", ["guessing", "flipping a coin"], "Many communities work to hear everyone and reach an agreement together.", true],
  ["A council is…", "a group of people who help make decisions", ["a type of boat", "a single judge"], "Many governments have a council that makes decisions together."],
  ["In a government, a leader is chosen by…", "the people they will serve", ["a coin toss", "nobody"], "Many First Nations choose their chief and council in elections."],
  ["Which is a job of a government?", "Making rules and providing services", ["Growing all the food", "Painting every house"], "Governments make decisions and help provide services for people."],
  ["A land claim agreement is…", "an agreement about land and rights", ["a kind of tax form", "a weather report"], "Yukon First Nations negotiated agreements about their lands and self-government."],
  ["Who decides how a self-governing First Nation uses its own settlement land?", "The First Nation", ["A faraway company", "No one"], "Self-governing Nations make decisions about their own lands."],
  ["The Yukon Legislative Assembly meets in…", "Whitehorse", ["Ottawa", "Vancouver"], "The territorial government meets in Whitehorse."],
  ["Canada's federal Parliament meets in…", "Ottawa", ["Whitehorse", "Winnipeg"], "Ottawa is Canada's capital."],
  ["Which levels of government can affect people in Yukon?", "First Nation, territorial and federal", ["Only a school", "Only one"], "People in Yukon can live under First Nation, territorial and federal governments.", true],
  ["Why do First Nations governments ask for advice from Elders?", "Elders carry knowledge and experience", ["Elders must sign every cheque", "Elders pick the weather"], "Elders help guide decisions.", true],
  ["Which does a government need to be fair?", "Listening to the people it serves", ["Ignoring everyone", "Making rules in secret"], "Fair governments listen and explain their decisions.", true],
  ["A vote is a way to…", "choose or decide as a group", ["pick a random winner", "hide a choice"], "Many communities vote to choose leaders or decide an issue."],
  ["Yukon is one of Canada's…", "three territories", ["ten provinces", "two oceans"], "Canada has ten provinces and three territories."],
  ["Which statement about self-government is true?", "It lets a First Nation make decisions for its citizens and lands", ["It removes the First Nation", "It means the Nation has no leaders"], "Self-government is about a Nation making its own decisions.", true],
  ["Why are agreements written down and signed?", "So everyone understands what was promised", ["So they can be lost", "Because paper is shiny"], "Written agreements make promises clear."],
  ["Which of these is a citizen's role in government?", "Voting when they are old enough and sharing opinions", ["Skipping every meeting", "Never learning about it"], "Citizens help shape decisions."],
];

export const units = [
  bankUnit({
    id: "yk-first-nations",
    title: "Yukon First Nations Today",
    emoji: "🏔️",
    blurb: "Meet the First Nations, languages and Elders of Yukon.",
    parentNote: "Yukon adds Yukon First Nations content to Grade 5 social studies. This unit covers the 14 First Nations, their languages and how communities share knowledge. Present tense, living communities.",
    standards: ["Yukon First Nations", "who the Yukon First Nations are, their languages and traditional territories"],
    items: FIRST_NATIONS,
  }),
  bankUnit({
    id: "yk-citizenship",
    title: "Yukon First Nations Citizenship",
    emoji: "🤝",
    blurb: "What it means to belong, share and help your community.",
    parentNote: "Yukon adds Yukon First Nations citizenship to Grade 5 social studies. Children practise rights, responsibilities, clans, Elders and belonging to more than one community.",
    standards: ["Yukon First Nations Citizenship", "citizenship, clans, rights and responsibilities"],
    items: CITIZENSHIP,
  }),
  bankUnit({
    id: "yk-governance",
    title: "Yukon First Nations Governance",
    emoji: "🏛️",
    blurb: "How First Nations and the Yukon make decisions.",
    parentNote: "Yukon adds Yukon First Nations governance to Grade 5 social studies. Children learn about chiefs and councils, the Umbrella Final Agreement and self-government.",
    standards: ["Yukon First Nations Governance", "how Yukon First Nations govern, and the Umbrella Final Agreement"],
    items: GOVERNANCE,
  }),
];
