import type { SortSet } from "../bank";
import { orderOf } from "../grades/kit";
import type { Unit } from "../types";
import { ab } from "./kit";
import { partsPlus, q } from "./g8-bank";

// Alberta Grade 8 social studies (2005): Historical Models of Societies. 8.1 Japan, 8.2 Renaissance Europe
// and 8.3 the Spanish and the Aztecs (the Mexica). BC's Renaissance and Reformation unit is shared (see g8.ts).
// All content is original. The Mexica and Nahua peoples are described with care: they are living cultures,
// and their descendants speak Nahuatl today. No sacred or ceremonial detail is included.

// ---------- 8.1 Japan ----------

const JAPAN_LAND = [
  q(1, "Japan is a country made up of…", "many islands", ["one large island", "a long peninsula only", "a desert"], "Japan has thousands of islands, and four main ones."),
  q(1, "Which is the largest of Japan's four main islands?", "Honshu", ["Hokkaido", "Kyushu", "Shikoku"], "Honshu is the biggest island and is home to Tokyo and Kyoto."),
  q(1, "Why do most people in Japan live on narrow coastal plains?", "Much of the land is mountainous.", ["The mountains are too warm.", "The plains are above the clouds.", "There are no rivers."], "Japan is about three-quarters mountains, so flat land is precious."),
  q(1, "What crop has been central to farming in Japan for a very long time?", "rice", ["wheat", "canola", "potatoes"], "Rice grown in flooded paddies fed many people in Japan."),
  q(2, "Japan lies where tectonic plates meet. What natural hazard is common there?", "earthquakes", ["blizzards", "locust swarms", "tornado outbreaks across plains"], "Many earthquakes and volcanoes happen around the Pacific plate boundaries."),
  q(2, "Shinto, an old belief in Japan, honours…", "kami, the spirits in nature and special places", ["only the shogun", "only foreign gods", "machines"], "Shinto shrines are found near mountains, trees and waterfalls."),
  q(2, "Buddhism came to Japan around the 500s CE from…", "Korea and China", ["Egypt", "Spain", "Mexico"], "Ideas, writing and religion travelled to Japan from nearby parts of Asia."),
  q(2, "Confucian ideas in Japan stressed…", "respect for family, order and duty", ["the freedom to ignore rules", "trade with other countries only", "staying away from people"], "Confucian teachings from China shaped ideas about loyalty and respect."),
  q(2, "Why did the sea help Japan stay separate from mainland Asia?", "Water lies between Japan and its neighbours.", ["There are no ships.", "The sea is frozen all year.", "Japan is joined to Korea."], "Being an island nation made it easier to limit contact."),
  q(3, "What is one way geography shaped how people in Japan lived?", "Fishing and farming on small amounts of flat land shaped communities.", ["Japan has huge flat prairies.", "Deserts shaped most towns.", "Japan has no coast."], "Mountains and the sea shaped where people lived and how they worked."),
  q(3, "How do a society's beliefs and values shape its worldview?", "They guide what people think is important and how they act.", ["They have no effect on people.", "They only matter to rulers.", "They change every day."], "Worldview is shaped by religion, philosophy, geography and experience."),
  q(3, "Which value did the samurai class admire?", "loyalty and discipline", ["wealth from trade", "avoiding all rules", "travelling abroad"], "Samurai were warriors who served lords and honoured a code of conduct."),
  q(3, "Why were arts such as haiku poetry and woodblock prints popular in Edo (Tokyo) in the 1700s?", "Peace and growing cities created audiences, and printing made art affordable.", ["There were no cities.", "The shogun banned all art.", "Printing was not yet known."], "Long peace helped city life and the arts to flourish."),
  q(1, "What is the capital of Japan today?", "Tokyo", ["Kyoto", "Beijing", "Seoul"], "Tokyo was called Edo before 1868."),
  q(1, "What is the tallest mountain in Japan?", "Mount Fuji", ["Mount Everest", "Mount Logan", "Mount Rainier"], "Mount Fuji is a volcano and a well-known symbol of Japan."),
  q(1, "Which ocean lies to the east of Japan?", "the Pacific Ocean", ["the Atlantic Ocean", "the Arctic Ocean", "the Indian Ocean"], "Japan is on the western edge of the Pacific."),
  q(1, "Which large country lies to the west of Japan across the sea?", "China", ["Mexico", "Brazil", "Australia"], "Korea and China have been neighbours across the sea for centuries."),
  q(1, "What is a typhoon?", "a strong storm with heavy rain and winds", ["a mountain", "a type of rice", "a kind of boat"], "Typhoons often reach Japan in late summer."),
  q(2, "In a rice paddy, fields are flooded. Why?", "Rice grows well with its roots in shallow water.", ["To keep the farmers cool", "To frighten insects", "To catch fish only"], "Rice paddies were shaped to hold water."),
  q(2, "Which two religions or philosophies had the greatest influence on early Japanese life?", "Shinto and Buddhism", ["Christianity and Islam", "Judaism and Sikhism", "Greek mythology and Roman law"], "Many Japanese people took part in both traditions."),
  q(2, "Which writing system did Japan adapt from China?", "kanji, characters", ["Latin letters only", "Cyrillic", "Hieroglyphs"], "Japan borrowed Chinese characters and made its own writing."),
  q(2, "What is a 'torii'?", "a gate at the entrance of a Shinto shrine", ["a type of sword", "a farming tool", "a ship"], "Torii mark the move from ordinary space into a shrine."),
  q(2, "Why did early Japanese villages often develop near rivers and coasts?", "Water, fish and flat land for farming were found there.", ["Mountains are warm.", "Cities had no rivers.", "There were no roads."], "People settled where food and water were available."),
  q(3, "How might frequent earthquakes have shaped the way buildings were built in Japan?", "Builders developed designs that could flex, such as wooden frames.", ["Builders avoided building at all.", "Builders only used rock.", "Builders built underwater."], "Pagodas with flexible wooden frames can sway without falling."),
  q(3, "The emperor in Japan had a special religious role while samurai held military power. What does this show?", "Different groups held different kinds of authority.", ["The emperor ruled alone in everything.", "Samurai had no power.", "Japan had no leader."], "Power was shared among the emperor, the shogun and regional lords."),
  q(3, "Why do historians look at both geography and beliefs to understand a society's worldview?", "Both the land and the ideas people hold shape how they live.", ["Geography does not matter.", "Beliefs never change.", "Only maps matter."], "A worldview is shaped by many things."),
  q(3, "Which statement shows Confucian ideas affecting family life in Japan?", "Respect for elders and duty to the family were highly valued.", ["Everyone ignored their elders.", "Families were not important.", "Children made all decisions."], "Confucian ideas stressed relationships and duty."),
];

const TOKUGAWA = [
  q(1, "Who held the real power in Japan during the Tokugawa period?", "the shogun", ["the emperor", "the merchants", "the farmers"], "The emperor was honoured, but the shogun ruled."),
  q(1, "Samurai were…", "warriors who served their lords", ["merchants", "farmers", "fishers"], "Samurai were at the top of Japan's class system."),
  q(1, "What is a daimyo?", "a regional lord who ruled a domain", ["a farming tool", "a type of sword", "a foreign trader"], "The daimyo ruled their lands under the shogun's authority."),
  q(1, "The Tokugawa shogunate ruled Japan for about…", "250 years", ["25 years", "10 years", "1000 years"], "From 1603 to 1868, Japan was ruled by the Tokugawa family."),
  q(2, "Which group was ranked highest in the Tokugawa class system?", "the samurai", ["the merchants", "the artisans", "the farmers"], "Samurai were first, then farmers, artisans and merchants."),
  q(2, "Merchants often had a lot of money. Where were they ranked in the Tokugawa class system?", "at the bottom", ["at the top", "just below the shogun", "above the samurai"], "The system ranked people by their role, not their wealth."),
  q(2, "Why did Tokugawa rulers make daimyo spend alternate years in Edo?", "To help the shogun keep control of the lords.", ["To help the lords learn English.", "To lower taxes.", "To teach the lords to farm."], "The system of 'alternate attendance' kept daimyo busy, costly and watched."),
  q(2, "What was Japan's isolation policy?", "It limited contact and trade with other countries.", ["It invited everyone to settle in Japan.", "It ended all farming.", "It made the emperor a shogun."], "From the 1630s, Japanese people were not allowed to leave, and foreign trade was tightly controlled."),
  q(2, "During the isolation period, which foreign traders were allowed at Nagasaki?", "the Dutch and the Chinese", ["the English and the French", "the Spanish and the Portuguese", "the Americans and Canadians"], "Only a few foreign traders were allowed, under strict rules."),
  q(2, "Which city became a huge centre of government and trade, and later became Tokyo?", "Edo", ["Kyoto", "Osaka", "Nagoya"], "By the 1700s Edo was one of the largest cities in the world."),
  q(3, "Why did the shogunate want to limit foreign contact?", "To protect its control and stop foreign influence from changing society.", ["To make trade bigger.", "To bring in foreign armies.", "To let anyone travel."], "Leaders feared that outside ideas and powers could weaken their rule."),
  q(3, "During isolation, how did Japanese scholars still learn about Western science?", "Through books brought by Dutch traders (called 'Dutch learning').", ["By travelling to Europe freely.", "By sending letters through the emperor.", "They did not learn anything."], "Some knowledge came through Nagasaki, even when contact was limited."),
  q(3, "The Tokugawa period was mostly peaceful. How did this affect Japan?", "Cities, trade and the arts grew.", ["Cities disappeared.", "Farming stopped.", "The shogun lost power at once."], "Without long wars, people could build, trade and create."),
  q(3, "How did a rice-based economy affect the status of samurai?", "Samurai were paid in rice, but some struggled when its value changed.", ["Samurai earned no payment.", "Samurai grew all the rice themselves.", "Samurai stopped serving lords."], "A fixed income in rice could shrink in value while merchants grew richer."),
  q(1, "What was the capital of the shogunate under the Tokugawa?", "Edo", ["Nagasaki", "Osaka", "Nara"], "The shogun's government was based in Edo."),
  q(1, "Which family ruled Japan as shoguns from 1603 to 1868?", "the Tokugawa family", ["the Medici family", "the Tudor family", "the Habsburg family"], "Tokugawa Ieyasu founded the line of shoguns."),
  q(1, "Who was at the bottom of the four-class system (not counting outcast groups)?", "merchants", ["samurai", "farmers", "the emperor"], "Merchants were ranked low because they did not produce food."),
  q(1, "What did farmers do in the Tokugawa period?", "They grew the rice that fed the country.", ["They ruled the domains.", "They carried swords as samurai.", "They governed Edo."], "Most people in Japan were farmers."),
  q(2, "Why were samurai not allowed to move from one lord to another freely?", "The system kept order and loyalty.", ["They could not walk.", "There were no roads.", "Lords wanted to lose followers."], "Loyalty to a lord was central to the samurai code."),
  q(2, "Some samurai had no lord. What were they called?", "ronin", ["shogun", "daimyo", "kami"], "A ronin was a masterless samurai."),
  q(2, "What was the Tokugawa government's reason for banning Christianity in the 1600s?", "Leaders feared it would weaken loyalty to the shogun and bring foreign influence.", ["Christianity was unknown.", "Leaders disliked churches' paint.", "Christianity was too old."], "The ban was part of the policy of control."),
  q(2, "Woodblock prints called ukiyo-e were popular in Edo. What did they often show?", "Scenes of daily life, landscapes and actors", ["Spanish ships", "Railways", "Maps of Europe"], "Artists such as Hokusai and Hiroshige made famous prints."),
  q(2, "Kabuki is a type of theatre popular in Tokugawa Japan. What does it include?", "music, dance and dramatic costumes", ["silent films", "radio shows", "sports matches"], "Kabuki began in the early 1600s."),
  q(2, "During the Tokugawa period, what was Edo's population by about 1700?", "About one million people", ["About 1 000 people", "About 5 000 people", "About 50 000 people"], "Edo was among the largest cities in the world."),
  q(3, "The daimyo travelled to Edo with large groups and kept families there. How did this help the shogun?", "It kept lords loyal and made it costly for them to rebel.", ["It made lords richer.", "It stopped all trade.", "It ended farming."], "Costly travel and family 'hostages' kept lords under control."),
  q(3, "Roads like the Tōkaidō linked Edo to other cities. What was one effect?", "Trade, news and travel grew.", ["Travel stopped.", "Roads were closed.", "Edo lost its people."], "Alternate attendance made busy highways with inns."),
  q(3, "Merchants could be wealthy but were ranked low. What problem might this have caused?", "Wealthy merchants had less status than their money suggested, which created tension.", ["No one noticed their wealth.", "Merchants became samurai at once.", "Merchants gave up trade."], "Money and status did not match."),
  q(3, "Why was the port at Dejima in Nagasaki important during isolation?", "It was a window to the outside world for trade and information.", ["It was where samurai trained.", "It closed all trade.", "It was for farmers only."], "The Dutch traded there under strict rules."),
  q(3, "How do historians know about daily life in Tokugawa Japan?", "Diaries, art, maps and records of the time give clues.", ["No evidence survives.", "Only legends exist.", "Only Spanish books."], "Primary sources help us learn."),
  q(3, "The population of Japan grew slowly during the late Tokugawa period. What might limit growth?", "Limits on farmland and famine in bad harvest years", ["Too many mountains were removed", "Too much trade with Europe", "A shortage of paper"], "Crop failures caused hardship."),
  q(3, "Why do some historians say isolation was not complete?", "Trade with China, Korea and the Dutch continued and ideas still arrived.", ["Japan traded with the whole world.", "There was no trade at all.", "There were no ports."], "'Closed country' policy was controlled contact, not no contact."),
];

const TOKUGAWA_ORDER = orderOf(
  "Put these events in Japan's history in order.",
  "Tokugawa Ieyasu became shogun in 1603. The isolation laws came in the 1630s, Perry arrived in 1853 and the Meiji Restoration was in 1868.",
  [
    { id: "shogun", label: "Tokugawa Ieyasu becomes shogun", emoji: "🏯" },
    { id: "isolation", label: "Japan limits contact with other countries", emoji: "🚪" },
    { id: "perry", label: "American ships arrive and ask Japan to open its ports", emoji: "⛴️" },
    { id: "meiji", label: "The Meiji Restoration begins", emoji: "🏛️" },
  ],
);

const MEIJI = [
  q(1, "Which country did Commodore Perry sail from to ask Japan to open its ports?", "the United States", ["Spain", "Mexico", "Brazil"], "Perry's ships arrived in 1853 and again in 1854."),
  q(1, "The new government of 1868 put which leader at its centre?", "the emperor", ["the shogun", "the merchants", "the farmers"], "The Meiji Restoration 'restored' the emperor to the centre of government."),
  q(1, "After 1868, Edo was renamed…", "Tokyo", ["Kyoto", "Osaka", "Nagasaki"], "The emperor moved there, and it became the capital."),
  q(1, "What does 'adaptation' mean?", "changing to fit new conditions", ["staying exactly the same", "forgetting everything", "keeping everything out"], "A society adapts when it takes on new ideas while keeping what matters to it."),
  q(2, "How did Perry's visit change Japan?", "It pushed Japan to open some ports to trade and weakened the shogunate.", ["It ended trade for good.", "It made Japan a colony.", "It had no effect."], "The treaty signed in 1854 opened ports and showed Japan's rulers could not stop foreign power."),
  q(2, "Which of these was a part of Japan's modernization in the Meiji period?", "building railways and factories", ["closing all ports", "banning schools", "stopping all trade"], "Japan built its first railway in 1872 and invested in industry."),
  q(2, "In the Meiji period, Japan set up…", "a national system of schools", ["a ban on reading", "a system of only private tutors", "no schools at all"], "Education was made widely available to build a skilled population."),
  q(2, "What happened to the privileges of the samurai class in the Meiji period?", "They were ended.", ["They were doubled.", "They stayed the same for 100 years.", "They were given to merchants only."], "The new government created a new army of ordinary citizens and ended the old class system."),
  q(2, "Why did Japan's leaders look to other countries for ideas?", "They wanted to build a strong, modern country that could protect itself.", ["They wanted to give up independence.", "They wanted to stop all change.", "They wanted to become isolated again."], "Leaders sent missions abroad to study technology, law and education."),
  q(3, "How is the Meiji period an example of 'adapting' to new conditions?", "Japan borrowed Western technology and methods while keeping much of its own culture.", ["Japan copied everything and changed nothing of its own.", "Japan rejected all new ideas.", "Japan gave its land away."], "Japan combined new tools with its own traditions and identity."),
  q(3, "Why was the end of isolation a major change for Japan?", "People, goods and ideas could now flow in and out.", ["Nothing changed.", "The land moved.", "The ports were already open."], "Contact with the world brought new opportunities and challenges."),
  q(3, "Which phrase describes the Meiji government's aims?", "'rich country, strong army'", ["'closed doors, empty ports'", "'no schools, no trade'", "'old ways only'"], "Leaders linked a strong economy with the ability to defend the country."),
  q(3, "Why did some samurai oppose the Meiji reforms?", "They lost their special status and income.", ["They wanted more railways.", "They liked the new schools.", "They were given more land."], "Reforms ended old privileges, and some samurai protested."),
];

const PERIOD_SORT: SortSet = {
  prompt: "Tokugawa period or Meiji period? Sort each description.",
  hint: "The Tokugawa shoguns ruled until 1868 and limited foreign contact. The Meiji period began in 1868 with rapid modernization.",
  bins: [
    { id: "tokugawa", label: "Tokugawa (before 1868)", emoji: "🏯" },
    { id: "meiji", label: "Meiji (after 1868)", emoji: "🚆" },
  ],
  items: [
    { label: "the shogun holds real power", emoji: "🏯", bin: "tokugawa" },
    { label: "foreign trade limited to Nagasaki", emoji: "🚢", bin: "tokugawa" },
    { label: "samurai ranked at the top", emoji: "⚔️", bin: "tokugawa" },
    { label: "daimyo rule their domains", emoji: "🗾", bin: "tokugawa" },
    { label: "first railway opens", emoji: "🚆", bin: "meiji" },
    { label: "national schools for children", emoji: "🏫", bin: "meiji" },
    { label: "emperor is the centre of government in Tokyo", emoji: "🏛️", bin: "meiji" },
    { label: "an army of ordinary citizens", emoji: "🪖", bin: "meiji" },
  ],
};

// ---------- 8.2 Renaissance Europe ----------

const RENAISSANCE = [
  q(1, "'Renaissance' means…", "rebirth", ["war", "harvest", "empire"], "People became very interested in learning and art from ancient Greece and Rome."),
  q(1, "Where did the Renaissance begin?", "Italy", ["Japan", "Mexico", "Canada"], "It began in wealthy Italian city-states such as Florence."),
  q(1, "Which Italian city is known as an early centre of the Renaissance?", "Florence", ["Paris", "London", "Madrid"], "Florence's merchants, bankers and artists helped start it."),
  q(1, "A patron is…", "someone who pays artists and thinkers to do their work", ["someone who paints walls", "a kind of mask", "a type of ship"], "Rich families supported artists so they could create."),
  q(2, "Which Florentine family was a famous patron of artists?", "the Medici", ["the Tokugawa", "the Tudors", "the Habsburgs"], "The Medici were bankers who spent money on art, buildings and learning."),
  q(2, "What is humanism?", "a way of thinking that values human learning and achievement", ["a belief that learning is useless", "a form of farming", "a law about trade"], "Humanists studied literature, history and the arts."),
  q(2, "Why did trade help to start the Renaissance in Italy?", "Trade made merchants and cities wealthy enough to pay for art and learning.", ["Trade made all people poor.", "Trade stopped all travel.", "Trade ended cities."], "Italian cities such as Venice and Genoa traded across the Mediterranean."),
  q(2, "The Black Death (1347–1351) changed Europe because…", "so many people died that society and work changed", ["it ended all farming", "it made cities larger", "it improved health"], "Fewer workers meant higher wages, and people asked new questions about life."),
  q(2, "In the Middle Ages, much of Europe's thinking centred on the Church. What shifted in the Renaissance?", "More attention to human abilities and the world, alongside religion", ["Religion disappeared at once", "Everyone stopped reading", "People stopped using art"], "Most people stayed deeply religious, but interest in human achievement grew."),
  q(2, "What does 'individualism' mean?", "valuing a person's talents and achievements", ["valuing only the group", "valuing only machines", "ignoring people"], "Renaissance artists and thinkers began to sign and be proud of their work."),
  q(3, "Why did scholars from the Greek-speaking East bring useful knowledge to Italy in the 1400s?", "They carried ancient Greek texts and ideas with them.", ["They brought gunpowder.", "They brought Indigenous maps from the Americas.", "They brought no books."], "Ancient Greek and Roman writings were studied again."),
  q(3, "Why is the Renaissance called the start of a 'Western worldview'?", "Its ideas about reason, the individual and learning influenced later Western societies.", ["It had no effect on later society.", "It ended Western ideas.", "It was a copy of Japan's isolation."], "Many ideas that shaped later societies were developed in this time."),
  q(3, "How did wealthy city-states in Italy differ from large kingdoms?", "Each city-state governed itself with its own leaders.", ["They all had one king.", "They had no cities.", "They were part of Japan."], "Florence, Venice and Milan each had their own governments."),
  q(3, "Which statement best compares the Renaissance with the Middle Ages?", "The Renaissance placed greater value on learning from ancient writers and on individual achievement.", ["The Middle Ages had no religion.", "The Renaissance had no art.", "They were exactly the same."], "Both periods were religious, but their focus and emphasis changed."),
  q(1, "The Renaissance lasted roughly from the 1300s to the…", "1600s", ["800s", "1900s", "2000s"], "It began in Italy and spread across Europe."),
  q(1, "Which city, famous for canals, was a Renaissance trading power?", "Venice", ["Edo", "Calgary", "Madrid"], "Venice grew rich from trade with the East."),
  q(1, "What were people in the Renaissance interested in learning from?", "ancient Greece and Rome", ["only the Middle Ages", "Japan", "the Americas"], "They studied old books, art and buildings."),
  q(1, "Which kind of rich merchant or banker family paid for art in Florence?", "the Medici", ["the Mexica", "the Tokugawa", "the Inuit"], "Patrons gave artists the money and time to work."),
  q(1, "What is a city-state?", "a city that governs itself and the land around it", ["a town with no leader", "a kind of boat", "a type of farm"], "Many Italian cities were independent."),
  q(2, "How did the Church influence life in the Middle Ages?", "It shaped learning, art and daily life.", ["It had no influence.", "It banned all music.", "It governed Japan."], "The Church was the centre of most communities."),
  q(2, "Why did the fall of Constantinople in 1453 matter to Renaissance Italy?", "Scholars moved west with ancient Greek writings.", ["Cars were invented.", "Printing ended.", "Italy lost its cities."], "Greek knowledge spread through Italian cities."),
  q(2, "What did humanists think was a good way to educate people?", "Study of history, writing, speaking and the arts", ["Only farming", "Only fighting", "Only music"], "Humanist schools used ancient writers."),
  q(2, "Which Italian poet and scholar is often called an early humanist?", "Petrarch", ["Cortés", "Moctezuma", "Gutenberg"], "Petrarch collected and studied ancient texts."),
  q(2, "The Renaissance happened after the Black Death. What shift in thinking can the plague help to explain?", "People started to question old ideas and look to the present life.", ["People stopped asking questions.", "People left all cities.", "Books were banned."], "Hardship led to questions about old ways."),
  q(2, "Why were guilds important in Renaissance cities?", "They organized trades and trained apprentices.", ["They ran the Church.", "They built ships only.", "They ruled kingdoms."], "A guild was a group of workers in the same craft."),
  q(3, "Why did the Renaissance spread from Italy to other parts of Europe?", "Trade, travel and printed books carried ideas north.", ["Because Italy was closed.", "Because books were secret.", "Because people refused to travel."], "New ideas moved with merchants, scholars and printers."),
  q(3, "A historian says the Renaissance was not a 'rebirth' for everyone. What does she mean?", "Many people, such as poor farmers, did not see their lives change much.", ["Nobody lived then.", "Everyone was rich.", "Everyone was an artist."], "Most people were still peasants and workers."),
  q(3, "How did rich families use art to show their power?", "They paid for paintings, statues and buildings that carried their names.", ["They hid the art.", "They banned art.", "They burned books."], "Patronage was a way to gain fame."),
  q(3, "Which of these best describes the worldview of Renaissance humanists?", "People can learn about the world through reason and study.", ["Nothing can be learned.", "Only rulers can think.", "Only the past matters."], "Humanists valued learning and human ability."),
  q(3, "Why do historians avoid saying that Europeans 'invented' all the knowledge of the Renaissance?", "Scholars in the Islamic world, China and elsewhere also made knowledge that reached Europe.", ["No one else had knowledge.", "Europe was isolated.", "Books were not shared."], "Mathematics, medicine and astronomy drew on many cultures."),
];

const RENAISSANCE_ART = [
  q(1, "Who painted the Mona Lisa?", "Leonardo da Vinci", ["Michelangelo", "Gutenberg", "Galileo"], "Leonardo was a painter, inventor and scientist."),
  q(1, "Who sculpted the marble statue David?", "Michelangelo", ["Leonardo da Vinci", "Shakespeare", "Luther"], "Michelangelo carved David between 1501 and 1504."),
  q(1, "Which invention helped books spread ideas quickly in Europe?", "the printing press", ["the telescope", "the compass", "the clock"], "Johannes Gutenberg's press (about 1450) made many copies quickly."),
  q(1, "A Renaissance artist who wanted to show depth in a flat picture used…", "perspective", ["silence", "stone", "wax"], "Perspective makes things look as if they are in 3-D."),
  q(2, "Michelangelo painted the ceiling of which famous chapel?", "the Sistine Chapel", ["the Mona Lisa Room", "the Tower of London", "the Alhambra"], "He painted it from 1508 to 1512 in Rome."),
  q(2, "Leonardo da Vinci's notebooks show that he studied…", "anatomy, machines and nature", ["only music", "only farming", "only trade"], "He drew the human body, flying machines and the flow of water."),
  q(2, "Brunelleschi designed which famous feature of Florence?", "the dome of its cathedral", ["the printing press", "the first telescope", "the compass"], "His dome was an engineering marvel of the early 1400s."),
  q(2, "William Shakespeare, a writer of the late 1500s and early 1600s, lived in…", "England", ["Italy", "Spain", "Japan"], "Shakespeare's plays are still performed today."),
  q(2, "Why did the printing press matter?", "It let ideas spread faster and to more people.", ["It made books very rare.", "It stopped people from reading.", "It was used only by kings."], "Cheaper books meant more people could learn to read and share ideas."),
  q(3, "Copernicus proposed that the Earth and other planets…", "travel around the Sun", ["are fixed at the centre of everything", "stand still while the Sun goes around Earth", "do not move"], "He published his Sun-centred idea in 1543."),
  q(3, "Galileo used a telescope to observe moons around Jupiter. Why was this important?", "It gave evidence that not everything orbits the Earth.", ["It proved the Earth is flat.", "It ended the Black Death.", "It started a new religion."], "Observation became important for testing ideas."),
  q(3, "Why did Renaissance scientists value observation and experiment?", "They wanted to test ideas with evidence instead of only trusting old authorities.", ["They wanted to avoid thinking.", "They stopped using books.", "They distrusted all evidence."], "This approach shaped modern science."),
  q(3, "Why did some Church leaders object to new scientific ideas?", "The ideas seemed to challenge long-held teachings and authority.", ["The ideas were boring.", "The Church disliked writing.", "The ideas were too cheap."], "New observations challenged old beliefs, which led to disagreements."),
  q(3, "Why did Renaissance patrons often place their family names or symbols on works of art?", "To show wealth, power and support for learning.", ["To hide the artist.", "To avoid being noticed.", "To stop others from seeing the art."], "Art was also a way to show a family's standing."),
  q(1, "Who wrote the plays Romeo and Juliet and Hamlet?", "William Shakespeare", ["Leonardo da Vinci", "Galileo", "Copernicus"], "Shakespeare wrote in England about 400 years ago."),
  q(1, "Which Renaissance artist was also a scientist and inventor?", "Leonardo da Vinci", ["Michelangelo only", "Gutenberg", "Luther"], "Leonardo drew machines and the human body."),
  q(1, "What did Galileo build and use to look at the sky?", "a telescope", ["a printing press", "a canoe", "a clock tower"], "He improved the telescope in 1609."),
  q(1, "Which city is the Sistine Chapel in?", "Rome", ["Florence", "Venice", "Paris"], "It is in Vatican City, in Rome."),
  q(2, "Why did artists study anatomy (the human body)?", "To paint and sculpt people more realistically.", ["To become doctors only", "To frighten people", "To avoid art"], "Careful study made figures more lifelike."),
  q(2, "What is a fresco?", "a painting made on wet plaster on a wall", ["a carved statue", "a printed book", "a kind of dome"], "Michelangelo's ceiling is a fresco."),
  q(2, "Which famous mural, painted by Leonardo, shows a meal with Jesus and the apostles?", "The Last Supper", ["Mona Lisa", "David", "The Thinker"], "It is in Milan."),
  q(2, "Why did Gutenberg's press use movable metal type?", "Letters could be reused to print many pages quickly.", ["Letters were glued down", "To avoid using ink", "So only one page could be made"], "Movable type made printing faster and cheaper."),
  q(2, "Which of these buildings is an example of Renaissance architecture?", "a building with a dome and columns inspired by ancient Rome", ["a wooden pagoda", "a Mexica pyramid", "a modern glass tower"], "Architects borrowed ideas from Greek and Roman buildings."),
  q(2, "Who was Nicolaus Copernicus?", "A scholar who said that Earth travels around the Sun.", ["An Italian painter", "A king of England", "A Spanish explorer"], "His book was published in 1543."),
  q(3, "Why was the printing press important for the spread of new scientific ideas?", "Scholars could share their work across Europe with printed books.", ["Books were hidden away", "Scholars stopped writing", "Presses were banned in Europe"], "Printed books helped ideas reach many people."),
  q(3, "The printing press also helped the Protestant Reformation. How?", "Luther's ideas spread quickly in printed pamphlets.", ["It made Church buildings", "It ended the Church", "It stopped people from reading"], "Pamphlets travelled widely."),
  q(3, "How was Renaissance perspective different from earlier flat painting?", "It used lines and size to show distance, so scenes looked three-dimensional.", ["It used only black", "It was only for sculpture", "It removed all shapes"], "Linear perspective used a vanishing point."),
  q(3, "Why might a scientist in the 1500s be careful when sharing a new idea?", "Powerful groups might disagree and punish those who challenged long-held beliefs.", ["There were no scientists", "Ideas were always welcomed", "Paper was banned"], "Galileo was put on trial for his writing."),
  q(3, "Which statement best compares Leonardo's and Michelangelo's work?", "Both used knowledge of the body and nature, but in different art forms and styles.", ["They were the same person", "Neither made art", "They worked only in Japan"], "Leonardo was a painter and inventor; Michelangelo a sculptor, painter and architect."),
  q(3, "Why do we still study Renaissance art and ideas today?", "They shaped how later people thought about art, science and learning.", ["They have no influence", "They are secret", "They ended in 1500"], "Many ideas were built on later."),
];

const RENAISSANCE_ORDER = orderOf(
  "Put these Renaissance-era events in order.",
  "Gutenberg's press (about 1450) came first, then Luther in 1517, Copernicus in 1543 and Galileo's telescope observations in 1610.",
  [
    { id: "gutenberg", label: "Gutenberg's printing press (about 1450)", emoji: "🖨️" },
    { id: "luther", label: "Martin Luther's Ninety-five Theses (1517)", emoji: "📜" },
    { id: "copernicus", label: "Copernicus publishes his Sun-centred model (1543)", emoji: "☀️" },
    { id: "galileo", label: "Galileo observes the moons of Jupiter (1610)", emoji: "🔭" },
  ],
);

// ---------- 8.3 The Spanish and the Aztecs ----------

const AZTEC = [
  q(1, "The Aztec Empire was led by the people who called themselves…", "the Mexica", ["the Inuit", "the Samurai", "the Medici"], "'Aztec' is the name many people use today. The people called themselves Mexica."),
  q(1, "What was the capital city of the Mexica?", "Tenochtitlan", ["Edo", "Florence", "Cuzco"], "It was built on an island in Lake Texcoco."),
  q(1, "What language did the Mexica speak?", "Nahuatl", ["Spanish", "Japanese", "Latin"], "Nahuatl is still spoken by well over a million people in Mexico today."),
  q(1, "Which crop was the most important food in Mexica farming?", "maize (corn)", ["rice", "wheat", "oats"], "Maize was grown with beans and squash."),
  q(2, "How did the Mexica grow food on and around the lake?", "on chinampas, small artificial islands built in shallow water", ["by cutting down all the forests", "with machine tractors", "on mountain glaciers"], "Chinampas were fertile, and farmers could grow several crops a year."),
  q(2, "How did people reach Tenochtitlan from the mainland?", "by causeways and by canoe", ["by train", "by flying machines", "through tunnels only"], "Raised roads called causeways crossed the lake."),
  q(2, "Tenochtitlan had a huge market. What was often used as money there?", "cacao beans", ["gold coins from Spain", "paper bills", "metal coins with a king's face"], "Cacao beans and cloth were used in trade."),
  q(2, "The Triple Alliance was an agreement among which three city-states?", "Tenochtitlan, Texcoco and Tlacopan", ["Venice, Florence and Milan", "Edo, Kyoto and Osaka", "Madrid, Seville and Granada"], "Together they formed the strongest power in central Mexico."),
  q(2, "What was tribute?", "goods or labour paid to a ruler by conquered peoples", ["a kind of sword", "a festival of music", "a type of farm"], "The Mexica collected tribute such as cloth, food and cacao from many peoples."),
  q(2, "Who was Moctezuma II?", "the Mexica ruler when the Spanish arrived", ["a Spanish king", "a samurai", "an Italian painter"], "He led from 1502 until 1520."),
  q(3, "What was a calpulli?", "a neighbourhood or community group in Mexica cities", ["a type of cloth", "a kind of boat", "a Spanish ship"], "Calpultin organized land, education and work for families."),
  q(3, "How did the Mexica society have different roles?", "There were nobles, commoners, merchants, artisans and enslaved people.", ["Everyone had the same job.", "There were only farmers.", "There were only soldiers."], "Social roles shaped daily life, but a person could earn honour through service."),
  q(3, "Why was the pochteca (merchants') network important?", "It linked far-off regions and brought goods and information to Tenochtitlan.", ["It stopped all trade.", "It built the causeways.", "It taught Spanish."], "Long-distance traders also gathered information about other lands."),
  q(3, "Why did some peoples under Mexica rule resent the empire?", "They had to pay tribute and had little say in government.", ["They received free trade goods.", "They were never conquered.", "They ruled Tenochtitlan."], "Resentment of tribute helps explain later alliances with the Spanish."),
  q(3, "The Mexica kept records in books made of folded paper called codices. What did these show?", "pictures and symbols recording history, tribute and calendars", ["only Spanish letters", "machines", "maps of Europe"], "Many were destroyed, but some survive and are studied today."),
  q(1, "Tenochtitlan was built on an island in a…", "lake", ["desert", "glacier", "harbour in Japan"], "Lake Texcoco surrounded the city."),
  q(1, "The Mexica built tall stepped structures. What do we call them today?", "pyramids", ["igloos", "cabins", "castles"], "Temple pyramids stood at the city's centre."),
  q(1, "Which food was made from maize and used for tortillas?", "dough from ground maize", ["rice", "wheat bread", "cheese"], "Maize was a staple food."),
  q(1, "What was cacao used for in Mexica life?", "A drink and a trade good", ["A kind of building stone", "A tool for farming", "A type of boat"], "Cacao beans were valuable."),
  q(1, "Where is Tenochtitlan's ruin today?", "under Mexico City", ["in Japan", "in Italy", "in Alberta"], "The Templo Mayor site is in Mexico City."),
  q(2, "Why was Tenochtitlan's location good for protection?", "It was surrounded by water and linked by causeways that could be guarded.", ["It was on a hill of ice", "It had a moat of sand", "It had no neighbours"], "The lake made the city hard to attack."),
  q(2, "What did the Mexica use to move goods across the lake?", "canoes", ["horses", "wagons with wheels", "trains"], "The Mexica had no draft animals and no wheeled carts."),
  q(2, "What kind of school did many Mexica children attend?", "a calmecac or a telpochcalli", ["a high school", "a ship school", "a monastery in Spain"], "Different schools trained different groups of children."),
  q(2, "Which cities joined with Tenochtitlan in the Triple Alliance?", "Texcoco and Tlacopan", ["Florence and Venice", "Edo and Kyoto", "Madrid and Seville"], "Their leaders shared tribute."),
  q(2, "The Mexica calendar helped plan farming and festivals. What did it track?", "days and seasons", ["only the tides", "only trade", "only wars"], "Calendars were important in many Mesoamerican cultures."),
  q(3, "A market in Tlatelolco was reported to be very large. Why do historians trust the Spanish accounts of it with care?", "The writers were outsiders with their own goals and may have exaggerated.", ["They all agree exactly", "Spanish writers never saw it", "They were Mexica writers"], "Primary sources reflect the writer's point of view."),
  q(3, "How did chinampas support a large city population?", "They produced several crops a year on rich, wet soil.", ["They made roads", "They stopped farming", "They blocked canoes"], "The farms were very productive."),
  q(3, "Why did the Mexica need tribute from other regions?", "To supply food, goods and labour for a growing city and empire.", ["To pay the Spanish", "To send to Japan", "To build the CPR"], "Tribute fed and supplied Tenochtitlan."),
  q(3, "The Mexica empire was made up of many peoples with different languages. What does this suggest about how it held together?", "It relied on alliances, tribute and power rather than shared identity alone.", ["Everyone chose it freely", "It had no leaders", "Everyone spoke Spanish"], "Some peoples were allies, some were conquered."),
  q(3, "Which statement shows respect when we talk about the Mexica today?", "Acknowledge their descendants, their language and their continuing culture.", ["Say they vanished", "Say they are only a legend", "Say they were all the same as other peoples"], "Nahua communities continue in Mexico today."),
];

const SPAIN = [
  q(1, "Which country sent Christopher Columbus on his 1492 voyage?", "Spain", ["Japan", "Mexico", "Canada"], "Queen Isabella and King Ferdinand supported his voyage."),
  q(1, "A conquistador was…", "a Spanish soldier-explorer who sought to conquer lands", ["a Japanese lord", "a Mexica farmer", "an Italian painter"], "Conquistador means 'conqueror' in Spanish."),
  q(1, "Which animal did the Spanish bring to the Americas that changed travel and war?", "the horse", ["the elephant", "the penguin", "the kangaroo"], "Horses were new to the Americas before the Spanish arrived."),
  q(1, "Many Spanish explorers wanted gold, wealth and…", "to spread the Catholic faith", ["to set up Buddhist temples", "to learn Nahuatl", "to find the North Pole"], "Motives were often described as 'God, gold and glory'."),
  q(2, "Which three motives are often used to describe Spanish exploration?", "God, gold and glory", ["peace, farms and trade", "music, art and food", "maps, ships and fish"], "Religion, wealth and fame all mattered to explorers and rulers."),
  q(2, "Why did the Spanish crown support explorers?", "To gain wealth and power, and to spread Christianity.", ["To give land to the Mexica.", "To end all trade.", "To stay inside Spain."], "Rulers expected to gain resources and new territory."),
  q(2, "Spanish soldiers had steel swords, armour and guns. What was one advantage?", "Their weapons could be very effective in battle against forces without them.", ["Steel made them invisible.", "Horses made them smaller.", "Guns could never fire."], "Technology was one factor among many in the conquest."),
  q(2, "What is meant by the Columbian Exchange?", "the movement of plants, animals, people and diseases between the Americas and the Old World", ["a trade of paintings", "a sports competition", "a Spanish election"], "Contact after 1492 changed the diets and lives of people on both sides of the Atlantic."),
  q(2, "In Spain in the 1500s, who had the most authority?", "the monarch and the Catholic Church", ["the merchants only", "the artists", "the farmers"], "Spain was a monarchy closely tied to the Church."),
  q(3, "How did the worldview of many Spanish people in the 1500s differ from the Mexica worldview?", "They had different beliefs, languages, governments and ideas of land and wealth.", ["They were exactly the same.", "Neither had any beliefs.", "They shared the same language."], "Differences in worldview led to misunderstanding and conflict."),
  q(3, "What is ethnocentrism?", "judging other cultures only by the standards of your own", ["loving all cultures equally", "avoiding all trade", "studying only maps"], "Some Europeans believed their ways were superior, which shaped how they treated Indigenous peoples."),
  q(3, "Why do historians compare the viewpoints of the Spanish and the Mexica?", "To understand how each side saw the same events in different ways.", ["To decide who is better.", "To ignore one side.", "To avoid learning history."], "Looking at several perspectives gives a fuller picture."),
  q(3, "Which of these is an effect of the Columbian Exchange on Europe?", "Foods like potatoes, tomatoes and maize were added to farming and diets.", ["Europe lost all its farms.", "Europe stopped trade.", "Europeans gave up cooking."], "Crops from the Americas changed what people could grow and eat."),
];

const EXCHANGE_SORT: SortSet = {
  prompt: "Which way did each travel in the Columbian Exchange?",
  hint: "Maize, potatoes, tomatoes and cacao were first grown in the Americas. Horses, wheat, cattle and pigs came across the Atlantic with Europeans.",
  bins: [
    { id: "toEurope", label: "From the Americas to Europe", emoji: "🌽" },
    { id: "toAmericas", label: "From Europe to the Americas", emoji: "🐎" },
  ],
  items: [
    { label: "maize (corn)", emoji: "🌽", bin: "toEurope" },
    { label: "potatoes", emoji: "🥔", bin: "toEurope" },
    { label: "tomatoes", emoji: "🍅", bin: "toEurope" },
    { label: "cacao (chocolate)", emoji: "🍫", bin: "toEurope" },
    { label: "horses", emoji: "🐎", bin: "toAmericas" },
    { label: "wheat", emoji: "🌾", bin: "toAmericas" },
    { label: "cattle", emoji: "🐄", bin: "toAmericas" },
    { label: "pigs", emoji: "🐖", bin: "toAmericas" },
  ],
};

const CONQUEST = [
  q(1, "Which Spanish leader arrived on the coast of Mexico in 1519?", "Hernán Cortés", ["Christopher Columbus", "Moctezuma", "Tokugawa Ieyasu"], "Cortés landed near what is now Veracruz."),
  q(1, "What disease, brought by Europeans, killed very many people in the Americas?", "smallpox", ["a cold only", "no disease", "scurvy"], "People in the Americas had never been exposed to it, so it spread quickly."),
  q(1, "In 1521, the Spanish and their allies took control of…", "Tenochtitlan", ["Edo", "Florence", "Madrid"], "Tenochtitlan fell after a long siege."),
  q(1, "What city was built on the ruins of Tenochtitlan?", "Mexico City", ["Madrid", "Lima", "Toronto"], "Mexico City is built on the lake bed where Tenochtitlan stood."),
  q(2, "Which peoples became important allies of Cortés?", "the Tlaxcalans and other peoples who opposed Mexica rule", ["the Japanese", "the Medici", "the Vikings"], "Many peoples hoped to end the tribute they paid to the Mexica."),
  q(2, "Who was Malintzin (also called Doña Marina or Malinche)?", "a Nahua woman who translated for Cortés", ["a Spanish queen", "a Mexica merchant", "a samurai"], "Her ability to speak several languages made her an important figure."),
  q(2, "Why was it hard for the Mexica to fight the Spanish after 1520?", "A smallpox epidemic killed many people, including leaders.", ["They had no weapons at all.", "They were all away at sea.", "They agreed with the Spanish."], "Disease weakened the city before the final siege."),
  q(2, "What does 'siege' mean?", "surrounding a city to cut off its supplies and force it to give up", ["a festival", "a sea voyage", "a trade agreement"], "The Spanish and their allies surrounded Tenochtitlan in 1521."),
  q(2, "Who was the last Mexica leader at the fall of Tenochtitlan?", "Cuauhtémoc", ["Moctezuma II", "Cortés", "Columbus"], "He led the defence and surrendered in August 1521."),
  q(2, "Which area did Spain name after it took control?", "New Spain", ["New France", "New Japan", "New Italy"], "New Spain was ruled from Mexico City."),
  q(3, "Many factors helped the Spanish succeed. Which statement is the most complete?", "Allies, disease, weapons and divisions among peoples all played a part.", ["Only weapons mattered.", "Only luck mattered.", "Only Cortés mattered."], "Historians point to several causes working together."),
  q(3, "Why were Indigenous allies so important to the Spanish campaign?", "Thousands of allied warriors fought alongside the Spanish.", ["They fought against the Spanish only.", "They were not involved at all.", "They sailed the ships."], "The conquest was not just Spanish against Mexica; many peoples took sides."),
  q(3, "What happened to the people and culture of the Mexica after the conquest?", "Nahua peoples and the Nahuatl language continue today.", ["Everyone disappeared.", "Nahuatl is no longer spoken.", "Mexico City was never rebuilt."], "Many descendants live in Mexico today and keep their language and traditions alive."),
  q(3, "How could the Spanish and Mexica worldviews have caused conflict?", "They differed on rule, land, religion and what a conquest meant.", ["They shared everything.", "Neither had leaders.", "Neither wanted trade."], "Different values led to different expectations."),
  q(1, "In what year did the Spanish and their allies take Tenochtitlan?", "1521", ["1067", "1776", "1905"], "The siege lasted about 75 days."),
  q(1, "Which country did Cortés sail from?", "Spain", ["Japan", "Canada", "Italy"], "He sailed from Cuba on behalf of Spain."),
  q(1, "What did Spain rename the land it ruled in Mexico?", "New Spain", ["New England", "New Italy", "New Japan"], "Mexico City became its capital."),
  q(1, "What animal did the Spanish bring that the Mexica had not seen?", "horses", ["bison", "llamas", "turkeys"], "The Spanish also brought cattle and pigs."),
  q(2, "The Spanish brought diseases such as smallpox and measles. Why were they so harmful to Indigenous people?", "They had no earlier exposure and little immunity.", ["The diseases were not real", "Nobody was sick", "The Spanish carried medicine for all"], "Epidemics killed a large share of the population."),
  q(2, "Why did Moctezuma meet with Cortés in 1519?", "He welcomed the strangers as guests and wanted to learn about them.", ["He wanted to give up the city on the spot", "He was already conquered", "He was in Spain"], "The meeting happened in Tenochtitlan in November 1519."),
  q(2, "What does 'conquest' mean?", "taking control of a place and its people by force", ["trading goods", "visiting for a holiday", "building a school"], "Conquest changes who governs a place."),
  q(2, "Which of these was a motive for Spanish explorers?", "Gold, power and spreading Christianity", ["Planting trees", "Learning Nahuatl", "Setting up a school for the Mexica"], "Spanish leaders wanted wealth and glory."),
  q(2, "What is a colony?", "a territory ruled by another country", ["a school", "a type of farm", "a trade fair"], "New Spain was a colony."),
  q(2, "What happened to many Mexica temples and buildings after 1521?", "Many were torn down and new buildings were put on top.", ["They were preserved untouched", "They were moved to Spain", "They were sold"], "Mexico City was built on top of the ruins."),
  q(3, "Why do many historians say the conquest was not simply 'Spain versus the Mexica'?", "Many Indigenous peoples took part on different sides for their own reasons.", ["Only Spanish people fought", "The Mexica had no opponents", "Nobody took sides"], "Alliances were crucial."),
  q(3, "How did Spanish rule change the way land and labour were organized?", "Systems such as encomienda made Indigenous people work for Spanish settlers.", ["Everyone was paid well", "The land was returned", "The work ended"], "These systems caused great hardship."),
  q(3, "Which statement shows that Mexica culture survived?", "Nahuatl is still spoken and many traditions continue today.", ["All books were saved", "Nobody speaks Nahuatl", "Nothing is known about the Mexica"], "Culture and language continue in communities."),
  q(3, "Why are the codices written after the conquest, such as the Florentine Codex, valuable but need careful reading?", "They record Nahua knowledge, but a Spanish friar directed the project.", ["They were written before the Spanish arrived", "They only show Spanish ideas", "They were not written by anyone"], "Nahua authors and a Spanish priest worked together."),
  q(3, "Malintzin has been described in different ways by different people. What does this show?", "People can judge the same historical figure differently depending on perspective.", ["There is only one correct view", "She never existed", "Nobody wrote about her"], "Historians weigh evidence from many sources."),
  q(3, "Why was Cuauhtémoc's surrender in 1521 important?", "It marked the end of Mexica rule in Tenochtitlan.", ["It started the Renaissance", "It created Japan", "It ended the Black Death"], "The city fell on August 13, 1521."),
  q(3, "Why do some people say the Columbian Exchange had both benefits and harms?", "New foods and animals spread, but disease and forced labour caused terrible losses.", ["It had only benefits", "It had no effects", "It only affected Europe"], "Plants and animals moved across oceans, and so did disease."),
];

const CONQUEST_ORDER = orderOf(
  "Put the events of the Spanish arrival in Mexico in order.",
  "Cortés landed in 1519 and entered Tenochtitlan that autumn. The Spanish were forced out in 1520, and Tenochtitlan fell in 1521.",
  [
    { id: "landing", label: "Cortés lands on the coast of Mexico (1519)", emoji: "⛵" },
    { id: "enters", label: "The Spanish enter Tenochtitlan (1519)", emoji: "🏙️" },
    { id: "flee", label: "The Spanish are forced out of the city (1520)", emoji: "🌧️" },
    { id: "fall", label: "Tenochtitlan falls after a siege (1521)", emoji: "🛡️" },
  ],
);

const WORLDVIEWS = [
  q(1, "A worldview is…", "the way a group of people understands the world and what matters", ["a type of map", "a way to paint", "a tool for farming"], "Worldviews are shaped by beliefs, values, land and history."),
  q(1, "A primary source is…", "created by someone who was there at the time", ["written long after by someone else", "a made-up story", "a textbook summary"], "Letters, diaries and objects from the time are primary sources."),
  q(1, "A perspective is…", "a point of view", ["a kind of ship", "a tool", "a law"], "People can see the same event in different ways."),
  q(2, "Which is an example of a secondary source?", "a textbook about the Renaissance", ["a letter written in 1520", "a painting made in 1500", "a tool from long ago"], "Secondary sources are written later by people who study the past."),
  q(2, "A letter written by Cortés about the conquest shows mostly…", "the Spanish point of view", ["the Mexica point of view", "no point of view", "the point of view of a Japanese shogun"], "A writer's background and goals shape how they describe events."),
  q(2, "Why is it important to look for Mexica and Nahua accounts as well as Spanish ones?", "To hear more than one side of the story.", ["Because Spanish accounts are never useful.", "Because Nahua accounts are always perfect.", "To avoid reading."], "Historians read many sources to understand different perspectives."),
  q(2, "A society that welcomes new ideas while keeping its own traditions is…", "adapting", ["staying isolated", "disappearing", "conquering"], "Japan's Meiji leaders are an example."),
  q(2, "A society that limits contact with others is…", "isolating itself", ["adapting all the time", "building a delta", "expanding quickly"], "Tokugawa Japan limited contact with other countries for about 200 years."),
  q(3, "Why do different people describe the same event differently?", "Their experiences, beliefs and goals shape what they notice and say.", ["They never see the event.", "Events are not real.", "They all have the same view."], "A person's worldview influences how they tell the past."),
  q(3, "Which question helps you judge a historical source?", "Who made it, when, and why?", ["What colour is the paper?", "How long is it?", "Is it famous?"], "Knowing who created a source and why helps you decide how to use it."),
  q(3, "Both Renaissance Italy and Tokugawa Japan had cities that grew rich. What does this show?", "Different societies can develop trade and the arts in different ways.", ["Every society is the same.", "Only Europe had cities.", "Only Japan had art."], "Comparing societies reveals both similarities and differences."),
  q(3, "A museum shows Mexica objects and uses the name 'Nahua' as well as 'Aztec'. Why?", "Using names people use for themselves is more respectful and accurate.", ["Names do not matter.", "To confuse visitors.", "To hide the history."], "Naming peoples carefully shows respect."),
  q(3, "Why do historians avoid saying one civilization was simply 'better' than another?", "Societies have different values and circumstances, so judging them by one standard can be unfair.", ["Because all history is false.", "Because only dates matter.", "Because they cannot read."], "Understanding how people saw their world helps explain their choices."),
  q(1, "Which is a primary source from the Renaissance?", "a letter written by Galileo", ["a modern textbook", "a documentary made last year", "a classroom poster"], "Primary sources were made at the time."),
  q(1, "Which is a secondary source?", "an encyclopedia article about Tokugawa Japan", ["a shogun's decree", "a samurai's diary", "a woodblock print from 1800"], "Secondary sources are made later by people who study the past."),
  q(1, "What does 'bias' mean?", "a leaning toward one side", ["a kind of map", "a trade", "a law"], "Everyone has a point of view, and it affects what they write."),
  q(1, "A timeline helps us see…", "the order of events", ["the weather", "the height of mountains", "the size of cities"], "Timelines place events in order."),
  q(2, "A Spanish chronicler and a Nahua author describe the fall of Tenochtitlan differently. What is a good response?", "Compare both accounts and ask who wrote them and why.", ["Trust only one", "Ignore both", "Pick the shorter one"], "Looking at several sources gives a fuller picture."),
  q(2, "What is an artifact?", "an object made by people in the past", ["a kind of storm", "an animal", "a place name"], "A tool, coin or pot can be an artifact."),
  q(2, "How is a map from 1500 different from a map today?", "It can show what people believed and knew at that time, and it may have errors.", ["It is always accurate", "It is made by satellite", "It shows modern roads"], "Old maps are useful for seeing how people saw the world."),
  q(2, "Japan during the Meiji era adopted new technology but kept many traditions. This is an example of…", "adaptation", ["isolation", "conquest", "tribute"], "Adapting means changing to meet new situations."),
  q(2, "A museum label gives a date, a place and who made an object. Why are these details useful?", "They help judge the source and place it in time.", ["They are decoration", "They hide the object", "They make the object older"], "Details about a source help us interpret it."),
  q(3, "Which statement is a generalization that may be unfair?", "All people in that society thought the same way.", ["Some people in the society disagreed.", "Many farmers lived in villages.", "The ruler had a large army."], "Words like 'all' often hide differences."),
  q(3, "A historian compares Tokugawa Japan's isolation with Renaissance Italy's trade. What is she doing?", "Comparing how two societies were connected to the world.", ["Making a mistake", "Writing fiction", "Ignoring evidence"], "Comparison helps show similarities and differences."),
  q(3, "What question helps you notice a bias in a source?", "What might the writer gain from telling it this way?", ["How many pages is it?", "What colour is the cover?", "Is it in a library?"], "Motives can shape the story."),
  q(3, "A student says the Renaissance was 'better' than the Tokugawa period. How could she improve her claim?", "Give evidence and explain by what measure, such as art, trade or science.", ["Say it again louder", "Skip the evidence", "Use only opinions"], "Good claims have criteria and evidence."),
  q(3, "Why is it important to learn about First Nations, Métis and Inuit perspectives alongside other world histories?", "Many different peoples shaped history, and their views add to a fuller picture.", ["They are not part of history", "Only one view counts", "They only matter in the future"], "Learning from many worldviews builds understanding."),
  q(3, "Which of these would be most useful for learning about everyday life in Tokugawa Edo?", "Prints, diaries and records from the time", ["A modern video game", "A cartoon", "A single legend"], "Evidence from the time is best."),
];

export const units: Unit[] = [
  {
    id: "japan-land-values-ab",
    title: "Japan: Land, Beliefs & Values",
    emoji: "🗾",
    blurb: "Islands, mountains and the ideas that shaped Japan",
    standards: ab("8.1", "Japan's geography, and the beliefs and values (Shinto, Buddhism, Confucian ideas) that shaped its worldview"),
    parentNote: "Japan's islands and mountains, its farming and fishing, and the Shinto, Buddhist and Confucian ideas that helped shape how people lived and what they valued.",
    generate: partsPlus({ items: JAPAN_LAND }),
  },
  {
    id: "japan-tokugawa-ab",
    title: "Tokugawa Japan & Isolation",
    emoji: "🏯",
    blurb: "Shoguns, samurai and a country that closed its doors",
    standards: ab("8.1", "the Tokugawa shogunate, the feudal class system, and Japan's policy of isolation"),
    parentNote: "How Japan was ruled by shoguns for about 250 years, how its class system worked, why the government limited contact with other countries, and what life in Edo was like.",
    generate: partsPlus({ items: TOKUGAWA, orders: [TOKUGAWA_ORDER] }),
  },
  {
    id: "japan-meiji-ab",
    title: "From Isolation to Adaptation",
    emoji: "🚆",
    blurb: "Perry, the Meiji Restoration and a changing Japan",
    standards: ab("8.1", "the end of isolation, the Meiji Restoration and how Japan adapted to new influences"),
    parentNote: "How American ships arrived in 1853, how Japan opened to the world, and how the Meiji government built railways, schools and industry while keeping parts of its own culture.",
    generate: partsPlus({ items: MEIJI, sorts: [PERIOD_SORT] }),
  },
  {
    id: "renaissance-origins-ab",
    title: "Where the Renaissance Began",
    emoji: "🏛️",
    blurb: "Italian city-states, wealth, patrons and humanism",
    standards: ab("8.2", "the origins of the Renaissance in Italy and the ideas of humanism and individualism"),
    parentNote: "Why Italian city-states such as Florence became centres of wealth and learning, what patrons and humanists did, and how the Renaissance worldview differed from the Middle Ages.",
    generate: partsPlus({ items: RENAISSANCE }),
  },
  {
    id: "renaissance-art-ideas-ab",
    title: "Renaissance Art, Printing & Science",
    emoji: "🎨",
    blurb: "Leonardo, Michelangelo, Gutenberg and Galileo",
    standards: ab("8.2", "Renaissance art and architecture, the printing press and the new scientific thinking"),
    parentNote: "Famous Renaissance artists and builders, how the printing press spread ideas, and how astronomers and scientists began to test old ideas with observation.",
    generate: partsPlus({ items: RENAISSANCE_ART, orders: [RENAISSANCE_ORDER] }),
  },
  {
    id: "aztec-empire-ab",
    title: "The Mexica & Tenochtitlan",
    emoji: "🌽",
    blurb: "A great city on a lake and the people who built it",
    standards: ab("8.3", "the Mexica (Aztec) society, the city of Tenochtitlan, farming, trade, tribute and government"),
    parentNote: "How the Mexica built Tenochtitlan on an island in Lake Texcoco, grew food on chinampas, traded and collected tribute, and how Nahua peoples and the Nahuatl language continue today.",
    generate: partsPlus({ items: AZTEC }),
  },
  {
    id: "spain-worldview-ab",
    title: "Spain & the Age of Exploration",
    emoji: "⛵",
    blurb: "Why Spanish explorers crossed the Atlantic",
    standards: ab("8.3", "the Spanish worldview and motives for exploration, and the Columbian Exchange"),
    parentNote: "What motivated Spain's rulers and explorers (faith, wealth and glory), the technology they brought, and how plants, animals and diseases crossed the Atlantic in both directions.",
    generate: partsPlus({ items: SPAIN, sorts: [EXCHANGE_SORT] }),
  },
  {
    id: "conquest-contact-ab",
    title: "Contact & Conquest in Mexico",
    emoji: "🛡️",
    blurb: "Cortés, allies, disease and the fall of Tenochtitlan",
    standards: ab("8.3", "the arrival of the Spanish, alliances, disease, the fall of Tenochtitlan, and the lasting effects of the conflict"),
    parentNote: "How the Spanish and many Indigenous allies came into conflict with the Mexica between 1519 and 1521, why the outcome had several causes, and how Nahua peoples and culture continue today.",
    generate: partsPlus({ items: CONQUEST, orders: [CONQUEST_ORDER] }),
  },
  {
    id: "worldviews-skills-ab",
    title: "Worldviews & Historical Sources",
    emoji: "🧭",
    blurb: "Comparing perspectives and judging sources",
    standards: ab("8.1; 8.2; 8.3", "comparing worldviews and perspectives, adaptation and isolation, and using primary and secondary sources"),
    parentNote: "What a worldview is, how to tell primary from secondary sources, and how to read a source for point of view. Applies to all three Grade 8 case studies: Japan, Renaissance Europe and the Spanish and Mexica.",
    generate: partsPlus({ items: WORLDVIEWS }),
  },
];
