import { bankUnit, type Q } from "../own";

// Grade 1 social studies, Connecting and Belonging: identity and family, needs and wants, getting along,
// caring for places, the wider world, and the skills and values outcomes (S and V codes).

const FAMILY: Q[] = [
  ["Which is a group you can belong to?", "a soccer team", ["a rainy day", "a rock"], "Teams, clubs and families are groups."],
  ["Which group might you belong to at school?", "your class", ["a cloud", "a sidewalk"], "Your class is a group."],
  ["Your family speaks Ukrainian at home. This is a…", "language you share", ["weather report", "number"], "Languages are part of a community."],
  ["Which is a way families show who they are?", "food, music and stories", ["only the weather", "only cars"], "Families share culture in many ways."],
  ["Which is a family tradition?", "a special meal each year", ["a rainy afternoon", "a lost sock"], "A tradition is done again and again."],
  ["A celebration is…", "a special time people enjoy together", ["a quiet nap", "a lost glove"], "Celebrations bring people together."],
  ["Who are your grandparents?", "your parents' parents", ["your pets", "your neighbours"], "Grandparents are the parents of your parents."],
  ["Who is your aunt?", "your parent's sister", ["your teacher", "your cousin's dog"], "An aunt is a parent's sister."],
  ["Who is your uncle?", "your parent's brother", ["your friend", "your pet"], "An uncle is a parent's brother."],
  ["Who comes before your parents in your family?", "your grandparents", ["your friends", "your cousins"], "Grandparents are an older generation."],
  ["A story your grandparent tells you about long ago helps you…", "learn about the past", ["lose your lunch", "run faster"], "Stories connect us to the past."],
  ["Why do we listen to stories from older people?", "We learn from them", ["They are loud", "They want us to leave"], "Stories of the past teach us about now."],
  ["Which is a way to show respect for someone's celebration?", "Listen and ask kindly", ["Laugh at it", "Say it is silly"], "We respect traditions of others."],
  ["A classmate celebrates differently from you. You should…", "be kind and curious", ["tease them", "ignore them"], "Respect the celebrations of others."],
  ["Which shows you value your family's traditions?", "taking part and sharing with pride", ["hiding them", "saying they are bad"], "Value your own stories and traditions."],
  ["Some people belong to a First Nation, Métis or Inuit community. This is a…", "community with its own culture", ["kind of weather", "toy"], "Many communities have their own cultures and languages."],
  ["Some people belong to a francophone community. They speak…", "French", ["Cree", "only English"], "Francophone means French-speaking."],
  ["Manitoba has a French community called Saint-Boniface. People there speak…", "French", ["Greek", "only Latin"], "Saint-Boniface is a francophone area of Winnipeg."],
  ["Many French families in Manitoba have traditions like…", "music and stories in French", ["only winter sports", "no music"], "Francophone traditions connect families to earlier generations."],
  ["In Manitoba, some First Nations speak languages like…", "Cree and Ojibwe", ["only Latin", "none at all"], "Many First Nations languages are spoken today."],
  ["Who in your family belongs to the same group as you?", "your family members", ["a stranger far away", "a pencil"], "Families are one kind of group."],
  ["Which sentence is true?", "People belong to many groups.", ["People belong to only one group.", "Groups are always big."], "You can be in a family, class and team.", true],
  ["Why are stories of the past important?", "We learn about our families and communities", ["They are not true", "They are for adults only"], "They help us understand the present.", true],
  ["A photo of your grandparents as children helps you…", "see the past", ["hear the weather", "taste soup"], "Photos are clues about the past.", true],
  ["Which is a good way to learn about a family tradition?", "Ask a family member", ["Guess alone", "Ignore it"], "People can tell us.", true],
  ["Which shows respect for a classmate's culture?", "Learn their words for “hello”", ["Make fun of their language", "Say theirs is wrong"], "Respect shows in what we do.", true],
  ["“Bonjour” is how many French speakers say…", "hello", ["goodbye", "thank you"], "Bonjour means hello.", true],
];

const NEEDS: Q[] = [
  ["Which is a need?", "water", ["a video game", "a toy robot"], "We need water to live."],
  ["Which is a need?", "food", ["candy only", "a new bike"], "Everyone needs food."],
  ["Which is a want?", "a new toy", ["a home", "clean water"], "A toy is nice but not a need."],
  ["Which is a need?", "a safe place to live", ["a pet robot", "a fancy hat"], "Shelter is a need."],
  ["Which is a want?", "a video game", ["healthy food", "warm clothes in winter"], "Games are fun but we can live without them."],
  ["Which is a need in a Manitoba winter?", "a warm coat", ["sunglasses for a beach", "a sandcastle kit"], "We need warm clothing when it is cold."],
  ["Which is a want?", "a sparkly sticker", ["a doctor visit when sick", "clean air"], "Stickers are extras."],
  ["Which is a need?", "love and care", ["a big TV", "a skateboard"], "Everyone needs to be cared for."],
  ["Needs are things we…", "must have to live and be well", ["only wish for", "can always skip"], "We need them every day."],
  ["Wants are things we…", "would like but can live without", ["must have to live", "cannot do without"], "Wants are extras."],
  ["Your friend wants a toy and you want a book. This is…", "okay; people have different wants", ["wrong", "a rule"], "We can respect different wants."],
  ["Your friend needs help with a lost mitten. What can you do?", "Help look for it", ["Laugh", "Hide it"], "We care about others' needs."],
  ["A commercial shows a toy and says, “Everyone needs one!” Is the toy a need?", "No, it is a want", ["Yes, always", "It is food"], "Ads can make us feel we need things."],
  ["What is an advertisement?", "something that tries to make you want a product", ["a bedtime story", "a map"], "Ads are on TV, signs and online."],
  ["A TV show has a cartoon cereal. After watching you want the cereal. Why?", "The show made it look fun", ["Cereal grows in the sky", "You are hungry for tires"], "Media can influence what we want."],
  ["A bike ad shows kids having fun. Does it show…", "something that wants us to buy it", ["homework", "a library"], "Ads try to get us to want things."],
  ["How can you decide if you really need something?", "Ask if you can live without it", ["Buy it fast", "Hide it"], "Needs help us live and be well."],
  ["A toy is yours. How should you treat it?", "Take care of it", ["Throw it away", "Break it"], "Caring for property is a good habit."],
  ["After you play with a game, you…", "put it away carefully", ["leave it in the rain", "stomp on it"], "Care for what is yours."],
  ["A classmate lends you a pencil. You should…", "return it and say thank you", ["keep it", "break it"], "Respect others' property."],
  ["Is it okay to take a friend's toy without asking?", "No", ["Yes, always", "Yes, if it's red"], "Ask first.", true],
  ["You break a library book by accident. What is a good thing to do?", "Tell the adult", ["Hide it", "Blame someone"], "Be honest and responsible.", true],
  ["You and a friend want different snacks. A kind way is to…", "take turns choosing", ["grab it", "say theirs is bad"], "Respect differences in wants.", true],
  ["Which is a want that many people enjoy?", "a trip to a park", ["breathing", "water"], "Fun things are wants.", true],
  ["Families often must choose between wants. Why?", "money and time are limited", ["magic", "weather only"], "People can't have everything.", true],
  ["A school has cubbies for coats. They help us…", "take care of our things", ["lose our things", "hurt our things"], "Storage protects belongings.", true],
  ["Needs for every child in the world include…", "food, water and a safe home", ["a phone", "a pool"], "All children have these needs.", true],
];

const TOGETHER: Q[] = [
  ["You see a classmate sitting alone. What can you do?", "Invite them to play", ["Walk away", "Laugh"], "Kind actions make friends."],
  ["How can you share a space with others?", "Take turns and make room", ["Take it all", "Push others"], "Cooperation shares spaces."],
  ["Two children want the same book. A fair idea is…", "take turns", ["grab it", "hide it"], "Seek agreement."],
  ["A group is building a tower. How can you help?", "Do your part and listen", ["Knock it down", "Walk away"], "Help the group."],
  ["Which is a way to work together?", "Share the jobs", ["Do nothing", "Take all the jobs"], "Everyone has a job to do."],
  ["When you play a game, you should consider…", "what others need and like", ["only yourself", "nothing"], "Think about others."],
  ["A new classmate does not know the game. What can you do?", "Teach them the rules", ["Say they are bad", "Stop the game"], "Include others."],
  ["Which sentence is respectful?", "May I please have a turn?", ["Give me that!", "You can't play."], "Polite words show respect."],
  ["A classmate's idea is different from yours. What is respectful?", "Listen to their idea", ["Tell them it's bad", "Cover your ears"], "We listen."],
  ["The rule says to walk in the hall. Why?", "So nobody gets hurt", ["To be slow", "No reason"], "Rules keep us safe."],
  ["A rule at school helps us…", "feel safe and fair", ["have no friends", "make a mess"], "Rules help everyone."],
  ["Why do we have rules in a community?", "To keep people safe and treat people fairly", ["To be boring", "For no reason"], "Rules and laws help."],
  ["Who makes decisions in your family?", "Often adults, with input from the family", ["Nobody", "A stranger"], "Families make decisions together."],
  ["A class votes on a game. This is an example of…", "making a decision together", ["breaking a rule", "being lost"], "Voting is a way to decide."],
  ["Which is a decision you make every day?", "what to wear", ["the weather", "your birthday"], "You make many choices."],
  ["You chose to share your crayons. What happens?", "Your friend feels happy", ["The crayons vanish", "Nothing at all"], "Our choices affect others."],
  ["You left your toys on the floor. What might happen?", "Someone could trip", ["They tidy themselves", "They fly away"], "Actions have consequences."],
  ["You said unkind words. What might happen?", "A friend feels hurt", ["They laugh at the weather", "Nothing ever"], "Words matter."],
  ["Two children argue. A peaceful way to solve it is to…", "talk calmly and listen", ["yell", "hit"], "Peaceful problem solving."],
  ["You and a friend disagree. You can say…", "Let's find a plan that works for both", ["I always win", "You are bad"], "Work it out peacefully."],
  ["How can you help a friend who is sad?", "Be kind and listen", ["Tease them", "Ignore them"], "Relationships matter."],
  ["Friends and family are important because they…", "care for us and we care for them", ["leave us alone", "are the same as us"], "Relationships are important.", true],
  ["Your class has people of many backgrounds. This is…", "something to appreciate", ["a problem", "a secret"], "Diversity makes communities rich.", true],
  ["A classmate is learning English. A kind action is to…", "be patient and friendly", ["laugh at them", "leave them out"], "Value people who are different from us.", true],
  ["You want to help in your class. You can…", "tidy up or hand out papers", ["break things", "hide supplies"], "Contribute to the group.", true],
  ["Why do we tell the truth when a mistake happens?", "It builds trust", ["It is boring", "It starts fights"], "Trust matters in a group.", true],
  ["How can you tell your friend you disagree kindly?", "I see it a bit differently.", ["You are wrong!", "That's dumb."], "Use kind words.", true],
  ["Many First Nations have traditional laws that guide how people live. We should…", "respect them", ["laugh at them", "ignore them"], "Respect the laws of communities.", true],
];

const PLACES: Q[] = [
  ["Your home address tells…", "where your home is", ["what you eat", "your age"], "An address names the street and number."],
  ["Which is part of an address?", "a street name", ["a favourite colour", "a pet name"], "Addresses have numbers and street names."],
  ["Which describes where your home is?", "near the park", ["very sunny", "very tasty"], "Use landmarks like parks."],
  ["Your home is across from the school. This tells…", "its relative location", ["its colour", "its price"], "Relative terms describe where things are."],
  ["Which word describes location?", "beside", ["quickly", "loudly"], "Beside tells where."],
  ["Which word describes location?", "behind", ["happily", "quietly"], "Behind tells where."],
  ["The library is next to the school. The school is…", "next to the library", ["far from the library", "on the moon"], "Next to goes both ways."],
  ["A map uses pictures and symbols to show…", "a place", ["a taste", "a sound"], "Maps show places from above."],
  ["A map of your classroom shows…", "where things are", ["what you ate", "the weather"], "Classroom maps help find things."],
  ["On a map of your room, the bed is shown as a…", "symbol", ["person", "song"], "Maps use symbols."],
  ["To make a simple map of your room, you could first…", "draw the walls and door", ["add the roof", "draw the sky"], "Start with the outline."],
  ["Which helps you read a map?", "a key", ["a hat", "a boot"], "A map key explains the symbols."],
  ["A landmark is…", "a place that is easy to recognize", ["a kind of cloud", "a game"], "A tall tower or a park can be a landmark."],
  ["The Golden Boy sits on top of the Manitoba Legislative Building in…", "Winnipeg", ["Brandon", "Churchill"], "It is a famous landmark in Winnipeg."],
  ["The Forks in Winnipeg is where two rivers meet. They are the Red River and the…", "Assiniboine River", ["Nile River", "Thames River"], "The Forks has been a meeting place for a very long time."],
  ["The Forks has long been a meeting place for…", "Indigenous peoples", ["only visitors from space", "nobody"], "People gathered there for thousands of years, and people still gather there."],
  ["Which landmark is in Manitoba?", "Lake Winnipeg", ["Niagara Falls", "Mount Everest"], "Lake Winnipeg is a very large lake in Manitoba."],
  ["Churchill, Manitoba is a town famous for watching…", "polar bears", ["penguins", "kangaroos"], "Polar bears gather near Churchill."],
  ["Which part of Winnipeg is the heart of Manitoba's French community?", "Saint-Boniface", ["Churchill", "Brandon"], "Saint-Boniface is a francophone area of Winnipeg.", true],
  ["Why is nature special to us?", "It gives us air, water and beauty", ["It is boring", "It is only for adults"], "Nature gives many benefits."],
  ["Which is a way we enjoy nature?", "go for a walk", ["pull up all the plants", "shout at trees"], "Time in nature can be calming."],
  ["Many Indigenous peoples have a special relationship with the land, which they…", "take care of and respect", ["pay no attention to", "dislike"], "Their relationship with nature is important and ongoing."],
  ["You see litter in the park. What should you do?", "Put it in a garbage or recycling bin", ["Leave it", "Throw more"], "Look after our community places."],
  ["Which is a good way to respect a park?", "Use the bins for garbage", ["Draw on the benches", "Pick all the flowers"], "Respect places in the community."],
  ["Which helps the environment?", "turn off lights you are not using", ["leave the tap running", "drop garbage"], "Small choices help.", true],
  ["Which action shows care for nature at school?", "Recycling paper", ["Wasting paper", "Breaking branches"], "Care for the environment.", true],
  ["Not littering helps the community by…", "keeping places clean and safe", ["making more mess", "hiding signs"], "Clean spaces are for everyone.", true],
  ["On a map, up is often shown as…", "north", ["the bus", "the road"], "Many maps have north at the top.", true],
];

const WORLD: Q[] = [
  ["Do children in all countries need food and water?", "Yes", ["No", "Only in Canada"], "People everywhere have similar needs."],
  ["Do families in other places love and care for each other?", "Yes, like families here", ["No, never", "Only on holidays"], "People all over the world have similar relationships."],
  ["Which do all children in the world need?", "a safe home", ["a trampoline", "a phone"], "Every child needs safety."],
  ["Which is something all people around the world need?", "friendship and care", ["a boat", "snow"], "People everywhere need relationships."],
  ["People around the world may speak different…", "languages", ["moons", "mountains"], "There are many languages."],
  ["Is it true that children everywhere like to play?", "Yes", ["No, never", "Only at night"], "Play is shared everywhere."],
  ["A pen pal in another country is a…", "connection to a place far away", ["lost shoe", "kind of cloud"], "Letters can link you to people elsewhere."],
  ["Which can connect you to someone in another country?", "a video call", ["a rock", "a puddle"], "Technology connects people."],
  ["Your cousin lives in another country. This is a…", "connection with another place", ["mystery", "a mistake"], "Family can connect us to the world."],
  ["Your friend's family comes from far away. You can…", "ask about where they are from", ["tease them", "ignore them"], "Learn about others."],
  ["Which food might come from another place and be eaten in Canada?", "bananas", ["snow", "clouds"], "Many foods travel here from other places."],
  ["When there is a flood far away and people need help, we can…", "give to a trusted charity", ["laugh", "forget them"], "Helping others around the world is kind."],
  ["UNICEF helps children in many places. This is an example of…", "caring about others around the world", ["a toy brand", "a school game"], "Groups work to help children everywhere."],
  ["Some schools send a toy or a card to help others far away. This is…", "being kind to people elsewhere", ["a mistake", "a game"], "Consider others' needs."],
  ["A Project Love in a school helps…", "people in other communities", ["only one child", "no one"], "Schools can help far away."],
  ["Why is it good to care about people elsewhere?", "We share one world", ["It is a rule only", "It makes noise"], "We are connected.", true],
  ["Children in a different place may eat different food but still need…", "food", ["jewellery", "trophies"], "Needs are the same.", true],
  ["Which sentence is true?", "People everywhere have similar needs.", ["Only people in Canada need food.", "Needs are different everywhere."], "All people need basic things.", true],
  ["Which sentence is true?", "People may live differently but share feelings.", ["People elsewhere have no feelings.", "Only Canadians have friends."], "We share feelings and needs.", true],
  ["On a globe, we can find…", "countries far away", ["only our house", "only our school"], "A globe shows the whole Earth.", true],
  ["Your family may have a relative in another country. You can send them a…", "card or video message", ["rock", "puddle"], "Keep in touch.", true],
  ["A kind action for a child far away could be…", "giving to a trusted group that helps children", ["ignoring news", "making fun of them"], "Be willing to help.", true],
  ["Learning another language helps you…", "connect with more people", ["avoid people", "forget your own"], "Languages build connections.", true],
  ["A new student from another country joins your class. You can…", "welcome them", ["ignore them", "tease them"], "Welcome new friends.", true],
  ["Neighbours here came from many countries. This makes our community…", "richer and more interesting", ["empty", "less safe"], "Different backgrounds add to our communities.", true],
  ["Which is the best way to learn about people far away?", "read a book or talk to someone from there", ["guess without learning", "make up stories"], "Learn from good sources.", true],
  ["Needs for water are shared by…", "people, animals and plants everywhere", ["only Canada", "only grown-ups"], "All living things need water.", true],
];

const SKILLS: Q[] = [
  ["Which is a way to find information?", "ask a person or look in a book", ["close your eyes", "stand still"], "Gather information from sources."],
  ["Which is a source of information?", "a library book", ["a sock", "a sandwich"], "Books give information."],
  ["Which is a source of information?", "a video", ["a mitten", "a pillow"], "We can learn by watching."],
  ["Sort these into two groups: cat, dog, apple, pear. Which are animals?", "cat and dog", ["apple and pear", "cat and apple"], "Group things that are alike."],
  ["Sort these: cap, boot, sock, spoon. Which are clothes?", "cap, boot and sock", ["cap and spoon", "spoon and sock"], "A spoon is not clothing."],
  ["Sort by size: a cup, a bucket. Which is bigger?", "the bucket", ["the cup", "they are the same"], "Compare to sort."],
  ["Which word tells about time long ago?", "yesterday", ["tomorrow", "next week"], "Yesterday has already happened."],
  ["Which word tells about time that has not yet happened?", "tomorrow", ["yesterday", "last year"], "Tomorrow is the next day."],
  ["Which word is about the past?", "last week", ["next week", "soon"], "Last week is in the past."],
  ["Which word is about now?", "today", ["last year", "someday"], "Today is the day we are in."],
  ["A timeline shows events in…", "the order they happened", ["any order", "alphabetical order"], "Timelines show order from first to last."],
  ["Put in order: baby, child, grown-up", "baby, child, grown-up", ["grown-up, baby, child", "child, grown-up, baby"], "People grow in order."],
  ["On a timeline of your day, what comes first?", "waking up", ["going to bed", "dinner"], "The day starts when you wake."],
  ["Which tool helps you tell the time?", "a clock", ["a spoon", "a ruler"], "Clocks tell the time."],
  ["Which tool can you use to draw a map?", "a pencil and paper", ["a ball", "a bucket"], "Draw simple maps."],
  ["You compare two kinds of leaves. You can see how they are…", "alike and different", ["tasty", "loud"], "Comparing helps us learn."],
  ["Your friend tells you a new fact. You change your idea. This is…", "revising your ideas with new information", ["a mistake", "a trick"], "It is good to change ideas when we learn more."],
  ["You think it will rain. Then you see sunshine. A good thing to say is…", "I changed my mind because I saw sun.", ["I won't change.", "It's the sun's fault."], "Change ideas when you see new facts."],
  ["You think a cat is mean, then it purrs on your lap. You may…", "change your opinion", ["never change", "scold it"], "New information can change an idea."],
  ["We form opinions from…", "what we see and learn", ["nothing", "luck"], "Use information to form opinions."],
  ["Listen actively means…", "pay attention to the speaker", ["talk the whole time", "look away"], "Listen with your ears and eyes.", true],
  ["Which is respectful language?", "Please pass the glue.", ["Gimme that!", "Hey, dummy!"], "Use respectful words.", true],
  ["Which gives a reason?", "I like the park because I can run.", ["I like the park.", "Park."], "Because gives a reason.", true],
  ["Tell what happened in order. Which is first: wake up, eat, school?", "wake up", ["school", "eat"], "Start at the beginning.", true],
  ["You tell a friend about your weekend. You say what happened…", "in order", ["backwards only", "never"], "Tell events in order.", true],
  ["You show your idea by drawing. This is sharing…", "visually", ["by taste", "by smell"], "You can share ideas in pictures.", true],
  ["You build a model to show an idea. This is sharing…", "concretely", ["with a sneeze", "never"], "Concrete means with objects.", true],
  ["Which is a good way to share your idea with the class?", "tell it and show a picture", ["whisper to the floor", "wait forever"], "Present your ideas in different ways.", true],
];

export const familyAndStories = bankUnit({
  id: "mb-g1-family-stories",
  title: "My Family & Stories",
  emoji: "👨‍👩‍👧",
  blurb: "Groups we belong to, family traditions and stories of the past.",
  parentNote:
    "Practises the groups children belong to, how families share their culture and traditions, family connections across generations, and respect for the stories, languages and celebrations of others, including francophone, First Nations, Métis and Inuit communities in Manitoba.",
  standards: [
    "1-KI-007, 1-KI-007A, 1-KI-007F, 1-KI-009, 1-KH-017, 1-KH-017F, 1-KH-018, 1-KC-002A, 1-KC-003A, 1-VI-003, 1-VI-005, 1-VH-009",
    "groups we belong to, family culture and traditions, previous generations, and valuing stories of the past",
  ],
  items: FAMILY,
});

export const needsAndWants = bankUnit({
  id: "mb-g1-needs-wants",
  title: "Needs & Wants",
  emoji: "🛒",
  blurb: "What we need, what we want and how ads can change that.",
  parentNote:
    "Practises telling needs from wants, noticing how advertising and television can make us want things, caring for our own and others' property, and respecting that people's wants can differ.",
  standards: [
    "1-KE-027, 1-KE-028, 1-KE-030, 1-VE-013, 1-VE-014",
    "needs and wants, media influence, caring for property and respecting differences",
  ],
  items: NEEDS,
});

export const gettingAlong = bankUnit({
  id: "mb-g1-getting-along",
  title: "Getting Along",
  emoji: "🤝",
  blurb: "Share, decide together, follow rules and solve problems kindly.",
  parentNote:
    "Practises working and playing together, being fair and respectful, following rules, making choices and noticing their effects, helping settle conflicts peacefully, and valuing friendships and differences.",
  standards: [
    "1-KP-022, 1-KP-023, 1-VC-001, 1-VC-002, 1-VI-004, 1-VI-006, 1-VP-011, 1-VP-011A, 1-VP-012, 1-S-100, 1-S-101, 1-S-102, 1-S-301",
    "cooperating, fairness and respect, rules, decisions and their consequences, and settling conflicts peacefully",
  ],
  items: TOGETHER,
});

export const placesWeCareFor = bankUnit({
  id: "mb-g1-places-we-care-for",
  title: "Places We Care For",
  emoji: "🏞️",
  blurb: "Where we live, landmarks, simple maps and looking after nature.",
  parentNote:
    "Practises describing where a home is, reading and making simple maps, naming local landmarks including Indigenous and francophone ones, and caring for nature and community places.",
  standards: [
    "1-KL-013, 1-KL-016A, 1-KL-016F, 1-VL-007, 1-VL-007A, 1-VL-008, 1-S-103, 1-S-205, 1-S-206, 1-S-207",
    "addresses and relative location, simple maps, local landmarks, and caring for nature and community places",
  ],
  items: PLACES,
});

export const worldNeighbours = bankUnit({
  id: "mb-g1-world-neighbours",
  title: "Our World Together",
  emoji: "🌎",
  blurb: "People everywhere have the same needs, and we can help each other.",
  parentNote:
    "Practises noticing that people all over the world share needs and feelings, connections children may have to people elsewhere, and being willing to help.",
  standards: ["1-KG-020, 1-KG-021, 1-VG-010", "shared needs and relationships around the world, personal connections and willingness to help"],
  items: WORLD,
});

export const thinkingSkills = bankUnit({
  id: "mb-g1-thinking-skills",
  title: "Social Studies Skills",
  emoji: "🧭",
  blurb: "Find information, sort, order events and share ideas.",
  parentNote:
    "Practises the skills children use in social studies: gathering and sorting information, using words for time, simple timelines, comparing, forming and changing opinions with reasons, listening respectfully and telling events in order.",
  standards: [
    "1-S-200, 1-S-201, 1-S-202, 1-S-203, 1-S-204, 1-S-300, 1-S-302, 1-S-303, 1-S-400, 1-S-401, 1-S-402, 1-S-403, 1-S-404",
    "gathering and sorting information, time words, timelines, comparing, opinions and reasons, and sharing ideas in order",
  ],
  items: SKILLS,
});
