import { bankUnit, type Q } from "../own";

// Grade 1 English language arts: letters (A2.2), reading and viewing (B1, B2, B3), writing (C1, C2, C3) and
// listening and speaking manners (A1, D1, D2). Purely oral and presentation outcomes are only touched through choice questions.

const LETTERS: Q[] = [
  ["Which lowercase letter matches A?", "a", ["e", "o"], "A is the capital, a is the small one."],
  ["Which lowercase letter matches B?", "b", ["d", "p"], "B and b are a pair."],
  ["Which lowercase letter matches D?", "d", ["b", "q"], "D and d are a pair."],
  ["Which lowercase letter matches G?", "g", ["q", "y"], "G and g are a pair."],
  ["Which lowercase letter matches M?", "m", ["n", "w"], "M and m are a pair."],
  ["Which lowercase letter matches R?", "r", ["n", "h"], "R and r are a pair."],
  ["Which lowercase letter matches T?", "t", ["f", "l"], "T and t are a pair."],
  ["Which capital letter matches h?", "H", ["N", "K"], "h is the small one, H is the capital."],
  ["Which capital letter matches k?", "K", ["X", "R"], "k and K are a pair."],
  ["Which capital letter matches p?", "P", ["B", "D"], "p and P are a pair."],
  ["Which capital letter matches s?", "S", ["Z", "C"], "s and S are a pair."],
  ["Which capital letter matches w?", "W", ["M", "V"], "w and W are a pair."],
  ["What is the name of this letter: Q?", "Q", ["O", "G"], "The letter Q is called Q."],
  ["Which letter comes after C in the alphabet?", "D", ["B", "E"], "A, B, C, D."],
  ["Which letter comes before F in the alphabet?", "E", ["G", "D"], "D, E, F."],
  ["Which letter comes between L and N?", "M", ["K", "O"], "L, M, N."],
  ["Which is the first letter of the alphabet?", "A", ["Z", "M"], "The alphabet begins with A."],
  ["Which is the last letter of the alphabet?", "Z", ["A", "X"], "The alphabet ends with Z."],
  ["Which word starts with a capital letter?", "Winnipeg", ["winnipeg", "wINnipeg"], "Names of places start with a capital."],
  ["Which is the correct way to write your name?", "Ava", ["ava", "aVA"], "A name begins with a capital letter."],
  ["Which pair is the same letter?", "E and e", ["E and a", "E and o"], "Capital and small forms of the same letter."],
  ["Which pair is the same letter?", "T and t", ["T and f", "T and l"], "Match big to small."],
  ["Which pair is the same letter?", "Y and y", ["Y and v", "Y and u"], "Y has a capital and a small form."],
  ["Which two letters look alike but are different?", "b and d", ["b and b", "a and a"], "b has its tummy on the right, d on the left.", true],
  ["Which letter has a tail that goes below the line?", "g", ["a", "o"], "g, j, p, q and y have tails.", true],
  ["Which lowercase letter matches Q?", "q", ["p", "g"], "Q and q are a pair.", true],
  ["Which lowercase letter matches N?", "n", ["m", "h"], "N and n are a pair.", true],
  ["Which lowercase letter matches J?", "j", ["i", "l"], "J and j are a pair.", true],
];

const READING: Q[] = [
  ["What do you do before reading a new book?", "Think about what you already know", ["Close your eyes", "Turn all the pages fast"], "Prior knowledge helps you understand."],
  ["Look at the cover. What might the book be about?", "You can make a prediction", ["You must not guess", "It is a secret"], "We predict with clues from the cover."],
  ["The cover shows a dog digging a big hole. What might happen?", "The dog finds a bone", ["The dog flies to Mars", "The dog turns into a car"], "A good prediction fits the clues."],
  ["A girl packs a bag and puts on boots. What will she do next?", "go for a walk", ["fall asleep in the sink", "swim in a desert"], "Use the clues to predict."],
  ["The sky is dark and it begins to rain. What might a boy get?", "an umbrella", ["a sunburn", "a kite for wind in July"], "Rain makes us want an umbrella."],
  ["Which of these tells you a book is about real facts?", "It has headings and photos", ["It has a talking owl", "It starts “Once upon a time”"], "Nonfiction often has headings and photos."],
  ["Which is a heading?", "a bold title above a part", ["the last page", "a glue stick"], "A heading names what a part is about."],
  ["A picture with a label helps you…", "understand the text", ["lose your place", "skip the book"], "Text features give extra information."],
  ["A chart in a book shows…", "information in a list or grid", ["a made-up story", "only colours"], "Charts organize facts."],
  ["Which is a story from long ago told out loud?", "oral storytelling", ["a phone bill", "a menu"], "Many people share stories by telling them."],
  ["Which is a list of what to buy?", "a shopping list", ["a poem", "a map"], "A list shows things one after another."],
  ["Which kind of text tells true facts about animals?", "a nonfiction book", ["a fairy tale", "a made-up joke"], "Nonfiction gives facts."],
  ["Which kind of text has made-up characters and events?", "fiction", ["a weather report", "a recipe"], "A story that is made up is fiction."],
  ["A poem often has…", "words that rhyme or have rhythm", ["only numbers", "no words"], "Poems play with sounds."],
  ["A book that tells about a person's life is a…", "biography", ["recipe", "calendar"], "A biography tells about a life."],
  ["You read about a cat. Your cat at home does the same thing. This is a…", "connection", ["mistake", "puzzle"], "You connect the text to your own life."],
  ["A story is about a snowy day. You remember sledding. You are…", "making a connection", ["losing your place", "writing a list"], "You link the text to what you know."],
  ["A word like “habitat” is a topic word. Where might you learn it?", "a book about animals", ["a book about shoes", "a game of tag"], "Topic words belong to a subject."],
  ["The word “seed” is a topic word. Which subject is it from?", "plants", ["music", "swimming"], "Seeds grow into plants."],
  ["The word “fraction” is a topic word. Which subject is it from?", "math", ["art", "gym"], "Fractions are in math."],
  ["The word “map” is a topic word. Which subject is it from?", "social studies", ["music", "baking"], "We use maps to find places."],
  ["Who might know a lot about a topic you are learning?", "an Elder or an expert", ["a stranger on the street", "nobody"], "People in our communities can help us learn.", true],
  ["Why do we ask questions before reading?", "to find out what we are curious about", ["to make the book end", "to hide the pictures"], "Questions help us look for answers.", true],
  ["A book has a table of contents. It helps you…", "find where parts are", ["spell your name", "colour the cover"], "It lists the parts of the book.", true],
  ["You want to learn about bears. Which book should you choose?", "a book about bears", ["a book about boats", "a book about boots"], "Choose a text that fits your question.", true],
  ["After reading, you can share what you learned by…", "telling a friend", ["tearing the book", "hiding it"], "Sharing helps us remember.", true],
  ["A speech bubble in a comic shows…", "what a character says", ["the title", "the page number"], "Words inside the bubble are spoken.", true],
];

const THINK: Q[] = [
  ["Which could be true?", "Owls fly at night.", ["Owls drive trucks.", "Owls are made of ice."], "Facts match what is real."],
  ["Which could NOT be true?", "A cow flies to the moon on a bike.", ["A cow eats grass.", "A cow gives milk."], "Some things are make-believe."],
  ["A story says a fox talks. Is that real?", "No, it is make-believe", ["Yes, foxes talk", "Yes, always"], "Talking animals appear in stories."],
  ["A book says that fish live in water. Is that true?", "Yes", ["No, they live in trees", "No, in the sky"], "Fish live in water."],
  ["A book says the sun is cold and blue. Is that true?", "No, the sun is very hot", ["Yes", "Only on Mondays"], "The sun is hot."],
  ["Which sentence is false?", "Snow is warm.", ["Snow is cold.", "Snow is white."], "Snow is cold."],
  ["Which sentence is true?", "Birds have feathers.", ["Birds have fur.", "Birds have scales."], "Feathers are what birds have."],
  ["Which sentence is false?", "Fish walk to school.", ["Fish swim.", "Fish have fins."], "Fish do not walk."],
  ["Two friends ride the same roller coaster. One loves it. The other does not. Why?", "People can feel differently", ["One is wrong", "One did not ride"], "People can have different viewpoints."],
  ["Mia likes rain. Sam does not. Can both be right about their feelings?", "Yes", ["No, only Mia", "No, only Sam"], "Feelings and opinions can differ."],
  ["A friend says, “I like red best.” You like blue. What is okay?", "We can like different colours", ["Only red is right", "Nobody likes blue"], "We respect other viewpoints."],
  ["“I think this book is funny because the dog slips.” This is an…", "opinion with a reason", ["address", "number"], "An opinion tells what you think and why."],
  ["Which is an opinion?", "This story is the best.", ["The story has 12 pages.", "The story is about a cat."], "Words like best show an opinion."],
  ["Which is a fact?", "A dog has four legs.", ["Dogs are the best.", "Dogs are funny."], "A fact can be checked."],
  ["Why is it good to see people like you in books?", "It feels good to see yourself", ["It is not important", "It is a trick"], "Books should show many kinds of people."],
  ["Why is it good to read books about different families?", "We learn about others", ["We stop learning", "It is a rule for adults"], "Books are windows to other lives."],
  ["You see only one kind of family in a book. What can you say?", "I wish I could see my family too", ["Nobody else exists", "That family is wrong"], "Many kinds of people should be in stories."],
  ["Which sentence gives a reason?", "I liked the book because it was funny.", ["I liked it.", "Book."], "“Because” gives a reason."],
  ["Which sentence shares an opinion about a story?", "I liked the ending.", ["The book is on the shelf.", "The cover is green."], "An opinion tells what you think."],
  ["Finish: I liked the story because…", "the dragon was kind", ["of", "the the"], "A reason tells why."],
  ["What can a picture help you find out?", "who is in the story", ["the book's weight", "the price"], "Pictures give clues."],
  ["A story has a talking tree. Real trees…", "do not talk", ["sing songs", "read books"], "Real trees do not talk.", true],
  ["One book says whales are fish, another says mammals. What can you do?", "Check another source", ["Never read again", "Guess wildly"], "Compare sources to check what is true.", true],
  ["Two people see one game. One says fun, one says too loud. Why?", "Each has a different viewpoint", ["One is lying", "They saw different games"], "People can feel differently about the same thing.", true],
  ["What is a good reason to like a book?", "It made me laugh", ["It is a book", "Because"], "A good reason says something about the book.", true],
  ["Which one might be true in a nonfiction book?", "Bees help flowers make seeds.", ["Bees drive buses.", "Bees live on Mars."], "Nonfiction tells true facts.", true],
  ["You read that frogs start as tadpoles. Where could you check?", "In a nature book", ["On your shoe", "In a drawer"], "Check a trusted source.", true],
];

const WRITING: Q[] = [
  ["Before you write, what can help you plan?", "Draw or talk with a partner", ["Wait for a miracle", "Put away your pencil"], "Drawing and talking help you plan."],
  ["Which is a way to plan what to write?", "make a list of ideas", ["close the notebook", "cut the page"], "Brainstorm ideas first."],
  ["A story needs a beginning, a…", "middle and an end", ["table and a chair", "colour and a shape"], "Stories have three parts."],
  ["Which comes first in a story?", "beginning", ["end", "last page"], "Stories start at the beginning."],
  ["Which comes last in a story?", "ending", ["beginning", "title page"], "The ending wraps up the story."],
  ["Put in order: I woke up. I ate breakfast. I went to bed.", "woke up, ate, went to bed", ["went to bed, woke up, ate", "ate, went to bed, woke up"], "Day events go in order."],
  ["Which word helps you tell what happens first?", "First", ["Never", "Purple"], "First, next, then, last show order."],
  ["Which word helps you tell what happens at the end?", "Last", ["First", "Under"], "Last tells the end."],
  ["Which words go together in a list about fruit?", "apple, pear, plum", ["apple, chair, plum", "pear, desk, plum"], "Group related ideas."],
  ["Which item does NOT belong in a list of animals?", "chair", ["cat", "owl"], "A chair is not an animal."],
  ["Which item does NOT belong in a list of colours?", "table", ["red", "green"], "A table is not a colour."],
  ["Which of these is a sentence that tells a feeling?", "I am happy!", ["happy am", "I."], "A sentence tells a whole thought."],
  ["Bold words in a book show…", "the word is important", ["the page is wet", "the book is old"], "Writers use bold to stand out."],
  ["An exclamation mark shows…", "strong feeling", ["a question", "a pause only"], "! shows excitement."],
  ["Which writing sounds like it comes from you?", "I love my dog Bruno!", ["A pet is an animal.", "It exists."], "Your voice shows your feelings."],
  ["Which sentence shows a feeling?", "I felt so proud!", ["It is a table.", "There are three."], "Show what you feel."],
  ["A friend says, “Please add more detail.” You should…", "add a few more words", ["throw it away", "stop writing"], "Listening to feedback makes writing clearer."],
  ["A friend says, “I don't understand this word.” What can you do?", "Change it to make it clearer", ["Ignore your friend", "Erase everything"], "We can change our ideas to be clearer."],
  ["Which is a good way to make writing clearer?", "add a picture or detail", ["delete all of it", "scribble on it"], "More detail helps readers."],
  ["Which could be added to a story to make it more fun?", "a drawing", ["a hole", "a smudge"], "Pictures add meaning."],
  ["Which tool can you use to write on a computer?", "a keyboard", ["a ruler", "a spoon"], "Keys help us type letters."],
  ["Which of these is a kind of writing that tells facts?", "informational text", ["a rhyme", "a sneeze"], "Informational text tells facts.", true],
  ["Which kind of writing tries to make a reader agree with you?", "persuasive writing", ["a shopping list", "a map"], "Persuasive writing gives reasons.", true],
  ["Which kind of writing tells what something looks like?", "descriptive writing", ["a sum", "a clock"], "Descriptive writing uses details.", true],
  ["Which line is a description?", "The red ball is round and bouncy.", ["Go.", "Ball."], "Details tell more.", true],
  ["Which tool makes a story with pictures and sound?", "a recording app", ["a rock", "a spoon"], "Modes include words, images and sound.", true],
  ["Telling a story out loud, recording it, and adding pictures use…", "more than one mode", ["only one mode", "no mode"], "Words, images and sound are different modes.", true],
];

const TALK: Q[] = [
  ["When someone is talking, you should…", "listen with your eyes and ears", ["talk loudly", "walk away"], "Good listeners look at the speaker."],
  ["Which shows you are listening?", "Turn your body to the speaker", ["Look at the ceiling", "Tap on a desk"], "Body position shows listening."],
  ["Which is a good way to join a talk?", "Wait until the speaker is done", ["Shout over them", "Walk away"], "Take turns."],
  ["A friend shares a story. You can…", "share one that connects", ["say nothing and leave", "laugh at them"], "Share your own experience kindly."],
  ["You did not hear the directions. What can you do?", "Ask a question", ["Guess without asking", "Leave"], "Questions help us understand."],
  ["Which is a question?", "What is your name?", ["Tell me your name.", "My name is Jo."], "A question asks and ends with ?"],
  ["Someone asks, “What is your favourite colour?” Which answer matches?", "Green", ["Tuesday", "Seven"], "Match the answer to the question."],
  ["Someone asks, “How old are you?” Which answer matches?", "Six", ["Blue", "Under the bed"], "Match the answer to the question."],
  ["Someone asks, “Where do you live?” Which answer matches?", "In Winnipeg", ["A red hat", "Yesterday"], "Where asks about a place."],
  ["Someone asks, “When is lunch?” Which answer matches?", "At noon", ["In a lunch box", "Green"], "When asks about time."],
  ["Which is a complete sentence?", "The dog ran fast.", ["ran fast", "the dog"], "A complete sentence tells who and what."],
  ["Which is a complete sentence?", "I like to read.", ["like to", "I and"], "It has a who and a what."],
  ["Which sentence is spoken in the best way?", "I want to share my idea.", ["Me idea share.", "Idea."], "Use full words."],
  ["Which word is kinder to ask for something?", "please", ["now", "give"], "Kind words help conversations."],
  ["You talk with a grandparent. Which is a polite way to start?", "Hello, how are you?", ["Hey you", "Give me that"], "We can adjust how we talk to match who we talk to."],
  ["Which is a better way to talk to a teacher?", "Excuse me, may I ask a question?", ["Hey, you!", "Move it"], "Polite words are respectful."],
  ["Which is a good way to talk to a friend on the playground?", "Do you want to play?", ["Go away", "No"], "A friendly voice works."],
  ["When you have something important to say, you can…", "raise your hand and speak", ["stay silent forever", "shout"], "Your voice matters in a group."],
  ["Which is a way to change topic in a talk?", "“I'd also like to talk about…”", ["“Be quiet.”", "“No.”"], "Use words that join the talk."],
  ["Which is a good way to tell how you learned today?", "I can say what went well", ["I will not say", "Never"], "Think about what went well."],
  ["What can you use to check your own learning?", "a sticker chart or checklist", ["a spoon", "a rock"], "Checklists show progress.", true],
  ["A teacher says, “What went well?” You can say…", "I finished my picture", ["Purple", "Tomorrow is Monday"], "Share a real thing that went well.", true],
  ["A good goal for reading is to…", "read a little every day", ["never read", "read only a page a year"], "Small steps help.", true],
  ["You moved your sticker up your chart. What does it show?", "You are making progress", ["You are done forever", "You lost"], "Charts show how far you have come.", true],
  ["When you give your idea, it helps to add…", "a reason", ["a sneeze", "a hat"], "Reasons make ideas stronger.", true],
  ["Which is better to say to an Elder?", "Thank you for sharing your story.", ["Hey, you!", "Tell me now."], "Show respect.", true],
  ["Which is the most polite way to start a call with a grown-up?", "Hello, may I speak to Anna?", ["Anna, now.", "Who is this, hurry."], "Formal talk uses polite words.", true],
];

export const alphabetMatch = bankUnit({
  id: "mb-g1-alphabet-match",
  title: "Big and Little Letters",
  emoji: "🔤",
  blurb: "Match capital letters to small ones and know the alphabet order.",
  parentNote: "Practises naming letters and matching capital letters to lowercase ones, and knowing which letter comes before and after.",
  standards: ["ELA.1.A2.2", "naming alphabet letters and matching upper to lowercase"],
  items: LETTERS,
});

export const readingSmart = bankUnit({
  id: "mb-g1-reading-smart",
  title: "Reading Smart",
  emoji: "📖",
  blurb: "Predict, connect, and use text features.",
  parentNote:
    "Practises thinking before and while reading: using what you already know, predicting what happens next, making connections to your own life, using headings and pictures, telling kinds of texts apart and learning topic words.",
  standards: [
    "ELA.1.B1.1, ELA.1.B1.2, ELA.1.B1.3, ELA.1.B1.4, ELA.1.B2.1, ELA.1.B2.2, ELA.1.B2.3, ELA.1.B2.4, ELA.1.B2.7",
    "background knowledge, choosing texts, text forms and features, predictions, connections and topic words",
  ],
  items: READING,
});

export const truthAndViewpoints = bankUnit({
  id: "mb-g1-true-and-viewpoints",
  title: "True, Pretend and Opinions",
  emoji: "🤔",
  blurb: "What is real, what is pretend, and why people think differently.",
  parentNote:
    "Practises telling what could be true from what is make-believe, noticing that people see the same thing differently, seeing people like us in books, and giving an opinion with a reason.",
  standards: [
    "ELA.1.B3.1, ELA.1.B3.2, ELA.1.B3.3, ELA.1.B3.4",
    "seeing ourselves in texts, what could be true or false, different viewpoints and sharing opinions with reasons",
  ],
  items: THINK,
});

export const writingPlan = bankUnit({
  id: "mb-g1-writing-plan",
  title: "Plan and Write",
  emoji: "✏️",
  blurb: "Plan, put ideas in order, and make writing clearer.",
  parentNote:
    "Practises planning writing by drawing and talking, putting ideas in order, grouping ideas that belong together, showing feelings in writing, improving after feedback, and knowing different kinds of writing.",
  standards: [
    "ELA.1.C1.1, ELA.1.C1.2, ELA.1.C1.3, ELA.1.C1.4, ELA.1.C1.5, ELA.1.C2.1, ELA.1.C2.4, ELA.1.C2.5, ELA.1.C3.1, ELA.1.C3.5",
    "planning, kinds of writing, organizing ideas, personal voice, feedback, forming letters and using more than one mode",
  ],
  items: WRITING,
});

export const talkAndListen = bankUnit({
  id: "mb-g1-talk-and-listen",
  title: "Listen and Talk",
  emoji: "👂",
  blurb: "Good listening, kind words and thinking about your learning.",
  parentNote:
    "Practises the habits of a good listener and speaker: looking at the speaker, taking turns, asking and answering questions, using complete sentences, adjusting how we talk for different people, and thinking about our own learning.",
  standards: [
    "ELA.1.A1.1, ELA.1.A1.2, ELA.1.A1.3, ELA.1.A1.4, ELA.1.A1.5, ELA.1.A1.6, ELA.1.D1.1, ELA.1.D1.2, ELA.1.D1.3, ELA.1.D2.1, ELA.1.D2.2, ELA.1.D2.3, ELA.1.D2.4, ELA.1.D2.5",
    "listening, taking part in talks, questions and answers, complete sentences, speaking for an audience and reflecting on learning",
  ],
  items: TALK,
});
