import { bankUnit, type Q } from "../own";

// Grade 2 English language arts: writing mechanics, fluency, responding to texts, finding information, planning and
// improving writing, media, and polite listening and asking (strands A to D).

const LETTERS: Q[] = [
  ["Which word is written correctly at the start of a sentence?", "The", ["the", "tHe"], "A sentence begins with a capital letter."],
  ["Which name is written correctly?", "Maya", ["maya", "mAya"], "Names begin with a capital letter."],
  ["Which is the capital letter that goes with b?", "B", ["d", "P"], "B is the capital form of b."],
  ["Which is the capital letter that goes with g?", "G", ["C", "Q"], "G is the capital form of g."],
  ["Which is the lowercase letter that goes with R?", "r", ["n", "p"], "r is the lowercase form of R."],
  ["Which is the lowercase letter that goes with D?", "d", ["b", "p"], "d is the lowercase form of D."],
  ["Which letter has a tail that drops below the line?", "g", ["a", "o"], "The letters g, j, p, q and y drop below the line."],
  ["Which letter does NOT drop below the line?", "e", ["p", "y"], "e sits on the line."],
  ["Which letter is tall and reaches the top line?", "l", ["a", "c"], "The letters b, d, h, k and l are tall."],
  ["Which letter is short and sits in the middle space?", "m", ["t", "f"], "m is a short letter."],
  ["Which sentence is easiest to read?", "Letters of the same size with even spaces", ["Letters of different sizes squished together", "Letters leaning every which way"], "Neat, even letters make writing easy to read.", true],
  ["Which letter is the lowercase of Q?", "q", ["g", "p"], "q is the lowercase form of Q."],
  ["Which sentence has good spacing between words?", "I like red apples.", ["Ilike redapples.", "I likered apples."], "Leave a finger space between words."],
  ["How much space goes between two words?", "about one finger", ["none at all", "a whole line"], "A finger space helps readers see where each word stops."],
  ["Which sentence uses capital letters correctly?", "Sam lives in Winnipeg.", ["sam lives in winnipeg.", "Sam Lives In Winnipeg."], "Capitals are for the start of a sentence and for names of people and places."],
  ["Which word needs a capital letter?", "Manitoba", ["tree", "jump"], "The name of a province always starts with a capital."],
  ["Which word needs a capital letter?", "Monday", ["lunch", "pencil"], "Days of the week begin with capitals."],
  ["Which day name is written correctly?", "Friday", ["friday", "FridaY"], "Days of the week begin with a capital letter."],
  ["Which is written with the right-sized letters?", "dog", ["DoG", "dOg"], "Use capitals only where they belong."],
  ["When you print, where do the letters sit?", "on the line", ["above the line", "far below the line"], "Most letters sit on the line."],
  ["Which sentence needs a capital letter changed?", "we went to the lake.", ["We went to the lake.", "Our dog ran."], "The first word must begin with a capital letter.", true],
  ["Which sentence has all its capitals right?", "Ella and Omar visited Brandon.", ["ella and Omar visited brandon.", "Ella and omar visited Brandon."], "Names of people and places need capitals.", true],
  ["You typed a story on a computer. Which key makes a capital letter?", "Shift", ["Space bar", "Enter only"], "Hold Shift and press a letter for a capital.", true],
  ["Which key puts a space between words when you type?", "Space bar", ["Shift", "Delete"], "The space bar makes the space between words.", true],
];

const SIGHT: Q[] = [
  ["Which word is a common word you see in many stories?", "the", ["zebra", "volcano"], "Words like the, and, was and said are in almost every story."],
  ["Which word is a common word you see in many stories?", "said", ["rhinoceros", "telescope"], "You will meet said again and again."],
  ["Which word means the same as “large”?", "big", ["tiny", "wet"], "Big and large mean almost the same."],
  ["Read the word: “because”. Which word is it?", "because", ["become", "before"], "Look at all of the letters."],
  ["Read the word: “where”. Which word is it?", "where", ["were", "when"], "Where asks about a place."],
  ["Read the word: “were”. Which word is it?", "were", ["where", "wear"], "Were is about the past, like “we were there”."],
  ["Which word fits? “We ___ going to the park.”", "are", ["our", "or"], "We are going."],
  ["Which word fits? “That is ___ dog.”", "our", ["are", "hour"], "Our shows that the dog belongs to us."],
  ["Which word fits? “___ you want to play?”", "Do", ["Dew", "Doe"], "Do you want to play?"],
  ["Which word is spelled the way we say “they”?", "they", ["thay", "thei"], "They has the letters t-h-e-y."],
  ["Which mark tells your voice to stop at the end of a telling sentence?", "a period", ["a question mark", "an exclamation mark"], "A period ends a telling sentence."],
  ["Which mark tells you a sentence is a question?", "a question mark", ["a period", "a comma"], "Your voice goes up at a question mark."],
  ["Which mark tells you to read with strong feeling?", "an exclamation mark", ["a comma", "a period"], "Read it with excitement or surprise."],
  ["What should you do when you read a comma?", "pause for a moment", ["stop and shout", "skip the next word"], "A comma is a short pause."],
  ["What should you do when you reach a period?", "stop and take a breath", ["read faster", "go back to the start"], "A period is a full stop."],
  ["How should you read “Wow, that is huge!”?", "with surprise", ["in a sleepy voice", "in a whisper"], "The exclamation mark shows strong feeling."],
  ["Which way of reading helps others understand best?", "not too fast and not too slow", ["as fast as possible", "one word at a time with long stops"], "A steady pace helps listeners follow."],
  ["Reading smoothly with phrases is like…", "talking", ["robot words", "whispering to yourself only"], "Good reading sounds like talking."],
  ["Read the sentence: “Can we go?” How does your voice end?", "it goes up", ["it goes down a lot", "it stays flat like a hum"], "Questions usually rise at the end."],
  ["Which sentence should be read with a pause after “Yes”?", "Yes, I can come.", ["Yes I can come", "Yes I Can Come"], "The comma tells you to pause."],
  ["A word you know on sight means you can…", "read it quickly without sounding it out", ["never read it", "only read it in the dark"], "Sight words are read at a glance.", true],
  ["Which word do you need to look at carefully so you do not mix it up with “then”?", "than", ["thin", "this"], "Then and than look almost the same.", true],
  ["“Would” and “could” rhyme. Which word also rhymes with them?", "should", ["shoot", "shout"], "Would, could and should end the same way.", true],
  ["Why do we notice punctuation when we read aloud?", "it helps the reading make sense", ["it makes the story shorter", "it changes the words"], "Punctuation tells us when to pause and how to say it.", true],
  ["Which sentence shows a quick pause after “first”?", "First, we put on our boots.", ["First we put on, our boots.", "First we, put on our boots."], "The comma goes after the word that begins the sentence.", true],
];

const RESPOND: Q[] = [
  ["A story is about a dog that gets lost. Your dog once got lost too. What are you doing?", "making a connection", ["making a mistake", "skipping the story"], "Linking a story to your own life is a connection."],
  ["You read about snow. You remember building a snow fort. This is a…", "text-to-self connection", ["spelling rule", "kind of rhyme"], "You connected the text to yourself."],
  ["You read about a fox in one book and in a second book. This connects…", "one book to another book", ["a book to a song only", "nothing at all"], "That is a text-to-text connection."],
  ["You read about the Prairies and know the Prairies are flat. You used…", "what you already know", ["a guess with no reason", "a random choice"], "Using what you know helps you understand."],
  ["Which sentence gives an opinion about a book?", "I liked the story because it was funny.", ["The book has 20 pages.", "The book is on the shelf."], "An opinion tells what you think."],
  ["Which sentence gives a reason for an opinion?", "I liked it because the animals were silly.", ["I liked it.", "It is a book."], "A reason begins with “because”."],
  ["Why do we give reasons for our opinions?", "so others understand our thinking", ["to make the book shorter", "to hide what we think"], "Reasons help others understand."],
  ["Two friends ride the same roller coaster. One loves it and one is scared. This shows that…", "people can feel differently about the same thing", ["one friend is wrong", "roller coasters are not real"], "Different viewpoints are normal."],
  ["Two children read the same story. One likes the ending. The other does not. What is true?", "Both can have their own opinion.", ["Only one can be right", "Neither one read it"], "People can respond differently."],
  ["Which question helps you find a reason in the text?", "What did the story say that made you think that?", ["What colour is the cover?", "How many pages are left?"], "Use the text to back up your idea."],
  ["Text says: “Mia hid under her blanket.” Which feeling fits?", "scared", ["proud", "sleepy at noon"], "Hiding under a blanket often shows fear."],
  ["Text says: “Leo hugged his new puppy and laughed.” How does Leo feel?", "happy", ["angry", "lonely"], "Hugging and laughing show happiness."],
  ["A character says, “I can do it!” again and again. What kind of character is this?", "someone who keeps trying", ["someone who gives up", "someone who sleeps"], "Repeating it shows determination."],
  ["Which connection helps you understand a story about a new school?", "your first day at school", ["the colour of your socks", "what you had for lunch last week"], "A close connection makes the story clearer."],
  ["A story is set in winter on the Prairies. What might you picture?", "snow and bundled-up people", ["a hot desert", "a coral reef"], "Use what you know about winter in Manitoba."],
  ["After reading you say, “I think the fox was clever.” What did you share?", "your opinion", ["a spelling rule", "a title"], "An opinion tells what you think."],
  ["Which sentence tells something that happened in the book, with evidence?", "The text says the fox opened the gate.", ["I like gates.", "Foxes are fun."], "Evidence comes from the text."],
  ["A picture book shows a big storm. The words say “It was loud.” How can the picture help?", "It shows what loud looks like", ["It cannot help", "It changes the words"], "Pictures add meaning.", true],
  ["Why is it good to read stories about different kinds of people?", "we learn about many lives and ideas", ["it is the rule of the library", "stories are only for spelling"], "Stories are windows to other lives.", true],
  ["Some stories show a family like yours. Others show families unlike yours. Both are…", "worth reading", ["not real", "too hard"], "Seeing yourself and others in books both matter.", true],
  ["You do not see anyone like you in a book. What can you do?", "ask for books that show many kinds of people", ["stop reading forever", "tear out a page"], "Asking for more books helps everyone.", true],
  ["“The wolf is big and mean.” Another story says wolves care for their pups. What can you do?", "check more than one book", ["trust only the first one", "stop reading"], "Compare what different texts say.", true],
  ["Which sentence shows a different viewpoint from “Recess is the best part of school”?", "I like art class more than recess.", ["Recess is the best part of school.", "Recess is after lunch."], "A viewpoint can differ from yours.", true],
  ["After reading, you say, “This part reminds me of my grandmother's kitchen.” This is…", "a connection from your own life", ["a rhyme", "a title"], "You linked the book to your own life.", true],
  ["Which opinion has a reason?", "I like the poem because it makes me smile.", ["I like the poem.", "The poem is on page 3."], "Look for the word “because”.", true],
];

const FINDING: Q[] = [
  ["Before reading about frogs, what could you do first?", "think about what you already know about frogs", ["close your eyes and sleep", "read the last page only"], "Thinking about what you know prepares you."],
  ["Which question could guide an investigation about bees?", "What do bees eat?", ["Bees.", "Yes."], "A good question starts with a question word."],
  ["Which is a question word?", "why", ["the", "blue"], "Who, what, where, when, why and how begin questions."],
  ["Which question would you ask to learn about beavers?", "Where do beavers build their homes?", ["Beavers are brown.", "Look at the beaver."], "A question ends with a question mark and asks for information."],
  ["Where could you learn about birds in your area?", "a book, a bird expert or a nature website", ["a toy box", "an empty cupboard"], "Many sources give information."],
  ["Who might know a lot about the history of your community?", "an Elder or a long-time neighbour", ["a stranger on a boat", "a stuffed toy"], "People who have lived there a long time can share what they know."],
  ["You want to learn about snowshoe hares. Which text should you pick?", "a book about northern animals", ["a cookbook", "a book about cars"], "Pick texts that match your topic."],
  ["Which text might help you learn how plants grow?", "an information book about plants", ["a joke book", "a song about trucks"], "Information books teach facts."],
  ["Which source has real facts about a topic?", "an information book", ["a made-up story about dragons", "a comic about a talking pizza"], "Information books are about real things."],
  ["You find ten facts about owls. You must share only three. What should you do?", "choose the facts that answer your question", ["pick facts at random", "read all ten at once"], "Choose what matters most."],
  ["Your question is “What do owls eat?” Which fact is most useful?", "Owls eat mice and insects.", ["Owls are brown.", "Owls sleep in the day."], "It answers your question."],
  ["Which fact does NOT help answer “Where do frogs live?”", "Frogs have wide mouths.", ["Frogs live near ponds.", "Frogs live in wet places."], "It does not say where they live."],
  ["What is a topic word for a text about weather?", "temperature", ["pickle", "ladder"], "Temperature is a weather word."],
  ["What is a topic word for a text about plants?", "roots", ["wheels", "pillow"], "Plants have roots."],
  ["What is a topic word for a text about the Prairies?", "grain", ["coral", "iceberg"], "Grain grows on the Prairies."],
  ["Which word belongs with the topic “water”?", "stream", ["engine", "button"], "A stream is a small flow of water."],
  ["Which words belong with the topic “space”?", "planet and star", ["spoon and fork", "desk and chair"], "Planets and stars are in space."],
  ["A glossary in a book tells you…", "what special words mean", ["who wrote the book", "where to buy it"], "A glossary lists key words and their meanings."],
  ["You see a word in bold in a nonfiction book. What might it mean?", "it is an important word", ["it is a mistake", "it is a name"], "Bold words are often explained in the text."],
  ["Which phrase uses the right topic word? “The ___ of the plant takes in water.”", "roots", ["wheels", "pages"], "Roots take in water."],
  ["You can make a web to…", "show how ideas connect", ["fix a shoe", "measure a room"], "A web shows an idea and its parts.", true],
  ["Which would be good to investigate as a group?", "How do we stay safe on the playground?", ["Yes", "Blue is a colour."], "A group can look for answers to a good question.", true],
  ["Which question starts with “how” and helps you learn about seeds?", "How do seeds grow into plants?", ["Seeds.", "Green seeds are here."], "A “how” question asks about a process.", true],
  ["Some people know a lot about a topic and can answer questions. They are…", "experts", ["strangers", "pretenders"], "An expert has deep knowledge.", true],
  ["Which of these is the best topic word for a text about the human body?", "muscle", ["lantern", "tractor"], "Muscles are part of the body.", true],
  ["After reading, you can share a new word you learned by…", "using it in a sentence", ["hiding it", "crossing it out"], "Using new words helps you remember them.", true],
];

const PLAN: Q[] = [
  ["Before you write, what is a good first step?", "think of your ideas", ["hand in the page", "erase the whole page"], "Plan first, then write."],
  ["Which helps you plan a story?", "a list of what happens first, next and last", ["a blank wall", "a closed book"], "A list or storyboard keeps your ideas in order."],
  ["Which is a way to plan your writing?", "draw pictures of your ideas", ["rip up the paper", "close your eyes only"], "Drawings can plan a story."],
  ["What does brainstorming mean?", "thinking of many ideas", ["choosing one right away", "writing the title only"], "Brainstorming means thinking of lots of ideas."],
  ["A word web helps you…", "collect words about a topic", ["wash a spider", "count pages"], "A web shows words that go with a topic."],
  ["You write about your pet to tell a story. This kind of writing is…", "narrative", ["a recipe", "a list of rules"], "A narrative tells a story."],
  ["You write facts about whales. This kind of writing is…", "informational", ["a poem about love", "a made-up tale"], "Informational writing gives facts."],
  ["You describe a sunset with colourful words. This kind of writing is…", "descriptive", ["a list of names", "a calendar"], "Descriptive writing paints a picture with words."],
  ["You write to convince a friend to try a game. This kind of writing is…", "persuasive", ["narrative", "a recipe"], "Persuasive writing tries to change someone's mind."],
  ["Who might read your thank-you card?", "your audience", ["a speed limit", "a lamp"], "The audience is the person who reads or hears your writing."],
  ["Why do we write a letter to a grandparent?", "to share news", ["to count to a hundred", "to make a map"], "The purpose of the letter is to share."],
  ["You reread your story and one sentence does not make sense. What can you do?", "change the sentence so it makes sense", ["leave it", "cover it up"], "Writers fix parts that are unclear."],
  ["A friend says, “I did not understand this part.” What is a good way to use that?", "add more details", ["get upset", "throw it away"], "Feedback helps writers make things clear."],
  ["To make a story clearer, you can…", "add a missing detail", ["remove all the words", "write it upside down"], "Adding details can help."],
  ["Which sentence should be removed from a story about a picnic?", "My shoes are blue and green.", ["We packed sandwiches.", "We sat by the lake."], "It does not belong to the picnic story."],
  ["Which order makes sense? First, next, last.", "We got ready, we played, we went home.", ["We went home, we got ready, we played.", "We played, we went home, we got ready."], "Events usually happen in order."],
  ["Why do we reread our writing?", "to find and fix mistakes", ["to make it longer for no reason", "to hide it"], "Rereading helps you improve it."],
  ["Which tool can you use to write a story on a computer?", "a word processor", ["a ruler", "a spoon"], "A word processor lets you type and change text."],
  ["A poster uses words and pictures together. This is…", "more than one mode of communication", ["a spelling test", "only a sound"], "Words and pictures are two modes."],
  ["Which message works best on a poster for a school bake sale?", "Bake Sale Friday! Come and eat!", ["Friday", "Ssshh"], "A clear message tells people what and when.", true],
  ["You make a video for your class. Which belongs in it?", "words, pictures and sound", ["a blank screen", "a blank sheet"], "A video can bring together text, images and sound.", true],
  ["Who is the audience for a note to your teacher?", "your teacher", ["your pet fish", "the wind"], "The audience is who the writing is for.", true],
  ["You want to write about your favourite winter game. What could you list first?", "words that tell about the game", ["the names of the days", "your address"], "Listing ideas helps you plan.", true],
  ["Which sentence best fits a persuasive paragraph?", "We should plant a garden because it helps bees.", ["A garden has dirt.", "I went to bed."], "Persuasive writing gives a reason.", true],
  ["You decide to use pictures with your writing. Why?", "to help the reader understand", ["to fill the paper", "to hide the words"], "Pictures can add meaning.", true],
];

const MEDIA: Q[] = [
  ["Which is a way to share a message with many people?", "a poster", ["a secret", "a whisper alone"], "Posters, videos and signs reach many people."],
  ["Which of these is media?", "a TV show", ["a pencil", "a shoe"], "TV shows, videos and websites are media."],
  ["Which of these is media?", "a website", ["a chair", "a sandwich"], "Websites share messages."],
  ["Which of these is media?", "a poster", ["a rock", "a puddle"], "A poster shares a message."],
  ["A video can use…", "pictures, words and sound", ["only smell", "only taste"], "Videos can mix text, images and sound."],
  ["A book that has pictures and words uses…", "more than one way to share ideas", ["no ideas", "only sound"], "Words and pictures together tell more."],
  ["A character in a story is a thief who tricks others. Should you trust that character?", "no, not without checking", ["yes, always", "yes, because it is a story"], "Think about what a character does."],
  ["A website says “Free candy! Click now!” What should you do?", "ask a trusted adult before clicking", ["click right away", "tell a stranger your name"], "Be careful with things that seem too good to be true."],
  ["Who is a good person to ask if you are not sure a website is safe?", "a parent or teacher", ["a stranger online", "a pop-up"], "Ask a trusted adult."],
  ["You read two books about owls. One says owls sleep in the day and the other says they sleep at night. What do you do?", "check a third source", ["pick the one you like", "give up"], "Check another reliable source."],
  ["Why might a story with a talking fox not be good for learning real fox facts?", "it is made up", ["foxes are not real", "it has no pictures"], "Make-believe is not always true to life."],
  ["Who knows more about real bears?", "a wildlife biologist who studies bears", ["a story about a talking bear", "a cartoon bear in a hat"], "Experts who study a topic share real facts."],
  ["An ad for a toy says it is “the best in the world.” This message is trying to…", "get you to want the toy", ["teach you math", "tell you the weather"], "Ads are made to make people want things."],
  ["Which is an ad?", "a message that wants you to buy a snack", ["a book about whales", "a class list"], "An ad tries to sell something."],
  ["You see yourself in a story when…", "the character shares something with you", ["the cover is blue", "the book is long"], "Seeing yourself is part of feeling welcome in a story."],
  ["Which sentence is about how people are shown in a book?", "The book shows children from many places.", ["The book has 32 pages.", "The book is on the shelf."], "Who is shown in a text matters."],
  ["Some texts leave out people like you. How might that feel?", "left out", ["more important than others", "like a prize"], "It is fair to notice who is missing."],
  ["Which helps you decide if a source can be trusted?", "who made it and why", ["the colour of the page", "how loud it is"], "Think about the maker and purpose.", true],
  ["A cartoon shows a rabbit flying. Is it giving real facts?", "no, it is make-believe", ["yes, rabbits fly", "yes, rabbits are birds"], "A cartoon is fun but not always true.", true],
  ["An online video says it knows a secret that will make you rich. What is a good plan?", "tell a trusted adult", ["send money", "share your address"], "Ask for help with anything that feels risky.", true],
  ["A character in a story always tells the truth and helps others. Why might you trust that character?", "their actions are kind and honest", ["they wear a hat", "they have a long name"], "Actions help us decide.", true],
  ["Which would be a fair way to show many kinds of families in a picture book?", "show different families together", ["show only one kind", "leave families out"], "Many kinds of people can be shown.", true],
  ["After watching an ad, you can ask yourself…", "Do I really need this?", ["What colour is the TV?", "Where is the remote?"], "Questioning ads helps you choose wisely.", true],
  ["Which is a safe thing to do with a screen?", "take breaks and ask before you search", ["share your password", "talk to strangers"], "Safe habits matter.", true],
  ["A poster has a big picture and large words. Why?", "to catch people's attention", ["to hide the message", "to use more paper"], "Posters are designed to be noticed.", true],
];

const LISTEN: Q[] = [
  ["When someone is speaking to the group, you should…", "look at the speaker and listen", ["talk to your neighbour", "look away and hum"], "Show you are listening."],
  ["Which body language shows you are listening?", "facing the speaker", ["turning your back", "lying on the floor"], "Face the speaker."],
  ["Which facial expression shows you are listening?", "a calm, interested face", ["rolling your eyes", "yawning loudly"], "An interested face is kind."],
  ["Which shows that you are listening to a partner?", "eyes on your partner and a still body", ["fidgeting with a toy", "talking over them"], "Still bodies show focus."],
  ["Your friend finishes talking. What is a kind thing to say next?", "That's interesting! Can you tell me more?", ["Be quiet.", "I was not listening."], "Show interest."],
  ["You did not hear what someone said. What can you say?", "Could you say that again, please?", ["What? You mumbled.", "Nothing."], "Ask politely for clarification."],
  ["You are not sure what a word means. What can you ask?", "What does that word mean?", ["Why are you talking?", "I do not like this."], "Asking for the meaning clears things up."],
  ["Which question asks for more information?", "What happened next?", ["Yes.", "Maybe so."], "A question about what happened asks for details."],
  ["Which question helps you find out more about a friend's pet?", "What does your pet like to do?", ["I do not like pets.", "Pets."], "Ask a question with a question word."],
  ["A classmate says, “I built a fort.” Which is a good follow-up question?", "How did you build it?", ["Do you like cake?", "It is Monday."], "A related question shows you listened."],
  ["Which question is more specific?", "What colour was the bird's tail?", ["Tell me stuff.", "Birds?"], "A specific question asks about one detail."],
  ["When you speak to an Elder, you should…", "use respectful words", ["call out names", "interrupt"], "Speak with respect."],
  ["Which greeting is more formal?", "Good morning, Mr. Lee.", ["Yo!", "Hey you!"], "Formal greetings use polite words."],
  ["Which greeting is more informal, for a friend?", "Hi, Sam!", ["Dear Principal Smith,", "Good afternoon, ma'am."], "Informal talk is for friends."],
  ["You are thanking your teacher. Which is polite?", "Thank you for helping me.", ["Give me that.", "Whatever."], "Polite words show respect."],
  ["Which is an informal way to talk with a friend?", "Wanna play?", ["Would you care to join us, sir?", "May I address the committee?"], "Casual words are okay with friends."],
  ["Which is a formal way to ask a teacher for help?", "Excuse me, could you help me, please?", ["Hey, do my work.", "Help!"], "Say please and use a polite tone."],
  ["Why do we change how we talk with different people?", "to be respectful and clear", ["to be silly all the time", "to be hard to understand"], "Different people and places need different words."],
  ["It is your turn to talk in a group. What helps others understand you?", "speak clearly and in order", ["whisper and rush", "shout"], "Say things in a clear order.", true],
  ["You want to add to a friend's idea. What can you say?", "I like that idea, and I would add…", ["That is silly.", "No."], "Build on others' ideas.", true],
  ["Which shows you care what the group says?", "waiting for your turn to speak", ["calling out over others", "walking away"], "Take turns when you speak.", true],
  ["You can share your voice in class when you have something to say. Why does your voice matter?", "your ideas can help everyone", ["it never matters", "nobody listens"], "Everyone's ideas count.", true],
  ["A friend is shy. What can you do?", "invite them kindly to share", ["tease them", "ignore them"], "Kindness helps everyone join in.", true],
  ["You use a longer sentence to explain: “I like recess because we can run.” This is…", "a complex sentence", ["a single word", "a title"], "A longer sentence with “because” gives a reason.", true],
  ["Which sentence gives a reason?", "I am happy because it is Friday.", ["I am happy.", "It is Friday."], "Because introduces the reason.", true],
];

const mkLanguage = (id: string, title: string, emoji: string, blurb: string, parentNote: string, codes: string, text: string, items: Q[]) =>
  bankUnit({ id, title, emoji, blurb, parentNote, standards: [codes, text], items });

export const moreLanguage = [
  mkLanguage("mb-capitals-and-neat-writing", "Capitals, Letters and Spaces", "✏️", "Capital letters, tall and tail letters, and spaces between words.",
    "Using capital and lowercase letters correctly, forming letters with the right size and placement, spacing words, and typing with a keyboard.",
    "ELA.2.A2.2, ELA.2.C3.1", "capital and lowercase letters, letter formation, spacing and typing", LETTERS),
  mkLanguage("mb-sight-words-and-phrasing", "Sight Words and Reading with Expression", "📖", "Read common words quickly and use punctuation to read well.",
    "Recognizing common words quickly and noticing punctuation to read in phrases with the right pausing and expression.",
    "ELA.2.A2.6", "high-frequency words, and punctuation that guides phrasing", SIGHT),
  mkLanguage("mb-responding-to-stories", "Connections and Opinions", "💭", "Link stories to your life and share what you think.",
    "Making connections to texts, giving an opinion with reasons, recognizing that others can see things differently, and noticing who is shown in texts.",
    "ELA.2.B2.4, ELA.2.B3.1, ELA.2.B3.3, ELA.2.B3.4", "connections, opinions with reasons, different viewpoints and who is represented", RESPOND),
  mkLanguage("mb-finding-information", "Asking Questions and Finding Facts", "🔎", "Ask good questions, choose texts and learn topic words.",
    "Using what you know, asking basic questions, choosing texts and facts for a purpose, and using topic words.",
    "ELA.2.B1.1, ELA.2.B1.2, ELA.2.B1.3, ELA.2.B1.4, ELA.2.B2.7", "prior knowledge, questions, choosing texts and facts, and topic vocabulary", FINDING),
  mkLanguage("mb-planning-and-improving", "Plan, Write and Make It Better", "🗒️", "Plan ideas, pick a kind of writing and fix parts that do not make sense.",
    "Planning with lists and webs, different types of writing for different readers, revising unclear writing, and combining words, pictures and sound.",
    "ELA.2.C1.1, ELA.2.C1.2, ELA.2.C1.3, ELA.2.C1.4, ELA.2.C1.5, ELA.2.C2.5, ELA.2.C3.5", "planning, types of writing, revising and multimodal texts", PLAN),
  mkLanguage("mb-media-and-trust", "Media, Trust and Who Is in the Story", "📺", "Notice who made a message and whether to trust it.",
    "Recognizing media, deciding with guidance whether a source or character can be trusted, and noticing who is shown or missing in texts.",
    "ELA.2.B3.1, ELA.2.B3.2, ELA.2.C3.5", "media messages, trusting sources and characters, and representation", MEDIA),
  mkLanguage("mb-listening-and-asking", "Listening, Asking and Polite Talk", "👂", "Show you are listening, ask for more, and talk in the right way.",
    "Using non-verbal cues to show listening, asking questions to learn more, adding to others' ideas and changing how you talk for different people.",
    "ELA.2.A1.1, ELA.2.A1.2, ELA.2.A1.3, ELA.2.A1.4, ELA.2.A1.5, ELA.2.A1.6, ELA.2.D1.1", "listening, asking questions, speaking clearly and formal or informal talk", LISTEN),
];
