import { bankUnit, type Q } from "../own";

// Grade 2 mathematics: skip counting, even and odd numbers, ordinals (2.N.1 to 2.N.3) and days, weeks, months (2.SS.1).

const COUNT: Q[] = [
  ["Count by 2s: 2, 4, 6, __", "8", ["7", "9"], "Add 2 each time. 6 and 2 more is 8."],
  ["Count by 2s: 10, 12, 14, __", "16", ["15", "18"], "Add 2 each time. 14 and 2 more is 16."],
  ["Count by 2s: 20, 22, 24, __", "26", ["25", "28"], "Add 2 each time. 24 and 2 more is 26."],
  ["Count by 5s: 5, 10, 15, __", "20", ["16", "25"], "Add 5 each time. 15 and 5 more is 20."],
  ["Count by 5s: 25, 30, 35, __", "40", ["36", "45"], "Add 5 each time. 35 and 5 more is 40."],
  ["Count by 5s: 50, 55, 60, __", "65", ["61", "70"], "Add 5 each time. 60 and 5 more is 65."],
  ["Count by 10s: 10, 20, 30, __", "40", ["31", "50"], "Add 10 each time. 30 and 10 more is 40."],
  ["Count by 10s: 40, 50, 60, __", "70", ["61", "80"], "Add 10 each time. 60 and 10 more is 70."],
  ["Count by 10s: 70, 80, 90, __", "100", ["91", "110"], "Add 10 each time. 90 and 10 more is 100."],
  ["Count back by 2s: 12, 10, 8, __", "6", ["7", "4"], "Take away 2 each time. 8 take away 2 is 6."],
  ["Count back by 2s: 20, 18, 16, __", "14", ["15", "12"], "Take away 2 each time. 16 take away 2 is 14."],
  ["Count back by 5s: 30, 25, 20, __", "15", ["19", "10"], "Take away 5 each time. 20 take away 5 is 15."],
  ["Count back by 5s: 60, 55, 50, __", "45", ["49", "40"], "Take away 5 each time. 50 take away 5 is 45."],
  ["Count back by 10s: 80, 70, 60, __", "50", ["59", "40"], "Take away 10 each time. 60 take away 10 is 50."],
  ["Count back by 10s: 100, 90, 80, __", "70", ["79", "60"], "Take away 10 each time. 80 take away 10 is 70."],
  ["Which number comes next? 4, 6, 8, 10, __", "12", ["11", "14"], "These numbers go up by 2."],
  ["Which number comes next? 15, 20, 25, 30, __", "35", ["31", "40"], "These numbers go up by 5."],
  ["Which number comes next? 30, 40, 50, 60, __", "70", ["61", "80"], "These numbers go up by 10."],
  ["Which number is missing? 2, 4, __, 8, 10", "6", ["5", "7"], "Count by 2s: 2, 4, 6, 8, 10."],
  ["Which number is missing? 5, __, 15, 20, 25", "10", ["11", "12"], "Count by 5s: 5, 10, 15, 20, 25."],
  ["Which number is missing? 10, 20, __, 40, 50", "30", ["35", "25"], "Count by 10s: 10, 20, 30, 40, 50."],
  ["You have 5 hands. Each hand has 5 fingers. Count by 5s: how many fingers in all?", "25", ["20", "30"], "Count by 5s five times: 5, 10, 15, 20, 25.", true],
  ["There are 6 pairs of mittens. Count by 2s: how many mittens?", "12", ["10", "14"], "Count by 2s six times: 2, 4, 6, 8, 10, 12.", true],
  ["Count by 10s: 7 dimes make how many cents?", "70", ["17", "7"], "Count by 10s seven times: 10, 20, 30, 40, 50, 60, 70.", true],
  ["Count back by 5s from 50. What are the next two numbers?", "45, 40", ["49, 48", "40, 30"], "Take away 5 each time: 50, 45, 40.", true],
  ["Count by 2s starting at 1: 1, 3, 5, __", "7", ["6", "8"], "Add 2 each time. 5 and 2 more is 7.", true],
];

const EVEN: Q[] = [
  ["Is 6 even or odd?", "even", ["odd", "neither"], "6 objects can be put into pairs with none left over."],
  ["Is 7 even or odd?", "odd", ["even", "neither"], "7 objects make 3 pairs with 1 left over."],
  ["Is 10 even or odd?", "even", ["odd", "neither"], "10 makes 5 pairs with none left over."],
  ["Is 13 even or odd?", "odd", ["even", "neither"], "13 makes 6 pairs with 1 left over."],
  ["Is 18 even or odd?", "even", ["odd", "neither"], "18 makes 9 pairs with none left over."],
  ["Is 25 even or odd?", "odd", ["even", "neither"], "25 makes 12 pairs with 1 left over."],
  ["Is 40 even or odd?", "even", ["odd", "neither"], "Numbers that end in 0 are even."],
  ["Is 51 even or odd?", "odd", ["even", "neither"], "Numbers that end in 1 are odd."],
  ["Which number is even?", "14", ["15", "17"], "An even number can be split into two equal groups."],
  ["Which number is odd?", "9", ["8", "12"], "An odd number always has one left over when you make pairs."],
  ["Pick the even number.", "32", ["33", "35"], "Even numbers end in 0, 2, 4, 6 or 8."],
  ["Pick the odd number.", "47", ["46", "48"], "Odd numbers end in 1, 3, 5, 7 or 9."],
  ["8 children make pairs. How many are left without a partner?", "0", ["1", "2"], "8 is even, so every child has a partner."],
  ["9 children make pairs. How many are left without a partner?", "1", ["0", "2"], "9 is odd, so one child has no partner."],
  ["Which group of counters can be put into pairs with none left over?", "12 counters", ["11 counters", "13 counters"], "12 is an even number."],
  ["Which group of counters has one left over when put into pairs?", "15 counters", ["14 counters", "16 counters"], "15 is an odd number."],
  ["Which number ends in an even digit?", "76", ["75", "79"], "The digits 0, 2, 4, 6 and 8 are even."],
  ["Which of these numbers is odd?", "63", ["60", "64"], "63 ends in 3, which is odd."],
  ["The first four odd numbers are 1, 3, 5 and…", "7", ["6", "8"], "Odd numbers go up by 2."],
  ["The first four even numbers are 2, 4, 6 and…", "8", ["7", "9"], "Even numbers go up by 2."],
  ["Who is 3rd in line? A cat is first, a dog is second, a fish is third.", "the fish", ["the cat", "the dog"], "First, second, third: the fish is third."],
  ["What is the 1st month of the year?", "January", ["February", "December"], "The year starts with January."],
  ["In a line of 5 children, which place is the last child in?", "5th", ["4th", "6th"], "The fifth child is the last one in a line of 5."],
  ["Which one means “in position number 2”?", "2nd", ["1st", "3rd"], "2nd means second."],
  ["Is the sum 4 + 4 even or odd?", "even", ["odd", "neither"], "Two equal groups always make an even number.", true],
  ["Is 3 + 4 even or odd?", "odd", ["even", "neither"], "3 + 4 = 7, and 7 is odd.", true],
  ["Is 5 + 5 even or odd?", "even", ["odd", "neither"], "5 + 5 = 10, and 10 is even.", true],
];

const CALENDAR: Q[] = [
  ["How many days are in a week?", "7", ["5", "10"], "Sunday to Saturday is 7 days."],
  ["How many months are in a year?", "12", ["10", "7"], "January to December is 12 months."],
  ["Which day comes after Monday?", "Tuesday", ["Sunday", "Wednesday"], "Monday, then Tuesday."],
  ["Which day comes before Friday?", "Thursday", ["Saturday", "Wednesday"], "Thursday, then Friday."],
  ["Which day comes after Saturday?", "Sunday", ["Friday", "Monday"], "Saturday is followed by Sunday."],
  ["Which day comes between Tuesday and Thursday?", "Wednesday", ["Monday", "Friday"], "Tuesday, Wednesday, Thursday."],
  ["Which month comes after March?", "April", ["February", "May"], "March, then April."],
  ["Which month comes before July?", "June", ["August", "May"], "June, then July."],
  ["What is the first month of the year?", "January", ["March", "December"], "A new year begins in January."],
  ["What is the last month of the year?", "December", ["November", "January"], "December is month number 12."],
  ["Which month comes between September and November?", "October", ["August", "December"], "September, October, November."],
  ["Which of these is a month?", "May", ["Monday", "Summer"], "May is one of the 12 months."],
  ["Which of these is a day of the week?", "Thursday", ["April", "Winter"], "Thursday is one of the 7 days."],
  ["Is a week longer or shorter than a month?", "shorter", ["longer", "the same"], "A month has about 4 weeks."],
  ["Is a year longer or shorter than a week?", "longer", ["shorter", "the same"], "A year has 12 months, and a week is only 7 days."],
  ["Which is longer?", "a month", ["a day", "a week"], "A month is about 30 days."],
  ["Which is shorter?", "a day", ["a week", "a year"], "A week has 7 days."],
  ["Which two days are the weekend?", "Saturday and Sunday", ["Monday and Tuesday", "Friday and Monday"], "Many families rest on Saturday and Sunday."],
  ["School starts on Monday. How many days until the next Monday?", "7", ["5", "6"], "A whole week is 7 days.", true],
  ["Today is Tuesday. What day is it in 2 days?", "Thursday", ["Wednesday", "Friday"], "Tuesday, Wednesday, Thursday.", true],
  ["Today is Friday. What day was it 3 days ago?", "Tuesday", ["Wednesday", "Monday"], "Count back: Thursday, Wednesday, Tuesday.", true],
  ["It is January. What month comes 2 months later?", "March", ["February", "April"], "January, February, March.", true],
  ["Which month comes 2 months after October?", "December", ["November", "January"], "October, November, December.", true],
  ["How many days are in 2 weeks?", "14", ["12", "9"], "7 + 7 = 14.", true],
  ["Kiran has a birthday every year. How many months until it comes again?", "12", ["7", "10"], "A year is 12 months.", true],
  ["Which month has Canada Day (July 1)?", "July", ["June", "August"], "Canada Day is on the first day of July."],
];

export const skipCounting = bankUnit({
  id: "mb-skip-counting",
  title: "Skip Counting",
  emoji: "🦘",
  blurb: "Count by 2s, 5s and 10s, forward and back.",
  parentNote: "Skip counting by 2s, 5s and 10s forward and backward from 0 to 100, using a hundred chart or number line.",
  standards: ["2.N.1", "skip counting by 2s, 5s and 10s forward and backward"],
  items: COUNT,
});

export const evenOdd = bankUnit({
  id: "mb-even-odd",
  title: "Even, Odd and Ordinals",
  emoji: "🧦",
  blurb: "Pair things up, and say who is first, second or third.",
  parentNote: "Deciding whether a number up to 100 is even or odd by making pairs, and using ordinal numbers for position.",
  standards: ["2.N.2, 2.N.3", "even and odd numbers, and ordinal numbers"],
  items: EVEN,
});

export const calendar = bankUnit({
  id: "mb-calendar",
  title: "Days, Weeks and Months",
  emoji: "📅",
  blurb: "How many days make a week and months make a year?",
  parentNote: "Relating days to a week and months to a year, using a calendar to solve simple problems.",
  standards: ["2.SS.1", "days in a week and months in a year"],
  items: CALENDAR,
});
