import { bankUnit, type Q } from "../own";

// Grade 2 social studies: Our Community (2-KI, 2-KL, 2-KH, 2-V and 2-S outcomes) and Canada's Communities.

const COMMUNITY: Q[] = [
  ["What is a community?", "a group of people who live, work or play in the same place", ["a single house", "a kind of animal"], "A community is people and the place they share."],
  ["Which is part of a community?", "a school", ["the Moon", "a volcano on Mars"], "Schools, stores and parks are in communities."],
  ["Which service helps keep a community safe?", "the fire department", ["a toy shop", "a movie poster"], "Firefighters keep people safe."],
  ["Which service takes care of sick people?", "a hospital or clinic", ["a library", "a pizza shop"], "Health services are in communities."],
  ["Which place is where children learn?", "a school", ["a bakery", "a gas station"], "Schools are for learning."],
  ["Which place lends books for free?", "a library", ["a bank", "a bakery"], "Libraries are open to everyone."],
  ["Which is a way to travel in a community?", "a bus", ["a volcano", "a cloud"], "Buses are public transportation."],
  ["Which is a kind of transportation?", "a bicycle", ["a sandwich", "a hat"], "Bicycles help people travel."],
  ["Which is a natural feature of a community?", "a river", ["a bridge", "a store"], "Rivers are natural."],
  ["Which is a constructed (built) feature of a community?", "a bridge", ["a lake", "a hill"], "People build bridges."],
  ["Which is a natural feature?", "a hill", ["a road", "a library"], "Hills are landforms."],
  ["Which is a built feature?", "a school building", ["a prairie", "a lake"], "People build schools."],
  ["Climate is…", "the usual weather in a place over many years", ["today's lunch", "a kind of rock"], "Climate describes a place's weather."],
  ["Which describes the climate of Manitoba?", "cold winters and warm summers", ["no seasons", "hot all year"], "Manitoba has four seasons."],
  ["Which is a landform?", "a hill", ["a school", "a road"], "A landform is a shape of the land."],
  ["Which is a waterway?", "a river", ["a hill", "a field"], "A waterway is a path of water."],
  ["Winnipeg is built near where two rivers meet. Which two rivers?", "Red River and Assiniboine River", ["Nile and Amazon", "Fraser and Peace"], "The Forks is where the Red and Assiniboine meet."],
  ["Why do people build communities near water?", "they need it to drink, grow food and travel", ["water has no use", "rivers are loud"], "Water is important for life."],
  ["Which characteristic is common to most communities?", "people live and work together", ["no one lives there", "no rules exist"], "People share a place.", true],
  ["A community of 200 people in the north is different from a big city. Which could be different?", "the number of stores and services", ["the number of days in a week", "the colour of the sky"], "Communities differ in size and services.", true],
  ["Which are services in a town?", "schools, libraries and fire halls", ["dragons", "pirate ships"], "Services help people.", true],
  ["Which of these shows the climate of a place?", "It snows every winter.", ["It rained today.", "I wore blue."], "Climate is the pattern over many years.", true],
  ["Cultural groups in a community may share…", "languages, foods and celebrations", ["the same height", "the same shoes"], "Culture includes language, food and traditions.", true],
  ["Which is a way to find a cultural group in your community?", "a festival or community event", ["a locked room", "a sleeping bag"], "Events bring cultural groups together.", true],
  ["Which question helps you describe your community?", "What buildings and services are here?", ["What is on Jupiter?", "What colour is a lion?"], "Describe what you can see and find.", true],
  ["Which place in a community is for playing?", "a park", ["a post office", "a fire station"], "Parks are for play.", true],
];

const WHOWEARE: Q[] = [
  ["Which helps shape who you are?", "your family", ["a random number", "the shape of a cloud"], "Family is a big part of who you are."],
  ["Which helps shape who you are?", "the language you speak", ["the weather on Mars", "an unknown rock"], "Language is part of identity."],
  ["Which helps shape who you are?", "the place where you live", ["a bird in China", "a star far away"], "Where you live is part of you."],
  ["Which helps shape who you are?", "traditions in your family", ["a closed door", "an empty bag"], "Traditions are habits that families share."],
  ["A tradition is…", "something a group does again and again", ["a one-time accident", "a type of cloud"], "Traditions are passed on."],
  ["Which is an example of a family tradition?", "baking a special bread each holiday", ["tripping on a step", "losing a sock"], "Traditions are repeated on purpose."],
  ["Your culture includes…", "foods, music and ways of celebrating", ["only your shoe size", "only your age"], "Culture is how a group lives."],
  ["Your heritage is…", "what comes to you from your family and ancestors", ["a game you made up today", "an animal"], "Heritage is passed from earlier generations."],
  ["Some people are First Nations, Métis or Inuit. This is part of their…", "heritage and culture", ["weather", "address only"], "These are distinct peoples with their own cultures."],
  ["Some Manitobans have francophone heritage. This means…", "their ancestors spoke French", ["they never speak", "they live in the water"], "Francophone means French-speaking."],
  ["A group you may belong to is…", "your class", ["a lonely rock", "a tree stump"], "A class is a group."],
  ["Which is a group that shares a language?", "a French-speaking community", ["a pile of bricks", "a snow bank"], "Language groups share words."],
  ["Which is a community group?", "a sports team", ["a puddle", "a lamp"], "Teams are groups."],
  ["Which group might you belong to?", "a family", ["a shoe", "a pencil"], "Families are groups."],
  ["Which makes you feel you belong?", "being welcome in a group", ["being left out", "being teased"], "Welcome helps us belong."],
  ["Why is it good to value the groups you belong to?", "they support you and help you learn", ["they never help", "they make you worse"], "Groups give support."],
  ["Which cultural group might you find in a Manitoba community?", "Ukrainian, Filipino, Métis or Cree families, and many more", ["only one group", "no groups"], "Manitoba is home to many cultural groups."],
  ["Which food might be part of a family's heritage?", "bannock or perogies or pho, depending on the family", ["a rock", "a crayon"], "Foods often come from heritage."],
  ["Why can it be fun to learn about other people's traditions?", "we learn new ways of living", ["it is boring", "it is wrong"], "Learning about others builds understanding.", true],
  ["Elders share stories and teachings with their communities. This helps young people…", "know who they are and where they come from", ["forget their past", "stop learning"], "Stories connect generations.", true],
  ["Your ancestors are…", "family members who lived long ago", ["next-door neighbours", "your classmates"], "Ancestors come before us.", true],
  ["When you learn a story from a grandparent, you are connected to…", "the past, the present and the future", ["only yesterday", "nothing"], "Stories link time.", true],
  ["Which is a way to share your heritage with the class?", "tell about a family tradition", ["hide it", "make fun of others"], "Sharing helps others know you.", true],
  ["Which would you say about a classmate whose family has a different tradition from yours?", "I would like to hear about it.", ["That is weird.", "It is wrong."], "Be curious and kind.", true],
  ["A friend has a different home language. What is a kind thing to do?", "learn a word in that language", ["laugh", "avoid them"], "Learning words is respectful.", true],
];

const PAST: Q[] = [
  ["Which word tells about a long time ago?", "past", ["future", "tomorrow"], "The past is what happened earlier."],
  ["Which word tells what will happen later?", "future", ["past", "yesterday"], "The future is still to come."],
  ["Which word tells about today?", "present", ["ancient", "last year"], "The present is now."],
  ["Which came first?", "yesterday", ["tomorrow", "next week"], "Yesterday is in the past."],
  ["Which time word means 'a very long time ago'?", "long ago", ["right now", "soon"], "Long ago is far in the past."],
  ["A story about a flood in a town long ago is a story of…", "the community's past", ["next year", "a game"], "It tells about a past event."],
  ["Who can tell you stories about your community's past?", "Elders and long-time neighbours", ["a rock", "a toy"], "People who lived there remember."],
  ["Elders in many First Nations and Métis communities share…", "stories and teachings", ["nothing at all", "only numbers"], "Oral history is passed on by telling."],
  ["Oral history means…", "stories passed down by telling", ["a paint colour", "a type of tool"], "Oral means spoken."],
  ["Why is oral history important to the land?", "stories teach about places and how to care for them", ["stories are never true", "land has no stories"], "Many peoples share stories about places."],
  ["Francophone communities in Manitoba have stories of…", "settlers and events in their French-speaking past", ["nothing", "the Moon"], "Saint-Boniface has a long francophone story."],
  ["Which is a way to learn about events in your community's past?", "ask someone older", ["close your ears", "forget it"], "Ask people who remember."],
  ["Order these: first, next, last. Which order tells a day?", "wake up, go to school, go to bed", ["go to bed, wake up, go to school", "go to school, go to bed, wake up"], "Events happen in order."],
  ["A story is told in order of time. We call that…", "chronological order", ["backwards order", "no order"], "Chronological means in order of time."],
  ["Which sentence is in the right order? Spring, summer, autumn, ___", "winter", ["spring", "summer"], "Seasons come in a cycle."],
  ["Which came first in a person's life?", "being a baby", ["being a grandparent", "being an adult"], "A baby is the youngest stage."],
  ["Which timeline order is correct?", "baby, child, teenager, adult", ["adult, child, baby, teenager", "teenager, baby, adult, child"], "Life stages go in order."],
  ["A place that used to have a one-room school now has a big school. This shows that communities…", "change over time", ["never change", "always shrink"], "Communities grow and change.", true],
  ["Why do we keep stories of a community's past?", "to remember and learn from them", ["to forget them", "to hide them"], "Stories help us learn.", true],
  ["A grandparent says, “When I was your age, we had no internet.” This is a story from…", "the past", ["the future", "next year"], "It happened long ago.", true],
  ["Which word fits a story set 100 years ago?", "long ago", ["tomorrow", "this minute"], "A century is a long time.", true],
  ["Why might we feel connected to stories of our community?", "they are about people and places we know", ["they are about nobody", "they are about nothing"], "Personal connection grows from shared places.", true],
  ["A museum helps us learn about…", "the past", ["next week's lunch", "the shape of a cloud"], "Museums keep objects from earlier times.", true],
  ["A photograph from long ago shows a horse and wagon. What does this tell us?", "how people travelled in the past", ["how people travel today", "the weather tomorrow"], "Old photos show the past.", true],
  ["Which is the best source for facts about a local event many years ago?", "someone who was there or a local history book", ["a guess", "a made-up story"], "Use good sources.", true],
];

const MAPS: Q[] = [
  ["Which direction is straight up on most maps?", "north", ["south", "east"], "North is usually at the top."],
  ["Which direction is opposite north?", "south", ["east", "west"], "South is the opposite of north."],
  ["Which direction is opposite east?", "west", ["north", "south"], "West is opposite east."],
  ["The four cardinal directions are north, south, east and…", "west", ["up", "left"], "Cardinal directions are N, S, E and W."],
  ["Where does the Sun rise?", "in the east", ["in the west", "in the south"], "The Sun rises in the east."],
  ["Where does the Sun set?", "in the west", ["in the east", "in the north"], "The Sun sets in the west."],
  ["What is a map title?", "it tells what the map shows", ["a colour", "a rock"], "The title is the name of the map."],
  ["What does a map legend (key) show?", "what the symbols mean", ["the map's colour", "who drew it"], "A legend explains symbols."],
  ["On a map, a small picture or shape that stands for something is a…", "symbol", ["spell", "title"], "A symbol stands for something real."],
  ["On a map legend, a blue line often stands for…", "a river", ["a road", "a school"], "Blue usually shows water."],
  ["On a map legend, a small square with a flag often stands for…", "a school", ["a lake", "a mountain"], "The legend tells you what each symbol means."],
  ["What do you look at to know what a symbol means?", "the legend", ["the sky", "the back of your hand"], "The legend explains the symbols."],
  ["A map of your classroom shows the door on the east wall. If you stand facing north, the door is on your…", "right", ["left", "back"], "East is to the right when you face north."],
  ["You face north. Which direction is behind you?", "south", ["east", "west"], "Behind you is the opposite direction."],
  ["You face north. Which direction is to your left?", "west", ["east", "south"], "West is on your left when you face north."],
  ["The library is east of the school. Where is the school from the library?", "west", ["north", "east"], "Directions are opposites."],
  ["The park is north of the pond. Where is the pond from the park?", "south", ["north", "west"], "South is opposite north."],
  ["Which of these would you put on a map of your school?", "a title, a legend and symbols", ["a joke", "a shopping list"], "These help others read the map."],
  ["To make a map of your classroom, you should include…", "a title and a legend", ["nothing", "a song"], "A good map has a title and legend.", true],
  ["Which symbol could stand for a tree on a map?", "a small green tree picture", ["a thundercloud", "a red car"], "Symbols should look like what they stand for.", true],
  ["On a map of Manitoba, a star often marks…", "the capital city", ["a lake", "a farm"], "Many maps mark capitals with a star.", true],
  ["You are at the north end of the playground. To get to the south end you walk…", "south", ["north", "up"], "Go the opposite direction.", true],
  ["The legend shows a blue square for a pond. The map shows a blue square beside the school. What is beside the school?", "a pond", ["a road", "a hill"], "Use the legend to read the symbol.", true],
  ["Which two directions could be on a compass at right angles to each other?", "north and east", ["north and south", "east and west"], "North and east make a corner.", true],
  ["On a map, why is a title important?", "it tells what the map is about", ["it makes the map bigger", "it is a game"], "A title names the map.", true],
];

const DIVERSE: Q[] = [
  ["Which describes Canada?", "a country with many different peoples and cultures", ["a country with one culture", "a small island"], "Canada is diverse."],
  ["Which people were in Canada long before settlers arrived?", "First Nations, Métis and Inuit", ["Only visitors from far away", "No one"], "Indigenous Peoples have lived here since long before Canada became a country."],
  ["First Nations, Métis, Inuit and francophone communities are part of…", "the Canadian community", ["only one province", "no community"], "They all belong to Canada."],
  ["Which of these is a francophone community in Manitoba?", "Saint-Boniface", ["Yellowknife", "Churchill Falls"], "Saint-Boniface has a long francophone history."],
  ["Which of these might be a francophone celebration in Manitoba?", "Festival du Voyageur", ["a hockey playoff", "a farmers' day"], "The Festival du Voyageur is held in Winnipeg every winter."],
  ["Many place names in Canada come from…", "First Nations languages, French, English and other languages", ["only one language", "computer codes"], "Place names tell about the languages and people of an area."],
  ["The name Manitoba comes from…", "a word from Cree or Ojibwe", ["a French word for cold", "an English word for flat"], "It comes from Indigenous words."],
  ["The name Winnipeg comes from a Cree word meaning…", "muddy water", ["clear sky", "tall mountain"], "Win-nipi means muddy waters."],
  ["The name Saskatchewan comes from…", "a Cree word for a swiftly flowing river", ["a Latin word for sand", "a French word for wheat"], "It comes from the Cree word kisiskâciwani-sîpiy."],
  ["Place names in Quebec are often…", "French", ["Greek", "Japanese"], "Many Quebec place names are French."],
  ["Which Canadian celebration has French roots?", "Fête nationale", ["Groundhog Day", "Halloween"], "French Canadians celebrate it in June.", true],
  ["Immigration means…", "people moving to a new country to live", ["visiting a zoo", "sleeping on a train"], "Immigrants come to make a new home."],
  ["Many people came to Canada from other parts of the world to…", "make new homes and communities", ["go back the next day", "climb the Moon"], "Settlers built communities."],
  ["Which food in Canada comes from many cultures?", "perogies, pizza and butter chicken", ["only plain bread", "nothing"], "Food connects us to other places."],
  ["Which shows that Canada is linked to other countries?", "we eat foods from around the world", ["we have no friends", "our country is alone"], "Foods, music and travel connect us."],
  ["Which kind of media connects Canada to other countries?", "a movie from another country", ["a closed door", "an empty room"], "Movies show other places."],
  ["Which Canadian region is known for grain?", "the Prairies", ["the Arctic", "the West Coast"], "Prairie farms grow wheat and canola."],
  ["Which Canadian region is known for lumber (wood)?", "the West Coast", ["the Prairies", "the Arctic islands"], "British Columbia has large forests."],
  ["Which Canadian region is known for fishing?", "the Atlantic coast", ["the Prairies", "the northern forests"], "Atlantic fishers catch cod, lobster and more."],
  ["Which Canadian region is known for mines?", "the North", ["the Gulf Islands", "the Great Lakes cities"], "Northern Canada has many mines."],
  ["Prairie grain helps people in other communities by…", "giving them bread and cereal", ["making rain", "building bridges"], "Our quality of life depends on many communities.", true],
  ["How does lumber from the West Coast help people on the Prairies?", "it is used to build houses", ["it makes snow", "it grows wheat"], "Goods travel across Canada.", true],
  ["Why is it good to value people's different ways of life?", "we learn from each other", ["it makes things worse", "it is not allowed"], "Respect and curiosity help communities.", true],
  ["Poems, paintings and songs about the land show that…", "people see and feel the land in different ways", ["there is one right picture", "art is not about places"], "Art shows many ways of seeing.", true],
  ["Which sentence shows being willing to consider other points of view?", "I will listen to your idea first.", ["I only listen to myself.", "Your idea is silly."], "Open minds help us understand.", true],
  ["Being a member of the Canadian community means…", "we share a country and look after each other", ["we do not belong", "we are alone"], "We belong together.", true],
  ["Which sentence is TRUE?", "Canada has many languages, including Indigenous languages.", ["Canada has only one language.", "Canada has no languages."], "Canada has many languages.", true],
];

const WORKING: Q[] = [
  ["You and a partner share one set of markers. A fair plan is to…", "take turns", ["grab them all", "hide them"], "Sharing is fair."],
  ["A group needs to choose a game. A fair way is to…", "vote or take turns choosing", ["let the loudest decide", "choose for everyone"], "Voting is fair."],
  ["Each person in a group has a job. This is called…", "sharing responsibilities", ["doing nothing", "arguing"], "Everyone helps."],
  ["Which sentence shows you are listening?", "You said you want a turn. I can wait.", ["Whatever.", "I was not listening."], "Show you heard."],
  ["Which sentence is respectful?", "I see it differently. Can I tell you why?", ["That is dumb.", "Shut up."], "Speak kindly."],
  ["Which words are respectful?", "please and thank you", ["give me", "go away"], "Kind words show respect."],
  ["Two friends argue. A fair way to solve it is to…", "listen to both sides", ["let one win always", "yell more"], "Both people should be heard."],
  ["How can you solve a problem without fighting?", "talk and find a plan", ["push", "call names"], "Peaceful words work."],
  ["Which helps solve a conflict peacefully?", "cool down, then talk", ["say mean things", "run away and hide"], "A calm voice helps."],
  ["You and a friend both want the swing. What is a fair plan?", "take turns for a few minutes each", ["fight for it", "tell on the friend"], "Turn-taking is fair."],
  ["Everyone has the right to be heard. This means…", "we let others speak", ["only one talks", "nobody talks"], "Everyone's voice counts."],
  ["Which is a way to be fair?", "follow the same rules for everyone", ["make different rules for each person", "break the rules"], "Fair means equal chances."],
  ["Which is a way to cooperate?", "work together to clean up", ["leave a mess for others", "tell others to do it all"], "Cooperation shares the work."],
  ["When people agree on a plan, they have reached…", "an agreement", ["a mess", "a mistake"], "Agreeing makes a shared plan."],
  ["Leaders should be sensitive to others. This means…", "noticing how people feel", ["ignoring feelings", "making fun"], "Sensitive leaders care."],
  ["A leader notices that a child is left out of the game. What is a good leader move?", "invite them to join", ["leave them alone", "laugh"], "Good leaders include others."],
  ["Who contributes to a community?", "everyone who helps in some way", ["only the mayor", "no one"], "Everyone can contribute."],
  ["A neighbour shovels the walk for an older person. They are…", "contributing to the community", ["wasting time", "causing trouble"], "Helping is a contribution."],
  ["Why do we thank people who help our community?", "it shows we value their work", ["it is a rule of math", "it makes them leave"], "Gratitude matters.", true],
  ["Which sentence shows you value your community?", "I help keep our park clean.", ["I drop litter.", "I do not care."], "Caring is action.", true],
  ["A group cannot agree. What is a peaceful next step?", "ask for more ideas and try again", ["end the group", "keep arguing"], "Try again with new ideas.", true],
  ["You disagree with a friend. How can you show respect?", "say what you think without put-downs", ["call them names", "leave them out"], "Respect means no put-downs.", true],
  ["Why should we think about the rights of others?", "everyone deserves to be treated fairly", ["only some people matter", "it is a game"], "Everyone's rights matter.", true],
  ["Which is a way to volunteer?", "help at a school fundraiser", ["break a toy", "stay in bed"], "Volunteering is giving time.", true],
  ["A leader asks, “What do you think?” and then listens. What is the leader showing?", "respect for other ideas", ["a lack of care", "a wish to talk only"], "Good leaders listen.", true],
];

const FINDOUT: Q[] = [
  ["Where can you find information about your community?", "a library, a person or a website", ["a locked box", "a blank wall"], "Many sources give information."],
  ["Which source has pictures and facts about Canada?", "an atlas or an information book", ["a cartoon", "a toy"], "Atlases and books give facts."],
  ["You can learn by…", "looking, listening and reading", ["sleeping", "ignoring"], "Use your senses and sources."],
  ["A chart that puts information in rows and columns is a…", "table", ["spell", "joke"], "A table is a visual organizer."],
  ["A web helps you organize…", "ideas and facts about a topic", ["your shoes", "your pencils"], "A web shows how ideas connect."],
  ["Which is a visual organizer?", "a chart", ["a spoon", "a coat"], "Charts, webs and tables organize facts."],
  ["Which question would you ask for a research project about your town?", "How did our town get its name?", ["Yes.", "Town."], "Research questions ask for information."],
  ["Which is a good research question?", "What jobs do people have in our community?", ["Jobs", "Yes or no"], "Questions begin with question words."],
  ["Which tool could you use to find a place on a map?", "an atlas or globe", ["a spoon", "a pencil case"], "Atlases show places."],
  ["Which tool lets you see a map online?", "a computer or tablet", ["a rock", "a boot"], "Electronic tools can show maps."],
  ["Two answers to a problem: A is quick but messy, B takes longer but is neat. What do we weigh?", "advantages and disadvantages", ["the colour of the paper", "the day of the week"], "Weigh good and bad points."],
  ["An advantage of walking to school is that it…", "gives exercise and fresh air", ["takes no time ever", "is always warm"], "Walking is healthy."],
  ["A disadvantage of walking to school in winter is that it…", "can be cold", ["is a sunny day", "is flat"], "Cold is a downside."],
  ["You see many people at the park on warm days. What opinion might you form?", "Many people like the park in summer.", ["No one likes parks.", "Parks are always empty."], "Opinions come from information you notice."],
  ["You learn a new fact that does not fit your idea. What should you do?", "think again and maybe change your idea", ["ignore the new fact", "hide the fact"], "Revising ideas is smart."],
  ["Which sentence gives a reason for an opinion?", "I think the library is useful because it has free books.", ["I think the library.", "The library."], "Reasons use because."],
  ["Which is a good way to share what you learned?", "make a poster or give a short talk", ["keep it secret", "tear it up"], "Share ideas in different ways."],
  ["You can present information…", "orally, visually, concretely or electronically", ["only by yelling", "never"], "There are many ways to present.", true],
  ["Which source might have a TV ad for a snack?", "TV or online media", ["a rock", "a mitten"], "Media includes ads.", true],
  ["Media can influence what children choose. For example, an ad can make you want…", "a toy or a snack", ["the weather", "the day"], "Ads try to change what people want.", true],
  ["Which is a smart question to ask about an ad?", "Is this ad trying to sell me something?", ["What colour is the TV?", "Where is the remote?"], "Questioning media helps us choose.", true],
  ["When you present your ideas, the best order is…", "beginning, middle, end", ["end, beginning, middle", "random"], "A clear order helps listeners.", true],
  ["You gather information from an Elder, a book and a website. You are using…", "more than one source", ["one source", "no sources"], "Several sources help.", true],
  ["After the class has voted, you notice a different view could also be fair. You should…", "listen to the new idea", ["ignore it", "tease them"], "Be open to other points of view.", true],
  ["You tell a story of your day in the order it happened. You are using…", "chronological order", ["no order", "random order"], "Tell events in order of time.", true],
];

const mk = (id: string, title: string, emoji: string, blurb: string, parentNote: string, codes: string, text: string, items: Q[]) =>
  bankUnit({ id, title, emoji, blurb, parentNote, standards: [codes, text], items });

export const moreSocial = [
  mk("mb-what-makes-a-community", "What Makes a Community?", "🏘️", "Services, transportation, landforms and the features of where we live.",
    "Describing the characteristics of local communities, including services, transportation, schools, cultural groups, and natural and built features.",
    "2-KI-004, 2-KI-005, 2-KI-006, 2-KL-019", "characteristics of communities, cultural groups, and natural and constructed features", COMMUNITY),
  mk("mb-who-we-are", "Who I Am and Where I Belong", "🧒", "Family, language, traditions and the groups we belong to.",
    "Factors that shape identity such as family, language, community and traditions, groups a child belongs to, heritage, and how Elders and ancestors connect people to the past.",
    "2-KI-007, 2-KI-008, 2-KI-008A, 2-KI-009, 2-KI-010, 2-KI-010A, 2-KI-010F, 2-VI-005", "identity, heritage and culture, groups and the stories of Elders and communities", WHOWEARE),
  mk("mb-community-stories", "Stories of Our Community's Past", "📜", "Long ago, now and later, and stories told by Elders and neighbours.",
    "Telling stories of people and events in a community's past, telling events in order, using time words, and valuing oral history as a way to learn about the land.",
    "2-KH-025, 2-KH-025A, 2-KH-025F, 2-VH-008, 2-VH-008A, 2-VH-008F, 2-VH-009, 2-S-202, 2-S-404", "stories of the past, oral history, time words and chronological order", PAST),
  mk("mb-maps-and-directions", "Maps, Legends and Directions", "🧭", "Read and make maps with a title, a legend and symbols.",
    "Reading and making maps with a title, legend and symbols, using north, south, east and west, and locating a community on a map.",
    "2-KL-018, 2-S-205, 2-S-206, 2-S-207", "locating a community, map titles, legends and symbols, and cardinal directions", MAPS),
  mk("mb-diverse-canada", "Many Peoples, Many Places", "🇨🇦", "Place names, francophone and Indigenous communities, and connections across Canada.",
    "The diversity of Canada, place name origins, francophone influences, how newcomers have built communities, links to other countries, and goods that come from different regions.",
    "2-KI-011, 2-KI-013, 2-KH-028, 2-KH-029, 2-KH-030, 2-KG-032, 2-VE-013, 2-VI-006, 2-VI-006A, 2-VI-006F, 2-VL-007, 2-VG-010, 2-VC-003", "diversity in Canada, place names, francophone influence, newcomers, global links and regional products", DIVERSE),
  mk("mb-working-together", "Working Together Fairly", "🤝", "Take turns, listen, solve problems and help your community.",
    "Cooperating, resolving conflicts peacefully, listening actively, using respectful language, leading with care, and valuing contributions to the community.",
    "2-S-100, 2-S-101, 2-S-102, 2-S-104, 2-S-400, 2-S-401, 2-VC-001, 2-VC-002, 2-VI-004, 2-VP-011, 2-VP-012", "cooperation, peaceful conflict solving, respectful listening, leadership and contributing", WORKING),
  mk("mb-finding-out", "Finding Out and Sharing Ideas", "🔍", "Ask questions, use sources and tools, and share what you learn.",
    "Asking research questions, gathering and organizing information, weighing advantages and disadvantages, forming and revising opinions, noticing media influence, and presenting ideas.",
    "2-S-200, 2-S-201, 2-S-203, 2-S-300, 2-S-301, 2-S-302, 2-S-303, 2-S-402, 2-S-403, 2-KE-039", "research questions, sources, organizers, opinions, media influence and presenting", FINDOUT),
];
