import { bankUnit, type Q } from "../own";

// Grade 2 science: tools and technology, careers, taking action, and ways of knowing (SCI.2.A to SCI.2.D).

const TOOLS: Q[] = [
  ["Which tool helps you see tiny things up close?", "a magnifying glass", ["a ruler", "a spoon"], "A magnifying glass makes small things look bigger."],
  ["Which tool measures how long something is?", "a ruler", ["a thermometer", "a rain gauge"], "A ruler measures length."],
  ["Which tool measures how warm or cold something is?", "a thermometer", ["a ruler", "a magnifying glass"], "A thermometer measures temperature."],
  ["Which tool collects rain to measure it?", "a rain gauge", ["a wind vane", "a ruler"], "A rain gauge catches rain."],
  ["Which tool shows the direction of the wind?", "a wind vane", ["a rain gauge", "a scale"], "A wind vane points into the wind."],
  ["Which tool tells you how heavy something is?", "a scale", ["a compass", "a clock"], "A scale measures mass."],
  ["Which tool helps you tell which way is north?", "a compass", ["a thermometer", "a scale"], "A compass needle points north."],
  ["Which tool tells you how much time has passed?", "a timer", ["a ruler", "a magnifier"], "A timer measures time."],
  ["Technology is something people have made to…", "meet a need or help us", ["be a rock", "grow like a plant"], "People create technology to solve problems."],
  ["Which is technology made by people?", "a bicycle", ["a pebble", "a cloud"], "People invented the bicycle."],
  ["Which is technology made by people?", "a pair of mittens", ["a snowflake", "the Sun"], "People made mittens to keep hands warm."],
  ["Which is NOT technology made by people?", "a river", ["a bridge", "a boat"], "A river is natural."],
  ["Why did people create the umbrella?", "to keep us dry in the rain", ["to make rain", "to melt snow"], "It solves a problem."],
  ["Why did people invent the wheel?", "to help move things more easily", ["to make food", "to stop the wind"], "Wheels make moving easier."],
  ["Why do people use snowshoes in deep snow?", "so they do not sink in", ["to make snow melt", "to catch fish"], "Snowshoes spread weight over the snow."],
  ["Why do we use a lunch box?", "to carry and keep food", ["to measure wind", "to see far away"], "People made lunch boxes for that need."],
  ["What should you do before using a new tool in science?", "listen to the safety rules", ["use it without asking", "throw it"], "Always follow the safety rules."],
  ["What should you do if a tool breaks?", "tell your teacher", ["hide it", "keep using it"], "Tell an adult."],
  ["How should you use scissors safely?", "cut only the materials you are told to", ["run with them", "point them at friends"], "Use scissors carefully."],
  ["Which is a safe way to look at a leaf up close?", "with a magnifying glass", ["by tasting it", "by squeezing it hard"], "Observe carefully and safely."],
  ["Which clothing is a technology that protects your head on a bike?", "a helmet", ["a bowl", "a scarf"], "A helmet protects your head.", true],
  ["After using a science tool, you should…", "put it back where it belongs", ["leave it on the floor", "take it home"], "Tidy tools after use.", true],
  ["Which tool would you use to find out how much a toy car weighs?", "a balance scale", ["a rain gauge", "a wind vane"], "A balance scale compares masses.", true],
  ["You want to know how tall a plant is. What tool do you use?", "a ruler", ["a thermometer", "a compass"], "A ruler measures length.", true],
  ["Why do we wash our hands after we study soil or plants?", "to stay clean and healthy", ["to turn the soil blue", "to hide the plant"], "Washing hands keeps us healthy.", true],
  ["Which has been created by people to get food from the ground?", "a farm tractor", ["a sunrise", "a mountain"], "A tractor helps farmers.", true],
];

const CAREERS: Q[] = [
  ["Who studies the weather?", "a meteorologist", ["a baker", "a dentist"], "A meteorologist forecasts the weather."],
  ["Who studies plants?", "a botanist", ["a pilot", "a driver"], "A botanist studies plants."],
  ["Who studies living things and how they live?", "a biologist", ["a tailor", "a painter"], "A biologist studies life."],
  ["Who cares for sick animals?", "a veterinarian", ["a plumber", "a singer"], "A veterinarian is an animal doctor."],
  ["Who grows crops and raises animals for food?", "a farmer", ["a pilot", "a banker"], "Farmers use science to grow food."],
  ["Who studies how living things and their homes fit together?", "an ecologist", ["a mail carrier", "a chef"], "An ecologist studies ecosystems."],
  ["Who protects wildlife and fish and enforces rules about them?", "a conservation officer", ["a clown", "a dancer"], "Conservation officers care for nature."],
  ["Who catches fish for a living?", "a fisher", ["an architect", "a poet"], "Fishers know about water and fish."],
  ["Which is a hobby that uses science?", "growing a garden", ["sleeping", "watching a blank wall"], "Gardeners learn about plants."],
  ["Which is a hobby that uses science?", "collecting rocks", ["tying shoes", "folding clothes"], "Rock collecting is a science hobby."],
  ["Which activity helps you learn about birds?", "bird watching", ["jumping rope", "painting a fence"], "Bird watching is a nature hobby."],
  ["Which activity helps you learn about fish and ice in winter?", "ice fishing", ["swimming", "kite flying"], "Ice fishing is a winter activity in Manitoba."],
  ["Which activity uses seeds and soil?", "gardening", ["bowling", "hopscotch"], "Gardening needs science."],
  ["Which hobby keeps fish in a tank?", "keeping an aquarium", ["roller skating", "juggling"], "An aquarium keeper cares for fish."],
  ["Which activity uses science to take pictures of animals and plants?", "nature photography", ["bowling", "sewing"], "Photographers look closely at nature."],
  ["Which sport uses science of motion?", "swimming", ["knitting", "napping"], "Swimmers learn how water pushes."],
  ["Which person uses science about the sky to plan a flight?", "a pilot", ["a florist", "a barber"], "Pilots need to know the weather."],
  ["A baker uses science when bread rises. What makes the dough rise?", "tiny bubbles of gas", ["magic", "cold air only"], "Yeast makes gas bubbles."],
  ["Many people pick berries and plants in the summer. They need to know…", "which plants are safe", ["only the colours", "nothing at all"], "Careful knowledge keeps people safe.", true],
  ["Who might use a microscope to look at tiny things?", "a scientist", ["a mail carrier", "a bus driver"], "Scientists use microscopes.", true],
  ["Which job helps look after the land and water?", "a park ranger", ["a toy seller", "an actor"], "A park ranger protects natural areas.", true],
  ["Which person studies rocks and what the ground is made of?", "a geologist", ["a baker", "a singer"], "A geologist studies rocks.", true],
  ["A person who studies water below the ground is a…", "hydrogeologist", ["clown", "poet"], "They study groundwater.", true],
  ["Which job needs you to know about animals and how to help them?", "a vet technologist", ["a window washer", "a lifeguard"], "An animal health technologist helps animals.", true],
  ["Which of these could you do now that uses science?", "plant a seed and watch it grow", ["wait for a monster", "wish for rain"], "You can watch and write down what happens.", true],
];

const ACTION: Q[] = [
  ["Which action saves water at school?", "turn off the tap tightly", ["leave the tap running", "pour water on the floor"], "Turning off taps saves water."],
  ["Which action saves water at home?", "take a shorter shower", ["leave the hose on", "fill the tub for fun"], "Short showers use less water."],
  ["How can you help plants and animals near your school?", "keep the schoolyard clean", ["drop garbage", "trample the flowers"], "A clean place helps wildlife."],
  ["Which would make a schoolyard welcome to birds?", "put up a bird feeder", ["add loud noise", "cut every tree"], "Feeders and trees help birds."],
  ["Which plant helps bees and butterflies?", "a flower garden", ["a parking lot", "a pile of garbage"], "Flowers give nectar."],
  ["A puddle can be a tiny home for…", "insects and tadpoles", ["whales", "bears"], "Puddles and ditches can hold life."],
  ["How can we protect a pond or ditch near school?", "keep litter out of it", ["throw rocks at animals", "dump paint into it"], "Clean water is important."],
  ["Which action lowers air pollution?", "walk or bike to school", ["leave a car running", "burn garbage"], "Walking makes less pollution."],
  ["Why should drivers not leave a car running while parked?", "it adds pollution to the air", ["it makes grass grow", "it cools the road"], "Idling adds pollution."],
  ["Which helps reduce waste?", "using a refillable water bottle", ["using a new plastic bottle every day", "throwing out lunch"], "A refillable bottle makes less garbage."],
  ["What can you do with a used paper to help the environment?", "reuse or recycle it", ["tear it up and toss it outside", "burn it"], "Reuse and recycle."],
  ["Which action shows you care about a local wetland?", "stay on the path and take only photos", ["pick every plant", "chase the ducks"], "Leave it as you found it."],
  ["Why is it good to ask a question about a problem at school?", "it helps find a way to fix it", ["it makes the problem bigger", "it ends the school day"], "Good questions lead to solutions."],
  ["How can a class take action on a problem?", "make a plan and work together", ["do nothing", "blame someone"], "Teams can make a difference."],
  ["Which is a way to ask people to save water?", "make a poster", ["hide the taps", "break the pipes"], "Posters share ideas."],
  ["Water is important because…", "all living things need it", ["only people need it", "nothing needs it"], "Plants and animals also need water."],
  ["Who can help with science and the environment?", "everyone, including children", ["only adults", "only scientists in labs"], "Everyone can contribute."],
  ["Which of these do plants and animals NEED from the schoolyard?", "clean air, water and food", ["litter", "loud music"], "Needs are the same for living things.", true],
  ["You see a hose left on at the school. What do you do?", "tell a teacher so it can be turned off", ["step on the hose", "ignore it"], "Tell an adult.", true],
  ["How could the class check how much water the school uses?", "ask the caretaker and read the numbers together", ["guess without looking", "close the school"], "Gathering information helps plan.", true],
  ["Which action helps a local ditch full of tadpoles?", "do not pour soap or oil in it", ["pour in cleaner", "fill it with trash"], "Keep water clean for living things.", true],
  ["Which of these is a small action with a big effect?", "everyone puts litter in the bin", ["one person tosses litter", "nobody does anything"], "Small actions add up.", true],
  ["What helps if you want to make your school greener?", "plant trees or a garden with a teacher", ["cut flowers", "pave the grass"], "Plants help the environment.", true],
  ["Which is a good way to share what you learned about saving water?", "tell a younger class", ["keep it secret", "tell the wind"], "Teaching others spreads the idea.", true],
  ["Which of these helps keep air clean at school?", "plant trees in the yard", ["burn leaves", "run engines"], "Trees take in carbon dioxide.", true],
];

const KNOWING: Q[] = [
  ["Which helps scientists learn about nature?", "watching carefully", ["not looking", "closing their eyes"], "Careful observing is a science skill."],
  ["How can you learn about the land and weather?", "spend time outdoors and notice changes", ["stay in a closet", "never ask questions"], "Learning from the land takes time and attention."],
  ["Many First Nations, Métis and Inuit people learn from the land. How?", "by watching it closely across the seasons", ["by ignoring it", "by guessing"], "Careful watching over time teaches a lot."],
  ["Many Elders share knowledge about animals and plants. How do they share it?", "through stories and by teaching on the land", ["through magic spells", "never"], "Knowledge is shared through stories and doing."],
  ["Which is a good way to learn from an Elder?", "listen respectfully and ask polite questions", ["interrupt", "walk away"], "Respect and listening matter."],
  ["Many Indigenous people say that people, plants, animals and water are connected. This means…", "what happens to one affects the others", ["nothing is connected", "only people matter"], "Living things depend on each other."],
  ["Which is a way of taking care of the land?", "take only what you need", ["take everything", "leave trash"], "Taking only what you need helps the land last."],
  ["Seasons change. In winter on the Prairies, many animals…", "grow thick fur or sleep", ["bloom flowers", "swim in warm water"], "Animals prepare for the cold."],
  ["Which knowledge comes from watching the same place for many years?", "when the geese return in spring", ["how to spell a word", "what time school ends"], "Watching nature across many years teaches patterns."],
  ["What does a scientist do to find an answer?", "ask a question and try to find out", ["guess and stop", "ignore the question"], "Scientists ask and test."],
  ["Which is a science question?", "What do plants need to grow?", ["Which is your favourite colour?", "What is your name?"], "A science question can be tested."],
  ["Which way of learning uses your senses?", "looking, listening and touching safely", ["sleeping", "ignoring"], "Observing uses the senses."],
  ["Tools like snowshoes, canoes and sleds were made by people living on the land. They are…", "technologies", ["toys only", "not useful"], "People made tools to meet needs."],
  ["Many communities use traditional tools and new tools. This shows that…", "people keep learning and using what works", ["old tools are never used", "new tools are forbidden"], "Knowledge grows and continues."],
  ["Land-based learning means learning…", "outdoors, on and from the land", ["only from screens", "only in a locked room"], "Land-based learning happens outside."],
  ["Everyone can ask questions about nature. This means…", "everyone can be a scientist", ["only adults can", "only experts can"], "Curiosity belongs to everyone."],
  ["Your friend notices which flowers bloom first in spring. They are…", "making observations", ["breaking rules", "daydreaming only"], "Noticing patterns is science."],
  ["A good scientist is curious. This means they…", "like to ask why", ["never ask", "dislike learning"], "Curious people wonder about the world."],
  ["Why is it good to connect science to things you already know?", "it helps you understand new ideas", ["it makes things harder", "it is not allowed"], "Linking helps learning.", true],
  ["You notice ice melts faster in the sun. What are you doing?", "learning from observation", ["making a rule", "sleeping"], "Observation leads to ideas.", true],
  ["How can sharing different ideas help us learn?", "we see more than one way to understand", ["we all think the same", "it never helps"], "Different ways of knowing add up.", true],
  ["Why is it important to be respectful when we learn from others' knowledge?", "it shows we value what they share", ["it is not important", "it makes them leave"], "Respect builds trust.", true],
  ["Which sentence shows science and Indigenous knowledge can work together?", "Both can teach us about the land.", ["Only one can teach us anything.", "Neither helps."], "Different ways of knowing can add to each other.", true],
  ["You have a favourite spot outdoors. What can you do there each season?", "draw what you notice", ["close your eyes", "go home"], "Noticing change is a science skill.", true],
  ["What can a nature journal help you do?", "keep track of what you see over time", ["lose track of time", "stop learning"], "Journals record observations.", true],
];

const mk = (id: string, title: string, emoji: string, blurb: string, parentNote: string, codes: string, text: string, items: Q[]) =>
  bankUnit({ id, title, emoji, blurb, parentNote, standards: [codes, text], items });

export const moreScience = [
  mk("mb-tools-and-technology", "Science Tools and Technology", "🔬", "Pick the right tool and use it safely.",
    "Choosing and using science tools safely, and recognizing that people create technologies to meet needs.",
    "SCI.2.C.4, SCI.2.D.2", "using tools safely, and technologies created by people", TOOLS),
  mk("mb-science-in-jobs", "Science Jobs and Hobbies", "👩‍🔬", "Who uses science at work and at play?",
    "Making connections between science and careers, hobbies and activities such as farming, gardening and ice fishing.",
    "SCI.2.C.5", "careers, hobbies and activities that use science", CAREERS),
  mk("mb-taking-action", "Taking Action for Nature", "🌍", "Small actions to look after water, air and wildlife.",
    "Taking class or personal action on local issues such as water use, wildlife in the schoolyard and air quality.",
    "SCI.2.C.1", "taking action on local science, technology, society and environment issues", ACTION),
  mk("mb-learning-from-the-land", "Curious About the World", "🌱", "Many ways of watching, asking and learning from the land.",
    "Cultivating curiosity, noticing the world with the senses, and learning how many First Nations, Métis and Inuit people learn from the land.",
    "SCI.2.A.1, SCI.2.B.1", "curiosity and belonging in science, and Indigenous ways of knowing about the land", KNOWING),
];
