import { bankUnit, type Q } from "../own";

// Grade 2 social studies. Our Community (2-KC, 2-KI, 2-KP) and Canada's Communities (2-KL, 2-KI, 2-KC).

const LEADERS: Q[] = [
  ["Who helps run a city or town?", "the mayor", ["a pilot", "a chef"], "A mayor leads a city or town."],
  ["What is the leader of a rural municipality called?", "a reeve", ["a coach", "a captain"], "Many rural communities in Manitoba have a reeve."],
  ["Who leads a First Nation community?", "a chief", ["a mayor only", "a bus driver"], "A chief leads, with a council, and Elders give guidance."],
  ["Who in a community shares knowledge, wisdom and stories?", "Elders", ["strangers", "cartoon characters"], "Elders are respected for their wisdom."],
  ["Who leads a class?", "the teacher", ["the crossing guard", "the mayor"], "A teacher leads a class."],
  ["Who helps children cross the street safely?", "a crossing guard", ["a baker", "a farmer"], "A crossing guard is a community helper."],
  ["Who leads a team?", "a captain or coach", ["a doctor", "a librarian"], "A coach or captain leads a team."],
  ["Which is a way to show leadership at school?", "help a new student feel welcome", ["leave a mess", "ignore others"], "Leaders help and include."],
  ["Which is a way to show leadership?", "Take turns and let everyone play", ["Always go first", "Tell others they cannot join"], "Good leaders are fair."],
  ["A good leader…", "listens to others", ["never listens", "always shouts"], "Listening is part of being a good leader."],
  ["What is a right you have at school?", "to be treated with respect", ["to tease others", "to skip class"], "Everyone has the right to feel safe and respected."],
  ["What is a responsibility you have at school?", "to follow the rules", ["to break the rules", "to be late on purpose"], "Responsibilities are things we should do."],
  ["Which is a responsibility in a community?", "put garbage in the bin", ["drop litter", "yell at neighbours"], "Everyone helps keep a community clean."],
  ["Which is a right of every child?", "to be safe", ["to be unkind", "to take others' things"], "Every child has the right to be safe."],
  ["Two children both want the same toy. A peaceful way to solve it is to…", "take turns", ["grab it", "hit"], "Taking turns solves the problem without hurting anyone."],
  ["Which is a possible source of conflict?", "two people want the same thing", ["sharing a snack", "waving hello"], "Wanting the same thing can cause conflict."],
  ["Another source of conflict is…", "not following the rules in a game", ["saying thank you", "helping a friend"], "Rules that are not followed can lead to arguments."],
  ["Which is a peaceful way to solve a conflict?", "talk it out and listen", ["yell", "call names"], "Peaceful ways keep everyone safe."],
  ["You and a friend disagree. What could you say?", "“Let's find a plan that works for both of us.”", ["“You are wrong!”", "“I'm never playing again.”"], "Kind words help solve problems."],
  ["Why do communities have rules and laws?", "to keep people safe and fair", ["to spoil fun", "so no one can go outside"], "Rules help everyone get along."],
  ["Why is it good to volunteer in your community?", "it helps others and makes the community better", ["it is a way to win money", "it makes more rules"], "Volunteers give their time to help.", true],
  ["A neighbour needs help carrying groceries. What could you do?", "offer to help", ["walk away", "laugh"], "Helping is a way to contribute.", true],
  ["Why do we value the work of community helpers?", "they make our community safer and better", ["they never work", "they take our toys"], "Their work helps everyone.", true],
  ["A leader should be sensitive to others. This means…", "paying attention to how others feel", ["ignoring feelings", "making fun of others"], "Sensitive leaders care about feelings.", true],
  ["Which choice shows peaceful conflict solving?", "Say how you feel and ask for what you need", ["Push to get your way", "Say nothing and sulk"], "Say how you feel in a calm, kind way.", true],
];

const SYMBOLS: Q[] = [
  ["What are the two official languages of Canada?", "English and French", ["English and Spanish", "French and German"], "Canada has two official languages."],
  ["Which of these is an official language of Canada?", "French", ["Spanish", "Greek"], "French and English are official in Canada."],
  ["Are many languages spoken in Canada?", "yes", ["no, only one", "no, only two"], "People in Canada speak many languages, including First Nations, Métis and Inuit languages."],
  ["Which of these is an Indigenous language spoken in Manitoba?", "Cree", ["Latin", "Japanese"], "Cree, Ojibwe, Dakota, Dene and Michif are spoken in Manitoba."],
  ["Which language is a Métis language?", "Michif", ["Latin", "Greek"], "Michif is a Métis language."],
  ["Who are Canada's original peoples?", "First Nations and Inuit Peoples", ["Only newcomers", "Nobody"], "First Nations and Inuit have lived here for a very long time."],
  ["Which colours are on the Canadian flag?", "red and white", ["blue and yellow", "green and black"], "The flag is red and white with a maple leaf."],
  ["What is in the middle of the Canadian flag?", "a red maple leaf", ["a star", "a moon"], "The maple leaf is a Canadian symbol."],
  ["Which animal is a symbol of Canada?", "beaver", ["kangaroo", "panda"], "The beaver is a national symbol."],
  ["Which is the capital city of Canada?", "Ottawa", ["Winnipeg", "Toronto"], "Ottawa is the capital of Canada."],
  ["Which is the capital city of Manitoba?", "Winnipeg", ["Ottawa", "Brandon"], "Winnipeg is Manitoba's capital."],
  ["Which bird is a symbol of Manitoba?", "great grey owl", ["robin", "eagle"], "The great grey owl is Manitoba's provincial bird."],
  ["Which flower is a symbol of Manitoba?", "prairie crocus", ["rose", "tulip"], "The prairie crocus is Manitoba's flower."],
  ["What is Manitoba's provincial tree?", "white spruce", ["palm", "maple"], "The white spruce is Manitoba's tree."],
  ["Where does Canada's government meet?", "Parliament Hill", ["Winnipeg Beach", "Banff"], "Parliament Buildings are in Ottawa."],
  ["Where does Manitoba's government meet?", "the Legislative Building", ["a hockey arena", "the zoo"], "The Manitoba Legislative Building is in Winnipeg."],
  ["The statue on top of the Manitoba Legislative Building is called…", "the Golden Boy", ["the Giant Owl", "the Silver Girl"], "The Golden Boy is a well-known Manitoba monument."],
  ["What day do we think about peace and war?", "Remembrance Day", ["Canada Day", "Earth Day"], "Remembrance Day is November 11."],
  ["What flower do many people wear for Remembrance Day?", "a red poppy", ["a daisy", "a sunflower"], "The red poppy shows that we remember."],
  ["Canada is one of many…", "countries in the world", ["cities in the world", "oceans in the world"], "Canada is a country."],
  ["Which continent is Canada part of?", "North America", ["Europe", "Africa"], "Canada is in North America.", true],
  ["Name one thing that connects Canada to other countries.", "food from around the world", ["a talking tree", "a moon base"], "Foods, music and travel connect countries.", true],
  ["Many families have come to Canada from other parts of the world. Why?", "to make a new home", ["to stay for one hour", "to find the moon"], "People come to build new lives.", true],
  ["Which sentence is true?", "Canada has many cultures.", ["Canada has only one culture.", "Canada has no cultures."], "Canada is diverse.", true],
  ["Which is a place name that comes from a First Nations word?", "Manitoba", ["Vancouver", "Halifax"], "Manitoba comes from a word in Cree or Ojibwe.", true],
  ["French-speaking communities in Manitoba include…", "Saint-Boniface", ["Nunavut", "Banff"], "Saint-Boniface in Winnipeg has a long francophone history.", true],
];

const RESOURCES: Q[] = [
  ["Which of these is a natural resource?", "water", ["a toy car", "a plastic bag"], "Natural resources come from nature."],
  ["Which one is a natural resource?", "trees", ["a television", "a bicycle"], "Wood comes from trees."],
  ["Which is NOT a natural resource?", "a pencil sharpener", ["soil", "fish"], "People make a pencil sharpener."],
  ["Soil helps farmers grow…", "crops", ["plastic", "glass"], "Crops grow in soil."],
  ["Which natural resource do we drink?", "water", ["rock", "wood"], "Clean water is a resource."],
  ["Manitoba has many lakes. What can people get from them?", "fish", ["cars", "toys"], "Fishing is common in Manitoba."],
  ["Manitoba has forests in the north. What resource do we get from them?", "wood", ["salt water", "coral"], "Wood is used for building."],
  ["The prairie has rich black soil. What grows there?", "wheat and canola", ["palm trees", "coral"], "Prairie farms grow crops."],
  ["Which resource is found underground?", "minerals", ["clouds", "birds"], "Mining takes minerals from under the ground."],
  ["The wind can be used to make…", "electricity", ["bread", "paper"], "Wind turbines make electricity."],
  ["Water from rivers can be used to make…", "electricity", ["bricks", "paper"], "Manitoba makes much of its electricity from water power."],
  ["What does it mean to conserve a resource?", "use it carefully so it lasts", ["use it all up", "throw it away"], "To conserve is to protect and save."],
  ["Which action conserves water?", "turn off the tap while brushing teeth", ["leave the tap running", "waste water"], "Saving water helps conserve it."],
  ["Which action conserves paper?", "write on both sides", ["throw away clean pages", "tear pages for fun"], "Using both sides saves paper."],
  ["Which action helps conserve energy?", "turn off lights you are not using", ["leave every light on", "open the fridge for fun"], "Saving electricity conserves energy."],
  ["What does it mean to recycle?", "to make used things into new things", ["to throw things on the ground", "to burn them all"], "Recycling gives used materials new life."],
  ["Which goes in the recycling bin?", "a clean paper box", ["a banana peel", "a dirty tissue"], "Paper can be recycled."],
  ["Planting a tree helps to…", "restore the forest", ["use up the forest", "pave the forest"], "New trees grow where others were cut."],
  ["Why is it important to look after the land and water?", "people, plants and animals need them", ["they are only for looks", "nobody needs them"], "All living things need clean land and water."],
  ["How does the weather shape daily life in Manitoba?", "we wear warm clothes in winter", ["we never go outside", "we wear shorts every day"], "People adjust to their natural environment."],
  ["In winter many Manitobans enjoy…", "skating and skiing", ["swimming in the lake", "sunbathing outside"], "Cold, snowy winters shape activities."],
  ["Lakes freeze in winter. What can people do on frozen lakes?", "ice fishing", ["water-skiing", "swimming"], "Ice fishing is a winter activity in Manitoba.", true],
  ["Why do farmers need good weather?", "crops grow with sun and rain", ["farm animals dislike food", "tractors need ice"], "Plants need sun and rain.", true],
  ["Why is a community near a river useful?", "people can get water and travel", ["rivers are always dry", "rivers are made of rock"], "Rivers give water, food and routes.", true],
  ["A community is next to a big forest. What could people make?", "wood products", ["ocean salt", "snow cones"], "A forest provides wood.", true],
  ["Which is better for the land?", "put litter in the bin", ["drop litter on the ground", "dump paint in a creek"], "Caring for the land means keeping it clean.", true],
];

export const leaders = bankUnit({
  id: "mb-leaders-and-rights",
  title: "Leaders, Rights and Responsibilities",
  emoji: "🤝",
  blurb: "Who leads our community, and how do we get along?",
  parentNote: "Community leaders, the rights and responsibilities of members of a community, leadership at school, and peaceful ways of solving conflict.",
  standards: ["2-KC-001, 2-KP-033, 2-KP-034, 2-KP-035", "responsibilities and rights, community leaders, leadership and sources of conflict"],
  items: LEADERS,
});

export const symbols = bankUnit({
  id: "mb-canada-symbols",
  title: "Canada, Languages and Symbols",
  emoji: "🍁",
  blurb: "Flags, languages and the symbols of Canada and Manitoba.",
  parentNote: "Canadian and Manitoban symbols, Canada's two official languages and other languages spoken here, Remembrance Day, and Canada as one of many countries.",
  standards: ["2-KC-002, 2-KC-003, 2-KI-014, 2-KI-015, 2-KH-027, 2-KG-031", "symbols and monuments, Remembrance Day, languages, Canada's original peoples and Canada in the world"],
  items: SYMBOLS,
});

export const resources = bankUnit({
  id: "mb-natural-resources",
  title: "Natural Resources and Caring for the Land",
  emoji: "🌲",
  blurb: "What does the land give us, and how do we protect it?",
  parentNote: "Natural resources in communities, how the natural environment shapes daily life, and why conserving and restoring resources matters.",
  standards: ["2-KL-016, 2-KL-017, 2-KL-020, 2-KL-021, 2-KL-022", "natural resources, how the environment shapes daily life, and conserving or restoring resources"],
  items: RESOURCES,
});
