import { bankUnit, type Q } from "../own";

// More Grade 3 social studies: identities (3-KI-007, 3-KI-007A, 3-KI-007F, 3-VI-004), the land (3-KL-019, 3-VL-005, 3-VL-006,
// 3-VL-006A, 3-S-103), people and places (3-VG-010, 3-VE-012, 3-KI-009A), working together (3-S-100, 3-S-102, 3-S-104, 3-S-400,
// 3-S-403) and the inquiry skills (3-S-200 to 3-S-203, 3-S-300 to 3-S-304, 3-S-402).

const IDENTITY: Q[] = [
  ["Your identity is…", "who you are and what makes you, you", ["your desk number", "the weather"], "Identity is shaped by many things."],
  ["Which can influence your identity?", "The language you speak", ["The colour of your pencil", "The weather today"], "Language is part of culture."],
  ["Which can influence your identity?", "Your culture and traditions", ["A random number", "The shape of a cloud"], "Culture shapes how we live."],
  ["Which can influence your identity?", "The place where you live", ["The time on a clock", "The month on a calendar only"], "Place shapes who we are."],
  ["Groups and communities that you belong to can…", "shape who you are", ["erase you", "have no effect"], "Belonging influences identity."],
  ["Music, art, books and shows are examples of…", "arts and media", ["only homework", "sports"], "Arts and media can shape identity."],
  ["Two children in the same class can have…", "different identities", ["the same identity always", "no identity"], "Everyone is unique."],
  ["Culture is…", "the ways a group lives, such as food, language, music and traditions", ["a kind of building", "a type of weather"], "Culture includes many things."],
  ["A tradition is…", "something a family or group does again and again", ["a one-time accident", "a rule only for kids"], "Traditions are passed on."],
  ["Which is a family tradition?", "Making a special meal each winter", ["Getting lost once", "Losing a mitten"], "Traditions repeat."],
  ["Being proud of your own community means you…", "value where you belong", ["dislike others", "ignore your home"], "You can be proud and respect others too."],
  ["Some First Nations, Métis or Inuit children may describe their community by…", "its language, stories and ways of life", ["only a map", "nothing"], "Each community has its own."],
  ["A First Nations, Métis or Inuit person might say their community is important to them because of…", "family, language and traditions", ["advertisements", "a random number"], "Communities are living and present today."],
  ["Francophone means a person who speaks…", "French as a first language or at home", ["only Spanish", "no language"], "Manitoba has a francophone community."],
  ["In Manitoba, a francophone community is one where…", "people share the French language and culture", ["nobody speaks", "only English is allowed"], "St. Boniface is a well-known French community in Winnipeg."],
  ["Which Winnipeg neighbourhood is known for its French-speaking community?", "Saint-Boniface", ["Transcona only", "Charleswood only"], "Saint-Boniface has a long French history."],
  ["The Festival du Voyageur celebrates…", "French-Canadian and Métis heritage in winter", ["a summer circus", "a space launch"], "It is held every February in Winnipeg."],
  ["Being interested in other cultures means…", "wanting to learn about how others live", ["making fun", "staying away"], "Curiosity and respect go together."],
  ["Which question shows interest in another culture?", "What foods do you like to eat at celebrations?", ["Why are you strange?", "Why don't you live like me?"], "Ask with respect."],
  ["Which response is respectful when someone shares a custom?", "“Thank you for sharing. Tell me more.”", ["“That is weird.”", "“Stop.”"], "Respect means listening."],
  ["Learning a few words in a friend's language is a way to…", "show interest and respect", ["be rude", "forget your own language"], "Languages connect people."],
  ["Communities around the world have different…", "ways of living", ["number of days in a week", "kinds of sky"], "People live in different ways."],
  ["Which is a reason two communities might look different?", "They are in different places with different climates", ["Because everyone is the same", "Because nobody lives there"], "Place and culture shape life.", true],
  ["Identity can change as you…", "grow and learn", ["never", "close a book"], "People grow and change.", true],
  ["Why is it good to have friends with different identities?", "We can learn from each other", ["So we can all be the same", "So we never talk"], "Diversity makes communities richer.", true],
];

export const identity = bankUnit({
  id: "mb-who-i-am",
  title: "Who I Am & Where I Belong",
  emoji: "🧒",
  blurb: "Culture, language, place and the communities that shape who we are.",
  parentNote:
    "Practises factors that shape identity (culture, language, place, groups and communities, arts and media), describing a First Nations, Métis, Inuit or francophone community in general terms, and showing interest in the ways of life of other communities.",
  standards: ["3-KI-007, 3-KI-007A, 3-KI-007F, 3-VI-004", "factors that shape identity, personal community connections and interest in other cultures"],
  items: IDENTITY,
});

const LAND: Q[] = [
  ["People live in different ways on or with the land. This is…", "true", ["false", "unknown"], "Ways of life differ around the world."],
  ["A community in a cold northern place might wear…", "warm layers", ["swimsuits", "sandals only"], "People dress for their climate."],
  ["A community near the ocean may get food from…", "fishing", ["farming in the desert", "mining the Moon"], "The sea can provide food."],
  ["A community on the prairies may use land for…", "growing wheat and other crops", ["only mountains", "ice fishing only"], "Manitoba farmers grow crops."],
  ["Land provides communities with…", "food, water, materials and places to live", ["nothing", "only noise"], "The land gives us what we need."],
  ["Which comes from the land?", "Wood for building", ["A cartoon", "A song"], "Trees give wood."],
  ["Which comes from the land?", "Clean water from a river or lake", ["A video game", "A balloon"], "Water is a gift of the land."],
  ["Why do people value the land?", "It provides what communities need", ["It is only for show", "It is for nobody"], "Land supports life."],
  ["Many First Nations, Métis and Inuit peoples see living on and with the land as…", "sacred and something to care for", ["only a business", "unimportant"], "Many communities value a deep respect for the land."],
  ["To care for the land you can…", "pick up litter and protect habitats", ["leave garbage", "break plants"], "Caring for the land is everyone's job."],
  ["Which choice shows care for the environment?", "Turning off lights when you leave a room", ["Leaving taps on", "Throwing trash out the car window"], "Saving energy helps."],
  ["Which choice shows care for the environment?", "Using a reusable water bottle", ["Using a new plastic bottle every time", "Dropping it in the river"], "Reuse reduces waste."],
  ["Recycling paper helps by…", "saving trees and resources", ["making more garbage", "hurting the soil"], "Recycling reuses materials."],
  ["Planting a tree can help the environment because trees give…", "shade, homes for animals and cleaner air", ["more litter", "noise"], "Trees support life."],
  ["The global natural environment includes…", "forests, oceans, deserts, mountains and more", ["only cities", "only roads"], "The Earth has many natural places."],
  ["A desert is a place that is usually…", "very dry", ["very wet", "always frozen"], "Deserts get little rain."],
  ["A rainforest is a place that is usually…", "warm and wet", ["cold and dry", "bare rock"], "Rainforests get lots of rain."],
  ["The Arctic is a place that is usually…", "very cold", ["very hot", "a rainforest"], "The Arctic has long, cold winters."],
  ["Manitoba has many…", "lakes and rivers", ["oceans around it", "volcanoes"], "Lake Winnipeg is a very large lake."],
  ["It is good to appreciate nature's diversity because…", "many different living things depend on it", ["only people matter", "it is boring"], "Diversity is important."],
  ["Hunting, fishing and gathering are ways that some communities…", "take food from the land", ["avoid the land", "buy everything"], "These practices continue today in many places."],
  ["Taking only what you need is a way to show…", "respect for the land", ["greed", "forgetting"], "Respectful harvesting is common in many cultures."],
  ["What can we do when we are in a park?", "Stay on the path and leave nothing behind", ["Pick all the flowers", "Chase animals"], "Leave places as you found them.", true],
  ["Why should we protect wetlands?", "Many animals and plants live there and they clean water", ["They are useless", "They are only mud"], "Wetlands are important habitats.", true],
  ["Which decision shows care and responsibility for the environment?", "Walking or biking to school when you can", ["Asking for a ride 100 m", "Dropping litter"], "Choices add up.", true],
];

export const land = bankUnit({
  id: "mb-living-with-the-land",
  title: "Living On & With the Land",
  emoji: "🏞️",
  blurb: "How the land supports communities, and how we can care for it.",
  parentNote:
    "Practises how people live on and with the land in different places, valuing what the land provides, appreciating the variety of natural environments, and making choices that care for the environment. Many First Nations, Métis and Inuit communities see living with the land as sacred; this unit stays general and respectful.",
  standards: ["3-KL-019, 3-VL-005, 3-VL-006, 3-VL-006A, 3-S-103", "diverse ways of living with the land, valuing and caring for the environment"],
  items: LAND,
});

const PEOPLE: Q[] = [
  ["A contribution is…", "something you give or do to help", ["something you take", "a kind of food"], "Contributions help the community."],
  ["A crossing guard contributes by…", "helping children cross safely", ["selling stamps", "flying planes"], "They keep people safe."],
  ["A librarian contributes by…", "helping people find books and information", ["fixing cars", "growing wheat"], "Libraries share knowledge."],
  ["A farmer contributes by…", "growing food", ["writing laws", "directing traffic"], "Food comes from farms."],
  ["A nurse contributes by…", "caring for people's health", ["painting murals", "building roads"], "Nurses help people get better."],
  ["A firefighter contributes by…", "keeping the community safe from fires", ["delivering mail", "mowing grass"], "They protect people."],
  ["A bus driver contributes by…", "helping people get where they need to go", ["teaching math", "making bread"], "Transit connects people."],
  ["A neighbour who shovels an Elder's walk contributes by…", "being kind and helpful", ["causing a mess", "ignoring others"], "Small acts matter."],
  ["Volunteers give…", "their time to help without pay", ["money to buy toys", "orders"], "Volunteers help the community."],
  ["Children can contribute to their communities by…", "helping at school or in a neighbourhood clean-up", ["leaving garbage", "being unkind"], "Everyone can help."],
  ["Which contribution helps a community?", "Planting a community garden", ["Leaving litter", "Spreading rumours"], "Gardens give food and beauty."],
  ["Why do we thank people who help us?", "To show we value what they do", ["To make them leave", "Because we must pay"], "Thanks shows respect."],
  ["Communities around the world are connected because people…", "trade, travel and share ideas", ["never talk", "live alone"], "We are connected."],
  ["The food in many stores comes from…", "places far away as well as nearby", ["only one town", "nowhere"], "Food travels around the world."],
  ["Which shows a connection to a community elsewhere?", "Writing a letter or video chat with a pen pal in another country", ["Never meeting anybody", "Ignoring the world"], "Connections can be made by many means."],
  ["A food bank collects food for…", "people who need help getting enough to eat", ["pets only", "a store"], "Food banks support communities."],
  ["When there is a flood in another country, people elsewhere may…", "send help like food, supplies or money", ["ignore it", "cause more problems"], "Communities help each other."],
  ["Appreciating our connections to people elsewhere means we…", "see that we share the world", ["think we are alone", "are not connected"], "Everyone shares the Earth."],
  ["Protocol means…", "a respectful way of doing things in a group or culture", ["a kind of food", "a type of game"], "Protocols show respect."],
  ["In many Indigenous communities, a protocol when meeting an Elder is to…", "greet them politely and listen with respect", ["interrupt them", "ignore them"], "Respect for Elders is important in many communities."],
  ["Asking permission before taking part in or sharing something from a culture is a…", "respectful protocol", ["rude act", "way to avoid learning"], "Many communities teach protocols for sharing."],
  ["Protocols can differ from one Nation or community to another. So we should…", "learn about the protocols of the community we are visiting", ["assume all are the same", "skip them"], "Ask and listen."],
  ["Thanking someone who shares knowledge with you is…", "a respectful way to show gratitude", ["unnecessary", "rude"], "Gratitude is part of many protocols.", true],
  ["Which sentence names a way a community can recognize a person's contribution?", "Giving a thank-you card or award", ["Ignoring them", "Taking their tools"], "Recognition helps people feel valued.", true],
  ["Why is it important that everyone has something to contribute?", "A community is stronger when everyone helps", ["Only a few matter", "Nobody is needed"], "Many hands make a community strong.", true],
];

export const people = bankUnit({
  id: "mb-contributions-and-connections",
  title: "Helping & Connecting Communities",
  emoji: "🤝",
  blurb: "Contributions, links to communities elsewhere and respectful protocols.",
  parentNote:
    "Practises valuing what individuals contribute to their communities, our connections to people elsewhere in the world, and the idea of respectful protocols in Indigenous cultures, which differ from community to community.",
  standards: ["3-VE-012, 3-VG-010, 3-KI-009A", "valuing contributions, connections to communities elsewhere and respectful protocols"],
  items: PEOPLE,
});

const TEAM: Q[] = [
  ["Collaborating means…", "working together", ["working alone only", "arguing"], "Collaboration shares work."],
  ["In a group project, everyone should share…", "ideas and jobs", ["only blame", "only prizes"], "Share ideas, decisions and responsibilities."],
  ["Your group has four jobs and four people. A fair plan is to…", "give each person one job", ["give one person all jobs", "give nobody a job"], "Share responsibilities."],
  ["A group needs to decide what to build. A fair way to decide is to…", "listen to everyone then vote", ["let one person choose", "never decide"], "Decisions can be made together."],
  ["Which helps a group solve a disagreement?", "Take turns explaining your idea", ["Shout louder", "Walk away"], "Each person gets a turn."],
  ["Interacting fairly means…", "treating everyone the same way and sharing", ["picking favourites", "taking turns only for you"], "Fairness matters."],
  ["Interacting respectfully means…", "being kind and polite", ["teasing", "ignoring"], "Respect is kindness."],
  ["Which is respectful?", "Saying “please” and “thank you”", ["Calling names", "Grabbing"], "Polite words show respect."],
  ["Which shows fairness during a game?", "Everyone gets a turn", ["Some people are left out", "The loudest person decides"], "Fair play includes everyone."],
  ["You are playing with a new classmate. A kind thing to do is…", "invite them to join", ["leave them out", "ignore them"], "Inclusion makes a friend."],
  ["Rights of others include the right to…", "be heard and be safe", ["be ignored", "be teased"], "Everyone has rights."],
  ["Considering the opinions of others means…", "thinking about what they say, even if you disagree", ["ignoring them", "mocking them"], "Opinions matter."],
  ["Two friends disagree about a game. A good step is to…", "listen to each other and find a fair solution", ["stop playing forever", "yell"], "Fair solutions come from listening."],
  ["Active listening means…", "paying full attention to understand the speaker", ["looking away", "talking over them"], "You listen to understand."],
  ["Which shows active listening?", "Looking at the speaker and asking a question about what they said", ["Texting a friend", "Drawing a doodle"], "Show you are listening."],
  ["A perspective is…", "a way of seeing or thinking about something", ["a type of pencil", "a rule"], "Different people see things differently."],
  ["To understand someone's perspective, you can…", "ask them and listen", ["tell them they're wrong", "guess"], "Listening helps understanding."],
  ["After listening to a classmate's view, a respectful reply is…", "“I see why you think that.”", ["“That is dumb.”", "“Nobody cares.”"], "Acknowledge their view."],
  ["You can present information to a class by…", "using a poster, a model or a talk", ["hiding it", "keeping it secret"], "Many forms can be used."],
  ["Which is a visual way to present information?", "A poster or chart", ["A whisper", "A silent room"], "Visuals can be seen."],
  ["Which is a concrete way to present information?", "A model made of clay", ["A rumour", "A whisper"], "Concrete means using a real object."],
  ["An electronic way to present information is…", "a slide show", ["a paper plane", "a poster in a drawer"], "Slides are digital."],
  ["Giving each group member a role such as reporter or timekeeper is…", "a good way to share responsibilities", ["unfair", "a waste of time"], "Roles help groups work.", true],
  ["A group gets stuck. The best step is to…", "stop, talk about the problem and try a new plan", ["blame one person", "give up"], "Working together solves problems.", true],
  ["Why should we listen to quiet group members?", "They may have great ideas too", ["They never have ideas", "Because we must"], "Every voice matters.", true],
];

export const team = bankUnit({
  id: "mb-working-together",
  title: "Working Together Fairly",
  emoji: "🧩",
  blurb: "Share jobs, listen to others and treat everyone with respect.",
  parentNote:
    "Practises group skills: sharing ideas, decisions and responsibilities, being fair and respectful, considering other people's views, listening actively and choosing ways to present information.",
  standards: ["3-S-100, 3-S-102, 3-S-104, 3-S-400, 3-S-403", "collaborating, interacting fairly, listening to perspectives and presenting information"],
  items: TEAM,
});

const FIND: Q[] = [
  ["A source of information is…", "a place where you can find facts", ["a type of snack", "a game"], "Books, people and websites are sources."],
  ["Which is a print source?", "A book", ["A song", "A photo on a phone"], "Print sources are on paper."],
  ["Which is an oral source?", "An Elder or expert telling you a story", ["A map", "A poster"], "Oral means spoken."],
  ["Which is a visual source?", "A photograph", ["A speech", "A song"], "Visual sources are seen."],
  ["Which is an electronic source?", "A kids' website", ["A paper book", "A letter"], "Electronic sources are on a screen."],
  ["A material source could be…", "an artifact such as a tool or a coin", ["a poem", "a rumour"], "Material sources are objects."],
  ["Which is the best source for facts about your community?", "The town or city's official website or library", ["A guess from a friend", "A silly cartoon"], "Trusted sources are best."],
  ["A good research question is…", "clear and can be answered by looking for information", ["unclear", "silly"], "Make a question you can research."],
  ["Which is a research question?", "How did people travel in the past?", ["Hello?", "Yes?"], "Research questions start with who, what, where, when, why or how."],
  ["Which question words are useful for research?", "who, what, where, when, why, how", ["mix, fix, mop", "red, blue, green"], "These words open a question."],
  ["Before you search, you should…", "write the question you want to answer", ["close the book", "pick a random page"], "Questions guide the search."],
  ["Organizing information means…", "putting it in a clear order or chart", ["losing it", "hiding it"], "Organizers keep facts neat."],
  ["A concept map shows…", "how ideas connect", ["a recipe", "a game score"], "It uses circles and lines."],
  ["A chart with columns is a good way to…", "compare information", ["hide it", "paint a picture"], "Charts sort facts."],
  ["An outline is…", "a plan of main ideas and details", ["a coat", "a map"], "Outlines list topics and points."],
  ["A map is a way to record information about…", "places", ["feelings only", "time only"], "Maps show where things are."],
  ["Giving the title of a book you used is called…", "referencing your sources", ["hiding sources", "copying"], "Tell where your information came from."],
  ["Why list your sources?", "So others can find the same information", ["So no one reads it", "To be silly"], "Referencing is fair and honest."],
  ["Which tool helps you measure the length of a table?", "A ruler or metre stick", ["A clock", "A scale"], "Use the right tool."],
  ["Which tool would you use to look closely at a leaf?", "A magnifying glass", ["A ruler", "A broom"], "A magnifier shows details."],
  ["Which technology helps you look up a word?", "A dictionary or a safe website", ["A hammer", "A spoon"], "Choose the tool for the job."],
  ["Which tool would help you tell the time you spent on a task?", "A clock or timer", ["A ruler", "A paintbrush"], "Time tools measure minutes."],
  ["You are asked to find out how a pond animal lives. Which is the best first step?", "Ask a question and choose sources", ["Guess", "Paint the pond"], "Plan before you search.", true],
  ["You record the temperature each day for a week. Which is a good way to organize it?", "A chart or table", ["A single sentence", "A drawing of a cloud"], "Charts show patterns.", true],
  ["Why use more than one kind of source?", "Different sources give different details", ["It is always faster", "Facts are never in books"], "Use print, visual and oral sources.", true],
];

export const findOut = bankUnit({
  id: "mb-ask-and-find",
  title: "Ask, Find & Record",
  emoji: "🗂️",
  blurb: "Ask good questions, find information, organize it and name your sources.",
  parentNote:
    "Practises the first steps of social studies research: gathering information from oral, visual, material, print and electronic sources, organizing and recording it in charts and maps, naming sources, choosing tools and forming research questions.",
  standards: ["3-S-200, 3-S-201, 3-S-203, 3-S-300", "gathering and recording information, using tools and forming research questions"],
  items: FIND,
});

const THINK: Q[] = [
  ["A fact is something that…", "can be checked and shown to be true", ["is what someone feels", "is always a guess"], "Facts can be proven."],
  ["An opinion is…", "what someone thinks or feels", ["a proven fact", "a measurement"], "Opinions are beliefs."],
  ["“Winnipeg is the capital of Manitoba.” is a…", "fact", ["opinion", "question"], "You can check it in an atlas."],
  ["“Winter is the best season.” is an…", "opinion", ["fact", "measurement"], "People can disagree."],
  ["“The Red River flows through Winnipeg.” is a…", "fact", ["opinion", "guess"], "A map shows it."],
  ["“Pizza is the tastiest food.” is an…", "opinion", ["fact", "date"], "Taste is personal."],
  ["Which sentence is a fact?", "Canada has ten provinces.", ["Canada is the prettiest country.", "Winter is the worst."], "Count them in an atlas."],
  ["Which sentence is an opinion?", "The parade was the most fun event.", ["The parade was on Saturday.", "The parade had 12 floats."], "Words like “most fun” show opinion."],
  ["Words like “best,” “worst” and “prettiest” often show a…", "opinion", ["fact", "date"], "They express feelings."],
  ["A conclusion is…", "a decision you make using information and evidence", ["a guess with no reason", "a random word"], "Conclusions are based on evidence."],
  ["You see dark clouds, wind and lightning. A fair conclusion is…", "a storm is coming", ["it is sunny", "it is a holiday"], "Use the evidence."],
  ["You see many bike tracks in the mud. A fair conclusion is…", "people biked here recently", ["a giant walked here", "it never rains"], "Evidence supports it."],
  ["A good conclusion has…", "evidence to back it up", ["no evidence", "only a feeling"], "Say how you know."],
  ["To support your idea, you can use…", "information or something you observed", ["nothing", "a rumour"], "Give a reason."],
  ["Which statement supports the idea that a park is popular?", "Many people were there on the weekend.", ["It has swings.", "I like it."], "Evidence shows what happens."],
  ["Which is a reason to support “We should recycle”?", "It reduces garbage and saves resources.", ["Because I said so", "Because of colour"], "Give a good reason."],
  ["New information can mean you…", "change your opinion", ["must stay the same", "stop listening"], "It is okay to change your mind."],
  ["You thought all birds fly. You then learn that penguins can't fly. You should…", "revise what you thought", ["ignore the fact", "say the penguin is wrong"], "Update ideas with new information."],
  ["Revising your ideas based on new information shows you are…", "a thoughtful thinker", ["wrong always", "lazy"], "Good thinkers learn."],
  ["Advantages are…", "the good points of something", ["the bad points", "the facts"], "Pros."],
  ["Disadvantages are…", "the bad points of something", ["the good points", "the answers"], "Cons."],
  ["Advantage of taking a bus to school:", "It's a way to get there without needing a ride", ["It is always late", "It never comes"], "A bus can be convenient."],
  ["Disadvantage of a long walk to school in winter:", "It can be cold", ["It's good exercise", "It's quiet"], "Weather can be a problem."],
  ["Before you pick a solution, you should…", "think about the good and bad of each choice", ["pick the first one", "flip a coin"], "Consider advantages and disadvantages.", true],
  ["A class can have a quiet reading corner or a big game table, but not both. How do they decide?", "Talk about the advantages and disadvantages and vote", ["Pick randomly", "Let one person choose"], "Compare choices fairly.", true],
  ["Which statement mixes fact and opinion?", "Manitoba has beautiful lakes; Lake Winnipeg is one of the largest in Canada.", ["Lake Winnipeg is large.", "Manitoba has lakes."], "“Beautiful” is an opinion; the size is a fact.", true],
];

export const think = bankUnit({
  id: "mb-think-it-through",
  title: "Think It Through",
  emoji: "💭",
  blurb: "Fact or opinion, evidence, conclusions and weighing solutions.",
  parentNote:
    "Practises telling fact from opinion, drawing conclusions from evidence, supporting an opinion with a reason, changing ideas with new information, and weighing advantages and disadvantages of solutions.",
  standards: ["3-S-301, 3-S-302, 3-S-303, 3-S-304, 3-S-402", "advantages and disadvantages, conclusions from evidence, revising ideas, fact and opinion and supporting ideas"],
  items: THINK,
});
