import { bankUnit, type Q } from "../own";

// More Grade 3 English language arts: listening and talking (ELA.3.A1.1 to A1.4, A1.6), sounds and words (A2.1, A2.2, A2.6),
// asking questions and choosing information (B1.1, B1.2, B1.4, C1.2, B3.1), planning writing (C1.1, C1.3, C1.4),
// making writing better (A1.5, C2.4, C2.5, C3.1), design and media (C1.5, C3.5, D1.2) and learning goals (D2.1 to D2.5).

const LISTEN: Q[] = [
  ["When you listen to a talk, a key idea is…", "an important idea you want to remember", ["the speaker's shoes", "any small detail at all"], "Key ideas are the main points."],
  ["Which helps you remember key ideas while listening?", "Jot a word or a quick picture", ["Look out the window", "Talk to a friend"], "Notes help you hold on to key ideas."],
  ["A speaker says, “Bees help flowers make seeds.” The key idea is…", "bees help flowers", ["bees are yellow", "flowers are red"], "Pick the main point."],
  ["Which shows you are listening to a classmate?", "Look at them and nod", ["Turn your back", "Draw on your desk"], "Non-verbal cues show you are listening."],
  ["Taking turns in a group talk means…", "one person speaks while others listen", ["everyone talks at once", "nobody ever talks"], "Turn taking makes talks fair."],
  ["Your friend is still speaking. What should you do?", "Wait until they finish", ["Speak over them", "Walk away"], "Waiting is part of turn taking."],
  ["A group talk is a good place to…", "share ideas and hear other ideas", ["win every argument", "stay silent all day"], "Dialogue means talking and listening."],
  ["Which is a polite way to add to someone's idea?", "“I agree, and I also think…”", ["“That is silly.”", "“Stop talking.”"], "Build on an idea kindly."],
  ["Which is a thoughtful question about a story on frogs?", "Why do tadpoles need water?", ["Is it lunch yet?", "What is your name?"], "Thoughtful questions help you think about the content."],
  ["A question that begins with “why” or “how” usually asks for…", "an explanation", ["a yes or a no only", "a number only"], "Why and how questions make people explain."],
  ["Your teacher asks, “How do you know?” You should give…", "evidence from the text or what you saw", ["a guess with nothing behind it", "no answer"], "Evidence supports your thinking."],
  ["Which answer gives evidence?", "“The book says owls hunt at night.”", ["“Just because.”", "“I don't know.”"], "Point to the book or what you observed."],
  ["A partner shares an opinion different from yours. A kind reply is…", "“Thanks for telling me. Here is what I think.”", ["“You are wrong.”", "“Nobody cares.”"], "You can disagree politely."],
  ["Saying “I felt happy when…” is a way to share…", "your feelings", ["a map", "a recipe"], "You can talk about thoughts and feelings."],
  ["Saying “I prefer cats because…” shares a…", "preference", ["fact that never changes", "rule"], "A preference is what you like best."],
  ["When you are in a large group, you can show you want to speak by…", "raising your hand", ["shouting", "tapping everyone"], "A raised hand is a social convention."],
  ["Which is a good reason to ask a question?", "You want to understand better", ["You want to interrupt", "You want to be silent"], "Questions help us understand."],
  ["After a partner talks, you can check you understood by saying…", "“So you are saying…”", ["“Whatever.”", "“I wasn't listening.”"], "Repeating the idea shows you listened."],
  ["The best time to ask a question about a talk is…", "after the speaker has finished or when invited", ["every second", "never"], "Wait for a good moment."],
  ["Which question can be answered with evidence from a story?", "Why was the fox worried?", ["What is your favourite colour?", "Where do you live?"], "Look back at the story for evidence."],
  ["Your group shares ideas one at a time. This is called…", "a group discussion", ["a spelling test", "a silent reading"], "Dialogue means ideas move between people."],
  ["Which is a way to listen with your whole body?", "Face the speaker and stay still", ["Spin in your chair", "Cover your ears"], "Quiet bodies help listeners."],
  ["A good listener can tell the group…", "one idea they heard from someone else", ["only their own idea", "nothing"], "Highlighting key ideas shows listening.", true],
  ["“I think the story was sad because the dog was lost.” This sentence gives…", "an opinion with a reason", ["only a fact", "only a question"], "The word “because” introduces a reason.", true],
  ["Two friends want to speak at the same time. The kindest plan is to…", "take turns", ["both talk louder", "stop being friends"], "Turn taking keeps talks fair.", true],
  ["Which question would help you think deeper about a story?", "What might happen next, and why?", ["Is the book heavy?", "How many pages are blue?"], "Deep questions need thinking and evidence.", true],
];

export const listening = bankUnit({
  id: "mb-listening-talking",
  title: "Listening & Talking Together",
  emoji: "👂",
  blurb: "Key ideas, taking turns, thoughtful questions and sharing opinions.",
  parentNote:
    "Practises listening for key ideas, using non-verbal cues and turn taking, asking thoughtful questions, giving evidence, and sharing thoughts and preferences in a group.",
  standards: ["ELA.3.A1.1, ELA.3.A1.2, ELA.3.A1.3, ELA.3.A1.4, ELA.3.A1.6", "listening for key ideas, turn taking, group dialogue, thoughtful questions with evidence, and sharing opinions"],
  items: LISTEN,
});

const SOUNDS: Q[] = [
  ["How many sounds (phonemes) are in the word “ship”?", "3", ["4", "2"], "Say it slowly: sh-i-p."],
  ["How many sounds are in the word “stop”?", "4", ["2", "3"], "s-t-o-p."],
  ["How many sounds are in the word “chin”?", "3", ["4", "2"], "ch-i-n. The letters c and h make one sound."],
  ["Which word starts with the same sound as “phone”?", "fish", ["pig", "hat"], "ph and f make the /f/ sound."],
  ["Blend the sounds /k/ /a/ /t/. What word is it?", "cat", ["cut", "kit"], "Push the sounds together."],
  ["Blend /b/ /l/ /o/ /w/. What word is it?", "blow", ["bow", "low"], "Say each sound, then smoosh them."],
  ["Take the /s/ off “spin.” What is left?", "pin", ["sin", "spi"], "Remove the first sound."],
  ["Change the /m/ in “mat” to /s/. What word do you get?", "sat", ["map", "mat"], "Swap the first sound."],
  ["Change the last sound of “bat” to /g/. What word do you get?", "bag", ["bad", "bit"], "Swap the final sound."],
  ["Which word rhymes with “light”?", "night", ["lit", "late"], "Rhymes end with the same sound."],
  ["Which word has the long /a/ sound as in “cake”?", "rain", ["rat", "run"], "Long a says its own name."],
  ["Which word has a silent letter?", "knee", ["tree", "bed"], "The k in knee is not said."],
  ["Which word has the /sh/ sound?", "dish", ["disk", "dig"], "The letters sh make one sound."],
  ["Which word has the /th/ sound?", "bath", ["bat", "back"], "The letters th make one sound."],
  ["Which pair is the same letter, in capital and lower case?", "B and b", ["B and d", "B and p"], "A capital and its lower-case form are the same letter."],
  ["Which is the lower-case form of “R”?", "r", ["p", "b"], "The big letter R becomes r."],
  ["The letter “a” can look different in different fonts. It is still…", "the same letter", ["a different letter", "a number"], "Fonts change the shape, not the letter."],
  ["The word “because” is a…", "high-frequency word", ["silly word", "number"], "You see high-frequency words again and again."],
  ["Which is a high-frequency word?", "said", ["zephyr", "xylophone"], "Common words come up often in reading."],
  ["Which word is spelled in an unusual way?", "friend", ["cat", "sit"], "Some words do not follow common spelling patterns."],
  ["When you see a period at the end of a sentence, your voice…", "falls and you pause", ["jumps up", "shouts"], "Punctuation helps you read with expression."],
  ["A question mark tells you to read with a voice that…", "goes up at the end", ["stays flat", "whispers"], "Questions usually rise at the end."],
  ["An exclamation mark tells you to read with…", "strong feeling", ["no feeling", "a yawn"], "Excitement is shown with “!”"],
  ["Commas tell you to…", "take a short pause", ["stop reading", "skip the words"], "A comma is a small pause."],
  ["Reading with prosody means reading with…", "expression and good phrasing", ["the fastest speed", "no voice at all"], "Prosody is how the reading sounds.", true],
  ["Which word has the most sounds?", "splash", ["sat", "ship"], "s-p-l-a-sh: five sounds.", true],
  ["Reading smoothly, not word by word, is called…", "fluency", ["fumbling", "flipping"], "Fluent readers read at a good pace.", true],
];

export const sounds = bankUnit({
  id: "mb-sounds-and-fluency",
  title: "Sounds, Letters & Fluent Reading",
  emoji: "🔤",
  blurb: "Count and blend sounds, know your letters and read with expression.",
  parentNote:
    "Practises sound awareness (segmenting, blending and changing sounds), letters in different fonts, recognizing common and tricky words quickly, and using punctuation to read with expression.",
  standards: ["ELA.3.A2.1, ELA.3.A2.2, ELA.3.A2.6", "sound awareness, letters in different fonts, high-frequency words and reading with expression"],
  items: SOUNDS,
});

const WONDER: Q[] = [
  ["Before you read about whales, it helps to think about…", "what you already know about whales", ["what you ate", "the weather in July"], "Prior knowledge helps you understand new topics."],
  ["Which is a source of knowledge for a project about bees?", "A beekeeper who visits the class", ["A game you made up", "A random guess"], "Experts and field trips teach us."],
  ["A field trip to a farm can help you learn…", "about how food is grown", ["nothing at all", "only how to ride a bus"], "Real experiences add knowledge."],
  ["An Elder shares a story with your class. This is a way to…", "learn from people in the community", ["skip reading", "end the topic"], "Elders and knowledge keepers share wisdom."],
  ["What do you do when you activate prior knowledge?", "Think about what you already know", ["Close the book", "Draw a rocket"], "You connect new ideas to old ideas."],
  ["Which is a focused question about plants?", "What do seeds need to sprout?", ["Plants?", "Is it Tuesday?"], "A focused question is clear and specific."],
  ["A focused question starts from…", "something you noticed", ["something you ate", "nothing"], "Observations lead to questions."],
  ["You notice leaves turn colour in autumn. A good question is…", "Why do leaves change colour?", ["Who cares?", "Is my shoe blue?"], "Ask what you wonder about."],
  ["A group investigates how fast snow melts. Which question fits?", "Does snow melt faster in sun or shade?", ["What time is lunch?", "How tall is the school?"], "Questions guide the investigation."],
  ["You find five facts about wolves. Two are about dogs. You should…", "leave out the facts that don't fit your topic", ["keep every fact", "throw all the facts away"], "Decide what to share or omit."],
  ["When you review your notes, you decide what to…", "keep and what to leave out", ["lose forever", "erase from the library"], "Choose what is important for your audience."],
  ["A fact that is not about your topic is a…", "detail you may leave out", ["main idea", "title"], "Stay on topic."],
  ["Which source is likely to have accurate facts about volcanoes?", "A nonfiction book from the library", ["A silly cartoon", "A rumour"], "Use trusted sources."],
  ["A mentor in writing is…", "an author or expert whose work you learn from", ["a type of pencil", "a spelling mistake"], "Mentor texts show good writing."],
  ["A model text helps you see…", "how a text is put together", ["how to hide a book", "which desk is yours"], "Models show a form to follow."],
  ["Which is a digital source of information?", "A website for kids written by scientists", ["A shopping bag", "A cloud in the sky"], "Digital sources include safe sites."],
  ["Which source can be audio?", "A podcast", ["A poster", "A pencil case"], "Audio sources are heard."],
  ["After finding new information, you can…", "talk about it with others", ["hide it", "forget it"], "Discussing helps you understand."],
  ["A story shows many kinds of families. This shows…", "diversity", ["a mistake", "only one way to live"], "Diversity means differences are shown."],
  ["Inclusion in a story means…", "everyone is welcomed and belongs", ["only some belong", "nobody speaks"], "Inclusive stories welcome all."],
  ["A book shows a child using a wheelchair joining a game. The book shows…", "inclusion", ["a bad ending", "a recipe"], "Everyone joins in."],
  ["Which book shows diversity?", "A story with characters from many cultures", ["A book of blank pages", "A phone book"], "Diverse stories include many people."],
  ["Telling a friend what a story says about being fair is…", "sharing how an idea is presented", ["copying", "spelling"], "You share what you notice.", true],
  ["Which question would NOT help a group investigate worms?", "What is on TV tonight?", ["What do worms eat?", "Where do worms live?"], "Questions should relate to the topic.", true],
  ["You have too many facts for a one-page poster. You should…", "choose the most important facts", ["use the smallest print", "add more facts"], "Decide what to share or omit.", true],
  ["Why is it good to use more than one source?", "You can check facts and learn more", ["It is faster to lose them", "It makes the work longer for no reason"], "Two sources can agree and add detail.", true],
];

export const wonder = bankUnit({
  id: "mb-wonder-and-find-out",
  title: "Wonder & Find Out",
  emoji: "🔍",
  blurb: "What you know, good questions, choosing facts and stories that include everyone.",
  parentNote:
    "Practises using what you already know, asking focused questions, choosing information from sources, deciding what to include, and noticing diversity and inclusion in stories.",
  standards: ["ELA.3.B1.1, ELA.3.B1.2, ELA.3.B1.4, ELA.3.B3.1, ELA.3.C1.2", "prior knowledge, focused questions, selecting information, sources and diversity in texts"],
  items: WONDER,
});

const PLAN: Q[] = [
  ["Before writing, a writer should first…", "choose a topic", ["hand in the work", "erase the page"], "Planning begins with a topic."],
  ["Which topic comes from personal experience?", "The day I learned to skate", ["Facts about Mars I never read", "A rule I never heard"], "Write about what you know."],
  ["Who is a writer's audience?", "The people who will read the writing", ["The pencil", "The desk"], "Think about who will read it."],
  ["A note to a younger child should use…", "simple, friendly words", ["very hard words", "no words"], "Fit the writing to the audience."],
  ["The purpose of writing is…", "the reason you are writing", ["the colour of the paper", "the length of a word"], "Purpose may be to tell, explain, describe or persuade."],
  ["Writing to convince people to recycle has the purpose to…", "persuade", ["describe a pet", "tell a joke only"], "Persuasive writing asks readers to agree."],
  ["Writing a story about a lost mitten is…", "narrative writing", ["informational writing", "a recipe"], "A narrative tells a story."],
  ["Writing facts about owls is…", "informational writing", ["narrative writing", "a poem"], "Informational writing explains facts."],
  ["Writing about how a puppy looks, sounds and feels is…", "descriptive writing", ["persuasive writing", "a list of rules"], "Description paints a picture with words."],
  ["“You should come to our class play!” is…", "persuasive writing", ["informational writing", "a map"], "It tries to convince the reader."],
  ["Which planning tool lists ideas as a web?", "A word web", ["A ruler", "A calendar"], "A word web connects ideas."],
  ["Brainstorming means…", "thinking of lots of ideas quickly", ["choosing the last idea", "writing a final copy"], "Brainstorming gets ideas flowing."],
  ["A list of topics for a story is a kind of…", "planning", ["publishing", "erasing"], "Lists help you plan."],
  ["Asking yourself questions about a topic helps you…", "find ideas to write", ["lose your place", "fill the page with ink"], "Questions are a planning strategy."],
  ["Drawing a picture before writing can help you…", "think of details", ["skip the writing", "forget the topic"], "Drawings are a planning strategy."],
  ["A thinking map or graphic organizer helps you…", "sort your ideas", ["pack a bag", "paint a wall"], "Organizers keep ideas in order."],
  ["A research planner helps you…", "plan what to find out", ["avoid questions", "hide notes"], "Plan your research."],
  ["For a story, which is the best order for a plan?", "Beginning, middle, end", ["End, end, end", "Title, title, title"], "Stories have a beginning, middle and end."],
  ["Which type of writing would explain how a seed grows?", "Informational", ["Narrative only", "Persuasive only"], "It explains how something works."],
  ["A story about a dragon who learns to share is a…", "story (fiction)", ["science report", "weather chart"], "Fiction is made up."],
  ["A poster that tells people to walk to school uses…", "persuasive writing", ["a poem only", "a diary"], "It urges people to act."],
  ["Which genre tells true facts about a topic?", "Nonfiction", ["Fairy tale", "Fable"], "Nonfiction is true."],
  ["A sensory web lists what you see, hear, smell and…", "feel", ["owe", "pay"], "Sensory words come from the five senses.", true],
  ["Why plan before you write?", "It helps your ideas stay organized", ["It makes writing slower for no reason", "It is only for adults"], "Plans save time and keep writing clear.", true],
  ["Your audience is your grandparents. Which opening fits?", "“Dear Grandma, guess what I did today!”", ["“Yo!!!”", "“To whom it may concern, the end.”"], "Choose words that fit who reads it.", true],
  ["Writing an invitation to a birthday needs the date, time and…", "place", ["moon colour", "pet name"], "Invitations give key information.", true],
];

export const plan = bankUnit({
  id: "mb-plan-your-writing",
  title: "Plan Your Writing",
  emoji: "📝",
  blurb: "Topics, audience, purpose, planning tools and kinds of writing.",
  parentNote:
    "Practises choosing a topic from experience, thinking about audience and purpose, using planning tools such as webs and organizers, and telling narrative, informational, descriptive and persuasive writing apart.",
  standards: ["ELA.3.C1.1, ELA.3.C1.3, ELA.3.C1.4", "choosing a topic for an audience and purpose, planning strategies and types of writing"],
  items: PLAN,
});

const BETTER: Q[] = [
  ["“I like my dog.” Which sentence adds a descriptive word?", "I like my fluffy brown dog.", ["I like my dog dog.", "Dog my like I."], "Descriptive words tell more about a noun."],
  ["Which sentence uses a stronger verb?", "The cat pounced on the toy.", ["The cat went on the toy.", "The cat did the toy."], "Strong verbs show action clearly."],
  ["“We went to the park.” Which makes it more interesting?", "We raced to the sunny park.", ["We park.", "We went went."], "Add specific words."],
  ["Which sentence has a varied pattern, starting differently?", "After lunch, we played tag.", ["We played. We played. We played.", "Play we tag."], "Vary how sentences begin."],
  ["Which is a complex sentence?", "I took an umbrella because it was raining.", ["It rained.", "Umbrella."], "A complex sentence has two ideas joined by a word like because."],
  ["Which word joins two ideas?", "because", ["happy", "soft"], "Because, when, although and after are connecting words."],
  ["Choose the best word: “I stayed inside _____ it was cold.”", "because", ["banana", "under"], "The second part gives a reason."],
  ["Choose the best word: “_____ the bell rang, we lined up.”", "When", ["Green", "Bark"], "When tells about time."],
  ["Choose the best word: “I like soccer, _____ my sister likes swimming.”", "but", ["so", "the"], "But shows a difference."],
  ["A transition word tells the reader…", "how ideas connect", ["how to spell", "where to stop reading"], "Words like first, next and finally are transitions."],
  ["Which is a transition word that shows order?", "Next", ["Purple", "Lamp"], "First, next, then and finally show order."],
  ["Which sentence makes sense?", "The kids ate lunch outside.", ["Kids the outside ate lunch.", "Lunch kids eat the the."], "Read your writing to check it makes sense."],
  ["Which sentence does NOT make sense?", "The bike drank the sunny sandwich.", ["The bike has two wheels.", "She rode her bike."], "Notice when writing doesn't make sense."],
  ["You read your story aloud and one part is confusing. You should…", "revise that part", ["delete the whole story", "ignore it"], "Revising makes writing clearer."],
  ["Revising means…", "making changes to improve your writing", ["copying someone's work", "putting your pencil away"], "You add, remove and change words."],
  ["Which change is a revision?", "Adding a detail sentence", ["Throwing the page away", "Smudging the ink"], "Revisions improve content."],
  ["A classmate says, “Tell me more about the storm.” You can…", "add details about the storm", ["erase the storm", "hide your paper"], "Use feedback to improve."],
  ["Seeking feedback means…", "asking someone what they think of your writing", ["hiding it", "reading it only to yourself"], "Feedback helps writers."],
  ["If two sentences say the same thing, you can…", "remove one", ["add a third", "colour them"], "Remove repeated ideas."],
  ["Which word is more specific than “thing”?", "backpack", ["it", "stuff"], "Specific words are clearer."],
  ["Which sentence shows an opinion in your own voice?", "I think the best part was the giant slide!", ["There are 24 hours in a day.", "Slides are objects."], "Voice shows how you think and feel."],
  ["Good handwriting means letters have the right size, spacing and…", "placement on the line", ["colour of ink only", "number of words"], "Letters sit on the line and have even spacing."],
  ["Margins are…", "the blank space around the edge of a page", ["the title", "the end"], "Margins keep writing neat."],
  ["On a computer, choosing a clear font size helps readers…", "read easily", ["get lost", "skip words"], "Large, clear fonts help readers.", true],
  ["Which font choice is best for a poster for a group across the room?", "Large, bold letters", ["Tiny letters", "Curly tiny letters in pale yellow"], "Think of your audience.", true],
  ["Which pair of sentences is joined best?", "I was tired, so I went to bed early.", ["I was tired so so so.", "Tired bed I went."], "A connecting word links the ideas.", true],
];

export const better = bankUnit({
  id: "mb-make-writing-better",
  title: "Make Writing Better",
  emoji: "✏️",
  blurb: "Strong words, joining ideas, revising and neat writing.",
  parentNote:
    "Practises adding descriptive words, joining ideas with connecting and transition words, noticing when writing doesn't make sense, revising with feedback, and neat handwriting and word processing.",
  standards: ["ELA.3.A1.5, ELA.3.C2.4, ELA.3.C2.5, ELA.3.C3.1", "complex sentences and transitions, voice, revising with feedback and neat letter formation"],
  items: BETTER,
});

const MEDIA: Q[] = [
  ["A multimodal text uses…", "more than one way to share a message", ["only one letter", "only silence"], "Words, pictures and sound are modes."],
  ["Which is a multimodal text?", "A poster with words and pictures", ["A page with one word", "A blank page"], "It uses text and images."],
  ["Which of these uses sound and images?", "A video", ["A pencil", "A bookmark"], "Video has sound, images and sometimes words."],
  ["A slide show with narration uses…", "pictures and a spoken voice", ["only a pencil", "no sound or images"], "Narration means someone talks over it."],
  ["Oral storytelling uses…", "your voice to share a story", ["only a screen", "only a pencil"], "Stories can be told aloud."],
  ["A photo essay tells ideas with…", "photos and short words", ["only numbers", "an empty page"], "Pictures carry the message."],
  ["A song can be a text because it…", "shares a message", ["is always short", "has no words"], "Songs communicate ideas."],
  ["A research report or project can be shared as…", "a poster, slide show or book", ["only a rock", "only a puzzle"], "Many forms can share what you learned."],
  ["Planning the layout of a poster means…", "deciding where words and pictures go", ["choosing the paper brand", "counting the pages"], "Layout is how things are arranged."],
  ["A good title on a poster should be…", "big and easy to read", ["tiny and hidden", "upside down"], "Titles tell people what it is about."],
  ["Which picture belongs on a poster about frogs?", "A photo of a frog in a pond", ["A truck", "A birthday cake"], "Visuals should fit the topic."],
  ["Which is relevant to a report on apples?", "A picture of an apple tree", ["A picture of a moon rocket", "A picture of a bicycle"], "Pick relevant visuals."],
  ["Font colour that is hard to read on the background is a…", "bad choice", ["good choice", "required"], "Choose colours with good contrast."],
  ["Which colour choice is easiest to read?", "Dark blue words on a white page", ["Light yellow words on white", "Pale grey on white"], "Contrast helps the reader."],
  ["A graphic organizer on a computer can help you…", "put ideas in order before you write", ["lose your work", "erase your name"], "Digital tools can plan too."],
  ["You can use a visual aid in a talk to…", "help the audience understand", ["hide the topic", "fill the room with noise"], "Visual aids support the message."],
  ["Which would be the best visual aid for a talk on the water cycle?", "A labelled diagram", ["A blank sheet", "A random photo"], "Diagrams show how parts connect."],
  ["Choosing an artifact for your talk means choosing…", "an object that supports your message", ["the loudest toy", "an object that has nothing to do with it"], "Artifacts can show what you mean."],
  ["Digital tools can help you…", "share ideas in new ways", ["avoid learning", "stop reading"], "Slides, recordings and drawings are digital tools."],
  ["Who should you think of before choosing your mode of communication?", "Your audience", ["Your shoes", "Your desk"], "Pick the mode that works for them."],
  ["To tell a younger class how to stay safe, a good mode is…", "a short poster with simple pictures", ["a long report with tiny print", "a blank card"], "Match the mode to the audience."],
  ["To share a story with a grandparent far away, a good mode is…", "a recorded video or audio message", ["a locked box", "a drawing of nothing"], "Video and audio can travel."],
  ["Adding a sound to your slide show changes the…", "effect on the audience", ["spelling of words", "page number"], "Modes change how a message feels.", true],
  ["Which is the best purpose for a poster with an arrow and “Recycle here”?", "To tell people what to do", ["To tell a story", "To sing"], "Signs direct people.", true],
  ["A video can show something a book cannot easily show, like…", "movement and sound", ["silence only", "nothing"], "Different modes have different strengths.", true],
  ["Why use fewer words and a clear picture on a slide?", "So the audience can take it in quickly", ["So nobody sees it", "So it is hard to read"], "Keep slides simple.", true],
];

export const media = bankUnit({
  id: "mb-media-and-design",
  title: "Posters, Slides & Media",
  emoji: "🖼️",
  blurb: "Share ideas with words, pictures, sound and design.",
  parentNote:
    "Practises multimodal texts (posters, slide shows, videos, photo essays), planning a layout, choosing visuals and fonts, and picking the best way to share a message with an audience.",
  standards: ["ELA.3.C1.5, ELA.3.C3.5, ELA.3.D1.2", "multimodal texts, layout and visuals, choosing a mode for an audience and visual aids"],
  items: MEDIA,
});

const GOALS: Q[] = [
  ["A learning goal is…", "something you want to get better at", ["a prize", "a school bus"], "Goals help you grow."],
  ["Which is a specific reading goal?", "I will read for 15 minutes each night.", ["I will be good.", "I will try."], "Specific goals say what and how."],
  ["Which is a specific writing goal?", "I will add a capital letter to the start of each sentence.", ["Write better.", "Do more."], "A specific goal names the action."],
  ["Which is a listening goal?", "I will wait for others to finish before I speak.", ["I will run.", "I will paint."], "Listening goals are about how you listen."],
  ["Which is a speaking goal?", "I will speak loudly enough for the back row to hear.", ["I will sit.", "I will cut paper."], "Speaking goals are about your talking."],
  ["Which goal uses the word “viewing”?", "I will look carefully at the diagram to find details.", ["I will clap.", "I will skip."], "Viewing means looking at images and videos."],
  ["Which goal is about representing?", "I will show my idea in a clear drawing.", ["I will whisper.", "I will hop."], "Representing is sharing ideas in pictures or models."],
  ["Self-monitoring means…", "checking how you are doing as you learn", ["playing a game", "asking someone else to do the work"], "You watch your own learning."],
  ["While reading, you stop and ask, “Does this make sense?” This is…", "self-monitoring", ["napping", "cheating"], "You are checking your understanding."],
  ["A strategy is…", "a plan or trick that helps you learn", ["a kind of snack", "a mistake"], "Strategies help you solve problems."],
  ["Which is a reading strategy?", "Look back at the pictures for clues", ["Close your eyes", "Skip all the words"], "Pictures can help with meaning."],
  ["If a strategy isn't working, you should…", "try a different strategy", ["give up forever", "hide it"], "Think about which strategies work."],
  ["Thinking aloud means…", "saying your thinking out loud", ["sleeping", "turning the volume down"], "It lets you hear your own strategies."],
  ["Criteria are…", "the things that tell you what good work looks like", ["the answers", "mistakes"], "A rubric lists criteria."],
  ["A rubric is a tool that…", "shows what to aim for", ["is a kind of pencil", "ends the lesson"], "It lists levels of quality."],
  ["Which tool can help you check your own learning?", "A learning journal", ["A rubber duck", "A lunch box"], "Journals, lists and mind maps all help."],
  ["Descriptive feedback tells you…", "what you did well and what to work on", ["only “good job”", "nothing"], "Specific feedback is more useful."],
  ["Which is descriptive feedback?", "“Your story has a strong beginning. Try adding more detail in the middle.”", ["“Nice.”", "“Okay.”"], "It gives details."],
  ["After getting feedback, a learner should…", "decide on changes to make", ["hide the work", "argue with everyone"], "Feedback helps you choose next steps."],
  ["A next step is…", "what you will do to keep improving", ["a staircase", "the end of the day"], "Think about what to do next."],
  ["Tracking your progress means…", "keeping a record of how you are improving", ["throwing work away", "forgetting what you learned"], "A chart can show your progress."],
  ["Reflecting on an accomplishment means…", "thinking about what you learned or did well", ["pretending it didn't happen", "ignoring it"], "Reflection helps you notice growth."],
  ["Which sentence shows reflecting?", "“I used the word web and it helped me find ideas.”", ["“I like cookies.”", "“It is Monday.”"], "You notice what worked.", true],
  ["Which goal is better, A or B? A: “Read more.” B: “Read two chapters of my book by Friday.”", "B", ["A", "Both are the same"], "Specific goals can be measured.", true],
  ["You set a goal to learn 10 new words and learned 8. A kind way to think about it is…", "“I learned a lot! I will keep working on 2 more.”", ["“I always fail.”", "“It doesn't matter.”"], "Celebrate progress and plan next steps.", true],
];

export const goals = bankUnit({
  id: "mb-learning-goals",
  title: "My Learning Goals",
  emoji: "🎯",
  blurb: "Set goals, check how you're learning and use feedback to grow.",
  parentNote:
    "Practises self-monitoring, choosing strategies, using criteria and rubrics, using feedback, setting specific goals for listening, speaking, reading, writing, viewing and representing, and tracking progress.",
  standards: ["ELA.3.D2.1, ELA.3.D2.2, ELA.3.D2.3, ELA.3.D2.4, ELA.3.D2.5", "self-monitoring, criteria, feedback, learning goals and tracking progress"],
  items: GOALS,
});
