import { bankUnit, type Q } from "../own";

// Grade 3 social studies, Global Communities: maps and globes (3-KL-014 to 3-KL-016, 3-KL-020, 3-S-205 to 3-S-207),
// life in communities around the world, needs and rights, and an ancient society (3-KH-021 to 3-KH-026).

const MAPS: Q[] = [
  ["A globe is a model of…", "Earth", ["the Moon", "a city"], "A globe is a round map of the whole Earth."],
  ["The equator is an imaginary line that goes…", "around the middle of Earth", ["from pole to pole", "only through Canada"], "The equator circles Earth halfway between the poles."],
  ["The half of Earth north of the equator is the…", "Northern Hemisphere", ["Southern Hemisphere", "Eastern Ocean"], "North of the equator is the Northern Hemisphere."],
  ["The half of Earth south of the equator is the…", "Southern Hemisphere", ["Northern Hemisphere", "Arctic"], "South of the equator is the Southern Hemisphere."],
  ["Canada is in the…", "Northern Hemisphere", ["Southern Hemisphere", "middle of the equator"], "Canada is north of the equator."],
  ["Australia is in the…", "Southern Hemisphere", ["Northern Hemisphere", "Arctic Ocean"], "Australia is south of the equator."],
  ["How many continents are there?", "7", ["3", "12"], "The seven continents are Africa, Antarctica, Asia, Australia, Europe, North America and South America."],
  ["Which continent is Canada on?", "North America", ["Europe", "Africa"], "Canada is in North America."],
  ["Which is the coldest continent, covered in ice?", "Antarctica", ["Africa", "Australia"], "Antarctica is at the South Pole."],
  ["Egypt is on the continent of…", "Africa", ["Europe", "South America"], "Egypt is in the north-east of Africa."],
  ["Brazil is on the continent of…", "South America", ["Asia", "Antarctica"], "Brazil is in South America."],
  ["Japan is on the continent of…", "Asia", ["Africa", "Europe"], "Japan is an island country in Asia."],
  ["How many oceans are named on most maps?", "5", ["2", "9"], "The five oceans are the Pacific, Atlantic, Indian, Southern and Arctic."],
  ["Which is the largest ocean?", "Pacific Ocean", ["Arctic Ocean", "Indian Ocean"], "The Pacific is the largest."],
  ["Which ocean is at the very top of the world?", "Arctic Ocean", ["Indian Ocean", "Southern Ocean"], "The Arctic Ocean surrounds the North Pole."],
  ["A map's title tells you…", "what the map shows", ["how old it is", "who drew it"], "The title names the map's topic."],
  ["A legend (key) on a map explains…", "what the symbols mean", ["the weather", "the date"], "A legend lists the symbols and what they stand for."],
  ["A compass rose shows…", "directions", ["distances", "prices"], "It shows north, south, east and west."],
  ["The four cardinal directions are…", "north, south, east and west", ["up, down, in and out", "left, right, front and back"], "N, S, E and W are the cardinal directions."],
  ["On most maps, north is toward the…", "top", ["bottom", "left"], "North is usually at the top of the map."],
  ["Which direction is opposite to north?", "south", ["east", "west"], "South is the opposite of north."],
  ["Which direction is opposite to east?", "west", ["north", "south"], "West is the opposite of east."],
  ["A photograph taken from an airplane looking down is an…", "aerial photograph", ["portrait", "globe"], "Aerial photographs show places from above."],
  ["A picture of Earth taken by a satellite is a…", "satellite image", ["drawing of a legend", "compass rose"], "Satellites take pictures from space."],
  ["Maps, aerial photographs and satellite images all…", "show places on Earth", ["tell stories only", "play music"], "They are ways of representing the land and water."],
  ["On a map the school is north of the park. To get from the park to the school you go…", "north", ["south", "east"], "North of the park means up from the park.", true],
  ["The library is east of the store. The store is…", "west of the library", ["east of the library", "north of the library"], "If A is east of B, then B is west of A.", true],
  ["You are facing north. Which direction is behind you?", "south", ["east", "west"], "Behind north is south.", true],
];

export const maps = bankUnit({
  id: "mb-world-maps",
  title: "Maps of Our World",
  emoji: "🗺️",
  blurb: "Globes, continents, oceans, hemispheres and reading a map with a title, legend and compass rose.",
  parentNote:
    "Practises the equator and the Northern and Southern Hemispheres, the continents and oceans, and reading maps, aerial photographs and satellite images with a title, legend, compass rose and the four cardinal directions.",
  standards: ["3-KL-014, 3-KL-015, 3-KL-016, 3-KL-020, 3-S-205, 3-S-206, 3-S-207", "the equator and hemispheres, continents and oceans, map tools and cardinal directions"],
  items: MAPS,
});

const LIFE: Q[] = [
  ["Culture includes people's…", "language, food, music and ways of life", ["only their age", "only their address"], "Culture is the way a group of people live and express themselves."],
  ["Which is part of a community's culture?", "The songs and stories people share", ["The colour of a bus", "The number of windows"], "Songs and stories are cultural expression."],
  ["Housing in a very hot, dry place is often built to…", "stay cool", ["hold in the heat", "float on snow"], "People build homes to suit the weather."],
  ["In a very cold place, homes are built to…", "keep warm", ["stay cool", "let in all the wind"], "Warm homes help people stay safe in cold places."],
  ["Houses on stilts above water are common in places that have…", "floods", ["no rain at all", "deep snow"], "Stilts keep homes above the water."],
  ["Many people in a rainy, forested place use wood for building because…", "trees are nearby", ["wood is never found", "they cannot cut it"], "People use natural resources they can find."],
  ["Natural resources are…", "things from nature that people use", ["toys", "machines"], "Water, trees, soil and fish are natural resources."],
  ["Which is a natural resource?", "Water", ["A plastic toy", "A phone"], "Water comes from nature."],
  ["A community near the ocean might get food by…", "fishing", ["farming wheat in the sea", "mining coal in the water"], "Communities near the sea often fish."],
  ["A community in rich farmland might have many…", "farms", ["fishing boats only", "glaciers"], "Good soil helps farmers grow food."],
  ["Which is a way people express culture?", "Dancing", ["Sleeping", "Waiting for a bus"], "Dance, music and art express culture."],
  ["Clothing often depends on…", "weather and traditions", ["nothing", "only the day of the week"], "People wear clothing that suits the weather and their traditions."],
  ["Learning about other cultures can help us…", "understand and respect others", ["feel scared", "avoid people"], "Curiosity and respect help people get along."],
  ["Is it kind to say another culture's food is “weird”?", "No, it is kinder to be curious", ["Yes, always", "Yes, if you do not like it"], "Using respectful language shows we value diversity."],
  ["Which sentence uses respectful language?", "Her family eats different foods than mine.", ["Her food is gross.", "Those people are strange."], "Respectful language describes differences kindly."],
  ["If your community and another both celebrate with food, you share…", "something in common", ["nothing at all", "the same house"], "Many communities share ideas like celebrating together."],
  ["Which is a difference between a city and a small village?", "A city usually has more people", ["A village has more tall buildings", "A city has fewer roads"], "Cities are larger and busier."],
  ["Mass media like TV and the internet can sometimes show…", "only part of what a place is like", ["everything about a place", "nothing"], "Media can leave out many things, so we should ask questions."],
  ["Before you decide what a faraway place is like, you should…", "look at more than one source", ["believe the first picture", "never learn about it"], "More than one source gives a fuller picture."],
  ["Weather such as heavy rain or very high winds can change how people…", "build and travel", ["sleep at night only", "speak"], "Natural events affect daily life."],
  ["Which good is made from something that grows on a farm?", "Bread", ["A bicycle", "A glass window"], "Bread comes from wheat grown on farms."],
  ["Which is a technology that helps farmers?", "A tractor", ["A paper plate", "A birthday card"], "A tractor is a tool that helps do farm work."],
  ["Which is a job in a fishing community?", "Boat builder", ["Ski instructor", "Camel driver"], "Boats are needed where people fish."],
  ["Communities meet their members' needs by…", "sharing work, food and shelter", ["keeping everything secret", "staying apart"], "Communities work together to meet needs."],
  ["Is every community around the world alike?", "No, they are diverse", ["Yes, all the same", "Only big ones differ"], "Communities have many different ways of life."],
  ["A place with long dry seasons might grow crops that…", "need little water", ["need a lot of rain", "only grow in snow"], "People grow plants that suit the land.", true],
  ["People in one community use a tool to carry water because…", "it is a need in their way of life", ["tools are never needed", "water is never needed"], "Tools help meet needs.", true],
  ["Which statement best compares your daily life to life in another community?", "Some things are alike and some are different", ["Everything is the same", "Nothing is the same"], "Comparing finds both similarities and differences.", true],
];

export const life = bankUnit({
  id: "mb-global-communities",
  title: "Communities Around the World",
  emoji: "🌍",
  blurb: "How land, climate, resources and culture shape daily life in communities far and near.",
  parentNote:
    "Practises daily life in communities around the world: homes, food, work and technology that suit the land and weather, cultural expression, respectful language about differences and how media can show only part of a place.",
  standards: ["3-KI-009, 3-KI-010, 3-KI-011, 3-KI-012, 3-KI-013, 3-KL-017, 3-KL-018, 3-KE-035, 3-KE-036, 3-KE-038, 3-S-401", "ways of life, culture and how land and resources shape work, goods and homes"],
  items: LIFE,
});

const NEEDS: Q[] = [
  ["Basic human rights include…", "clean water and food", ["video games", "a pet"], "Everyone needs safe water, food, shelter and care."],
  ["Which is a basic need for every person?", "Shelter", ["A toy robot", "A new bike"], "Shelter protects people from weather."],
  ["Which is a basic human right?", "Going to school", ["Owning a boat", "Having a phone"], "Education is a right of children everywhere."],
  ["Sharing helps communities because…", "more people have what they need", ["nobody gets anything", "it makes things unfair"], "Fairness and sharing help meet needs."],
  ["Fairness means…", "treating people in a just way", ["giving everything to one person", "ignoring rules"], "Fair means each person is treated justly."],
  ["A country is a kind of community with…", "borders", ["no people", "only one house"], "Borders mark where one country ends."],
  ["Which is a country?", "Canada", ["Winnipeg", "Atlantic Ocean"], "Canada is a country; Winnipeg is a city."],
  ["A border is…", "a line between countries", ["a type of food", "a compass"], "Borders separate countries."],
  ["Which is a concern shared by communities around the world?", "Having clean water", ["Choosing a game", "Picking a colour"], "Many communities need safe water."],
  ["Another concern for communities everywhere is…", "keeping people healthy", ["building a skate park only", "choosing a movie"], "Health care matters in every community."],
  ["Which group helps children around the world?", "UNICEF", ["A toy store", "A cartoon channel"], "UNICEF is part of the United Nations and helps children."],
  ["The United Nations is an organization of…", "many countries working together", ["only one country", "cartoon characters"], "Countries join the UN to cooperate."],
  ["The Red Cross and Red Crescent help people…", "during emergencies and disasters", ["with homework", "pick toys"], "They give help in emergencies."],
  ["A food bank helps people get…", "food", ["new cars", "airplane tickets"], "Food banks give food to people who need it."],
  ["Which service helps people stay healthy?", "A hospital", ["A theme park", "A toy shop"], "Hospitals care for sick and hurt people."],
  ["Which service helps people learn?", "A school", ["A bakery", "A gas station"], "Schools help children learn."],
  ["A clean water well in a village helps people…", "meet a basic need", ["avoid learning", "get lost"], "Clean water is a basic need."],
  ["Which communities have the same basic needs?", "All communities", ["Only big cities", "Only far north"], "Every community has needs for food, water and shelter."],
  ["Which is a way that communities around the world are alike?", "People celebrate special days", ["They all speak one language", "They all live in snow"], "Celebrating is something many communities share."],
  ["Which is an example of a connection between communities?", "Food or goods traded across the world", ["Nothing is ever traded", "Only toys are traded"], "Trade connects communities."],
  ["Buying fruit grown in another country is a link between…", "your community and a faraway one", ["your home and your yard", "two rooms"], "Goods travel around the world."],
  ["You can help people far away by…", "donating to a trusted charity", ["throwing garbage", "ignoring everyone"], "Giving thoughtfully can help others."],
  ["Taking short showers and not wasting water helps…", "protect a shared resource", ["nothing", "make more garbage"], "Saving water helps people everywhere."],
  ["Collecting warm clothes for a drive helps…", "people who need them", ["nobody", "only the one giving"], "Donations can meet needs."],
  ["Which action shows care for the environment?", "Recycling paper", ["Dumping garbage in a river", "Leaving taps on"], "Recycling reduces waste."],
  ["All human beings are equal means…", "everyone deserves the same respect", ["only some deserve respect", "boys and girls are different in worth"], "Equality means equal worth.", true],
  ["A child far away has a different language and the same right to…", "be safe and learn", ["be left out", "go without food"], "Every child has the same basic rights.", true],
  ["Why can sharing between countries be important during a flood or earthquake?", "Other countries can send help", ["Floods fix themselves", "Nobody ever needs help"], "Countries often help one another in emergencies.", true],
];

export const needs = bankUnit({
  id: "mb-needs-and-rights",
  title: "Needs, Rights & Sharing",
  emoji: "💧",
  blurb: "Basic needs and rights, fairness, and how people and groups help communities worldwide.",
  parentNote:
    "Practises basic human rights and needs, fairness and sharing, countries as communities with borders, concerns common to communities worldwide, organizations such as UNICEF and the Red Cross, and personal choices that can help people elsewhere.",
  standards: ["3-KC-005, 3-KC-006, 3-KI-008, 3-KG-027, 3-KG-028, 3-KG-029, 3-KG-030, 3-KG-031, 3-VC-001, 3-VC-003, 3-VG-009, 3-KE-037", "basic rights and needs, fairness and sharing, and organizations that support communities"],
  items: NEEDS,
});

const ANCIENT: Q[] = [
  ["Ancient Egypt grew up along the…", "Nile River", ["Amazon River", "Rhine River"], "The Nile gave water and rich soil."],
  ["Ancient Egyptians farmed because the Nile flooded and left behind…", "rich soil", ["snow", "ice"], "The yearly flood made land good for crops."],
  ["The leader of ancient Egypt was called the…", "pharaoh", ["mayor", "principal"], "A pharaoh ruled ancient Egypt."],
  ["Ancient Egyptians wrote using pictures called…", "hieroglyphs", ["emojis", "numbers"], "Hieroglyphs are picture symbols for sounds and ideas."],
  ["Ancient Egyptians wrote on a paper-like material made from…", "papyrus reeds", ["wool", "plastic"], "Papyrus grew along the Nile."],
  ["Huge stone tombs that ancient Egyptians built are the…", "pyramids", ["castles", "igloos"], "The pyramids are tombs for pharaohs."],
  ["Most ancient Egyptian homes were made of…", "mud bricks", ["glass", "steel"], "Mud and straw were easy to find near the river."],
  ["Many ancient Egyptians worked as…", "farmers", ["astronauts", "airline pilots"], "Most people farmed near the Nile."],
  ["What did ancient Egyptians use to travel on the Nile?", "boats", ["trains", "cars"], "The river was like a road."],
  ["Ancient Egyptians often wore clothes made of…", "linen", ["nylon", "fleece"], "Linen is made from the flax plant and is light in hot weather."],
  ["Why was light clothing useful in Egypt?", "The weather was hot", ["It was snowy", "It was always windy"], "Light clothing suits a hot climate."],
  ["Ancient Egyptians believed in many…", "gods and goddesses", ["video games", "airlines"], "Their stories and traditions included many gods."],
  ["A story or custom passed down by ancient Egyptians is an example of…", "tradition", ["a modern invention", "a mistake"], "Customs and stories are traditions."],
  ["Which was a custom of ancient Egypt?", "Preserving bodies as mummies", ["Sending text messages", "Flying kites made of nylon"], "Mummification was a custom of ancient Egypt."],
  ["Ancient Egyptians expressed themselves through…", "art, music and building", ["only mobile phones", "TV shows"], "Art and architecture were ways to express ideas."],
  ["Which is a contribution of ancient Egypt we still use?", "A 365-day calendar idea", ["Electric lights", "Cell phones"], "Their calendar ideas influenced later calendars."],
  ["Paper-like writing material from ancient Egypt led to the idea of…", "paper", ["plastic bags", "TV"], "The word “paper” comes from papyrus."],
  ["Ancient means…", "from a very long time ago", ["very new", "from last year"], "Ancient societies lived thousands of years ago."],
  ["A timeline puts events in…", "order from earliest to latest", ["random order", "alphabetical order"], "Timelines show when events happened."],
  ["Which happened first?", "Pyramids were built", ["Cars were invented", "Airplanes were invented"], "Pyramids are thousands of years old."],
  ["How do we know about ancient Egypt today?", "From artifacts and writings left behind", ["From a time machine", "From guessing only"], "Archaeologists study things people left behind."],
  ["An artifact is…", "an object made by people long ago", ["a new toy", "a type of weather"], "Artifacts help us learn about the past."],
  ["Communities change over time. Which is an example?", "More cars on roads than long ago", ["The Sun disappears", "Mountains vanish overnight"], "Communities change as people and technologies change."],
  ["Which continues over time in many cultures?", "Traditions and stories", ["Yesterday's weather", "Last week's lunch"], "Many traditions are passed down."],
  ["A tradition that is passed down is an example of…", "continuity", ["something forgotten", "a sudden change"], "Continuity means something stays the same over time.", true],
  ["Why were rulers of ancient Egypt buried in pyramids?", "It was a custom about the afterlife", ["They were bored", "Pyramids were warm in winter"], "Burial customs were important in their beliefs.", true],
  ["Compared with Egypt long ago, which is true today?", "We use machines and electricity", ["We use hieroglyphs for school", "Everyone travels by reed boat"], "Technology has changed a lot.", true],
];

export const ancient = bankUnit({
  id: "mb-ancient-egypt",
  title: "Ancient Egypt",
  emoji: "🏺",
  blurb: "Daily life, customs and lasting ideas of an ancient society beside the Nile.",
  parentNote:
    "Practises daily life, customs, ways of expression and lasting contributions of ancient Egypt as one example of an ancient society, plus how communities and traditions change or continue over time and how timelines help.",
  standards: ["3-KH-021, 3-KH-022, 3-KH-023, 3-KH-024, 3-KH-025, 3-KH-026, 3-VH-007, 3-VH-008, 3-S-202, 3-S-204", "daily life, customs, expression and contributions of an ancient society, and change over time"],
  items: ANCIENT,
});
