import { bankUnit, type Q } from "../own";

// More Grade 4 social studies: the northern territory studied (Nunavut), citizenship and identity, power and
// conflict, government and property, Manitoba places and heritage, and the skills strand (maps, research,
// thinking). Indigenous and francophone content is light, in the present tense, and needs partner review.

const NUNAVUT_LAND: Q[] = [
  ["Nunavut is one of Canada's…", "territories", ["provinces", "oceans"], "Canada has three territories: Yukon, Northwest Territories and Nunavut."],
  ["What is the capital city of Nunavut?", "Iqaluit", ["Yellowknife", "Whitehorse"], "Iqaluit is on Baffin Island."],
  ["Which island is the largest island in Canada and holds Iqaluit?", "Baffin Island", ["Vancouver Island", "Prince Edward Island"], "Baffin Island is in the Arctic."],
  ["Which ocean is north of Nunavut?", "Arctic Ocean", ["Pacific Ocean", "Atlantic Ocean"], "The Arctic Ocean is at the top of the map."],
  ["Which large bay touches both Nunavut and Manitoba?", "Hudson Bay", ["Bay of Fundy", "Georgian Bay"], "Hudson Bay is on the north-east edge of Manitoba."],
  ["Which province shares a border with Nunavut?", "Manitoba", ["Alberta", "Nova Scotia"], "Nunavut touches Manitoba to the south."],
  ["Compared with Manitoba, where is Nunavut?", "north of it", ["south of it", "west of it"], "Use the compass rose."],
  ["Which territory is directly west of Nunavut?", "Northwest Territories", ["Yukon", "Quebec"], "NWT and Nunavut share a border."],
  ["Which region of Canada is most of Nunavut in?", "the Arctic region", ["the Prairie region", "the Atlantic region"], "Cold, treeless land."],
  ["What is the Arctic tundra?", "cold, treeless land with frozen ground below the surface", ["a thick rainforest", "a hot desert"], "Permafrost lies under the surface."],
  ["What is permafrost?", "ground that stays frozen all year", ["a type of tree", "a kind of storm"], "Perma means lasting."],
  ["Which animal lives in Nunavut?", "polar bear", ["koala", "kangaroo"], "Polar bears hunt on sea ice."],
  ["Which animal herds migrate across the tundra in Nunavut?", "caribou", ["camels", "zebras"], "Caribou travel long distances."],
  ["Which is a natural resource found in Nunavut's land?", "minerals such as gold", ["bananas", "cotton"], "Mining is an important industry."],
  ["Which resource from the Arctic waters do people fish and eat?", "Arctic char", ["tuna", "catfish"], "Char is a cold-water fish."],
  ["Nunavut is very large but has a small…", "population", ["map", "coastline"], "Fewer people live there than in many Canadian cities."],
  ["Where do most people in Nunavut live?", "in small communities spread along the coasts", ["in huge cities", "inland in big towns only"], "Population is spread out."],
  ["Most communities in Nunavut are connected to each other by…", "airplanes and boats, not roads", ["a highway system", "railways"], "There are few roads between communities."],
  ["Why is the population of Nunavut spread out?", "The land is huge and the climate is cold", ["There are too many roads", "Cities are crowded"], "Distance and climate matter."],
  ["Winters in Nunavut are…", "long, dark and very cold", ["short and hot", "wet and warm"], "The Arctic has months of darkness in winter."],
  ["In summer in the far north, the Sun may…", "stay up for a long time each day", ["never rise", "turn blue"], "It is called the midnight sun."],
  ["Which Canadian region's name means \"our land\" in Inuktitut?", "Nunavut", ["Yukon", "Manitoba"], "Nunavut means our land."],
  ["About how many people live in Nunavut?", "about 40 000", ["about 4 million", "about 400 million"], "Nunavut has fewer people than any other province or territory.", true],
  ["Which feature is part of Nunavut's land?", "Many islands in the Arctic Ocean", ["Large hardwood forests", "Rainforests"], "Many islands lie in the Arctic Archipelago.", true],
  ["Why can mining be both helpful and challenging in the North?", "It can bring jobs but can change the land", ["It has no effects", "It makes the Arctic warmer overnight"], "Think of benefits and costs.", true],
  ["Which statement about the North's resources is true?", "Fish, wildlife and minerals are important there", ["There are no resources", "Only palm trees grow"], "Many northerners depend on land and sea.", true],
];

const NAMES: Q[] = [
  ["The community of Kugluktuk was once called…", "Coppermine", ["Frobisher Bay", "Churchill"], "Kugluktuk is an Inuinnaqtun name."],
  ["The capital city Iqaluit was once called…", "Frobisher Bay", ["Coppermine", "Rankin Inlet"], "The name changed in 1987."],
  ["Why have many northern places been renamed?", "To use the Inuit names people have long used", ["To confuse visitors", "To make them shorter"], "Names show history and identity."],
  ["What does a place name tell us?", "about the people, language and history of a place", ["nothing", "only the weather"], "Names carry stories."],
  ["Which language are many Nunavut place names from?", "Inuktitut or Inuinnaqtun", ["Latin", "Spanish"], "These are Inuit languages."],
  ["Which of these is an Inuit place name in Nunavut?", "Qikiqtarjuaq", ["Winnipeg", "Brandon"], "Qikiqtarjuaq is a community on Baffin Island."],
  ["What is an inuksuk (plural inuksuit)?", "a stone figure built by Inuit for many purposes", ["a kind of boat", "a kind of dog"], "Inuksuit are built from stones."],
  ["One purpose of an inuksuk is to…", "mark a place where food is stored", ["tell the weather", "hold up a roof"], "Food caches were marked."],
  ["Another purpose of an inuksuk is to…", "show the direction to travel", ["show the time", "change the weather"], "Inuksuit help people find their way."],
  ["An inuksuk can also mark…", "a good hunting or fishing place", ["a school", "a hockey rink"], "Hunting spots."],
  ["An inuksuk can also give…", "a feeling of companionship", ["a ticket", "a map of cities"], "A figure looks like a person standing on the land."],
  ["Inuksuit are important because they…", "help people travel and live on the land", ["are decorations only", "are toys"], "They are a practical tool."],
  ["Which would be a way to find your direction in the Arctic?", "Use an inuksuk, the Sun or stars, or a compass", ["Guess", "Close your eyes"], "Many ways to orient."],
  ["A compass needle points to…", "magnetic north", ["the Moon", "the nearest city"], "Compasses help find direction."],
  ["Which tool uses satellites to show your location?", "GPS", ["a thermometer", "a ruler"], "Global Positioning System."],
  ["At night, which can help you find north in the northern sky?", "the North Star", ["a rainbow", "a lightning bolt"], "The North Star seems nearly still."],
  ["The Sun rises in the…", "east", ["west", "south"], "It sets in the west."],
  ["At noon in Canada, the Sun is mostly in the…", "south", ["north", "east"], "Canada is north of the equator."],
  ["Where does the compass rose on a map point to the top?", "north", ["south", "west"], "N is up on most maps."],
  ["If you walk away from the Sun at noon in Manitoba, you are heading…", "north", ["south", "east"], "Sun is south at noon."],
  ["Why might travellers in a treeless landscape use inuksuit?", "There are few other landmarks", ["There are many trees", "They like stones"], "Landmarks guide the way."],
  ["Traditional knowledge about the land is passed down by…", "family, Elders and experience", ["only online games", "nobody"], "Knowledge is shared across generations."],
  ["Which of these is a landmark you could use to find your way?", "a hill or inuksuk", ["a cloud shape that changes", "a shadow at night"], "Landmarks do not move.", true],
  ["An inuksuk in the landscape most likely means…", "someone built it for a reason", ["it fell there by accident always", "it is rain"], "They are made with purpose.", true],
  ["Why is it important to respect inuksuit?", "They have meaning and purpose for the people who built them", ["They are free to knock over", "They are only rocks"], "Do not knock them down.", true],
];

const NUNAVUT_PEOPLE: Q[] = [
  ["Who are Inuit?", "Indigenous people who live in the Arctic, including Nunavut", ["people from a city in Manitoba", "a kind of animal"], "Inuit have lived in the Arctic for a very long time."],
  ["Which language do many Inuit in Nunavut speak?", "Inuktitut", ["Latin", "Italian"], "Inuktitut is an Inuit language."],
  ["Besides Inuktitut, which Inuit language is spoken in parts of western Nunavut?", "Inuinnaqtun", ["Greek", "Swahili"], "Inuinnaqtun is spoken in places like Kugluktuk."],
  ["Which are official languages in Nunavut?", "Inuktut, English and French", ["only French", "only Latin"], "Inuktut means Inuktitut and Inuinnaqtun."],
  ["Throat singing is a kind of…", "Inuit music made by two singers face to face", ["painting", "hockey"], "It is a traditional art and game."],
  ["Drum dancing is a tradition in which people…", "dance to the beat of a drum", ["paint rocks", "fish in a boat"], "Many Inuit communities perform drum dances today."],
  ["Soapstone carving is a type of…", "visual art", ["music", "weather"], "Artists carve animals and people."],
  ["Which is a well-known community for Inuit printmaking and art?", "Kinngait (Cape Dorset)", ["Winnipeg", "Brandon"], "Kinngait artists are famous."],
  ["What is an Inuit game of skill like the high kick?", "kicking a target held high", ["throwing a snowball", "digging a hole"], "Inuit games test strength and balance."],
  ["Today, many Inuit families in the North enjoy…", "both traditional and modern activities", ["only old ways", "no traditions"], "Cultures change and continue."],
  ["Which clothing material do some Inuit still use for warm parkas?", "caribou or sealskin", ["silk", "paper"], "These materials are very warm."],
  ["Stories and traditions in Nunavut are often shared through…", "storytelling by Elders", ["only video games", "silence"], "Oral tradition."],
  ["Which statement is respectful?", "Inuit have many communities and each has its own character", ["All Inuit are exactly the same", "Inuit live only in the past"], "Do not generalize."],
  ["What does it mean to value the North's contributions to Canada?", "Recognize resources, culture and knowledge shared with all Canadians", ["Ignore the North", "Take without asking"], "The North is part of Canada."],
  ["Which contribution from the North helps all Canadians?", "art, minerals and knowledge of the Arctic", ["Rice farms", "Palm oil"], "Many things come from the North."],
  ["Many northern communities share country food such as…", "Arctic char and caribou", ["pineapple", "olives"], "Country food is food from the land."],
  ["Which of these is an Inuit tradition of making a warm coat for a baby?", "the amauti, a parka with a pouch", ["a swimsuit", "a raincoat"], "The amauti carries a baby."],
  ["Stories told by Elders often teach…", "values and how to live well on the land", ["how to read a thermometer", "how to draw a legend"], "Stories carry teachings."],
  ["How do Elders help communities?", "They share knowledge, language and stories", ["They make rules for games only", "They stop all change"], "Elders are respected teachers."],
  ["What is the best way to learn about a community's culture?", "Listen to people from that community", ["Make a guess", "Use a stereotype"], "Respectful learning."],
  ["The Nunavut flag and symbols include…", "an inuksuk and the North Star", ["a maple leaf", "a tractor"], "Symbols reflect Inuit culture.", true],
  ["Why is it important to keep a language alive?", "Language carries culture, history and identity", ["It makes maps easier", "It is not important"], "Languages hold knowledge.", true],
  ["What are Inuit games like string figures good for?", "Telling stories and building skill", ["Measuring rain", "Marking food"], "Games teach and bring people together.", true],
  ["Why do we say \"Inuit are\" (present) not \"Inuit were\"?", "Inuit communities are living and thriving today", ["Inuit are gone", "Only the past matters"], "Use present tense for living cultures.", true],
  ["Which choice shows respect when you visit a community's art show?", "Ask permission before taking photos", ["Touch every piece", "Take whatever you like"], "Ask first.", true],
];

const NORTH_CHANGE: Q[] = [
  ["What year was Nunavut created as a territory?", "1999", ["1867", "1950"], "April 1, 1999."],
  ["Nunavut was created from part of the…", "Northwest Territories", ["Yukon", "Manitoba"], "The NWT was divided in 1999."],
  ["Which agreement helped create Nunavut?", "a land claim agreement signed by Inuit and the government", ["a hockey treaty", "a school plan"], "Inuit negotiated their land claim."],
  ["One main reason for creating Nunavut was so Inuit could…", "have more say in their own government and lands", ["move south", "close their communities"], "Self-government."],
  ["After the split, the western territory is still called…", "Northwest Territories", ["Southwest Territories", "Nunavut"], "NWT remains."],
  ["What is the capital of the Northwest Territories?", "Yellowknife", ["Iqaluit", "Whitehorse"], "Yellowknife is on Great Slave Lake."],
  ["Who live in the Northwest Territories along with Inuit?", "Dene, Métis and other communities", ["only cities", "only farmers"], "People of many nations."],
  ["Which of these has changed in the North in the last 100 years?", "transportation, with snowmobiles and planes now common", ["The Sun's colour", "The shape of the map"], "Technology has changed travel."],
  ["Which was a traditional way to travel over snow?", "dog team and sled", ["bicycle", "subway"], "Qamutiit are sleds."],
  ["Which modern way to travel over snow do many people use today?", "snowmobile", ["rowboat", "tractor"], "Snowmobiles are widely used."],
  ["How has food changed in the North?", "Stores sell more foods, and many families still enjoy country food", ["No one eats country food anymore", "All food is grown in Arctic gardens"], "Both traditional and store-bought foods."],
  ["How has clothing changed in the North?", "People wear both traditional clothing and modern jackets", ["Only paper clothing", "Only summer clothes"], "Mix of old and new."],
  ["Why is it hard to get fresh food in the North?", "Goods must travel a long way by plane or ship", ["There is no food", "Stores are free"], "Distance raises costs."],
  ["How has education changed?", "Children now learn in community schools, with more Inuit languages taught", ["No one goes to school", "Schools are underground"], "Schools are in communities."],
  ["Which change made it easier to talk to relatives far away?", "telephone and internet", ["sled", "igloo"], "Communication technology."],
  ["How has recreation changed?", "People enjoy hockey, video games and traditional Inuit games", ["Everyone plays only one game", "No games exist"], "Both old and new."],
  ["What does an Inuit land claim recognize?", "Inuit rights to land and a role in decisions", ["Taxes paid by Inuit", "A new language"], "It gave Inuit ownership of some lands."],
  ["How can we describe change in culture?", "Cultures keep traditions and also change", ["Cultures never change", "Cultures disappear"], "Cultures are alive."],
  ["Which is a reason for naming the new territory in an Inuit language?", "It honours the people and place", ["It is shorter", "Nobody uses it"], "Names show identity."],
  ["Why are Inuit languages used in Nunavut's schools and government?", "To keep the languages strong in everyday life", ["Because no one speaks English", "To make maps"], "Languages carry culture."],
  ["Counting how many people live in a place is part of its…", "demographics", ["weather", "legend"], "Demographics are facts about people."],
  ["Which question helps you learn about change over time?", "How was life different 100 years ago?", ["What colour is it?", "Who is tallest?"], "Think about the past."],
  ["Which is a way that climate change affects the North?", "Sea ice melts earlier, which changes travel and hunting", ["The Sun stops rising", "Snow turns purple"], "The Arctic is warming quickly.", true],
  ["When the territory was divided, Inuit in the east wanted…", "their own government that reflected their culture", ["no government", "a ban on languages"], "Self-determination.", true],
  ["Which of these is a good source to learn about northern life today?", "Books and websites written by northerners", ["Rumours", "A joke site"], "Choose reliable voices.", true],
];

const CITIZEN: Q[] = [
  ["What does it mean to be a citizen of Canada?", "To belong to Canada with rights and responsibilities", ["To live far away", "To own a pet"], "Citizens have rights and responsibilities."],
  ["Which is a responsibility of a Canadian citizen?", "Obey the law and respect others", ["Ignore rules", "Ignore neighbours"], "Citizens follow laws."],
  ["Which is a right of a Canadian citizen?", "Freedom to speak and share opinions", ["Taking others' things", "Skipping school forever"], "Freedoms are part of democracy."],
  ["Which describes a good citizen at school?", "Helping keep the classroom tidy and kind", ["Making a mess", "Leaving others out"], "Contribute to your community."],
  ["How can you contribute to your community?", "Volunteer to help a neighbour or clean a park", ["Stay home always", "Litter"], "Giving time helps."],
  ["Why do citizens vote when they're old enough?", "To choose leaders and have a say", ["Because voting is a game", "To get a prize"], "Voting is a way to take part."],
  ["Which is a way a citizen shows pride in Canada?", "Learn about its history and care for its land", ["Ignore it", "Never talk about it"], "Value citizenship."],
  ["Being a Canadian citizen also means respecting…", "people of every culture", ["only your own culture", "no one"], "Canada is diverse."],
  ["What is one meaning of belonging?", "Feeling welcome in a group", ["Being alone", "Being lost"], "Belonging matters."],
  ["Which factor can shape your identity?", "your culture, community, place and region", ["only the weather", "only your age"], "Many things shape identity."],
  ["How does where you live shape who you are?", "Your region, landscape and neighbours are part of your life", ["It has no effect", "Nothing ever changes"], "Place matters."],
  ["How can culture shape identity?", "Through language, food, music, stories and celebrations", ["Through homework only", "Through nothing"], "Culture is lived."],
  ["Many First Nations, Métis and Inuit people are also Canadian citizens. This means they…", "belong to their nation or community and to Canada", ["must give up their culture", "cannot vote"], "Identities can be layered."],
  ["Which statement about identity is true?", "A person can belong to more than one community", ["You can only belong to one group", "Identity never changes"], "People have many belongings."],
  ["Many francophone Manitobans speak French at home and school. Their identity includes…", "French language and heritage", ["no language", "no culture"], "Francophone communities are part of Manitoba."],
  ["Which is a francophone cultural event in Manitoba?", "Festival du Voyageur", ["Stampede", "Carnival of Venice"], "It is held each winter in Saint-Boniface."],
  ["Learning from an Elder about their culture helps you…", "understand identity and respect", ["avoid history", "forget traditions"], "Elders share teachings."],
  ["Which is a respectful thing to do when an Elder speaks?", "Listen quietly and thank them", ["Talk loudly", "Leave early"], "Respectful listening."],
  ["What does it mean to value diversity?", "To see differences as a strength", ["To avoid people who are different", "To pick favourites"], "Diversity enriches communities."],
  ["Which community group helps people in your town?", "a food bank volunteer team", ["a video game", "a pile of leaves"], "Groups help each other."],
  ["Which action is NOT being a good citizen?", "Throwing garbage in a park", ["Planting a tree", "Helping a neighbour"], "Care for shared places."],
  ["What does Canada Day celebrate?", "the birth of Canada as a country on July 1", ["a day of the week", "a hockey game"], "Canada Day is July 1."],
  ["Which sentence shows value for citizenship?", "I will vote when I am an adult and help others now.", ["I won't ever help.", "I don't care."], "Take part.", true],
  ["Why do citizens have both rights and responsibilities?", "So that everyone can live safely and fairly together", ["Because rules are random", "To make life harder"], "Rights need responsibilities.", true],
  ["Which choice makes a classroom a good community?", "Each person helps and listens", ["Only the teacher does everything", "No one cooperates"], "Everyone contributes.", true],
  ["A newcomer joins your class. What shows welcome?", "Invite them to play and share", ["Ignore them", "Laugh at their accent"], "Welcome builds belonging.", true],
];

const POWER: Q[] = [
  ["Which is an example of authority at school?", "A teacher making a classroom rule", ["A friend giving a joke", "A bird landing"], "Authority is the right to make decisions."],
  ["Which is an example of authority in a town?", "A mayor or council making a bylaw", ["A stranger", "A pet"], "Local governments set rules."],
  ["Which is a rule that helps keep people safe?", "Stop at a red light", ["Jump at a red light", "Run across a road"], "Rules keep us safe."],
  ["What is a law?", "a rule made by a government that everyone must follow", ["a game", "a kind of food"], "Laws are made by governments."],
  ["What is a student council?", "a group of students elected to help make decisions", ["a type of lunch", "a school bus"], "It is a formal group."],
  ["Which is an informal kind of power?", "A friend who everyone follows on the playground", ["The mayor", "A judge"], "Informal power is not given by rules."],
  ["Which is a formal kind of power?", "A principal", ["A popular kid", "A neighbour's dog"], "Formal authority is official."],
  ["Which is a misuse of power?", "A group of kids making others give them snacks", ["Taking turns", "Sharing"], "Bullying uses power unfairly."],
  ["What should you do if someone is bullying you?", "Tell a trusted adult", ["Keep it secret", "Bully back"], "Adults can help."],
  ["Which is a peaceful way to deal with conflict?", "Talk calmly and listen to each other", ["Yell", "Hit"], "Peaceful solutions."],
  ["Two friends want the same ball. What is a fair solution?", "Take turns", ["Fight over it", "Hide it"], "Fair, peaceful."],
  ["Which helps solve a conflict?", "Using \"I feel\" statements", ["Name-calling", "Blaming"], "\"I feel upset when...\" helps."],
  ["What is a conflict manager?", "a student trained to help classmates solve problems peacefully", ["a game", "a gym teacher only"], "Peer helpers exist at many schools."],
  ["A patrol student has authority to help traffic safety. They should use it…", "with respect for others", ["to boss friends", "to take things"], "Respect the rights of others."],
  ["Which is a way to reach a group decision?", "Everyone shares ideas and the group agrees on a plan", ["One person decides without listening", "No one speaks"], "Consensus means group agreement."],
  ["What does it mean to negotiate?", "Talk it over to reach an agreement", ["Run away", "Shout louder"], "Compromise."],
  ["Your group disagrees. Which phrase helps build consensus?", "What if we try both ideas?", ["My way only", "Forget it"], "Look for a plan everyone can accept."],
  ["Which shows fairness?", "Everyone gets a turn", ["Only favourites get turns", "Rules change for some"], "Treat everyone fairly."],
  ["Which statement is respectful?", "I may disagree, but I will listen.", ["You are silly.", "I won't listen."], "Respect differences."],
  ["Why do groups assign roles such as timekeeper and recorder?", "So the work is shared fairly", ["To confuse everyone", "To avoid work"], "Shared responsibility."],
  ["When a rule seems unfair, a peaceful action is to…", "talk to the teacher or council about it", ["break the rule secretly", "make a fuss"], "Use fair ways to change rules."],
  ["Which is a result of a gang using power unfairly?", "Fear and hurt in a community", ["Safer streets", "More friendship"], "Misuse of power harms people."],
  ["Which choice would build trust among teammates?", "Do your part and encourage others", ["Blame others", "Give up"], "Trust grows from fairness.", true],
  ["After a disagreement, which step helps repair a friendship?", "Say sorry and listen", ["Say nothing and walk away", "Spread rumours"], "Repair with kindness.", true],
  ["Why do societies have laws as well as classroom rules?", "To keep people safe and treat them fairly", ["To stop fun", "To be bossy"], "Laws protect everyone.", true],
];

const GOV: Q[] = [
  ["Which is private property?", "a family's home", ["a public park", "a city street"], "Private property is owned by a person or group."],
  ["Which is public property?", "a public library", ["a family's backyard", "a friend's bike"], "Public property belongs to everyone."],
  ["Which is public property?", "a city park", ["your lunch", "your backpack"], "Everyone can use it."],
  ["Which is private property?", "your own bike", ["a city bus", "a public school"], "It belongs to you."],
  ["Why should we respect public property?", "It belongs to everyone and costs money to fix", ["It belongs to no one", "It is free to break"], "Everyone shares it."],
  ["What should you do before borrowing a classmate's pencil?", "Ask permission", ["Take it", "Hide it"], "Respect private property."],
  ["You find a lost mitten at a playground. What is a respectful action?", "Hand it to a staff person or post it on the lost and found", ["Keep it", "Throw it away"], "It belongs to someone."],
  ["Which service does a government provide?", "public schools", ["video games", "pizza delivery"], "Governments provide education."],
  ["Which service does a government help provide?", "health care", ["toys", "birthday parties"], "Hospitals and clinics."],
  ["Which service does a city provide?", "garbage pickup and clean water", ["movie tickets", "snacks"], "Sanitation."],
  ["Who plows snow from public roads in a city?", "city workers", ["a magician", "a team of birds"], "Governments maintain roads."],
  ["Which government worker helps keep people safe?", "firefighter or police officer", ["a clown only", "a bird"], "Emergency services."],
  ["Which is a way that governments pay for services?", "through taxes", ["through pizza", "through toys"], "People pay taxes."],
  ["What do libraries give people?", "free access to books and information", ["free cars", "free houses"], "Libraries are public."],
  ["How are many First Nations chiefs and councillors chosen?", "by elections in their community", ["by a coin flip", "by a school vote"], "Many First Nations elect their leaders."],
  ["In Manitoba, there are elected representatives of the Métis. Which group does so?", "Manitoba Métis Federation", ["the Winnipeg Jets", "a bakery"], "The MMF represents Métis in Manitoba."],
  ["Which statement is true?", "First Nations, Métis and Inuit people elect leaders in their communities", ["No Indigenous leaders exist", "Leaders are chosen by a coin flip"], "Indigenous governments are active today."],
  ["What does it mean to \"elect\" someone?", "to choose them by voting", ["to take their house", "to hide them"], "Elections choose leaders."],
  ["Which is an example of media?", "a TV news show", ["a rock", "a shoe"], "Media tells us about the world."],
  ["Which is an example of media?", "a website", ["a bicycle", "a mitten"], "Websites are media."],
  ["How can advertisements shape what we think?", "They show things in a way that makes us want a product", ["They always tell the whole truth", "They never use pictures"], "Ads persuade."],
  ["A news story shows only one kind of place in Canada. What might happen?", "People may form an incomplete idea of that place", ["Everyone is fully informed", "Nothing at all"], "Media influence perceptions."],
  ["If a TV show only shows cities when talking about Canada, you might forget about…", "farms, small towns and the North", ["the Sun", "water"], "Canada is diverse.", true],
  ["Why should we check more than one source of news?", "Different sources can show different parts of the story", ["It makes news longer", "All sources are the same"], "Compare sources.", true],
  ["Which action shows respect for public property?", "Put your litter in a bin", ["Draw on a bench", "Break a swing"], "Look after shared things.", true],
];

const PLACES: Q[] = [
  ["Where is The Forks?", "Where the Red and Assiniboine rivers meet in Winnipeg", ["On the Arctic coast", "In Brandon"], "People have met there for thousands of years."],
  ["Lower Fort Garry is a historic site that was once a…", "Hudson's Bay Company fur trade post", ["subway station", "airport"], "It's near Selkirk."],
  ["Where is the Musée de Saint-Boniface?", "in Winnipeg's Saint-Boniface neighbourhood", ["in Churchill", "in Flin Flon"], "It tells the story of francophone and Métis history."],
  ["What is Thunderbird House?", "a gathering place in Winnipeg for Indigenous cultural activities", ["a hockey rink", "a zoo"], "It is on Main Street."],
  ["Which Manitoba national park is home to bison and elk?", "Riding Mountain National Park", ["Banff", "Gros Morne"], "It's on the Manitoba Escarpment."],
  ["Near Churchill, Wapusk National Park protects…", "polar bear dens", ["palm trees", "volcanoes"], "Bears den near Hudson Bay."],
  ["Which Manitoba provincial park has sand dunes called Spirit Sands?", "Spruce Woods", ["Whiteshell", "Hecla"], "Near Carberry."],
  ["Which Manitoba provincial park has many lakes and Canadian Shield rock?", "Whiteshell", ["Spruce Woods", "Birds Hill"], "In eastern Manitoba."],
  ["Which Manitoba place is a UNESCO World Heritage Site in the boreal forest?", "Pimachiowin Aki", ["Lower Fort Garry only", "The Forks Market"], "It's cared for by Anishinaabe communities."],
  ["What is a national park?", "land protected by the Government of Canada for nature and history", ["a shopping mall", "a school"], "Parks protect special places."],
  ["What is a provincial park?", "land protected by a province for nature and recreation", ["a parking lot", "a hospital"], "Run by the province."],
  ["Why do we protect special places?", "So future generations can enjoy and learn from them", ["To keep them locked", "To forget them"], "Conservation."],
  ["Which museum is at The Forks?", "Canadian Museum for Human Rights", ["Hockey Hall of Fame", "Royal Ontario Museum"], "It is in Winnipeg."],
  ["Which Manitoba town is famous for polar bears?", "Churchill", ["Brandon", "Dauphin"], "On Hudson Bay."],
  ["Which waterway flows through Winnipeg?", "Red River", ["St. Lawrence River", "Fraser River"], "The Red flows north to Lake Winnipeg."],
  ["Oak Hammock Marsh is important for…", "birds and wetland animals", ["skyscrapers", "ski hills"], "Wetlands protect wildlife."],
  ["Which describes many First Nations, Métis and Inuit peoples' relationship with the land?", "It is a close relationship of care and respect", ["They have no connection to land", "They only visit on weekends"], "Land is part of life and culture."],
  ["How can people care for Manitoba's natural environment?", "Reduce waste and respect wildlife", ["Dump trash", "Pick every flower"], "Stewardship."],
  ["Which choice shows respect for the natural environment when camping?", "Pack out your garbage", ["Leave fire burning", "Chase animals"], "Leave no trace."],
  ["Many Manitobans respect land, water and sky because…", "they are needed by all living things", ["they are boring", "they are gifts of a store"], "Respect the environment."],
  ["Which place shows both nature and history?", "Lower Fort Garry National Historic Site", ["a parking lot", "an empty room"], "It has old buildings and open grounds."],
  ["Which of these is a cultural place?", "a museum or arts centre", ["a pond", "a cloud"], "Cultural places share art and history."],
  ["What should you do when visiting a historic site?", "Follow the rules and treat it gently", ["Climb on old walls", "Take souvenirs from buildings"], "Respect heritage.", true],
  ["Why might a class pick a project to reduce energy use at school?", "To make a decision that reflects care for the environment", ["To get a prize only", "To make noise"], "Caring decisions.", true],
  ["Which would a Manitoba visitor most likely see at Riding Mountain?", "forest, lakes and wildlife", ["coral reefs", "volcanoes"], "It's in the boreal and prairie mix.", true],
  ["Why might a place be significant to a community?", "It holds history, culture or natural beauty", ["It has a number", "It is far away"], "Significance means importance.", true],
];

const HERITAGE: Q[] = [
  ["Which language group is Winnipeg's name from (meaning \"muddy water\")?", "Cree", ["Latin", "Greek"], "Many Manitoba place names come from Indigenous languages."],
  ["The Assiniboine River's name comes from a word in which language?", "an Indigenous language", ["Spanish", "Dutch"], "Many places have Indigenous names."],
  ["The Red River jig is a lively dance connected to the…", "Métis", ["Vikings", "Romans"], "Fiddles and quick footwork."],
  ["The Métis sash is a…", "woven belt that is part of Métis culture", ["hat", "kind of boat"], "Also called ceinture fléchée."],
  ["What is the symbol on the Métis flag?", "an infinity sign", ["a maple leaf", "a moose"], "It shows the Métis people live on forever."],
  ["What language is sometimes spoken by Métis people in Manitoba?", "Michif", ["Latin", "Swahili"], "Michif blends French and Cree."],
  ["What is a powwow?", "a gathering with dancing, drumming and celebration", ["a kind of boat", "a type of map"], "Many First Nations communities hold powwows."],
  ["Which group represents many First Nations in Manitoba?", "Assembly of Manitoba Chiefs", ["a bakery", "a school"], "It brings chiefs together."],
  ["Which of these is a First Nations language spoken in Manitoba?", "Cree", ["French only", "Greek"], "Others include Ojibwe, Dakota and Dene."],
  ["Many First Nations, Métis and Inuit communities in Manitoba are connected by…", "family ties, trade, languages and shared history", ["nothing", "a bridge only"], "Communities are connected."],
  ["Which festival celebrates francophone and fur trade history each February in Saint-Boniface?", "Festival du Voyageur", ["Folklorama", "Fringe Festival"], "Voyageurs paddled canoes with furs."],
  ["Le Cercle Molière is…", "a French-language theatre company in Saint-Boniface", ["a dessert", "a sport"], "It is the oldest continuously operating theatre company in Canada."],
  ["La Liberté is…", "a French-language newspaper in Manitoba", ["a bus", "a kind of soup"], "It's published in Saint-Boniface."],
  ["The Université de Saint-Boniface teaches in…", "French", ["Latin only", "Greek"], "It is a French-language university in Winnipeg."],
  ["Which towns have French names in Manitoba?", "Saint-Pierre-Jolys and Notre-Dame-de-Lourdes", ["Banff and Jasper", "Halifax and Yarmouth"], "French place names show settlement."],
  ["What is a voyageur?", "a canoe traveller in the fur trade", ["a train driver", "an astronaut"], "They paddled with furs and goods."],
  ["Why did francophone settlers come to Manitoba?", "to farm, trade and build communities", ["to avoid the weather", "to take the lake"], "Many families settled in places like Saint-Boniface."],
  ["Louis Riel is remembered as…", "a Métis leader who helped bring Manitoba into Canada in 1870", ["a hockey star", "an astronaut"], "Louis Riel Day is in February."],
  ["Which statement about European settlement is true?", "It brought disease and changes that harmed many First Nations, Métis and Inuit communities", ["It changed nothing", "It helped everyone equally"], "Settlement brought displacement and cultural change."],
  ["Which result came from newcomers bringing new diseases?", "Many Indigenous communities lost many people", ["Everyone became healthier", "The weather changed"], "Diseases spread quickly in the past."],
  ["Why is oral tradition valuable?", "Stories pass down history and teachings", ["It is a fairy tale", "It is useless"], "Many communities learn history through stories."],
  ["Why can learning Manitoba's history matter in your life?", "It helps you understand your community and neighbours", ["It does not matter", "It is just dates"], "History shapes the present."],
  ["Which place name in Manitoba comes from an Indigenous language?", "Winnipeg", ["Brandon", "Selkirk"], "Brandon and Selkirk have European names.", true],
  ["Which is an artistic achievement of Manitobans?", "a ballet company like the Royal Winnipeg Ballet", ["a car race", "a hockey stick"], "Winnipeg has a world-famous ballet.", true],
  ["How can you show respect for different cultures in Manitoba?", "Learn about them and join events with respect", ["Say stereotypes", "Laugh at costumes"], "Respect leads to understanding.", true],
];

const MAPSKILLS: Q[] = [
  ["What does a map title tell you?", "what the map shows", ["who drew it", "the weather"], "Titles name the map."],
  ["What does a map legend (key) explain?", "what the symbols mean", ["where the Sun is", "who owns the map"], "Symbols need a key."],
  ["What does a compass rose show?", "directions", ["distance only", "time"], "N, S, E and W."],
  ["On a map, north is usually…", "at the top", ["at the bottom", "at the left"], "North is up."],
  ["What does a grid on a map help you do?", "find places using letters and numbers", ["tell time", "measure weight"], "A grid uses coordinates."],
  ["A town is at B-3 on a map grid. What is B-3?", "the grid square where you look", ["the town's size", "a river"], "Letter and number locate it."],
  ["On a map, a blue area usually shows…", "water", ["forest", "desert"], "Blue is for water."],
  ["On a map, a star in a circle could mean…", "a capital city", ["a lake", "a mountain"], "Check the legend."],
  ["Which direction is opposite north?", "south", ["east", "west"], "N and S are opposites."],
  ["Which direction is between north and east?", "northeast", ["southwest", "northwest"], "NE."],
  ["Which direction is between south and west?", "southwest", ["northeast", "southeast"], "SW."],
  ["If you travel from Winnipeg to Thompson, you go mostly…", "north", ["south", "west"], "Thompson is north of Winnipeg."],
  ["If you travel from Winnipeg to Brandon, you go mostly…", "west", ["east", "north"], "Brandon is west of Winnipeg."],
  ["If you travel from Winnipeg to Emerson (on the U.S. border), you go mostly…", "south", ["north", "west"], "Emerson is south of Winnipeg."],
  ["Which would help you draw a map of your classroom?", "a title, legend, compass rose and grid", ["only a name", "only colours"], "Maps need these parts."],
  ["Which map part tells you the symbol for a school?", "legend", ["title", "compass rose"], "A legend explains symbols."],
  ["Which map part tells you how to find north?", "compass rose", ["title", "legend"], "It shows directions."],
  ["A map's scale helps you figure out…", "real distances", ["colours", "language"], "Scale links map and real size."],
  ["Which is the best map to find a route across town?", "a street map", ["a map of Canada", "a world map"], "A larger scale shows streets."],
  ["Which map shows all of Canada's provinces and territories?", "a political map of Canada", ["a street map", "a classroom floor plan"], "Political maps show boundaries."],
  ["Which tool tells your location from satellites?", "GPS", ["ruler", "thermometer"], "Global Positioning System."],
  ["If a map has no title, you may not know…", "what it is about", ["the colour of the paper", "the size of the page"], "Titles name the subject."],
  ["On a map's grid, you read…", "the letter first and the number second (such as C-4)", ["only colours", "only a drawing"], "Follow the grid rule on the map.", true],
  ["A hiker with no phone should orient themselves by observing…", "landmarks such as hills and rivers", ["TV shows", "shop windows"], "Landscape clues.", true],
  ["How can the Sun and stars help you find your way?", "They rise and set in predictable directions", ["They make noise", "They change daily at random"], "Use the Sun's path or the North Star.", true],
];

const RESEARCH: Q[] = [
  ["Which source could you use for a report on Manitoba?", "an atlas, a book or a trusted website", ["a rumour", "a joke"], "Choose reliable sources."],
  ["Which is a print source?", "an encyclopedia", ["a podcast", "a video"], "Print sources are on paper."],
  ["Which is an electronic source?", "a website", ["a paper atlas", "a library card"], "Electronic sources are online."],
  ["Which is a visual source?", "a photograph", ["a paragraph only", "a poem"], "Visual sources show images."],
  ["A good research question starts with words such as…", "how, why or what", ["pop, bang or fizz", "up, down or sideways"], "Open questions explore."],
  ["Which is a good research question?", "How did the fur trade shape Manitoba?", ["Yes?", "Manitoba."], "Real questions need research."],
  ["Which sentence is a fact?", "Winnipeg is the capital of Manitoba.", ["Winnipeg is the best city.", "Winnipeg is boring."], "Facts can be checked."],
  ["Which sentence is an opinion?", "Winter is the best season.", ["Winter has snow in Manitoba.", "Winter follows fall."], "Opinions are beliefs."],
  ["Which is a fact?", "Lake Winnipeg is a large lake in Manitoba.", ["Lake Winnipeg is the prettiest.", "Everyone likes Lake Winnipeg."], "A fact is checkable."],
  ["Which words often signal an opinion?", "best, worst and prettiest", ["measure and count", "metre and litre"], "Opinion words judge."],
  ["A decade is…", "10 years", ["100 years", "1 year"], "Dec- means ten."],
  ["A century is…", "100 years", ["10 years", "1000 years"], "Cent- means hundred."],
  ["A generation is about…", "the time from parents to children, around 25 years", ["one day", "one month"], "Families have generations."],
  ["Which phrase tells of a long time ago in family history?", "in the time of our ancestors", ["last night", "this morning"], "Ancestors are those who came before."],
  ["A timeline is used to…", "show events in order", ["measure rain", "draw a map"], "Sequence in time."],
  ["On a timeline, which event comes first?", "1670 (Hudson's Bay Company founded)", ["1870 (Manitoba joins Canada)", "1999 (Nunavut created)"], "Earlier years come first."],
  ["Which year is later: 1812 or 1870?", "1870", ["1812", "They are the same"], "Bigger year = later."],
  ["To organize information, you could use…", "a chart or concept map", ["a rock", "a cloud"], "Organizers sort ideas."],
  ["What should you record when you use a source?", "its title, author and where you found it", ["nothing", "only the colour of the book"], "Reference your sources."],
  ["When you evaluate your assumptions, you…", "check whether you were right after learning more", ["never change your mind", "ignore new facts"], "Be open-minded."],
  ["Which is an advantage of walking to school?", "It's healthy and good for the environment", ["It takes the whole day", "It costs a lot"], "Weigh good and bad sides."],
  ["Which is a disadvantage of walking to school in winter?", "It can be cold", ["It is quiet", "It saves money"], "Plan for conditions."],
  ["You see a photograph of an old tool. What can you learn?", "How people lived and worked", ["Nothing", "Who wins a race"], "Artifacts and photos are evidence."],
  ["After reading three sources that agree, you can…", "draw a conclusion supported by evidence", ["ignore them", "guess"], "Conclusions need evidence.", true],
  ["Which statement is respectful of human diversity?", "People live in many kinds of homes and families.", ["All families are the same.", "Some people don't matter."], "Use inclusive language.", true],
  ["To support your idea in a group, you should…", "give a reason or example", ["shout", "say nothing"], "Support opinions with information.", true],
  ["Which is a good tool for sharing your research with the class?", "a poster or slide show", ["a blank paper", "a locked box"], "Choose a clear format.", true],
];

export const units = [
  bankUnit({
    id: "mb-north-land",
    title: "The North: Land & Resources",
    emoji: "🧊",
    blurb: "Nunavut's islands, tundra, animals and resources",
    parentNote: "Practises where Nunavut is, its physical features, resources, climate and how few people live there across a very large land.",
    standards: ["4-KL-028, 4-KL-029, 4-KL-030", "locating and describing the physical features, natural resources and population of Nunavut"],
    items: NUNAVUT_LAND,
  }),
  bankUnit({
    id: "mb-north-names",
    title: "Northern Names & Inuksuit",
    emoji: "🪨",
    blurb: "Place names, inuksuit and finding your way",
    parentNote: "Practises why northern place names have changed back to Inuit names, what inuksuit are used for, and ways of finding direction (landmarks, sun, stars, compass, GPS).",
    standards: ["4-KL-031, 4-KL-032, 4-S-208", "changes to place names, the purposes of inuksuit and ways to orient yourself"],
    items: NAMES,
  }),
  bankUnit({
    id: "mb-north-people",
    title: "People of the North",
    emoji: "🥁",
    blurb: "Inuit languages, art, music and stories today",
    parentNote: "A light introduction to Inuit languages, arts, games and stories in Nunavut today, and to the idea that Inuit cultures are living and continue to change. It needs partner review.",
    standards: ["4-KI-013, 4-KI-014, 4-KH-036, 4-VL-007", "Indigenous contributions, languages and communities, stories and traditions of Nunavut, and the North's place in Canada"],
    items: NUNAVUT_PEOPLE,
  }),
  bankUnit({
    id: "mb-north-change",
    title: "A New Territory, A Changing North",
    emoji: "🛷",
    blurb: "How Nunavut began and how northern life has changed",
    parentNote: "Practises why Nunavut and the new Northwest Territories were created in 1999 and how food, clothing, travel, schools and recreation have changed in the last century.",
    standards: ["4-KH-037, 4-KH-038", "the reasons for creating Nunavut and the new Northwest Territories, and changes in ways of life in the last century"],
    items: NORTH_CHANGE,
  }),
  bankUnit({
    id: "mb-citizen-identity",
    title: "Citizens & Identity",
    emoji: "🍁",
    blurb: "Belonging, rights, responsibilities and who we are",
    parentNote: "Practises what being a Canadian citizen means, contributing to a community, and how culture, community, place and region (including First Nations, Métis, Inuit and francophone identities) shape identity.",
    standards: ["4-KC-004, 4-KC-004A, 4-KC-004F, 4-KI-009, 4-KI-009A, 4-KI-009F, 4-VC-001, 4-VC-002", "what citizenship means, belonging, contributing to groups and communities, and the factors that shape identity"],
    items: CITIZEN,
  }),
  bankUnit({
    id: "mb-power-conflict",
    title: "Power, Rules & Peaceful Solutions",
    emoji: "🕊️",
    blurb: "Authority, fairness and settling conflict kindly",
    parentNote: "Practises formal and informal power and authority in children's lives, using authority respectfully, solving conflict peacefully and reaching group decisions.",
    standards: ["4-KP-045, 4-KP-046, 4-VP-011, 4-S-100, 4-S-101, 4-S-102, 4-S-104", "power and authority, positive ways to handle conflict, respecting others' rights, and working together fairly"],
    items: POWER,
  }),
  bankUnit({
    id: "mb-government-property",
    title: "Government, Property & Media",
    emoji: "🏛️",
    blurb: "Public and private property, services and media",
    parentNote: "Practises public and private property, the services governments provide, elected First Nations, Métis and Inuit representatives, and how media shape what we think about people and places.",
    standards: ["4-KP-044, 4-KP-044A, 4-KE-047, 4-KE-048, 4-KE-049, 4-VE-012", "elected Indigenous representatives, public and private property, services governments provide, and media influences"],
    items: GOV,
  }),
  bankUnit({
    id: "mb-special-places",
    title: "Special Places in Manitoba",
    emoji: "🏞️",
    blurb: "Parks, historic sites and caring for the land",
    parentNote: "Practises Manitoba's places of historic, cultural or environmental importance, such as The Forks, Lower Fort Garry, Riding Mountain and Wapusk, and respect for the land, water and sky.",
    standards: ["4-KL-024, 4-KL-025, 4-VL-006, 4-VL-006A, 4-S-103", "special places in Manitoba, relationships with the land, and care for the natural environment"],
    items: PLACES,
  }),
  bankUnit({
    id: "mb-heritage",
    title: "Manitoba's Heritage",
    emoji: "🎻",
    blurb: "Métis, First Nations and francophone contributions",
    parentNote: "Practises contributions of First Nations, Métis and francophone Manitobans to the province's culture, place names and history, the effects of European settlement, and why oral tradition matters. It needs partner review.",
    standards: ["4-KI-006A, 4-KI-006F, 4-KI-007A, 4-KI-008F, 4-KI-011, 4-KI-011A, 4-KI-012, 4-KI-012F, 4-KH-034, 4-VH-008, 4-VH-009, 4-VI-003, 4-VI-004", "Indigenous and francophone achievements and contributions, the impact of European settlement, and valuing oral tradition and diversity"],
    items: HERITAGE,
  }),
  bankUnit({
    id: "mb-map-skills",
    title: "Map Skills",
    emoji: "🧭",
    blurb: "Titles, legends, compass roses and grids",
    parentNote: "Practises reading and building maps with a title, legend, compass rose and grid, and finding direction by landmarks, the Sun and stars, compass or GPS.",
    standards: ["4-S-205, 4-S-206", "constructing and interpreting maps with a title, legend, compass rose and grid"],
    items: MAPSKILLS,
  }),
  bankUnit({
    id: "mb-research-skills",
    title: "Research & Thinking Skills",
    emoji: "🔎",
    blurb: "Sources, facts and opinions, timelines and conclusions",
    parentNote: "Practises choosing sources, asking research questions, telling fact from opinion, measuring time (decade, century, generation), timelines, weighing solutions and drawing conclusions from evidence.",
    standards: ["4-S-200, 4-S-201, 4-S-202, 4-S-203, 4-S-204, 4-S-300, 4-S-301, 4-S-302, 4-S-303, 4-S-304, 4-S-305, 4-S-402", "finding and organizing information, time words and timelines, asking questions, fact and opinion, and drawing conclusions"],
    items: RESEARCH,
  }),
];
