import { bankUnit, type Q } from "../own";

// More Grade 4 science: adaptations and living things, energy transfer and the senses, scientific skills
// and thinking, engineering and technology, and Indigenous ways of knowing (light touch, present tense).

const ADAPT: Q[] = [
  ["What is a habitat?", "the place where a plant or animal lives and finds what it needs", ["a kind of food", "a type of weather"], "A habitat has food, water, shelter and space."],
  ["What is an adaptation?", "a feature or behaviour that helps a living thing survive", ["a kind of habitat", "a type of rock"], "Adaptations help survival."],
  ["Why does an Arctic hare have thick white fur in winter?", "It keeps warm and blends in with snow", ["It helps it fly", "It helps it swim"], "White fur is camouflage in snow."],
  ["What is camouflage?", "colours or patterns that help an animal blend in", ["a loud sound", "a kind of nest"], "Hidden animals are safer."],
  ["A fawn has white spots on a brown coat. How do they help?", "They blend in with sunlight and shadows on the forest floor", ["They make the fawn glow", "They help it swim"], "Spots look like dappled light."],
  ["Why do polar bears have a thick layer of fat?", "It keeps them warm in cold water and air", ["It helps them climb trees", "It helps them fly"], "Fat insulates."],
  ["Which adaptation helps a cactus survive in the desert?", "It stores water in its thick stem", ["It has big thin leaves", "It grows in water"], "Deserts are dry."],
  ["Which adaptation helps a duck swim?", "webbed feet", ["long claws", "thick fur"], "Webbed feet push water."],
  ["Which adaptation helps an eagle catch prey?", "sharp talons and strong eyesight", ["webbed feet", "thick fur"], "Hunters need sharp tools."],
  ["Why do many birds fly south in autumn?", "to find food and warmer weather", ["to find snow", "to sleep under water"], "Migration is a survival behaviour."],
  ["What is hibernation?", "a deep sleep that helps an animal survive winter", ["a kind of migration", "a way of swimming"], "Bears and some ground squirrels hibernate."],
  ["Which is a behaviour adaptation?", "A beaver slapping its tail to warn others", ["A fish having gills", "A rabbit having long ears"], "Behaviours are things animals do."],
  ["Which is a body-part adaptation?", "A rabbit's long ears", ["A bird migrating", "A bear hibernating"], "Body parts are physical features."],
  ["Why do pine trees have needles instead of wide leaves?", "Needles lose less water and shed snow", ["Needles are softer", "Needles make fruit"], "Needles help in cold, dry winters."],
  ["Which animal's colouring helps it hide on a tree trunk?", "a brown moth", ["a bright red cardinal", "a pink flamingo"], "Match the background."],
  ["Which animal has fur that changes colour with the seasons?", "snowshoe hare", ["robin", "frog"], "It's brown in summer and white in winter."],
  ["Plants need soil nutrients, water and sunlight. What do plants take from soil?", "water and nutrients", ["sound", "wind"], "Roots take up water and minerals."],
  ["How do bees help plants?", "They carry pollen from flower to flower", ["They eat the roots", "They give the plants water"], "This is pollination."],
  ["What is pollination?", "moving pollen so a plant can make seeds", ["making honey", "cutting flowers"], "Bees, wind and birds can pollinate."],
  ["How does a burr help a plant spread its seeds?", "It sticks to animal fur and travels", ["It floats on air", "It digs underground"], "Seed dispersal means seeds move."],
  ["How do maple seeds travel?", "They spin like helicopters on the wind", ["They swim", "They are carried by ants only"], "Wind seed dispersal."],
  ["How do some animals help plants spread seeds?", "By eating fruit and dropping seeds elsewhere", ["By planting trees on purpose", "By drinking the soil"], "Seeds pass through animals."],
  ["Humans rely on plants for…", "food and oxygen", ["only noise", "only metal"], "Plants make oxygen and food."],
  ["Why does a squirrel bury nuts?", "to store food for later", ["to hide them from the sun", "to plant a house"], "Caching food.", true],
  ["Why is a fish's streamlined body useful?", "It moves easily through water", ["It stays dry", "It helps it climb"], "Streamlined means smooth.", true],
  ["If a pond dries up, what will happen to the animals that live there?", "They must move or may not survive", ["Nothing", "They grow wings"], "Habitat loss harms animals.", true],
  ["Why do animals and plants depend on one another?", "Each provides things the other needs", ["Plants do not need anything", "Only animals need things"], "Living things are connected.", true],
  ["Which is the best habitat for a polar bear?", "sea ice in the Arctic", ["a hot desert", "a warm rainforest"], "Adaptations fit habitats.", true],
];

const ENERGY_SENSES: Q[] = [
  ["What is energy?", "something that can make things move or change", ["a kind of rock", "a kind of animal"], "Energy causes action."],
  ["What is the main source of energy for Earth's living things?", "the Sun", ["the Moon", "the wind"], "Plants use sunlight to make food."],
  ["Which of these is a source of energy?", "the Sun", ["a pillow", "a book"], "Sources provide energy."],
  ["When you eat a meal, you get energy from…", "food", ["water only", "air only"], "Food is fuel for bodies."],
  ["A car moves when its engine uses…", "fuel", ["paper", "grass"], "Fuel is stored energy."],
  ["When you plug in a lamp, what does the electricity do?", "It gives energy for light", ["It makes the room cold", "It stays in the plug"], "Electricity transfers energy to the bulb."],
  ["When the Sun warms a puddle, energy goes from…", "the Sun to the water", ["the water to the Sun", "the puddle to the sky only"], "Energy transfers from a source to an object."],
  ["A toaster uses energy to make bread…", "hot", ["cold", "wet"], "Electrical energy turns into heat."],
  ["A battery gives a toy car energy to…", "move", ["freeze", "grow"], "Stored energy makes things go."],
  ["A fan uses electricity to…", "move air", ["make cheese", "grow plants"], "Electrical energy moves the blades."],
  ["A phone charger moves energy from the outlet to…", "the phone's battery", ["your hand", "the lamp"], "Charging stores energy."],
  ["Rubbing your hands together makes them warm. Energy of motion turns into…", "heat", ["sound only", "plants"], "Friction makes heat."],
  ["Which sense do you use to detect heat from a campfire?", "touch", ["hearing", "taste"], "You feel warmth on your skin."],
  ["Which sense detects light?", "sight", ["smell", "touch"], "Eyes detect light."],
  ["Which sense detects sound?", "hearing", ["sight", "taste"], "Ears detect sound."],
  ["Which sense helps you notice smoke from a fire?", "smell", ["hearing only", "taste only"], "Smoke has a scent."],
  ["Why is it dangerous to touch a hot stove?", "It is giving off a lot of heat energy", ["It makes noise", "It smells bad"], "Heat can burn skin."],
  ["A smoke alarm uses which energy to alert you?", "sound", ["taste", "touch only"], "It beeps loudly."],
  ["A flashlight shows light energy from…", "the battery", ["the Moon", "the soil"], "The battery powers the bulb."],
  ["Which sentence is true?", "Energy can move from one place to another", ["Energy cannot move", "Energy is always a solid"], "Energy transfers."],
  ["A rolling ball hits a pin and moves it. Energy goes from…", "the ball to the pin", ["the pin to the ball", "nowhere"], "Motion transfers energy."],
  ["A solar panel collects energy from…", "sunlight", ["wind only", "sound only"], "Sunlight becomes electricity."],
  ["A microphone detects which energy?", "sound", ["heat", "smell"], "Sound waves are energy."],
  ["Wind turbines use energy of the…", "moving air", ["Moon", "soil"], "Wind spins the blades.", true],
  ["A campfire gives off which two kinds of energy you can sense?", "heat and light", ["sound and soil", "wind and ice"], "You feel warmth and see flames.", true],
  ["Why do we wear hearing protection near very loud machines?", "Strong sound energy can hurt ears", ["It makes the machine quiet", "It helps us see"], "Loud sounds can damage hearing.", true],
  ["A thermometer helps us detect…", "heat (temperature)", ["sound", "smell"], "It measures how warm something is.", true],
];

const SKILLS: Q[] = [
  ["Which tool measures temperature?", "thermometer", ["ruler", "clock"], "Degrees Celsius are used in Canada."],
  ["Which tool measures length?", "ruler", ["thermometer", "balance"], "Metres and centimetres."],
  ["Which tool compares the mass of two objects?", "balance", ["clock", "magnifying glass"], "The heavier side goes down."],
  ["Which tool measures how much liquid a cup holds?", "measuring cup", ["ruler", "clock"], "Volume is measured in millilitres or litres."],
  ["Which tool measures time?", "clock or stopwatch", ["thermometer", "ruler"], "Seconds, minutes and hours."],
  ["Which unit measures mass?", "grams", ["centimetres", "litres"], "Grams and kilograms."],
  ["Which unit measures volume of a liquid?", "millilitres", ["metres", "kilograms"], "mL and L."],
  ["Which unit measures temperature in Canada?", "degrees Celsius", ["kilograms", "kilometres"], "°C."],
  ["Which is a safe science practice?", "Wear safety goggles when told to", ["Taste unknown liquids", "Run in the lab"], "Safety first."],
  ["You see an unknown powder in a lab. What do you do?", "Do not touch or taste it; ask the teacher", ["Smell it closely", "Taste it"], "Never taste science materials."],
  ["What is a hypothesis?", "a prediction you can test", ["a final answer", "a kind of tool"], "It is a guess based on what you know."],
  ["Which is a hypothesis?", "I think a ball will bounce higher on a hard floor than on grass.", ["I like balls.", "Balls are round."], "It can be tested."],
  ["What should you do with data?", "Record it carefully and look for patterns", ["Ignore it", "Change it to match your guess"], "Data is evidence."],
  ["What if your results don't match your hypothesis?", "That is still useful: we learn something", ["You failed", "You must hide the results"], "Evidence can support or refute a prediction."],
  ["Why do scientists repeat their tests?", "To check the results are reliable", ["To waste time", "To make it fancy"], "More trials, more trust."],
  ["In a fair test, how many things should you change?", "just one", ["every single thing", "none, ever"], "Change one variable."],
  ["You test paper towels to see which soaks up most water. What stays the same?", "the amount of water poured", ["the type of paper towel", "the towel being tested"], "Keep other things equal."],
  ["Which question can be answered by an experiment?", "Which soil holds more water, sand or clay?", ["Which soil is prettiest?", "Which soil is nicest?"], "Testable questions can be measured."],
  ["Which is an observation?", "The ice melted in 6 minutes.", ["I think ice is fun.", "Ice should be blue."], "An observation uses senses or tools."],
  ["Which tool helps see tiny details on a leaf?", "magnifying glass", ["balance", "thermometer"], "It enlarges."],
  ["Which tool helps see distant birds?", "binoculars", ["ruler", "balance"], "They magnify far-away things."],
  ["A tuning fork helps you study…", "sound vibrations", ["rock layers", "soil"], "It vibrates and makes sound."],
  ["Which graph shows how a plant grows each week?", "a line graph", ["a map", "a ruler"], "Lines show change over time."],
  ["Scientists explain nature using evidence. When new evidence appears, explanations may…", "change", ["never change", "be erased from history"], "Science improves.", true],
  ["You measure the same item three times and get 8 cm, 8 cm and 9 cm. What should you do?", "Measure again carefully", ["Pick the number you like", "Throw it out"], "Repeat to check.", true],
  ["Which is a good way to record data?", "a table with labels and units", ["scribbles", "memory only"], "Organize your data.", true],
  ["Which statement is supported by this evidence: \"The plant in the sun grew 5 cm; the one in the closet grew 1 cm\"?", "Sunlight helps plants grow", ["Closets are cold", "Plants like closets"], "Match conclusion to data.", true],
];

const ENGINEER: Q[] = [
  ["What does an engineer do?", "uses science to design solutions to problems", ["only paints pictures", "only writes stories"], "Engineers solve problems."],
  ["What is technology?", "tools and inventions people make to solve problems", ["only computers", "only plants"], "A pencil is technology too."],
  ["Which is a first step in solving a problem?", "Identify the problem clearly", ["Build immediately", "Give up"], "Know the problem."],
  ["Why is it good to think of many possible solutions?", "The best one may not be the first idea", ["Only one can work", "It is a waste of time"], "Compare ideas."],
  ["You test a model bridge and it bends. What do you do next?", "Redesign it and test again", ["Quit", "Hide it"], "Engineers improve designs."],
  ["Which is an example of technology that helps us hear better?", "a hearing aid", ["a boot", "a pencil"], "It makes sound louder."],
  ["Which is an example of technology that helps us see better?", "eyeglasses", ["a spoon", "a rock"], "Lenses help sight."],
  ["Which technology uses energy from sunlight?", "a solar panel", ["a spoon", "a pillow"], "Solar technology."],
  ["A new technology may have good and bad effects. Which is a possible bad effect of cars?", "air pollution", ["fewer roads", "more quiet"], "Burning fuel releases gases."],
  ["A good effect of electric lights is that they…", "let us see at night", ["use no energy", "make the Sun brighter"], "Benefits."],
  ["A wind farm has benefits and drawbacks. Which is a drawback?", "Spinning blades can harm birds if poorly placed", ["It makes oil", "It is made of paper"], "Every choice has costs."],
  ["Why do engineers test a design?", "To find out if it works well", ["To damage it", "To make it look pretty only"], "Testing finds weak spots."],
  ["What does \"functionality\" mean for a design?", "how well it does its job", ["its colour", "its price tag only"], "Does it work?"],
  ["Which would be important for a school bag design?", "Strong zippers and comfortable straps", ["Heavy stone sides", "No pockets"], "Match design to purpose."],
  ["A class wants to reduce noise in a hallway. Which is a possible solution?", "Put soft rugs and ceiling panels", ["Make louder bells", "Add more drums"], "Soft materials absorb sound."],
  ["Which is a way to reduce energy used for lighting?", "Turn off lights when not needed", ["Add more bulbs", "Leave all lights on"], "Saving energy."],
  ["Which job uses science about soil and crops?", "farmer or agronomist", ["lifeguard", "bus driver"], "Agronomists study crops and soil."],
  ["Which job studies how well people hear?", "audiologist", ["dentist", "pilot"], "Audio = sound."],
  ["Which job uses knowledge about light and eyesight?", "optometrist", ["baker", "plumber"], "Eye doctors."],
  ["Which hobby uses science of sound?", "playing music", ["watching clouds only", "sleeping"], "Instruments make sound by vibration."],
  ["Which job protects and studies living things and habitats?", "ecologist", ["accountant", "painter"], "Ecology studies relationships in nature."],
  ["A student wants fewer wasted lunches. Which is a problem to solve?", "Too much food goes in the garbage", ["The sky is blue", "Pencils are long"], "A problem needs improving.", true],
  ["You must pick a solution. Which should you compare?", "How well each works, its cost and its effect on the environment", ["Only the colour", "Only the name"], "Weigh benefits and drawbacks.", true],
  ["A new gadget helps people but creates lots of waste. What should designers think about?", "A way to reduce the waste", ["Making more waste", "Ignoring it"], "Technology has consequences.", true],
  ["A group of students can take action on a local environmental problem. Which is an example?", "Planting a native plant garden at school", ["Throwing out the trash", "Ignoring it"], "Take action.", true],
];

const WAYS: Q[] = [
  ["Many First Nations, Métis and Inuit people learn about the land by…", "spending time on the land and observing carefully", ["never going outdoors", "only reading online"], "Land-based learning is a way of knowing."],
  ["Who often shares knowledge about the land and animals with younger people in a community?", "Elders and knowledge keepers", ["only machines", "no one"], "Knowledge is passed on with respect."],
  ["Many Indigenous ways of knowing see people, animals, plants and water as…", "connected to each other", ["completely separate", "unimportant"], "Everything is interconnected."],
  ["Observing the seasons carefully helps people know…", "when plants grow and animals move", ["the time of day only", "nothing"], "Close observation is a skill shared by scientists and knowledge keepers."],
  ["Which is a respectful way to learn about the land?", "Take only what you need and give thanks", ["Take everything", "Leave trash"], "Care for the land."],
  ["Many Indigenous communities share knowledge through…", "stories, teaching and doing", ["only exams", "silence"], "Knowledge is shared in many ways."],
  ["Inuit have long used knowledge of snow, ice and weather to…", "travel safely in the Arctic", ["avoid the outdoors", "grow bananas"], "Careful observation keeps people safe."],
  ["Which is an example of traditional and modern knowledge working together?", "Using GPS along with a knowledge keeper's advice on ice", ["Ignoring all advice", "Guessing"], "Ways of knowing can complement each other."],
  ["Indigenous peoples' knowledge of the land is…", "alive and still used today", ["only from long ago", "gone"], "It continues today."],
  ["Why do many communities teach children to look after water?", "Water is needed by all living things", ["Water is useless", "It is only for boats"], "Caring for water is caring for life."],
  ["Land-based learning means…", "learning outdoors on the land", ["learning on the phone", "learning in the dark"], "Learning with the land."],
  ["Which describes a sustainable way of living?", "Using resources in ways that leave enough for the future", ["Using everything now", "Wasting for fun"], "Sustainable = lasts."],
  ["Which shows a respectful way to share knowledge you learned from someone?", "Say who taught you and thank them", ["Claim it as your own", "Hide it"], "Give credit."],
  ["A science fair project about plants could include…", "observations on how plants grow with care", ["random guesses with no looking", "ignoring the plants"], "Observing is science.", true],
  ["Why can both Western science and Indigenous knowledge help us understand nature?", "They each offer careful observations and ideas", ["Only one is useful", "Neither is useful"], "Different ways of knowing can both teach us.", true],
  ["Which is a way to listen well when an Elder or guest speaks?", "Be quiet, look and respect what is shared", ["Interrupt", "Play a game"], "Listening is respect.", true],
  ["Which of these shows curiosity about nature?", "Asking questions and looking closely at a leaf", ["Ignoring plants", "Breaking branches"], "Curiosity leads to science.", true],
  ["Everyone can be a scientist. Which is true?", "People of all backgrounds and ages can contribute to science", ["Only adults can", "Only some people can"], "Belonging in science.", true],
  ["You might feel connected to nature when you…", "spend time outdoors noticing living things", ["stay inside all day", "ignore weather"], "Personal connection to nature.", true],
  ["Which question could you ask a knowledge keeper, with respect?", "How did you learn to notice changes in the seasons?", ["Why is your knowledge not real?", "Why do you talk?"], "Ask with respect.", true],
  ["Which of these is a good habit for learning in nature?", "Watch quietly and write what you see", ["Chase animals", "Pick every flower"], "Quiet observation."],
  ["The land is described by many Indigenous peoples as…", "something to care for and live in balance with", ["something to use up", "something unimportant"], "Reciprocal relationships."],
  ["Which tool is both old and still used by scientists?", "careful observation", ["guessing", "ignoring"], "Observation has always been central."],
  ["Which describes a wholistic way of knowing?", "Looking at how all parts of nature fit together", ["Looking at only one tiny piece", "Looking at no pieces"], "Wholistic = the whole picture."],
  ["Learning about science can build your sense of…", "belonging and confidence", ["fear only", "boredom only"], "Everyone belongs."],
  ["A teacher invites a local knowledge keeper to share. A good way to show thanks is…", "to listen well and say thank you", ["to ignore them", "to leave early"], "Show respect."],
];

export const units = [
  bankUnit({
    id: "mb-adaptations",
    title: "Adaptations & Habitats",
    emoji: "🦊",
    blurb: "How plants and animals survive where they live",
    parentNote: "Practises habitats, body and behaviour adaptations, camouflage, migration and hibernation, and how plants and animals rely on each other (pollination, seed dispersal, soil nutrients).",
    standards: ["SCI.4.E.13, SCI.4.E.15", "adaptations to a habitat, and how plants and animals rely on each other and the environment"],
    items: ADAPT,
  }),
  bankUnit({
    id: "mb-energy-senses",
    title: "Energy on the Move",
    emoji: "🔋",
    blurb: "How energy moves and how we sense it",
    parentNote: "Practises energy sources, how energy moves from a source to an object or living thing to cause action, and how people use their senses to detect heat, light and sound.",
    standards: ["SCI.4.E.6, SCI.4.E.7", "energy transfer from sources, and using the senses to detect energy in action"],
    items: ENERGY_SENSES,
  }),
  bankUnit({
    id: "mb-science-skills",
    title: "Think Like a Scientist",
    emoji: "🔬",
    blurb: "Measuring, predicting, testing and safe science",
    parentNote: "Practises measuring tools and units, safe use of equipment, fair tests, hypotheses, collecting data and drawing conclusions from evidence.",
    standards: ["SCI.4.C.2, SCI.4.C.3, SCI.4.C.4, SCI.4.D.1, SCI.4.D.2, SCI.4.D.3, SCI.4.D.4", "measuring, scientific practices, safe use of equipment, and how scientists use evidence and hypotheses"],
    items: SKILLS,
  }),
  bankUnit({
    id: "mb-engineering",
    title: "Problems, Inventions & Careers",
    emoji: "🛠️",
    blurb: "Engineering, technology and jobs that use science",
    parentNote: "Practises how engineers solve problems, comparing solutions, the good and bad effects of technology, taking action on local issues, and careers and hobbies that use science.",
    standards: ["SCI.4.C.1, SCI.4.C.5, SCI.4.D.5, SCI.4.D.6, SCI.4.D.7", "taking action on issues, careers that use science, engineering, choosing solutions and the effects of technology"],
    items: ENGINEER,
  }),
  bankUnit({
    id: "mb-ways-of-knowing",
    title: "Ways of Knowing Nature",
    emoji: "🌲",
    blurb: "Looking closely, learning on the land, caring for it",
    parentNote: "A light introduction to the ways First Nations, Métis and Inuit peoples observe and care for the land today, alongside curiosity, belonging and respect in science. It needs partner review.",
    standards: ["SCI.4.A.1, SCI.4.B.1", "First Nations, Métis and Inuit ways of knowing, and curiosity and belonging in science"],
    items: WAYS,
  }),
];
