import { bankUnit, type Q } from "../own";

// More Grade 4 English language arts: listening and talking together, big words, connecting to texts, fair and
// trustworthy texts, planning and revising writing, and thinking about learning. Purely oral and presentation
// outcomes are left out.

const TALK: Q[] = [
  ["Which shows you are listening to a speaker?", "Looking at the speaker and nodding", ["Looking out the window", "Talking to a friend"], "Eyes, face and body show listening."],
  ["Your group is sharing ideas. What is turn-taking?", "One person speaks while the others listen", ["Everyone talks at once", "Only the loudest person talks"], "Turns make sure every voice is heard."],
  ["When should you speak in a group talk?", "When it is your turn", ["While someone else is talking", "Never"], "Wait for the speaker to finish."],
  ["Which is a key idea from a talk about beavers building dams?", "Beavers build dams to make ponds", ["Beavers are brown", "The speaker wore a hat"], "A key idea is the main point."],
  ["Why do we jot down key words while someone speaks?", "To remember the important ideas", ["To make the speaker stop", "To fill the page"], "Short notes help memory."],
  ["Which is an open-ended question?", "Why do leaves change colour?", ["Is the sky blue?", "Do you like pizza?"], "Open-ended questions need more than yes or no."],
  ["Which question makes you think the most?", "How could we keep our park clean?", ["Is the park big?", "Is it open?"], "\"How\" and \"why\" questions need thinking."],
  ["Which question starts a deeper conversation?", "Why do you think the character made that choice?", ["Was the book long?", "Did you read it?"], "Ask for reasons."],
  ["A friend asks, \"Why do you like that book?\" Which answer gives a reason?", "Because the story is funny and the animals talk", ["Because", "I just do"], "A reason tells why."],
  ["Which sentence gives evidence for an opinion?", "Dogs are great pets because they love to play and can be trained", ["Dogs are great", "I like dogs a lot"], "Evidence supports what you think."],
  ["A classmate has a different opinion from you. What is a respectful reply?", "I see it differently. Here is why I think that.", ["That is a silly idea.", "You are wrong."], "Disagree kindly and give reasons."],
  ["Which is a polite way to join a conversation?", "Wait for a pause, then add your idea", ["Interrupt loudly", "Turn your back"], "Wait for the right moment."],
  ["Which shows that you are NOT listening?", "Fidgeting and talking to someone else", ["Nodding along", "Asking a question about the topic"], "Listening takes focus."],
  ["In a partner talk, what should you do after your partner shares an idea?", "Add to it or ask about it", ["Ignore it", "Change the topic right away"], "Build on each other's ideas."],
  ["Which is a good way to share a feeling with a group?", "I felt proud when we finished our project.", ["Nothing bothers me.", "Don't ask me."], "Say how you feel using \"I\" sentences."],
  ["Which sentence uses a transition word?", "First we gathered leaves, and then we sorted them.", ["We gathered leaves.", "Leaves are red."], "Transitions such as first and then link ideas."],
  ["Which sentence is more complex?", "Although it was raining, we played outside.", ["We played.", "It rained."], "A complex sentence joins two ideas."],
  ["Which word best completes it? \"I like skating, ___ I like skiing even more.\"", "but", ["because", "or"], "Use a joining word that fits the meaning."],
  ["Which word best completes it? \"We wore mitts ___ it was very cold.\"", "because", ["but", "so that"], "Because gives the reason."],
  ["Which is a richer word than \"big\" for a huge mountain?", "enormous", ["small", "tiny"], "Rich words give a clearer picture."],
  ["A friend says, \"Pass me the thing.\" What could make it clearer?", "Pass me the red pencil, please.", ["Pass me that.", "Give it."], "Be specific."],
  ["Which question would you ask to learn more about a speaker's idea?", "What makes you say that?", ["Are you done?", "Can I go now?"], "Ask for the reason."],
  ["During a group discussion, you disagree with a point. What should you do?", "Say it politely and explain why", ["Roll your eyes", "Stay silent and be upset"], "Respectful talk helps everyone.", true],
  ["Which response shows you reflected on someone's idea?", "That reminds me of what you said earlier about recycling.", ["Whatever.", "I wasn't listening."], "Reflecting connects ideas.", true],
  ["Why is it helpful to highlight key details when listening to a news story?", "You can recall who, what, when, where and why", ["You can skip the middle", "You can talk over it"], "Key details answer the five W questions.", true],
  ["Which question asks for evidence?", "What in the story made you think that?", ["Do you agree?", "Who is your friend?"], "Evidence is a detail from the text.", true],
];

const BIG_WORDS: Q[] = [
  ["How many syllables are in \"butterfly\"?", "3", ["2", "4"], "But-ter-fly."],
  ["How many syllables are in \"important\"?", "3", ["2", "4"], "Im-por-tant."],
  ["How many syllables are in \"adventure\"?", "3", ["2", "4"], "Ad-ven-ture."],
  ["How many syllables are in \"unbelievable\"?", "5", ["3", "4"], "Un-be-liev-a-ble."],
  ["How many syllables are in \"community\"?", "4", ["3", "5"], "Com-mu-ni-ty."],
  ["How many syllables are in \"playground\"?", "2", ["1", "3"], "Play-ground."],
  ["Which word is split into syllables correctly?", "pic-ture", ["pict-ure", "p-icture"], "Divide where you hear a beat."],
  ["Which word is split into syllables correctly?", "ex-plore", ["exp-lore", "e-xplore"], "Ex-plore has two beats."],
  ["Which word is split into syllables correctly?", "fan-tas-tic", ["fant-as-tic", "fa-ntas-tic"], "Fan-tas-tic."],
  ["Which word has a prefix?", "unhappy", ["happily", "happen"], "Un- is added at the start."],
  ["Which word has a suffix?", "careful", ["carpet", "candle"], "-ful is added at the end."],
  ["Which word has the prefix \"re-\"?", "replay", ["table", "money"], "Re- at the start means again."],
  ["Which word is spelled correctly?", "enough", ["enuff", "enogh"], "Learn tricky spellings by chunks: e-nough."],
  ["Which word is spelled correctly?", "beautiful", ["beutiful", "beautifull"], "Beau-ti-ful."],
  ["Which word is spelled correctly?", "February", ["Febuary", "Februry"], "Feb-ru-ar-y."],
  ["Which word is spelled correctly?", "separate", ["seperate", "seprate"], "There's \"a rat\" in sep-a-rate."],
  ["Which word is spelled correctly (Canadian spelling)?", "neighbour", ["neighbor", "nabour"], "Canadians use -our."],
  ["Which word is spelled correctly?", "knowledge", ["nolege", "knowlege"], "Silent k at the start."],
  ["Which word is spelled correctly?", "island", ["iland", "isleand"], "The s is silent."],
  ["Which punctuation mark tells you to pause a little in the middle of a sentence?", "comma", ["period", "question mark"], "Commas are small pauses."],
  ["How should your voice sound at the end of a question?", "It goes up a little", ["It goes flat for every question", "It stays silent"], "A question mark signals a rising voice."],
  ["How should you read the sentence \"Watch out!\"?", "With strong feeling", ["In a whisper, bored", "Very slowly and sleepily"], "An exclamation mark shows feeling."],
  ["A period at the end of a sentence tells a reader to…", "stop and take a breath", ["go faster", "read it again"], "Periods mark the end of a thought."],
  ["Read: \"Mia, my best friend, is here.\" The commas tell you to…", "pause around \"my best friend\"", ["shout", "skip those words"], "Commas set off extra information."],
  ["Reading the long word \"extraordinary\", which strategy helps most?", "Break it into chunks: ex-tra-or-din-ar-y", ["Skip it", "Guess from the first letter"], "Chunk long words.", true],
  ["Which word breaks into the parts \"re\" + \"build\" + \"ing\"?", "rebuilding", ["building", "rebuilt"], "Re- again, build, -ing.", true],
  ["Which sentence is read smoothly because you notice the commas?", "We packed apples, bread, cheese and juice.", ["We packed apples bread cheese and juice.", "We, packed apples bread cheese, and juice."], "Commas in a list help pacing.", true],
  ["If you read a sentence and it does not make sense, what should you do?", "Reread it and check the punctuation", ["Keep going quickly", "Stop reading the story"], "Fluent readers fix their mistakes.", true],
];

const CONNECT: Q[] = [
  ["Before reading a book about wolves, you think about what you already know. This is called…", "using prior knowledge", ["skipping the book", "guessing the ending"], "Prior knowledge is what you already know."],
  ["Which helps you understand a new text about space?", "Think about what you already know about planets", ["Ignore the title", "Read only the last page"], "Connect old and new knowledge."],
  ["You read about a girl who moves to a new town. You moved last year too. This is a…", "text-to-self connection", ["text-to-text connection", "text-to-world connection"], "Your own life links to the story."],
  ["A story reminds you of another book you read. This is a…", "text-to-text connection", ["text-to-self connection", "text-to-world connection"], "One text links to another."],
  ["An article about floods reminds you of the news about a flood in your province. This is a…", "text-to-world connection", ["text-to-self connection", "text-to-text connection"], "The text links to real events."],
  ["Why do readers make connections?", "To understand and enjoy the text more", ["To read more slowly", "To skip words"], "Connections build meaning."],
  ["Which is a multimodal text?", "A picture book with words and illustrations", ["A blank page", "A single word"], "Multimodal texts mix words, pictures, sound or video."],
  ["Which is a multimodal text?", "A video with narration and captions", ["A plain list of words only", "A list of letters"], "It uses sound, pictures and words."],
  ["Which source would be best to learn how volcanoes work?", "A science book about volcanoes", ["A cookbook", "A map of a mall"], "Match your purpose to the text."],
  ["You want to find out when the library opens. Which text is best?", "The library's website or sign", ["A fairy tale", "A poem about autumn"], "Pick a text that fits your question."],
  ["You want to read for fun. Which text could you pick?", "A funny novel", ["A phone book", "A bus timetable"], "Reading for enjoyment."],
  ["Which creators could write books for your class library?", "Authors from many cultures and communities", ["Only authors from one place", "No one"], "Diverse creators give different views."],
  ["Which question connects your life with a bigger topic?", "How do people in my town help the environment?", ["What colour is it?", "Who is tallest?"], "Link personal experience to broader topics."],
  ["You are researching how birds migrate. Which is a strong inquiry question?", "Why do some birds fly south each winter?", ["Is a bird a bird?", "Birds?"], "Detailed questions need thinking."],
  ["Which is a text to gather background knowledge about Manitoba?", "An atlas or Manitoba nature guide", ["A comic about aliens", "A recipe for cake"], "Choose sources that match."],
  ["After reading three sources, what should you decide?", "Which facts to share and which to leave out", ["To copy everything", "To forget it all"], "Choose what fits your purpose."],
  ["You find a fact that has nothing to do with your topic. What do you do?", "Leave it out", ["Add it anyway", "Make it the title"], "Keep to your purpose."],
  ["A character feels left out. Which connection could you make?", "I felt that way when I was new at school.", ["I like pizza.", "It is Tuesday."], "A real connection links feelings."],
  ["Reading a book about the Red River, you recall a trip to Winnipeg. This is a…", "text-to-self connection", ["text-to-text connection", "no connection"], "Your own trip links to the text."],
  ["Which is a good reason to choose a nonfiction book?", "To learn facts about a topic", ["To read a made-up fairy tale", "To read a joke only"], "Nonfiction teaches facts."],
  ["A poem and a story are both about winter. A reader notices both use cold images. This is…", "making connections between texts", ["copying", "guessing"], "Compare texts that share ideas."],
  ["What can a graphic or photo in a text do?", "Give information the words do not", ["Hide the meaning", "Slow down the reader for no reason"], "Images add meaning."],
  ["Which helps you understand a new word in a sentence about \"habitats\"?", "Think about what you know about where animals live", ["Skip the sentence", "Cover the picture"], "Prior knowledge unlocks vocabulary.", true],
  ["You read: \"The class planted trees to help the planet.\" Which connection links to the world?", "Many communities plant trees to help the Earth", ["I like trees", "Trees are green"], "A world connection links to what is happening beyond you.", true],
  ["Why might two readers connect differently to the same story?", "They have different experiences", ["One reads wrong", "The words change"], "Experiences shape connections.", true],
  ["Which source gives you the most reliable information on how electricity is made?", "A science textbook or museum website", ["An unsigned post", "A joke video"], "Look for trusted sources.", true],
];

const FAIR: Q[] = [
  ["What does it mean for a text to show diversity?", "It shows people with many backgrounds and ways of life", ["It shows only one kind of person", "It has pictures only"], "Diversity means differences."],
  ["What does inclusion mean in a story?", "Everyone is welcomed and treated fairly", ["Some are left out", "Only boys join"], "Included means part of the group."],
  ["A book shows children of many cultures playing together. What does it show?", "Diversity and inclusion", ["Only winning", "A map"], "Different people, together."],
  ["How can you show that a story is inclusive?", "Point to something a character does or says as evidence", ["Say it is nice", "Skip the story"], "Use evidence such as quotes or actions."],
  ["What is a stereotype?", "An unfair idea that all people in a group are the same", ["A kind of poem", "A true fact about one person"], "Stereotypes ignore individuals."],
  ["Which sentence shows a stereotype?", "All girls like pink.", ["Some children like pink.", "My friend likes pink."], "\"All\" ignores differences."],
  ["Which sentence shows a stereotype?", "Old people can't use computers.", ["My grandpa uses a tablet.", "Some people learn computers later."], "It is a broad unfair claim."],
  ["What is bias?", "Favouring one side in an unfair way", ["Being very tall", "A kind of map"], "A biased text isn't balanced."],
  ["A story only shows boys as brave and girls as scared. This is…", "bias", ["balance", "fairness"], "It treats groups unfairly."],
  ["What is prejudice?", "Judging people before knowing them", ["Knowing a friend well", "Sharing a snack"], "Pre-judging."],
  ["You read an advertisement that says, \"Everyone loves our juice!\" Should you trust it?", "Check it, because ads want to sell things", ["Always, because it's printed", "Yes, because it uses exclamation marks"], "Ads try to persuade."],
  ["Which source is more trustworthy for facts about whales?", "A science book written by an expert", ["A rumour", "An unsigned post"], "Experts check their facts."],
  ["Which is a sign that a website may not be trustworthy?", "No author or date and lots of pop-up ads", ["It names its sources", "It is written by a scientist"], "Look for who wrote it."],
  ["A character says, \"Never trust anyone from that town.\" What should you notice?", "It is unfair to judge a whole town", ["It's always true", "It is a fact"], "This is prejudice."],
  ["Which is an opinion?", "Winter is the best season.", ["Winter has snow in Manitoba.", "Winter follows autumn."], "Opinions are what someone thinks."],
  ["Which is a fact?", "Lake Winnipeg is in Manitoba.", ["Lake Winnipeg is the prettiest lake.", "Everyone loves fishing there."], "A fact can be checked."],
  ["You write, \"I think the library should have more books because kids read more when they have choices.\" This is…", "an opinion with a reason", ["a fact only", "a question"], "You gave a reason."],
  ["Which opinion is supported by evidence?", "Recycling is good because it reduces garbage in landfills.", ["Recycling is good.", "I just like it."], "Evidence = reasons or facts."],
  ["You see a stereotype in a movie. What is a good response?", "Notice it and say why it is unfair", ["Believe it", "Repeat it to friends"], "Respond kindly and clearly."],
  ["A text says \"Everyone from the North lives in igloos.\" What is wrong with it?", "It treats all northerners as the same", ["It is exciting", "It is too long"], "People live in many kinds of homes."],
  ["Which statement is fairer?", "Many people in the North live in houses and apartments.", ["Everyone lives in igloos.", "No one lives there."], "Use words like many and some."],
  ["Which character's actions show kindness to a newcomer?", "She shared her lunch and invited the new girl to play.", ["She laughed at the new girl.", "She ignored the new girl."], "Actions show values."],
  ["Which question helps you decide whether to trust a source?", "Who wrote this and how do they know?", ["Is it long?", "Is it colourful?"], "Check the author and evidence."],
  ["Which picture caption is least biased?", "Children of many ages play in the park.", ["Only fun kids play here.", "Boring people sit alone."], "Neutral captions describe.", true],
  ["After reading a biased story, what should a thoughtful reader ask?", "Whose voice is missing?", ["Is it tall?", "Can I stop?"], "Notice who is not heard.", true],
  ["Which response to a stereotype is respectful?", "That is not true for everyone. Let me share what I know.", ["That is dumb.", "I agree with it."], "Correct with kindness.", true],
];

const PLAN: Q[] = [
  ["Which is a way to choose a topic for writing?", "Think about what you know and care about", ["Pick the longest word", "Copy a friend's idea"], "Good writers use their own ideas."],
  ["Before writing, you jot down ideas as fast as you can. This is…", "brainstorming", ["proofreading", "publishing"], "Brainstorming gathers ideas."],
  ["A drawing with a topic in the middle and branches out is a…", "mind map", ["timeline", "calendar"], "Mind maps connect ideas."],
  ["Which writing tool helps you plan a story's beginning, middle and end?", "a story organizer", ["a calculator", "a ruler"], "Organizers sort ideas."],
  ["Why do writers plan before they write?", "To organize their ideas", ["To make writing harder", "To get done fast"], "A plan saves time later."],
  ["Which type of writing tells a made-up or real story with characters?", "narrative", ["persuasive", "informational"], "Narrative = story."],
  ["Which type of writing gives facts about a topic?", "informational", ["narrative", "descriptive"], "Informational = information."],
  ["Which type of writing paints a picture of a place or person with details?", "descriptive", ["persuasive", "informational"], "Descriptive = describing."],
  ["Which type of writing tries to convince the reader?", "persuasive", ["narrative", "descriptive"], "Persuasive = persuade."],
  ["A letter asking the principal for a new soccer ball is…", "persuasive writing", ["a story", "a poem"], "It tries to convince."],
  ["A report about moose in Manitoba is…", "informational writing", ["narrative writing", "persuasive writing"], "It shares facts."],
  ["A paragraph describing a rainy day with sounds and smells is…", "descriptive writing", ["informational writing", "a list"], "It paints a picture."],
  ["A story about a lost puppy finding its way home is…", "narrative writing", ["descriptive writing", "a report"], "It has a plot."],
  ["Your audience is kindergarten children. Which word choice fits?", "Short, simple words", ["Very long technical words", "Slang only"], "Know your audience."],
  ["What is the purpose of a how-to writing piece?", "To explain steps so others can do something", ["To scare readers", "To make a joke only"], "Purpose = why you write."],
  ["Which is a multimodal text you could create?", "A poster with words and pictures", ["A blank page", "One word"], "It combines modes."],
  ["Which is a multimodal text you could create?", "A slide show with narration", ["A pencil", "A silent blank screen"], "Slides, voice and images work together."],
  ["Before writing a report, you ask an expert and read a book. This is…", "gathering information from sources", ["guessing", "copying"], "Research gives you facts."],
  ["Which source is a mentor text for writing a poem?", "A poem you admire", ["A phone number list", "A bus schedule"], "Learn from good examples."],
  ["Jot notes are…", "short notes of key words and ideas", ["a full essay", "a final copy"], "Quick, not perfect."],
  ["Why is a research planner helpful?", "It helps you list questions and where to look", ["It writes the report for you", "It has no use"], "Plan your research."],
  ["Which question belongs in a research planner?", "What do I want to find out?", ["Where is my lunch?", "What time is recess?"], "Start with your question."],
  ["For a persuasive poster, which topic fits best?", "Why we should walk to school", ["A recipe for soup", "A list of dinosaurs"], "Persuasive = take a position.", true],
  ["You want to share a story out loud with music. Which form fits?", "Oral storytelling", ["A bar graph", "A map"], "Choose the form for your message.", true],
  ["Which digital tool could help you organize ideas for a report?", "a graphic organizer on a tablet", ["a clock", "a pencil sharpener"], "Digital organizers help planning.", true],
  ["You must choose an audience for a thank-you note. Who is the best audience?", "The person who helped you", ["A stranger", "No one"], "The note is for them.", true],
  ["Which pair matches the writing to its purpose?", "Persuasive: convince; Informational: inform", ["Persuasive: inform; Informational: convince", "Narrative: convince; Descriptive: list"], "Know the purposes.", true],
];

const REVISE: Q[] = [
  ["Which sentence has a sensory detail (something you hear)?", "The thunder rumbled across the prairie.", ["It was a day.", "There was weather."], "Sensory details use the five senses."],
  ["Which sentence uses a sensory detail (something you smell)?", "The warm bannock smelled like fresh bread.", ["The food was food.", "It was a lunch."], "Smell is one of the senses."],
  ["Which sentence has a stronger word choice?", "The puppy bounded across the yard.", ["The puppy went across the yard.", "The puppy moved."], "Strong verbs show action."],
  ["Which word is stronger than \"said\" for a loud shout?", "yelled", ["whispered", "asked"], "Pick a word that matches the action."],
  ["Which word is stronger than \"nice\"?", "friendly", ["okay", "good"], "Specific words are clearer."],
  ["Which sentence adds a detail to show how something looks?", "The tall maple glowed red and gold.", ["The tree was there.", "It was a tree."], "Describe with colour and shape."],
  ["Revising means…", "making your writing better", ["throwing it away", "erasing everything"], "Revising improves ideas and words."],
  ["You notice a sentence does not make sense. What should you do?", "Revise it so it is clear", ["Leave it", "Make it longer with random words"], "Fix confusing parts."],
  ["Your friend reads your story and says the middle is confusing. This is…", "feedback", ["a prize", "a mistake"], "Feedback helps you improve."],
  ["Which is helpful feedback?", "Your first paragraph grabs me. Add more details in the middle.", ["It's bad.", "I don't like it."], "Helpful feedback is kind and specific."],
  ["Which step belongs in revising?", "Moving sentences into a better order", ["Choosing a new notebook", "Counting the pages"], "Reorganize ideas."],
  ["Which step belongs in revising?", "Adding a detail to a bare sentence", ["Colouring the cover", "Sharpening your pencil"], "Add to make clear."],
  ["Which step belongs in revising?", "Taking out a sentence that does not fit", ["Making all words big", "Skipping the end"], "Remove off-topic ideas."],
  ["Which sentence is clearer?", "I put my red mitts in my backpack.", ["I put them in it.", "I put stuff in there."], "Name things clearly."],
  ["When you write by hand, what helps people read it?", "Neat letters with spaces between words", ["Squeezing words together", "Tiny letters"], "Legibility."],
  ["When writing, margins are…", "the empty space around the edge of the page", ["a kind of punctuation", "a title"], "Margins keep writing neat."],
  ["When you use a computer to write, which choice makes text easy to read?", "A clear font and a good size", ["Tiny curly font", "A pale yellow font on white"], "Choose readable fonts."],
  ["On a poster, which font colour is easiest to read on white paper?", "dark blue or black", ["pale yellow", "light grey"], "Contrast helps readers."],
  ["Your final text uses words, pictures and sound. What is it?", "a multimodal text", ["a list", "a title only"], "Several modes combined."],
  ["Which is a good idea for a final poster?", "Add a title, pictures and short labels", ["Cover it with text", "Use no title"], "Fit your audience and purpose."],
  ["Why add a picture or graph to a report?", "To help the audience understand", ["To fill space only", "To hide the words"], "Visuals support ideas."],
  ["A video with narration should match its purpose. For teaching younger kids, narration should be…", "slow and clear", ["fast and mumbled", "silent"], "Fit the audience."],
  ["Which change improves \"The dog is good\"?", "The dog fetched the ball and wagged its tail.", ["The dog is good dog.", "Dog good."], "Show with details.", true],
  ["Which revision shows ideas moving in order?", "First we mixed the dough. Next we rolled it. Finally we baked it.", ["We baked it. First we mixed. Next we rolled.", "Rolled the dough. We baked. Mixed it."], "Transitions show order.", true],
  ["You seek feedback from a classmate. Which request is best?", "Which part is hard to understand?", ["Is this perfect?", "Can I stop now?"], "Ask about specific areas.", true],
  ["Which change adds a sense of touch?", "The wool mitts felt scratchy and warm.", ["The mitts were mitts.", "The mitts were there."], "Touch details.", true],
  ["Which sentence has the best word choice for a scary moment?", "The door creaked open slowly.", ["The door was open.", "The door was a door."], "Sound words add mood.", true],
];

const LEARN: Q[] = [
  ["Which question helps you check your own learning?", "What strategies have I learned?", ["Who is tallest?", "What is for lunch?"], "Self-monitoring."],
  ["Which question helps a reader who is stuck?", "What can I do to figure this out?", ["Why bother?", "Can I skip it?"], "Ask about strategies."],
  ["You don't know a word in a story. Which is a good strategy?", "Use clues from nearby words and pictures", ["Skip the whole story", "Close the book"], "Context clues help."],
  ["Which is a learning goal?", "I will learn to check my writing for capital letters.", ["I will be good.", "I will try."], "Goals are specific."],
  ["Which goal is specific?", "I will read 10 pages each night.", ["I will read some.", "I will be better."], "Specific goals have numbers or actions."],
  ["Which tool helps you track your learning over time?", "a learning journal", ["a ruler", "a snack"], "Journals record progress."],
  ["Which tool collects your best work to show growth?", "a portfolio", ["a calendar", "a map"], "A portfolio shows progress."],
  ["Which can help you check your own understanding?", "Telling a partner the main idea in your own words", ["Skipping the page", "Guessing"], "Explaining shows you understood."],
  ["Teachers give you feedback: \"Add more details to your middle.\" What is a good next step?", "Add details and check again", ["Ignore it", "Throw the page away"], "Use feedback to grow."],
  ["Which describes a growth mindset?", "I can't do it yet, but I can learn", ["I'm just bad at it", "I'll never learn"], "\"Yet\" shows growth."],
  ["You made a mistake in your spelling. What is a helpful thought?", "Mistakes help me learn", ["I give up", "This is the worst"], "Mistakes are for learning."],
  ["A classmate helps you with your writing. What is a kind thing to say?", "Thank you, that helps", ["Go away", "Nobody asked"], "Be thankful for help."],
  ["Which helps you keep track of progress in reading?", "A chart where you record books finished", ["A blank wall", "A pencil case"], "Charts show growth."],
  ["Which shows you reflected on new learning?", "I learned that commas separate items in a list.", ["I did a page.", "It was Tuesday."], "Reflection names what you learned."],
  ["Which of these is a criterion for good writing?", "Capital letters and punctuation are correct", ["The paper is white", "The pen is blue"], "Criteria describe quality."],
  ["Which pair is a good set of criteria for a poster?", "Clear title and neat pictures", ["Long and loud", "Heavy paper"], "Criteria help you assess."],
  ["After a lesson, you ask yourself, \"What is important to know?\" This is…", "self-monitoring", ["daydreaming", "copying"], "Think about your thinking."],
  ["How can you improve your listening?", "Face the speaker and ignore distractions", ["Doodle through the talk", "Talk to a friend"], "Active listening is a skill."],
  ["Your goal is to improve your spelling. Which action helps?", "Practise tricky words a little every day", ["Never look at them", "Only guess"], "Practice builds skills."],
  ["After finishing a unit, how can you show progress?", "Compare old and new work", ["Throw out old work", "Forget the old work"], "Look back at growth."],
  ["Which statement shows you monitored your reading?", "I stopped when it didn't make sense and reread.", ["I kept going and ignored it.", "I closed the book."], "Fix-up strategies."],
  ["You want to be a better writer. Whom might you ask for descriptive feedback?", "A teacher or classmate who read your work", ["Nobody", "A stranger you will never meet"], "Ask readers."],
  ["Which goal fits \"I want to improve my listening\"?", "I will repeat key ideas back to my partner.", ["I will sit still forever.", "I will talk more."], "Make a plan that matches the goal.", true],
  ["A podcast could be used to…", "share what you learned in your own voice", ["measure rain", "colour a map"], "Digital tools can show learning.", true],
  ["How does monitoring your progress help?", "You see what is working and what to change", ["It stops all learning", "It hides your goals"], "Reflection informs next steps.", true],
  ["Which is the best way to respond to descriptive feedback?", "Pick one thing to change and try it", ["Argue", "Do nothing"], "Small steps are doable.", true],
];

export const units = [
  bankUnit({
    id: "mb-talk-together",
    title: "Listening & Talking Together",
    emoji: "🗣️",
    blurb: "Good listeners, good questions, kind conversations",
    parentNote: "Practises listening for key ideas, taking turns, asking open-ended questions, giving reasons and using rich words and linking words in conversation.",
    standards: ["ELA.4.A1.1, ELA.4.A1.2, ELA.4.A1.3, ELA.4.A1.4, ELA.4.A1.6", "listening, taking turns, asking open-ended questions and sharing ideas in conversation"],
    items: TALK,
  }),
  bankUnit({
    id: "mb-big-words",
    title: "Big Words & Smooth Reading",
    emoji: "📖",
    blurb: "Syllables, spelling and reading with feeling",
    parentNote: "Practises breaking long words into syllables and parts, spelling tricky words, and reading smoothly by noticing punctuation.",
    standards: ["ELA.4.A2.3, ELA.4.A2.6", "decoding and spelling multisyllabic words, and reading fluently with punctuation"],
    items: BIG_WORDS,
  }),
  bankUnit({
    id: "mb-connect-texts",
    title: "Making Connections",
    emoji: "🔗",
    blurb: "Link what you read to your life and the world",
    parentNote: "Practises using what you already know, text-to-self, text-to-text and text-to-world connections, choosing the right text, and deciding what to share from research.",
    standards: ["ELA.4.B1.1, ELA.4.B1.2, ELA.4.B1.3, ELA.4.B1.4, ELA.4.B2.4", "prior knowledge, choosing texts, inquiry questions and making connections to texts"],
    items: CONNECT,
  }),
  bankUnit({
    id: "mb-fair-texts",
    title: "Fair & Trustworthy Texts",
    emoji: "⚖️",
    blurb: "Spot bias, stereotypes and sources you can trust",
    parentNote: "Practises noticing diversity and inclusion in stories, telling fact from opinion, spotting stereotypes and bias, and deciding whether a source can be trusted.",
    standards: ["ELA.4.B3.1, ELA.4.B3.2, ELA.4.B3.4", "diversity and inclusion in texts, trusting sources, stereotypes and bias, and supported opinions"],
    items: FAIR,
  }),
  bankUnit({
    id: "mb-plan-writing",
    title: "Plan Your Writing",
    emoji: "📝",
    blurb: "Topics, plans and the four kinds of writing",
    parentNote: "Practises choosing a topic and audience, planning with brainstorming and organizers, and matching narrative, informational, descriptive and persuasive writing to a purpose.",
    standards: ["ELA.4.C1.1, ELA.4.C1.2, ELA.4.C1.3, ELA.4.C1.4, ELA.4.C1.5", "choosing topics, planning, kinds of writing and creating multimodal texts"],
    items: PLAN,
  }),
  bankUnit({
    id: "mb-revise-writing",
    title: "Revise & Polish",
    emoji: "✨",
    blurb: "Vivid details, fixing what's unclear, neat finished work",
    parentNote: "Practises adding sensory details, choosing stronger words, revising to make writing clearer, using feedback and presenting final work neatly with words and images.",
    standards: ["ELA.4.C2.3, ELA.4.C2.5, ELA.4.C3.1, ELA.4.C3.5", "word choice and sensory details, revising, legible and digital writing, and final multimodal texts"],
    items: REVISE,
  }),
  bankUnit({
    id: "mb-learning-goals",
    title: "My Learning Goals",
    emoji: "🎯",
    blurb: "Set goals, use feedback, notice how you grow",
    parentNote: "Practises setting specific goals, choosing strategies, using feedback and tracking progress in listening, speaking, reading and writing.",
    standards: ["ELA.4.D2.1, ELA.4.D2.2, ELA.4.D2.3, ELA.4.D2.4, ELA.4.D2.5", "self-monitoring, criteria, feedback, goals and tracking progress"],
    items: LEARN,
  }),
];
