import { bankUnit, type Q } from "../own";

// Grade 4 science, Cluster 1 (Earth science: soil, rocks and energy resources). Light, sound and living things
// are adopted from existing units.

const SOIL: Q[] = [
  ["Soil is made mostly of…", "tiny bits of rock and rotted plants and animals", ["only water", "only air"], "Soil mixes broken rock with humus."],
  ["What is humus?", "rotted plant and animal matter in soil", ["a type of rock", "a kind of sand"], "Humus feeds plants and holds water."],
  ["Which type of soil has large, gritty grains?", "sandy soil", ["clay soil", "loam"], "Sand feels rough and water runs through it quickly."],
  ["Which soil feels sticky when wet and holds a lot of water?", "clay soil", ["sandy soil", "gravel"], "Clay particles are very tiny."],
  ["Which soil is a mix of sand, silt, clay and humus?", "loam", ["sandy soil", "gravel"], "Loam is great for growing plants."],
  ["Which type of soil lets water drain through the fastest?", "sandy soil", ["clay soil", "loam"], "Big gaps between sand grains let water through."],
  ["Which soil is the hardest for water to soak into?", "clay soil", ["sandy soil", "loam"], "Clay's tiny grains pack tightly."],
  ["Fertile soil is soil that…", "is good for growing plants", ["is always dry", "has no life in it"], "Fertile soil has nutrients, air and water."],
  ["Which of these does fertile soil have?", "nutrients and humus", ["only sand", "only stones"], "Nutrients feed plants."],
  ["What do earthworms do for soil?", "mix it and let in air", ["make it into rock", "poison it"], "Worms tunnel and help soil get air and water."],
  ["Which living thing helps break down dead leaves into humus?", "decomposers such as fungi and worms", ["clouds", "mountains"], "Decomposers recycle dead plants and animals."],
  ["Soil is important because…", "plants grow in it and animals depend on plants", ["it is cold", "it is shiny"], "Food from farms starts with soil."],
  ["What do plants get from soil?", "water and nutrients", ["sunlight", "sound"], "Roots take up water and nutrients."],
  ["Which layer of soil is on top and is the darkest and richest?", "topsoil", ["bedrock", "subsoil"], "Topsoil has the most humus."],
  ["What is under the soil layers?", "bedrock", ["topsoil", "humus"], "Bedrock is solid rock."],
  ["Why is Manitoba's Red River valley good for farming?", "It has very rich, dark soil", ["It is solid rock", "It is covered in sand"], "Ancient lake bottom left rich soil."],
  ["What can wash away soil from a hillside?", "heavy rain or wind", ["gentle sunshine", "moonlight"], "Erosion carries soil away."],
  ["What is erosion?", "the wearing away and moving of soil and rock", ["the growing of plants", "melting snow"], "Water, wind and ice cause erosion."],
  ["How can farmers protect soil from blowing away?", "Plant crops or grass to cover it", ["Leave it bare", "Dig it all up"], "Roots hold soil in place."],
  ["Which would help keep soil healthy?", "adding compost", ["adding plastic", "adding oil"], "Compost adds humus and nutrients."],
  ["Compost is made from…", "rotted food scraps and leaves", ["plastic bottles", "metal cans"], "Composting turns waste into food for soil."],
  ["Which tool could you use to sort soil by particle size?", "a sieve", ["a thermometer", "a clock"], "A sieve separates larger bits from small ones."],
  ["When you shake soil with water in a jar and let it settle, the biggest pieces settle…", "first, at the bottom", ["last, at the top", "in the middle"], "Heavier, bigger pieces sink fastest."],
  ["Which kind of soil would be best for a vegetable garden?", "loam with compost", ["pure sand", "pure gravel"], "Loam holds water but also drains."],
  ["Which soil would be too dry for most plants to grow?", "pure sand", ["loam", "humus-rich soil"], "Sand does not hold water well.", true],
  ["Why is it a good idea to keep soil covered with plants?", "Roots hold soil and stop erosion", ["Plants make soil blow away", "Soil needs to stay bare"], "Roots hold soil together.", true],
  ["A farmer finds her field drains slowly and puddles. What soil might it have a lot of?", "clay", ["sand", "gravel"], "Clay holds water.", true],
  ["How does soil form over a very long time?", "Rock breaks into small pieces and mixes with humus", ["Water freezes into dust", "Plants turn into stone"], "Weathering and rotting make soil over hundreds of years.", true],
  ["Why is topsoil called a resource that is slow to replace?", "It can take hundreds of years to form", ["It forms overnight", "It is made in factories"], "We should care for it.", true],
];

const ENERGY: Q[] = [
  ["Energy from the sun, wind or water is called…", "renewable", ["non-renewable", "broken"], "Renewable energy keeps coming back."],
  ["Which source of energy is renewable?", "wind", ["coal", "oil"], "Wind blows again and again."],
  ["Which source of energy is renewable?", "flowing water", ["natural gas", "coal"], "Dams use moving water to make electricity."],
  ["Which source of energy is renewable?", "sunlight", ["oil", "coal"], "The sun shines every day."],
  ["Which source of energy is non-renewable?", "coal", ["wind", "sunlight"], "Coal took millions of years to form."],
  ["Which source of energy is non-renewable?", "oil", ["water", "wind"], "Oil cannot be replaced quickly."],
  ["Which source of energy is non-renewable?", "natural gas", ["solar", "wind"], "Natural gas is a fossil fuel."],
  ["Non-renewable energy sources…", "will run out one day", ["never run out", "come from the sun"], "Once used, they cannot be replaced in our lifetime."],
  ["What do we call coal, oil and natural gas?", "fossil fuels", ["wind fuels", "water fuels"], "They formed from ancient plants and animals."],
  ["Most of Manitoba's electricity comes from…", "hydroelectric dams", ["coal mines", "nuclear plants"], "Dams on rivers such as the Nelson make electricity."],
  ["What is a hydroelectric dam?", "A wall that uses falling water to make electricity", ["A wall that stops snow", "A pool for swimming"], "Moving water turns a turbine."],
  ["What spins to generate electricity at a wind farm?", "turbines", ["wheels", "sails"], "Wind turns the blades."],
  ["Solar panels turn sunlight into…", "electricity", ["rain", "oil"], "Solar panels are on some roofs."],
  ["Where would a solar panel work best?", "a sunny place", ["a dark cave", "under water"], "It needs sunlight."],
  ["Burning fossil fuels can cause…", "air pollution", ["more fresh water", "more wind"], "Burning fuel releases gases."],
  ["Which choice saves energy at home?", "Turn off lights when you leave a room", ["Leave all lights on", "Open the fridge often"], "Small actions add up."],
  ["Which choice saves energy?", "Walk or bike to school", ["Ride alone in a big car", "Leave the car running"], "Walking uses no fuel."],
  ["Which is a good way to save energy in winter?", "Wear a sweater and keep doors closed", ["Open all windows", "Turn the heat up very high"], "It keeps warm air inside."],
  ["Why do we care about using less energy?", "It saves resources and protects nature", ["It makes things taste better", "It makes the sun brighter"], "Saving energy helps the planet."],
  ["Biomass energy comes from…", "burning plants such as wood", ["wind", "rocks only"], "It is renewable if new trees grow."],
  ["Which is a drawback of dams?", "They can change the land and water", ["They make no electricity", "They use coal"], "Dams flood land upstream and change habitats.", true],
  ["Which is a benefit of wind power?", "It makes electricity without burning fuel", ["It works with no wind", "It uses coal"], "Wind does not make air pollution.", true],
  ["A wind farm is a good idea where there is…", "steady, strong wind", ["no wind", "dense forest"], "Open areas on the prairie are windy.", true],
  ["A battery stores…", "energy", ["wind", "rocks"], "Batteries store energy to use later.", true],
  ["Which of these is a renewable resource when managed well?", "trees", ["coal", "oil"], "New trees can be planted.", true],
  ["Which pairing is correct?", "Coal — non-renewable", ["Sunlight — non-renewable", "Oil — renewable"], "Coal and oil are non-renewable.", true],
  ["How could families reduce the energy they use for lighting?", "Use LED bulbs", ["Use bigger old bulbs", "Leave bulbs on all night"], "LED bulbs use much less power.", true],
  ["Which is the best example of conserving energy?", "Unplugging devices when finished", ["Leaving the TV on all night", "Running the dryer half empty"], "Devices can use power even when off.", true],
  ["Which type of energy is found in the Prairies in big amounts?", "wind", ["tidal", "geothermal volcano"], "The Prairies are open and windy.", true],
];

const ROCKS: Q[] = [
  ["Rock that forms when melted rock cools and hardens is…", "igneous", ["sedimentary", "metamorphic"], "Igneous rock starts as hot, melted rock."],
  ["Rock that forms from layers of sand, mud and shells pressed together is…", "sedimentary", ["igneous", "metamorphic"], "Sedimentary rock forms in layers."],
  ["Rock that is changed by heat and pressure is…", "metamorphic", ["igneous", "sedimentary"], "Metamorphic means changed in form."],
  ["Granite is an example of which kind of rock?", "igneous", ["sedimentary", "metamorphic"], "Granite cooled from melted rock."],
  ["Sandstone is an example of which kind of rock?", "sedimentary", ["igneous", "metamorphic"], "Sandstone is made of sand pressed together."],
  ["Limestone is an example of which kind of rock?", "sedimentary", ["igneous", "metamorphic"], "Limestone often forms from shells in water. Manitoba's Tyndall stone is limestone."],
  ["Marble is an example of which kind of rock?", "metamorphic", ["igneous", "sedimentary"], "Marble is limestone changed by heat and pressure."],
  ["Which rock is most likely to contain fossils?", "sedimentary rock", ["igneous rock", "metamorphic rock"], "Fossils are pressed into soft layers."],
  ["What is a fossil?", "the remains or traces of a living thing from long ago", ["a type of soil", "a kind of crystal"], "Fossils are found in rock."],
  ["Lava is…", "melted rock that has reached the surface", ["frozen water", "a kind of soil"], "Cooled lava becomes igneous rock."],
  ["What is a mineral?", "a natural, non-living solid found in rocks", ["a living plant", "a kind of water"], "Rocks are made of one or more minerals."],
  ["Which tool would help you look closely at the grains in a rock?", "a hand lens", ["a clock", "a ruler only"], "A magnifier shows tiny details."],
  ["Which test checks how easily a mineral is scratched?", "hardness", ["colour only", "weight of the box"], "Harder minerals scratch softer ones."],
  ["What is weathering?", "the breaking of rock into smaller pieces", ["the growing of crystals", "a kind of storm"], "Wind, water and ice can break rock apart."],
  ["Which weathers rock when water freezes in cracks?", "ice", ["sunshine only", "darkness"], "Ice expands and splits rock."],
  ["What is erosion?", "the carrying away of bits of rock and soil", ["the freezing of lakes", "the making of lava"], "Water and wind move the pieces."],
  ["Which of these can cause erosion?", "flowing water", ["a still pebble", "a closed book"], "Rivers carry sand and silt."],
  ["The Canadian Shield is made mostly of very old…", "hard rock", ["soft sand", "ice"], "It is some of the oldest rock on Earth."],
  ["Which Manitoba stone is used on buildings and is full of fossils?", "Tyndall stone", ["soapstone", "chalk"], "Tyndall stone is a limestone quarried near Winnipeg."],
  ["A rock collection is best sorted by…", "how the rocks look and feel", ["their price", "who found them"], "Scientists sort by properties."],
  ["Which of these is a use of rock?", "building materials", ["food", "clothing"], "Rock is used for buildings and roads."],
  ["Which of these is a mineral resource Manitoba mines?", "nickel", ["pineapples", "rubber"], "Manitoba has metal mines."],
  ["When sediment piles up and is pressed over a long time it can become…", "sedimentary rock", ["igneous rock", "a volcano"], "Pressure joins the pieces."],
  ["How many main types of rock are there?", "three", ["one", "ten"], "The three types are igneous, sedimentary and metamorphic."],
  ["Which rock has crystals that formed as melted rock cooled slowly?", "granite", ["sandstone", "shale"], "Slow cooling makes bigger crystals.", true],
  ["A rock with layers that you can scratch with a fingernail is probably…", "sedimentary", ["igneous", "metamorphic"], "Softer layered rock is often sedimentary.", true],
  ["Why do rivers have smooth, rounded stones?", "Water rubs them against each other for a long time", ["Someone polished them", "They grew round"], "Erosion rounds stones.", true],
  ["How can a mountain become smaller over a very long time?", "Weathering and erosion wear it down", ["It sinks into soil", "Plants eat it"], "Rock wears away slowly.", true],
  ["A fossil is most likely to be found in…", "a layer of sedimentary rock", ["fresh lava", "a glass jar"], "Hot lava would destroy remains.", true],
];

export const units = [
  bankUnit({
    id: "mb-soil",
    title: "Soil Detectives",
    emoji: "🪱",
    blurb: "What soil is made of and why it matters",
    parentNote:
      "Practises the nature and types of soil (sandy, clay and loam), what makes soil fertile, the layers of soil, and how people look after it.",
    standards: ["SCI.4.E.9, SCI.4.E.10", "the nature and types of soil, and the properties of fertile soil"],
    items: SOIL,
  }),
  bankUnit({
    id: "mb-energy-resources",
    title: "Energy We Use",
    emoji: "🌬️",
    blurb: "Renewable and non-renewable energy",
    parentNote:
      "Practises renewable and non-renewable sources of energy, including the hydroelectric power Manitoba depends on, and ways families can save energy.",
    standards: ["SCI.4.E.8", "the differences between renewable and non-renewable energy sources"],
    items: ENERGY,
  }),
  bankUnit({
    id: "mb-rocks",
    title: "Rocks & Minerals",
    emoji: "🪨",
    blurb: "Igneous, sedimentary, metamorphic and fossils",
    parentNote:
      "Practises the three types of rock and how each forms, minerals and fossils, and how weathering and erosion wear rock down.",
    standards: ["SCI.4.E.11, SCI.4.E.12", "types of rock and how they form, weathering and erosion of rock"],
    items: ROCKS,
  }),
];
