import { bankUnit, type Q } from "../own";

// Grade 4 social studies, Canada's Geography (Cluster 1) and Manitoba (Clusters 2 and 3): regions, maps,
// citizenship and government, Manitoba's land, people and history. Indigenous content is light, in the present
// tense, and needs partner review.

const MAP: Q[] = [
  ["Which is the capital city of Manitoba?", "Winnipeg", ["Brandon", "Thompson"], "Winnipeg is Manitoba's capital and largest city."],
  ["Which is the capital city of Canada?", "Ottawa", ["Winnipeg", "Vancouver"], "Ottawa is where Canada's Parliament meets."],
  ["Which is the capital city of Saskatchewan?", "Regina", ["Saskatoon", "Edmonton"], "Regina is the capital of the province next door to the west."],
  ["Which is the capital city of Alberta?", "Edmonton", ["Calgary", "Regina"], "Edmonton is Alberta's capital. Calgary is bigger in some ways, but it is not the capital."],
  ["Which is the capital city of British Columbia?", "Victoria", ["Vancouver", "Kelowna"], "Victoria is on Vancouver Island."],
  ["Which is the capital city of Ontario?", "Toronto", ["Ottawa", "Hamilton"], "Toronto is Ontario's capital. Ottawa is the capital of the whole country."],
  ["Which is the capital city of Quebec?", "Quebec City", ["Montreal", "Ottawa"], "Quebec City is the capital. Montreal is the biggest city."],
  ["Which is the capital city of Nova Scotia?", "Halifax", ["Fredericton", "Charlottetown"], "Halifax is on the Atlantic coast."],
  ["Which is the capital city of New Brunswick?", "Fredericton", ["Halifax", "St. John's"], "Fredericton is the capital of New Brunswick."],
  ["Which is the capital city of Prince Edward Island?", "Charlottetown", ["Halifax", "Fredericton"], "Charlottetown is on Canada's smallest province."],
  ["Which is the capital city of Newfoundland and Labrador?", "St. John's", ["Halifax", "Charlottetown"], "St. John's is the easternmost capital in Canada."],
  ["Which is the capital city of Yukon?", "Whitehorse", ["Yellowknife", "Iqaluit"], "Whitehorse is the capital of Yukon."],
  ["Which is the capital city of the Northwest Territories?", "Yellowknife", ["Whitehorse", "Iqaluit"], "Yellowknife is on Great Slave Lake."],
  ["Which is the capital city of Nunavut?", "Iqaluit", ["Yellowknife", "Whitehorse"], "Iqaluit is on Baffin Island."],
  ["How many provinces does Canada have?", "10", ["3", "13"], "Canada has ten provinces and three territories."],
  ["How many territories does Canada have?", "3", ["10", "5"], "Yukon, the Northwest Territories and Nunavut."],
  ["Which of these is a territory?", "Nunavut", ["Manitoba", "Ontario"], "Nunavut is one of Canada's three territories, in the north."],
  ["Which of these is a province?", "Manitoba", ["Yukon", "Nunavut"], "Manitoba is a province. Yukon and Nunavut are territories."],
  ["Which province is directly west of Manitoba?", "Saskatchewan", ["Ontario", "Alberta"], "Saskatchewan shares Manitoba's western border."],
  ["Which province is directly east of Manitoba?", "Ontario", ["Saskatchewan", "Quebec"], "Ontario shares Manitoba's eastern border."],
  ["Which territory is north of Manitoba?", "Nunavut", ["Yukon", "Alberta"], "Nunavut touches Manitoba's northern border."],
  ["Which ocean is on Canada's west coast?", "Pacific Ocean", ["Atlantic Ocean", "Arctic Ocean"], "The Pacific Ocean is next to British Columbia."],
  ["Which ocean is on Canada's east coast?", "Atlantic Ocean", ["Pacific Ocean", "Arctic Ocean"], "The Atlantic Ocean is next to Nova Scotia and Newfoundland."],
  ["Which ocean is on Canada's north coast?", "Arctic Ocean", ["Pacific Ocean", "Atlantic Ocean"], "The Arctic Ocean is the icy ocean in the north."],
  ["Canada is north of which country?", "the United States", ["Mexico", "Brazil"], "The United States is Canada's neighbour to the south."],
  ["On a map, which direction is usually at the top?", "north", ["south", "east"], "North is toward the top of most maps."],
  ["The direction between north and east is…", "northeast", ["southwest", "northwest"], "Intermediate directions mix two cardinal directions."],
  ["The direction between south and west is…", "southwest", ["northeast", "southeast"], "South and west together make southwest."],
  ["Manitoba is in which part of Canada?", "the middle", ["the far east", "the far north"], "Manitoba is in the centre of Canada, between the Pacific and Atlantic oceans.", true],
  ["Which letter on a compass rose points east?", "E", ["N", "W"], "N, E, S and W stand for the four cardinal directions.", true],
  ["Going from Winnipeg to Regina, you travel mostly…", "west", ["east", "north"], "Saskatchewan is west of Manitoba.", true],
  ["Going from Winnipeg to Toronto, you travel mostly…", "east", ["west", "south"], "Ontario is east of Manitoba.", true],
  ["Which province is on the Atlantic coast?", "Nova Scotia", ["Alberta", "Manitoba"], "Nova Scotia has Atlantic coastline. Alberta and Manitoba have none.", true],
];

const REGIONS: Q[] = [
  ["Canada has large areas called…", "geographic regions", ["time zones", "street maps"], "Each region has its own landforms, climate and plants."],
  ["Which region has the Rocky Mountains?", "Western Cordillera", ["Interior Plains", "Canadian Shield"], "The Western Cordillera is full of tall mountains in the west."],
  ["Which region is mostly flat or gently rolling grassland?", "Interior Plains", ["Western Cordillera", "Appalachian"], "The Interior Plains are also called the Prairies."],
  ["Which region is made of very old, hard rock with many lakes?", "Canadian Shield", ["Interior Plains", "Western Cordillera"], "The Canadian Shield covers about half of Canada."],
  ["Which region is found along the shores of Hudson Bay, flat and wet?", "Hudson Bay Lowlands", ["Western Cordillera", "Appalachian"], "The Hudson Bay Lowlands are marshy and low."],
  ["Which region has Canada's largest cities along the Great Lakes and the St. Lawrence River?", "Great Lakes–St. Lawrence Lowlands", ["Arctic Lowlands", "Western Cordillera"], "Many people live in this region because the land is good for farming."],
  ["Which region has old, rounded mountains in the east?", "Appalachian", ["Western Cordillera", "Interior Plains"], "The Appalachian region reaches from Quebec to Newfoundland and Labrador."],
  ["Which region is very cold and has no trees?", "Arctic", ["Interior Plains", "Great Lakes–St. Lawrence Lowlands"], "In the Arctic it is too cold for trees to grow."],
  ["A landform is…", "a natural feature of the land", ["a kind of weather", "a big city"], "Mountains, plains and valleys are landforms."],
  ["Which of these is a landform?", "mountain", ["village", "highway"], "A mountain is a natural landform."],
  ["Which of these is a landform?", "plain", ["bridge", "farm"], "A plain is a large area of flat land."],
  ["Which Canadian region is best known for growing wheat and canola?", "Interior Plains", ["Arctic", "Western Cordillera"], "The flat, fertile Prairie soil is good for crops."],
  ["Most of northern Manitoba is part of which region?", "Canadian Shield", ["Western Cordillera", "Appalachian"], "The Shield has rock, lakes and forest."],
  ["Southern Manitoba is mostly part of which region?", "Interior Plains", ["Arctic", "Appalachian"], "Southern Manitoba is mainly flat prairie."],
  ["Which region touches the Pacific Ocean?", "Western Cordillera", ["Canadian Shield", "Interior Plains"], "The mountains meet the Pacific coast."],
  ["Which of these is a major lake system in Canada?", "the Great Lakes", ["the Rocky Mountains", "the Prairies"], "The Great Lakes are shared with the United States."],
  ["Which river flows past Quebec City and Montreal?", "St. Lawrence River", ["Red River", "Mackenzie River"], "The St. Lawrence River flows to the Atlantic."],
  ["Which large body of salt water is on the northeast side of Manitoba?", "Hudson Bay", ["Lake Winnipeg", "Great Slave Lake"], "Churchill, Manitoba, is on Hudson Bay."],
  ["Which of these is a mountain range in western Canada?", "Rocky Mountains", ["Canadian Shield", "Great Lakes"], "The Rockies run through Alberta and British Columbia."],
  ["Which region would you visit to see tundra and polar bears?", "Arctic", ["Great Lakes–St. Lawrence Lowlands", "Appalachian"], "Tundra is cold land with low plants and no trees."],
  ["Climate is…", "the usual weather in a place over many years", ["today's weather only", "the height of a mountain"], "Climate describes the pattern of weather over a long time."],
  ["Which region has the mildest winters, near the Pacific coast?", "Western Cordillera", ["Arctic", "Canadian Shield"], "The coast of British Columbia is warmer in winter than the prairies."],
  ["Why is farming so common on the Interior Plains?", "The land is flat and the soil is rich", ["It is always warm", "There are tall mountains"], "Flat land and good soil help crops grow."],
  ["Why are there so few farms on the Canadian Shield?", "The rock is hard and the soil is thin", ["There is too much sand", "It is always dry"], "Crops need deep soil, and the Shield has thin soil over rock."],
  ["Which of these is an ocean?", "Arctic Ocean", ["Lake Winnipeg", "Hudson Bay"], "Oceans are the largest bodies of salt water.", true],
  ["Which of these is a lake?", "Lake Winnipeg", ["Hudson Bay", "Arctic Ocean"], "Lake Winnipeg is a freshwater lake in Manitoba.", true],
  ["Which of these is a river that flows through Manitoba?", "Red River", ["St. Lawrence River", "Fraser River"], "The Red River flows north through Winnipeg into Lake Winnipeg.", true],
  ["The Canadian Shield is mostly…", "rock, lakes and forest", ["tall mountains", "flat farmland"], "Think of a rocky, lake-filled forest.", true],
  ["Why do people say Canada has a vast and diverse geography?", "It is very large and has many different landscapes", ["It is all flat and the same", "It is very small"], "Canada has mountains, plains, forests, lakes and Arctic land.", true],
  ["Which region is the best match for “rolling hills, farms and tall grass”?", "Interior Plains", ["Western Cordillera", "Arctic"], "Rolling land with farms and grass fits the Prairies.", true],
];

const CITIZENS: Q[] = [
  ["Which animal is a national symbol of Canada?", "beaver", ["lion", "kangaroo"], "The beaver is on Canada's nickel and is a national symbol."],
  ["Which leaf is on Canada's flag?", "maple leaf", ["oak leaf", "birch leaf"], "A red maple leaf is in the middle of the flag."],
  ["Which animal is on Manitoba's coat of arms and flag?", "bison", ["lion", "kangaroo"], "The plains bison stands on Manitoba's shield."],
  ["Which is the provincial flower of Manitoba?", "prairie crocus", ["wild rose", "tulip"], "The prairie crocus blooms in early spring on the prairie."],
  ["Which is the provincial bird of Manitoba?", "great grey owl", ["snowy owl", "robin"], "The great grey owl is Manitoba's bird."],
  ["Who is shown on top of the Manitoba Legislative Building?", "the Golden Boy", ["a bison", "the Prime Minister"], "The Golden Boy is a famous gold statue in Winnipeg."],
  ["Where does Canada's Parliament meet?", "Ottawa", ["Winnipeg", "Toronto"], "The Parliament Buildings are in Ottawa."],
  ["Where does Manitoba's government meet?", "Winnipeg", ["Ottawa", "Brandon"], "The Legislative Building is in Winnipeg."],
  ["A symbol is…", "something that stands for an idea or a place", ["a type of map", "a kind of law"], "A flag is a symbol of a country."],
  ["Which day is Canada's birthday?", "July 1", ["November 11", "September 30"], "Canada Day is July 1."],
  ["Which day do we remember people who served in wars?", "Remembrance Day", ["Canada Day", "Louis Riel Day"], "It is on November 11."],
  ["Louis Riel Day in Manitoba is in which month?", "February", ["July", "November"], "It is held on the third Monday of February."],
  ["September 30 is the National Day for…", "Truth and Reconciliation", ["Canada", "Flags"], "People wear orange shirts to learn about residential schools and to show respect."],
  ["National Indigenous Peoples Day is on…", "June 21", ["July 1", "November 11"], "It celebrates the cultures and contributions of First Nations, Inuit and Métis peoples."],
  ["Which of these is a democratic ideal?", "equality", ["unfair treatment", "ignoring people"], "Equality means people are treated fairly."],
  ["Which of these is a democratic ideal?", "freedom", ["secrets", "bossing people"], "Freedoms such as speaking your mind are part of democracy."],
  ["In a democracy, people choose their leaders by…", "voting", ["fighting", "guessing"], "Citizens vote in elections."],
  ["Which levels of government does Canada have?", "municipal, provincial and federal", ["school, home and park", "north, south and east"], "Each level has different jobs."],
  ["Which level of government runs your city or town?", "municipal", ["federal", "provincial"], "A mayor and council lead a municipal government."],
  ["Who leads a city or town?", "the mayor", ["the Premier", "the Prime Minister"], "A mayor leads with a council."],
  ["Who is the leader of the Manitoba government?", "the Premier", ["the mayor", "the Prime Minister"], "The Premier leads the province."],
  ["Who is the leader of the federal government?", "the Prime Minister", ["the Premier", "the mayor"], "The Prime Minister leads Canada."],
  ["The people elected to the Manitoba Legislative Assembly are called…", "MLAs", ["MPs", "mayors"], "MLA stands for Member of the Legislative Assembly."],
  ["The people elected to represent us in Ottawa are called…", "MPs", ["MLAs", "councillors"], "MP stands for Member of Parliament."],
  ["Which level of government is mostly in charge of local roads and garbage pickup?", "municipal", ["federal", "provincial"], "Cities and towns look after local services."],
  ["Which level of government is mostly in charge of schools and health care?", "provincial", ["municipal", "federal"], "Provinces look after education and health."],
  ["Which level of government is in charge of the army and money for the whole country?", "federal", ["municipal", "provincial"], "The federal government works for all of Canada."],
  ["One purpose of government is to…", "make rules and laws", ["pick your friends", "grow your food"], "Governments make laws and provide services.", true],
  ["Which is a service governments provide?", "public schools", ["video games", "candy stores"], "Schools, roads and hospitals are public services.", true],
  ["Which is a good way to be a responsible citizen?", "Help in your community", ["Break the rules", "Ignore others"], "Citizens share and help.", true],
  ["First Nations, Métis and Inuit communities also elect…", "their own leaders", ["no one", "only a mayor"], "Many communities have a chief and council, or other elected leaders.", true],
];

const LAND: Q[] = [
  ["Which is the capital city of Manitoba?", "Winnipeg", ["Brandon", "Churchill"], "Winnipeg is the capital and the largest city."],
  ["Which large lake is in the middle of Manitoba?", "Lake Winnipeg", ["Lake Superior", "Great Bear Lake"], "Lake Winnipeg is the biggest lake that lies entirely in Manitoba."],
  ["Two rivers meet at The Forks in Winnipeg. They are the Red and the…", "Assiniboine", ["Fraser", "Mackenzie"], "The Red and Assiniboine Rivers join at The Forks."],
  ["Which Manitoba town is on Hudson Bay?", "Churchill", ["Brandon", "Steinbach"], "Churchill is famous for polar bears and beluga whales."],
  ["What animal do many visitors travel to Churchill to see?", "polar bears", ["kangaroos", "elephants"], "Polar bears gather near Hudson Bay in the fall."],
  ["Which body of water is on the northeast edge of Manitoba?", "Hudson Bay", ["Pacific Ocean", "Lake Superior"], "Manitoba is the only prairie province with a seacoast."],
  ["Which country is south of Manitoba?", "the United States", ["Mexico", "Russia"], "Manitoba borders North Dakota and Minnesota."],
  ["Which province is west of Manitoba?", "Saskatchewan", ["Ontario", "Alberta"], "Saskatchewan is the western neighbour."],
  ["Which province is east of Manitoba?", "Ontario", ["Saskatchewan", "Quebec"], "Ontario is the eastern neighbour."],
  ["Which territory is north of Manitoba?", "Nunavut", ["Yukon", "Alberta"], "Nunavut meets Manitoba's northern border."],
  ["Which is a Manitoba natural resource?", "fresh water for hydroelectric power", ["ocean oil rigs", "palm trees"], "Dams on rivers such as the Nelson make electricity."],
  ["Which Manitoba resource comes from the forest?", "lumber", ["bananas", "coral"], "Trees in northern and eastern Manitoba are cut for lumber and paper."],
  ["Which crop is grown on many Manitoba farms?", "canola", ["coffee", "rice"], "Canola and wheat are grown on the prairie farmland."],
  ["Which Manitoba resource is mined near Thompson and Flin Flon?", "metals such as nickel and copper", ["salt from the sea", "diamonds only"], "Northern Manitoba has mines."],
  ["Where do most Manitobans live?", "in the south, in and near Winnipeg", ["in the far north", "on Hudson Bay"], "About half of Manitobans live in Winnipeg."],
  ["About how many people live in Manitoba?", "about 1.4 million", ["about 14 000", "about 140 million"], "Manitoba has around one and a half million people."],
  ["Which Manitoba city is the second largest?", "Brandon", ["Churchill", "Gimli"], "Brandon is in the southwest."],
  ["What is a population?", "the number of people who live in a place", ["the height of a hill", "a kind of weather"], "Population means how many people live there."],
  ["What is Riding Mountain?", "a national park", ["a city", "a lake"], "Riding Mountain National Park has forest, lakes and wildlife such as bison."],
  ["Which of these is a landform in southern Manitoba?", "prairie", ["glacier", "volcano"], "Prairie is flat grassland."],
  ["Which Manitoba region is covered in rock, lakes and forests?", "the Canadian Shield", ["the Rocky Mountains", "the Great Lakes"], "East and north of Lake Winnipeg is Shield country."],
  ["Which of these helps protect Manitoba's environment?", "recycling and saving water", ["leaving garbage in parks", "wasting energy"], "Stewardship means caring for the land and water."],
  ["Stewardship means…", "taking care of something that belongs to everyone", ["owning all the land", "using as much as you can"], "Stewardship is caring for the environment for the future."],
  ["Manitoba's rivers and lakes are used to…", "make electricity, travel and fish", ["grow bananas", "mine diamonds only"], "Water is a very important Manitoba resource."],
  ["A natural resource is…", "something from nature that people use", ["a thing made in a factory", "a kind of game"], "Water, soil, trees and minerals are natural resources.", true],
  ["Why do farms in southern Manitoba do well?", "The soil is rich and the land is flat", ["It is a desert", "It is a mountain"], "Rich prairie soil helps crops grow.", true],
  ["First Nations peoples in Manitoba have cared for the land for…", "thousands of years", ["only a few years", "one season"], "Many Indigenous peoples continue to care for and use the land.", true],
  ["Why do places of environmental importance need protecting?", "They have special plants, animals or water", ["They are far away", "They are boring"], "Parks protect wildlife and natural places.", true],
  ["Which would be a good way to look after a Manitoba lake?", "Keep garbage and chemicals out of the water", ["Pour old paint in it", "Dump trash on the shore"], "Clean water is good for fish, animals and people.", true],
];

const PEOPLE: Q[] = [
  ["Manitoba is home to people from…", "many cultures", ["only one culture", "no cultures"], "Manitoba is diverse. People come from many places."],
  ["Which languages are spoken by First Nations in Manitoba?", "Cree, Ojibwe and Dakota", ["Greek and Latin", "Hawaiian and Maori"], "Some First Nations languages in Manitoba include Cree, Ojibwe, Dakota, Dene and Oji-Cree."],
  ["Michif is a language of…", "the Métis", ["the Vikings", "the Romans"], "Michif is a language that combines Cree and French."],
  ["Which peoples lived on the Prairies long before Europeans arrived?", "First Nations", ["Vikings", "Romans"], "First Nations peoples have lived on this land for thousands of years."],
  ["The Métis are…", "a people with both First Nations and European roots", ["a kind of animal", "visitors from space"], "The Métis have their own history, culture and language."],
  ["Inuit traditionally come from…", "the Arctic", ["the Prairies", "the Great Lakes"], "Some Inuit live in Manitoba too, especially in Winnipeg and Churchill."],
  ["Where is the largest French-speaking community in Manitoba?", "Saint-Boniface in Winnipeg", ["Churchill", "Flin Flon"], "Saint-Boniface is the historic French community."],
  ["Which festival celebrates French-Métis voyageur culture in Winnipeg every February?", "Festival du Voyageur", ["Folklorama", "Canada Day"], "Festival du Voyageur has snow sculptures and fiddle music."],
  ["Which August festival in Winnipeg shows off many cultures?", "Folklorama", ["Festival du Voyageur", "Remembrance Day"], "Folklorama has pavilions for cultures from all over the world."],
  ["Which town in Manitoba is known for its Icelandic heritage?", "Gimli", ["Churchill", "Thompson"], "Gimli is on Lake Winnipeg, and its Icelandic festival happens in August."],
  ["Many Ukrainian Canadians came to farm the Prairies. Which food is a traditional Ukrainian dish?", "perogies", ["sushi", "tacos"], "Perogies are filled dumplings."],
  ["Which kind of dancing is Métis?", "jigging", ["ballet only", "polka only"], "Métis jigging is a lively fiddle dance."],
  ["Which cloth belt is a Métis symbol?", "the sash", ["the kilt", "the sari"], "The ceinture fléchée, or Métis sash, is a colourful woven belt."],
  ["A cultural community is…", "a group of people who share a heritage", ["a group of buildings", "a type of weather"], "A culture includes language, food, music and traditions."],
  ["What is an Elder?", "a respected person who shares teachings", ["a kind of tree", "a type of boat"], "Elders pass on knowledge to young people."],
  ["Why do we learn from oral traditions?", "People pass on history by telling stories", ["Stories have no meaning", "Nobody writes anything"], "Storytelling is an important way to keep history."],
  ["Which of these are artistic achievements?", "painting, music and dance", ["rain and snow", "mountains and lakes"], "Art is created by people."],
  ["The Royal Winnipeg Ballet is famous for…", "dance", ["farming", "mining"], "It is one of Canada's best-known dance companies."],
  ["The Canadian Museum for Human Rights is in…", "Winnipeg", ["Churchill", "Brandon"], "It is a national museum in Winnipeg at The Forks."],
  ["What does diversity mean?", "differences among people", ["everyone is the same", "being alone"], "Diversity is the different cultures and backgrounds in a community."],
  ["Which is a respectful way to learn about other cultures?", "Listen and ask kind questions", ["Make fun of them", "Ignore them"], "Respect helps communities get along."],
  ["Many people from the Philippines have made their home in…", "Winnipeg", ["Churchill", "Gimli only"], "Winnipeg has one of Canada's largest Filipino communities."],
  ["Some Mennonite families came to Manitoba to…", "farm and live in peace", ["fish in the sea", "mine gold"], "Many Mennonite communities began in southern Manitoba in the 1870s."],
  ["Which of these shows respect for people's identity?", "Using someone's name correctly", ["Teasing about their name", "Ignoring them"], "Names are an important part of who we are.", true],
  ["Many cultures bring new foods, music and celebrations to Manitoba. This is called…", "cultural contributions", ["weather changes", "map making"], "Each culture adds something to the community.", true],
  ["Cree, Dene, Ojibwe, Dakota and Oji-Cree are…", "different First Nations languages", ["kinds of tools", "kinds of berries"], "They are languages that are still spoken in Manitoba today.", true],
  ["Why is it important to say that First Nations, Métis and Inuit peoples are living communities?", "They are here today, not just in the past", ["They are all gone", "They live in books"], "These peoples continue to live, work and lead in Manitoba.", true],
  ["Your identity can be shaped by…", "family, culture and place", ["only the weather", "only your age"], "Identity comes from many things in your life.", true],
  ["Which sentence is a respectful way to talk about people?", "Many First Nations have their own languages.", ["All Nations are exactly the same.", "They are all from long ago."], "Each Nation is different, and they are all still here.", true],
];

const STORY: Q[] = [
  ["Voyageurs were…", "fur-trade canoe travellers", ["airline pilots", "railway workers"], "They paddled birchbark canoes to carry furs and goods."],
  ["What did voyageurs use to travel on rivers?", "canoes", ["trucks", "skateboards"], "Rivers were the highways of the fur trade."],
  ["What was the main thing traded in the fur trade?", "furs", ["computers", "cars"], "Beaver fur was popular for hats in Europe."],
  ["What was the Hudson's Bay Company?", "a fur-trading company", ["a school", "a hockey team"], "It set up trading posts, such as York Factory."],
  ["Why did people build forts at river meeting points?", "Rivers were the best way to travel and trade", ["There were no rivers", "To keep cattle"], "Waterways were the routes people used."],
  ["The Red River and the Assiniboine River meet at…", "The Forks", ["Churchill", "Brandon"], "People have met and traded at The Forks for thousands of years."],
  ["Who were the Selkirk settlers?", "families from Scotland who settled at the Red River", ["Vikings", "Romans"], "They arrived in 1812 and started the Red River Colony."],
  ["Which year did the first Selkirk settlers arrive?", "1812", ["1612", "1912"], "The Selkirk settlers came to the Red River in 1812."],
  ["Who helped the Selkirk settlers survive their first winters?", "First Nations and Métis neighbours", ["no one", "robots"], "Chief Peguis and others shared food and knowledge."],
  ["Chief Peguis was a leader of…", "the Saulteaux (Ojibwe) near the Red River", ["the Vikings", "Parliament"], "He helped the newcomers and is remembered in Manitoba."],
  ["What was pemmican?", "dried meat, fat and berries", ["a kind of boat", "a kind of hat"], "Métis hunters made pemmican to feed the fur traders."],
  ["Which vehicle did the Métis use to carry buffalo meat and furs?", "the Red River cart", ["a bus", "an aeroplane"], "These wooden carts made a loud squeaking sound."],
  ["Who was Louis Riel?", "a Métis leader and founder of Manitoba", ["a hockey player", "a scientist"], "Riel led the Red River Resistance and helped bring Manitoba into Canada."],
  ["In what year did Manitoba become a province?", "1870", ["1670", "1970"], "Manitoba joined Canada in 1870."],
  ["Manitoba started as a very small province. People called it…", "the postage stamp province", ["the giant province", "the island province"], "It was small at first and grew larger later.", true],
  ["Why did the Métis want a say in how Red River was governed?", "They wanted their rights and land protected", ["They wanted to leave Canada for Mars", "They did not care"], "Riel and the Métis wanted a voice and rights.", true],
  ["What do we call a story passed down by speaking?", "oral tradition", ["a mapped route", "an encyclopedia"], "Oral history is an important way to learn the past."],
  ["Which was the earliest way people travelled Manitoba's rivers?", "birchbark canoes", ["motorboats", "jet skis"], "Indigenous peoples built canoes long before Europeans arrived."],
  ["Why did people settle near rivers and lakes?", "For food, water and travel", ["Rivers had no use", "To avoid fish"], "Water gave people what they needed."],
  ["Why did many farmers settle in southern Manitoba?", "The land was flat and the soil was rich", ["It was frozen all year", "There was no land"], "Good farmland drew settlers."],
  ["What helped bring many settlers to the Prairies in the late 1800s?", "the railway", ["the aeroplane", "the Internet"], "Trains carried people and goods across the country."],
  ["Which change happened in Manitoba over time?", "Houses changed from log cabins to modern homes", ["Winters became summers", "Rivers moved to Ontario"], "Life in Manitoba has changed in many ways."],
  ["How did people write letters long ago?", "by hand with pen and paper", ["with a phone", "with email"], "Communication has changed a lot."],
  ["A timeline shows…", "events in the order they happened", ["a map's directions", "the weather today"], "A timeline puts events in order."],
  ["Which came first?", "The fur trade", ["The Internet", "The railway"], "Fur trading began long before the railway or Internet."],
  ["Which came first?", "The Selkirk settlers' arrival", ["Manitoba becoming a province", "The Internet"], "1812 came before 1870.", true],
  ["Why do we share stories about Manitoba's past?", "To learn how we got here and to honour people", ["To forget the past", "To avoid learning"], "History helps us understand today.", true],
  ["Many place names in Manitoba come from…", "First Nations languages", ["Roman words only", "space"], "Manitoba itself is an Indigenous name, with roots in Cree and Ojibwe.", true],
  ["Settlement of newcomers changed life for First Nations and Métis peoples. This was often…", "a big change, and sometimes unfair", ["no change at all", "always peaceful"], "Newcomers' arrival changed land, treaties and ways of life.", true],
];

export const units = [
  bankUnit({
    id: "mb-canada-map",
    title: "Provinces, Territories & Capitals",
    emoji: "🗺️",
    blurb: "Find places on a map of Canada",
    parentNote:
      "Practises locating Canada's provinces, territories and capital cities, naming the three oceans, Manitoba's neighbours, and using cardinal and intermediate directions on a map.",
    standards: ["4-KL-015, 4-KL-019, 4-S-207", "Manitoba's place in Canada, provinces, territories and capitals, and directions on a map"],
    items: MAP,
  }),
  bankUnit({
    id: "mb-canada-regions",
    title: "Canada's Regions",
    emoji: "⛰️",
    blurb: "Landforms, lakes and the land from coast to coast",
    parentNote:
      "Practises the geographic regions of Canada, such as the Western Cordillera, the Interior Plains and the Canadian Shield, what each is like, and major landforms and bodies of water.",
    standards: ["4-KL-016, 4-KL-017, 4-KL-018, 4-VL-005", "geographic regions of Canada, their landforms and climate, and major lakes, rivers and oceans"],
    items: REGIONS,
  }),
  bankUnit({
    id: "mb-canadian-citizens",
    title: "Citizens & Governments",
    emoji: "🏛️",
    blurb: "Symbols, special days and who does what",
    parentNote:
      "Practises Canadian and Manitoba symbols, days important to Canadians and Manitobans, democratic ideals, and the municipal, provincial and federal levels of government and their leaders.",
    standards: ["4-KC-001, 4-KC-002, 4-KC-003, 4-KP-041, 4-KP-042, 4-KP-043", "symbols and special days, democratic ideals, and the purposes and levels of government"],
    items: CITIZENS,
  }),
  bankUnit({
    id: "mb-manitoba-land",
    title: "Manitoba's Land & Resources",
    emoji: "🦬",
    blurb: "Lakes, rivers, farms and how we care for them",
    parentNote:
      "Practises Manitoba's geography: its lakes, rivers and cities, neighbours, natural resources, where people live, and caring for the environment.",
    standards: ["4-KL-020, 4-KL-021, 4-KL-022, 4-KL-023", "geographic features, natural resources and population of Manitoba, and environmental stewardship"],
    items: LAND,
  }),
  bankUnit({
    id: "mb-manitoba-people",
    title: "Manitoba's Peoples & Cultures",
    emoji: "🎶",
    blurb: "Communities, languages and celebrations",
    parentNote:
      "Practises the First Nations, Métis, Inuit, francophone and many other cultural communities of Manitoba, their languages, arts and festivals, and respectful ways to learn about one another.",
    standards: ["4-KI-005, 4-KI-006, 4-KI-007, 4-KI-008, 4-KI-010", "cultural communities in Manitoba, their artistic achievements, and First Nations, Métis, Inuit and francophone communities"],
    items: PEOPLE,
  }),
  bankUnit({
    id: "mb-manitoba-story",
    title: "Manitoba's Story",
    emoji: "🛶",
    blurb: "Voyageurs, settlers and how Manitoba began",
    parentNote:
      "Practises the story of how Manitoba grew: the fur trade, the Selkirk settlers, the Métis and Louis Riel, how the land shaped where people settled, and how life has changed.",
    standards: ["4-KL-026, 4-KL-027, 4-KH-033, 4-KH-035", "how the land shaped settlement, stories of the Selkirk settlers and people who shaped Manitoba, and change over time"],
    items: STORY,
  }),
];
