import { bankUnit, type Q } from "../own";

// More Grade 5 social studies, The Mosaic of Canada: map and land skills, research and evidence, working together
// respectfully, and the values of citizenship. Indigenous content is in the present tense, says "many" or "some"
// and stays general.

const MAPS: Q[] = [
  ["Which map feature tells you what the symbols mean?", "legend", ["title", "scale"], "The legend explains symbols."],
  ["Which map feature shows directions?", "compass rose", ["legend", "grid"], "It points north, south, east and west."],
  ["Which map feature tells the subject of the map?", "title", ["scale", "grid"], "Read the title first."],
  ["What does a map scale show?", "how map distances match real distances", ["the colours", "the date"], "1 cm might be 10 km."],
  ["A map grid uses…", "letters and numbers to find a place", ["only colours", "only symbols"], "Look up the column, then the row."],
  ["A map has a scale where 1 cm is 10 km. Two towns are 4 cm apart. How far apart are they?", "40 km", ["14 km", "4 km"], "4 × 10 = 40."],
  ["A map has a scale where 1 cm is 5 km. Two lakes are 6 cm apart. How far apart are they?", "30 km", ["11 km", "6 km"], "6 × 5 = 30."],
  ["If north is at the top of the map, east is on the…", "right", ["left", "bottom"], "East is to the right."],
  ["If north is at the top of the map, west is on the…", "left", ["right", "top"], "West is to the left."],
  ["Which direction is opposite south?", "north", ["east", "west"], "North and south are opposites."],
  ["Which would you use to find the direction to walk without a map?", "a compass", ["a ruler", "a clock"], "The needle points to magnetic north."],
  ["The Sun rises in the…", "east", ["west", "north"], "It sets in the west."],
  ["At midday in Manitoba, shadows point toward the…", "north", ["south", "east"], "The Sun is in the southern sky in the middle of the day."],
  ["Which helps you orient yourself outdoors?", "noticing landmarks such as a river or a hill", ["closing your eyes", "ignoring the land"], "Landscape clues help you find your way."],
  ["Many Indigenous Peoples have used knowledge of the land, such as river flow, stars and animal signs, to travel. This is called…", "Traditional Knowledge", ["a guess", "a game"], "It is built up over many generations."],
  ["Reading the land can include noticing…", "plants, animals, water and the weather", ["only buildings", "nothing"], "Close observation shows where you are."],
  ["Which kind of map shows traditional territories of First Peoples?", "a map of Indigenous territories", ["a weather map", "a road map of one city"], "Traditional territories are shown on special maps."],
  ["First Peoples' traditional territories…", "do not follow modern provincial borders", ["are the same as provinces", "do not exist"], "Their lands were known long before provinces."],
  ["Which map would you use to see where the Red River and Lake Winnipeg are?", "a map of Manitoba", ["a map of a school gym", "a map of the Moon"], "Choose a map that fits your question."],
  ["A good map you make includes…", "a title, legend, compass rose, grid and scale", ["only colours", "only a border"], "Those five are the key features."],
  ["Why include a legend on your map of a park?", "so readers know what each symbol means", ["to fill the page", "to hide the map"], "Symbols need explaining.", true],
  ["You draw a map of your classroom. What should the scale show?", "how many steps or metres each square stands for", ["the date", "the weather"], "A scale makes the map to size.", true],
  ["Which grid reference means column C, row 3?", "C3", ["3C is always wrong", "33"], "Name the column first, then the row.", true],
  ["You can't see the Sun and have no compass. Which clue could still help you find north?", "moss, shadows and landmarks together with other signs", ["a single guess", "the colour of your coat"], "Use several clues, not just one.", true],
  ["Why is a compass useful on a cloudy day?", "it still points to magnetic north", ["it makes the sky clear", "it shows the time"], "A compass works without the Sun.", true],
  ["Which tool is most helpful for moving across land you do not know?", "a map and a compass together", ["a clock only", "a ruler only"], "Combine tools.", true],
];

export const maps = bankUnit({
  id: "mb-maps-and-land-5",
  title: "Maps, Directions and Reading the Land",
  emoji: "🧭",
  blurb: "Build maps and find your way",
  parentNote: "Reading and making maps with a title, legend, compass rose, grid and scale; finding direction with a compass, landmarks and Traditional Knowledge; and where First Peoples' traditional territories appear on maps.",
  standards: ["5-KL-016, 5-S-205, 5-S-207A, 5-S-208", "traditional territories on maps, making maps, reading the land and finding direction"],
  items: MAPS,
});

const INQUIRY: Q[] = [
  ["Historical inquiry begins with…", "a question you want to answer", ["the answer", "a vote"], "Plan your topic and goals first."],
  ["Which is a good research question for Grade 5?", "Why did the fur trade matter to Manitoba?", ["What is history?", "Is it fun?"], "A strong question is focused and has answers to find."],
  ["Which is a primary source?", "a letter written by a trader at a fort", ["a textbook written today", "a movie made last year"], "Primary sources come from the time."],
  ["Which is a secondary source?", "a book written by a historian today", ["a diary from 1850", "a photograph taken in 1850"], "Secondary sources are written later."],
  ["An artifact is…", "an object made and used by people in the past", ["a story", "a new toy"], "Artifacts tell us how people lived."],
  ["What can a photograph show a historian?", "how a place and people looked at the time", ["what people were thinking", "the future"], "Look closely and ask questions."],
  ["A good way to study an artifact is to ask…", "what is it made of and how might it have been used?", ["what does it cost now?", "who is my friend?"], "Observe the material and use."],
  ["Which source is a work of art that may show history?", "a painting of a settlement", ["a shopping list from today", "a sports score"], "Art can show how people saw things."],
  ["Songs, legends and oral histories are sources because…", "they carry knowledge and stories from the past", ["they are not real", "they are always wrong"], "Many communities keep history through stories."],
  ["Which tool can help you organize research?", "a concept map", ["a calculator", "a ruler"], "Maps and charts organize ideas."],
  ["What should you record when you take notes?", "the key ideas and where you found them", ["every word on the page", "nothing"], "Reference sources properly."],
  ["Which is a good place to look up a Canadian historical fact?", "a trusted library book or museum website", ["a rumour", "a chat message"], "Choose reliable sources."],
  ["Which technology helps with research?", "a digital library catalogue", ["a flashlight", "a rubber band"], "Choose the right tool for the task."],
  ["Drawing a conclusion means…", "making a statement that the evidence supports", ["guessing", "copying a friend"], "Conclusions follow from evidence."],
  ["Three sources say the fort opened in 1820. What can you conclude?", "the fort most likely opened in 1820", ["nobody knows", "the fort was never built"], "Agreement among sources strengthens it."],
  ["Interpretations of history may change when…", "new information is found", ["people forget", "the calendar changes"], "Our understanding grows."],
  ["A new discovery shows that a village was larger than people thought. Historians…", "update what they say about the past", ["ignore it", "hide it"], "History is revised with evidence."],
  ["You believed a story was true, then found a source showing a different fact. A good historian…", "reconsiders what they believed", ["insists they were right", "stops researching"], "Test your assumptions against new information."],
  ["Which statement is an assumption?", "People in the past were all the same.", ["The fort was built in 1820.", "The river flows north."], "An assumption is not backed by evidence."],
  ["When a solution has an advantage and a disadvantage, you should…", "weigh both before choosing", ["only count the advantage", "choose at random"], "Evaluate the pros and cons."],
  ["A town could build a new bridge. An advantage is faster travel. A disadvantage might be…", "the cost and the effect on the river", ["the bridge's colour", "the day of the week"], "List both sides.", true],
  ["Which pair is a source and its reliable use?", "a museum's artifact label used to learn when an object was made", ["a rumour used for dates", "a joke used for facts"], "Reliable labels cite evidence.", true],
  ["Fact versus opinion: which is an opinion?", "Canada's winters are the hardest to live through.", ["Winnipeg is in Manitoba.", "Lake Winnipeg is large."], "An opinion tells what someone feels.", true],
  ["Two accounts of the same event differ. What helps you decide?", "who wrote each, when, and what evidence they used", ["which is longer", "which is more colourful"], "Evaluate the source.", true],
  ["You look at an old map from a trader. What question helps you analyze it?", "Who made this map and for what purpose?", ["What is the paper's price?", "Who likes maps?"], "Think about the maker's perspective.", true],
  ["A historical fiction book is a useful source if you remember that…", "the story is made up from real history and may add details", ["every detail is real", "it has no connection to history"], "Check the facts in other sources.", true],
];

export const inquiry = bankUnit({
  id: "mb-history-inquiry-5",
  title: "Be a History Detective",
  emoji: "🔍",
  blurb: "Ask questions, check sources and weigh the evidence",
  parentNote: "Planning historical inquiry, choosing and organizing sources including artifacts, art and stories, drawing conclusions from evidence and understanding that interpretations can change.",
  standards: ["5-S-200, 5-S-201, 5-S-203, 5-S-300, 5-S-301, 5-S-302, 5-S-303, 5-S-305, 5-S-309, 5-S-310", "planning inquiry, selecting and organizing sources, evaluating evidence and changing interpretations"],
  items: INQUIRY,
});

const TOGETHER: Q[] = [
  ["Listening to understand means…", "paying attention to the speaker's point of view", ["planning what you will say", "talking louder"], "Listen before you respond."],
  ["Which phrase shows you listened?", "So you're saying…", ["I'm not listening.", "Whatever."], "Restating shows understanding."],
  ["Which sentence uses respectful language about people?", "People in Canada come from many cultures.", ["Those people are all the same.", "Some groups are better."], "Respectful language values diversity."],
  ["Which word is respectful when talking about a person with a disability?", "a person who uses a wheelchair", ["a victim of a wheelchair", "a crippled person"], "Put the person first."],
  ["Which is better to say about a classmate's idea?", "I think a different idea might work, and here is why.", ["That's stupid.", "You never get it."], "Disagree with reasons."],
  ["Why should you support your opinion with information?", "so others can see why you think it", ["to sound louder", "to end the talk"], "Reasons make opinions stronger."],
  ["Which opinion is supported?", "The park needs a new bench because three people stand while they wait for the bus.", ["The park needs a bench.", "Benches are good."], "It gives a reason."],
  ["A classmate says something that is hard to understand. You…", "ask a clarifying question", ["laugh", "walk away"], "Clarify with kindness."],
  ["Which is a clarifying question?", "Can you tell me more about what you mean?", ["Why are you here?", "Who asked you?"], "It invites more explanation."],
  ["In a group, how do you share ideas fairly?", "take turns and let everyone speak", ["let one person talk", "talk over others"], "Everyone's voice counts."],
  ["Consensus means…", "the group agrees on a decision", ["one person decides", "everyone leaves"], "People work toward agreement."],
  ["Two group members want different ideas. A good first step is to…", "listen to each reason and look for a plan that works for both", ["vote without talking", "stop the project"], "Negotiate constructively."],
  ["Negotiating means…", "talking to find a solution that works for everyone", ["winning an argument", "refusing to talk"], "Give and take."],
  ["A friend has a different belief from yours. A respectful response is to…", "listen and say you see it differently", ["tease them", "ignore them"], "Respect differences."],
  ["Respecting the rights of others includes…", "letting people have their say", ["interrupting", "ignoring them"], "Everyone has the right to be heard."],
  ["Which is a way to present a research finding?", "a poster, a talk or a slideshow", ["only hide it", "never share it"], "Present orally, visually, concretely or electronically."],
  ["What is a concrete way to show how a fort looked?", "build a model", ["say nothing", "guess"], "Concrete means something you can touch."],
  ["Which belief statement states a perspective clearly?", "I believe everyone should help keep our river clean because we all use it.", ["River.", "Clean."], "State your belief and a reason.", true],
  ["In a discussion, you want to be sure you understand. You…", "paraphrase and ask if you got it right", ["interrupt", "agree with everything"], "Check meaning.", true],
  ["A classmate is shy. How can the group include them?", "invite their idea and wait kindly", ["tell them to hurry", "skip them"], "Make space for others.", true],
  ["Which option best builds consensus?", "list each person's ideas and combine the best parts", ["pick the loudest voice", "flip a coin without talking"], "Combine ideas.", true],
  ["A spokesperson for your group should…", "share the group's ideas, not just their own", ["share only their own idea", "stay silent"], "They represent the group.", true],
  ["Which question helps a group solve a problem?", "What else could we try?", ["Why are you wrong?", "Can we stop?"], "Keep ideas flowing.", true],
  ["When you state an opinion on an issue, you should also say…", "the reasons or facts behind it", ["nothing more", "that others are wrong"], "Evidence supports a belief.", true],
];

export const together = bankUnit({
  id: "mb-respectful-talk-5",
  title: "Listen, Share and Solve Together",
  emoji: "🤝",
  blurb: "Respectful words, fair groups and clear opinions",
  parentNote: "Listening to others, using language that respects diversity, supporting ideas with information, negotiating to reach agreement and presenting ideas in different ways.",
  standards: ["5-VC-001, 5-S-104, 5-S-400, 5-S-401, 5-S-402, 5-S-403, 5-S-404, 5-S-405", "respecting others, listening, respectful language, supporting opinions, negotiating and presenting ideas"],
  items: TOGETHER,
});

const VALUES: Q[] = [
  ["Which action shows being willing to contribute to a group?", "doing your part in a class project", ["letting others do it all", "refusing to help"], "Contribute to your community."],
  ["Which is a way to contribute to your community?", "helping at a neighbourhood cleanup", ["leaving litter", "staying away"], "Community matters."],
  ["Canadian history and geography help shape…", "who we are and where we feel we belong", ["only the weather", "nothing"], "Our past and places are part of our identity."],
  ["Which places might be part of someone's identity?", "the river, town or land they grew up on", ["a random number", "a colour"], "Places matter to people."],
  ["Many different communities have contributed to Canada, including…", "First Nations, Inuit, Métis, French, British and many other cultural communities", ["only one group", "no one"], "Canada is a mosaic of peoples."],
  ["Which of these is a contribution to Canada's culture?", "foods, songs and stories from many communities", ["one language only", "one holiday only"], "Culture is shared and changes."],
  ["Many Canadians have family connections to places around the world. Which of these shows that connection?", "a family celebrating a holiday from their home country", ["nobody has connections", "everyone is from one place"], "Connections link people."],
  ["Why is it good to learn about the places Canadians come from?", "it helps us understand each other", ["it is a waste", "it ends friendships"], "Understanding builds respect."],
  ["Which decision shows care for the environment?", "picking up litter on a trail", ["dropping litter", "ignoring a spill"], "Care for the land and water."],
  ["Which choice is the most responsible for the environment?", "turning off lights when you leave a room", ["leaving the tap running", "leaving lights on all night"], "Small habits add up."],
  ["A class reduces waste at lunch. This shows…", "responsibility for the environment", ["carelessness", "no effect"], "Taking action matters."],
  ["Burial grounds, memorials and old artifacts deserve…", "respect", ["a shovel", "a game"], "They are important to the people connected to them."],
  ["You find an old tool in a field on a school trip. What is the respectful thing to do?", "leave it and tell your teacher", ["take it home", "break it"], "Artifacts should not be taken."],
  ["Why are places of historical significance protected?", "they help us understand and remember the past", ["they are old", "they are boring"], "History is worth keeping."],
  ["Some land can be used for farming, for housing or kept as a natural area. Being willing to consider diverse approaches means…", "listening to the different ideas people have", ["picking one right away", "ignoring ideas"], "Think about many views before deciding."],
  ["Many First Nations value caring for the land for future generations. This is an example of…", "an approach to land use that looks to the future", ["a way to avoid thinking", "a rule about games"], "It is a way of living with the land.", true],
  ["Why is it important to hear from the people who live on the land when deciding how to use it?", "they know it well and will be affected by the choice", ["they do not matter", "so decisions go faster"], "Include those most affected.", true],
  ["A school can choose to recycle, compost or both. Which approach shows consideration of many views?", "ask students, families and staff before choosing", ["decide without asking", "ignore the plan"], "Consult before deciding.", true],
  ["Which statement shows appreciating history?", "Knowing how my community began helps me understand where I live.", ["History is useless.", "The past doesn't matter."], "History informs identity.", true],
  ["Telling a person's story respectfully means…", "using their own words and not changing what they said", ["making things up", "leaving out the person's name"], "Be accurate and fair.", true],
  ["A museum shows First Peoples' stories of early contact with Europeans. Why does it share these stories?", "they give another view of what happened", ["to confuse visitors", "they are not important"], "Many perspectives make history fuller.", true],
  ["Why is it good for Canadians to share traditions from different cultures?", "it helps everyone learn from each other", ["it ends traditions", "it makes people the same"], "Sharing builds understanding.", true],
  ["Which is an example of acting on a value of caring for the environment?", "choosing to walk to school when you can", ["throwing garbage in a river", "leaving the car running"], "Actions show values.", true],
  ["Which belief best fits being a good citizen?", "I contribute to my community and respect others' rights.", ["I only think about me.", "Rules are for others."], "Citizenship is about shared responsibility.", true],
];

export const citizenship = bankUnit({
  id: "mb-citizens-and-values-5",
  title: "Citizens, Places and Caring",
  emoji: "🌎",
  blurb: "Contribute, care and respect the past",
  parentNote: "Values of citizenship: contributing to groups and communities, valuing the many peoples who shaped Canada, caring for the environment, respecting historic places and considering different approaches to land use.",
  standards: ["5-KH-024, 5-VC-002, 5-VE-015, 5-VG-013, 5-VI-004, 5-VI-005, 5-S-103, 5-S-106", "contributing to community, the peoples who shaped Canada, caring for the environment and respecting historic places"],
  items: VALUES,
});
