import { bankUnit, type Q } from "../own";

// More Grade 5 English language arts (ELA.5): planning and researching, revising and spelling, diversity and bias,
// multisyllabic words, reading with purpose, multimodal texts, discussion language and setting learning goals.
// Purely oral and presentation outcomes are left to the classroom.

const PLAN: Q[] = [
  ["Which topic is focused enough for a one-page report?", "How beavers build a lodge", ["Animals", "Everything about nature"], "A focused topic is small enough to cover well."],
  ["Before writing, you jot down ideas in a web. This strategy is called…", "mind mapping", ["proofreading", "skimming"], "A mind map links ideas around a centre."],
  ["Who is a report's audience?", "the people who will read it", ["the pencil used to write it", "the title only"], "Writers choose words for their readers."],
  ["Which purpose does a persuasive letter have?", "to convince the reader", ["to tell a joke only", "to list a recipe"], "Persuasive writing tries to change a mind."],
  ["Which source is the best for facts about wolves?", "a nonfiction book by a wildlife biologist", ["a rumour from a friend", "a cartoon"], "Choose sources written by experts."],
  ["Jot notes are…", "short words and phrases that record key ideas", ["a finished paragraph", "a long copy of the page"], "Notes use your own words."],
  ["Why should you write down where each fact came from?", "so you can check it and give credit", ["to make the report longer", "so nobody reads it"], "Recording sources is part of honest research."],
  ["Which question is open-ended?", "Why do some birds fly south in the fall?", ["Is a robin a bird?", "Do birds have wings?"], "Open-ended questions start with why or how."],
  ["Which question needs more than one source to answer well?", "How has farming on the Prairies changed over 100 years?", ["What colour is wheat?", "What is 4 + 4?"], "Big questions need several sources."],
  ["You notice your notes say nothing about where an animal lives. What do you do?", "find more information about its habitat", ["leave the gap and hope", "skip the animal"], "Reviewing notes helps you spot gaps."],
  ["A good way to plan before drafting is to…", "put your ideas in order in an outline", ["start with the last sentence", "copy a web page"], "An outline shows what comes first, next and last."],
  ["Which is an expert you could ask about trees?", "a forester", ["a stranger online", "a classmate who has never read about them"], "Experts know their subject well."],
  ["An audio interview is a source that you…", "listen to and take notes from", ["only read", "only watch"], "Sources can be spoken, written or visual."],
  ["You are writing about a Manitoba lake. Which is a digital source?", "a government website about the lake", ["a rumour", "your guess"], "Check who made a website."],
  ["Which idea does NOT belong in a report on how bees make honey?", "the history of the bicycle", ["how bees collect nectar", "what the hive looks like inside"], "Stay on the topic."],
  ["A sketch can help planning because it…", "shows ideas you can then describe in words", ["replaces all research", "makes the text shorter"], "Drawing is a way of thinking."],
  ["What is a research planner?", "a chart that lists your questions, sources and notes", ["a kind of dictionary", "a final copy"], "Planners keep research organized."],
  ["Which details would a writer gather for a report on the Red River?", "where it flows, who lives along it, how it floods", ["a favourite song", "a cooking recipe"], "Gather facts that fit the topic."],
  ["Brainstorming means…", "listing many ideas quickly before choosing", ["fixing spelling", "reading aloud"], "No idea is wrong at the start."],
  ["Which source might be biased?", "an ad written by the company that sells the product", ["an atlas", "a science museum guide"], "Ask who made it and why.", true],
  ["Two sources give different dates for the same event. What should you do?", "check a third reliable source", ["pick the one you like", "use both dates"], "Compare sources to find the facts.", true],
  ["A group wants to learn about recycling. Which question best guides their exploration?", "What happens to a plastic bottle after we recycle it?", ["Is recycling good?", "What is plastic?"], "A strong question needs several sources and thinking.", true],
  ["You have a topic, a purpose and an audience. What comes next in planning?", "choose a strategy to organize your ideas", ["hand in the work", "stop researching"], "Planning comes before drafting.", true],
  ["Which pair of sources would give the broadest information about a historic fur trade fort?", "a museum website and an interview with a historian", ["two copies of the same page", "two blank pages"], "Different kinds of sources add different details.", true],
  ["Which topic would be too big for a short report?", "The whole history of Canada", ["Why the loon calls at night", "How a lock on a canal works"], "Narrow a topic until you can cover it well.", true],
];

export const planning = bankUnit({
  id: "mb-research-planning-5",
  title: "Plan, Question and Research",
  emoji: "🗺️",
  blurb: "Choose a topic, ask good questions and find sources",
  parentNote: "Choosing a focused topic for an audience and purpose, planning with webs and notes, asking open-ended questions, using several sources and noticing gaps.",
  standards: ["ELA.5.B1.2, ELA.5.B1.4, ELA.5.C1.1, ELA.5.C1.2, ELA.5.C1.3", "choosing a topic, asking questions, gathering sources and planning a piece of writing"],
  items: PLAN,
});

const REVISE: Q[] = [
  ["Revising means…", "improving ideas, order and clarity", ["only fixing spelling", "copying the draft"], "Revise first, then edit."],
  ["You reread your paragraph and one sentence is about something else. You…", "remove it or move it", ["leave it", "make it louder"], "Every sentence should fit the main idea."],
  ["A checklist helps a writer by…", "showing what the writing should include", ["writing the story", "spelling words"], "Criteria tell you what to look for."],
  ["Feedback from a classmate is useful when it is…", "specific and kind", ["only a thumbs up", "about their handwriting"], "Descriptive feedback guides improvement."],
  ["Which feedback is descriptive?", "Your second paragraph needs a sentence that tells where the story happens.", ["It's fine.", "I like it."], "It tells the writer what to do."],
  ["Which step comes after drafting?", "revising", ["brainstorming", "publishing before checking"], "Draft, revise, edit, publish."],
  ["When you reread for logic, you check that…", "ideas follow in an order that makes sense", ["every word has six letters", "the font is red"], "Order matters in a story or report."],
  ["Which sentence should come first in a recipe's steps?", "Wash your hands.", ["Eat and enjoy.", "Serve on a plate."], "Steps follow the order they happen."],
  ["Which tool can confirm how to spell \"necessary\"?", "a digital dictionary", ["a guess", "a thesaurus only"], "Dictionaries confirm spelling."],
  ["Spell check misses \"their\" when you meant \"there\" because…", "both are real words", ["it is always right", "it ignores spelling"], "Proofread yourself too."],
  ["Which spelling strategy helps with \"island\"?", "remember the silent s", ["skip the s", "add a z"], "Notice the tricky part of the word."],
  ["Which is spelled correctly?", "separate", ["seperate", "seprate"], "There is \"a rat\" in separate."],
  ["Which is spelled correctly (Canadian)?", "colour", ["color", "colur"], "Canadians write -our."],
  ["Which is spelled correctly (Canadian)?", "centre", ["center", "centar"], "Canadians write -re."],
  ["Which is correct?", "I will practise piano.", ["I will practice piano.", "I will practis piano."], "Practise is the verb in Canadian spelling."],
  ["The words \"rain\" and \"train\" share…", "the spelling pattern \"ain\"", ["the pattern \"ane\"", "no pattern"], "Spelling patterns help with new words."],
  ["The plural of \"baby\" is…", "babies", ["babys", "babyes"], "Change y to i, then add es."],
  ["The plural of \"knife\" is…", "knives", ["knifes", "knifs"], "Change f to v, then add es."],
  ["Which word has a silent letter?", "knight", ["night", "light"], "The k in knight is silent."],
  ["A writer moves a paragraph so that the problem comes before the solution. This is…", "revising for order", ["fixing a comma", "changing the font"], "It improves how ideas flow."],
  ["Which change makes a draft clearer?", "replacing \"thing\" with the exact noun", ["adding more things", "making the title longer"], "Exact words are clearer.", true],
  ["Which is the best use of peer feedback?", "choose the suggestions that fit your goal and try them", ["ignore all of it", "copy a classmate's text"], "You decide what helps your piece.", true],
  ["Which rule helps spell \"believe\"?", "i before e, except after c", ["e before i always", "silent b"], "Think of the rhyme.", true],
  ["Which word is spelled correctly?", "accommodate", ["acommodate", "accomodate"], "Two c's and two m's.", true],
  ["Which passage has a sentence that does not belong?", "The lake was calm. We paddled slowly. I like pizza. The loons called to each other.", ["The lake was calm. We paddled slowly. The loons called to each other.", "We paddled slowly on the calm lake."], "Find the sentence that does not fit the scene.", true],
];

export const revising = bankUnit({
  id: "mb-revising-spelling-5",
  title: "Revise and Spell It Right",
  emoji: "✏️",
  blurb: "Make writing clearer and spell tricky words",
  parentNote: "Using checklists and feedback to revise for order and focus, and using spelling patterns, strategies and dictionaries (with Canadian spelling) to check words.",
  standards: ["ELA.5.C2.5, ELA.5.C3.2", "revising with criteria and feedback, and spelling strategies and patterns"],
  items: REVISE,
});

const DIVERSITY: Q[] = [
  ["A story shows a family from a different culture sharing a meal. This presents…", "diversity", ["a bias", "a rhyme"], "Diversity means differences among people."],
  ["Inclusion means…", "making sure everyone is welcome and can take part", ["only some people can play", "copying each other"], "Everyone belongs."],
  ["A character uses a wheelchair and plays on the basketball team. What does this show?", "people with different abilities can take part", ["wheelchairs are rare", "basketball is easy"], "Texts can show inclusion."],
  ["Which is text evidence that a character is kind?", "She shared her lunch with a new student.", ["The classroom had a window.", "It was Tuesday."], "Actions are evidence of character."],
  ["A stereotype is…", "an overly simple idea about a whole group of people", ["a true fact about everyone", "a kind of poem"], "People in a group are different from each other."],
  ["\"All girls like pink\" is…", "a stereotype", ["a fact", "an opinion about colours only"], "It makes a claim about a whole group."],
  ["Prejudice is…", "judging people before knowing them", ["knowing someone well", "liking a book"], "Prejudice means a judgment made in advance."],
  ["Bias in a text means…", "it favours one side or view unfairly", ["it has no words", "it is very long"], "Look for who is left out."],
  ["A book about farm life only shows boys working. A thoughtful reader says…", "Girls and women farm too, so this leaves people out.", ["That is all of farming.", "I do not need to think."], "Notice who is missing."],
  ["Which is an opinion supported by evidence?", "I think the story is exciting because the hero escapes three times.", ["It is exciting.", "Everyone must like it."], "Give a reason from the text."],
  ["Which sentence supports the opinion \"The wolf is brave\"?", "The wolf stood between the pups and the storm.", ["The wolf was grey.", "Wolves live in packs."], "Evidence matches the opinion."],
  ["You read a story that makes fun of a group of people. A good response is to…", "say respectfully that it is unfair and explain why", ["laugh along", "copy the idea"], "Respond to bias thoughtfully."],
  ["An illustration shows only one kind of family. Which question is helpful?", "Which families are not shown?", ["What colour is the page?", "How many pages are there?"], "Ask who is missing."],
  ["A quote from a character is useful because it…", "can be evidence for what the character thinks", ["is always funny", "shows the author's name"], "Quotes are text evidence."],
  ["Which book would add to a classroom library's diversity?", "stories by authors from many communities, including First Nations and Métis authors", ["ten copies of the same story", "books by only one author"], "A range of creators gives a range of voices."],
  ["Why does it matter to read stories from many creators?", "we learn about people whose lives differ from ours", ["to finish faster", "to avoid thinking"], "Stories build understanding."],
  ["A character is brave even though she is small. What does that challenge?", "the stereotype that only big people are brave", ["the plot", "the setting"], "Texts can break stereotypes."],
  ["Which is a fair way to describe an Indigenous character in a modern story?", "as a person with their own personality, like any other character", ["as a symbol only", "as someone from long ago only"], "Indigenous peoples live in Canada today."],
  ["What is the best response to a stereotype in a text?", "name it and explain why it is unfair", ["ignore it", "repeat it"], "Speak up kindly and clearly.", true],
  ["Two characters from different backgrounds become friends. Which detail best shows inclusion?", "They invite each other to join in their traditions.", ["They never speak.", "They are the same age."], "Inclusion means welcoming differences.", true],
  ["An author writes about a place only from the visitor's point of view. What might be missing?", "the voices of the people who live there", ["the ending", "the title"], "Perspective affects what is told.", true],
  ["Which statement shows respect for different opinions?", "I see it differently, and here is why.", ["Your idea is silly.", "Only mine counts."], "Disagree with reasons, not insults.", true],
  ["Which claim is a generalization that needs evidence?", "Kids in cities never like nature.", ["Many kids enjoy nature.", "Some kids visit parks."], "Words like never and always are warnings.", true],
  ["After reading, you change your mind about a character. Good readers…", "point to the part of the text that changed their thinking", ["hide the change", "say nothing"], "Evidence shows your thinking.", true],
];

export const diversity = bankUnit({
  id: "mb-diversity-bias-5",
  title: "Diversity, Bias and Fairness in Texts",
  emoji: "🌈",
  blurb: "Spot who is included and who is left out",
  parentNote: "Recognizing how diversity and inclusion appear in texts, using evidence to support an opinion, and responding thoughtfully to stereotypes, bias and prejudice.",
  standards: ["ELA.5.B3.1, ELA.5.B3.4", "diversity and inclusion in texts, evidence for opinions, and responding to stereotyping and bias"],
  items: DIVERSITY,
});

const WORDS: Q[] = [
  ["How many syllables are in \"elephant\"?", "3", ["2", "4"], "el-e-phant."],
  ["How many syllables are in \"community\"?", "4", ["3", "5"], "com-mu-ni-ty."],
  ["How many syllables are in \"adventure\"?", "3", ["2", "4"], "ad-ven-ture."],
  ["Which word breaks into syllables as \"won-der-ful\"?", "wonderful", ["wonder", "wonderfully"], "Count the beats."],
  ["Which prefix means \"not\"?", "un-", ["re-", "pre-"], "Unhappy means not happy."],
  ["Which prefix means \"again\"?", "re-", ["un-", "dis-"], "Rewrite means write again."],
  ["The suffix -ful means…", "full of", ["without", "not"], "Hopeful means full of hope."],
  ["The suffix -less means…", "without", ["full of", "again"], "Careless means without care."],
  ["The word \"unbelievable\" has the prefix…", "un-", ["-able", "be-"], "Un- comes at the start."],
  ["The word \"unbelievable\" has the suffix…", "-able", ["un-", "-lieve"], "-able comes at the end."],
  ["Which is the root of \"transportation\"?", "port", ["trans", "tion"], "Port means to carry."],
  ["Which word contains the root \"aqua\" (water)?", "aquarium", ["umbrella", "calendar"], "An aquarium holds water."],
  ["Which word has the Greek root \"graph\" (write)?", "autograph", ["autumn", "umbrella"], "Autograph is your own writing."],
  ["Which word is divided correctly?", "pol-lu-tion", ["po-llu-tion", "poll-ut-ion"], "Divide between double consonants."],
  ["Which word is divided correctly?", "con-struc-tion", ["cons-truc-tion", "const-ruc-tion"], "Divide after the prefix con-."],
  ["In \"invisible\", how many syllables are there?", "4", ["3", "5"], "in-vis-i-ble."],
  ["How many syllables are in \"important\"?", "3", ["2", "4"], "im-por-tant."],
  ["Which word is spelled correctly?", "temperature", ["temprature", "temperture"], "tem-per-a-ture."],
  ["Which word is spelled correctly?", "environment", ["enviroment", "envirnment"], "en-vi-ron-ment has the n before ment."],
  ["Which word is spelled correctly?", "government", ["goverment", "govenment"], "gov-ern-ment."],
  ["The letters \"tion\" at the end of a word sound like…", "shun", ["tee-on", "tin"], "Nation sounds like nay-shun."],
  ["Which word ends with the \"shun\" sound spelled \"sion\"?", "decision", ["nation", "motion"], "Decision uses s-i-o-n."],
  ["The letters \"ough\" in \"through\" sound like…", "oo", ["off", "ow"], "Through rhymes with blue."],
  ["Which word has a silent letter?", "wrinkle", ["winkle", "twinkle"], "The w in wrinkle is silent."],
  ["Reading a long word, a good strategy is to…", "break it into chunks and sound out each", ["skip it", "guess the first letter"], "Chunk by syllable.", true],
  ["Which word is divided correctly?", "mul-ti-ple", ["mult-i-ple", "mu-lti-ple"], "Each syllable has a vowel sound.", true],
  ["\"Pre-\" in \"preview\" means…", "before", ["after", "again"], "A preview is a look before.", true],
  ["Which word belongs to the same family as \"signal\"?", "signature", ["single", "simple"], "Both come from the root sign.", true],
  ["Which word is spelled correctly?", "necessary", ["neccessary", "necesary"], "One c, two s's.", true],
];

export const multisyllabic = bankUnit({
  id: "mb-long-words-5",
  title: "Long Words: Chunk and Spell",
  emoji: "🧩",
  blurb: "Break long words into parts you know",
  parentNote: "Reading and spelling longer words by finding syllables, prefixes, suffixes and roots, and noticing common spelling patterns.",
  standards: ["ELA.5.A2.3", "decoding and spelling multisyllabic words"],
  items: WORDS,
});

const READING: Q[] = [
  ["Before reading a text about wolves, you recall what you already know. This is…", "using prior knowledge", ["skipping", "guessing the ending"], "Prior knowledge helps you understand new text."],
  ["Why does prior knowledge help?", "it connects new ideas to things you know", ["it makes the text shorter", "it replaces reading"], "Connections help understanding."],
  ["Which text is a multimodal text?", "a web page with words, photos and a video", ["a page of plain words only", "a blank page"], "Multimodal texts use more than one mode."],
  ["Which source best builds background for a novel set in the 1800s?", "a short nonfiction article about the time", ["a recipe", "a weather map"], "Choose texts that fit your purpose."],
  ["You are reading directions for a science experiment. You should read…", "slowly and carefully", ["as fast as possible", "only the title"], "Adjust your rate to your purpose."],
  ["You are skimming a page to find a date. You read…", "quickly, looking for numbers", ["every word slowly", "backwards"], "Skimming is for finding."],
  ["When a passage is hard to understand, you should…", "slow down and reread", ["read faster", "stop for good"], "Slowing down helps comprehension."],
  ["A good reader asks, \"Does this make sense?\" This is…", "self-monitoring", ["skimming", "rhyming"], "Check understanding as you read."],
  ["Which strategy helps if you do not know a word?", "look at the words around it", ["skip the page", "close the book"], "Context clues help."],
  ["Reading with expression means…", "your voice shows meaning and feeling", ["reading in a whisper only", "reading in a monotone"], "Fluency includes expression."],
  ["A poem is best read…", "slowly, noticing rhythm and line breaks", ["as fast as a list", "only the first line"], "Poems are meant to be savoured."],
  ["Fluent reading is…", "smooth, accurate and with the right pace", ["very fast always", "silent only"], "Fluency helps comprehension."],
  ["Why choose different kinds of texts to learn about a topic?", "each kind shows different information", ["they are all the same", "to read less"], "Variety builds knowledge."],
  ["Which is a good way to choose a book for fun?", "read the back cover and the first page", ["pick the thickest", "pick one at random without looking"], "Preview before choosing."],
  ["Which of these can be a text?", "a photograph with a caption", ["only a novel", "only a poem"], "Texts can be viewed as well as read."],
  ["Before reading, you ask \"What will this be about?\" This is…", "previewing and predicting", ["revising", "proofreading"], "Look at headings and pictures."],
  ["You wonder how your reading strategies are working. You are…", "reflecting on your learning", ["spelling", "copying"], "Reflecting helps you improve."],
  ["Which question shows self-monitoring in reading?", "Do I need to reread this part?", ["Is this book heavy?", "What colour is the cover?"], "Check your understanding."],
  ["A strategy for remembering a long chapter is to…", "stop and summarize after each section", ["read it all and never think", "skip headings"], "Pause to check.", true],
  ["You are reading an article for research. What do you do with a fact you do not know?", "note it and check it in another source", ["ignore it", "assume it is wrong"], "Gather and check information.", true],
  ["When two texts about the same event give different details, you…", "compare them and think about why they differ", ["pick the shorter one", "ignore both"], "Different creators have different views.", true],
  ["Which choice shows adjusting your rate for a purpose?", "slowing down for a science explanation, speeding up for an easy story", ["reading everything at one speed", "never rereading"], "Match your pace to the text.", true],
  ["A graphic text with a map and labels needs you to…", "read the words and study the picture together", ["ignore the picture", "ignore the words"], "Multimodal texts need both.", true],
  ["Which goal is a specific reading goal?", "I will read for 15 minutes each night and note two new words.", ["I will read better.", "I will try."], "Specific goals have steps.", true],
];

export const reading = bankUnit({
  id: "mb-read-with-purpose-5",
  title: "Read With a Purpose",
  emoji: "📚",
  blurb: "Use what you know and read at the right pace",
  parentNote: "Using prior knowledge, choosing varied texts, adjusting reading rate for purpose and checking understanding while reading.",
  standards: ["ELA.5.A2.6, ELA.5.B1.1, ELA.5.B1.3, ELA.5.D2.1", "reading fluency and rate, prior knowledge, choosing multimodal texts and self-monitoring"],
  items: READING,
});

const MULTI: Q[] = [
  ["A multimodal text uses…", "more than one mode, such as words and images", ["only letters", "only sound"], "Modes include text, image, sound and video."],
  ["Which is a mode of communication?", "sound", ["spelling", "a comma"], "Modes are ways of sharing a message."],
  ["Which text mixes several modes?", "a digital story with narration and pictures", ["a list of words", "a ruler"], "It has audio and images."],
  ["A poster should have…", "a clear title and pictures that fit the message", ["tiny words only", "no title"], "Posters catch the eye."],
  ["Why choose a large, clear font for a poster?", "so it can be read from far away", ["to use more ink", "to hide mistakes"], "Think about your audience."],
  ["Which font choice is best for a long paragraph?", "a plain, easy-to-read font", ["a swirly decorative font", "all capitals"], "Readable text helps readers."],
  ["Which colour choice is easiest to read?", "dark text on a light background", ["yellow text on white", "light grey on white"], "Contrast helps."],
  ["Why add a photo to a report on a lighthouse?", "it shows what words alone cannot", ["to fill the page", "to hide errors"], "Images can add information."],
  ["Which would be best to add to a video about recycling?", "narration that explains each step", ["silence", "a different topic"], "Sound can explain."],
  ["What is a caption?", "words that explain a picture", ["a kind of font", "a page number"], "Captions go with images."],
  ["Which digital tool is made for writing and editing text?", "a word processor", ["a calculator", "a thermometer"], "Word processors help you type and format."],
  ["When writing by hand, legible means…", "easy to read", ["very small", "very fast"], "Readers need to be able to read it."],
  ["Spacing between words and lines helps readers because…", "it keeps text from running together", ["it uses more paper", "it hides errors"], "White space helps."],
  ["A thinking map, such as a web or flow chart, helps you…", "organize ideas before drafting", ["spell", "print"], "Maps show how ideas connect."],
  ["For a message to a younger class, you should…", "use simple words and bright pictures", ["use long technical words", "have no pictures"], "Think about your audience."],
  ["A final text should have a clear purpose such as…", "to inform, to persuade or to entertain", ["to confuse", "to fill space"], "Purpose guides choices."],
  ["Which medium is best to show how a plant grows over weeks?", "a series of photos or a short video", ["one word", "a sentence about soil"], "Time can be shown with a sequence."],
  ["What should a slide in a presentation NOT have?", "a whole page of tiny text", ["a short heading", "one clear picture"], "Slides support the speaker.", true],
  ["Why include a title and your name on a finished piece?", "readers know what it is and who made it", ["to fill space", "it is a rule for fonts"], "Titles and names identify work.", true],
  ["Which combination best informs people about a local park?", "a map, a short description and a photo", ["a long list of words", "a blank page"], "Use modes that fit the message.", true],
  ["A poem is performed as audio with a drawing beside it. Which two modes are mixed?", "sound and image", ["touch and taste", "smell and sound"], "Audio and visual.", true],
  ["Before publishing a digital story, you should…", "check the text, images and sound work together", ["publish right away", "delete the images"], "Check all parts.", true],
  ["Which choice shows thinking about the audience?", "using a bigger font for a grandparent who has trouble seeing small print", ["using a tiny font", "using no words"], "Make it work for the reader.", true],
  ["Which is the best reason to use a heading in a report?", "it tells readers what each section is about", ["to make the page longer", "to use more colours"], "Headings organize text.", true],
];

export const multimodal = bankUnit({
  id: "mb-multimodal-texts-5",
  title: "Create With Words, Pictures and Sound",
  emoji: "🎨",
  blurb: "Choose fonts, images and modes for your audience",
  parentNote: "Planning and polishing texts that combine words, images, sound and video, and choosing fonts, layout and tools to suit an audience and purpose.",
  standards: ["ELA.5.C1.5, ELA.5.C3.1, ELA.5.C3.5", "creating multimodal texts, legible and word-processed writing, and combining modes for an audience"],
  items: MULTI,
});

const TALK: Q[] = [
  ["Which question is open-ended?", "How do you think the character felt?", ["Was the character sad?", "Is the character a girl?"], "Open-ended questions need explaining."],
  ["Which question asks for reasoning?", "Why did the beaver build a dam?", ["Is the beaver a mammal?", "Does the beaver have a tail?"], "Why and how questions go deeper."],
  ["Which word is a transition word that shows order?", "first", ["green", "because of"], "Order words: first, next, then, finally."],
  ["Which transition word shows a result?", "so", ["but", "then"], "It rained, so we stayed inside."],
  ["Which transition word shows a contrast?", "however", ["therefore", "finally"], "However introduces a difference."],
  ["Which transition word adds an idea?", "also", ["but", "instead"], "Also means in addition."],
  ["Which sentence is complex?", "We went inside because it started to snow.", ["We went inside.", "It snowed."], "A complex sentence has a main clause and a dependent clause."],
  ["Which word makes a dependent clause?", "although", ["and", "the"], "Although it was cold, we played outside."],
  ["Which sentence has a stronger, more detailed description?", "The huge grey whale surfaced beside our boat.", ["The whale came.", "Something moved."], "Details help listeners picture it."],
  ["When someone is speaking, a good listener…", "looks at the speaker and waits for a turn", ["talks at the same time", "looks away"], "Social conventions help conversation."],
  ["When listening to a story, what helps summarize it?", "retelling the key ideas in your own words", ["repeating every word", "remembering only the title"], "A summary is short and in your own words."],
  ["A good summary of a talk about composting includes…", "the main ideas and key details", ["every sentence", "only your opinion"], "Be brief."],
  ["Which body language shows you are listening?", "nodding and facing the speaker", ["turning away", "doodling loudly"], "Non-verbal cues show respect."],
  ["In a group discussion, what should you do if you disagree?", "say so politely and give a reason", ["interrupt", "stay silent and sulk"], "Listen, then respond."],
  ["Which sentence builds on someone else's idea?", "I agree with Sam, and I'd like to add that…", ["No.", "That's boring."], "Collaborative talk builds on ideas."],
  ["Which is a sentence starter for asking about someone's reason?", "What makes you think that?", ["Stop talking.", "I don't care."], "It invites explanation."],
  ["Which word means almost the same as \"said\" and shows excitement?", "exclaimed", ["whispered", "murmured"], "Pick a precise verb."],
  ["Which description gives the clearest picture?", "a rusty red bike with a bent front wheel", ["a bike", "a thing"], "Precise details help.", true],
  ["Which sentence correctly joins two ideas?", "I wanted to go outside, but it was raining.", ["I wanted to go outside but, it was raining.", "I wanted to go outside but it was raining but."], "Use a comma before but joining two clauses.", true],
  ["Which transition best fits? \"The ice was thin. ____, we stayed off the lake.\"", "Therefore", ["Meanwhile", "For example"], "Therefore shows a result.", true],
  ["Someone's idea differs from yours. A good reply starts with…", "I see it a different way.", ["That's wrong.", "Be quiet."], "Respectful phrasing keeps talk open.", true],
  ["Which question would best push a discussion about fairness further?", "Who might not think this is fair, and why?", ["Is it fair?", "Yes or no?"], "Ask for other perspectives.", true],
  ["A speaker says, \"It's important to recycle.\" Which follow-up asks for the idea behind it?", "Why do you think it is important?", ["How old are you?", "Is it Friday?"], "Ask behind the statement.", true],
  ["Which pair of sentences uses a transition correctly?", "Rain fell all morning. As a result, the soccer game was cancelled.", ["Rain fell all morning. As a result, we had pizza for lunch on Friday.", "Rain fell all morning. Meanwhile, the game was cancelled for sunshine."], "The result must follow from the cause.", true],
];

export const talk = bankUnit({
  id: "mb-talk-and-listen-5",
  title: "Talk, Listen and Ask Why",
  emoji: "💬",
  blurb: "Open-ended questions and clear connecting words",
  parentNote: "Listening to summarize, joining a discussion respectfully, asking open-ended questions and using complex sentences with transition words to share ideas.",
  standards: ["ELA.5.A1.1, ELA.5.A1.2, ELA.5.A1.3, ELA.5.A1.4, ELA.5.A1.5", "listening for key ideas, discussion habits, open-ended questions and complex sentences with transitions"],
  items: TALK,
});

const GOALS: Q[] = [
  ["A learning goal is…", "something you want to get better at", ["a prize", "a grade"], "Goals point your learning."],
  ["Which goal is the most specific?", "I will reread my writing to check each sentence has a capital letter and end mark.", ["I will do better.", "I will try my best."], "Specific goals say what you will do."],
  ["Criteria are…", "the things a good piece of work includes", ["the marks on a test", "the pencils you use"], "Class criteria say what to aim for."],
  ["Why make criteria with your class?", "everyone knows what good work looks like", ["to make the work harder", "to avoid doing work"], "Shared criteria are fair and clear."],
  ["A portfolio is…", "a collection of your work that shows your learning", ["a lunch box", "a kind of font"], "It shows growth over time."],
  ["A learning journal helps you…", "write about what you learned and what you want to work on", ["hide your work", "skip reflection"], "Journals support reflection."],
  ["Descriptive feedback tells you…", "what is working and what to try next", ["only a score", "only that you are done"], "It guides improvement."],
  ["Which is descriptive feedback?", "Your opening grabs the reader. Try adding one detail about the setting.", ["Good.", "Try harder."], "It names a strength and a next step."],
  ["After getting feedback, you should…", "pick a next step and try it", ["ignore it", "feel upset forever"], "Feedback helps you grow."],
  ["Which question helps you plan a strategy before writing?", "What strategies will I use to plan and draft?", ["Who is the tallest?", "What is for lunch?"], "Think about your approach."],
  ["Which shows tracking progress?", "keeping a list of the books you've read each month", ["hiding your work", "forgetting what you did"], "Collect evidence of learning."],
  ["Evidence of learning can be…", "a piece of writing, a journal entry or a recording", ["only a mark", "nothing"], "It shows what you can do."],
  ["Which is a strength in listening?", "I can summarize what a speaker says.", ["I don't listen.", "I don't know."], "A strength is something you do well."],
  ["Which is a next step for a writer who forgets end marks?", "reread each sentence and check the end mark", ["write fewer sentences", "stop writing"], "A next step is an action."],
  ["Reflecting means…", "thinking about what went well and what to change", ["forgetting", "finishing quickly"], "Reflection builds learning."],
  ["A podcast can be used to self-assess because you can…", "listen back and notice what to improve", ["not hear yourself", "hide it"], "Recording lets you review."],
  ["What is the first step in reaching a goal?", "decide exactly what it is", ["give up", "wait"], "Plans start with a clear goal."],
  ["Which plan has steps?", "Read 10 pages a night, jot two new words, and share them on Friday.", ["Read more.", "Improve."], "Steps are small actions.", true],
  ["You set a goal to improve in speaking. Which evidence would show progress?", "a recording from September and one from November", ["a picture of a pencil", "your age"], "Compare evidence over time.", true],
  ["Why is it good to notice a strength as well as a goal?", "strengths show what already works", ["strengths do not matter", "goals are bad"], "Build on your strengths.", true],
  ["Which sentence best reflects on a process?", "When I made a mind map first, my writing was easier to organize.", ["I wrote.", "It was okay."], "Link the strategy to the result.", true],
  ["Peer feedback is most helpful when you…", "listen, ask questions and decide what to use", ["argue back", "ignore it"], "Learning from others takes listening.", true],
  ["Why revisit your goal after a few weeks?", "to see how far you've come and set a new step", ["to forget it", "to change the criteria secretly"], "Monitor and adjust.", true],
  ["Which tool could a student use to track writing progress?", "a portfolio with dated samples", ["a stopwatch only", "a compass"], "Dated samples show growth.", true],
];

export const goals = bankUnit({
  id: "mb-learning-goals-5",
  title: "Set a Goal and Track Your Growth",
  emoji: "🎯",
  blurb: "Use criteria and feedback to get better",
  parentNote: "Setting specific learning goals, using class criteria and descriptive feedback, and collecting evidence to see progress in reading, writing, speaking, listening and representing.",
  standards: ["ELA.5.D2.1, ELA.5.D2.2, ELA.5.D2.3, ELA.5.D2.4, ELA.5.D2.5", "self-assessment, class criteria, feedback, learning goals and tracking progress"],
  items: GOALS,
});
