import { bankUnit, type Q } from "../own";

// Grade 5 mathematics: mental math, measurement and shapes (5.N.3, 5.N.4, 5.SS.2 to 5.SS.6).

const MENTAL: Q[] = [
  ["6 × 7 = ?", "42", ["36", "48"], "Think 6 × 6 = 36, then add one more 6."],
  ["8 × 9 = ?", "72", ["64", "81"], "8 × 10 = 80, then take away 8."],
  ["7 × 7 = ?", "49", ["42", "56"], "7 × 7 is one more 7 than 6 × 7 = 42."],
  ["9 × 6 = ?", "54", ["56", "63"], "9 × 6 is 10 × 6 = 60 take away 6."],
  ["8 × 8 = ?", "64", ["56", "72"], "Double 8 × 4 = 32."],
  ["56 ÷ 7 = ?", "8", ["7", "9"], "7 × 8 = 56, so 56 ÷ 7 = 8."],
  ["72 ÷ 9 = ?", "8", ["6", "9"], "9 × 8 = 72."],
  ["63 ÷ 7 = ?", "9", ["8", "7"], "7 × 9 = 63."],
  ["48 ÷ 6 = ?", "8", ["7", "6"], "6 × 8 = 48."],
  ["81 ÷ 9 = ?", "9", ["8", "7"], "9 × 9 = 81."],
  ["6 × 40 = ?", "240", ["24", "2 400"], "Do 6 × 4 = 24, then add one zero."],
  ["5 × 300 = ?", "1 500", ["150", "15 000"], "Do 5 × 3 = 15, then add two zeros."],
  ["7 × 200 = ?", "1 400", ["140", "14 000"], "7 × 2 = 14, then add two zeros."],
  ["9 × 50 = ?", "450", ["45", "4 500"], "9 × 5 = 45, then add one zero."],
  ["8 × 30 = ?", "240", ["24", "2 400"], "8 × 3 = 24, then add one zero."],
  ["Half of 46 is 23. So 4 × 23 is the same as…", "2 × 46", ["2 × 23", "4 × 46"], "Halving one number and doubling the other keeps the product the same."],
  ["Double 15 is 30 and half of 24 is 12. So 24 × 15 = 12 × ?", "30", ["15", "24"], "Halve 24 to get 12, then double 15 to get 30."],
  ["36 × 5 is the same as half of 36 × ?", "10", ["5", "20"], "5 is half of 10, so 36 × 5 is half of 36 × 10."],
  ["4 × 25 = ?", "100", ["75", "125"], "Four quarters make one dollar: 4 × 25 = 100."],
  ["20 × 15 = ?", "300", ["30", "3 000"], "2 × 15 = 30, then add one zero."],
  ["12 × 5 = ?", "60", ["50", "72"], "Half of 12 × 10 = 120 is 60."],
  ["9 × 8 = 72. What is 9 × 80?", "720", ["72", "7 200"], "Add one zero to 72."],
  ["3 × 6 = 18. What is 300 × 6?", "1 800", ["180", "18 000"], "Add two zeros to 18."],
  ["Which fact helps you solve 54 ÷ 6?", "6 × 9 = 54", ["6 × 8 = 48", "9 × 9 = 81"], "Think of the multiplication fact that makes 54."],
  ["Which is the best way to find 8 × 15 in your head?", "8 × 10 = 80 and 8 × 5 = 40, then add", ["8 + 15", "8 × 1 and 8 × 5, then add"], "Break 15 into 10 and 5.", true],
  ["25 × 8 = ?", "200", ["160", "225"], "25 × 4 = 100, so 25 × 8 is double that.", true],
  ["15 × 6 = ?", "90", ["75", "80"], "10 × 6 = 60 and 5 × 6 = 30.", true],
  ["12 × 25 = ?", "300", ["250", "325"], "Four 25s make 100, so 12 × 25 is three 100s.", true],
  ["480 ÷ 6 = ?", "80", ["8", "800"], "48 ÷ 6 = 8, then add one zero.", true],
  ["3 600 ÷ 9 = ?", "400", ["40", "4 000"], "36 ÷ 9 = 4, then add two zeros.", true],
];

export const mental = bankUnit({
  id: "mb-mental-math-5",
  title: "Mental Math Tricks",
  emoji: "🧠",
  blurb: "Facts to 81 and clever shortcuts",
  parentNote: "Recalling multiplication and division facts to 9 × 9, and mental strategies such as adding zeros, halving and doubling, and breaking a number into friendly parts.",
  standards: ["5.N.3, 5.N.4", "multiplication and division facts to 81, and mental strategies for multiplying"],
  items: MENTAL,
});

const MEASURE: Q[] = [
  ["How many millimetres are in 1 centimetre?", "10", ["100", "1"], "A centimetre is made of 10 millimetres."],
  ["How many millimetres are in 1 metre?", "1 000", ["100", "10"], "1 m is 100 cm, and each cm is 10 mm."],
  ["Which is the best unit for the thickness of a dime?", "millimetre", ["metre", "kilometre"], "A dime is about 1 mm thick."],
  ["Which is the best unit for the length of a pencil?", "centimetre", ["kilometre", "millimetre"], "A pencil is about 15 to 19 cm long."],
  ["Which is about 1 mm thick?", "a dime", ["a book", "a table"], "A dime is a very thin coin."],
  ["A bean is about 8 ___ long.", "mm", ["m", "km"], "A bean is tiny, so use millimetres."],
  ["How many mL are in 1 L?", "1 000", ["100", "10"], "Litre means a thousand millilitres."],
  ["2 L is the same as…", "2 000 mL", ["200 mL", "20 mL"], "Multiply 2 by 1 000."],
  ["3 000 mL is the same as…", "3 L", ["30 L", "300 L"], "Divide 3 000 by 1 000."],
  ["Which is the best unit for the water in a swimming pool?", "litre", ["millilitre", "millimetre"], "A pool holds a huge amount, so use bigger units."],
  ["Which is about 5 mL?", "a teaspoon of medicine", ["a bathtub of water", "a jug of milk"], "A teaspoon is a very small amount."],
  ["Which is about 1 L?", "a carton of milk", ["a teaspoon", "a rain barrel"], "Milk cartons often hold 1 L."],
  ["What does volume measure?", "the space an object takes up", ["how long it is", "how heavy it is"], "Volume is how much space something fills."],
  ["Which unit measures volume?", "cubic centimetre (cm³)", ["square centimetre (cm²)", "centimetre (cm)"], "Volume uses cubes."],
  ["A cube has sides 1 cm long. Its volume is…", "1 cm³", ["1 cm²", "6 cm"], "That cube is one cubic centimetre."],
  ["A box holds 2 layers of 6 cubes. What is its volume in cubes?", "12", ["8", "6"], "2 layers × 6 cubes = 12 cubes."],
  ["A box is 3 cubes long, 2 wide and 2 high. How many cubes fill it?", "12", ["7", "10"], "3 × 2 × 2 = 12."],
  ["Which is the better unit for the volume of a large moving truck?", "cubic metre (m³)", ["cubic centimetre (cm³)", "millimetre (mm)"], "Use bigger cubes for big spaces."],
  ["Which is the better unit for the volume of a small dice?", "cubic centimetre (cm³)", ["cubic metre (m³)", "litre (L)"], "A dice is about 1 or 2 cm on each side."],
  ["A cubic metre is a cube that is each side…", "1 m long", ["1 cm long", "1 mm long"], "Cubic metres use sides of 1 m."],
  ["Which unit measures capacity?", "litre", ["square metre", "centimetre"], "Capacity is how much a container holds."],
  ["Which holds more?", "a 2 L jug", ["a 500 mL bottle", "a 250 mL cup"], "2 L is 2 000 mL."],
  ["Which is a good referent for 1 mm?", "the thickness of a dime", ["the width of a hand", "the length of a bus"], "A referent is a familiar object you can compare with."],
  ["Which is a good referent for 1 cm³?", "a small sugar cube", ["a shoebox", "a fridge"], "A sugar cube is about 1 cm on each side."],
  ["A tank holds 4 L. How many 500 mL cups fill it?", "8", ["4", "2"], "1 L is two cups of 500 mL, so 4 L is eight cups.", true],
  ["Which is the same as 4 500 mL?", "4 L 500 mL", ["45 L", "450 mL"], "4 000 mL is 4 L, and 500 mL is left over.", true],
  ["A box is 5 cm long, 4 cm wide and 3 cm high. Its volume is…", "60 cm³", ["12 cm³", "47 cm³"], "5 × 4 × 3 = 60.", true],
  ["A line is 35 mm long. How many centimetres is that?", "3 cm 5 mm", ["35 cm", "3 cm 50 mm"], "30 mm is 3 cm, and 5 mm is left.", true],
  ["Which has the greatest volume?", "5 cm × 5 cm × 5 cm", ["4 cm × 4 cm × 4 cm", "10 cm × 2 cm × 2 cm"], "125, 64 and 40 cubic centimetres.", true],
  ["1.5 L is the same as…", "1 500 mL", ["150 mL", "15 mL"], "Multiply 1.5 by 1 000.", true],
];

export const measure = bankUnit({
  id: "mb-measuring-5",
  title: "Millimetres, Volume and Capacity",
  emoji: "📏",
  blurb: "mm, cm³, m³, mL and L",
  parentNote: "Choosing units for length (mm), volume (cm³, m³) and capacity (mL, L), using everyday referents, and linking millilitres to litres.",
  standards: ["5.SS.2, 5.SS.3, 5.SS.4", "measuring in millimetres, volume in cubic units, and capacity in mL and L"],
  items: MEASURE,
});

const SHAPES: Q[] = [
  ["Parallel lines are lines that…", "never cross", ["cross at a square corner", "touch at one point"], "Think of railway tracks."],
  ["Perpendicular lines meet at…", "a right angle", ["no point", "a very small angle"], "Perpendicular lines make a square corner."],
  ["Which pair of lines is parallel?", "two opposite sides of a ruler", ["two sides of a corner of a wall", "the hands of a clock at 3:00"], "Parallel lines stay the same distance apart."],
  ["The hands of a clock at 3:00 are…", "perpendicular", ["parallel", "the same line"], "They make a right angle."],
  ["Which shape has four equal sides and four right angles?", "square", ["trapezoid", "parallelogram"], "A square has equal sides and square corners."],
  ["A rectangle has…", "two pairs of equal, parallel sides", ["only one pair of parallel sides", "no parallel sides"], "Opposite sides are equal and parallel."],
  ["A quadrilateral has…", "four sides", ["three sides", "five sides"], "Quad means four."],
  ["Which is a quadrilateral?", "a trapezoid", ["a triangle", "a hexagon"], "Count the sides: it has four."],
  ["A rhombus has…", "four equal sides", ["only two equal sides", "three equal sides"], "A rhombus looks like a tilted square."],
  ["A parallelogram has…", "two pairs of parallel sides", ["no parallel sides", "exactly one pair of parallel sides"], "Opposite sides are parallel."],
  ["A trapezoid has…", "at least one pair of parallel sides", ["no right angles at all", "four equal sides"], "Look for sides that never meet."],
  ["Which quadrilateral has exactly one pair of parallel sides?", "a trapezoid", ["a rectangle", "a rhombus"], "Rectangles and rhombuses have two pairs."],
  ["Every square is also a…", "rectangle", ["triangle", "trapezoid with no parallel sides"], "A square has four right angles, like a rectangle."],
  ["Which shape has all sides equal but no right angles?", "a rhombus that is not a square", ["a square", "a rectangle"], "It looks like a squashed square."],
  ["How many parallel edges does a cube have on its top face?", "4 edges in 2 parallel pairs", ["none", "6"], "Opposite edges of a square face are parallel."],
  ["Two faces on opposite sides of a box are…", "parallel", ["perpendicular", "triangles"], "The top and bottom of a box never meet."],
  ["A wall and the floor of a room are…", "perpendicular", ["parallel", "the same"], "They meet at a right angle."],
  ["How many pairs of parallel sides does a parallelogram have?", "2", ["1", "4"], "Opposite sides are parallel."],
  ["A kite has two pairs of equal sides that are…", "next to each other", ["opposite each other", "all the same length"], "Think of a kite in the sky."],
  ["Which shape is NOT a quadrilateral?", "a pentagon", ["a rhombus", "a square"], "A pentagon has five sides."],
  ["How many right angles does a rectangle have?", "4", ["2", "0"], "All four corners are square."],
  ["A shape has 4 sides, none parallel. It is a…", "quadrilateral that is not a parallelogram", ["rectangle", "square"], "Parallel sides are needed for a parallelogram."],
  ["Which letter has parallel lines?", "H", ["V", "X"], "The two tall sides of an H never meet."],
  ["Which shape can be sorted as both a rhombus and a parallelogram?", "a square", ["a trapezoid with one parallel pair", "a kite"], "A square has two pairs of parallel sides and four equal sides.", true],
  ["A shape has 4 equal sides but no right angles. Which is it?", "rhombus", ["square", "rectangle"], "Squares have right angles.", true],
  ["A rectangle is not a rhombus unless it is also a…", "square", ["trapezoid", "triangle"], "Only squares have four equal sides and four right angles.", true],
  ["Opposite sides equal, opposite angles equal, no right angles. Which shape?", "parallelogram", ["rectangle", "square"], "Rectangles need right angles.", true],
  ["Which pair is parallel on a 3-D rectangular prism?", "the front and back faces", ["the front face and the top face", "the left face and the bottom face"], "Parallel faces face each other.", true],
  ["Why is a square a special rectangle?", "It has four right angles and its sides are all equal", ["It has three sides", "It has no parallel sides"], "A square meets every rule for a rectangle.", true],
];

export const quadrilaterals = bankUnit({
  id: "mb-quadrilaterals-5",
  title: "Parallel Lines and Quadrilaterals",
  emoji: "🔷",
  blurb: "Sort four-sided shapes",
  parentNote: "Finding parallel and perpendicular edges and sides, and sorting quadrilaterals (rectangles, squares, trapezoids, parallelograms and rhombuses) by their sides and angles.",
  standards: ["5.SS.5, 5.SS.6", "parallel and perpendicular sides and edges, and sorting quadrilaterals"],
  items: SHAPES,
});
