import { bankUnit, type Q } from "../own";

// More Grade 5 science: matter and its changes (SCI.5.E.2 to E.4), the nature of science and technology (SCI.5.D),
// and scientific skills, measurement and safety (SCI.5.C). Indigenous content is in the present tense, says "many"
// or "some", and stays general.

const MATTER: Q[] = [
  ["Matter is anything that…", "has mass and takes up space", ["is alive", "can be seen without a tool"], "Air is matter too."],
  ["Which is a solid?", "an ice cube", ["steam", "milk"], "A solid keeps its own shape."],
  ["Which is a liquid?", "juice", ["a rock", "oxygen"], "A liquid takes the shape of its container."],
  ["Which is a gas?", "water vapour", ["ice", "sand"], "A gas spreads out to fill its container."],
  ["What happens when ice is heated?", "it melts into liquid water", ["it turns into a rock", "it becomes colder"], "Heat changes the state."],
  ["Melting is a change from…", "solid to liquid", ["liquid to gas", "gas to liquid"], "Ice melting is solid to liquid."],
  ["Freezing is a change from…", "liquid to solid", ["solid to gas", "gas to solid"], "Water freezes into ice."],
  ["Boiling or evaporating is a change from…", "liquid to gas", ["gas to liquid", "solid to liquid"], "Water becomes water vapour."],
  ["Condensation is a change from…", "gas to liquid", ["liquid to solid", "solid to gas"], "Water drops form on a cold glass."],
  ["At what temperature does pure water freeze (at sea level)?", "0 °C", ["10 °C", "100 °C"], "Water freezes at 0 °C."],
  ["At what temperature does pure water boil (at sea level)?", "100 °C", ["0 °C", "50 °C"], "Water boils at 100 °C."],
  ["Melting ice and then freezing it again shows a change that is…", "reversible", ["impossible", "a chemical reaction"], "You can go back to ice."],
  ["A physical change is one where…", "the substance stays the same kind of matter", ["a new substance forms", "matter disappears"], "Only size, shape or state changes."],
  ["Which is a physical change?", "tearing paper", ["burning paper", "rusting a nail"], "Torn paper is still paper."],
  ["Which is a physical change?", "chopping wood", ["burning wood", "baking a cake"], "Chopped wood is still wood."],
  ["Which is a chemical change?", "rusting of an iron nail", ["bending a nail", "cutting a nail"], "Rust is a new substance."],
  ["Which is a chemical change?", "baking a cake", ["melting butter", "mixing flour and sugar"], "Heat changes the batter into something new."],
  ["A sign of a chemical reaction is…", "a new substance with new properties", ["a change in shape", "a change in size"], "A new substance has formed."],
  ["Which could be a sign of a chemical reaction?", "bubbles of gas and a new smell", ["a change in colour from drawing", "a bigger puddle"], "Gas, colour change, heat or light can be signs."],
  ["A mixture is…", "two or more substances that are not chemically joined", ["a single pure substance", "a new substance made by a reaction"], "Each part keeps its own properties."],
  ["Which is a mixture?", "salad", ["pure water only", "a single iron nail"], "You can pick out the parts."],
  ["Which method separates sand from water?", "filtration", ["freezing", "burning"], "A filter traps the sand."],
  ["How can you separate salt from salt water?", "let the water evaporate", ["use a magnet", "use a sieve"], "The salt is left behind."],
  ["A magnet can separate…", "iron filings from sand", ["sugar from water", "salt from water"], "Iron is attracted to magnets."],
  ["Is dissolving sugar in water reversible?", "yes, by evaporating the water", ["no, never", "only by freezing"], "The sugar remains after evaporation.", true],
  ["You melt a candle's wax and it cools again. Burning the same wax's wick is…", "a chemical change", ["a physical change", "freezing"], "Burning forms new substances.", true],
  ["A sealed bag holds baking soda and vinegar. After they react and the bag swells, the total mass stays…", "the same", ["greater", "less"], "No matter is gained or lost.", true],
  ["Ice melts in a closed jar. The mass of the jar and contents after it melts is…", "the same", ["greater", "less"], "Matter is conserved in a state change.", true],
  ["When you stir sugar into tea, no matter is lost. Where is the sugar?", "spread evenly through the tea", ["gone completely", "turned into water"], "It is dissolved, not destroyed.", true],
  ["Which pair is correctly matched?", "burning wood: chemical; chopping wood: physical", ["burning wood: physical; chopping wood: chemical", "both: chemical"], "Burning makes new substances.", true],
  ["Which is NOT a way to separate a mixture?", "adding heat to turn it into a new substance", ["filtering", "using a magnet"], "Separating keeps the substances unchanged.", true],
];

export const matter = bankUnit({
  id: "mb-matter-changes-5",
  title: "Mixtures, Changes and Reactions",
  emoji: "🧪",
  blurb: "States of matter, mixtures and chemical change",
  parentNote: "How matter changes state with temperature, the difference between a mixture, a physical change and a chemical reaction, and why no matter is gained or lost.",
  standards: ["SCI.5.E.2, SCI.5.E.3, SCI.5.E.4", "changes of state, mixtures, physical and chemical change, and conservation of matter"],
  items: MATTER,
});

const NATURE: Q[] = [
  ["Science tries to…", "explain things we see in nature", ["make up stories", "avoid questions"], "Science builds explanations from evidence."],
  ["A scientific explanation is accepted when it…", "fits the evidence best at that time", ["is the oldest", "is the loudest"], "Explanations can change with new evidence."],
  ["A model in science is…", "a way to represent how something works", ["a fashion model", "a final answer"], "Models can be drawings, objects or ideas."],
  ["A theory in science is…", "a well-tested explanation supported by lots of evidence", ["a wild guess", "a rumour"], "Theories explain many observations."],
  ["Scientists collect data by…", "observing and measuring", ["guessing", "ignoring results"], "Data comes from careful work."],
  ["Which is a measurement?", "The plant grew 4 cm in a week.", ["The plant looks nice.", "I like plants."], "A measurement has a number and a unit."],
  ["Which is an observation?", "The water in the cup turned blue.", ["I think blue is best.", "Water should be red."], "An observation describes what you notice."],
  ["Can scientists use data from other sources?", "yes, such as research others have published", ["no, never", "only from television"], "Science builds on shared knowledge."],
  ["A hypothesis is…", "a prediction based on what you know", ["the final result", "a measurement"], "It can be tested."],
  ["Which is a good hypothesis?", "If I add more light, the plant will grow taller.", ["Plants are green.", "I like light."], "It predicts what will happen."],
  ["A hypothesis is based on…", "research, past experience or observations", ["a coin toss", "what you wish"], "Predictions come from evidence."],
  ["The results of an experiment support a hypothesis. This means…", "the evidence agrees with the prediction", ["the prediction is proved forever", "the experiment failed"], "Evidence can support or refute."],
  ["The results do not match your hypothesis. This is…", "useful, since you learned something", ["a failure", "cheating"], "Refuted ideas still teach."],
  ["Why do scientists test ideas more than once?", "to check the results are reliable", ["to waste time", "to get bored"], "Repeats build trust."],
  ["Engineering is…", "using science to solve problems and design things", ["only fixing cars", "only drawing"], "Engineers apply science."],
  ["Which is technology?", "a thermometer", ["a rock", "a cloud"], "Technology is made to solve a problem."],
  ["Science helps engineers by giving them…", "knowledge about how materials and forces behave", ["a vacation", "new names for things"], "Knowledge informs design."],
  ["New technology can help science by…", "letting us observe things we could not before", ["slowing research", "stopping experiments"], "Microscopes and telescopes are examples."],
  ["When designing a solution, there may be…", "many possible solutions", ["only one answer", "no answer"], "Compare designs."],
  ["When choosing a solution, you might consider…", "cost, safety and the effect on the environment", ["only the colour", "nothing at all"], "Think about the impacts."],
  ["A town is choosing between two ways to make power. What should they weigh?", "benefits and harms for people and the environment", ["only which is cheaper", "only what is popular"], "Science has ethical and social implications."],
  ["Plastic bags are cheap but harm wildlife if littered. This shows that…", "technologies can have good and bad effects", ["technologies are always good", "wildlife never matters"], "Applications of science have implications.", true],
  ["Many First Nations, Métis and Inuit communities have knowledge of the land built up over many generations. This is…", "a way of knowing about the natural world", ["a mistake", "only a story"], "Different ways of knowing can both help us understand nature.", true],
  ["Why can one problem have more than one good solution?", "people can balance cost, safety and sustainability in different ways", ["problems have no answers", "all solutions are the same"], "Critical and creative thinking both matter.", true],
  ["A scientist's explanation changes after better instruments gather new data. This shows science is…", "open to change when evidence changes", ["always wrong", "never based on data"], "Science updates with evidence.", true],
  ["Which statement describes a scientific approach?", "Test the idea, record what happens and share the results.", ["Decide the answer first and ignore the data.", "Only believe what is popular."], "Evidence guides decisions.", true],
  ["Everyone can contribute to science. Which is an example?", "a student noticing which bird visits the feeder and recording it", ["only adults can contribute", "no one can help"], "Citizen science counts.", true],
  ["Curiosity helps scientists because it…", "leads them to ask new questions", ["makes them stop", "replaces data"], "Questions start investigations.", true],
];

export const natureOfScience = bankUnit({
  id: "mb-nature-of-science-5",
  title: "How Science and Technology Work",
  emoji: "🔭",
  blurb: "Hypotheses, evidence, engineering and choices",
  parentNote: "How science builds explanations from evidence, how hypotheses are tested, how engineering uses science to solve problems, and how solutions have social and environmental effects.",
  standards: ["SCI.5.A.1, SCI.5.B.1, SCI.5.D.1, SCI.5.D.2, SCI.5.D.3, SCI.5.D.4, SCI.5.D.5, SCI.5.D.6", "explanations, evidence, hypotheses, engineering, many ways of knowing and the implications of science"],
  items: NATURE,
});

const SKILLS: Q[] = [
  ["Which tool measures mass?", "pan balance", ["thermometer", "ruler"], "A balance compares masses."],
  ["Which tool measures force?", "spring scale", ["ruler", "anemometer"], "Force is measured in newtons (N)."],
  ["Which tool measures wind speed?", "anemometer", ["spring scale", "pan balance"], "Cups spin in the wind."],
  ["Which tool measures temperature?", "thermometer", ["ruler", "balance"], "Temperature is measured in °C."],
  ["Which unit measures force?", "newton (N)", ["kilogram", "litre"], "Force is measured in N."],
  ["Which unit measures volume of liquid?", "litre (L)", ["gram", "metre"], "Volume is measured in L and mL."],
  ["Which unit measures mass?", "kilogram (kg)", ["litre", "degree Celsius"], "Mass is measured in g and kg."],
  ["Which unit measures speed?", "km/h", ["kg", "mL"], "Speed is distance divided by time."],
  ["How many millilitres are in 1 L?", "1000", ["100", "10"], "Milli means thousandth."],
  ["How many grams are in 1 kg?", "1000", ["100", "10"], "Kilo means thousand."],
  ["How many millimetres are in 1 m?", "1000", ["100", "10"], "There are 1000 mm in a metre."],
  ["How many centimetres are in 1 m?", "100", ["10", "1000"], "Centi means hundredth."],
  ["How many minutes are in 2 h?", "120", ["60", "200"], "60 minutes per hour."],
  ["Which tool would you use to measure 250 mL of water?", "a graduated cylinder", ["a thermometer", "a spring scale"], "Volumetric vessels measure volume."],
  ["Why do scientists use standard units?", "everyone can understand and compare results", ["to make numbers bigger", "to avoid measuring"], "Standard units are shared."],
  ["Which is the best unit for the length of a pencil?", "cm", ["km", "L"], "Choose a unit that fits the size."],
  ["Which is the best unit for the distance between two towns?", "km", ["mm", "mL"], "Large distances use km."],
  ["Which data display is best to show how temperature changed over a week?", "a line graph", ["a recipe", "a map of Canada"], "Line graphs show change over time."],
  ["Safety goggles protect your…", "eyes", ["ears", "knees"], "Wear them when splashing is possible."],
  ["What should you do before an experiment?", "read the steps and set up an uncluttered space", ["run around", "taste the materials"], "Safe work starts with a plan."],
  ["You see broken glass during science. What do you do?", "tell your teacher and do not touch it", ["pick it up with bare hands", "hide it"], "Handle glass with care."],
  ["Which is a safe habit?", "putting equipment away after use", ["leaving materials on the floor", "tasting science materials"], "A tidy space is a safe space."],
  ["A microscope helps you…", "see things too small for your eyes", ["see far away", "measure mass"], "Use it carefully."],
  ["What does a climate scientist do?", "studies long-term weather patterns", ["builds bridges", "grows wheat"], "Climate science uses data."],
  ["A farmer uses science when they…", "check soil, weather and plant growth to decide when to plant", ["never watch the weather", "ignore the soil"], "Farming connects to science.", true],
  ["Which hobby uses ideas about forces?", "cycling uphill with different gears", ["watching clouds only", "counting steps in a dream"], "Gears and levers change forces.", true],
  ["A veterinarian uses science to…", "keep animals healthy", ["cook dinner", "paint cars"], "They study animal bodies.", true],
  ["Baking and cooking involve science because…", "heating changes ingredients into new substances", ["heat does nothing", "food has no matter"], "Cooking uses chemical changes.", true],
  ["A group wants to help reduce climate emissions at school. Which action is a good start?", "walk, bike or carpool instead of driving alone", ["leave buses running", "turn on every light"], "Using less fuel reduces emissions.", true],
  ["After a severe storm, a class wants to make a safety plan. What should it include?", "where to go, how to stay informed and how to help neighbours", ["a plan to ignore warnings", "only snacks"], "Plans reduce harm.", true],
  ["You measure a plant at 8.5 cm, 9 cm and 9.6 cm over three days. What is the best way to show it?", "a table or line graph with units", ["a list with no units", "a picture of a sun"], "Data needs units.", true],
  ["Many Elders and Knowledge Keepers share teachings about caring for the land. Learning from them is an example of…", "learning with a community member", ["ignoring science", "a risk to avoid"], "Community members share knowledge, experience and teachings.", true],
];

export const skills = bankUnit({
  id: "mb-science-skills-5",
  title: "Measure, Stay Safe and Take Action",
  emoji: "📏",
  blurb: "Choose the right tool, unit and safe habit",
  parentNote: "Choosing and using tools and SI units, displaying data, working safely, linking science to careers and hobbies, and thinking about actions to help the environment.",
  standards: ["SCI.5.C.1, SCI.5.C.2, SCI.5.C.3, SCI.5.C.4, SCI.5.C.5", "scientific measurement, safe practices, using tools, careers and taking action"],
  items: SKILLS,
});
