import { bankUnit, type Q } from "../own";

// Grade 5 science: weather, climate, cells and friction (SCI.5.E.5, E.6, E.8, E.9 to E.16).

const WEATHER: Q[] = [
  ["What is weather?", "the conditions in the air outside at a certain time and place", ["the average of 30 years of temperature", "the kind of soil in a field"], "Weather changes from hour to hour and day to day."],
  ["Which tool measures temperature?", "thermometer", ["barometer", "rain gauge"], "A thermometer tells how hot or cold it is."],
  ["Which tool measures air pressure?", "barometer", ["thermometer", "anemometer"], "A barometer shows the pressure of the air."],
  ["Which tool measures wind speed?", "anemometer", ["rain gauge", "barometer"], "Cups on an anemometer spin faster in stronger wind."],
  ["Which tool measures how much rain fell?", "rain gauge", ["wind vane", "thermometer"], "It collects rain in a tube."],
  ["A wind vane shows…", "the direction the wind comes from", ["how fast it blows", "how much rain fell"], "The arrow points into the wind."],
  ["What gives Earth most of the energy that drives weather?", "the Sun", ["the Moon", "the stars"], "The Sun heats the air, land and water."],
  ["What is wind?", "moving air", ["moving water", "a kind of cloud"], "Air moves from high pressure toward low pressure."],
  ["Warm air tends to…", "rise", ["sink", "stay in one spot"], "Warm air is lighter than cold air."],
  ["Cold air tends to…", "sink", ["rise quickly", "turn into rain"], "Cold air is heavier."],
  ["Which cloud is tall and dark and can bring thunderstorms?", "cumulonimbus", ["cirrus", "stratus"], "Cumulonimbus clouds tower high."],
  ["Thin, wispy clouds high in the sky are called…", "cirrus", ["cumulonimbus", "nimbus"], "Cirrus clouds are high and feathery."],
  ["Which step of the water cycle turns liquid water into water vapour?", "evaporation", ["condensation", "precipitation"], "Heat from the Sun makes water evaporate."],
  ["Which step turns water vapour into tiny droplets in clouds?", "condensation", ["evaporation", "collection"], "Cool air makes vapour condense."],
  ["Rain, snow, sleet and hail are all types of…", "precipitation", ["evaporation", "condensation"], "Precipitation falls from clouds."],
  ["Where does most of the water in the water cycle collect?", "oceans, lakes and rivers", ["in clouds only", "in the air only"], "Water collects before it evaporates again."],
  ["What is a front in weather?", "where two air masses meet", ["a very big cloud", "a kind of snow"], "Fronts often bring changing weather."],
  ["A warm front is when…", "warm air moves over cooler air", ["cold air pushes under warm air", "winds stop"], "The warm air slides up over the cold air."],
  ["Which is a sign of a coming storm?", "a falling barometer reading", ["a perfectly clear sky", "a calm lake"], "Falling air pressure often comes before storms."],
  ["High pressure usually brings…", "clear, fair weather", ["storms", "tornadoes"], "Sinking air tends to keep skies clear."],
  ["Low pressure usually brings…", "cloudy, wet weather", ["clear skies", "steady warm days"], "Rising air forms clouds."],
  ["Why do forecasters use computers and many measurements?", "weather has many parts that interact", ["weather never changes", "clouds cannot be seen"], "Many things work together to make weather."],
  ["Why is long-term weather prediction hard?", "small changes today can grow into big changes later", ["the Sun stops shining", "water does not evaporate"], "Weather is a complex system."],
  ["A seven-day forecast is usually less sure about…", "day 7 than day 1", ["day 1 than day 7", "nothing at all"], "The further away, the harder to predict."],
  ["Why do farmers watch the weather forecast?", "to plan planting, spraying and harvest", ["to choose their favourite colour", "to count clouds for fun"], "Weather affects crops.", true],
  ["Why is a blizzard warning important on the Prairies?", "it helps people stay safe and plan travel", ["it makes snow warm", "it stops the wind"], "Warnings keep people safe.", true],
  ["Why can a town beside a big lake have milder weather than a town far inland?", "land and water heat and cool differently", ["water never moves", "air has no weight"], "Different surfaces warm at different speeds.", true],
  ["Water vapour cools high in the sky and forms droplets. This is…", "condensation", ["evaporation", "melting"], "Gas to liquid is condensation.", true],
  ["A puddle dries up on a sunny day. Where did the water go?", "into the air as water vapour", ["into the ground only", "it disappeared"], "Evaporation moves water into the air.", true],
  ["Why do weather stations record data over many days?", "to spot patterns and make better predictions", ["to make the day longer", "to stop storms"], "Patterns help us forecast.", true],
];

export const weather = bankUnit({
  id: "mb-weather-5",
  title: "Weather and the Water Cycle",
  emoji: "⛈️",
  blurb: "What makes the weather change",
  parentNote: "How the Sun, air, water and land interact to cause daily weather, the water cycle, tools for measuring weather, and why long-term forecasting is hard.",
  standards: ["SCI.5.E.9, SCI.5.E.10, SCI.5.E.11", "daily weather, the water cycle and weather prediction"],
  items: WEATHER,
});

const CLIMATE: Q[] = [
  ["Climate is…", "the long-term weather pattern of a region", ["today's weather", "the temperature right now"], "Climate is the pattern over many years."],
  ["Weather changes quickly. Climate…", "changes slowly over a long time", ["changes every hour", "never exists"], "Climate is an average."],
  ["Which is a statement about climate?", "Winters in Churchill are long and very cold.", ["It is snowing in Churchill today.", "It rained at lunch."], "Climate describes what is usual."],
  ["Which is a statement about weather?", "It is windy this afternoon.", ["Summers on the Prairies are usually warm.", "Deserts get little rain each year."], "Weather is what is happening now."],
  ["Which two things are used to describe climate?", "temperature and precipitation", ["colour and shape", "size and weight"], "Climate graphs show both."],
  ["Places closer to the equator are usually…", "warmer", ["colder", "windier all year"], "The Sun's rays are more direct near the equator."],
  ["Places closer to the poles are usually…", "colder", ["hotter", "wetter all year"], "The Sun's rays are spread out near the poles."],
  ["Latitude is…", "how far a place is north or south of the equator", ["how high it is", "how far from the sea"], "Latitude affects climate."],
  ["Higher places, such as mountains, are usually…", "cooler", ["warmer", "always dry"], "The air gets colder as you go up."],
  ["Why do places near large bodies of water often have milder weather?", "water warms and cools slowly", ["water makes the air heavier", "water blocks the Sun"], "Water holds heat longer than land."],
  ["Manitoba's winter is cold because…", "the Sun's rays are low and the land is far from warm oceans", ["the Sun turns off", "it is on the equator"], "Latitude and distance from oceans matter."],
  ["Which has a climate with lots of rain all year?", "a rainforest", ["a desert", "the Arctic tundra"], "Rainforests are wet and warm."],
  ["Which has a climate with very little rain?", "a desert", ["a rainforest", "a swamp"], "Deserts are dry."],
  ["A climate graph shows…", "average temperature and precipitation by month", ["the weather this hour", "wind direction"], "It is a summary over many years."],
  ["Ocean currents can change a region's climate by…", "carrying warm or cold water along coasts", ["stopping the wind", "making mountains"], "Warm currents warm nearby land."],
  ["What is a greenhouse effect?", "gases in the air trap some of the Sun's heat", ["clouds turn green", "plants make the air warmer by growing"], "It is natural, and more gas traps more heat."],
  ["Burning fossil fuels adds more of which gas to the air?", "carbon dioxide", ["helium", "oxygen only"], "Carbon dioxide traps heat."],
  ["What is meant by climate change?", "a long-term change in a region's weather patterns", ["a change in today's weather", "a new season"], "It is measured over many years."],
  ["Which action can help slow climate change?", "using less fuel by walking or biking", ["leaving lights on", "driving more"], "Using less fuel puts less carbon dioxide in the air."],
  ["Which source of power adds less carbon dioxide to the air?", "wind and solar", ["coal", "gasoline"], "Wind and sunshine do not burn fuel."],
  ["Planting trees can help because trees…", "take in carbon dioxide", ["make the Sun hotter", "stop rain"], "Trees use carbon dioxide to grow."],
  ["Why do scientists collect climate data for many years?", "to find long-term trends", ["to know tomorrow's temperature exactly", "to count the stars"], "A pattern needs lots of data."],
  ["Which region has a climate best for growing wheat?", "one with warm summers and enough rain", ["a desert with no water", "a glacier"], "Crops need warmth and water."],
  ["A place with cold, snowy winters and warm summers has…", "four distinct seasons", ["no seasons", "only one season"], "Many places in Manitoba are like this."],
  ["How do Indigenous Elders and knowledge keepers help us understand changes to the land?", "they share what they have observed over many generations", ["they decide the weather", "they build weather satellites"], "Traditional Knowledge records long-term change.", true],
  ["Why does permafrost melting matter in northern Manitoba?", "it can change the land and shake buildings and roads", ["it makes rain stop", "it cools the oceans"], "Frozen ground holds the land in place.", true],
  ["Why is one hot summer not proof of climate change?", "climate is measured over a long time", ["thermometers fail in summer", "summers are always cool"], "A single season is weather.", true],
  ["Which pair is correctly matched?", "weather: today's snow; climate: usual snowfall each winter", ["weather: usual snowfall; climate: today's snow", "weather: 30 years; climate: one hour"], "Weather is short term; climate is long term.", true],
  ["A farmer notes that frost now comes later each fall. This is evidence of a…", "change in climate pattern", ["change in the Moon", "new kind of wind vane"], "A pattern over many years suggests climate change.", true],
  ["Why do cities away from the sea often have bigger changes between summer and winter?", "land heats and cools faster than water", ["land weighs less than air", "the Sun is farther away"], "Seas keep temperatures steadier.", true],
];

export const climate = bankUnit({
  id: "mb-climate-5",
  title: "Climate",
  emoji: "🌎",
  blurb: "Weather patterns over many years",
  parentNote: "Climate as long-term weather patterns, what shapes a region's climate, and the ways human activity and the natural world affect it.",
  standards: ["SCI.5.E.12, SCI.5.D.7", "climate as long-term weather patterns, and the effect of human activity"],
  items: CLIMATE,
});

const CELLS: Q[] = [
  ["The basic unit of life is the…", "cell", ["atom", "organ"], "All living things are made of cells."],
  ["Which tool lets us see cells?", "microscope", ["telescope", "thermometer"], "Cells are too small to see with just our eyes."],
  ["All living things are made of…", "one or more cells", ["only one organ", "water alone"], "Some living things have just one cell."],
  ["An organism with only one cell is…", "unicellular", ["multicellular", "invisible"], "Uni means one."],
  ["An organism with many cells is…", "multicellular", ["unicellular", "a rock"], "Multi means many."],
  ["Which is a unicellular organism?", "bacterium", ["oak tree", "moose"], "A bacterium is one tiny cell."],
  ["Which is multicellular?", "a human", ["an amoeba", "a bacterium"], "People have trillions of cells."],
  ["What does the nucleus do?", "controls the cell's activities", ["stores water for the whole body", "makes sunlight"], "It is the cell's control centre."],
  ["What does the cell membrane do?", "controls what enters and leaves the cell", ["makes food from light", "keeps the cell perfectly still"], "It is like a gate."],
  ["Which part gives a plant cell its stiff shape?", "cell wall", ["nucleus", "cytoplasm"], "Plant cells have a rigid wall."],
  ["Which part of a plant cell captures sunlight?", "chloroplast", ["cell membrane", "nucleus"], "Chloroplasts hold the green chlorophyll."],
  ["The jelly-like fluid inside a cell is the…", "cytoplasm", ["nucleus", "cell wall"], "Other cell parts float in it."],
  ["Which cell part is found in plant cells but not animal cells?", "cell wall", ["nucleus", "cell membrane"], "Animal cells have no wall."],
  ["Cells need energy, which they get from…", "food", ["silence", "sleep only"], "Food gives cells energy."],
  ["Besides food, living cells need…", "water and oxygen", ["sand and rock", "paint"], "Cells need water, oxygen and a way to get rid of waste."],
  ["Cells must also be able to…", "get rid of waste", ["stay completely still", "stop taking in food"], "Waste can harm a cell."],
  ["Why do cells divide?", "to repair, replace and grow", ["to become smaller forever", "to stop working"], "New cells replace old ones."],
  ["A scrape on your knee heals because…", "cells divide to replace damaged cells", ["cells disappear", "the skin freezes"], "Division makes new skin cells."],
  ["A seedling grows taller because its cells…", "divide and get bigger", ["turn into water", "disappear"], "Growth means more cells."],
  ["Cells that do a special job are called…", "specialized cells", ["empty cells", "dead cells"], "Different cells do different jobs."],
  ["Which specialized cell carries messages in the body?", "nerve cell", ["red blood cell", "root hair cell"], "Nerve cells send signals."],
  ["Red blood cells carry…", "oxygen", ["light", "sound"], "They move oxygen around the body."],
  ["Which plant cell takes in water from soil?", "root hair cell", ["nerve cell", "skin cell"], "Root hair cells are long and thin."],
  ["Muscle cells help the body…", "move", ["see light", "carry oxygen"], "They shorten and relax."],
  ["A group of similar cells working together is a…", "tissue", ["molecule", "planet"], "Tissues form organs.", true],
  ["Which order goes from smallest to biggest?", "cell, tissue, organ, organ system", ["organ, cell, tissue, system", "system, organ, cell, tissue"], "Cells form tissues, tissues form organs.", true],
  ["The stomach is an example of a(n)…", "organ", ["cell", "tissue"], "It is made of several kinds of tissue.", true],
  ["The heart, blood vessels and blood form the…", "circulatory system", ["digestive system", "skeletal system"], "They work together to move blood.", true],
  ["Why do organ systems interact?", "to keep the body healthy and working", ["to make the body heavier", "they do not interact"], "Each system depends on the others.", true],
  ["The lungs take in oxygen. The circulatory system then…", "carries it to cells", ["throws it away", "turns it into food"], "Systems work together.", true],
];

export const cells = bankUnit({
  id: "mb-cells-5",
  title: "Cells: The Basic Unit of Life",
  emoji: "🔬",
  blurb: "Cell parts, needs and jobs",
  parentNote: "Cells as the basic unit of life, what living cells need, why cells divide, specialized cells in multicellular organisms, and how organ systems work together.",
  standards: ["SCI.5.E.13, SCI.5.E.14, SCI.5.E.15, SCI.5.E.16, SCI.5.E.17", "cells, their needs and division, specialized cells, and organ systems"],
  items: CELLS,
});

const FRICTION: Q[] = [
  ["A force is…", "a push, a pull or a twist", ["a kind of energy that has no effect", "a kind of light"], "Forces act on objects."],
  ["Which is a pull?", "opening a door by its handle", ["pushing a swing away", "kicking a ball"], "A pull moves something toward you."],
  ["Which is a push?", "kicking a ball", ["tugging a wagon", "opening a drawer by its knob"], "A push moves something away."],
  ["Which is a twist?", "turning a doorknob", ["throwing a ball", "lifting a book"], "A twist turns an object."],
  ["A force can make an object…", "start moving, stop or change direction", ["only get lighter", "disappear"], "Forces change motion."],
  ["Friction is a force that…", "slows or stops motion between surfaces that touch", ["speeds things up for free", "only works in air"], "Rubbing surfaces resist each other."],
  ["Which surface has the most friction?", "sandpaper", ["ice", "polished glass"], "Rough surfaces have more friction."],
  ["Which surface has the least friction?", "ice", ["carpet", "sandpaper"], "Smooth, slippery surfaces have less."],
  ["Why do we put sand on icy sidewalks?", "to add friction so people do not slip", ["to make them shine", "to melt ice faster than salt"], "Sand gives shoes something to grip."],
  ["Why do bike tires have treads?", "to grip the road", ["to make the bike lighter", "to make noise"], "Treads add friction."],
  ["Oil on a bike chain helps because…", "it reduces friction", ["it adds friction", "it makes the chain heavier"], "Lubricants make surfaces slide easily."],
  ["Rubbing your hands together makes them warm. Why?", "friction produces heat", ["the force disappears", "your hands get lighter"], "Rubbing turns motion into heat."],
  ["Which force always pulls objects toward the centre of Earth?", "gravity", ["magnetism", "friction"], "Gravity makes things fall."],
  ["A hockey puck slides far on ice because…", "there is little friction", ["there is a lot of friction", "gravity is off"], "Ice is slippery."],
  ["A heavy box is hard to slide across a carpet because of…", "friction", ["magnetism", "light"], "The carpet grips the box."],
  ["Which would reduce friction on a sled?", "waxing the runners", ["adding sandpaper under them", "pouring sand on the hill"], "Wax makes surfaces smoother."],
  ["Simple machines make work…", "easier by changing a force's size or direction", ["impossible", "heavier"], "They help us use forces."],
  ["Which is a simple machine?", "lever", ["battery", "thermometer"], "Levers, wheels, pulleys, ramps and screws are simple machines."],
  ["A ramp is also called an…", "inclined plane", ["axle", "pulley"], "It is a sloping surface."],
  ["A flagpole rope uses which simple machine?", "pulley", ["wedge", "ramp"], "A pulley changes the direction of a pull."],
  ["A seesaw is a…", "lever", ["wedge", "screw"], "A lever turns on a point called a fulcrum."],
  ["A wheel and axle makes it easier to…", "move things by rolling", ["twist a screw only", "cut wood"], "A wheel reduces friction when it rolls."],
  ["Which is a wedge?", "an axe blade", ["a flagpole", "a wheelbarrow wheel"], "A wedge splits things apart."],
  ["Friction can make a machine less efficient because…", "some energy is lost as heat", ["it makes more energy", "it stops gravity"], "Moving parts rub and lose energy.", true],
  ["Why do machines need regular oiling?", "to reduce friction between moving parts", ["to make the machine louder", "to make parts stick"], "Less friction means less waste and wear.", true],
  ["A pulley with a rusty axle is harder to turn. Why?", "more friction", ["less gravity", "more magnetism"], "Rust roughens the surfaces.", true],
  ["Which change makes a ramp easier to push a box up?", "make the ramp smoother and longer", ["make it rougher and steeper", "make the box heavier"], "Less friction and a gentler slope need less force.", true],
  ["Which is a benefit of friction?", "brakes stopping a bike", ["a machine heating up and wearing out", "a drawer sticking"], "Friction lets us stop.", true],
  ["A longer lever handle lets you…", "lift a load with less force", ["lift with more force", "make no difference"], "A longer arm gives more leverage.", true],
  ["An inclined plane makes work easier by…", "using a smaller force over a longer distance", ["using a bigger force over a shorter distance", "removing gravity"], "A gentle slope trades distance for force.", true],
];

export const friction = bankUnit({
  id: "mb-friction-5",
  title: "Forces, Friction and Machines",
  emoji: "🛷",
  blurb: "Pushes, pulls and rubbing surfaces",
  parentNote: "Forces as pushes, pulls and twists, how friction affects motion, and how friction makes simple machines less efficient.",
  standards: ["SCI.5.E.5, SCI.5.E.6, SCI.5.E.8", "forces, the effects of friction on motion, and friction in machines"],
  items: FRICTION,
});
