import { bankUnit, type Q } from "../own";

// Grade 5 social studies, The Mosaic of Canada: First Peoples, early European colonization, the fur trade,
// and Canada before and at Confederation. Indigenous content is written in the present tense where it is about
// living communities, and says "some" or "many" because each Nation is different.

const FIRST: Q[] = [
  ["First Peoples have lived in North America for…", "thousands of years", ["about 100 years", "only since 1867"], "Their stories and history go back a very long time."],
  ["Many First Nations share stories about…", "where their people came from", ["how to use the internet", "only the weather"], "Origin stories are an important part of many cultures."],
  ["Scientists have a theory that people first came to North America by…", "crossing a land bridge from Asia", ["sailing from Africa", "flying"], "Some scientists study migration from Asia during the ice age."],
  ["Many First Peoples' stories teach that their people have always been here. This is…", "a different way of knowing from the migration theory", ["a mistake", "a modern invention"], "Stories and science can sit side by side."],
  ["The ice age changed the land by…", "carving valleys and lakes with moving ice", ["growing deserts", "making volcanoes"], "Glaciers shaped the land."],
  ["Much of Manitoba's land was once covered by a huge glacial lake called…", "Lake Agassiz", ["Lake Ontario", "Lake Louise"], "Lake Agassiz left rich, flat soil."],
  ["What are First Peoples?", "the original peoples of North America", ["people who arrived in 1867", "only one Nation"], "They include First Nations, Métis and Inuit."],
  ["Which of these are First Peoples groups in Canada?", "First Nations, Métis and Inuit", ["British, French and Dutch", "Loyalists and Acadians"], "These three groups are recognized in Canada."],
  ["Before contact with Europeans, First Peoples cultures were…", "diverse, with many languages and ways of life", ["all the same", "unknown"], "Each Nation had its own culture."],
  ["Which Nation traditionally lived on the Prairies and followed the bison?", "Plains Cree", ["West Coast Haida", "Inuit of the Arctic"], "Many Plains Nations depended on bison."],
  ["Which People are known for living in the Arctic and using igloos and kayaks?", "Inuit", ["Haida", "Mi'kmaq"], "Inuit homelands stretch across the North."],
  ["Which Nations lived in longhouses near the Great Lakes?", "Haudenosaunee", ["Inuit", "Plains Cree"], "Haudenosaunee longhouses held several families."],
  ["Why did food, clothing and shelter differ between Nations?", "they used what the local land provided", ["they all ignored the land", "they bought them from stores"], "People adapted to their environment."],
  ["Many Plains peoples used tipis because they were…", "easy to move with the bison herds", ["too heavy to move", "made of ice"], "Tipis could be taken down and carried."],
  ["Which Nation traditionally lived on the West Coast and built big cedar houses?", "Haida", ["Plains Cree", "Inuit"], "Cedar was plentiful there."],
  ["How did many First Peoples show respect for the land?", "by using only what they needed and giving thanks", ["by taking as much as they could", "by ignoring animals"], "Many teachings stress respect and balance."],
  ["Oral tradition means…", "knowledge passed down by telling and listening", ["only written books", "TV shows"], "Elders and storytellers share history."],
  ["Why is oral tradition important to many First Peoples?", "it carries history, laws and teachings from generation to generation", ["it is only for fun", "it replaced all writing"], "Knowledge is kept through spoken stories."],
  ["Leadership in some First Peoples communities was by…", "hereditary right, in other places by consensus", ["one law for all of them", "a vote at a store"], "Different Nations organized leadership differently."],
  ["In some communities, women held leadership roles. This is called…", "matriarchy or women's leadership", ["monarchy only", "dictatorship"], "Some societies, such as the Haudenosaunee, honoured women leaders."],
  ["First Peoples communities traded with each other by…", "exchanging goods such as furs, tools and food", ["using credit cards", "only using money"], "Trade routes crossed the continent."],
  ["Besides trade, First Peoples nations also…", "worked together and made alliances", ["never spoke to one another", "built roads of asphalt"], "They shared knowledge and sometimes formed alliances."],
  ["Which is a way to show respect for a story told by an Elder?", "listen quietly and thoughtfully", ["interrupt", "ignore it"], "Listening is a form of respect."],
  ["Which of these is a primary source about First Peoples history?", "a story told by an Elder from the community", ["a made-up cartoon", "a rumour"], "A person with knowledge from the community is a strong source."],
  ["Why should we say “some” or “many” when we describe First Peoples?", "because each Nation has its own culture", ["because they are all the same", "because nobody knows"], "Avoid treating all Nations as one.", true],
  ["First Peoples communities in Canada today are…", "living, growing communities", ["only in the past", "no longer here"], "Cultures and languages continue.", true],
  ["What can help us learn about First Peoples with respect?", "ask and listen to people from the Nation", ["guess from movies", "copy sacred things"], "Learn from community members.", true],
  ["Why is it good to value diverse approaches to leadership?", "different ways can work well and teach us", ["only one is allowed", "leaders are never needed"], "Leadership can look different in different places.", true],
  ["Which is an example of First Peoples' connection to the land?", "teachings that say people are part of nature", ["building cities of glass", "ignoring the seasons"], "Many teachings link people with animals, plants and water.", true],
];

export const firstPeoples = bankUnit({
  id: "mb-first-peoples-5",
  title: "First Peoples Before Contact",
  emoji: "🪶",
  blurb: "Stories, land and leadership",
  parentNote: "First Peoples' origin stories and migration theories, the ice age and the land, how diverse Nations lived, led and traded, and why oral tradition matters. The wording says 'some' and 'many' because each Nation is different. This content needs review with Indigenous partners.",
  standards: ["5-KI-004, 5-KI-005, 5-KI-006, 5-KL-014, 5-KL-017, 5-KP-046, 5-KE-050, 5-VH-008, 5-VP-014", "First Peoples' stories, cultures, land and leadership before contact"],
  items: FIRST,
});

const EUROPE: Q[] = [
  ["Which Europeans set up Nouvelle-France?", "the French", ["the Spanish", "the Dutch only"], "Nouvelle-France means New France."],
  ["Which explorer founded Québec in 1608?", "Samuel de Champlain", ["Jacques Cartier", "Henry Hudson"], "Champlain founded Québec in 1608."],
  ["Which explorer sailed up the St. Lawrence River in 1534?", "Jacques Cartier", ["Samuel de Champlain", "John Cabot"], "Cartier claimed land for France."],
  ["John Cabot was sent by England to find…", "a sea route to Asia", ["gold in Alaska", "Winnipeg"], "Cabot reached Newfoundland in 1497."],
  ["Which Europeans came to L'Anse aux Meadows about 1000 years ago?", "Norse", ["British", "Spanish"], "A Norse camp has been found in Newfoundland."],
  ["Many Europeans explored hoping to find…", "the Northwest Passage to Asia", ["a way to the Moon", "Manitoba"], "A short route to Asia would have helped trade."],
  ["Why did Europeans expand their territories into North America?", "for trade, wealth, land and to spread their religion", ["they were invited by all Nations", "to hide from the Sun"], "Europeans competed for wealth and power."],
  ["Which countries built colonial empires in North America?", "France and Britain", ["Egypt and India", "Canada and Mexico"], "Both claimed land and fought over it."],
  ["In Nouvelle-France, the seigneurial system was…", "a way of dividing land among landowners and farmers", ["a school system", "a kind of sailing"], "A seigneur held land and the habitants farmed it."],
  ["A habitant in Nouvelle-France was usually a…", "farmer", ["king", "sailor"], "Habitants worked the land."],
  ["Who ran the royal government in Nouvelle-France?", "a governor appointed by the king of France", ["elected mayors", "First Nations chiefs"], "The king had the final say."],
  ["Which religion was most common in Nouvelle-France?", "Roman Catholic", ["Hindu", "Buddhist"], "The Church played a big role."],
  ["Early settlers in Atlantic Canada included…", "French and British people", ["Japanese", "Portuguese only"], "Both set up settlements."],
  ["Acadia was a French colony in…", "what is now the Maritime provinces", ["what is now Manitoba", "what is now Yukon"], "The Acadians lived by the sea."],
  ["The Acadian deportation, beginning in 1755, was when…", "the British forced many Acadians to leave their homes", ["Acadians chose to leave happily", "the French took over Acadia"], "Families were separated and sent away."],
  ["The Battle of the Plains of Abraham in 1759 was part of…", "the British conquest of Nouvelle-France", ["the Acadian deportation", "the fur trade"], "Britain won and took control."],
  ["After the conquest, Nouvelle-France became a…", "British colony", ["Spanish colony", "separate country"], "Britain took control in 1763."],
  ["Which European wars affected First Peoples and colonies?", "wars between France and Britain", ["wars with no effect", "wars in Asia only"], "First Peoples were pulled into the conflicts."],
  ["Early settlements were often built beside…", "rivers and the sea", ["deserts", "mountain peaks"], "Water was the best way to travel."],
  ["Which factor helped Europeans move around early Canada?", "rivers and lakes", ["paved highways", "airports"], "Boats on waterways were the main route."],
  ["Diseases from Europe affected First Peoples by…", "making many people very ill", ["making them stronger", "having no effect"], "People had no past protection from them."],
  ["First Peoples helped early Europeans by…", "sharing food, guiding and trading", ["building their ships", "writing their maps first"], "Many settlers survived with Indigenous help."],
  ["Missionaries came to Canada to…", "teach their religion", ["trade furs only", "study the weather"], "Many missionaries worked with First Peoples."],
  ["How did First Peoples' and Europeans' views of using natural resources often differ?", "Europeans often saw resources to sell, while many First Peoples emphasized sharing and balance", ["Neither used any resources", "All of them agreed completely"], "Ideas about land and use were different."],
  ["Which statement shows empathy for the struggles of early peoples?", "Many Acadian families lost their homes and had to start over.", ["Everyone had an easy life.", "Nothing was hard then."], "Empathy is understanding how others felt.", true],
  ["Why did France and Britain compete for North America?", "for land, resources and power", ["for sports trophies", "to avoid trade"], "Each wanted a bigger empire.", true],
  ["Canada's heritage includes…", "Indigenous, French and British roots", ["only British roots", "only French roots"], "These three heritages are part of Canada's story.", true],
  ["Place names such as Winnipeg and Manitoba come from…", "First Nations words", ["British kings", "French saints only"], "Many Canadian place names come from Indigenous languages.", true],
  ["Why is it good to read different accounts of the same event?", "they can show different points of view", ["they are always the same", "history never changes"], "Comparing accounts gives a fuller picture.", true],
  ["A timeline helps us…", "put events in order", ["measure rain", "draw a map"], "Events are shown from earliest to latest.", true],
];

export const earlyColonies = bankUnit({
  id: "mb-early-colonies-5",
  title: "Exploration and Early Colonies",
  emoji: "⛵",
  blurb: "Nouvelle-France and early Canada",
  parentNote: "European explorers and colonists, daily life and government in Nouvelle-France and Atlantic Canada, the Acadian deportation, the British conquest, and the impact on First Peoples.",
  standards: ["5-KI-007, 5-KI-008, 5-KL-018, 5-KL-019, 5-KH-025, 5-KH-026, 5-KH-027, 5-KH-028, 5-KH-029, 5-KH-033, 5-KG-043, 5-KP-047, 5-KP-048, 5-KE-051, 5-VH-009, 5-VH-011, 5-VH-012", "early European colonization of Canada, Nouvelle-France and the Acadian deportation"],
  items: EUROPE,
});

const FUR: Q[] = [
  ["The fur trade was a business of…", "trading animal furs for goods", ["selling cars", "farming wheat only"], "Furs were traded for tools, cloth and more."],
  ["Which fur was in highest demand in Europe?", "beaver", ["moose", "rabbit"], "Beaver pelts were made into felt hats."],
  ["Why did Europeans want beaver fur?", "it made fashionable felt hats", ["it was used as food", "it made glass"], "European fashion drove the trade."],
  ["What did First Peoples receive in the fur trade?", "metal tools, cloth, kettles and guns", ["computers", "cars"], "Goods from Europe were traded for furs."],
  ["Which company was started in 1670 and traded around Hudson Bay?", "the Hudson's Bay Company", ["the North West Company", "the Canadian Pacific Railway"], "The HBC began in 1670."],
  ["The North West Company was based in…", "Montréal", ["Churchill", "Halifax"], "It competed with the HBC."],
  ["Which is a major trading post at the mouth of the Nelson and Hayes rivers in Manitoba?", "York Factory", ["Fort Garry", "Fort William only"], "York Factory was the HBC's chief depot."],
  ["The Hudson's Bay Company mostly used which route to ship goods to Europe?", "Hudson Bay", ["the Pacific Ocean", "the Gulf of Mexico"], "Ships came to posts on the bay."],
  ["The North West Company used which method to move furs?", "birchbark and big canoes along rivers", ["airplanes", "large trucks"], "Voyageurs paddled long distances."],
  ["A voyageur was a…", "canoe-paddler who carried goods and furs", ["bank worker", "teacher"], "Voyageurs travelled long routes."],
  ["Coureurs de bois were…", "French traders who travelled in the woods", ["Spanish soldiers", "farmers in Québec"], "They traded furs without licences."],
  ["Pierre-Esprit Radisson and Médard Chouart des Groseilliers helped start…", "the Hudson's Bay Company", ["Confederation", "the Red River cart trade"], "They saw the value of Hudson Bay."],
  ["Who guided traders, hunted and prepared furs?", "First Nations and Métis men and women", ["only Europeans", "nobody"], "The trade depended on Indigenous skills."],
  ["The fur trade could not work without…", "First Nations and Red River Métis workers", ["airplanes", "telephones"], "They provided knowledge, furs and labour."],
  ["Pemmican was a food made from…", "dried bison meat, fat and berries", ["potatoes and milk", "rice and fish"], "It kept for a long time and fed fur trade workers."],
  ["Who were the Métis?", "a people with both First Nations and European roots, with their own culture", ["only French traders", "only Cree families"], "The Métis are a distinct Indigenous people."],
  ["The Red River Métis lived mainly around…", "what is now Winnipeg and the Red River", ["Vancouver Island", "Halifax"], "Red River was the Métis homeland in Manitoba."],
  ["The Red River cart was a…", "wooden two-wheeled cart pulled by oxen or horses", ["steam train", "motorboat"], "It was very useful on the Prairies."],
  ["The Métis hunted…", "bison on the Prairies", ["whales in the Atlantic", "elephants"], "The buffalo hunt was a big event each year."],
  ["The Red River Métis helped the fur trade by…", "supplying pemmican, hauling goods and guiding", ["building railways", "making cars"], "They were skilled hunters and freighters."],
  ["Where did the fur trade expand to over time?", "the west and north of Canada", ["only the east", "only the south"], "Traders went where the beaver were."],
  ["Why did trading posts get built near rivers?", "boats and canoes were the best way to travel", ["roads were everywhere", "it was fun"], "Waterways were highways."],
  ["Canadian place names often tell us about…", "history, people and languages", ["nothing at all", "only the weather"], "Many places are named for people or First Nations words."],
  ["Competition between the HBC and the North West Company led to…", "conflict and, in 1821, a merger", ["both closing in 1700", "an end to all trade"], "The companies joined in 1821.", true],
  ["How did the land affect the fur trade?", "posts were built where furs and waterways were", ["posts were built in deserts", "land did not matter"], "Geography shaped where trading was done.", true],
  ["Why were farmers sometimes in conflict with fur traders?", "farms changed the land that fur animals needed", ["farmers wanted fewer crops", "traders loved farming"], "Settlement can harm hunting grounds.", true],
  ["How did the fur trade change First Peoples' lives?", "it brought new goods and new competition, and also disease and change", ["it changed nothing", "it ended all trade"], "There were benefits and harms.", true],
  ["Which group deserves appreciation for the fur trade's success?", "First Nations, Métis, French and British people together", ["only the British", "only the French"], "Many peoples took part.", true],
  ["The fur trade is part of Manitoba's history because…", "many posts and routes were in what is now Manitoba", ["there were no animals here", "it never reached here"], "Rivers like the Red and Nelson were important routes.", true],
  ["Fur trade stories help us learn history. They are mostly…", "accounts told from different points of view", ["exactly the same everywhere", "never useful"], "Different people tell the story differently.", true],
];

export const furTrade = bankUnit({
  id: "mb-fur-trade-5",
  title: "The Fur Trade and the Red River Métis",
  emoji: "🛶",
  blurb: "Trade, routes and the Métis",
  parentNote: "The fur trade, the Hudson's Bay and North West Companies, the people who made it work, and the origins and rise of the Red River Métis. Needs review with Métis partners.",
  standards: ["5-KI-009, 5-KL-020, 5-KL-021, 5-KH-030, 5-KH-031, 5-KH-032, 5-KH-034, 5-KH-035, 5-KH-036, 5-KG-044, 5-KP-049, 5-KE-052, 5-KE-053, 5-VI-003, 5-VL-007", "the fur trade, its people and routes, and the Red River Métis"],
  items: FUR,
});

const BEFORE: Q[] = [
  ["The United Empire Loyalists were people who…", "stayed loyal to Britain and left the United States", ["fought for American independence", "were French farmers"], "They moved north after the American Revolution."],
  ["Why did the Loyalists move to what is now Canada?", "they were loyal to Britain and faced danger in the United States", ["Canada had no winters", "to find gold in Manitoba"], "They wanted to stay British subjects."],
  ["The War of 1812 was fought between…", "Britain (with Canada) and the United States", ["France and Spain", "Canada and Mexico"], "It happened in British North America."],
  ["Which Shawnee leader fought alongside the British in the War of 1812?", "Tecumseh", ["Louis Riel", "Samuel de Champlain"], "Tecumseh led an alliance of Nations."],
  ["Who is remembered for warning the British of a surprise American attack in 1813?", "Laura Secord", ["Isaac Brock", "Marie-Anne Gaboury"], "Laura Secord walked a long way to warn them."],
  ["The Selkirk Settlement was set up by…", "Lord Selkirk, along the Red River", ["Louis Riel, in Halifax", "John A. Macdonald, in Toronto"], "Scottish settlers arrived in 1812."],
  ["Who helped the Selkirk settlers survive early winters?", "First Nations and Métis neighbours", ["no one", "only British soldiers"], "Local peoples shared food and knowledge."],
  ["The 1837–1838 Rebellions were about…", "people wanting more say in how they were governed", ["a war over fur", "building the railway"], "Reformers wanted responsible government."],
  ["Who led the rebellion in Lower Canada?", "Louis-Joseph Papineau", ["William Lyon Mackenzie", "George-Étienne Cartier"], "He led the Patriotes."],
  ["Who led the rebellion in Upper Canada?", "William Lyon Mackenzie", ["Louis-Joseph Papineau", "John Cabot"], "Mackenzie led reformers around Toronto."],
  ["Confederation means…", "provinces joining together to form one country", ["a battle", "a kind of treaty with France"], "Canada began in 1867."],
  ["In what year did Canada become a country?", "1867", ["1812", "1759"], "Confederation was July 1, 1867."],
  ["Which four provinces formed Canada in 1867?", "Ontario, Quebec, Nova Scotia and New Brunswick", ["Manitoba, Alberta, BC and Yukon", "Ontario, Quebec, BC and Alberta"], "Manitoba joined in 1870."],
  ["When did Manitoba join Confederation?", "1870", ["1867", "1905"], "The Red River Resistance led to the Manitoba Act of 1870."],
  ["Who were the “Fathers of Confederation” who worked to build Canada?", "John A. Macdonald, George-Étienne Cartier and others", ["Champlain and Cartier", "Laura Secord and Tecumseh"], "They were political leaders in the 1860s."],
  ["Who was Canada's first prime minister?", "John A. Macdonald", ["Wilfrid Laurier", "Louis Riel"], "He led from 1867."],
  ["Why did some people argue for Confederation?", "to build a railway, share defence and trade more", ["to give up Canada", "to end all trade"], "Joining together had advantages."],
  ["Why did some people argue against Confederation?", "they feared losing local control or paying higher taxes", ["they wanted a bigger city", "they wanted fewer people"], "Some Maritimers worried about their voice."],
  ["Who could vote in 1867?", "mainly men who owned property", ["every adult", "all children"], "Women, most Indigenous people and many others could not."],
  ["In 1867, which group could generally NOT vote?", "women", ["landowning men", "some wealthy men"], "Women got the vote later."],
  ["Citizenship in 1867 differed from today because…", "rights depended on gender, wealth and background", ["everyone had equal rights", "there were no laws"], "Many rights were limited then."],
  ["Today, Canadian citizens have rights such as…", "voting and equal treatment under the law", ["no rights at all", "rights only for the rich"], "The Charter protects rights."],
  ["Responsibilities of citizens today include…", "obeying laws and respecting others' rights", ["ignoring laws", "avoiding school"], "Rights come with responsibilities."],
  ["How did Canada East and Canada West differ?", "language, religion and laws", ["only weather", "nothing"], "Canada East was mostly French and Catholic; Canada West was mostly English and Protestant."],
  ["Migration to another country can affect people's identities because…", "they may keep some customs and take on new ones", ["they forget everything", "nothing changes"], "Identity can grow and change.", true],
  ["Why did people immigrate to Canada in the 1800s?", "to escape hardship such as famine and to find land", ["to avoid the sea", "because it was warm"], "Hard times in Europe pushed people to leave.", true],
  ["How did European views of First Peoples change between 1763 and 1867?", "from partners to people some wrongly saw as dependent", ["they never changed", "they all admired them"], "Views shifted in unfair ways.", true],
  ["Where were traditional Métis lands and communities in the west?", "along the Red and Assiniboine rivers and across the Prairies", ["on the Atlantic coast", "only in the Arctic"], "Red River was the heart of Métis lands.", true],
  ["Why value history as a way of understanding Canada today?", "it explains how our country and communities came to be", ["it has no connection", "it is just old"], "The past shapes the present.", true],
];

export const confederation = bankUnit({
  id: "mb-confederation-5",
  title: "Building Canada: Before and at Confederation",
  emoji: "🍁",
  blurb: "Loyalists to Confederation",
  parentNote: "Pre-Confederation Canada: the Loyalists, the War of 1812, the Selkirk Settlement, the 1837-1838 Rebellions, the road to Confederation and what citizenship meant in 1867 compared with today.",
  standards: ["5-KC-001, 5-KC-002, 5-KC-003, 5-KI-010, 5-KI-011, 5-KI-012, 5-KI-013, 5-KL-022, 5-KL-023, 5-KH-037, 5-KH-038, 5-KH-039, 5-KH-040, 5-KH-041, 5-KH-042, 5-KG-045, 5-VH-010", "pre-Confederation events, Confederation and citizenship in 1867"],
  items: BEFORE,
});

const SKILLS: Q[] = [
  ["A map title tells you…", "what the map shows", ["how old the mapmaker is", "which way is north"], "The title names the topic."],
  ["A map legend (key) explains…", "what the symbols mean", ["where the map was printed", "how long the trip is"], "Legends decode the symbols."],
  ["A compass rose shows…", "the directions", ["the scale", "the date"], "It points N, S, E and W."],
  ["Which direction is opposite to north?", "south", ["east", "west"], "North and south are opposites."],
  ["A map scale lets you…", "work out real distances", ["see the weather", "find the capital"], "One centimetre on the map may be many kilometres."],
  ["Latitude lines run…", "east and west, parallel to the equator", ["north to south", "up and down only"], "They measure distance north or south of the equator."],
  ["Longitude lines run…", "north to south, from pole to pole", ["east and west", "around the equator only"], "They measure distance east or west of the prime meridian."],
  ["The equator is at…", "0° latitude", ["90° latitude", "0° longitude"], "It splits Earth into north and south."],
  ["A grid on a map helps you…", "find a place using letters and numbers", ["hide a place", "change the scale"], "Coordinates name a square."],
  ["A primary source is…", "created by someone who was there", ["a book written 100 years later", "a guess"], "Letters, diaries and photos from the time are primary sources."],
  ["Which is a secondary source?", "a textbook about the fur trade", ["a trader's diary", "a photo taken in 1850"], "A textbook was written later by someone who was not there."],
  ["Which is a primary source?", "a diary kept by a settler", ["an encyclopedia", "a school website about history"], "It was written at the time."],
  ["A fact can be…", "checked and proven", ["only a feeling", "always changing"], "An opinion is what someone thinks."],
  ["Which is an opinion?", "The Red River cart was the best invention ever.", ["The Red River cart had two wheels.", "Red River carts were made of wood."], "“Best” is a personal judgment."],
  ["Which is a fact?", "Canada became a country in 1867.", ["Confederation was the best year ever.", "Everybody loved the railway."], "A date can be checked."],
  ["Why compare two accounts of the same event?", "to see different perspectives", ["to find the shortest one", "because they are always the same"], "Different people see events differently."],
  ["Bias means…", "an unfair leaning toward one view", ["a map scale", "a kind of source"], "We look for bias when we check sources."],
  ["Which question helps you check if a source is trustworthy?", "Who made it, and why?", ["How many pages is it?", "What colour is the cover?"], "Purpose and author matter."],
  ["Which is a respectful way to disagree in a group?", "listen first, then share your idea politely", ["interrupt loudly", "refuse to talk"], "Listening is a key skill."],
  ["Your group has a conflict. A fair first step is to…", "each person explains their view calmly", ["leave the group", "decide alone"], "Understanding comes before solving."],
  ["Another peaceful way to solve a conflict is to…", "negotiate and compromise", ["shout", "ignore it forever"], "Each side gives a little."],
  ["A timeline shows…", "events in order", ["distance", "temperature"], "It is a visual organizer for history."],
  ["Which belongs on a timeline of Canada?", "1867 Confederation", ["a recipe", "a map scale"], "Dates with events go on timelines."],
  ["When you visit a historic burial ground you should…", "be respectful and quiet", ["climb the stones", "take things away"], "Places of historical importance deserve respect.", true],
  ["Using Traditional Knowledge to read the land means…", "learning from what Elders know about signs on the land", ["ignoring the landscape", "using only a phone"], "Knowledge keepers teach how to read the land.", true],
  ["You read two stories about the same event that disagree. What should you do?", "check more sources and think about each view", ["pick the shortest", "decide one must be silly"], "Compare diverse perspectives.", true],
  ["History can change as new information is found. This means…", "our understanding can grow over time", ["history never changes", "old stories are wrong always"], "New evidence sometimes changes the story.", true],
  ["A web page has no author and no date. How trustworthy is it?", "less trustworthy until you can check it", ["completely trustworthy", "always right"], "A good source says who and when.", true],
  ["To make a decision fair for everyone you should…", "consider how it affects each person", ["only think of yourself", "flip a coin without thinking"], "Fairness looks at everyone.", true],
  ["You notice a joke that treats a group unfairly. That is…", "bias or discrimination, and it is kind to speak up", ["good humour", "a fact"], "Recognize bias and suggest a fair solution.", true],
];

export const skills = bankUnit({
  id: "mb-history-skills-5",
  title: "Maps, Sources and Fair Thinking",
  emoji: "🧭",
  blurb: "Read maps and check sources",
  parentNote: "Reading and building maps with latitude and longitude, telling primary from secondary sources and fact from opinion, comparing points of view, and working fairly with others.",
  standards: ["5-S-100, 5-S-101, 5-S-102, 5-S-105, 5-S-202, 5-S-204, 5-S-206, 5-S-207, 5-S-304, 5-S-306, 5-S-307, 5-S-308", "map skills, historical sources, fact and opinion, and working fairly with others"],
  items: SKILLS,
});
