import { bankUnit, type Q } from "../own";

// More Grade 6 science units for the Manitoba outcomes: electrical safety, the nature of species, how science works
// and scientific measurement.

const SAFETY: Q[] = [
  ["Why should you never use a hair dryer near a filled bathtub or sink?", "Water can carry electricity and cause a shock", ["The dryer might get too cold", "It will make the water boil"], "Water and electricity are a dangerous mix."],
  ["Is it safe to touch a plugged-in appliance with wet hands?", "No, wet hands make a shock more likely", ["Yes, water protects you", "Yes, if it is a small appliance"], "Dry your hands first."],
  ["A power line has fallen on the ground. What should you do?", "Stay far away and tell an adult to call for help", ["Touch it with a stick", "Walk across it carefully"], "Always treat a downed line as live."],
  ["Why should you never put a metal object into a wall outlet?", "It can cause a serious shock", ["It will fill up the outlet", "It can make the wall cold"], "Outlets carry household electricity."],
  ["When you unplug a cord, you should…", "pull the plug, not the cord", ["pull the cord hard", "swing the cord around"], "Pulling on the cord can damage it."],
  ["What should you do if a cord is frayed or the wires show?", "Stop using it and tell an adult", ["Wrap it in a paper towel", "Keep using it carefully"], "Damaged cords can cause shocks or fires."],
  ["Which is a safe battery habit?", "Use batteries made for the device and never open them", ["Heat a battery in an oven", "Cut a battery open"], "Batteries can leak or burst."],
  ["Why shouldn’t you connect the two ends of a battery with a wire and nothing else?", "It makes a short circuit that can get hot", ["It will make the battery bigger", "It will make a rainbow"], "A short circuit lets too much current flow."],
  ["Why is a swallowed button battery an emergency?", "It can burn the body very quickly", ["It makes a person taller", "It tastes sweet"], "Get medical help right away."],
  ["What is the job of a fuse or a circuit breaker?", "To stop the electricity when too much current flows", ["To make the lights brighter", "To store power"], "They protect wires from overheating."],
  ["Which is a risk of plugging too many devices into one outlet?", "The wires can overheat and cause a fire", ["The devices will run faster", "The power turns to water"], "Do not overload outlets."],
  ["What should you do during a thunderstorm?", "Stay inside and away from plugged-in electronics and water", ["Fly a kite outside", "Stand under a tall tree"], "Lightning is a huge discharge of electricity."],
  ["Why should you not climb a tree near power lines?", "You could touch a line and be shocked", ["The tree would be too small", "Lines make branches break"], "Stay well away from lines."],
  ["The electricity in a Canadian wall outlet is about 120 volts. A flashlight battery is about 1.5 volts. Which is more dangerous to touch?", "The wall outlet", ["The battery", "They are the same"], "Higher voltage can push more current through you."],
  ["Why do we use small batteries for classroom circuits?", "Their low voltage is much safer than household electricity", ["They are more colourful", "They can’t be used up"], "Low-voltage DC is safe to handle with care."],
  ["Why wear safety goggles or follow safety steps when building circuits?", "To protect your eyes and avoid hazards if something heats up", ["To see the colours better", "To hear louder"], "Follow your teacher’s safety rules."],
  ["A wire in a circuit feels hot. What should you do?", "Disconnect the battery and tell your teacher", ["Squeeze the wire", "Add another battery"], "Heat means something is wrong."],
  ["Which of these is a good rule for using electric appliances at home?", "Ask an adult before using them and keep them dry", ["Use them in the bath", "Leave them on all night"], "Follow safety rules.", true],
  ["Before changing a light bulb, you should…", "switch the light off and let the bulb cool", ["leave it on to see better", "touch the metal base"], "Bulbs can be hot and the socket is live.", true],
  ["Which statement about extension cords is the safest?", "Use them only for a short time and do not run them under a rug", ["Run them under carpets", "Plug many cords together in a chain"], "Covered cords can overheat.", true],
  ["Why do bathrooms and kitchens often have special outlets that shut off quickly if they sense a leak of current?", "Water is near, so extra protection against shocks is needed", ["Bathrooms need more lights", "To save energy"], "These are called ground-fault outlets.", true],
  ["Some devices have a plastic or rubber covering on wires. Why?", "Plastic and rubber are insulators that keep electricity in the wire", ["They make wires taste better", "They make metal heavier"], "Insulators do not let current flow easily.", true],
  ["Which pair is a conductor and an insulator?", "Copper wire, rubber", ["Rubber, plastic", "Glass, wood"], "Metals like copper conduct; rubber insulates.", true],
  ["Why can a damaged battery that is swollen or leaking be a hazard?", "It may contain chemicals that can burn skin or start a fire", ["It is too light", "It is out of fashion"], "Tell an adult and do not use it.", true],
  ["Which is the safest way to charge a device?", "Use the right charger and keep it on a hard, dry surface", ["Charge it under a pillow", "Use any charger you find"], "Charging can make heat.", true],
  ["Who should repair a broken electrical appliance?", "A trained adult or professional", ["You, with a fork", "Nobody; wet it first"], "Repairs can be dangerous.", true],
];

export const electricalSafety = bankUnit({
  id: "mb-electrical-safety",
  title: "Electrical Safety",
  emoji: "⚠️",
  blurb: "Stay safe around plugs, batteries, power lines and water.",
  parentNote:
    "Practises safety rules for household electricity, batteries and circuits: keeping electricity away from water, handling cords and plugs, power lines, and safe use of low-voltage batteries.",
  standards: ["SCI.6.E.7, SCI.6.C.4", "safety precautions for electricity, and using equipment safely"],
  items: SAFETY,
});

const SPECIES: Q[] = [
  ["A species is a group of living things that…", "can breed with each other and have offspring that survive and can also breed", ["all live in the same country", "all have the same colour"], "Members of a species can produce viable offspring."],
  ["Offspring are…", "the young that come from parents", ["the parents’ food", "the nest"], "A foal is the offspring of a horse."],
  ["A hybrid is the offspring of…", "two different species or varieties", ["two identical twins", "one plant only"], "Hybrids mix traits from two kinds of parents."],
  ["A mule is the offspring of…", "a horse and a donkey", ["a cow and a goat", "a dog and a cat"], "The parents are two different species."],
  ["Mules are usually unable to have young of their own. This is a clue that…", "a horse and a donkey are separate species", ["mules are a type of tree", "mules live in water"], "If hybrids cannot breed, the parents are separate species."],
  ["A liger is the offspring of a…", "male lion and female tiger", ["wolf and a fox", "cow and a horse"], "They are two different big cat species."],
  ["A grolar bear (or pizzly bear) comes from a…", "polar bear and a grizzly bear", ["black bear and a panda", "moose and a bear"], "It is a hybrid of two bear species."],
  ["A coydog is the offspring of a…", "coyote and a dog", ["bobcat and a lynx", "rabbit and a fox"], "A coyote is a wild canid; a dog is a domestic one."],
  ["Why might a polar bear and a grizzly bear meet and breed in the wild?", "Warming Arctic conditions can bring their ranges closer together", ["They share a den every winter", "They both fly south"], "Changing habitat can bring species together."],
  ["Farmers often grow hybrid crops. Why?", "Crossing two varieties can give plants with useful traits like disease resistance", ["Hybrid plants never need water", "Hybrid plants are made in factories"], "People choose parent plants for helpful traits."],
  ["Hybrid corn is made by…", "crossing two different varieties of corn", ["painting the corn", "freezing the seeds"], "Breeders pick parent varieties."],
  ["Which pair would most likely be the same species?", "Two golden retrievers", ["A frog and a hawk", "A tulip and a trout"], "They can breed and have fertile pups."],
  ["Which statement is true?", "Two dogs of different breeds can still breed together and have puppies that can breed", ["Different dog breeds are different species", "Dogs cannot breed"], "All dog breeds belong to the same species."],
  ["The word viable means…", "able to live and grow", ["very large", "very loud"], "Viable offspring can survive."],
  ["Why do scientists group living things into species?", "To describe and organize the variety of life", ["To decide who is the strongest", "To rename animals every year"], "Classification helps us study life."],
  ["A hybrid animal is raised in a zoo. Which is the best description?", "It has traits from both parent species", ["It has no parents", "It is a new kind of plant"], "A hybrid shows a mix of traits."],
  ["Would you expect a rose and a rabbit to breed?", "No, they are very different living things", ["Yes, always", "Yes, in winter only"], "Plants and animals cannot produce offspring together."],
  ["A bird book says two kinds of ducks sometimes breed in the wild. What does this tell us?", "Some different species can sometimes produce hybrids", ["All birds are one species", "Ducks cannot lay eggs"], "Hybridization happens in nature, but not always.", true],
  ["If two animals can breed but their young cannot, what might a scientist conclude?", "They are probably different species", ["They are identical", "The young are plants"], "Infertile hybrids point to separate species.", true],
  ["Which is an example of a plant hybrid?", "A cross between two kinds of apple trees", ["A tree and a rock", "A wolf and a flower"], "Plant breeders create hybrids too.", true],
  ["A farmer wants wheat that stands up to a fungus. Which approach uses hybrids?", "Cross a strong wheat with one that resists the fungus", ["Pour water on it", "Plant it in the dark"], "Selecting parent plants gives new combinations.", true],
  ["Which statement describes a species best?", "Its members share features and can produce viable offspring together", ["Its members look exactly the same", "Its members live in the same house"], "Appearance alone is not enough.", true],
  ["Why can looking alike be misleading when naming species?", "Different species can look similar, and one species can show variety", ["All animals look alike", "Looks never matter"], "Breeding and other features matter.", true],
  ["Which group are scientists likely to call a hybrid?", "Offspring of a male horse and a female donkey", ["Offspring of two horses", "A group of ten ponies"], "Two kinds of parents make a hybrid.", true],
  ["A cross between two plant varieties produces seeds that grow into strong plants. Which word describes the seeds?", "Viable", ["Empty", "Invisible"], "They can grow into new plants.", true],
  ["Which of these is NOT a hybrid?", "A wolf pup born to two wolves", ["A mule", "A liger"], "Both parents are the same species.", true],
];

export const species = bankUnit({
  id: "mb-species-and-hybrids",
  title: "Species & Hybrids",
  emoji: "🧬",
  blurb: "What makes a species, and what happens when two kinds breed.",
  parentNote:
    "Practises what a species is, what viable offspring are, and hybrids such as mules, ligers, grolar bears and hybrid crops.",
  standards: ["SCI.6.E.16", "the nature of plant and animal species: viable offspring and hybrids"],
  items: SPECIES,
});

const SCIENCE_WORKS: Q[] = [
  ["A hypothesis is…", "a prediction about what is happening or might happen", ["a final proven fact", "a list of materials"], "It is based on research, experience or observations."],
  ["Which is a hypothesis?", "If I add more sunlight, the bean plant will grow taller.", ["Bean plants are green.", "What is a plant?"], "A hypothesis can be tested."],
  ["Scientists collect data by…", "observing and measuring", ["guessing", "copying a friend"], "Data come from observations and measurements."],
  ["Which is a measurement?", "The plant is 12 cm tall.", ["The plant looks happy.", "I like the plant."], "A measurement has a number and a unit."],
  ["Which is an observation?", "The leaves turned yellow.", ["The plant must be unhappy.", "Plants are boring."], "An observation is what you notice."],
  ["Evidence that agrees with a hypothesis…", "supports it", ["proves it for all time", "ends the study"], "Evidence can support or refute (go against) a prediction."],
  ["If the data do not match the hypothesis, a scientist should…", "revise the idea and test again", ["hide the data", "change the data"], "Honest results are what matter."],
  ["A scientific theory or model is the one that…", "best fits the evidence at the time", ["is the most popular", "is the oldest"], "Models can change as new evidence appears."],
  ["Why might a scientific explanation change?", "New evidence may show a better explanation", ["Scientists get bored", "Because of the weather"], "Science is open to revision."],
  ["Science tries to explain…", "phenomena in nature", ["only things in books", "only the past"], "It builds explanations from evidence."],
  ["Which is a good use of scientific knowledge?", "Engineers using it to design safer bridges", ["Ignoring the weather", "Skipping experiments"], "Science supports engineering and technology."],
  ["What is technology?", "Tools and processes people make to solve problems", ["Only computers", "Only robots"], "A bicycle is technology too."],
  ["Cars let people travel quickly but also produce pollution. This shows that technology can have…", "both benefits and drawbacks", ["no effects", "only benefits"], "Technologies can help and harm."],
  ["Which is a benefit of vaccines?", "They help protect people from disease", ["They stop all weather", "They end all work"], "Vaccines are a medical technology."],
  ["Plastic bags are cheap and useful but can harm wildlife. What does this show?", "A technology can have social and environmental consequences", ["Plastic is always safe", "Wildlife likes plastic"], "Think about all the effects.", true],
  ["When solving a problem, there is usually…", "more than one possible solution", ["only one solution", "no solution"], "Each solution has trade-offs."],
  ["A town wants to reduce litter. Which is a possible solution?", "More recycling bins and a community clean-up", ["Throw more garbage", "Ignore it"], "Different ideas can all help."],
  ["Which would you consider when choosing between two solutions?", "Cost, how well it works and the effect on the environment", ["Only the colour", "Only which is the oldest"], "Look at several factors.", true],
  ["Which question is about the ethics of a technology?", "Is it fair and safe for everyone it affects?", ["What colour is it?", "Who is tallest?"], "Ethics asks about right and fair.", true],
  ["A group wants to build a new road through a forest. Which impact on the ecosystem should they think about?", "Loss of animal habitat", ["The price of crayons", "The colour of cars"], "Apply science to see consequences.", true],
  ["Why do scientists repeat experiments?", "To check that the results are reliable", ["To use more paper", "Because they forgot"], "Repeated trials build confidence.", true],
  ["A scientist records that plants in the dark grew 3 cm and plants in light grew 9 cm. The data are used to…", "decide whether the evidence supports the prediction", ["pick a favourite plant", "decide the lunch menu"], "Data answer the question.", true],
  ["The type of data a scientist looks for is guided by…", "the hypothesis or theory being tested", ["the weather forecast", "the scientist’s lunch"], "A prediction tells you what to measure.", true],
  ["Which is a prediction?", "I think the ice cube in the sun will melt faster than the one in the shade.", ["The ice cube is cold.", "Ice is water."], "A prediction says what might happen.", true],
  ["Which of these shows careful record keeping?", "A table of dated measurements", ["A loose note on a napkin", "No notes at all"], "Systematic data collection means writing results clearly.", true],
  ["A new invention makes jobs easier but uses a lot of energy. A thoughtful person would…", "weigh the benefits and the costs", ["only count the benefits", "only count the costs"], "Technologies have trade-offs.", true],
];

export const scienceWorks = bankUnit({
  id: "mb-how-science-works",
  title: "How Science Works",
  emoji: "🔬",
  blurb: "Hypotheses, evidence, models and what technology means for people and nature.",
  parentNote:
    "Practises how scientists make predictions, collect data and use evidence, how explanations change over time, and the benefits and drawbacks of technologies.",
  standards: ["SCI.6.D.1, SCI.6.D.2, SCI.6.D.3, SCI.6.D.4, SCI.6.D.6, SCI.6.D.7", "the nature of science: hypotheses, data, evidence, and technologies and their consequences"],
  items: SCIENCE_WORKS,
});

const MEASURE: Q[] = [
  ["How many metres are in 1 kilometre?", "1000", ["100", "10"], "Kilo means one thousand."],
  ["How many centimetres are in 1 metre?", "100", ["10", "1000"], "Centi means one hundredth."],
  ["How many millimetres are in 1 centimetre?", "10", ["100", "1000"], "Milli means one thousandth of a metre."],
  ["How many grams are in 1 kilogram?", "1000", ["100", "10"], "Kilo means 1000."],
  ["How many millilitres are in 1 litre?", "1000", ["100", "10"], "Milli means one thousandth."],
  ["Which tool measures mass?", "A balance", ["A ruler", "A thermometer"], "A pan balance compares masses."],
  ["Which tool measures force?", "A spring scale", ["A stopwatch", "A voltmeter"], "Force is measured in newtons (N)."],
  ["Which tool measures temperature?", "A thermometer", ["A ruler", "A balance"], "Temperature is in °C."],
  ["Which tool measures the volume of a liquid?", "A graduated cylinder", ["A ruler", "A clock"], "Volume is in mL or L."],
  ["Which tool measures time?", "A stopwatch", ["A spring scale", "A balance"], "Time is in seconds, minutes and hours."],
  ["Which tool measures electric current?", "An ammeter", ["A ruler", "A balance"], "Current is measured in amperes (A)."],
  ["Which tool measures electric potential (voltage)?", "A voltmeter", ["A thermometer", "A clock"], "Voltage is measured in volts (V)."],
  ["What is the unit for force?", "Newton (N)", ["Metre (m)", "Litre (L)"], "Named for Isaac Newton."],
  ["What is 3500 g in kilograms?", "3.5 kg", ["35 kg", "0.35 kg"], "Divide grams by 1000."],
  ["What is 2.5 L in millilitres?", "2500 mL", ["250 mL", "25 mL"], "Multiply litres by 1000."],
  ["What is 4.2 m in centimetres?", "420 cm", ["42 cm", "4200 cm"], "Multiply metres by 100."],
  ["What is 50 mm in centimetres?", "5 cm", ["50 cm", "0.5 cm"], "Divide millimetres by 10."],
  ["What is 0.8 km in metres?", "800 m", ["80 m", "8 m"], "Multiply kilometres by 1000."],
  ["How many minutes are in 2.5 hours?", "150", ["250", "120"], "2.5 × 60 = 150."],
  ["What is 90 minutes in hours?", "1.5 h", ["0.9 h", "9 h"], "60 minutes make an hour."],
  ["A cyclist rides 120 km in 2 hours. What is the average speed?", "60 km/h", ["240 km/h", "122 km/h"], "Speed = distance ÷ time."],
  ["A runner covers 100 m in 20 s. What is the average speed?", "5 m/s", ["2000 m/s", "20 m/s"], "100 ÷ 20 = 5.", true],
  ["A car goes 90 km/h for 3 hours. How far does it travel?", "270 km", ["30 km", "93 km"], "Distance = speed × time.", true],
  ["About how long is a classroom door?", "2 m", ["2 mm", "2 km"], "Estimate with a familiar object.", true],
  ["About how much liquid is in a small water bottle?", "500 mL", ["500 L", "5 mL"], "Half a litre.", true],
  ["About what is the mass of a paper clip?", "1 g", ["1 kg", "100 g"], "It is very light.", true],
  ["What temperature is a comfortable room?", "About 20 °C", ["About 80 °C", "About −10 °C"], "Water boils at 100 °C and freezes at 0 °C.", true],
  ["Which unit is best for the distance from Winnipeg to Brandon?", "Kilometres", ["Millimetres", "Millilitres"], "Large distances use km.", true],
  ["Which unit is best for the length of an ant?", "Millimetres", ["Kilometres", "Litres"], "Small lengths use mm.", true],
  ["A graph shows how a plant’s height changes each week. Which kind of graph shows change over time?", "A line graph", ["A map", "A label"], "Line graphs show trends.", true],
  ["Why do scientists use standard units such as metres and grams?", "So everyone can compare and share measurements", ["Because they look fancy", "To make numbers longer"], "Standard units mean the same thing everywhere.", true],
  ["The prefix milli- means…", "one thousandth", ["one thousand", "one hundred"], "Think millimetre and millilitre.", true],
  ["The prefix kilo- means…", "one thousand", ["one thousandth", "ten"], "Think kilometre and kilogram.", true],
];

export const measurement = bankUnit({
  id: "mb-scientific-measurement",
  title: "Scientific Measurement",
  emoji: "📏",
  blurb: "Pick the right tool and unit, and convert between metric units.",
  parentNote:
    "Practises choosing measuring tools and SI units for length, mass, volume, time, temperature, speed, force and electricity, converting between metric units and the meaning of prefixes such as kilo and milli.",
  standards: ["SCI.6.C.2", "measuring with the appropriate tools and units, and converting between SI units"],
  items: MEASURE,
});
