import { bankUnit, type Q } from "../own";

// More Grade 6 English language arts units for the Manitoba outcomes (strands B and C and the learning-to-learn strand D).

const TEXT_FEATURES: Q[] = [
  ["Where would you look to find which page a chapter starts on?", "The table of contents", ["The glossary", "The caption"], "The table of contents lists chapters with page numbers."],
  ["Where do you find an alphabetical list of topics with page numbers, usually at the back of a book?", "The index", ["The table of contents", "The title page"], "The index is in alphabetical order."],
  ["A glossary explains…", "key words used in the book", ["who drew the pictures", "where the book was printed"], "It works like a small dictionary for that book."],
  ["A caption is…", "the words beside or under a photo that explain it", ["the title of the book", "a list of chapters"], "Captions tell you what a picture shows."],
  ["What does a heading tell the reader?", "What the next section is mostly about", ["Who wrote the book", "How long the book is"], "Headings and subheadings organize a text."],
  ["Why are some words in bold print?", "They are important words, often defined in the text or glossary", ["They are spelled wrong", "They are the author’s name"], "Bold print helps you spot key vocabulary."],
  ["A labelled diagram helps a reader…", "see the parts of something and what they are called", ["hear the story", "find the author’s birthday"], "Labels name each part."],
  ["A timeline shows…", "events in the order they happened", ["the rules of a game", "a recipe’s ingredients"], "Timelines put events in time order."],
  ["What does a map legend (key) explain?", "What the symbols and colours on the map mean", ["Who made the map", "How old the map is"], "Look at the legend before reading a map."],
  ["A bar graph in an article helps the reader…", "compare amounts quickly", ["learn how to spell", "hear a voice"], "Graphs turn numbers into a picture."],
  ["A sidebar is…", "a box with extra information next to the main text", ["the last page of a book", "a kind of poem"], "Sidebars add interesting extras."],
  ["You want to find every page that mentions volcanoes. Which text feature is best?", "The index", ["The cover", "The caption"], "The index lists topics and their pages."],
  ["You want a quick idea of what a chapter covers before reading it. What should you read first?", "The headings and subheadings", ["The last sentence only", "The page numbers"], "Skim the headings to preview."],
  ["A biography is a text about…", "a real person’s life, written by someone else", ["an imaginary planet", "how to bake bread"], "Bio means life; the author is not the subject."],
  ["An autobiography is written by…", "the person it is about", ["a newspaper editor", "a friend of the person"], "Auto means self."],
  ["A fable is a short story that…", "often uses animals and teaches a lesson", ["lists steps to follow", "gives weather facts"], "A fable ends with a moral."],
  ["A recipe is an example of which kind of text?", "A procedural (how-to) text", ["A legend", "A poem"], "It gives steps in order."],
  ["A text that uses words, photos and sound together, such as a documentary video, is…", "a multimodal text", ["a one-word text", "a dictionary"], "Multimodal means more than one mode."],
  ["Historical fiction is…", "a made-up story set in a real time in the past", ["a list of real dates", "a science report"], "The setting is real history; the characters can be invented."],
  ["An infographic mainly combines…", "pictures, numbers and short text to share facts", ["only long paragraphs", "only poems"], "It is designed to be understood at a glance."],
  ["Why might a science article include a diagram and a paragraph about the same idea?", "Each helps the reader understand in a different way", ["The author ran out of words", "The diagram replaces the title"], "Using two modes can clarify an idea.", true],
  ["In a science text, which word is subject-specific vocabulary?", "Photosynthesis", ["Beautiful", "Because"], "Subject words belong to one area of study.", true],
  ["In a math text, which word is subject-specific vocabulary?", "Perimeter", ["Gentle", "Sunset"], "Perimeter is a math term.", true],
  ["You meet a new word in bold. What is the best first step?", "Look for a definition nearby or in the glossary", ["Skip the whole page", "Guess a random meaning"], "Bold words are often explained.", true],
  ["An editorial is a text written to…", "share an opinion about an issue", ["list school lunch menus", "teach long division steps"], "Editorials argue a point of view.", true],
  ["Why choose a book written by an expert for a research project?", "The expert’s knowledge makes it more likely to be accurate", ["Experts always use short words", "Expert books have no pictures"], "Choose texts that suit your purpose and are trustworthy.", true],
  ["To build background knowledge about the Red River, which pair of texts is the best match?", "A history book and a map", ["A cookbook and a joke book", "A phone manual and a menu"], "Pick texts that fit your topic.", true],
  ["A podcast is mainly a…", "audio text", ["printed text", "picture-only text"], "You listen to it.", true],
];

export const textFeatures = bankUnit({
  id: "mb-text-features-forms",
  title: "Text Features & Forms",
  emoji: "📚",
  blurb: "Use headings, indexes, captions and graphs, and know different kinds of texts.",
  parentNote:
    "Practises text features such as the table of contents, index, glossary, captions and diagrams, the names of common text forms, and subject-specific vocabulary.",
  standards: ["ELA.6.B1.3, ELA.6.B2.2, ELA.6.B2.7", "text features, kinds of texts, and subject-specific vocabulary"],
  items: TEXT_FEATURES,
});

const WRITING_PLAN: Q[] = [
  ["A writer first needs to choose a topic and think about…", "the audience and purpose", ["the font colour", "the page count only"], "Who will read it and why you are writing guide every choice."],
  ["Which is a way to plan before writing?", "Make a graphic organizer or jot notes", ["Skip straight to the last line", "Copy a friend’s page"], "Planning tools help gather ideas."],
  ["Brainstorming means…", "listing many ideas quickly before choosing", ["fixing spelling mistakes", "reading a text aloud"], "Write ideas down without judging them first."],
  ["A mind map is…", "a diagram with a main idea in the centre and related ideas around it", ["a type of dictionary", "a poem form"], "It shows how ideas connect."],
  ["Which topic is better focused for a short report?", "How beavers build dams", ["Everything about animals", "The whole world"], "A narrower topic is easier to cover well."],
  ["A complete piece of writing usually has…", "an introduction, a body and a conclusion", ["only a body", "only a title"], "These three parts organize the text."],
  ["What does the introduction do?", "Tells the reader what the text is about and draws them in", ["Lists the spelling errors", "Ends the story"], "It opens the piece."],
  ["What does a conclusion do?", "Wraps up the main ideas", ["Starts a new topic", "Repeats the title five times"], "It gives the reader a sense of an ending."],
  ["A paragraph groups…", "sentences about one main idea", ["every idea in the report", "all the titles"], "Start a new paragraph for a new idea."],
  ["Supporting details in a paragraph…", "give facts, examples or reasons for the main idea", ["change the topic", "should be left out"], "Details back up the main idea."],
  ["Which words signal a chronological (time order) pattern?", "First, next, then, finally", ["However, but, although", "Because, so, as a result"], "Time-order words show sequence."],
  ["Which words often signal cause and effect?", "Because, so, as a result", ["First, second, third", "Meanwhile, later, after"], "These words link a cause to its effect."],
  ["A text explains how pollution from a spill harms fish. Which organization pattern fits best?", "Cause and effect", ["Compare and contrast", "Time order only"], "It shows what happened because of something else."],
  ["A text that tells how a seed grows from planting to flower fits which pattern?", "Chronological sequence", ["Problem and solution", "Description only"], "Events go in time order."],
  ["A text that shows how frogs and toads are alike and different uses…", "compare and contrast", ["cause and effect", "time order"], "Look for alike and different."],
  ["Which text form fits writing to a friend who lives far away?", "A letter", ["A glossary", "A timeline"], "A letter has a greeting and a closing."],
  ["Where can you gather information for a research report?", "Books, trusted websites and an expert you interview", ["A rumour only", "One unsigned post"], "Use a mix of reliable sources."],
  ["Which source is likely to be the most reliable for facts about the planets?", "A science museum’s website", ["A stranger’s joke post", "An advertisement"], "Check who made the source and why."],
  ["Notetaking is best done…", "in your own words, with the key ideas", ["by copying whole pages", "by drawing doodles only"], "Short notes in your own words help avoid copying."],
  ["You find two sources that disagree about a fact. What should you do?", "Check a third reliable source", ["Choose the shorter one", "Ignore the topic"], "Compare sources to decide.", true],
  ["A paragraph starts with the sentence “Wolves live in packs.” Which sentence is a supporting detail?", "A pack can have six to ten wolves that hunt together.", ["Dogs are popular pets.", "I like the colour green."], "A supporting detail stays on the main idea.", true],
  ["Which sentence does NOT belong in a paragraph about how bees make honey?", "My cousin lives near the lake.", ["Bees collect nectar from flowers.", "Worker bees store the nectar in the hive."], "Remove sentences that stray from the topic.", true],
  ["Which is the best topic sentence for a paragraph about recycling at school?", "Our school can reduce waste by recycling paper.", ["Paper.", "Many things exist."], "A topic sentence states the main idea clearly.", true],
  ["Which is the strongest purpose statement?", "I will persuade my classmates to walk to school.", ["I will write something.", "This is a page."], "A clear purpose names what you want the audience to think, feel or do.", true],
  ["A writer wants to inform younger students about the water cycle. Which choice suits that audience?", "Short sentences with simple words and a labelled picture", ["Long technical terms with no pictures", "A poem with no facts"], "Match the writing to the audience.", true],
  ["Why should a writer talk to others while planning?", "Other people’s ideas can help focus or expand your own", ["To avoid doing any planning", "To make the text shorter"], "Discussion is a good planning technique.", true],
  ["Digital tools such as a word processor help a writer to…", "draft, move and edit text easily", ["avoid having ideas", "stop reading"], "They make revising simpler.", true],
];

export const writingPlan = bankUnit({
  id: "mb-planning-and-organizing",
  title: "Plan & Organize Writing",
  emoji: "📝",
  blurb: "Choose a topic, plan, and organize ideas in paragraphs.",
  parentNote:
    "Practises choosing a focused topic for an audience, planning with organizers, using organization patterns such as cause and effect, and building introductions, paragraphs and conclusions.",
  standards: ["ELA.6.C1.1, ELA.6.C1.2, ELA.6.C1.3, ELA.6.C2.1", "choosing a topic, planning, gathering information and organizing writing"],
  items: WRITING_PLAN,
});

const CAPS_SPELLING: Q[] = [
  ["Which sentence uses capital letters correctly?", "We visited Winnipeg in July.", ["we visited winnipeg in july.", "We visited winnipeg in July."], "Capitalize the first word and proper nouns like city names. Months are capitalized too."],
  ["Which word needs a capital letter?", "manitoba", ["river", "city"], "Names of provinces are proper nouns."],
  ["Which is correct?", "Lake Winnipeg is big.", ["lake Winnipeg is big.", "Lake winnipeg is big."], "A named lake is a proper noun."],
  ["Which is correct?", "My teacher, Ms. Singh, reads aloud.", ["my teacher, ms. singh, reads aloud.", "My Teacher, Ms. Singh, reads aloud."], "Capitalize titles used with a name, not general job words."],
  ["Which is correct?", "“Let’s go,” said Mia.", ["“let’s go,” said Mia.", "“Let’s go,” Said Mia."], "Capitalize the first word of a quotation."],
  ["Which book title is capitalized correctly?", "The Wind in the Willows", ["the wind in the willows", "The wind In The willows"], "Capitalize the first and important words of a title."],
  ["Which abbreviation is capitalized correctly?", "Mr. Lee", ["mr. Lee", "MR. lee"], "Mr. begins with a capital."],
  ["Which is correct?", "We celebrate Canada Day on July 1.", ["We celebrate canada day on july 1.", "We celebrate Canada day on july 1."], "Holidays and months are capitalized."],
  ["Which is correct?", "I like science and math.", ["I like Science and Math.", "i like science and math."], "School subjects are not capitalized unless they are language names."],
  ["Which is correct?", "She speaks French and English.", ["She speaks french and english.", "She speaks French and english."], "Names of languages are capitalized."],
  ["Which sentence needs no capital changes?", "On Monday, we went to the Forks.", ["On monday, we went to the Forks.", "On Monday, we went to the forks."], "Days and place names are capitalized."],
  ["Which word is NOT capitalized in a sentence?", "winter", ["Tuesday", "Canada"], "Seasons are not capitalized; days are.", true],
  ["Which has the correct capitals?", "Premier Smith spoke on Tuesday.", ["premier Smith spoke on tuesday.", "Premier smith spoke on Tuesday."], "A title before a name and the name are capitalized.", true],
  ["Which is correct?", "The Red River flows north.", ["The red river flows north.", "the Red River flows north."], "Named rivers are capitalized.", true],
  ["Which is the correct spelling?", "favourite", ["favorite", "favurite"], "Canadian spelling keeps the u in our words."],
  ["Which is the correct Canadian spelling?", "colour", ["color", "culor"], "Canadian spelling keeps the u."],
  ["Which is the correct Canadian spelling?", "centre", ["center", "centar"], "Canadian spelling uses re."],
  ["Which word is spelled correctly?", "neighbour", ["neighbor", "naybour"], "Canadian spelling keeps the u."],
  ["Which word is spelled correctly?", "necessary", ["neccesary", "necesary"], "One c and two s’s: ne-ces-sa-ry."],
  ["Which word is spelled correctly?", "separate", ["seperate", "seperete"], "Remember “a rat” in sep-a-rate."],
  ["Which word is spelled correctly?", "beautiful", ["beutiful", "beautifull"], "Beau-ti-ful has three syllables."],
  ["Choose the right word: “___ going to the library.”", "They’re", ["Their", "There"], "They’re means they are."],
  ["Choose the right word: “The dog wagged ___ tail.”", "its", ["it’s", "its’"], "It’s means it is; its shows ownership."],
  ["Choose the right word: “Do you know ___ coat this is?”", "whose", ["who’s", "whos"], "Who’s means who is."],
  ["Choose the right word: “I would like ___ pizza.”", "some", ["sum", "sume"], "Sum is an answer in math."],
  ["A spell checker may NOT catch which mistake?", "Using “form” when you meant “from”", ["Writing “teh”", "Writing “recieve”"], "Both are real words, so it may not flag it.", true],
  ["Which strategy helps you spell “knight”?", "Remember the silent k and the gh pattern", ["Spell it like “nite” only", "Leave out letters you cannot hear"], "Some words keep silent letters.", true],
  ["The words “sign” and “signal” share a root. How can that help spelling?", "It reminds you the g is there even if you do not say it in “sign”", ["It shows both words are spelled the same", "It means g is always silent"], "Related words can help you spell.", true],
  ["Which sentence is spelled the Canadian way?", "I practise piano daily.", ["I practice piano daily.", "I practis piano daily."], "In Canada, practise is the verb and practice is the noun.", true],
];

export const capitalsSpelling = bankUnit({
  id: "mb-capitals-and-spelling",
  title: "Capitals & Spelling",
  emoji: "🔠",
  blurb: "Use capital letters correctly and spell tricky words the Canadian way.",
  parentNote:
    "Practises capitals for proper nouns, titles, dialogue and abbreviations, Canadian spelling patterns, commonly confused words, and using spelling strategies and tools.",
  standards: ["ELA.6.C3.2, ELA.6.C3.3", "spelling strategies and consistent, accurate capital letters"],
  items: CAPS_SPELLING,
});

const MEDIA_BIAS: Q[] = [
  ["A multimodal text combines…", "two or more ways of communicating, such as words and pictures", ["only one font", "only silence"], "Modes include text, images, sound and video."],
  ["Which is a multimodal text?", "A video with narration and captions", ["A list of words", "A blank page"], "It uses sound, pictures and words."],
  ["A poster for a school event should make the message…", "clear for the audience", ["as small as possible", "hard to read"], "Choose images and words for your purpose."],
  ["Which choice makes a slideshow easier to understand?", "Short text and a clear picture on each slide", ["A whole page of tiny text", "A different font on every line"], "Keep slides simple."],
  ["Sound effects in a digital story are used to…", "add mood or meaning", ["fix spelling", "replace the title"], "Sound is one of the modes."],
  ["Who is a text’s intended audience?", "The people the creator wants to reach", ["The printer", "The publisher’s accountant"], "Creators make choices for a specific audience."],
  ["A text creator’s purpose may be to…", "inform, entertain or persuade", ["be invisible", "hide the title"], "Ask why was this made?"],
  ["Which question helps you check for bias?", "Whose voice is missing from this text?", ["How long is the title?", "What colour is the cover?"], "Bias can come from leaving out views."],
  ["Bias in a text means…", "it shows only one side or unfairly favours a view", ["it has too many pictures", "it is long"], "Biased texts are not balanced."],
  ["Prejudice is…", "judging people unfairly without knowing them", ["a kind of punctuation", "a long word"], "It is an unfair opinion formed in advance."],
  ["A stereotype is…", "an oversimplified idea about a group of people", ["a fact about weather", "a type of map"], "Stereotypes treat people as all the same."],
  ["A story shows only boys as scientists. What might a thoughtful reader notice?", "It leaves out girls and others who are scientists", ["It uses too many verbs", "It has a long title"], "Representation matters.", true],
  ["How can a reader support an observation about how a group is shown?", "Use evidence such as a quote, an action or an illustration", ["Say it is just a feeling", "Guess without looking"], "Point to the text.", true],
  ["Which shows inclusion in a class library?", "Books with characters and creators from many cultures and abilities", ["Only books about one culture", "Only books with no people"], "Diverse books help everyone see themselves.", true],
  ["Equity means…", "giving people what they need so everyone has a fair chance", ["giving everyone exactly the same thing no matter what", "treating some people better"], "Equity is about fairness of opportunity.", true],
  ["You notice a poster makes fun of how a group of people speaks. A good response is to…", "say respectfully what bothers you and give a reason from the poster", ["laugh along", "say nothing and walk away forever"], "Respond to bias using specific evidence.", true],
  ["An ad says “9 out of 10 kids love our cereal” but does not say how many were asked. What should a viewer think?", "More information is needed to trust the claim", ["It must be true", "It is a poem"], "Check the evidence behind a claim.", true],
  ["An article about a hockey rink was written by the company that sells ice. A reader should…", "think about whether the writer is favouring the company", ["ignore all facts", "assume it is neutral"], "Consider who made a text and why.", true],
  ["A news story and a social media post disagree. What is a good step?", "Look for a reliable source that confirms the facts", ["Believe the louder one", "Believe the first one"], "Cross-check information.", true],
  ["Which is a respectful way to describe a person from another culture?", "Use the name or term they use for themselves", ["Use a nickname you made up", "Use a joke"], "Respectful language honours people’s own words.", true],
  ["Which digital tool could you use to make a short narrated story?", "A video or slideshow app with a microphone", ["A calculator", "A ruler"], "Digital stories mix pictures, words and voice."],
  ["Which medium is best for sharing a quick weather warning to many people at once?", "A text alert", ["A printed novel", "A museum display"], "Match the medium to the message."],
  ["What is the benefit of adding a photo to a report on a community garden?", "It shows readers what the garden looks like", ["It makes the report shorter", "It replaces the facts"], "Visuals support the text."],
  ["A logo on a school shirt is an example of…", "a visual that communicates identity", ["a paragraph", "a recipe"], "Images carry meaning."],
  ["A reader notices a text uses only “he” for doctors. This is…", "a possible stereotype", ["a way to show math", "a map"], "Words can suggest who belongs in a job.", true],
  ["A final multimodal project should be checked to see if…", "each part helps communicate the message", ["it uses every colour", "it has as many effects as possible"], "More is not always better.", true],
  ["Which sentence best expresses a personal response to bias in a text?", "The author only tells the settlers’ side, so I want to read other perspectives too.", ["This is boring.", "I hate it."], "Respond with evidence and a next step.", true],
];

export const mediaBias = bankUnit({
  id: "mb-media-and-bias",
  title: "Media, Bias & Diversity",
  emoji: "🎬",
  blurb: "Notice how texts show people, and how words, pictures and sound work together.",
  parentNote:
    "Practises how multimodal texts combine modes, how audience and purpose shape a text, and how to notice bias, stereotypes, inclusion and equity in texts.",
  standards: ["ELA.6.B3.1, ELA.6.B3.4, ELA.6.C1.5, ELA.6.C3.5", "diversity and bias in texts, and creating multimodal texts"],
  items: MEDIA_BIAS,
});

const LEARNING: Q[] = [
  ["Prior knowledge is…", "what you already know about a topic", ["a new word", "a book’s index"], "Connecting to what you know helps you understand new text."],
  ["Before reading a book about glaciers, what could you do?", "Think about what you already know about ice and snow", ["Skip to the end", "Close the book"], "Activate your prior knowledge."],
  ["Which question is open-ended?", "Why did settlers come to the prairies?", ["Did settlers come to the prairies?", "Is this a book?"], "An open-ended question needs more than yes or no."],
  ["Which question starts a deeper inquiry?", "How did the railway change people’s lives?", ["Is it 1885?", "Was there a train?"], "“How” and “why” questions lead to deeper thinking."],
  ["A good group inquiry question can be explored from different…", "perspectives and subjects", ["colours", "fonts"], "Strong questions connect many viewpoints."],
  ["A text-to-self connection links the text to…", "your own experience", ["another country’s map", "a dictionary"], "Self means you."],
  ["A text-to-text connection links the text to…", "another book, article or story", ["your lunch", "the weather"], "Compare two texts."],
  ["A text-to-world connection links the text to…", "something that happens in the world", ["only your family", "only the title"], "For example, news or history."],
  ["Reading rate means…", "how fast or slow you read", ["how loudly you read", "which book you pick"], "Adjust it to suit your purpose."],
  ["You should read slower when…", "the text is full of new, difficult ideas", ["you are skimming for a name", "you already know the story"], "Slow down to understand tough material."],
  ["You can read faster when…", "you are scanning for one fact you already know how to spot", ["the text is a poem you are analyzing", "you are studying a diagram"], "Scanning is quicker than studying."],
  ["Fluency means reading…", "smoothly, with expression and understanding", ["as fast as possible with no meaning", "in a whisper only"], "Fluent readers understand what they read."],
  ["If your mind wanders while reading, a good fix-up strategy is to…", "reread the part you missed", ["pretend you got it", "turn off the light"], "Rereading restores meaning."],
  ["Metacognition means…", "thinking about how you learn", ["counting words", "drawing maps"], "It helps you pick good strategies."],
  ["Which is a helpful learning strategy for remembering a new word?", "Write it in a sentence and draw a picture", ["Look at it once", "Cover your eyes"], "Use more than one way to practise."],
  ["A learning goal should be…", "specific, so you know what to do", ["as vague as possible", "impossible"], "A clear goal is easier to reach."],
  ["Which is the best goal?", "I will read for 15 minutes each evening this week.", ["I will be better.", "I will read someday."], "It says what, how much and when."],
  ["After setting a goal, what comes next?", "Plan the steps to reach it", ["Forget it", "Change the topic"], "Plan then track."],
  ["How could you track progress on a reading goal?", "Keep a reading log", ["Hide the book", "Ask the librarian to read for you"], "Collecting evidence shows growth."],
  ["Descriptive feedback from a classmate says “Your story has strong dialogue, and the ending could be clearer.” This helps you to…", "know a strength and what to work on next", ["avoid revising", "stop writing"], "Good feedback is specific.", true],
  ["Which statement shows reflection?", "I understood more when I drew a diagram, so I will do that again.", ["I did it.", "Done."], "Reflection names what worked and why.", true],
  ["A group makes class criteria for a good summary. They are…", "a list of what a good summary includes", ["a list of authors", "a seating plan"], "Criteria help you check your work.", true],
  ["You are asked to share new subject-specific words from science. A good tool is…", "a personal word list with meanings", ["a blank page", "a map of Canada"], "Keep track of new vocabulary.", true],
  ["Which of these is a reason a reader’s perspective affects understanding?", "Different life experiences can lead readers to notice different things", ["All readers think the same way", "Experience never matters"], "Perspectives shape meaning.", true],
  ["You have to choose between two texts to learn about the Prairies. A good reason to choose one is that…", "it matches your purpose and is easy to trust", ["it has the longest title", "it has a shiny cover"], "Select texts to build background knowledge.", true],
  ["Which listening skill shows respect during a discussion?", "Summarize what someone said before you share your view", ["Interrupt right away", "Look away"], "Critical listening includes summarizing."],
  ["Which question clears up a confusing idea in a discussion?", "Can you explain what you mean by that?", ["Why are you here?", "Is it lunch?"], "Ask to clarify."],
  ["Which sentence is a complex sentence?", "Because it rained, we stayed inside.", ["We stayed in.", "It rained."], "A complex sentence has a dependent clause.", true],
];

export const learning = bankUnit({
  id: "mb-reading-and-learning-strategies",
  title: "Learning to Learn",
  emoji: "🧠",
  blurb: "Use what you know, ask big questions, and set goals for your learning.",
  parentNote:
    "Practises using prior knowledge, asking open-ended questions, making connections, adjusting reading rate, and choosing and tracking learning goals.",
  standards: ["ELA.6.A1.4, ELA.6.A1.5, ELA.6.A2.6, ELA.6.B1.1, ELA.6.B1.2, ELA.6.B2.4, ELA.6.D2.1, ELA.6.D2.3, ELA.6.D2.4, ELA.6.D2.5", "prior knowledge, questions, connections, reading rate, and setting and tracking learning goals"],
  items: LEARNING,
});
