import { bankUnit, type Q } from "../own";

// More Grade 6 social studies units for the Manitoba outcomes: Canada's geography, Canada since 1945, industry and
// technology, citizens' rights, identity and organizations, fairness, and history skills.
// Indigenous content is light and factual, and needs review with First Nations, Métis and Inuit partners.

const GEOGRAPHY: Q[] = [
  ["What is the capital city of Canada?", "Ottawa", ["Toronto", "Montréal"], "The federal government meets in Ottawa."],
  ["What is the capital city of Manitoba?", "Winnipeg", ["Brandon", "Churchill"], "Winnipeg is where the legislature sits."],
  ["What is the capital city of British Columbia?", "Victoria", ["Vancouver", "Kelowna"], "Victoria is on Vancouver Island."],
  ["What is the capital city of Alberta?", "Edmonton", ["Calgary", "Red Deer"], "Edmonton is in central Alberta."],
  ["What is the capital city of Saskatchewan?", "Regina", ["Saskatoon", "Moose Jaw"], "Regina is in the south of the province."],
  ["What is the capital city of Ontario?", "Toronto", ["Ottawa", "Hamilton"], "Toronto is Ontario’s largest city."],
  ["What is the capital city of Quebec?", "Québec City", ["Montréal", "Laval"], "Québec City is on the St. Lawrence River."],
  ["What is the capital city of New Brunswick?", "Fredericton", ["Moncton", "Saint John"], "Fredericton is on the Saint John River."],
  ["What is the capital city of Nova Scotia?", "Halifax", ["Sydney", "Truro"], "Halifax is on the Atlantic coast."],
  ["What is the capital city of Prince Edward Island?", "Charlottetown", ["Summerside", "Fredericton"], "PEI is Canada’s smallest province."],
  ["What is the capital city of Newfoundland and Labrador?", "St. John’s", ["Gander", "Corner Brook"], "It is on the island of Newfoundland."],
  ["What is the capital of Yukon?", "Whitehorse", ["Dawson City", "Yellowknife"], "Whitehorse is Yukon’s largest city."],
  ["What is the capital of the Northwest Territories?", "Yellowknife", ["Whitehorse", "Iqaluit"], "It sits on Great Slave Lake."],
  ["What is the capital of Nunavut?", "Iqaluit", ["Yellowknife", "Whitehorse"], "Nunavut became a territory in 1999."],
  ["How many provinces does Canada have?", "10", ["13", "3"], "There are 10 provinces and 3 territories."],
  ["How many territories does Canada have?", "3", ["10", "5"], "Yukon, Northwest Territories and Nunavut."],
  ["Which ocean is on Canada’s west coast?", "The Pacific Ocean", ["The Atlantic Ocean", "The Arctic Ocean"], "BC’s coast is on the Pacific."],
  ["Which ocean is on Canada’s east coast?", "The Atlantic Ocean", ["The Pacific Ocean", "The Indian Ocean"], "The Maritime provinces touch the Atlantic."],
  ["Which ocean is to the north of Canada?", "The Arctic Ocean", ["The Pacific Ocean", "The Atlantic Ocean"], "The northern coast borders the Arctic."],
  ["Which large bay is in northern Manitoba, Ontario and Quebec’s region?", "Hudson Bay", ["Bay of Fundy", "Georgian Bay"], "Churchill, Manitoba, is a port on Hudson Bay."],
  ["Which mountain range lies in western Canada?", "The Rocky Mountains", ["The Appalachians", "The Canadian Shield"], "The Rockies run through BC and Alberta."],
  ["The Great Lakes are found mostly between Canada and…", "the United States", ["Mexico", "Greenland"], "Four of the five Great Lakes are shared with the US."],
  ["The huge area of ancient rock around Hudson Bay is the…", "Canadian Shield", ["Interior Plains", "Appalachians"], "It covers much of Manitoba’s north and east."],
  ["Which landform region is mostly flat grassland with farms in southern Manitoba?", "The Interior Plains (Prairies)", ["The Rocky Mountains", "The Arctic Islands"], "Flat land is good for farming."],
  ["Which river runs through Quebec and Ontario and flows to the Atlantic?", "The St. Lawrence River", ["The Red River", "The Fraser River"], "It links the Great Lakes to the sea."],
  ["Which river runs north through Winnipeg into Lake Winnipeg?", "The Red River", ["The Saskatchewan River", "The Fraser River"], "It begins in the United States."],
  ["How does the Canadian Shield’s thin soil and rock affect life in northern Manitoba?", "Mining and forestry are more common than large-scale farming", ["Everyone farms wheat", "No one can live there"], "The environment shapes jobs.", true],
  ["Fertile prairie soil has led to which industry in southern Manitoba?", "Farming", ["Deep-sea fishing", "Rainforest logging"], "Soil, climate and land shape how people make a living.", true],
  ["Why do communities in the Arctic often have homes built on stilts or raised foundations?", "Frozen ground (permafrost) can thaw and shift", ["To see further away", "To reach the sea"], "Cold climates need special building methods.", true],
  ["Which of these is the highest mountain in Canada?", "Mount Logan, in Yukon", ["Mount Royal", "Mount Hope"], "It is in the St. Elias Mountains.", true],
  ["Which direction should you face to go from Winnipeg to Hudson Bay?", "North", ["South", "West"], "Hudson Bay is north of Winnipeg.", true],
  ["You are lost without a compass. Which clue helps you find direction?", "The Sun rises in the east and sets in the west", ["Streetlights", "Your shadow is always south"], "Observe the landscape and sky.", true],
  ["A compass needle points to…", "magnetic north", ["the Sun", "the nearest town"], "Use a compass to orient yourself.", true],
];

export const canadaMap = bankUnit({
  id: "mb-canada-map-and-landforms",
  title: "Provinces, Capitals & Landforms",
  emoji: "🗺️",
  blurb: "Where Canada’s provinces, territories, capitals and landforms are.",
  parentNote:
    "Practises locating Canada’s provinces, territories and capitals, its oceans, landforms and waterways, and how the natural environment affects daily life.",
  standards: ["6-KL-022, 6-KL-025, 6-KL-026, 6-S-208", "locating provinces, capitals, landforms and bodies of water, and the influence of the environment"],
  items: GEOGRAPHY,
});

const SINCE_1945: Q[] = [
  ["Which war did Canada join under the United Nations from 1950 to 1953?", "The Korean War", ["The Gulf War", "The Boer War"], "Thousands of Canadians served in Korea."],
  ["The Cold War was mainly a rivalry between…", "the United States and the Soviet Union", ["Canada and Mexico", "France and Spain"], "It was tense but did not mean direct war between them."],
  ["Which Canadian prime minister won the Nobel Peace Prize in 1957 for his work on a UN peacekeeping force?", "Lester B. Pearson", ["Brian Mulroney", "Stephen Harper"], "He was then Canada’s foreign minister."],
  ["What does a peacekeeper do?", "Helps keep fighting from restarting and protects civilians", ["Starts battles", "Collects taxes"], "Canada has taken part in many UN missions."],
  ["In which war did Canada send forces in 1991 after Iraq invaded Kuwait?", "The Gulf War", ["The Korean War", "The Cold War"], "A UN-backed coalition took part."],
  ["Canada sent soldiers to Afghanistan from 2001 to…", "2014", ["1960", "1990"], "Canada’s combat role ended in 2011 and training continued until 2014."],
  ["After the Second World War, many people who had lost their homes lived in…", "displaced persons camps", ["new castles", "airports"], "Canada accepted many refugees from Europe."],
  ["The Holocaust was…", "the persecution and murder of six million Jewish people and others by Nazi Germany", ["a type of storm", "a peace treaty"], "We remember it so that it never happens again."],
  ["Who is a refugee?", "A person who flees their country to be safe from danger", ["A tourist", "A student on vacation"], "Canada welcomes refugees."],
  ["In 1956 Canada welcomed refugees from which country after an uprising?", "Hungary", ["Brazil", "Japan"], "Thousands of Hungarians came to Canada."],
  ["In 1979 and 1980, Canadians sponsored many refugees who fled by boat from…", "Vietnam and neighbouring countries", ["Norway", "Peru"], "They were often called the “boat people”."],
  ["Which prime minister led during the 1982 Constitution Act with the Canadian Charter of Rights and Freedoms?", "Pierre Elliott Trudeau", ["Joe Clark", "Louis St. Laurent"], "The Charter became part of Canada’s constitution."],
  ["Which prime minister’s government introduced the Canadian Bill of Rights in 1960?", "John Diefenbaker", ["Lester B. Pearson", "Brian Mulroney"], "It was a step toward the Charter."],
  ["Under which prime minister did Newfoundland become Canada’s tenth province in 1949?", "Louis St. Laurent", ["Wilfrid Laurier", "John A. Macdonald"], "St. Laurent became prime minister in 1948."],
  ["The Canadian flag with the red maple leaf was first raised in…", "1965", ["1867", "1945"], "It replaced the Red Ensign."],
  ["Who was Canada’s first female prime minister, in 1993?", "Kim Campbell", ["Jean Chrétien", "Paul Martin"], "She served a few months in 1993."],
  ["The Canada–United States Free Trade Agreement of 1988 was signed under which prime minister?", "Brian Mulroney", ["Pierre Trudeau", "Lester Pearson"], "It later led to a broader trade deal."],
  ["In 1999, which new territory was created in northern Canada?", "Nunavut", ["Manitoba", "Labrador"], "Nunavut means “our land” in Inuktitut."],
  ["In 2008 the Prime Minister apologized in Parliament for…", "the residential school system", ["the Manitoba Act", "the building of the railway"], "Residential schools harmed First Nations, Inuit and Métis children."],
  ["Who was Canada’s prime minister during most of the Second World War and until 1948?", "William Lyon Mackenzie King", ["John Diefenbaker", "Jean Chrétien"], "The Canadian Citizenship Act took effect in 1947 under him.", true],
  ["The first Canadian Citizenship Act took effect in…", "1947", ["1867", "1982"], "Before then people were British subjects.", true],
  ["Which Canadian prime minister served from 1993 to 2003?", "Jean Chrétien", ["Brian Mulroney", "Paul Martin"], "He served three terms.", true],
  ["Which of these is a global event that affected Canadians in 2020?", "The COVID-19 pandemic", ["A moon landing", "The Cold War"], "Disease spread around the world.", true],
  ["The SARS outbreak of 2003 mainly affected people in which Canadian city?", "Toronto", ["Winnipeg", "Halifax"], "It showed how disease can spread worldwide.", true],
  ["In 1984 and 1985 many Canadians donated money for relief of a famine in…", "Ethiopia", ["Iceland", "Australia"], "Famine means a severe shortage of food.", true],
  ["Why do countries work together on climate change?", "Environmental changes affect people everywhere", ["It only affects ships", "Nobody is affected"], "International cooperation is needed for global problems.", true],
  ["Canada is a member of NATO. What does that mean?", "Canada has joined with other countries to defend one another", ["Canada does not have an army", "Canada is part of a school"], "NATO was founded in 1949.", true],
  ["A Canadian prime minister can be a person who…", "leads the federal government", ["only opens shops", "only makes maps"], "The prime minister is the head of government.", true],
];

export const since1945 = bankUnit({
  id: "mb-canada-since-1945",
  title: "Canada & the World Since 1945",
  emoji: "🌍",
  blurb: "Prime ministers, peacekeepers, refugees and big world events since 1945.",
  parentNote:
    "Practises prime ministers since 1945 and their achievements, Canada’s role in world conflicts and peacekeeping, and global events that affected Canadians such as refugee movements, relief efforts and disease.",
  standards: ["6-KH-038, 6-KG-043, 6-KG-044, 6-VG-014, 6-VG-015", "prime ministers since 1945, Canada in world conflicts, and global events that affected Canadians"],
  items: SINCE_1945,
});

const INDUSTRY: Q[] = [
  ["Urbanization means…", "more people living in cities and towns", ["more people living on farms", "fewer buildings"], "After 1945, Canada’s cities grew quickly."],
  ["After 1945, Canada’s population grew because of immigration and the…", "baby boom", ["gold rush", "fur trade"], "Many families had more children."],
  ["Suburbs are…", "neighbourhoods built at the edge of a city", ["places on the Moon", "farms in the north"], "Cars made suburbs possible."],
  ["The Trans-Canada Highway opened in…", "1962", ["1867", "1920"], "It links the provinces from coast to coast."],
  ["Which Canadian waterway opened in 1959 and let ocean ships travel to the Great Lakes?", "The St. Lawrence Seaway", ["The Red River", "The Panama Canal"], "It joined Canada and the US."],
  ["Television broadcasts began in Canada in…", "1952", ["1900", "1970"], "The CBC started the first stations in 1952."],
  ["Which invention changed communication the most since 1990?", "The internet", ["The wagon wheel", "The abacus"], "It lets people send messages instantly."],
  ["Which device lets you talk to someone anywhere while you move around?", "A cellphone", ["A telegraph", "A rotary phone"], "Mobile phones changed communication."],
  ["The Canadarm, first used in 1981, helps astronauts by…", "moving objects in space", ["digging a mine", "sewing clothing"], "It was designed in Canada."],
  ["Airplanes and airports have made travel across Canada…", "much faster", ["slower", "impossible"], "Planes cross the country in hours."],
  ["After 1945, more young people stayed in school longer and went to…", "colleges and universities", ["fur-trade posts", "farms only"], "Education opportunities grew."],
  ["Which farm machine helps a farmer harvest grain quickly?", "A combine", ["A canoe", "A telescope"], "Machines have changed farming."],
  ["On the Prairies since 1945, farms have generally become…", "larger and run with fewer workers", ["smaller and run with more horses", "all abandoned"], "Machinery meant fewer farmers could farm more land."],
  ["Canola is a crop first developed by…", "Canadian plant scientists", ["Viking farmers", "Egyptian scientists"], "It is now a major Prairie crop.", true],
  ["Agriculture matters to Canada because it…", "provides food and jobs and is sold around the world", ["makes the weather", "stops trade"], "Canada exports many farm products.", true],
  ["Hydroelectricity is made by…", "using flowing water to turn turbines", ["burning cookies", "freezing air"], "Manitoba produces much of its power this way.", true],
  ["What change in the economy came with computers and the internet?", "More jobs in technology and services", ["Fewer schools", "The end of all farming"], "Industries change over time.", true],
  ["Natural resources such as oil, minerals and forests support which type of industry?", "Resource industries", ["Only entertainment", "Only toys"], "They are a big part of the Canadian economy.", true],
  ["Which change helped people in small communities share information with the world?", "The internet and satellites", ["The printing press", "Handwritten letters only"], "Communication technology connects communities.", true],
  ["One effect of more cars was…", "more highways and suburbs", ["fewer roads", "no travel"], "Cars changed how cities were built.", true],
  ["Which is a downside of rapid industrial growth?", "More pollution", ["Fewer jobs everywhere", "No new inventions"], "Growth can harm the environment.", true],
  ["Before refrigeration, how did people keep food from spoiling?", "Salting, drying and cold cellars", ["Microwaves", "Freezers"], "Technology has changed food storage.", true],
  ["An example of a service industry is…", "teaching or health care", ["mining coal", "growing wheat"], "Services provide help instead of goods.", true],
  ["A major change in education since 1945 is…", "more people have access to school and computers", ["no teachers", "school only for adults"], "Technology and policy changed learning.", true],
  ["The first long-distance Canadian rail system was the…", "Canadian Pacific Railway", ["Canadian Hockey League", "Canada Post"], "It was built before 1945 but still matters.", true],
  ["Which of the following is NOT a kind of transportation?", "A glossary", ["A train", "An airplane"], "A glossary is part of a book."],
  ["Which of these is a form of mass communication?", "A newspaper", ["A secret note", "A whisper"], "Mass media reach many people."],
];

export const industry = bankUnit({
  id: "mb-industry-and-technology",
  title: "Industry & Technology",
  emoji: "🏭",
  blurb: "How farms, factories and new inventions have changed life since 1945.",
  parentNote:
    "Practises how industry and technology have changed life in Canada since 1945, including urbanization, transportation, communication, education and the importance of agriculture.",
  standards: ["6-KE-058, 6-VE-018", "how industry and technology changed life in Canada since 1945, and the importance of agriculture"],
  items: INDUSTRY,
});

const CITIZENS: Q[] = [
  ["Which right do Canadian citizens aged 18 and over have today?", "The right to vote", ["The right to ignore laws", "The right to stop paying taxes"], "Voting is an important right."],
  ["A responsibility of Canadian citizens is to…", "obey the law", ["ignore others’ rights", "avoid voting"], "Rights come with responsibilities."],
  ["Which is a responsibility of citizens?", "Respect other people’s rights", ["Make fun of others", "Skip jury duty always"], "Everyone’s rights matter."],
  ["Which document, part of the Constitution Act of 1982, lists the rights and freedoms of people in Canada?", "The Canadian Charter of Rights and Freedoms", ["The Manitoba Act", "The Indian Act"], "It protects freedoms such as speech and religion."],
  ["Women first won the right to vote in a provincial election in which province in 1916?", "Manitoba", ["Quebec", "Newfoundland"], "Manitoba was the first province to allow it."],
  ["Which Manitoba activist campaigned for women’s right to vote?", "Nellie McClung", ["Louis Riel", "Terry Fox"], "She led the 1914 Women’s Parliament in Winnipeg."],
  ["Most women won the right to vote in federal elections in…", "1918", ["1867", "1982"], "It was extended in 1918 and 1919."],
  ["First Nations people living on reserves could vote in federal elections without giving up their status starting in…", "1960", ["1867", "1915"], "Voting rights for First Nations people came late."],
  ["Inuit gained the right to vote in federal elections in…", "1950", ["1867", "1990"], "The Inuit voting right came in 1950."],
  ["People of Chinese, Japanese and South Asian background were allowed to vote federally by…", "1948", ["1867", "1900"], "Rights were denied for many years because of discrimination."],
  ["At the time of Confederation, who could usually vote?", "Property-owning men", ["All adults", "All children"], "Many people were left out, including women."],
  ["Today, a person born in Canada becomes a citizen…", "at birth", ["only at age 18", "only by paying a fee"], "Others can become citizens through a process."],
  ["Which of these is a freedom in the Charter?", "Freedom of expression", ["Freedom to avoid school", "Freedom to harm others"], "People can share their thoughts."],
  ["The Charter protects the right to use…", "English or French when dealing with the federal government", ["only Latin", "only one language everywhere"], "Canada has two official languages."],
  ["In 1979 the Supreme Court said that Manitoba’s 1890 law ending French as an official language was…", "unconstitutional", ["perfect", "required"], "French was recognized again in the province’s laws and courts."],
  ["Francophones in Manitoba are…", "people whose first language is French or who speak French as part of their community", ["people who live in Quebec only", "only people in Winnipeg"], "Manitoba has had a French-speaking community since the fur trade."],
  ["A current issue about citizenship in Canada is…", "how to welcome and include newcomers", ["whether to bring back the horse and buggy", "how many flags exist"], "Immigration and inclusion are ongoing issues.", true],
  ["Another current issue for Canadians is…", "reconciliation with First Nations, Inuit and Métis peoples", ["the price of crayons", "the age of the Sun"], "Reconciliation is about repairing relationships.", true],
  ["Why is voting important in a democracy?", "It lets citizens help choose their leaders", ["It is a game", "It lowers taxes automatically"], "Everyone’s voice counts.", true],
  ["Which group worked to win better wages and safe conditions for workers?", "Trade unions", ["Fur traders", "Mapmakers"], "The Winnipeg General Strike of 1919 was a famous labour event.", true],
  ["Suffragettes were people who…", "worked for the right of women to vote", ["built the railway", "sailed to Canada"], "They gave speeches and wrote petitions.", true],
  ["Why should we remember that many groups struggled for rights?", "To value what past generations achieved and keep rights strong", ["To blame children", "Because it is a game"], "Rights were won through hard work.", true],
  ["A benefit of living in Canada is…", "free public education and health care", ["no weather", "no rules"], "Canada offers education, health care and safety.", true],
  ["Which of these shows being active in democracy at school?", "Running for student council", ["Hiding from class", "Ignoring a vote"], "Taking part helps your community.", true],
  ["Compared with 1867, today in Canada…", "far more people can vote and have equal rights under the law", ["fewer people can vote", "only men can vote"], "Rights have grown over time.", true],
  ["The Official Languages Act, passed in 1969, made English and French…", "the official languages of the federal government", ["optional", "banned"], "It is part of the protections for francophones.", true],
  ["In Canada, which responsibility helps keep the courts fair?", "Serving on a jury when called", ["Hiding in the basement", "Voting twice"], "Jury duty is a civic responsibility.", true],
];

export const citizens = bankUnit({
  id: "mb-rights-then-and-now",
  title: "Rights Then & Now",
  emoji: "🗳️",
  blurb: "Who had rights in 1867 and how rights and responsibilities have grown.",
  parentNote:
    "Practises how the rights and responsibilities of citizens at Confederation compare to today, including women, First Nations, Métis and Inuit peoples and francophones, and current citizenship issues.",
  standards: ["6-KC-002, 6-KC-006, 6-VC-001, 6-VC-003, 6-VC-004, 6-VH-013, 6-VI-006", "citizens’ rights and responsibilities then and now, and current citizenship issues"],
  items: CITIZENS,
});

const IDENTITY: Q[] = [
  ["Which Manitoba organization represents First Nations in the province?", "The Assembly of Manitoba Chiefs", ["The Société franco-manitobaine", "The Winnipeg Jets"], "It is a voice for many First Nations."],
  ["Which organization represents the Red River Métis in Manitoba?", "The Manitoba Métis Federation", ["The Assembly of First Nations", "Pluri-Elles"], "It speaks for Manitoba Métis citizens."],
  ["The Assembly of First Nations is…", "a national organization for First Nations", ["a school", "a sports league"], "It works across Canada."],
  ["The Métis National Council represents…", "the Métis Nation at the national level", ["only the Arctic", "a hockey league"], "It speaks for Métis people across the country."],
  ["Which organization promotes the rights of francophones in Manitoba?", "The Société franco-manitobaine", ["The Manitoba Museum", "The Red Cross"], "It is based in Saint-Boniface."],
  ["Pluri-Elles is a Manitoba organization that…", "supports francophone women", ["sells cars", "runs a ski hill"], "It is part of the francophone community."],
  ["Which of these can help shape a person’s identity?", "Family, language and culture", ["Only the weather", "Only a phone"], "Identity comes from many parts of life."],
  ["Which sentence shows that a person’s identity can include more than one group?", "A student can be Métis, a francophone and a hockey player at the same time.", ["A person can only belong to one group.", "Groups cannot overlap."], "Identity is made of many parts."],
  ["National identity is…", "the feeling of belonging to a country", ["a type of passport", "a map"], "It is shaped by shared values and history."],
  ["Which of these might be a part of Canadian identity?", "Many languages and cultures living together", ["Only one language", "No holidays"], "Canada is diverse."],
  ["Terry Fox, who began a cross-Canada run for cancer research in 1980, was from which province?", "Manitoba (born in Winnipeg)", ["Alberta", "Yukon"], "His Marathon of Hope raised money for research."],
  ["Who was the Manitoba politician who held an eagle feather in the legislature in 1990?", "Elijah Harper", ["Louis Riel", "Lester Pearson"], "He is remembered for standing up for Indigenous peoples’ rights."],
  ["Roberta Bondar was the first Canadian woman to…", "travel in space", ["climb Mount Logan", "lead a nation"], "She flew on the Space Shuttle in 1992."],
  ["Viola Desmond is remembered for…", "refusing to leave a whites-only section of a movie theatre in 1946", ["flying a plane", "building a railway"], "She stood against racial discrimination."],
  ["Murray Sinclair, from Manitoba, led which commission?", "The Truth and Reconciliation Commission", ["The Charter Commission", "The Hockey Hall of Fame"], "It gathered stories about residential schools.", true],
  ["Tommy Douglas is often called the “father of” what in Canada?", "Medicare", ["The railway", "The flag"], "He led the first government in North America to bring in public health insurance.", true],
  ["Why do people form organizations?", "To work together for shared goals and rights", ["To avoid each other", "To build mazes"], "Groups can speak with a stronger voice.", true],
  ["Which of these is a national Inuit organization?", "Inuit Tapiriit Kanatami", ["The Canadian Tire", "The Grey Cup"], "It represents Inuit across Canada.", true],
  ["Cultural and language groups help keep traditions alive by…", "teaching language, celebrating events and sharing stories", ["forgetting the past", "closing schools"], "Language and culture are valued.", true],
  ["A student wants to learn their family’s language. Which organization could help?", "A community cultural or language centre", ["A shoe store", "A gas station"], "Many communities have language programs.", true],
  ["Respecting people of all cultures means…", "treating everyone with dignity and curiosity", ["only talking to people like you", "making jokes about differences"], "Respect is a core value.", true],
  ["The arts such as music, dance and painting help people…", "express their culture and identity", ["avoid each other", "stop speaking"], "Art carries stories.", true],
  ["Which statement is respectful when talking about First Nations?", "Many First Nations have their own languages and cultures.", ["All First Nations are the same.", "First Nations are only in the past."], "Do not treat all Nations as one.", true],
  ["Bilingual signs in Manitoba show that…", "English and French are both used in some places", ["only one language is allowed", "signs are for decoration"], "Both languages are part of Canada’s identity.", true],
  ["Which is a reason why someone’s identity may change over time?", "They learn new things and experience new communities", ["Their name is spelled wrong", "The weather changes"], "People grow.", true],
  ["Individuals from Canada’s past are remembered through…", "stories, monuments and museums", ["secret codes", "empty rooms"], "We learn about achievements to honour them.", true],
  ["Who is considered a founder of Manitoba and led the Red River provisional government?", "Louis Riel", ["Terry Fox", "Nellie McClung"], "He represented the Métis at Red River."],
];

export const identity = bankUnit({
  id: "mb-identity-and-organizations",
  title: "Identity & Organizations",
  emoji: "🧑‍🤝‍🧑",
  blurb: "People and groups that shape who we are in Canada.",
  parentNote:
    "Practises what shapes personal and national identity, organizations that promote the rights of First Nations, Métis, Inuit and francophone people in Manitoba, and well-known individuals from Canada’s past and present.",
  standards: ["6-KI-016, 6-KI-020, 6-KI-020A, 6-KI-020F, 6-KI-021, 6-VI-007, 6-VI-008, 6-VI-009", "personal and national identity, groups and organizations, and individuals from Canada’s past and present"],
  items: IDENTITY,
});

const FAIRNESS: Q[] = [
  ["Which is a peaceful way to settle a disagreement?", "Talk it over and listen to each other", ["Shout until the other gives up", "Walk away without a word"], "Clarify, listen and look for a fair solution."],
  ["Compromise means…", "each side gives up a little to reach an agreement", ["one side always wins", "no one speaks"], "Both sides gain something."],
  ["Negotiation is…", "talking to reach an agreement", ["a type of dance", "a sort of map"], "People discuss ideas and options."],
  ["Clarifying a problem means…", "asking questions so everyone understands it", ["giving up", "blaming someone"], "Understand before you solve."],
  ["Consensus means…", "everyone in a group agrees on a decision they can support", ["the loudest voice wins", "a coin flip"], "Build consensus by listening."],
  ["A group of students must choose a class project. A fair way to decide is to…", "listen to all ideas and vote or find agreement", ["let one person choose", "pick the project nobody wants"], "Everyone’s voice counts."],
  ["Discrimination is…", "treating people unfairly because of who they are", ["choosing a favourite colour", "sharing lunch"], "It can be based on race, gender, ability, religion and more."],
  ["Which is an example of discrimination?", "Not letting someone join a game because of their skin colour", ["Picking teams at random", "Taking turns"], "It is unfair and hurtful."],
  ["Bias is…", "favouring or disliking something unfairly", ["a type of exercise", "a sports score"], "Biased views are not balanced."],
  ["A classmate is called an unkind name because of where their family is from. What can you do?", "Say it’s not okay and tell a trusted adult", ["Laugh along", "Join in"], "Stand up safely and get help."],
  ["What does it mean to be fair?", "To treat people justly and give everyone a fair chance", ["To always get your way", "To follow only your friends"], "Fairness is about equal respect."],
  ["Equality means…", "everyone has the same rights and opportunities", ["everyone is identical", "no one has rights"], "Equality and equity are linked."],
  ["Which statement uses respectful language?", "Students with different abilities are part of our class.", ["Those students are a problem.", "People like that don’t belong."], "Use words that respect diversity."],
  ["Which word is respectful when talking about people from many cultures?", "Diverse", ["Weird", "Strange"], "Diversity is a strength."],
  ["Poverty is one factor that can…", "make it harder for some people to get the same chances", ["make everyone rich", "end all problems"], "Inequities can be caused by poverty, racism and sexism."],
  ["Racism is…", "treating people unfairly because of their race or ethnicity", ["a school subject", "a weather event"], "It leads to inequity."],
  ["Sexism is…", "treating people unfairly because of their gender", ["a type of food", "a sport"], "It is unfair."],
  ["A school finds that some students cannot afford supplies. A fair solution is…", "a supply drive or a program that provides supplies to anyone who needs them", ["only give supplies to the fastest students", "tell students to stop learning"], "Propose solutions that help everyone.", true],
  ["A class makes a rule that everyone gets a turn at the computer. This shows…", "fairness and equality", ["unfairness", "bias"], "Everyone gets a turn.", true],
  ["You notice a friend always gets left out of games. What is a kind step?", "Invite them to join and include them", ["Ignore them", "Tell them to go away"], "Inclusion is a choice.", true],
  ["Why does historical bias matter today?", "It can still affect how people are treated", ["It disappeared", "It was only about maps"], "We learn from the past.", true],
  ["Which is a way to raise awareness of an unfair situation?", "Make posters or give a short talk with facts", ["Spread rumours", "Say nothing"], "Share evidence respectfully.", true],
  ["Which action helps build a more inclusive community?", "Learning about different cultures and welcoming new neighbours", ["Avoiding new people", "Using unkind jokes"], "Community means everyone belongs.", true],
  ["Which sentence shows a willingness to support a solution to an inequity?", "I will help organize a clothing drive for families who need it.", ["It’s not my problem.", "I don’t care."], "Taking action matters.", true],
  ["Why is it important to listen to someone with a different point of view?", "To understand why they think that way", ["To prove them wrong", "To end the talk"], "Listening builds understanding.", true],
  ["When you make a decision about litter at the park, you show care for…", "the environment", ["only yourself", "nobody"], "Choose actions that look after places.", true],
  ["Which choice shows respect for a historic place such as a memorial or burial ground?", "Visit quietly and leave things as you found them", ["Climb on it for fun", "Take a souvenir"], "Treat historic places with respect.", true],
];

export const fairness = bankUnit({
  id: "mb-fairness-and-respect",
  title: "Fairness & Respect",
  emoji: "🤝",
  blurb: "Solve problems peacefully and speak up when something is unfair.",
  parentNote:
    "Practises resolving conflicts peacefully, building consensus, recognizing bias and discrimination, using respectful language, and supporting solutions to inequities.",
  standards: ["6-S-101, 6-S-102, 6-S-103, 6-S-104, 6-S-105, 6-S-106, 6-S-401, 6-KP-054, 6-VP-017", "resolving conflict fairly, recognizing bias and discrimination, and supporting solutions to inequities"],
  items: FAIRNESS,
});

const HISTORY_SKILLS: Q[] = [
  ["A timeline shows…", "events in the order they happened", ["only maps", "only pictures"], "Dates go from earliest to latest."],
  ["Which event happened first?", "Confederation, 1867", ["Manitoba joined, 1870", "The Charter, 1982"], "1867 comes before 1870 and 1982."],
  ["Put these in order, earliest first: Manitoba joins (1870), First World War begins (1914), Charter (1982).", "Manitoba joins, First World War begins, Charter", ["Charter, Manitoba joins, First World War begins", "First World War begins, Charter, Manitoba joins"], "Check the dates."],
  ["Which event is later than 1945?", "Canadian flag raised in 1965", ["Confederation in 1867", "Manitoba joins in 1870"], "1965 is after 1945."],
  ["A primary source is…", "created by someone who was there at the time", ["a modern textbook", "a movie about it"], "Examples are letters, photographs and diaries."],
  ["Which is a secondary source?", "A textbook written today about the 1800s", ["A diary from 1870", "A photograph from 1885"], "A secondary source is written later."],
  ["Which is a primary source about the railway?", "A photograph taken while workers laid the track", ["A modern movie", "A school poster"], "It was created at the time."],
  ["To research a topic, a historian first…", "plans questions and chooses sources", ["writes the conclusion", "guesses"], "Plan your inquiry first."],
  ["A good historical question is…", "How did the railway change the Prairies?", ["Is it pretty?", "What colour?"], "Open questions invite deeper research."],
  ["To organize information, a student might use…", "a chart, outline or concept map", ["a recipe", "a game board"], "Organizers help sort facts."],
  ["Why list your sources when you finish research?", "So readers can check where you found information", ["To make the page longer", "To impress the teacher with names"], "Sources show your information is honest."],
  ["A photograph from long ago is useful because it…", "gives visual evidence of how things looked", ["can never be wrong", "tells the whole story"], "Photos need careful study."],
  ["Which source tells you about daily life in a past community?", "Artifacts such as tools or clothing", ["A weather forecast for next week", "A shopping list"], "Objects are material evidence."],
  ["A song written during a time in history can be used to…", "learn about people’s feelings and ideas at that time", ["find the weather", "prove one fact for all"], "Music is a source of information.", true],
  ["Two accounts of the same event disagree. A careful historian should…", "compare them and look for more evidence", ["pick the one she likes", "ignore both"], "Compare differing accounts.", true],
  ["Why might two people describe the same event differently?", "They have different perspectives and experiences", ["One cannot read", "Events never happened"], "Perspectives shape accounts.", true],
  ["Why do interpretations of history change?", "New information is found, or earlier voices are listened to", ["History books are never written", "People forget"], "History is revised.", true],
  ["After reading three sources, a student writes a conclusion. It should be based on…", "evidence from the sources", ["a guess", "the first thing she read"], "Draw conclusions from evidence.", true],
  ["You learn something new that changes your opinion. A good response is to…", "think about your assumptions and update your view", ["ignore it", "insist you were right"], "Evaluate personal assumptions.", true],
  ["A historical novel set in the 1870s can help you understand…", "how people may have felt but is not a primary source", ["nothing", "the exact weather"], "Fiction can interpret the past, but check facts.", true],
  ["An old letter from a Red River settler is…", "a primary source", ["a secondary source", "an opinion poll"], "It was written at the time."],
  ["An encyclopedia article about Louis Riel is…", "a secondary source", ["a primary source", "an artifact"], "It was written later by someone else."],
  ["A newspaper from 1919 describing the Winnipeg General Strike is…", "a primary source", ["a modern summary", "a legend"], "It was printed at the time of the event.", true],
  ["Which approach shows respect for historic burial grounds and artifacts?", "Leave them in place and tell the proper authorities if you find them", ["Take them home", "Sell them"], "Treat them with respect.", true],
  ["Which of these is a good method for comparing viewpoints?", "Make a chart of who said what and why", ["Skip the evidence", "Ask only one person"], "Organize differing perspectives.", true],
  ["When you use a map as a source, what should you check?", "Who made it, when, and what its legend says", ["Only the colours", "Only the paper"], "Read maps critically.", true],
];

export const historySkills = bankUnit({
  id: "mb-history-research-skills",
  title: "History Research Skills",
  emoji: "🕰️",
  blurb: "Make timelines, check sources and compare accounts.",
  parentNote:
    "Practises sequencing events on timelines, telling primary and secondary sources apart, planning a historical inquiry, comparing differing accounts and drawing conclusions from evidence.",
  standards: ["6-S-200, 6-S-201, 6-S-204, 6-S-300, 6-S-302, 6-S-303, 6-S-305, 6-S-307, 6-S-308, 6-S-309, 6-S-310", "timelines, using and comparing sources, planning an inquiry and drawing conclusions"],
  items: HISTORY_SKILLS,
});
