import { bankUnit, type Q } from "../own";

// Grade 6 social studies, Canada: A Country of Change (1867 to the present). Outcomes are cited by code.
// Indigenous content is light and factual, and needs review with First Nations, Métis and Inuit partners.

const CONFEDERATION: Q[] = [
  ["In what year did Confederation create the Dominion of Canada?", "1867", ["1776", "1905"], "Canada became a country on July 1, 1867."],
  ["The law that created Canada in 1867 is the…", "British North America Act", ["Canadian Charter", "Manitoba Act"], "The BNA Act set up Canada as a federation."],
  ["Which four provinces were the first to join in 1867?", "Ontario, Quebec, New Brunswick and Nova Scotia", ["Manitoba, Alberta, Quebec and Yukon", "British Columbia, Ontario, Alberta and PEI"], "These four joined first, in 1867."],
  ["Who was Canada's first prime minister?", "Sir John A. Macdonald", ["Louis Riel", "Wilfrid Laurier"], "Macdonald led the new country from 1867."],
  ["A federal system means…", "power is shared between a national and provincial governments", ["only one government rules", "kings pick all laws"], "Canada's national and provincial governments each have responsibilities."],
  ["What is Confederation?", "The joining of colonies to form one country", ["A battle", "A type of treaty with France"], "Colonies joined together as provinces."],
  ["What was Rupert's Land?", "A huge territory in the northwest that the Hudson's Bay Company controlled", ["A city in Quebec", "A mountain range"], "It included much of present-day Manitoba."],
  ["In 1869 Canada arranged to take over Rupert's Land from the…", "Hudson's Bay Company", ["North West Mounted Police", "Canadian Pacific Railway"], "The company sold its rights to Canada."],
  ["Who lived in the Red River settlement before Manitoba became a province?", "Métis, First Nations and settlers", ["Only fur traders", "Nobody"], "It was home to many people, including a large Métis community."],
  ["Who led the Métis provisional government at Red River in 1869 and 1870?", "Louis Riel", ["Sir John A. Macdonald", "Gabriel Dumont"], "Riel spoke for the Red River people."],
  ["Why did people in Red River worry when surveyors arrived in 1869?", "They feared losing their land and rights", ["They wanted free pencils", "They disliked maps of the sea"], "The Métis had not been asked about the transfer."],
  ["In what year did Manitoba join Confederation?", "1870", ["1867", "1905"], "The Manitoba Act took effect in 1870."],
  ["Manitoba was first called the…", "“postage stamp province”", ["“golden province”", "“maple province”"], "It was small and square at first."],
  ["The Manitoba Act protected…", "both French and English language rights and Métis land", ["only the railway", "only fishing"], "Red River delegates won protection for rights and land."],
  ["Which two men travelled to Ottawa to help negotiate the Manitoba Act?", "Father Noël-Joseph Ritchot and Alfred Scott", ["Sir John A. Macdonald and Louis Riel", "Donald Smith and John Schultz"], "Ritchot was a priest and delegate from Red River."],
  ["Which Archbishop was involved in Manitoba's entry into Confederation?", "Alexandre-Antonin Taché", ["Henry Ford", "Jacques Cartier"], "Archbishop Taché was at Saint-Boniface."],
  ["Which province joined Confederation in 1871?", "British Columbia", ["Alberta", "Saskatchewan"], "A promise of a railway helped bring BC in."],
  ["Which was the smallest province to join in 1873?", "Prince Edward Island", ["Yukon", "Nunavut"], "PEI joined in 1873."],
  ["In what year did Alberta and Saskatchewan become provinces?", "1905", ["1870", "1949"], "Both joined together in 1905."],
  ["Which province was the last to join Confederation?", "Newfoundland, in 1949", ["Manitoba, in 1870", "Alberta, in 1905"], "Newfoundland and Labrador joined in 1949."],
  ["Which Canadian city is the capital of Manitoba?", "Winnipeg", ["Brandon", "Thompson"], "Winnipeg is where the legislature sits."],
  ["Which body of water is the largest lake that is mostly in Manitoba?", "Lake Winnipeg", ["Lake Superior", "Lake Ontario"], "Lake Winnipeg is one of the largest lakes in Canada."],
  ["The Red River and the Assiniboine River meet at a place in Winnipeg called…", "The Forks", ["The Rock", "The Peg"], "Indigenous peoples gathered there for thousands of years.", true],
  ["Why did the Métis want a province of their own?", "To protect their land, language and way of life", ["To start a railway", "To close the river"], "The provisional government sought guarantees.", true],
  ["Where was the Métis provisional government formed in 1869?", "Red River Settlement", ["Halifax", "Victoria"], "It formed in the Red River area near Fort Garry.", true],
  ["Who were the “Fathers of Confederation”?", "Leaders who helped create Canada", ["Explorers of the Arctic", "Fur-trade inventors"], "They met at Charlottetown and Quebec in 1864.", true],
  ["Why did Canada want to add the West to Confederation?", "To expand the country and open land for settlers", ["To make a new ocean", "To move the capital"], "Leaders wanted a country that stretched from sea to sea.", true],
  ["Which of these is a reason to join Confederation?", "Provinces could share costs such as railways", ["Provinces wanted to stop trading", "Provinces wanted separate currencies"], "Joining allowed colonies to cooperate.", true],
  ["Which sentence about Louis Riel is true?", "He led the Red River provisional government and is called the founder of Manitoba", ["He was Canada's first prime minister", "He built the railway"], "Parliament has recognized him as a founder of Manitoba.", true],
];

export const confederation = bankUnit({
  id: "mb-confederation",
  title: "Confederation & Manitoba",
  emoji: "🍁",
  blurb: "How Canada began in 1867 and how Manitoba joined in 1870.",
  parentNote:
    "Practises why Canada was formed in 1867, the British North America Act, which provinces joined and when, and the story of Red River, Louis Riel and Manitoba's entry into Confederation in 1870.",
  standards: ["6-KC-001, 6-KH-027, 6-KH-027F, 6-KH-033, 6-KH-034, 6-KL-023", "Confederation, the British North America Act, and Manitoba's entry into Confederation"],
  items: CONFEDERATION,
});

const TREATIES: Q[] = [
  ["What is a treaty?", "A formal agreement between nations", ["A kind of map", "A type of train"], "Treaties were made between First Nations and the Crown."],
  ["Treaty 1 was signed in 1871 near…", "Lower Fort Garry in Manitoba", ["Halifax", "Victoria"], "It was the first numbered treaty."],
  ["How many numbered treaties were made between 1871 and 1921?", "Eleven", ["Three", "Fifty"], "They are called Treaties 1 to 11."],
  ["Why did First Nations and the Crown make the numbered treaties?", "To agree about sharing the land and about the people's rights", ["To build a hockey rink", "To draw a map of Europe"], "Each side made promises."],
  ["A reserve is…", "land set aside for a First Nation under a treaty or the Indian Act", ["a kind of bank", "a train station"], "Reserves are communities with their own governments."],
  ["Treaty promises included things like…", "land, annuity payments and tools", ["free cars", "free airplanes"], "Promises varied by treaty."],
  ["Many First Nations people see treaties as…", "agreements that must be honoured by both sides", ["old papers that no longer matter", "jokes"], "Treaty rights continue today."],
  ["Which people lived in the Red River area, with their own culture and language, before and after the treaties?", "The Métis", ["The Vikings", "The Romans"], "The Métis are a distinct Indigenous people."],
  ["Who are the Métis?", "A distinct Indigenous people with roots in the fur trade", ["A kind of settler from Asia", "A province"], "The Métis Nation has its own culture and history."],
  ["Which force was created in 1873 to bring law to the West?", "North West Mounted Police", ["Canadian Army", "Prairie Guard"], "The NWMP later became the RCMP."],
  ["In 1874 the North West Mounted Police began their…", "march west", ["flight to the Arctic", "sailing trip to Europe"], "They travelled across the prairies."],
  ["What was a main job of the early North West Mounted Police?", "To keep order and enforce laws", ["To build bridges", "To sell tickets"], "They also worked with First Nations."],
  ["The North West Mounted Police later became the…", "RCMP", ["CPR", "HBC"], "RCMP stands for Royal Canadian Mounted Police."],
  ["What happened to the bison herds in the 1870s and 1880s?", "They were nearly wiped out", ["They doubled", "They moved to Ontario"], "Overhunting changed the way of life for Plains peoples."],
  ["Why was the loss of the bison hard for Plains First Nations and Métis?", "Bison were central to food, clothing and trade", ["Bison cost a lot of money", "Bison ran faster than trains"], "Food and trade depended on them."],
  ["The 1885 Resistance took place mainly in what is now…", "Saskatchewan", ["Nova Scotia", "Quebec"], "Fighting happened near Batoche and Duck Lake."],
  ["Which Métis leader was at the centre of the 1885 Resistance with Gabriel Dumont?", "Louis Riel", ["John A. Macdonald", "Wilfrid Laurier"], "Riel returned to help the Métis cause."],
  ["Who was the Métis military leader in 1885?", "Gabriel Dumont", ["Poundmaker", "Alexander Mackenzie"], "Dumont led the Métis fighters."],
  ["Which Cree leaders are remembered for seeking peace and protecting their people in this era?", "Poundmaker and Mistahimaskwa (Big Bear)", ["Sir John A. Macdonald and George Cartier", "Louis Riel and Ambroise Lépine"], "They are important Cree leaders."],
  ["Where did the main battle of the 1885 Resistance end?", "Batoche", ["Winnipeg", "Toronto"], "The Métis were defeated there in May 1885."],
  ["What was the result for Louis Riel?", "He was tried and hanged in 1885", ["He became prime minister", "He moved to Europe"], "His death is still remembered in Canada."],
  ["Why did the Métis and some First Nations resist in 1885?", "They were worried about land, food and being heard", ["They wanted to end the railway for fun", "They wanted new coins"], "The Métis petitions about land had gone unanswered."],
  ["What does “resistance” mean in this history?", "Standing up for rights and way of life", ["A school subject", "A kind of weather"], "The word describes people defending their rights."],
  ["Which person is a Métis leader in Manitoba history from 1867 to 1914?", "Louis Riel", ["Terry Fox", "Wayne Gretzky"], "Riel is one of Canada's well-known Métis leaders."],
  ["Why do Indigenous communities today say treaty promises are still important?", "Treaties are living agreements that were made to last", ["Treaties ended in 1900", "Treaties were about weather"], "Treaties set out a relationship between nations.", true],
  ["Which statement shows respect when learning about this history?", "There were many views, and Indigenous voices matter", ["There was only one view", "Only settlers' views matter"], "Compare different accounts of events.", true],
  ["Which source would help you learn the Métis point of view about 1885?", "Writings or oral history from Métis communities", ["A map of Europe", "A recipe book"], "Look for sources by the people involved.", true],
  ["Why is it important to learn about both treaties and reserves?", "They shaped where and how people live today", ["They are only about trees", "They cannot be understood"], "Their effects continue today.", true],
];

export const treaties = bankUnit({
  id: "mb-treaties-and-resistance",
  title: "Treaties, Métis & the Mounties",
  emoji: "🤝",
  blurb: "Treaties, reserves, the Métis, the NWMP and 1885.",
  parentNote:
    "Practises a first, respectful look at the numbered treaties and reserves, the Métis, the North West Mounted Police, the 1885 Resistance, and the Indigenous leaders of the time. This content needs review with First Nations, Métis and Inuit partners.",
  standards: ["6-KI-007, 6-KH-028, 6-KH-029, 6-KH-032", "treaties and reserves, the 1885 Resistance, the North West Mounted Police, and Indigenous leaders from 1867 to 1914"],
  items: TREATIES,
});

const HOMESTEADS: Q[] = [
  ["What is a homestead?", "A farm settled by a family, usually on land from the government", ["A type of boat", "A small shop"], "Settlers claimed land and farmed it."],
  ["Under the Dominion Lands Act, a settler paid $10 to claim how much land?", "160 acres", ["16 acres", "1600 acres"], "That is a quarter section."],
  ["To keep a homestead, a settler had to…", "live on it and farm it", ["sell it right away", "leave it empty"], "Settlers had to meet conditions to earn the title."],
  ["What was a section of land in the prairie survey?", "One square mile", ["One square metre", "One square kilometre"], "Land was divided into sections that are a mile on each side."],
  ["A quarter section is how many acres?", "160 acres", ["80 acres", "320 acres"], "A section is 640 acres. Divide by 4."],
  ["Why did the government survey the prairies into squares?", "To divide the land in an orderly way for settlers", ["To make a game board", "To plant flags"], "The survey system made land clear to claim."],
  ["Many early homes on the treeless prairie were made of…", "sod, or blocks of earth", ["glass", "metal"], "Sod houses used prairie soil and grass."],
  ["The government wanted immigrants to come to the prairies to…", "farm and grow Canada's population", ["build skyscrapers", "mine the Moon"], "Farming was important to the economy."],
  ["Who was the minister who promoted immigration to the West around 1896?", "Clifford Sifton", ["Wayne Gretzky", "Terry Fox"], "He advertised the “Last Best West”."],
  ["Which group of settlers came from Iceland to Manitoba, starting in 1875?", "Icelanders", ["Japanese", "Italians"], "They settled on Lake Winnipeg's shore at Gimli."],
  ["Many Ukrainian settlers came to the prairies, and brought…", "farming skills, food and church traditions", ["no belongings", "kangaroos"], "Ukrainian communities still shape the prairies."],
  ["Mennonite settlers came to southern Manitoba in the 1870s partly to…", "farm and keep their religious beliefs", ["mine gold", "work at sea"], "They were granted freedom to live by their faith."],
  ["Why was farming hard for homesteaders in the early years?", "Long, cold winters and isolation", ["Too many shops", "Too much traffic"], "Weather and distance made life difficult."],
  ["Which crop became the most important to prairie farmers?", "wheat", ["bananas", "rice"], "Wheat grown on the prairies fed the country and was sold abroad."],
  ["Marquis wheat was important because it…", "ripened early before frost", ["grew only in swamps", "needed no sun"], "Early ripening suited short prairie summers."],
  ["Which task was often done by women and children on a prairie homestead?", "gardening, cooking, and carrying water", ["flying planes", "driving trains"], "Everyone worked on the farm."],
  ["How did families on the prairies get news and goods from far away?", "By train and by mail", ["By teleportation", "By satellite"], "The railway linked the West to the East."],
  ["Which immigrants faced racism and a head tax when entering Canada?", "Chinese immigrants", ["Scottish immigrants", "French immigrants"], "Chinese workers had to pay a special tax."],
  ["The Chinese head tax started in 1885 at $50. Who paid it?", "Each Chinese person arriving", ["Only the Prime Minister", "The railway"], "It was a discriminatory tax."],
  ["A newcomer may face a challenge such as…", "a new language", ["a free house", "a snow day"], "Learning a new language is a common challenge."],
  ["What does discrimination mean?", "Treating people unfairly because of who they are", ["Sharing equally", "A kind of farm tool"], "Discrimination is unfair and hurtful."],
  ["Why was agriculture important to Canada's economy from 1867 to 1914?", "Selling grain brought money and jobs", ["It made cars", "It needed no workers"], "Wheat became a major export."],
  ["A “grain elevator” is used for…", "storing grain", ["storing water", "making cars"], "Elevators stood beside the railway."],
  ["Which group of people already lived on the prairies when homesteaders arrived?", "First Nations and Métis peoples", ["No one", "Only Vikings"], "Settlement changed their lives."],
  ["Immigration helped build Canada because newcomers…", "worked, farmed, started businesses and added their cultures", ["stayed only in cities", "did not work"], "Immigration shaped Canada's growth.", true],
  ["Why did the government advertise the “Last Best West” in Europe?", "To attract farmers to settle the prairies", ["To sell fish", "To attract tourists in winter only"], "Posters promised free land.", true],
  ["Which statement about the 1890-1914 immigration boom is true?", "Many newcomers came from Eastern Europe", ["No one came", "Everyone came from Asia"], "Ukrainians, Poles and others settled the West.", true],
  ["Which is a reason many immigrants left their homes?", "They wanted land, safety or a better life", ["They wanted to get lost", "They did not like food"], "Push and pull factors encouraged immigration.", true],
  ["Why was the CPR important to homesteaders?", "It brought settlers, supplies and markets for grain", ["It made wheat", "It built houses"], "Trains connected the farm to the world.", true],
  ["How can new communities show respect for newcomers today?", "Welcome them and learn from each other", ["Ignore them", "Make fun of their language"], "Respect builds a stronger community.", true],
];

export const homesteads = bankUnit({
  id: "mb-newcomers-and-homesteads",
  title: "Newcomers & Homesteads",
  emoji: "🌾",
  blurb: "Immigration to the prairies and life on a homestead.",
  parentNote:
    "Practises why Canada encouraged immigration to the West between 1890 and 1914, which groups came, the challenges newcomers met (including racism), daily life on a prairie homestead, and why farming mattered to Canada.",
  standards: ["6-KI-008, 6-KI-009, 6-KI-010, 6-KI-011, 6-KE-055", "immigration to the prairies, homestead life, challenges for newcomers, and the importance of agriculture"],
  items: HOMESTEADS,
});

const RAILWAY: Q[] = [
  ["What does CPR stand for?", "Canadian Pacific Railway", ["Canadian Prairie Road", "Central Pacific Route"], "The CPR joined the country by rail."],
  ["The Canadian Pacific Railway was finished in what year?", "1885", ["1867", "1914"], "The last spike was driven on November 7, 1885."],
  ["Where was the last spike of the CPR driven?", "Craigellachie, British Columbia", ["Winnipeg, Manitoba", "Halifax, Nova Scotia"], "A plain iron spike joined the east and west."],
  ["Why was the railway important to the new country?", "It linked the East and West and brought settlers", ["It replaced the post office", "It kept settlers away"], "The railway tied the country together."],
  ["The government promised British Columbia a railway to join…", "Confederation", ["the army", "the church"], "BC joined in 1871 on that promise."],
  ["Many thousands of workers who built the railway through the mountains were from…", "China", ["Iceland", "Brazil"], "Chinese workers did dangerous labour."],
  ["Why was railway work in the mountains dangerous?", "Explosions, rockfalls and harsh conditions", ["Too many pillows", "Too many cars"], "Many workers were injured or died."],
  ["Chinese railway workers were paid…", "less than other workers", ["more than other workers", "the same as the owners"], "They faced unfair treatment."],
  ["What did the railway do to the lives of First Nations and Métis peoples on the Plains?", "It brought settlement that changed their land use", ["Nothing at all", "It gave them free train rides forever"], "Settlers followed the railway."],
  ["Winnipeg became a big centre because…", "it was where many railways crossed", ["it was on the ocean", "it had a volcano"], "It was a gateway to the West."],
  ["A railway “spike” is a…", "big nail that holds the rail down", ["type of train car", "ticket"], "Spikes fasten rails to the ties."],
  ["Which of these shows the effect of the railway on towns?", "Towns grew up along the tracks", ["Towns moved into the ocean", "Towns vanished everywhere"], "Stations and elevators drew people."],
  ["What is a gold rush?", "A rush of people to a place where gold is found", ["A holiday", "A coin factory"], "People travelled far hoping to get rich."],
  ["Which gold rush brought thousands to the Yukon in 1896 to 1899?", "The Klondike Gold Rush", ["The Red River Gold Rush", "The Manitoba Gold Rush"], "Dawson City boomed."],
  ["Which Canadian territory was created in 1898 to manage the Klondike area?", "Yukon", ["Nunavut", "Manitoba"], "Yukon Territory was formed in 1898."],
  ["An earlier gold rush on the Fraser River in 1858 led to the founding of…", "the colony of British Columbia", ["Ontario", "Manitoba"], "Thousands of miners came."],
  ["Miners who went to the Klondike needed supplies. Who made money from them?", "Merchants and outfitters", ["Only the miners", "Nobody"], "Many people made money selling goods."],
  ["What was a hardship of the Klondike trail?", "Cold, hunger and steep passes", ["Too much sunshine", "Too many hotels"], "The journey was hard."],
  ["How did gold rushes affect Indigenous peoples?", "Miners and settlers entered their lands and changed life there", ["They had no effect", "Indigenous peoples all became miners"], "Newcomers came onto their territories."],
  ["The 1885 railway completion helped move troops during which event?", "the 1885 Resistance", ["the First World War", "Canada Day"], "The railway carried soldiers quickly west."],
  ["Which of these was sent across Canada by train?", "wheat", ["gold coins only", "ocean water"], "Trains carried grain to ports."],
  ["Why were Chinese workers treated unfairly after the railway was done?", "Racism led to the head tax and laws against them", ["They were too rich", "They left immediately"], "Discrimination affected their lives.", true],
  ["What was one effect of gold rushes on the economy?", "New towns and trade grew", ["Trade ended", "Farms vanished"], "Booming mining towns needed supplies.", true],
  ["Which tells the sequence best?", "CPR finished in 1885, Klondike Gold Rush in 1896", ["Klondike Gold Rush in 1850, CPR in 1860", "CPR finished in 1905, Confederation in 1867"], "Put events on a timeline.", true],
  ["How did the CPR change travel time across Canada?", "A trip took days instead of months", ["It took longer", "It did not change"], "Trains were much faster than wagons or boats.", true],
  ["Why do we remember the workers who built the CPR?", "Their hard and dangerous work helped link the country", ["They made mistakes", "They were famous actors"], "Their contributions deserve respect.", true],
  ["What does “transcontinental” mean?", "Crossing a whole continent", ["Under the sea", "Around a lake"], "Trans means across.", true],
  ["Which statement is a fact about the CPR?", "It was completed in 1885", ["It is the most beautiful ever", "It was the best idea"], "Facts can be checked. Opinions cannot.", true],
];

export const railway = bankUnit({
  id: "mb-railway-and-gold",
  title: "Railway & Gold Rushes",
  emoji: "🚂",
  blurb: "The Canadian Pacific Railway and the rush for gold.",
  parentNote:
    "Practises the building of the Canadian Pacific Railway, the people who built it, how it changed the West, and what the gold rushes meant for individuals and communities.",
  standards: ["6-KH-030, 6-KH-031", "the gold rushes, and events and issues in the construction of the Canadian Pacific Railway"],
  items: RAILWAY,
});

const WARS_ONE: Q[] = [
  ["The First World War lasted from…", "1914 to 1918", ["1939 to 1945", "1867 to 1870"], "It began in 1914 and ended in 1918."],
  ["When was Remembrance Day first held after the First World War?", "On November 11, the day fighting ended", ["On July 1", "On December 25"], "The fighting stopped on the 11th hour of the 11th day of the 11th month."],
  ["Which flower is a symbol of Remembrance Day?", "the poppy", ["the rose", "the tulip"], "Poppies grew on battlefields."],
  ["Who wrote the poem “In Flanders Fields”?", "John McCrae", ["Louis Riel", "Pauline Johnson"], "McCrae was a Canadian doctor."],
  ["Which battle in 1917 is remembered as a key Canadian victory?", "Vimy Ridge", ["Batoche", "Duck Lake"], "Canadians fought together for the first time there."],
  ["Why were Canadians sent to Europe in 1914?", "Canada was part of the British Empire, which declared war", ["To visit Paris", "To sell wheat"], "Britain's declaration brought Canada in."],
  ["The Canadian Expeditionary Force was…", "the army Canada sent overseas", ["a circus", "a railway company"], "Many young men volunteered."],
  ["Many Indigenous soldiers in the First World War were…", "snipers, scouts and fighters", ["too young to serve", "not allowed to take part at all"], "Indigenous soldiers served with distinction."],
  ["Francis Pegahmagabow was a famous…", "Indigenous sniper in the First World War", ["Prime Minister", "railway worker"], "He was an Ojibwe soldier decorated for bravery."],
  ["Who did the work at home during the war?", "Women worked in factories and farms", ["Nobody", "Only the army"], "Women took on many jobs while men were away."],
  ["In which year did most women in Canada get the right to vote in federal elections?", "1918", ["1867", "1982"], "Many women got the vote in 1918."],
  ["Manitoba was the first province where women could vote and run in provincial elections, in…", "1916", ["1867", "1950"], "Manitoba led the way."],
  ["Which Manitoba woman worked for women's right to vote?", "Nellie McClung", ["Louis Riel", "Terry Fox"], "McClung campaigned for suffrage."],
  ["What does “suffrage” mean?", "the right to vote", ["a type of farm", "a winter storm"], "Women's suffrage was the fight for votes for women."],
  ["Many First Nations women and men could not vote federally until…", "1960", ["1918", "1867"], "Voting rights came later for First Nations people."],
  ["The Winnipeg General Strike happened in…", "1919", ["1885", "1939"], "About 30 000 workers walked off the job."],
  ["Why did workers strike in Winnipeg in 1919?", "For fair wages and the right to bargain together", ["For longer school days", "For a free railway"], "Workers wanted safer jobs and a living wage."],
  ["A strike is when workers…", "stop work to ask for changes", ["go on vacation", "start a new company"], "A strike puts pressure on employers."],
  ["How long did the 1919 Winnipeg General Strike last?", "About six weeks", ["One day", "Three years"], "It ran from May to June 1919."],
  ["Which statement about changing roles for women, 1914 to 1945, is true?", "More women worked in jobs outside the home", ["No woman ever worked", "Women were banned from schools"], "Wartime changed women's work."],
  ["Who was Canada's prime minister during most of the First World War?", "Sir Robert Borden", ["Sir John A. Macdonald", "Pierre Trudeau"], "Borden led from 1911 to 1920."],
  ["Which prime minister led most of the period between the world wars?", "William Lyon Mackenzie King", ["Justin Trudeau", "Alexander Mackenzie"], "Mackenzie King served for many years."],
  ["Why do people wear poppies on Remembrance Day?", "To remember those who served and died", ["To celebrate a birthday", "To show a team colour"], "Wearing a poppy shows respect."],
  ["How can we show respect on Remembrance Day?", "Observe two minutes of silence", ["Play loud music", "Ignore the day"], "Silence at 11 a.m. is a sign of respect.", true],
  ["Why did the First World War start?", "Alliances, rivalry and tension among European countries", ["A hockey game", "A weather event"], "Many causes led to a wide war.", true],
  ["How did the war affect families at home?", "Many lost loved ones, and goods were scarce", ["Nothing changed", "Everyone got rich"], "War brought grief and shortages.", true],
  ["Which source tells you most about a soldier's feelings in the First World War?", "A letter he wrote home", ["A cookbook", "A map of Brazil"], "Primary sources give personal views.", true],
  ["Why is it important to learn that Canadians had different views about the war?", "People did not all agree, and understanding that helps us learn", ["Everyone thought the same", "It does not matter"], "History has many perspectives.", true],
  ["Why were women's votes a major change?", "It gave women a say in laws that affect them", ["It stopped elections", "It ended the war"], "Voting gives people a voice.", true],
  ["The Winnipeg General Strike shows that workers can…", "work together to ask for fair treatment", ["never change anything", "only strike in summer"], "The strike led to debate about labour rights.", true],
];

export const worldWarOne = bankUnit({
  id: "mb-first-world-war-and-1919",
  title: "First World War & Votes for Women",
  emoji: "🌺",
  blurb: "The First World War, the Winnipeg strike and women's right to vote.",
  parentNote:
    "Practises the causes and events of the First World War, Canada's part in it, Remembrance Day, the 1919 Winnipeg General Strike, and the struggle for women's right to vote in Manitoba and Canada.",
  standards: ["6-KC-003, 6-KH-035, 6-KH-036, 6-KH-037, 6-KG-039, 6-KG-040, 6-KP-046", "the First World War, the Winnipeg General Strike, and women's suffrage"],
  items: WARS_ONE,
});

const DEPRESSION: Q[] = [
  ["The Great Depression began in…", "1929", ["1867", "1945"], "The stock market crash in 1929 started it."],
  ["What was the Great Depression?", "A long time of high unemployment and hard times", ["A time of great parties", "A type of weather"], "Many people lost their jobs and savings."],
  ["The 1930s on the Prairies were called the “Dirty Thirties” because of…", "drought and dust storms", ["floods", "volcano eruptions"], "Crops dried up and the wind carried dust."],
  ["Why were farmers hit hard in the Depression?", "Crop prices fell and drought dried up their fields", ["They had too many tractors", "Trains stopped existing"], "Low prices and no rain were a double blow."],
  ["Many people in the 1930s survived by…", "sharing and helping neighbours", ["buying new cars", "moving to the Moon"], "Communities helped each other."],
  ["Relief camps in the 1930s were set up for…", "unemployed men", ["students", "doctors"], "Men worked for little pay."],
  ["Which year did the Second World War begin?", "1939", ["1914", "1918"], "It started in September 1939."],
  ["The Second World War ended in…", "1945", ["1918", "1939"], "Germany surrendered in May and Japan in September."],
  ["On what date did Canadian troops land at Juno Beach in Normandy?", "June 6, 1944", ["November 11, 1918", "July 1, 1867"], "This was D-Day."],
  ["What was Canada's involvement in the Second World War?", "Canada fought alongside its allies in Europe and the Pacific", ["Canada stayed out of the war", "Canada fought against its allies"], "Over a million Canadians served."],
  ["What was a hardship at home during the Second World War?", "Rationing of food and goods", ["Free candy", "Too much gasoline"], "People used coupons for sugar, butter and gas."],
  ["Tommy Prince was a…", "First Nations soldier from Manitoba who received medals", ["prime minister", "railway builder"], "He served in the Second World War and in Korea."],
  ["Which group was unfairly removed from the BC coast and had property taken during the Second World War?", "Japanese Canadians", ["Italian chefs", "Scottish farmers"], "Canada apologized in 1988."],
  ["The government apology to Japanese Canadians was made in…", "1988", ["1939", "1867"], "It acknowledged the wrong."],
  ["What was the Holocaust?", "The Nazi persecution and murder of six million Jewish people and others", ["A sports event", "A type of rainfall"], "Remembering it teaches us to stand against hatred."],
  ["How did new technology change life in the 1920s to 1940s?", "Radios, cars and electricity became common", ["Everyone had satellites", "Nothing changed"], "These inventions changed daily life."],
  ["Which invention let families hear news and music at home in the 1930s?", "radio", ["television", "smartphone"], "Radios were popular in homes."],
  ["Which Canadian invented insulin, helping people with diabetes, in the 1920s?", "Frederick Banting and Charles Best", ["Alexander Graham Bell", "Terry Fox"], "Their work at the University of Toronto saved lives."],
  ["Canada's prime minister for most of the Second World War was…", "William Lyon Mackenzie King", ["Sir John A. Macdonald", "Lester B. Pearson"], "He served from 1935 to 1948, with a break."],
  ["Why do we remember soldiers from the Second World War on Remembrance Day?", "They served and made sacrifices for peace", ["They won sports", "They built houses"], "We honour them with silence and poppies."],
  ["What was the main cause of the Second World War in Europe?", "Aggression by Nazi Germany led by Adolf Hitler", ["A flood", "A sports rivalry"], "Germany's invasions started the war."],
  ["Which statement about the Depression is true?", "Many families had very little money for food and rent", ["Everyone was rich", "No one lost a job"], "It was a hard time for many.", true],
  ["How did families in Manitoba cope in the Dirty Thirties?", "They shared food, patched clothes and helped each other", ["They bought imported goods", "They waited for rain with no change"], "Resourcefulness helped.", true],
  ["The Second World War changed Canada by…", "growing industry and giving women new jobs", ["ending farms", "closing all schools"], "The war changed the economy and society.", true],
  ["Why were Indigenous soldiers important to the war effort?", "They served with courage even when they faced unfair treatment at home", ["They were not involved", "They were paid more"], "Their service was important and sometimes overlooked.", true],
  ["Why do people use the word “sacrifice” about wartime?", "People gave up safety, time and sometimes their lives", ["People gave up pizza", "People gave out prizes"], "Sacrifice means giving something important.", true],
  ["Which source helps you learn how the Depression felt to a child?", "A diary by a child in the 1930s", ["A modern comic", "A list of dates only"], "Primary sources give a personal view.", true],
  ["Which is an opinion about wartime?", "The soldiers were the bravest people in history", ["The war ended in 1945", "The Allies landed in Normandy in 1944"], "Opinions use words like “bravest”.", true],
];

export const depression = bankUnit({
  id: "mb-depression-and-second-world-war",
  title: "Depression & Second World War",
  emoji: "🏵️",
  blurb: "Hard times in the 1930s and Canada in the Second World War.",
  parentNote:
    "Practises the Great Depression and Dirty Thirties on the Prairies, new technology of the time, the causes and events of the Second World War, and Canada's part in it, including Indigenous service and Japanese Canadian internment. Framed factually and kindly.",
  standards: ["6-KE-056, 6-KE-057, 6-KG-041, 6-KG-042, 6-KI-012", "the Great Depression, new technology, and the Second World War and Canada's part in it"],
  items: DEPRESSION,
});

const TODAY: Q[] = [
  ["In what year was the Canadian Charter of Rights and Freedoms signed?", "1982", ["1867", "1945"], "The Charter became part of the Constitution in 1982."],
  ["The Charter protects things like…", "freedom of expression and equality rights", ["the price of milk", "the date of holidays"], "It lists rights and freedoms."],
  ["Which is a right in the Charter?", "Freedom of peaceful assembly", ["Free pizza", "No school"], "People may gather peacefully."],
  ["Canada's two official languages are…", "English and French", ["English and Spanish", "French and Cree"], "The Official Languages Act of 1969 recognized both."],
  ["What is multiculturalism?", "Celebrating and respecting many cultures", ["Having one culture only", "Speaking one language"], "Canada was the first country to adopt a multiculturalism policy, in 1971."],
  ["In 1971 Canada adopted a policy of…", "multiculturalism", ["isolationism", "one-language only"], "It values cultural diversity."],
  ["The United Nations was created in…", "1945", ["1867", "1982"], "It began after the Second World War."],
  ["Lester B. Pearson won the Nobel Peace Prize for…", "ideas that led to UN peacekeeping", ["building a railway", "writing a poem"], "He helped end the Suez Crisis in 1956."],
  ["What do peacekeepers do?", "Help keep peace in places of conflict", ["Fight all wars", "Collect taxes"], "Canada has a long history of peacekeeping."],
  ["Which territory was created in 1999 when Inuit settled a land claim?", "Nunavut", ["Yukon", "Manitoba"], "Nunavut means “our land” in Inuktitut."],
  ["Terry Fox is remembered for…", "his Marathon of Hope to raise money for cancer research", ["inventing the telephone", "winning the Stanley Cup"], "He began his run in 1980."],
  ["Which Canadian organization shares news, music and stories in English and French?", "CBC/Radio-Canada", ["CPR", "RCMP"], "It is Canada's public broadcaster."],
  ["The Canadian flag with its red maple leaf was first raised in…", "1965", ["1867", "1914"], "It first flew on February 15, 1965."],
  ["Which Canadian invented the telephone?", "Alexander Graham Bell", ["Terry Fox", "Frederick Banting"], "Bell patented it in 1876."],
  ["Which Canadian-made invention helps people travel on snow?", "the snowmobile", ["the jet ski", "the helicopter"], "Joseph-Armand Bombardier invented it in Quebec."],
  ["Which is a Canadian invention for travel on water?", "the kayak", ["the gondola", "the junk"], "The Inuit invented the kayak."],
  ["What was the Affaire Forest about?", "The right to use French in Manitoba's courts and laws", ["A hockey rule", "A railway delay"], "Georges Forest challenged a parking ticket in English only."],
  ["The Forest case led to the Supreme Court of Canada saying that Manitoba's 1890 law banning French in laws was…", "unconstitutional", ["Popular", "Fair"], "French language rights were restored."],
  ["The Division scolaire franco-manitobaine (DSFM) is…", "a school division for French-language schools", ["a hockey league", "a railway"], "It was created in 1994."],
  ["Francophone Manitobans have strong communities in…", "Saint-Boniface and other places", ["Only Quebec", "Only Iceland"], "St. Boniface is a francophone heart of Winnipeg."],
  ["Which group has fought for its rights and self-determination in Canada since 1867?", "First Nations, Métis and Inuit", ["Fur companies", "Railway companies"], "Indigenous peoples continue to work for their rights."],
  ["In 2008 the Prime Minister apologized for…", "the residential school system", ["the weather", "the railway"], "It was a national apology."],
  ["September 30 is the…", "National Day for Truth and Reconciliation", ["Canada Day", "Remembrance Day"], "It honours residential school survivors."],
  ["Which of these shows one way Canada helps protect its identity?", "Canadian content rules for radio and television", ["Banning books", "Closing borders"], "Rules support Canadian arts.", true],
  ["Why do we have both English and French signs in many places?", "Both languages are official in Canada", ["Because of cold weather", "By accident"], "Language rights protect both communities.", true],
  ["Why did Canada create bilingual and multicultural policies?", "To respect French-speaking Canadians and newcomers", ["To end trade", "To close schools"], "These policies grew out of Canada's history.", true],
  ["Which statement shows why inequity still matters?", "Some people have fewer chances because of poverty or racism", ["Everyone has the same chances", "Inequity is a kind of fruit"], "We can work to make things fairer.", true],
  ["How can a child help solve inequity?", "Include others and speak up against unfair treatment", ["Ignore it", "Join in the teasing"], "Small actions can make a difference.", true],
  ["Which pair of items shows a Canadian arts expression?", "A Group of Seven painting and a Cree story", ["A tax form and a bill", "A stop sign and a parking meter"], "Arts show who we are.", true],
  ["Which sentence about Canada today is accurate?", "Canada is bilingual, multicultural and spread across a northern land", ["Canada has one language", "Canada has no cities"], "Canada is diverse.", true],
];

export const canadaToday = bankUnit({
  id: "mb-canada-today",
  title: "Canada Since 1945",
  emoji: "🇨🇦",
  blurb: "Rights, languages, peace and identity from 1945 to today.",
  parentNote:
    "Practises Canada since the Second World War: the Charter of Rights and Freedoms, two official languages and multiculturalism, Franco-Manitoban history, Indigenous rights and reconciliation, Canada and the United Nations, and what shapes Canadian identity. Indigenous content needs review with partners.",
  standards: ["6-KC-005, 6-KI-013, 6-KI-013F, 6-KI-014, 6-KI-015F, 6-KI-017, 6-KI-018, 6-KI-019, 6-KG-045, 6-KE-059", "rights and freedoms, bilingual and multicultural policies, Franco-Manitoban history, Indigenous rights, Canada and the UN, and Canadian identity"],
  items: TODAY,
});

const GOVERNMENT: Q[] = [
  ["Canada's three levels of government are…", "municipal, provincial or territorial, and federal", ["school, church and shop", "city, farm and forest"], "Each level has its own responsibilities."],
  ["Canada's federal government meets in…", "Ottawa", ["Winnipeg", "Regina"], "The Parliament Buildings are in Ottawa."],
  ["Manitoba's provincial government meets in…", "Winnipeg", ["Ottawa", "Brandon"], "The Legislative Building is in Winnipeg."],
  ["Who leads the federal government of Canada?", "the Prime Minister", ["the Premier", "the Mayor"], "The prime minister is the head of government."],
  ["Who leads a provincial government?", "the Premier", ["the Prime Minister", "the Mayor"], "Each province has a premier."],
  ["Who leads a city government?", "the Mayor", ["the Premier", "the Governor General"], "The mayor and council run the city."],
  ["What is an MP?", "A Member of Parliament who represents people in Ottawa", ["A mail person", "A police officer"], "MPs are elected to the House of Commons."],
  ["What is an MLA in Manitoba?", "A Member of the Legislative Assembly", ["A mayor's assistant", "A school janitor"], "MLAs sit in the provincial legislature."],
  ["What does a city council do?", "Makes decisions about things like parks, roads and garbage", ["Controls the army", "Prints money"], "Municipal governments handle local services."],
  ["Which level of government is mainly responsible for the army and for money (currency)?", "federal", ["municipal", "school board"], "These are national responsibilities."],
  ["Which level of government is mainly responsible for public schools and health care?", "provincial", ["federal only", "no one"], "Provinces manage education and health."],
  ["Which level of government is mainly responsible for local roads and garbage pick-up?", "municipal", ["federal", "provincial only"], "Cities and towns handle local services."],
  ["Canada is a…", "parliamentary democracy and constitutional monarchy", ["dictatorship", "republic ruled by one family"], "The King is head of state, but elected people make laws."],
  ["In a democracy, who chooses the leaders?", "the people, by voting", ["only one family", "the strongest person"], "Citizens vote in elections."],
  ["How old must a person be to vote in federal elections in Canada?", "18", ["12", "25"], "Citizens who are 18 or older may vote."],
  ["A secret ballot means…", "no one can see how you voted", ["everyone shouts their vote", "votes are posted online"], "It protects your freedom to choose."],
  ["An election is when…", "people vote to choose their representatives", ["the Prime Minister goes on holiday", "a law is written on paper"], "Voting is a way to take part."],
  ["Which two bodies make laws in Parliament?", "the House of Commons and the Senate", ["the court and the army", "the mayor and the police"], "Both study bills."],
  ["Who represents the King in Canada?", "the Governor General", ["the Premier", "the Mayor"], "The Governor General signs bills into law."],
  ["First Nations are governed by…", "a Chief and council", ["a mayor only", "the Prime Minister only"], "Many First Nations elect a Chief and council."],
  ["A First Nation's Chief and council make decisions about…", "community matters such as housing and services", ["the Senate", "the army"], "They serve their community."],
  ["What is a law?", "A rule made by government that everyone must follow", ["A suggestion", "A game"], "Laws keep order and fairness."],
  ["Why should citizens vote?", "To have a say in who makes decisions", ["To get a prize", "To skip school"], "Voting is a right and a way to contribute."],
  ["If you want to share an idea with your MLA, you can…", "write a letter or email", ["send a postcard to the Moon", "wait for no reason"], "Representatives listen to citizens.", true],
  ["What is the job of the opposition in Parliament?", "To question the government and offer other ideas", ["To do nothing", "To lead the army"], "Debate is part of democracy.", true],
  ["Why is it important that governments follow the law too?", "So power is used fairly", ["So they can change it anytime", "So no one has rights"], "The rule of law protects everyone.", true],
  ["What does a federal system mean for Manitobans?", "They have a say in more than one level of government", ["They have no government", "Only one person decides"], "Citizens vote at each level.", true],
  ["Which is a way to take part in democracy without being old enough to vote?", "Joining student council", ["Ignoring issues", "Skipping class"], "Young people can take part in decisions.", true],
  ["Why do we respect authority when it follows democratic ideals?", "Fair leaders help keep everyone safe and free", ["They are always right", "We have no choice"], "Respect depends on fair rules.", true],
  ["Which pair is correctly matched?", "Premier: provincial; Prime Minister: federal", ["Premier: federal; Mayor: provincial", "Prime Minister: municipal; Mayor: federal"], "Match each leader with their level of government.", true],
];

export const government = bankUnit({
  id: "mb-government-and-democracy",
  title: "Government & Democracy",
  emoji: "🗳️",
  blurb: "Three levels of government and how elections work.",
  parentNote:
    "Practises the main features of Canada's government (parliamentary system and federalism), the responsibilities of municipal, provincial, First Nations and federal governments, how elections work, and ways citizens take part in democracy.",
  standards: ["6-KC-004, 6-KP-049, 6-KP-051, 6-KP-052, 6-KP-053, 6-KP-053A", "the features of Canada's government, levels of government, electoral processes and democratic ideals"],
  items: GOVERNMENT,
});
