import { bankUnit, type Q } from "../own";

// Grade 7 mathematics units written for the Manitoba outcomes: divisibility rules (7.N.1), mean, median, mode and range
// with outliers (7.SP.1, 7.SP.2), and expressions, equations and preserving equality (7.PR.3 to 7.PR.7).

const DIVISIBILITY: Q[] = [
  ["Which number is divisible by 2?", "346", ["135", "207", "419"], "Even numbers end in 0, 2, 4, 6 or 8."],
  ["Which number is divisible by 5?", "235", ["232", "237", "239"], "A number is divisible by 5 when it ends in 0 or 5."],
  ["Which number is divisible by 10?", "480", ["485", "408", "84"], "A number is divisible by 10 when it ends in 0."],
  ["A number is divisible by 3 when…", "the sum of its digits is divisible by 3", ["its last digit is 3", "it is an even number", "its digits are all different"], "Add the digits. If that sum is in the 3 times table, so is the number."],
  ["Which number is divisible by 3?", "252", ["251", "254", "256"], "2 + 5 + 2 = 9, and 9 is divisible by 3."],
  ["Which number is divisible by 9?", "738", ["736", "739", "735"], "7 + 3 + 8 = 18, and 18 is divisible by 9."],
  ["Which number is divisible by 4?", "316", ["314", "318", "322"], "A number is divisible by 4 when its last two digits make a number divisible by 4. 16 ÷ 4 = 4."],
  ["Is 524 divisible by 4?", "Yes, because 24 is divisible by 4", ["No, because 5 + 2 + 4 = 11", "No, because it does not end in 0 or 5"], "Check the last two digits: 24 ÷ 4 = 6."],
  ["Which number is divisible by 6?", "144", ["146", "135", "250"], "A number is divisible by 6 when it is divisible by both 2 and 3. 144 is even and 1 + 4 + 4 = 9."],
  ["Why is 231 not divisible by 6?", "It is divisible by 3 but not by 2", ["It is divisible by 2 but not by 3", "It ends in 1, so it is a prime number"], "231 is odd, so 2 does not go into it. A number divisible by 6 needs both 2 and 3."],
  ["Which number is divisible by 8?", "512", ["514", "516", "518"], "Halve it three times: 512, 256, 128, 64. Each half is a whole number."],
  ["Which number is divisible by both 5 and 10?", "360", ["365", "36", "305"], "A number divisible by 10 ends in 0, and then it is divisible by 5 too."],
  ["Which number is NOT divisible by 3?", "428", ["426", "429", "432"], "4 + 2 + 8 = 14, and 14 is not divisible by 3."],
  ["Can you divide 12 by 0?", "No, dividing by 0 has no answer", ["Yes, the answer is 0", "Yes, the answer is 12", "Yes, the answer is 1"], "Division by 0 is not possible."],
  ["Why can 8 ÷ 0 not be answered?", "No number times 0 equals 8", ["Because 0 is an even number", "Because 8 is too small", "Because the answer would be 0"], "Division undoes multiplication. Anything times 0 is 0, never 8."],
  ["What is 0 ÷ 5?", "0", ["5", "1", "It cannot be done"], "Zero shared into 5 equal groups gives 0 in each group."],
  ["There are 180 students. Can they make equal teams of 9?", "Yes, because 1 + 8 + 0 = 9", ["No, because 180 does not end in 9", "No, because 9 is an odd number"], "A number whose digits add to a multiple of 9 is divisible by 9."],
  ["Which digit in the blank makes 57_ divisible by both 2 and 5?", "0", ["5", "2", "7"], "A number divisible by 2 and 5 must end in 0."],
  ["Which number is divisible by 2, 3 and 5?", "270", ["275", "252", "135"], "It must be even, end in 0 or 5, and have digits adding to a multiple of 3. Only 270 does all three."],
  ["Which number is divisible by 2, 4 and 8?", "128", ["124", "122", "126"], "128 ÷ 8 = 16, so it is divisible by 8, and so also by 4 and 2."],
  ["Which number is divisible by 3 but not by 9?", "123", ["126", "135", "128"], "1 + 2 + 3 = 6. 6 is divisible by 3 but not by 9."],
  ["If a number is divisible by 6, it must also be divisible by…", "2 and 3", ["4 and 9", "5 and 10", "2 and 4"], "6 = 2 × 3, so every multiple of 6 is a multiple of 2 and of 3."],
  ["Which number of friends cannot share 72 marbles equally?", "5", ["4", "8", "9"], "72 does not end in 0 or 5, so it is not divisible by 5."],
  ["Which number is divisible by 6 and by 9?", "108", ["96", "60", "45"], "Check 6 (even, digits add to a multiple of 3) and 9 (digits add to a multiple of 9). 1 + 0 + 8 = 9.", true],
  ["Which digit in the blank makes 4_6 divisible by 9?", "8", ["2", "5", "7"], "4 + 6 = 10. The digits must add to 18, so the blank is 8.", true],
  ["Which number is divisible by 10 but not by 4?", "30", ["40", "60", "80"], "40, 60 and 80 are in the 4 times table. 30 ÷ 4 = 7.5.", true],
  ["If a number is divisible by 9, it must also be divisible by…", "3", ["6", "2", "5"], "9 = 3 × 3, so every multiple of 9 is a multiple of 3. It need not be even or end in 0 or 5.", true],
];

export const divisibility = bankUnit({
  id: "mb-divisibility",
  title: "Divisibility Rules",
  emoji: "🧮",
  blurb: "Quick tests for 2, 3, 4, 5, 6, 8, 9 and 10",
  parentNote: "Children use the digits of a number to tell whether it divides evenly, and explain why no number can be divided by 0.",
  standards: ["7.N.1", "divisibility rules for 2, 3, 4, 5, 6, 8, 9 and 10, and why a number cannot be divided by 0"],
  items: DIVISIBILITY,
});

const CENTRAL: Q[] = [
  ["What is the mean of 4, 6, 8 and 10?", "7", ["6", "8", "28"], "Add the numbers (28) and divide by how many there are (4)."],
  ["What is the mean of 12, 15, 9, 20 and 14?", "14", ["12", "15", "70"], "12 + 15 + 9 + 20 + 14 = 70, and 70 ÷ 5 = 14."],
  ["What is the median of 3, 9, 5, 7 and 1?", "5", ["3", "7", "9"], "Put them in order: 1, 3, 5, 7, 9. The median is the middle number."],
  ["What is the median of 2, 4, 6 and 8?", "5", ["4", "6", "20"], "With two middle numbers, 4 and 6, find the number halfway between them."],
  ["What is the median of 10, 3, 7, 12, 8 and 6?", "7.5", ["7", "8", "6"], "In order: 3, 6, 7, 8, 10, 12. The middle two are 7 and 8, so the median is 7.5."],
  ["What is the mode of 4, 7, 7, 9, 4, 7?", "7", ["4", "9", "6.3"], "The mode is the value that appears most often. 7 appears three times."],
  ["What is the mode of 2, 3, 3, 5, 5, 8?", "3 and 5", ["3", "5", "8"], "Both 3 and 5 appear twice, more than any other value."],
  ["What is the range of 12, 5, 21 and 8?", "16", ["13", "21", "8"], "Range = greatest − least = 21 − 5."],
  ["The range of a data set tells you…", "how spread out the data are", ["the most common value", "the middle value", "the average value"], "Range is the difference between the greatest and least values."],
  ["A data set has no mode when…", "every value appears the same number of times", ["all the numbers are even", "the mean is a whole number", "there are fewer than five values"], "If no value appears more often than the others, there is no mode."],
  ["Scores: 8, 9, 7, 8, 9, 40. Which score is the outlier?", "40", ["7", "8", "9"], "An outlier is far away from the rest of the data."],
  ["Marks of 4, 5, 6 and 5 have a mean of 5. A mark of 25 is added. What is the new mean?", "9", ["5", "10", "45"], "4 + 5 + 6 + 5 + 25 = 45, and 45 ÷ 5 = 9."],
  ["Which measure is least affected by an outlier?", "median", ["mean", "range", "total"], "One very high or low value pulls the mean and the range, but the middle value barely moves."],
  ["A few houses sell for millions of dollars. Which measure best describes a typical price?", "median", ["mean", "range", "the highest price"], "The median is not pulled up by a few very high prices."],
  ["The mean of 5 numbers is 8. What is their sum?", "40", ["13", "8", "45"], "Mean × number of values = sum, so 8 × 5."],
  ["Which set of numbers has a mean of 6?", "2, 6, 10", ["1, 2, 3", "5, 6, 8", "2, 4, 9"], "2 + 6 + 10 = 18, and 18 ÷ 3 = 6."],
  ["Which measure can describe favourite colours in a survey?", "mode", ["mean", "median", "range"], "Colours are not numbers, so only the most common answer can be named."],
  ["Winnipeg daily lows (°C): −8, −3, −5, −10, −4. What is the median?", "−5", ["−4", "−6", "−3"], "In order: −10, −8, −5, −4, −3. The middle value is −5."],
  ["Winnipeg daily lows (°C): −8, −3, −5, −10, −4. What is the mean?", "−6", ["−5", "−30", "−7"], "The sum is −30, and −30 ÷ 5 = −6."],
  ["Winnipeg daily lows (°C): −8, −3, −5, −10, −4. What is the range?", "7", ["13", "−13", "−7"], "Greatest minus least: −3 − (−10) = −3 + 10 = 7.", true],
  ["What is the median of 12, 18, 14 and 20?", "16", ["14", "18", "17"], "In order: 12, 14, 18, 20. The middle two are 14 and 18, halfway between is 16."],
  ["What is the mean of 1.5, 2.5 and 3.5?", "2.5", ["3", "7.5", "1.5"], "The sum is 7.5, and 7.5 ÷ 3 = 2.5."],
  ["Test scores are 70, 80, 90 and 80. The next score is needed to make the mean of 5 scores 82. What is it?", "90", ["82", "80", "100"], "The total must be 5 × 82 = 410. The first four add to 320, and 410 − 320 = 90.", true],
  ["The data 6, 7, 7, 8, 9, 9, 10 is joined by an outlier of 30. What happens to the mode?", "It is still 7 and 9", ["It becomes 30", "It becomes 10", "It becomes 8"], "30 appears only once, so it does not change the most common values.", true],
  ["Five numbers have a mean of 10. One number, 20, is removed. What is the mean of the other four?", "7.5", ["10", "5", "8"], "The sum was 50. Now it is 30, and 30 ÷ 4 = 7.5.", true],
  ["Someone says the mean of 2, 3, 4 and 91 is “about 3”. What is wrong?", "The mean is 25, pulled up by the outlier 91", ["The mean is 4, because it is the middle", "The mean is 91, the greatest value"], "2 + 3 + 4 + 91 = 100, and 100 ÷ 4 = 25.", true],
];

export const centralTendency = bankUnit({
  id: "mb-mean-median-mode",
  title: "Mean, Median & Mode",
  emoji: "📊",
  blurb: "Typical values, spread and outliers",
  parentNote: "Children find the mean, median, mode and range of a data set and see how one unusual value, an outlier, changes them.",
  standards: ["7.SP.1, 7.SP.2", "mean, median, mode and range, and the effect of an outlier on them"],
  items: CENTRAL,
});

const EXPRESSIONS: Q[] = [
  ["Which is an equation?", "x + 4 = 9", ["x + 4", "3y − 2", "5a"], "An equation has an equal sign. It says two things have the same value."],
  ["Which is an expression?", "3n + 2", ["3n + 2 = 11", "n = 5", "4 + 1 = 5"], "An expression has no equal sign. It is a number phrase, like 3n + 2."],
  ["How are x + 3 and x + 3 = 10 different?", "The first is an expression; the second is an equation", ["The first is an equation; the second is an expression", "The first has a variable; the second does not"], "Only the second has an equal sign, so it can be solved."],
  ["In 5n + 8, which part is the variable?", "n", ["5", "8", "+"], "A variable is a letter that stands for a number."],
  ["In 5n + 8, which part is the constant?", "8", ["5", "n", "5n"], "The constant is the term that does not change, because it has no variable."],
  ["What is the value of 3n + 2 when n = 4?", "14", ["9", "20", "24"], "3 × 4 + 2 = 12 + 2."],
  ["What is the value of 5x − 7 when x = 3?", "8", ["12", "−1", "15"], "5 × 3 − 7 = 15 − 7."],
  ["What is the value of 2(a + 3) when a = 5?", "16", ["13", "11", "10"], "Do the brackets first: 5 + 3 = 8. Then 2 × 8."],
  ["What is the value of 20 − 2m when m = 6?", "8", ["108", "12", "32"], "2 × 6 = 12, and 20 − 12 = 8."],
  ["What is the value of 4a + 3b when a = 2 and b = 5?", "23", ["14", "26", "17"], "4 × 2 + 3 × 5 = 8 + 15."],
  ["What is the value of 2x + 1 when x = −3?", "−5", ["−7", "7", "−2"], "2 × (−3) + 1 = −6 + 1."],
  ["Solve: x + 7 = 15", "x = 8", ["x = 22", "x = 7", "x = 15"], "Subtract 7 from both sides: 15 − 7."],
  ["Solve: n − 6 = 9", "n = 15", ["n = 3", "n = 54", "n = 9"], "Add 6 to both sides: 9 + 6."],
  ["Solve: x + 12 = 5", "x = −7", ["x = 7", "x = 17", "x = −17"], "Subtract 12 from both sides: 5 − 12 = −7."],
  ["Solve: n − 4 = −2", "n = 2", ["n = −6", "n = −2", "n = 6"], "Add 4 to both sides: −2 + 4 = 2."],
  ["To solve x + 5 = 12, what do you do to both sides?", "Subtract 5", ["Add 5", "Subtract 12", "Multiply by 5"], "Subtracting 5 undoes adding 5. Do the same to both sides to keep the balance."],
  ["To solve 3x = 18, what do you do to both sides?", "Divide by 3", ["Subtract 3", "Multiply by 3", "Add 3"], "Dividing by 3 undoes multiplying by 3."],
  ["Solve: 4x = 28", "x = 7", ["x = 24", "x = 32", "x = 112"], "Divide both sides by 4."],
  ["A scale is level with x + 3 on one side and 10 on the other. If 3 is taken from both sides, what is left?", "x = 7", ["x = 13", "x = 3", "x = 10"], "Taking the same amount off both sides keeps it level: x on one side, 7 on the other."],
  ["Which step keeps x + 4 = 9 balanced?", "Subtract 4 from both sides", ["Subtract 4 from one side only", "Add 4 to the left side only", "Multiply the left side by 4"], "Whatever you do to one side, do to the other."],
  ["Mika has x stickers. After getting 6 more she has 15. Which equation matches?", "x + 6 = 15", ["x − 6 = 15", "6x = 15", "x + 15 = 6"], "Start with x, add 6, and the result is 15."],
  ["A taxi costs $4 plus $3 per kilometre. Which expression gives the cost for k kilometres?", "4 + 3k", ["3 + 4k", "7k", "4k + 3"], "A fixed $4, plus $3 for each of the k kilometres."],
  ["Solve: 2x + 3 = 11", "x = 4", ["x = 7", "x = 14", "x = 8"], "Subtract 3 to get 2x = 8, then divide by 2."],
  ["Solve: 5x + 2 = 27", "x = 5", ["x = 6", "x = 29", "x = 25"], "Subtract 2 to get 5x = 25, then divide by 5."],
  ["Solve: x ÷ 5 = 3", "x = 15", ["x = 8", "x = 0.6", "x = 2"], "Multiply both sides by 5 to undo dividing by 5."],
  ["What is the value of 10 − n when n = −4?", "14", ["6", "−6", "−14"], "10 − (−4) = 10 + 4.", true],
  ["Solve: 3x − 4 = 14", "x = 6", ["x = 10", "x = 30", "x = 3.3"], "Add 4 to get 3x = 18, then divide by 3.", true],
  ["Solve: x ÷ 4 + 2 = 6", "x = 16", ["x = 32", "x = 8", "x = 1"], "Subtract 2 to get x ÷ 4 = 4, then multiply by 4.", true],
];

export const expressionsEquations = bankUnit({
  id: "mb-expressions-equations",
  title: "Expressions & Equations",
  emoji: "⚖️",
  blurb: "Evaluate, balance and solve",
  parentNote: "Children tell an expression from an equation, evaluate expressions, and solve equations by doing the same thing to both sides.",
  standards: ["7.PR.3, 7.PR.4, 7.PR.5, 7.PR.6, 7.PR.7", "expressions and equations, evaluating, preserving equality, and solving linear equations"],
  items: EXPRESSIONS,
});
