import { bankUnit, type Q } from "../own";

// More Grade 7 science (Manitoba): how science works (hypotheses, bias, models), technology and its consequences,
// measurement and safe lab practice, science in everyday life and Indigenous ways of knowing, and energy and melting points.

const INQUIRY: Q[] = [
  ["A hypothesis is…", "a testable prediction about what will happen and why", ["a proven fact", "a type of graph", "a list of materials"], "A hypothesis can be tested with an experiment."],
  ["Which is a testable hypothesis?", "If plants get more light, they will grow taller.", ["Plants are pretty.", "Light is nice.", "I like green."], "A testable hypothesis names something you can change and measure."],
  ["In a fair test, the variable you change on purpose is the…", "independent (manipulated) variable", ["dependent variable", "control group only", "conclusion"], "You change one thing at a time."],
  ["The variable you measure to see the effect is the…", "dependent (responding) variable", ["independent variable", "hypothesis", "title"], "It depends on what you changed."],
  ["A student tests how the amount of water affects how fast bean seeds sprout. The independent variable is…", "the amount of water", ["the number of days to sprout", "the type of seed", "the colour of the pot"], "It is the thing the student changes."],
  ["In that same experiment, the dependent variable is…", "how fast the seeds sprout", ["the amount of water", "the room", "the pot size"], "It is what is measured."],
  ["Variables that must stay the same in a fair test are called…", "controlled variables", ["hypotheses", "results", "opinions"], "Keeping them the same makes the test fair."],
  ["Which is a controlled variable in the bean experiment?", "the amount of light each pot gets", ["the amount of water", "the time to sprout", "the conclusion"], "Only the water amount should change."],
  ["Why do scientists change only one variable at a time?", "So they know what caused the change", ["To save paper", "To make it harder", "To avoid measuring"], "More than one change would make results confusing."],
  ["An experiment is…", "a fair test used to check a prediction", ["a guess with no testing", "a story", "a poster"], "Experiments collect evidence."],
  ["Why do scientists repeat an experiment several times?", "To make sure the results can be trusted", ["To use up supplies", "Because the first try is always wrong", "To make the data harder to read"], "Repeated trials show patterns and reduce chance errors."],
  ["Empirical data is…", "information gathered by observing or measuring", ["a guess", "an opinion", "a rumour"], "Empirical means based on evidence from observation."],
  ["Which is quantitative data?", "The plant grew 8 cm.", ["The plant looks happy.", "The plant is pretty.", "I love the plant."], "Quantitative data uses numbers."],
  ["Which is qualitative data?", "The liquid turned blue.", ["It was 25 °C.", "It had a mass of 12 g.", "It took 30 s."], "Qualitative data describes without numbers."],
  ["Peer review is…", "when other experts check a scientist’s work before it is accepted", ["a classmate copying your results", "a popularity vote", "a kind of experiment"], "Other scientists look for errors and weak reasoning."],
  ["Why is peer review useful?", "It helps find mistakes and bias", ["It makes experiments longer", "It removes all data", "It makes results secret"], "Reviewers catch problems the first scientist missed."],
  ["Bias in science means…", "a leaning that can unfairly affect results or conclusions", ["a type of measurement", "a safe lab rule", "a unit"], "Scientists try to reduce bias."],
  ["A company that makes a vitamin pays for a study that only reports good results. This is an example of…", "bias", ["a controlled variable", "a fair test", "peer review"], "Leaving out some results is unfair."],
  ["A scientist only records the results that match her hypothesis. This is…", "confirmation bias", ["a controlled variable", "a unit conversion", "a safe procedure"], "Ignoring results that disagree is a bias."],
  ["Which helps reduce bias?", "Record all results, including surprising ones", ["Throw out results you dislike", "Test once", "Change the data"], "Honest records reduce bias."],
  ["A sample size that is very small can lead to…", "unreliable conclusions", ["perfect certainty", "faster results", "stronger evidence"], "Larger samples show patterns better.", true],
  ["When an experiment does not support your hypothesis, you should…", "report what happened and revise your thinking", ["hide the results", "change the data", "stop science forever"], "Unexpected results are part of learning.", true],
  ["Scientific explanations are those that…", "best fit the evidence available at a particular time", ["can never change", "are the most popular", "are the shortest"], "New evidence can change explanations."],
  ["Why can scientific explanations change over time?", "New evidence and better tools can show new things", ["Scientists lose interest", "Facts change by themselves", "Experiments are optional"], "Science is open to revision."],
  ["Which question can science test?", "Does road salt melt ice faster than sand?", ["Which colour is the prettiest?", "Is summer better than winter?", "Who is the nicest teacher?"], "Science tests questions that can be observed and measured."],
  ["Which is an observation?", "The ice cube melted in 12 minutes.", ["Ice cubes are boring.", "Ice should be warm.", "Melting is the best."], "An observation is what you see or measure."],
  ["Which is an inference?", "The ice melted faster because the room was warm.", ["The ice cube weighed 20 g.", "The ice cube was clear.", "The ice melted in 12 minutes."], "An inference is an explanation based on observations."],
  ["A line graph is best for showing…", "how something changes over time", ["a list of names", "the parts of a whole only", "a story"], "Time is on the horizontal axis.", true],
  ["A class compares results from different groups. One group got a very different number. The best next step is to…", "check for errors in how that group measured", ["throw the data away without looking", "ignore all other groups", "average the numbers without thought"], "Look for the cause before deciding.", true],
];

export const scientificInquiry = bankUnit({
  id: "mb-7-scientific-inquiry",
  title: "Fair Tests & Bias",
  emoji: "🧪",
  blurb: "Hypotheses, variables, evidence and peer review",
  parentNote: "Children practise how scientists test predictions: writing a hypothesis, controlling variables, collecting data honestly and spotting bias.",
  standards: ["SCI.7.C.3, SCI.7.D.1, SCI.7.D.2", "scientific practices, collecting data and reducing bias, and hypotheses, experiments and variables"],
  items: INQUIRY,
});

const MODELS: Q[] = [
  ["A scientific model is…", "a representation used to help explain something", ["a fashion model", "a final answer that never changes", "a list of facts"], "Models help us picture ideas that are too big, small or complex to see directly."],
  ["Which is a physical model?", "a plastic model of the Solar System", ["a recipe", "a poem", "a bar graph"], "You can touch it."],
  ["Which is a mathematical model?", "an equation that predicts how far a car travels", ["a clay figure", "a drawing of a tree", "a puppet"], "It uses math to represent a relationship."],
  ["Which is a simulation?", "a computer program that shows how planets move", ["a bar of soap", "a ruler", "a jar of water"], "A simulation imitates a real process."],
  ["Why do scientists use models of atoms and particles?", "The particles are too small to see directly", ["Atoms are huge", "Models are always exact", "Atoms do not exist"], "A model helps us picture the invisible."],
  ["A globe is a model of…", "Earth", ["the Sun", "an atom", "a cell"], "A globe shows Earth’s shape and features at a smaller size."],
  ["A model of the Solar System shows the planets as small balls. What is one limitation?", "The distances and sizes are not to scale", ["It shows the Sun", "It has planets", "It has colours"], "Every model has limits."],
  ["Models are described as metaphorical representations because they…", "stand for something else to help us understand", ["are always made of wood", "are exact copies", "cannot be changed"], "A model is like the real thing in some ways."],
  ["A well-established model has…", "a lot of evidence from many tests supporting it", ["no evidence", "only one test", "no scientists using it"], "Evidence builds trust."],
  ["Which model is well established?", "the Solar System with planets orbiting the Sun", ["a model with the Sun orbiting Earth", "a model with a flat Earth", "a model with no Sun"], "It is supported by centuries of observations."],
  ["Some models, such as models of black holes, are described as tentative because…", "scientists are still gathering evidence about them", ["they are false", "nobody has studied them", "they are too old"], "Tentative means not yet fully confirmed."],
  ["What happens to a model when new evidence does not fit it?", "Scientists may improve or replace it", ["It is kept unchanged", "It is ignored forever", "It becomes a fact"], "Models change with evidence."],
  ["A model of a river created with sand and water in a tray helps students learn about…", "erosion", ["photosynthesis", "magnets", "eclipses"], "It shows how water shapes land."],
  ["A flowchart or diagram of how water moves through the water cycle is a…", "conceptual model", ["recipe", "unit conversion", "biography"], "It shows relationships between ideas."],
  ["Why might scientists compare the results of a model with real data?", "To check how well the model works", ["To ignore either", "To make the model bigger", "To avoid measuring"], "Testing a model against evidence shows its strengths and limits."],
  ["Which of these is NOT a good reason to use a model?", "It is always completely identical to the real thing", ["It is safe", "It is smaller or simpler", "It lets us see what we cannot see"], "Models are simplified, not identical."],
  ["A weather forecast uses a computer model. Why may the forecast be wrong sometimes?", "The model uses limited data and simplified rules", ["Weather has no rules", "The computer is broken every time", "Scientists guess randomly"], "Models give best estimates, not certainty.", true],
  ["Knowledge from science is used in engineering when…", "engineers use scientific ideas to design solutions", ["scientists build homes without ideas", "engineers ignore science", "nobody applies science"], "Science informs design.", true],
  ["An engineer builds a small model of a bridge to test it. This is helpful because…", "problems can be found before building the real bridge", ["bridges never fail", "models are the real bridge", "testing is unnecessary"], "Testing models saves time, money and risk.", true],
  ["Which statement about the particle model of matter is correct?", "It explains why solids, liquids and gases behave differently", ["It shows exact photographs of atoms", "It is not based on evidence", "It is only about plants"], "Models explain observations."],
  ["Scientists often improve a model by…", "adding new evidence and testing again", ["ignoring new evidence", "removing all details", "keeping it secret"], "Revising models is normal."],
  ["Which model would best show the parts of a plant cell?", "a labelled diagram", ["a clock", "a map of Manitoba", "a timetable"], "Diagrams label parts."],
  ["A map is a model because it…", "represents a real place in a simpler form", ["is the real place", "is always to scale in every detail", "has no limits"], "Maps simplify landscapes."],
  ["A class makes a model of the Moon’s phases with a lamp and a ball. The lamp represents the…", "Sun", ["Moon", "Earth", "a star far away"], "The lamp supplies light like the Sun."],
  ["In that same model, the ball represents the…", "Moon", ["Sun", "Earth’s core", "a comet"], "The ball is lit by the lamp like the Moon is lit by the Sun."],
  ["A limitation of the lamp-and-ball model of the Moon’s phases is that…", "the sizes and distances are much smaller than real ones", ["it uses light", "it shows phases", "it has a ball"], "A model cannot show everything about the real thing."],
  ["Which is an example of science knowledge being used by engineers?", "using what we know about materials to design a stronger bicycle frame", ["picking a bike colour", "naming a bike", "buying a bike helmet"], "Engineers apply science to solve problems.", true],
  ["Scientists propose a new model that explains more observations than the old one. What usually happens?", "The new model is tested and may replace the old one", ["The old one is erased from history", "Nothing changes", "Scientists stop testing"], "Models that fit the evidence best are accepted.", true],
];

export const scientificModels = bankUnit({
  id: "mb-7-scientific-models",
  title: "Science Models",
  emoji: "🧩",
  blurb: "How models help us picture and test ideas",
  parentNote: "Children learn that models represent ideas to help explain the world, that some models are well established and others tentative, and that models can change with new evidence.",
  standards: ["SCI.7.D.3, SCI.7.D.4", "physical, mathematical and simulation models, and well-established and tentative models"],
  items: MODELS,
});

const TECH: Q[] = [
  ["Technology is…", "the use of tools and knowledge to solve problems", ["only computers", "only old machines", "only toys"], "Technology includes tools from a hammer to a satellite."],
  ["When designing a solution, which is a factor to consider?", "available materials", ["the weather on Mars", "a favourite colour only", "none"], "Materials, cost, safety and effects all matter."],
  ["Which factor is about people’s well-being?", "effects on humans and other animals", ["colour of the plans", "title of the project", "the number of drawings"], "A good solution considers who is affected."],
  ["Which factor is about costs?", "How much will it cost to build and use?", ["How long is the name?", "What is the font?", "How many pages?"], "Budget is part of design."],
  ["Which factor looks at the environment?", "Will it harm air, water or wildlife?", ["Is it a popular idea?", "Can it be photographed?", "Is it nice?"], "Environmental effects are part of design."],
  ["An engineer tests several ideas for a new lunch container. This shows…", "trying a variety of strategies before choosing a solution", ["giving up", "copying a single idea", "ignoring the problem"], "Solutions often take several tries."],
  ["Which strategy can help you test a design before you build it?", "making a drawing or model", ["guessing", "skipping the test", "asking nobody"], "Drawings, models and simulations help."],
  ["A computer simulation of a bridge under heavy traffic helps engineers…", "find weak points without building it", ["avoid math", "skip safety", "draw a map"], "Simulations test designs safely."],
  ["A prototype is…", "a first test version of a design", ["a final product", "a spelling word", "a type of battery"], "Prototypes are tested and improved."],
  ["After a prototype fails a test, the best step is to…", "learn from it and improve the design", ["hide the failure", "give up", "sell it as is"], "Failure gives information."],
  ["Antibiotics help cure infections. A negative consequence of using them too often is…", "bacteria can become resistant", ["bacteria disappear forever", "people become taller", "water boils faster"], "Overuse can lead to antibiotic resistance."],
  ["Plastic is cheap and convenient. A negative consequence is…", "plastic waste can pollute the environment", ["it is too heavy", "it always rots quickly", "it cannot be made"], "Plastics last a long time in nature."],
  ["Cars and trucks help people travel. One negative consequence is…", "greenhouse gas emissions", ["quieter streets always", "fewer roads", "cleaner air always"], "Burning fuels releases gases."],
  ["Digital communication helps people connect. One drawback is…", "misinformation can spread quickly", ["it works without power", "it has no cost", "it cannot reach far"], "Not everything shared online is true."],
  ["Old phones and computers that are thrown away can cause…", "electronic waste (e-waste)", ["more clean water", "faster Wi-Fi", "less pollution"], "E-waste can contain harmful materials."],
  ["Wind turbines make clean electricity. One impact to study is…", "effects on birds and bats", ["effects on the Moon", "effects on glaciers on Mars", "none"], "Even renewable energy has impacts."],
  ["Solar farms use large areas of land. This is an example of…", "a land-use impact of a renewable energy technology", ["a cost-free technology", "an old technology", "a pollution-free technology with no impact"], "Every technology has trade-offs."],
  ["Pumping groundwater helps farms get water. A possible unforeseen problem is…", "the aquifer can be used up faster than it refills", ["water becomes lighter", "wells become taller", "rivers freeze"], "Overuse can deplete an aquifer."],
  ["Farm technologies can help produce more food. A possible downside is…", "loss of biodiversity", ["no food", "smaller farms always", "fewer crops always"], "Using a few crops over huge areas can reduce variety."],
  ["Manufacturing makes goods affordable. A possible downside is…", "pollution from factories", ["higher prices always", "no jobs", "shorter days"], "Trade-offs are common."],
  ["A predictable consequence is one that…", "people can see coming", ["nobody could guess", "never happens", "happens only on Mondays"], "Some effects are expected."],
  ["An unforeseen consequence is one that…", "nobody expected when the technology was designed", ["was planned", "was written on the label", "is always good"], "Some effects appear only after years of use."],
  ["Once scientists learn that a technology harms the environment, a community should…", "evaluate whether to keep, change or replace it", ["ignore the information", "hide it", "keep using it exactly the same"], "Decisions can be revisited with new evidence.", true],
  ["Many communities moved away from lead paint and leaded gasoline after learning about health effects. This shows…", "technologies can be replaced when new information appears", ["technologies never change", "science is never used", "all technology is harmless"], "Societies adjust their choices.", true],
  ["A school removes single-use plastic bottles after a waste audit. This is an example of…", "redesigning how a technology is used", ["ignoring evidence", "adding more waste", "avoiding data"], "The community acted on what it learned.", true],
  ["Which would be a good way for a community to evaluate a new technology?", "weigh benefits and risks using reliable evidence", ["choose by popularity only", "ignore costs", "listen to one opinion only"], "Fair evaluation uses evidence and many views.", true],
  ["Manitoba generates much of its electricity from…", "hydroelectric dams", ["coal mines only", "tidal power", "volcanoes"], "Hydro dams on northern rivers supply most of the province’s power."],
  ["Hydroelectric dams provide clean electricity. One impact to evaluate is…", "flooding of land and changes to river ecosystems", ["lower prices of lumber", "more snow in July", "longer days"], "Even clean energy changes the environment."],
  ["A landfill that leaks can harm water quality. A technology that helps prevent this is…", "a liner and a collection system for leachate", ["a bigger pile", "burying garbage without any rules", "pouring it in a river"], "Better waste technology protects water.", true],
];

export const technologyChoices = bankUnit({
  id: "mb-7-technology-choices",
  title: "Technology & Trade-offs",
  emoji: "⚙️",
  blurb: "Design factors, benefits, risks and rethinking tech",
  parentNote: "Children think about what makes a good design, why technologies have benefits and drawbacks, and how communities can change a technology when they learn more.",
  standards: ["SCI.7.D.5, SCI.7.D.6, SCI.7.D.7, SCI.7.D.8", "design factors, trying strategies, predictable and unforeseen consequences, and reconsidering technologies"],
  items: TECH,
});

const MEASURE: Q[] = [
  ["Which tool measures temperature?", "thermometer", ["spring scale", "pan balance", "compass"], "Temperature is read in degrees Celsius (°C)."],
  ["Which tool measures mass?", "pan balance", ["thermometer", "ruler", "clock"], "A balance compares masses."],
  ["Which unit is used for mass?", "grams", ["litres", "metres", "newtons"], "Mass is measured in grams or kilograms."],
  ["Which tool measures force?", "spring scale", ["thermometer", "ruler", "graduated cylinder"], "A spring scale reads force in newtons."],
  ["The unit of force is the…", "newton (N)", ["joule (J)", "gram (g)", "litre (L)"], "N stands for newton."],
  ["The unit of energy is the…", "joule (J)", ["newton (N)", "litre (L)", "kilogram (kg)"], "J stands for joule."],
  ["Which tool measures the volume of a liquid?", "graduated cylinder", ["compass", "pan balance", "thermometer"], "Volumetric vessels such as cylinders measure volume."],
  ["Which unit is used for the volume of a liquid?", "millilitres (mL)", ["metres (m)", "kilograms (kg)", "seconds (s)"], "mL and L measure volume."],
  ["Which tool shows direction?", "compass", ["ruler", "thermometer", "stopwatch"], "A compass points to magnetic north and helps find directions."],
  ["An astrolabe was traditionally used to measure…", "the angle of a star or the Sun above the horizon", ["temperature", "mass", "time of a storm"], "Altitude is measured in degrees."],
  ["Which unit measures altitude angle?", "degrees", ["litres", "grams", "joules"], "Altitude here means the angle above the horizon."],
  ["Which unit measures the speed of a car on a highway?", "km/h", ["mL", "kg", "J"], "Kilometres per hour."],
  ["Speed in metres per second is written…", "m/s", ["mL/s", "kg/s", "N/s"], "Distance over time."],
  ["How many metres are in 1 kilometre?", "1000", ["10", "100", "10 000"], "Kilo means one thousand."],
  ["How many millimetres are in 1 centimetre?", "10", ["100", "1000", "1"], "Milli means one thousandth, centi means one hundredth."],
  ["How many centimetres are in 1 metre?", "100", ["10", "1000", "60"], "Centi means one hundredth."],
  ["How many millilitres are in 1 litre?", "1000", ["10", "100", "10 000"], "Milli means one thousandth."],
  ["How many grams are in 1 kilogram?", "1000", ["10", "100", "10 000"], "Kilo means one thousand."],
  ["How many minutes are in 2 hours?", "120", ["60", "100", "200"], "2 × 60 = 120."],
  ["2.5 kilometres is the same as…", "2500 m", ["25 m", "250 m", "25 000 m"], "2.5 × 1000."],
  ["350 centimetres is the same as…", "3.5 m", ["35 m", "0.35 m", "350 m"], "Divide by 100."],
  ["4.2 litres is the same as…", "4200 mL", ["420 mL", "42 mL", "42 000 mL"], "Multiply by 1000."],
  ["The SI prefix “milli” means…", "one thousandth", ["one thousand", "one hundred", "one tenth"], "A millimetre is one thousandth of a metre."],
  ["The SI prefix “kilo” means…", "one thousand", ["one thousandth", "one hundred", "ten"], "A kilogram is 1000 grams."],
  ["The SI prefix “centi” means…", "one hundredth", ["one hundred", "one tenth", "one thousand"], "A centimetre is one hundredth of a metre."],
  ["The SI prefix “deci” means…", "one tenth", ["one hundredth", "ten", "one thousand"], "A decimetre is one tenth of a metre.", true],
  ["The SI prefix “mega” means…", "one million", ["one thousand", "one billion", "one hundred"], "A megajoule is one million joules.", true],
  ["The SI prefix “hecto” means…", "one hundred", ["one thousand", "ten", "one tenth"], "A hectare is a hundred ares.", true],
  ["The symbol “µ” stands for the prefix…", "micro (one millionth)", ["milli (one thousandth)", "mega (one million)", "kilo (one thousand)"], "Micro is the smallest of these.", true],
  ["Why do scientists use standard SI units?", "So everyone around the world can compare measurements", ["Because they look nice", "To make work harder", "To measure only in Canada"], "Standard units mean the same thing everywhere."],
  ["Which tool is best for measuring the length of a pencil?", "ruler", ["thermometer", "spring scale", "stopwatch"], "Use the right tool for the attribute."],
  ["Which tool is best for measuring how long a ball rolls?", "a stopwatch or clock", ["a ruler", "a spring scale", "a compass"], "Time is measured with clocks."],
  ["To measure time on a stopwatch, the unit is usually…", "seconds", ["metres", "grams", "degrees"], "Seconds (s) are the SI unit of time."],
  ["Which graph best displays how temperature changes over an afternoon?", "a line graph", ["a map", "a list of words", "a circle graph of one value"], "Line graphs show change over time.", true],
  ["Which would be a good estimate for the mass of a school lunch?", "about 500 g", ["about 500 kg", "about 5 g", "about 50 kg"], "A lunch is lighter than a kilogram or two.", true],
  ["A temperature of 20 °C is best described as…", "a comfortable room temperature", ["freezing", "boiling", "very hot oven"], "Water freezes at 0 °C and boils at 100 °C."],
  ["Which is a good estimate for the height of a school door?", "about 2 m", ["about 2 cm", "about 2 km", "about 2 mm"], "A door is a bit taller than a person.", true],
];

export const measurementTools = bankUnit({
  id: "mb-7-measurement-tools",
  title: "Tools & Metric Units",
  emoji: "📏",
  blurb: "Pick the right tool and convert metric units",
  parentNote: "Children practise matching measurement tools to what they measure, using SI units and prefixes, converting between metric units and estimating.",
  standards: ["SCI.7.C.2", "measurement tools, SI units and prefixes, converting and estimating"],
  items: MEASURE,
});

const SAFETY: Q[] = [
  ["Before a lab starts, the first thing you should do is…", "listen to and follow safety instructions", ["start right away", "taste the materials", "rush through"], "Safety comes first."],
  ["When heating something with a hot plate, you should…", "wear safety goggles and keep long hair tied back", ["lean over the hot plate", "touch it to test", "leave it unattended"], "Protect your eyes and avoid burns."],
  ["Why should you wear safety goggles in a lab?", "To protect your eyes from splashes and flying bits", ["To look cool", "To see better in the dark", "To block sound"], "Goggles protect your eyes."],
  ["If glassware breaks, you should…", "tell your teacher and do not touch the pieces", ["pick it up with bare hands", "hide it", "sweep it into your pocket"], "Tell an adult."],
  ["Which is unsafe in a science lab?", "tasting chemicals", ["washing hands afterward", "reading labels", "tying back long hair"], "Never taste anything in the lab."],
  ["Chemical substances should be handled by…", "following instructions and reading labels", ["guessing", "mixing at random", "smelling directly from the bottle"], "Labels give hazard information."],
  ["To check the smell of a chemical safely, you should…", "waft the air toward you with your hand if your teacher says it is safe", ["put your nose in the container", "sniff deeply", "taste it"], "Waft gently."],
  ["Before you use a telescope or binoculars, remember never to…", "look at the Sun with them", ["clean the lens", "carry them with a strap", "put them in a case"], "Looking at the Sun through them can seriously damage eyes."],
  ["A logbook is used to…", "record observations and data as you work", ["store snacks", "hide results", "list friends"], "Scientists write their observations."],
  ["It is good practice to record data in a logbook…", "at the time you observe it, using the correct units", ["from memory next week", "only if the result is surprising", "without units"], "Immediate, accurate records."],
  ["A spreadsheet can help scientists…", "organize data and make graphs", ["cook", "play music only", "print photographs only"], "Spreadsheets store and display numbers."],
  ["Which would be a safe use of recycled materials in a design project?", "washed and checked containers", ["broken glass", "used needles", "unknown chemicals"], "Choose clean, safe materials."],
  ["Materials from nature, like leaves and rocks, should be…", "collected responsibly and without harming living things", ["taken from protected areas", "taken in any amount", "thrown away after"], "Respect nature."],
  ["At the end of a lab, you should…", "clean up and wash your hands", ["leave everything", "taste the sample", "pour chemicals anywhere"], "Cleaning protects you and others."],
  ["If you spill a chemical on your skin, you should…", "tell your teacher right away and rinse as directed", ["wipe on your clothes", "say nothing", "wait for it to dry"], "Tell your teacher right away."],
  ["Where should you find the nearest exit and the safety equipment in a science room?", "before starting the lab", ["only after an accident", "never", "after the lab ends"], "Know the safety routines."],
  ["What does a hazard symbol on a label tell you?", "that the contents may be dangerous in some way", ["the price", "the brand", "the colour"], "Symbols warn about risks."],
  ["A pan balance is used safely when you…", "place objects gently on the pans", ["drop objects on it", "press on it", "lean on the table"], "Treat equipment with care."],
  ["The right way to read the volume in a graduated cylinder is…", "at eye level, at the bottom of the curve of the liquid", ["from above", "from below", "by squinting from far away"], "Reading the meniscus at eye level avoids errors.", true],
  ["To carry a microscope or telescope safely you should…", "use both hands and walk carefully", ["swing it by the cord", "run", "carry with one finger"], "Handle equipment with both hands.", true],
  ["A student wants to remove the goggles because they feel uncomfortable during heating. What should they do?", "ask the teacher for a better fit, but keep eyes protected", ["take them off", "throw them away", "ignore the rule"], "Eye protection is not optional.", true],
  ["Which is the safest way to pour a hot liquid in a lab?", "Use heat-safe gloves or tongs and pour slowly away from your body", ["Pour quickly with bare hands", "Hold the container over your face", "Pour while running"], "Take care with heat.", true],
  ["Which keeps a work area safe?", "Keep bags and backpacks out of the walkways", ["Leave backpacks in the aisle", "Run between tables", "Eat in the lab"], "Clear walkways prevent trips."],
  ["You see a classmate doing something unsafe. The best action is to…", "tell the teacher right away", ["laugh", "copy them", "ignore it"], "Safety is everyone’s job."],
  ["Which tool would you use to compare the heat of two liquids safely?", "a thermometer", ["your finger", "your tongue", "your elbow"], "Use instruments, not your body."],
  ["Which diagram or chart is a good way to record how many seeds sprouted each day?", "a table of days and counts", ["a poem", "a poster title", "a photograph with no label"], "Tables organize repeated measurements."],
  ["When using binoculars or a telescope outdoors at night, the best place to observe is…", "away from bright lights, with an adult nearby", ["in a busy street", "on a roof alone", "beside a pond alone"], "Choose a dark, safe place.", true],
  ["Why do labs sometimes require closed-toe shoes?", "To protect feet from spills and falling objects", ["To be quiet", "For fashion", "To run faster"], "Protect yourself from hazards."],
  ["Which of these is a safe procedure when using a hot plate?", "Turn it off and let it cool before moving it", ["Carry it while hot", "Cover it with paper", "Pour water on it"], "Allow heating equipment to cool."],
];

export const labSafety = bankUnit({
  id: "mb-7-lab-safety",
  title: "Safe Science Practice",
  emoji: "🥽",
  blurb: "Use equipment safely and keep a good logbook",
  parentNote: "Children practise using science materials and equipment safely and competently, such as heat, glassware, chemicals and telescopes, and recording data in a logbook.",
  standards: ["SCI.7.C.4", "using materials and equipment appropriately, competently and safely"],
  items: SAFETY,
});

const SCIENCE_LIFE: Q[] = [
  ["An astronomer studies…", "stars, planets and space", ["rocks only", "the ocean only", "forests only"], "Astronomy is the science of space."],
  ["An ecologist studies…", "how living things interact with each other and their environment", ["only stars", "only machines", "only rocks"], "Ecology is about ecosystems."],
  ["Which worker uses ideas about heat transfer to keep buildings comfortable?", "an HVAC technician", ["a baker only", "a poet", "a painter"], "HVAC stands for heating, ventilation and air conditioning."],
  ["Which job uses ideas about forces and materials to design bridges?", "an engineer", ["a historian", "a florist", "a singer"], "Engineers apply science."],
  ["Which activity uses science ideas about energy and the body?", "fitness training", ["napping", "ignoring exercise", "sitting still always"], "Muscles use stored energy."],
  ["Which hobby uses ideas about wind and force?", "sailing", ["knitting only", "colouring", "stamp collecting"], "Sails use moving air."],
  ["Which hobby uses science ideas about decay and nutrients?", "composting", ["stamp collecting", "sketching", "chess"], "Compost shows nutrients being recycled."],
  ["Which hobby uses science ideas about plant needs?", "gardening", ["video watching", "painting walls", "juggling"], "Plants need light, water and nutrients."],
  ["Stargazing connects to science because it involves…", "observing objects in the night sky", ["cooking", "reading maps of towns", "building boats"], "People observe stars and planets."],
  ["A baseball pitcher throwing a fastball uses ideas about…", "force and motion", ["photosynthesis", "soil", "weather maps"], "Forces change how objects move."],
  ["Dancers use science ideas about…", "balance, forces and energy in movement", ["only colour", "only sound", "only cooking"], "Science is part of dance."],
  ["Many people who hunt, trap, fish and pick berries learn to observe…", "weather, animals, plants and seasons closely", ["only video games", "only buildings", "only clocks"], "These land-based practices rely on careful observation."],
  ["Which is an STSE issue?", "How can our school use less electricity?", ["What is for lunch?", "Who won the game?", "What is the date?"], "STSE means science, technology, society and the environment."],
  ["What does STSE stand for?", "science, technology, society and the environment", ["stars, time, speed and energy", "stories, tests, schools and exams", "sound, time, space and electricity"], "It links science to real life."],
  ["Which action could a class take about energy use in Manitoba homes?", "Plan ways to reduce heating and lighting use while staying comfortable", ["Leave lights on all day", "Turn off all heat in winter", "Ignore the problem"], "Action should be thoughtful."],
  ["A student measures surface temperatures on the school field to find where heat is absorbed most. This is an example of…", "gathering data to take action on an STSE issue", ["guessing", "cooking", "skipping a problem"], "Data guides action."],
  ["Which action could help a stressed local plant population?", "protecting its habitat and limiting damage from trampling", ["picking all the plants", "building a parking lot", "ignoring it"], "Action should support the species."],
  ["Curiosity in science means…", "wanting to find out how and why things happen", ["not asking questions", "knowing everything", "avoiding experiments"], "Curious scientists wonder and ask."],
  ["A scientific attitude includes…", "being open-minded and honest about evidence", ["ignoring evidence you dislike", "never changing your mind", "copying data"], "Honesty and openness matter."],
  ["Who can contribute to science?", "everyone", ["only adults", "only people in labs", "only people with special tools"], "Everyone can observe and ask questions."],
  ["Which connects a science idea to your own experience?", "Noticing that a metal spoon feels colder than a wooden one because heat leaves your hand faster", ["Memorizing a definition only", "Skipping the example", "Avoiding touching anything"], "Link ideas to experiences."],
  ["A personal connection to nature can be built by…", "spending time outside and noticing living things", ["staying inside always", "avoiding gardens", "ignoring seasons"], "Noticing builds connection."],
  ["First Nations, Métis and Inuit communities have knowledge about the land that was built through…", "careful observation over many generations", ["one experiment", "a single book", "chance only"], "Knowledge is passed on and grows.", true],
  ["Many First Nations, Métis and Inuit knowledge keepers teach that living things and the land are…", "interconnected, and should be cared for in return", ["unrelated", "only for use", "unimportant"], "Many communities teach reciprocity: give back as you take.", true],
  ["Land-based learning means…", "learning outdoors, from the land and the people who know it", ["learning only from screens", "learning only from tests", "learning only indoors"], "Learning on the land is practised in many communities today.", true],
  ["In many communities today, Indigenous knowledge and Western science are…", "used together in some projects to care for land and water", ["never shared", "opposed in every case", "identical"], "They can work alongside each other.", true],
  ["Which statement shows respect for Indigenous knowledge?", "Listen to Knowledge Keepers and ask permission before sharing what they teach", ["Take stories without asking", "Treat all Nations as one", "Say it is only history"], "Respect, permission and care for each community’s teachings.", true],
  ["Why is it important to say “some” or “many” First Nations rather than “all”?", "Each Nation has its own ways of knowing and traditions", ["It is shorter", "All are the same", "It makes the sentence rhyme"], "Nations are diverse.", true],
  ["Which statement describes scientific ideas in daily life?", "Cooking changes ingredients through heat and chemical changes", ["Cooking has no science", "Only labs use science", "Science is only in books"], "Science is everywhere."],
];

export const scienceInLife = bankUnit({
  id: "mb-7-science-in-life",
  title: "Science All Around Us",
  emoji: "🌍",
  blurb: "Careers, hobbies, ways of knowing and taking action",
  parentNote: "Children connect science to careers, hobbies and activities, practise scientific attitudes, think about taking action on a science and society issue, and learn that First Nations, Métis and Inuit communities have their own ways of knowing the land.",
  standards: ["SCI.7.A.1, SCI.7.B.1, SCI.7.C.1, SCI.7.C.5", "Indigenous ways of knowing, a sense of belonging in science, action on STSE issues and connections to careers and hobbies"],
  items: SCIENCE_LIFE,
});

const ENERGY: Q[] = [
  ["At what temperature does pure water boil at sea level?", "100 °C", ["0 °C", "50 °C", "212 °C"], "Water boils at 100 °C (212 °F)."],
  ["At what temperature does pure water melt (or ice melt)?", "0 °C", ["100 °C", "-10 °C", "32 °C"], "0 °C is the melting point of ice."],
  ["Different substances have different melting and boiling points because…", "the attraction between their particles is different", ["they are different colours", "they have different names", "they are in different rooms"], "Stronger attractions need more energy to break."],
  ["Which has a higher melting point?", "iron", ["water", "ethanol", "oxygen"], "Iron melts at about 1538 °C."],
  ["Which substance is a gas at room temperature?", "oxygen", ["iron", "water", "gold"], "Oxygen’s boiling point is about -183 °C."],
  ["Ethanol boils at about 78 °C and water at 100 °C. Which will boil first when heated?", "ethanol", ["water", "both at once", "neither"], "Lower boiling point means it boils first."],
  ["Why does chocolate melt in your hand?", "Its melting point is close to body temperature", ["It has no particles", "It is always a liquid", "It boils at 0 °C"], "Heat from your hands is enough to melt it."],
  ["Mercury melts at about -39 °C. At room temperature it is a…", "liquid", ["solid", "gas", "plasma"], "Room temperature is above its melting point and below its boiling point."],
  ["Gold melts at about 1064 °C. At room temperature gold is a…", "solid", ["liquid", "gas", "none of these"], "Room temperature is far below its melting point."],
  ["If a substance’s particles attract each other strongly, the melting point is likely…", "higher", ["lower", "the same as water’s", "zero"], "More energy is needed to loosen the particles."],
  ["What happens to the total amount of energy when it changes from one form to another?", "It stays the same", ["It doubles", "It disappears", "It always shrinks"], "Energy is transferred or changed, not created or destroyed."],
  ["When a battery lights a bulb, the energy changes from…", "chemical to electrical to light and heat", ["light to sound", "sound to chemical", "heat to nuclear"], "Stored chemical energy makes the bulb glow."],
  ["Plants use sunlight to make food. This is an energy exchange from…", "light energy to chemical energy", ["sound to light", "heat to sound", "electrical to magnetic"], "Photosynthesis stores energy."],
  ["When you eat food and run, the energy changes from…", "chemical energy in food to motion and heat", ["light to chemical", "sound to electrical", "nuclear to magnetic"], "Your body releases stored energy."],
  ["A pot of soup heated on a stove gains energy from…", "the burner", ["the spoon", "the lid", "the table"], "Energy is transferred to the soup."],
  ["Weather such as wind and storms can be understood as energy exchanges powered mainly by…", "the Sun", ["the Moon", "rocks", "magnets"], "Solar energy drives weather."],
  ["Energy stored in a stretched elastic band is…", "potential energy", ["kinetic energy", "sound energy", "light energy"], "Stored energy can be released."],
  ["When the stretched band is released, that stored energy changes to…", "motion (kinetic) energy", ["no energy", "chemical energy", "potential only"], "Moving objects have kinetic energy."],
  ["When energy is transferred, some of it ends up as…", "heat in the surroundings", ["nothing", "more energy than before", "mass"], "Energy is dissipated as heat."],
  ["Rubbing your hands together warms them. Energy changes from…", "motion to heat", ["heat to motion", "light to sound", "sound to light"], "Friction makes heat."],
  ["Efficiency tells us…", "how much of the energy put in is used for the job we want", ["how heavy a device is", "how loud a device is", "what colour a device is"], "More useful output means higher efficiency."],
  ["An LED bulb and an old incandescent bulb both give light. The LED is more efficient because…", "less of its energy is wasted as heat", ["it makes more heat", "it uses more energy", "it is bigger"], "Efficient devices waste less."],
  ["An old bulb gives off a lot of heat. This heat is…", "wasted energy", ["useful light", "stored light", "new energy"], "It is not the output we want from a bulb."],
  ["A car engine burns fuel and moves the car. Much of the fuel’s energy goes to…", "heat in the engine and surroundings", ["extra fuel", "new energy", "gravity"], "Engines waste a lot of energy as heat.", true],
  ["Which device is a good example of changing electrical energy to sound energy?", "a speaker", ["a toaster", "a lamp", "a fan"], "Speakers make sound from electricity."],
  ["Which device changes electrical energy mainly to heat?", "a toaster", ["a speaker", "a camera", "a microphone"], "Heating elements make heat."],
  ["Which device changes electrical energy mainly to motion?", "an electric fan", ["a toaster", "a lamp", "a doorbell"], "Motors turn electricity into movement."],
  ["The energy stored in a hydroelectric reservoir is…", "gravitational potential energy of water", ["chemical energy in coal", "heat from nuclear fuel", "sound energy"], "Water high above the turbine has stored energy.", true],
  ["In a hydroelectric dam, falling water spins a turbine. The energy of falling water changes to…", "electrical energy (and some heat)", ["only sound", "only light", "chemical energy only"], "Generators turn motion into electricity.", true],
  ["Why does a bouncing ball stop bouncing eventually?", "Some energy is turned into heat and sound each time", ["energy disappears forever", "the ball gets lighter", "gravity turns off"], "Energy spreads into the surroundings.", true],
  ["Which statement is true for all energy transfers?", "Some energy ends up as heat in the environment", ["No energy is ever wasted", "Energy is created", "Energy stops existing"], "Not all energy is useful for the job.", true],
  ["The SI unit used to measure energy is…", "joule (J)", ["newton (N)", "kilogram (kg)", "degree Celsius (°C)"], "Energy is measured in joules."],
];

export const energyAndMelting = bankUnit({
  id: "mb-7-energy-melting",
  title: "Energy Changes",
  emoji: "⚡",
  blurb: "Melting points, energy exchanges and efficiency",
  parentNote: "Children practise why substances melt and boil at different temperatures, follow energy as it changes form, and learn why some energy always ends up as heat.",
  standards: ["SCI.7.E.3, SCI.7.E.10, SCI.7.E.11", "melting and boiling points, energy exchanges in everyday phenomena, and energy transfer, dissipation as heat and efficiency"],
  items: ENERGY,
});
