import { bankUnit, type Q } from "../own";

// More Grade 7 social studies, Canada in the Contemporary World (Manitoba): comparing societies in Asia, Africa and
// Australasia, their geography, economies, history and government; Europe and the Americas; people on the move;
// global citizens; research, bias and viewpoints; working together; and reading the land and making maps.

const SOCIETIES: Q[] = [
  ["Which of these do ALL societies have in common?", "social structure, communication, art, beliefs, technology, governance and an economy", ["the same language", "the same religion", "the same food"], "Every society has these elements, but they take different forms."],
  ["Governance in a society means…", "how decisions are made and rules are kept", ["what people eat", "what music people play", "how big the houses are"], "It is the way a society is organized and led."],
  ["Which is an example of communication in a society?", "a language or sign system", ["a mountain", "a river", "a volcano"], "People share ideas through language and symbols."],
  ["An economy is…", "how a society produces, shares and uses goods and services", ["the weather", "the national flag", "a national song"], "It covers work, trade and money."],
  ["Which cultural factor can shape a way of life?", "beliefs and values", ["the temperature of a lake", "the number of trees", "the height of a hill"], "Culture includes beliefs, language, customs and traditions."],
  ["Which is an example of a society’s technology?", "the tools and machines it uses", ["its anthem", "its holidays", "its legends"], "Technology includes tools from ploughs to phones."],
  ["Japan has many mountains, so many people live on narrow coastal plains. This shows…", "how the natural environment shapes ways of life", ["that Japan has no cities", "that mountains are flat", "that farming is not possible"], "Landforms affect where people live."],
  ["The Maori are the Indigenous people of…", "Aotearoa New Zealand", ["Australia", "Japan", "India"], "Maori have lived in Aotearoa for centuries and continue to today."],
  ["Aboriginal and Torres Strait Islander peoples are the First Peoples of…", "Australia", ["New Zealand", "Japan", "South Africa"], "They include many different Nations and languages."],
  ["The Ainu are an Indigenous people of northern…", "Japan", ["Australia", "Kenya", "Indonesia"], "Ainu communities live in Hokkaido and continue their culture today."],
  ["The Maasai are a people who live in…", "Kenya and Tanzania", ["Japan and Korea", "Chile and Peru", "Norway and Sweden"], "Many Maasai communities herd cattle in East Africa."],
  ["Which is an example of artistic expression in Japan?", "origami (paper folding)", ["haka", "didgeridoo", "kente cloth"], "Japanese arts include origami, calligraphy and kabuki."],
  ["The haka is a traditional performance of the…", "Maori of New Zealand", ["Maasai of Kenya", "Ainu of Japan", "Sherpa of Nepal"], "Haka is part of Maori culture, including at sports and ceremonies today."],
  ["Kente cloth, with bright woven patterns, is made in…", "Ghana", ["Japan", "New Zealand", "India"], "Kente is a woven cloth with meaning in its patterns."],
  ["Dot painting is a form of art by Aboriginal artists in…", "Australia", ["Kenya", "Japan", "Vietnam"], "It is one of many art forms by Aboriginal artists."],
  ["Bollywood is the nickname for the film industry based in…", "Mumbai, India", ["Tokyo, Japan", "Nairobi, Kenya", "Sydney, Australia"], "Hindi-language movies are made there."],
  ["Gamelan music, played on gongs and metal instruments, comes from…", "Indonesia", ["Argentina", "Norway", "Greenland"], "It is a traditional orchestra from islands such as Java and Bali."],
  ["In some West African societies, a griot is…", "a storyteller who keeps history and music alive", ["a kind of boat", "a type of food", "a kind of tax"], "Oral tradition passes history from one generation to the next."],
  ["Oral tradition means…", "stories and knowledge passed on by speaking", ["written laws only", "paintings only", "textbooks only"], "Many societies rely on spoken stories."],
  ["Which is an example of westernization?", "Western-style clothing and foods spreading to many places", ["a traditional festival", "a local language lesson", "a mountain trail"], "Westernization means Western ideas and products spread widely."],
  ["Cultural homogenization means…", "cultures becoming more and more alike", ["cultures growing more different", "people forgetting maps", "countries merging"], "Global media can make places look similar.", true],
  ["Global communication, such as the internet, can lead to…", "ideas and styles spreading quickly between countries", ["no contact between countries", "less news", "fewer languages needed"], "It can also help people share their own cultures with the world."],
  ["A concern about westernization is that it may…", "weaken local languages and traditions", ["help all traditions grow", "stop trade", "end all technology"], "People may lose some traditional ways when others dominate.", true],
  ["Indigenous ways of life in many places are often closely connected to…", "the land and its resources", ["only big cities", "only factories", "only space"], "Many Indigenous peoples have deep ties to their lands."],
  ["Many Indigenous languages around the world are at risk because…", "fewer young people learn them as their first language", ["they are too easy", "they have no speakers", "they are banned by maps"], "Communities today work to keep their languages alive."],
  ["Why is it important to appreciate cultural and linguistic diversity?", "It enriches our understanding of the world", ["It makes people the same", "It is confusing", "It stops learning"], "Diversity is a source of ideas and creativity."],
  ["A good way to broaden your perspective beyond the familiar is to…", "learn about people whose lives are different from yours", ["avoid new ideas", "only talk to people like you", "ignore other cultures"], "Curiosity builds understanding."],
  ["Which question shows interest in another society’s way of life?", "How do families celebrate important days there?", ["Why can’t they be like us?", "Is their food strange?", "Who cares about them?"], "Ask respectful, open questions."],
  ["Concern for the loss of Indigenous ways of life means…", "supporting the efforts of Indigenous peoples to keep their languages, lands and traditions strong", ["ignoring changes", "agreeing that traditions do not matter", "forcing them to change"], "Respect and support from others can help.", true],
  ["A traditional meal of rice, fish and miso soup is part of which society’s food culture?", "Japanese", ["Maasai", "Maori", "Inuit"], "Rice and fish are central to Japanese cuisine.", true],
];

export const societiesCompared = bankUnit({
  id: "mb-7-societies-compared",
  title: "Comparing Societies",
  emoji: "🌏",
  blurb: "What societies share, and what makes each one unique",
  parentNote: "Children compare societies in Asia, Africa and Australasia: what all societies have in common, how culture, art, westernization and Indigenous ways of life shape daily life, and why diversity is valuable.",
  standards: ["7-KI-009, 7-KI-010, 7-KI-011, 7-KI-012, 7-KI-014, 7-VI-006, 7-VI-007, 7-VG-012, 7-VP-015", "elements all societies share, culture and artistic expression, westernization, Indigenous ways of life and appreciating diversity"],
  items: SOCIETIES,
});

const AAA_MAP: Q[] = [
  ["Which is the highest mountain in the world above sea level?", "Mount Everest", ["Mount Kilimanjaro", "Uluru", "Mount Fuji"], "It is in the Himalayas on the border of Nepal and China."],
  ["The Himalayas are mountains in…", "Asia", ["Africa", "Australia", "South America"], "They include Everest."],
  ["Mount Kilimanjaro is the highest mountain in…", "Africa", ["Asia", "Australia", "Europe"], "It is in Tanzania."],
  ["The Sahara is the world’s largest hot…", "desert", ["rainforest", "lake", "island"], "It stretches across northern Africa."],
  ["The Gobi Desert is in…", "Asia", ["Africa", "Australia", "North America"], "It spreads across Mongolia and northern China."],
  ["The Nile River flows north through…", "Africa, into the Mediterranean Sea", ["Asia, into the Pacific", "Australia, into the Tasman Sea", "Europe, into the Black Sea"], "It is one of the longest rivers in the world."],
  ["The Yangtze is the longest river in…", "Asia", ["Africa", "Australia", "Europe"], "It flows across China."],
  ["The Ganges is a river that flows through…", "India", ["Egypt", "Australia", "Japan"], "It is important to many people in India."],
  ["The Congo River is in…", "Africa", ["Asia", "Australia", "New Zealand"], "It flows through central Africa."],
  ["Lake Victoria is the largest lake in…", "Africa", ["Asia", "Australia", "Europe"], "It is shared by Uganda, Kenya and Tanzania."],
  ["Which city is the capital of Japan?", "Tokyo", ["Osaka", "Kyoto", "Seoul"], "Tokyo is one of the largest cities in the world."],
  ["Which city is the capital of India?", "New Delhi", ["Mumbai", "Kolkata", "Chennai"], "Mumbai is larger, but the capital is New Delhi."],
  ["Which city is the capital of China?", "Beijing", ["Shanghai", "Hong Kong", "Guangzhou"], "Shanghai is larger, but Beijing is the capital."],
  ["Which city is the capital of Egypt?", "Cairo", ["Alexandria", "Nairobi", "Lagos"], "Cairo is on the Nile."],
  ["Which city is the capital of Kenya?", "Nairobi", ["Cairo", "Cape Town", "Accra"], "It is in East Africa."],
  ["Lagos is a very large city in…", "Nigeria", ["Egypt", "Kenya", "South Africa"], "It is in West Africa."],
  ["Cape Town is a major city near the southern tip of…", "Africa", ["Asia", "Australia", "South America"], "It is in South Africa."],
  ["The capital of Australia is…", "Canberra", ["Sydney", "Melbourne", "Perth"], "Sydney is larger, but Canberra is the capital."],
  ["The capital of New Zealand is…", "Wellington", ["Auckland", "Christchurch", "Sydney"], "Auckland is the largest city."],
  ["Uluru is a large sandstone rock in…", "central Australia", ["New Zealand", "Japan", "Kenya"], "It is sacred to the Anangu people."],
  ["The Great Barrier Reef lies off the coast of…", "Australia", ["Japan", "Kenya", "India"], "It is the world’s largest coral reef system."],
  ["The Southern Alps are mountains in…", "New Zealand", ["Japan", "Kenya", "India"], "They run down the South Island."],
  ["The Great Dividing Range runs along the…", "east coast of Australia", ["west coast of Africa", "north coast of Asia", "south coast of New Zealand"], "It is the longest mountain range in Australia."],
  ["Which ocean is east of Asia and Australia?", "Pacific Ocean", ["Atlantic Ocean", "Arctic Ocean", "Southern Ocean only"], "The Pacific is the largest ocean."],
  ["Which ocean lies east of Africa?", "Indian Ocean", ["Atlantic Ocean", "Arctic Ocean", "Pacific Ocean"], "The Indian Ocean touches Africa, Asia and Australia."],
  ["Which sea lies between Africa and Europe?", "Mediterranean Sea", ["Red Sea", "Tasman Sea", "Caspian Sea"], "It lies north of Africa."],
  ["The Tasman Sea lies between Australia and…", "New Zealand", ["Japan", "India", "Kenya"], "It is part of the Pacific Ocean."],
  ["Monsoon rains in South Asia affect farming because…", "rice and other crops depend on the seasonal rains", ["there is no rain", "farming stops forever", "no one lives there"], "Many farmers plan around the monsoon."],
  ["People in the Sahara region often travel and trade along oases because…", "oases have scarce water in a dry land", ["oases are mountains", "oases are cities", "oases have snow"], "Water is life in the desert."],
  ["Much of Egypt’s population lives along the Nile because…", "the river provides water and fertile soil in a dry land", ["it is cold", "it is a mountain", "there are no cities"], "A river can shape where people live.", true],
  ["Japan is on the “Ring of Fire,” so people there prepare for…", "earthquakes and volcanoes", ["blizzards every day", "monsoons only", "desert storms"], "Buildings and schools practise safety.", true],
  ["Many Pacific islanders depend on the ocean for…", "fishing and travel", ["wheat farming", "coal mining", "skiing"], "Island ways of life are shaped by the sea."],
  ["Which continent is the largest by area?", "Asia", ["Africa", "Australia", "Europe"], "Asia is the largest continent."],
];

export const asiaAfricaAustralasiaMap = bankUnit({
  id: "mb-7-aaa-map",
  title: "Asia, Africa & Australasia Map",
  emoji: "🗺️",
  blurb: "Cities, landforms, water and how land shapes life",
  parentNote: "Children locate major cities, landforms and bodies of water in Asia, Africa and Australasia and explain how the natural environment influences ways of life.",
  standards: ["7-KL-022, 7-KL-023", "major cities, landforms and bodies of water in Asia, Africa and Australasia, and the influence of the environment on ways of life"],
  items: AAA_MAP,
});

const AAA_ECON: Q[] = [
  ["Japan is known for manufacturing things like…", "cars and electronics", ["wool", "cocoa", "diamonds"], "Manufacturing is a major activity."],
  ["India has a large industry in…", "computer services and software, along with farming", ["only fishing", "only forestry", "only whaling"], "Both farming and services are major."],
  ["Ghana is a major producer of…", "cocoa", ["rice for sushi", "kiwi fruit", "wool"], "Cocoa is used to make chocolate."],
  ["Kenya is known for exporting…", "tea, flowers and coffee", ["snow skis", "wheat flour", "maple syrup"], "These are major exports."],
  ["Australia has large industries in…", "mining, such as iron ore, and agriculture", ["only fishing", "only rice paddies", "only whaling"], "Iron ore is mined in the west of Australia."],
  ["New Zealand is known for…", "dairy products and sheep farming", ["oil only", "cars only", "tea only"], "Pastures cover much of the land."],
  ["Bangladesh has a large industry that makes…", "clothing and textiles", ["airplanes", "ships only", "snowmobiles"], "Clothing is a major export."],
  ["Tourism is a major economic activity in places such as…", "Thailand, Egypt and New Zealand", ["Antarctica", "the Sahara only", "none"], "People travel to see sites, beaches and nature."],
  ["Fishing is an important activity in…", "island nations such as Japan and the Philippines", ["landlocked countries", "deserts", "high mountains"], "Seafood is a key food and export."],
  ["Mobile money, such as M-Pesa in Kenya, lets people…", "send and receive money by phone", ["buy only tickets", "learn math", "watch TV"], "Mobile technology changes how people do business."],
  ["Solar-powered lights and phone chargers help people in places without a power grid by…", "giving them electricity from the Sun", ["using coal", "using wood only", "needing no energy"], "Technology can change daily life."],
  ["Mobile phones have changed life in many African communities by…", "making it easier to share information and do business", ["ending all farming", "replacing all schools", "stopping trade"], "Phones connect people quickly."],
  ["The impact of changing technologies on traditional farming can include…", "new machines and tools that change the work", ["no changes", "no harvests", "fewer seeds"], "Technology changes how work is done."],
  ["Fair trade means…", "farmers and workers are paid fairly and work in safe conditions", ["products are free", "products are cheaper than anywhere", "products are secret"], "It supports fair pay and safe work."],
  ["A cooperative is…", "a group of people who work together and share the benefits", ["a type of tax", "a giant company", "a machine"], "Farmers in a co-op may sell their crops together."],
  ["Child labour is a problem because it…", "keeps children from school and can harm them", ["helps children learn math", "makes games", "gives them money for school"], "Children have a right to education and safety."],
  ["Exploitation of workers means…", "treating workers unfairly, such as with low pay and unsafe conditions", ["paying a fair wage", "giving long vacations", "offering free lunch"], "Fair work protects people."],
  ["Exclusion from the workforce can happen when people…", "are denied jobs because of who they are", ["are given training", "are given tools", "are given good pay"], "Equal access to work matters.", true],
  ["Many factories in Asia make goods that are sold in Canada. This shows…", "trade connects people around the world", ["trade does not exist", "no one trades", "goods stay home"], "Global trade connects economies."],
  ["Why might shoppers choose fair trade coffee or chocolate?", "to support fair pay for growers", ["because it is always cheapest", "because it has no flavour", "because it is secret"], "Choices can support fairness."],
  ["Urbanization means…", "more people living in cities", ["people moving to farms", "cities becoming smaller", "forests growing"], "Cities have grown in many places."],
  ["Industrialization means…", "a society using more factories and machines to make goods", ["a society stopping all trade", "a society with no machines", "a society going back to farming only"], "It changes work and the environment."],
  ["Urbanization and industrialization can affect Indigenous peoples when…", "land is used for cities and factories, changing their traditional ways of life", ["nothing changes", "they always benefit", "they move to space"], "Land rights and ways of life can be at risk.", true],
  ["Access to safe drinking water affects health because…", "unsafe water can spread illness", ["water is heavy", "water is blue", "water is cold"], "Clean water prevents many diseases."],
  ["Which helps improve health in a community?", "clean water, enough food and access to medical care", ["fewer clinics", "unsafe water", "less food"], "These are basic needs."],
  ["Mosquito nets help prevent…", "malaria", ["colds", "broken bones", "sunburn"], "Malaria is spread by mosquitoes in some regions."],
  ["Vaccines help protect people from…", "diseases", ["rain", "traffic", "noise"], "They are a key public health tool."],
  ["HIV/AIDS has affected the health of many families in parts of…", "Africa and other regions around the world", ["only the Arctic", "only Antarctica", "no one"], "Health education and medicine help.", true],
  ["An epidemic is…", "a disease spreading quickly through many people in an area", ["a type of weather", "a festival", "a farm tool"], "It needs public health action."],
  ["Which would help a community deal with an epidemic?", "health workers, clean water and information", ["ignoring symptoms", "closing every clinic", "spreading rumours"], "Public health helps people.", true],
  ["A society’s economic activities are the…", "ways people make a living", ["names of its cities", "colours of its flag", "dates of its holidays"], "Activities include farming, fishing, manufacturing and services."],
];

export const asiaAfricaAustralasiaEconomy = bankUnit({
  id: "mb-7-aaa-economy",
  title: "Work, Trade & Health",
  emoji: "💼",
  blurb: "Economies, technology, fair trade and health",
  parentNote: "Children learn about economic activities in Asia, Africa and Australasia, how technology is changing work and daily life, issues like child labour and fair trade, and factors that affect health.",
  standards: ["7-KE-046, 7-KE-047, 7-KE-048, 7-KE-049, 7-KI-013", "economic activities, urbanization and Indigenous peoples, changing technologies, work and trade issues and health"],
  items: AAA_ECON,
});

const AAA_HIST: Q[] = [
  ["India became independent from British rule in…", "1947", ["1847", "1920", "1997"], "India and Pakistan became independent in August 1947."],
  ["Mohandas (Mahatma) Gandhi is remembered for…", "leading nonviolent resistance in India", ["inventing the telephone", "discovering Australia", "building the Great Wall"], "He used peaceful protest."],
  ["The Treaty of Waitangi, signed in 1840, was an agreement between…", "the British Crown and many Maori chiefs", ["Japan and China", "Australia and India", "Canada and Kenya"], "Its meaning and promises are still discussed in New Zealand today."],
  ["British colonization of Australia began in…", "1788", ["1588", "1888", "1988"], "The First Fleet arrived at Sydney Cove in 1788."],
  ["Colonization means…", "one country taking control of another place and its people", ["two countries sharing a border", "a trade agreement", "a sports event"], "It often changed ways of life."],
  ["Apartheid in South Africa was…", "a system of laws that separated and treated people unfairly by race", ["a trade route", "a festival", "a river"], "It was an unjust legal system."],
  ["Apartheid officially ended in the early…", "1990s", ["1890s", "1960s", "2010s"], "South Africa held its first democratic elections for all citizens in 1994."],
  ["Nelson Mandela became president of South Africa in…", "1994", ["1944", "1964", "2004"], "He was the first president chosen in an election open to all."],
  ["The Atlantic slave trade forced millions of people from…", "Africa to the Americas", ["Asia to Australia", "Europe to Antarctica", "Canada to Asia"], "It is a painful part of history with lasting effects."],
  ["Nuclear bombs were dropped on two Japanese cities, Hiroshima and Nagasaki, in…", "1945", ["1845", "1905", "1985"], "This happened at the end of the Second World War."],
  ["In 2004 a huge tsunami in the Indian Ocean affected countries in…", "Asia and Africa", ["only Europe", "only Canada", "only Antarctica"], "It was one of the deadliest natural disasters on record."],
  ["Japan’s system of government is a…", "constitutional monarchy with an elected parliament", ["one-person rule with no laws", "federation of tribes", "military council"], "The emperor has a symbolic role."],
  ["India is often called the world’s largest…", "democracy", ["monarchy", "desert", "island"], "Hundreds of millions vote."],
  ["Australia’s government is a…", "parliamentary democracy and a constitutional monarchy", ["single-party state", "military rule", "tribal council only"], "It shares a monarch with Canada."],
  ["In a democracy, citizens…", "can vote to choose their leaders", ["do not vote", "choose nothing", "are ruled by one family forever"], "Elections are part of democratic government."],
  ["A justice system includes…", "laws, courts and police", ["only farms", "only schools", "only roads"], "It helps keep order and settle disputes."],
  ["Unjust laws can affect people’s lives by…", "limiting their rights and opportunities", ["improving everything", "having no effect", "ending all taxes"], "Fairness in law matters."],
  ["The Berlin Conference of 1884–1885 saw European powers…", "divide up much of Africa among themselves", ["found the United Nations", "draw maps of Canada", "settle in Japan"], "Colonial borders still affect Africa today.", true],
  ["Many African countries gained independence from colonial rule in the…", "1950s and 1960s", ["1750s", "1850s", "2000s"], "A wave of independence changed the continent.", true],
  ["Why do historical events like colonization continue to affect societies today?", "They shaped borders, languages, economies and relationships", ["They are forgotten", "They only affected buildings", "They have no effects"], "History has lasting effects."],
  ["Which is an example of a disaster that can shape a society’s history?", "an earthquake that destroys a city", ["a school assembly", "a sunny day", "a birthday party"], "Disasters can change communities for years."],
  ["After the 2011 earthquake and tsunami in Japan, communities…", "worked to rebuild and improve safety", ["were abandoned forever", "did nothing", "moved to the Moon"], "Societies recover and prepare."],
  ["A truth and reconciliation process is meant to…", "tell the truth about past harms and work toward healing", ["hide the past", "blame everyone", "end all laws"], "South Africa and Canada have both held such processes.", true],
  ["English is widely used in many countries of Asia, Africa and Australasia partly because…", "of colonial history and global communication", ["it is the oldest language", "it is the easiest language", "there are no other languages"], "Language use reflects history."],
  ["A parliamentary democracy has a legislature, which…", "makes laws", ["builds roads only", "grows food", "sings songs"], "Elected members debate and pass laws."],
  ["One-party governments are different from democracies because they…", "allow only one political party to hold power", ["have free elections for many parties", "have no leaders", "have no laws"], "Citizens have fewer choices.", true],
  ["Courts and judges are important in a justice system because they…", "decide disputes under the law", ["write songs", "grow rice", "sell goods"], "They apply the law fairly."],
  ["Why is it useful to study how colonization changed a society?", "It helps us understand present-day challenges and strengths", ["It makes a good story only", "It changes the past", "It is not related to today"], "The past shapes the present."],
  ["Which statement about Aboriginal peoples in Australia today is correct?", "Many Nations continue their languages, cultures and traditions", ["They no longer exist", "They all share one language", "They live only in the past"], "Living cultures continue today."],
  ["In Aotearoa New Zealand, the Maori language (te reo Maori) is…", "an official language alongside English", ["not spoken anymore", "the only language", "banned"], "Te reo Maori is taught in many schools today."],
];

export const asiaAfricaAustralasiaHistory = bankUnit({
  id: "mb-7-aaa-history-government",
  title: "History & Government",
  emoji: "🏛️",
  blurb: "Events that shaped societies and how they are governed",
  parentNote: "Children learn about historical events that continue to affect societies in Asia, Africa and Australasia, and how governments and justice systems shape ways of life.",
  standards: ["7-KH-030, 7-KP-043, 7-KI-012", "historical events that continue to affect societies, government and the justice system, and westernization"],
  items: AAA_HIST,
});

const MOVE: Q[] = [
  ["A “push factor” in migration is something that…", "makes people want to leave a place", ["draws people to a place", "is a type of road", "is a map tool"], "Examples are war, drought and lack of jobs."],
  ["A “pull factor” in migration is something that…", "attracts people to a new place", ["makes people leave", "is a tax", "is a river"], "Examples are jobs, safety and schools."],
  ["Which is an environmental push factor?", "a long drought that destroys crops", ["a new school", "a job offer", "a bright city"], "Environmental events can make people leave."],
  ["Which is an economic pull factor?", "better paying jobs", ["a flood", "war", "a famine"], "Jobs draw people to new places."],
  ["Which is a political push factor?", "war or unsafe conditions", ["good schools", "job offers", "warm weather"], "People flee danger."],
  ["Which is a social pull factor?", "family and friends already living there", ["a drought", "pollution", "loss of land"], "Social ties draw people."],
  ["A person who leaves their country to live in another is called an…", "immigrant (in the new country)", ["explorer", "resident only", "ambassador"], "An emigrant leaves; an immigrant arrives."],
  ["A refugee is someone who…", "has been forced to leave their country to find safety", ["is travelling on holiday", "has moved for fun", "works at an airport"], "Refugees flee conflict or persecution."],
  ["Migration means…", "moving from one place to another to live", ["visiting for a day", "shopping", "growing"], "Migration can be within or between countries."],
  ["Why do many people move from rural areas to cities?", "to find jobs, schools and services", ["to find less work", "to farm more land", "to avoid services"], "Cities offer work and services."],
  ["Increased urbanization can happen because of…", "access to services, housing and employment", ["having no jobs", "no buildings", "no schools"], "People move where opportunities are."],
  ["A challenge faced by large cities is…", "traffic congestion", ["too few people", "no buildings", "too much silence"], "Many people travel on limited roads."],
  ["Which is an environmental challenge in large cities?", "air and water pollution", ["too much fresh air", "wild forests everywhere", "too few cars"], "Cities concentrate pollution."],
  ["Which is a social challenge in large cities?", "affordable housing", ["too many forests", "too few buildings", "too little noise"], "Rents can be high."],
  ["Which is an economic challenge in cities?", "unemployment or low wages for some people", ["no stores", "no rain", "no money anywhere"], "Not everyone finds good work."],
  ["Slums or informal settlements often grow when…", "cities grow quickly and housing is too expensive", ["cities shrink", "forests grow", "farms expand"], "People build homes where they can."],
  ["Winnipeg’s population grew in the early 1900s because of…", "immigration and growth in rail and trade", ["a lack of jobs", "closing of railways", "a ban on newcomers"], "Many people arrived from Europe and elsewhere."],
  ["Many communities in Manitoba today include people who came from…", "many parts of the world", ["only one country", "no other country", "only the Prairies"], "Canada welcomes newcomers from many places."],
  ["Which is a likely benefit of immigration for Canada?", "new skills, ideas and cultures", ["fewer ideas", "less diversity", "fewer jobs"], "Newcomers contribute in many ways."],
  ["Some people move because of climate change when…", "rising seas or drought make their home difficult to live in", ["it is sunny", "they like snow", "schools are closed"], "Environmental changes can force moves.", true],
  ["A city with millions of people is sometimes called a…", "megacity", ["village", "hamlet", "farm"], "Examples include Tokyo and Mexico City.", true],
  ["São Paulo, Mexico City and New York are major cities in…", "the Americas", ["Africa", "Asia", "Australia"], "They are among the largest cities in the Americas."],
  ["London, Paris and Moscow are major cities in…", "Europe", ["Africa", "South America", "Australia"], "They are capitals of European countries."],
  ["Public transit, such as buses and trains, helps cities by…", "reducing traffic and pollution", ["adding more cars", "removing roads", "closing offices"], "It moves many people efficiently."],
  ["Which helps a city address housing problems?", "building more affordable homes", ["tearing down all homes", "stopping all construction", "removing rent rules"], "Housing policies help."],
  ["Urban planners help cities by…", "designing how land, roads and buildings are used", ["growing crops", "fixing cars", "painting posters"], "They plan for growth."],
  ["Green spaces such as parks are important in cities because they…", "give people places to play and help clean the air", ["add pollution", "block sunlight always", "cost nothing"], "Parks improve quality of life.", true],
  ["Migration affects both the place people leave and the place they go to by…", "changing population, economy and culture", ["having no effect", "stopping change", "removing laws"], "Both places change.", true],
  ["Which statement is true about movement of people today?", "Millions of people migrate for many reasons every year", ["No one moves anymore", "Only farmers move", "Only adults move"], "Migration is a global process."],
];

export const peopleOnTheMove = bankUnit({
  id: "mb-7-people-on-the-move",
  title: "People on the Move",
  emoji: "🚆",
  blurb: "Why people migrate and the challenges of big cities",
  parentNote: "Children explore push and pull factors in migration, why cities grow, and the economic, environmental and social challenges large urban centres face.",
  standards: ["7-KL-019, 7-KL-025, 7-KE-051", "factors that influence the movement of people, reasons for urbanization and challenges of large urban centres"],
  items: MOVE,
});

const EUROPE_AMERICAS: Q[] = [
  ["The Rhine River flows through…", "Europe", ["Africa", "Asia", "South America"], "It runs from the Alps to the North Sea."],
  ["The Alps are mountains in…", "Europe", ["Africa", "North America", "Australia"], "They stretch across several countries."],
  ["The Danube is a river in…", "Europe", ["South America", "Africa", "Asia only"], "It flows through many countries to the Black Sea."],
  ["Which city is the capital of France?", "Paris", ["Lyon", "Marseille", "Brussels"], "It lies on the Seine River."],
  ["Which city is the capital of Italy?", "Rome", ["Milan", "Venice", "Naples"], "Rome has ancient ruins."],
  ["Which city is the capital of the United Kingdom?", "London", ["Manchester", "Edinburgh", "Dublin"], "It lies on the Thames."],
  ["The Amazon River flows mainly through…", "Brazil in South America", ["Argentina only", "Mexico", "Canada"], "It carries more water than any other river."],
  ["The Andes are mountains along the west of…", "South America", ["North America", "Europe", "Africa"], "They are the longest continental mountain range."],
  ["The Rocky Mountains stretch through…", "western Canada and the United States", ["Brazil", "Europe", "Africa"], "They run from Canada into the southwest of the United States."],
  ["The Great Lakes are shared by Canada and…", "the United States", ["Mexico", "Brazil", "Greenland"], "They hold a large share of the world’s surface fresh water."],
  ["The Mississippi River flows through…", "the United States", ["Brazil", "Spain", "Argentina"], "It empties into the Gulf of Mexico."],
  ["Mexico City is the capital of…", "Mexico", ["Spain", "Brazil", "Chile"], "It is one of the largest cities in the Americas."],
  ["Buenos Aires is the capital of…", "Argentina", ["Chile", "Peru", "Brazil"], "It lies on the Río de la Plata."],
  ["The Panama Canal connects the…", "Atlantic and Pacific Oceans", ["Pacific and Indian Oceans", "Arctic and Atlantic Oceans", "Black Sea and the Baltic Sea"], "Ships use it to avoid sailing around South America."],
  ["The Mediterranean Sea lies south of…", "Europe", ["South America", "Asia", "North America"], "It is bordered by southern Europe and North Africa."],
  ["The Amazon rainforest has been cleared in places for…", "farms, ranches and logging", ["more snow", "more mountains", "building volcanoes"], "Deforestation threatens many species."],
  ["Reforestation means…", "planting trees to restore a forest", ["cutting down a forest", "building a road", "draining a lake"], "It can help restore habitat."],
  ["Wetlands are important because they…", "filter water and provide habitat", ["pollute water", "cause deserts", "dry up rivers"], "Many species depend on them."],
  ["Restoring wetlands helps by…", "improving water quality and habitat for wildlife", ["increasing flooding only", "removing all animals", "adding pollution"], "Restoration can bring wildlife back."],
  ["Endangered species are those that…", "may disappear if they are not protected", ["are common", "live only in zoos", "are all insects"], "Habitat loss is a major cause."],
  ["The Netherlands is known for farming in…", "greenhouses and carefully managed land", ["deserts", "rainforests", "tundra"], "It is a major food exporter despite its small size."],
  ["Prairie farms in Canada and the United States produce much…", "wheat and other grains", ["bananas", "coffee beans", "tea"], "The Prairies are a major grain region."],
  ["Brazil is a major producer of…", "coffee and soybeans", ["tulips", "cranberries", "maple syrup"], "These are important crops in Brazil."],
  ["Food distribution is the…", "moving of food from where it is grown to where it is eaten", ["growing of food", "cooking of food", "tasting of food"], "It includes trucks, trains, ships and stores."],
  ["Food miles measure…", "how far food travels from farm to plate", ["how much food costs", "how big a farm is", "how ripe the fruit is"], "Shorter distances can mean less pollution."],
  ["Buying food grown nearby can…", "support local farmers and reduce transportation", ["increase travel distance", "raise pollution", "end farming"], "Local food has benefits.", true],
  ["Indigenous peoples in the Americas have approaches to land use that often emphasize…", "caring for the land for future generations", ["using up everything quickly", "ignoring the land", "selling all land"], "Many communities teach respect and stewardship.", true],
  ["Mining, forestry and farming are different ways of using…", "natural resources", ["clocks", "maps", "flags"], "Societies make choices about land and resources."],
  ["The Industrial Revolution began in…", "Great Britain in the 1700s", ["Japan in 1500", "Canada in 1950", "Brazil in 1200"], "Machines and factories changed how goods were made.", true],
  ["European colonization of the Americas continues to affect societies today through…", "land, languages, borders and relationships with Indigenous peoples", ["only food", "only clothes", "nothing"], "History shapes the present.", true],
  ["Which economic activity is important in many European countries?", "manufacturing and services such as banking and tourism", ["only whaling", "only desert farming", "only hunting"], "Economies are diverse."],
  ["Which economic activity is important in the Prairie provinces?", "agriculture and energy", ["pearl diving", "volcano tours", "rainforest logging"], "Grain and oil are significant here."],
];

export const europeAndAmericas = bankUnit({
  id: "mb-7-europe-americas",
  title: "Europe & the Americas",
  emoji: "🧭",
  blurb: "Places, land use, food and history",
  parentNote: "Children locate major places in Europe and the Americas and explore land and resource use, human impact on the environment, major economic activities, food production and historical events that still matter today.",
  standards: ["7-KL-024, 7-KL-028, 7-KL-029, 7-KH-031, 7-KE-050, 7-KE-052, 7-VL-008", "major places in Europe and the Americas, land and resource use, human impact on the environment, historical events, economic activities, food production and the diversity of the natural environment"],
  items: EUROPE_AMERICAS,
});

const GLOBAL: Q[] = [
  ["The Olympic Games bring together athletes from…", "countries around the world", ["only one country", "only Europe", "only students"], "International sporting events build understanding among peoples."],
  ["A world’s fair or Expo shows…", "inventions, art and culture from many countries", ["only farm tools", "only sports", "only maps"], "Expositions share ideas and achievements."],
  ["The Nobel Prizes are awarded for achievements such as…", "peace, science and literature", ["racing", "cooking", "fishing"], "They recognize contributions to humanity."],
  ["Film, music and literary festivals help build understanding by…", "sharing stories and cultures across borders", ["keeping cultures apart", "avoiding art", "ending trade"], "The arts connect people."],
  ["Malala Yousafzai is known for…", "speaking up for girls’ education and winning a Nobel Peace Prize", ["inventing the lightbulb", "exploring Antarctica", "writing a dictionary"], "She is from Pakistan."],
  ["Wangari Maathai of Kenya is known for…", "founding the Green Belt Movement that planted millions of trees", ["building roads", "flying planes", "inventing phones"], "She won the Nobel Peace Prize in 2004."],
  ["Nelson Mandela is known for…", "working to end apartheid in South Africa", ["discovering Australia", "founding the Red Cross", "inventing television"], "He became president of South Africa."],
  ["Mother Teresa is known for…", "caring for people in need in India", ["building the Panama Canal", "founding Olympic Games", "leading a pirate crew"], "She won the Nobel Peace Prize in 1979."],
  ["Terry Fox is remembered for…", "running his Marathon of Hope to raise money for cancer research", ["climbing Everest", "sailing around the world", "inventing the telephone"], "He was a Canadian from Manitoba."],
  ["The Red Cross and Red Crescent help people by…", "giving aid during disasters and wars", ["selling goods", "building skyscrapers", "making films"], "They are international humanitarian organizations."],
  ["Mennonite Central Committee (MCC) is an agency that…", "works for relief, development and peace around the world", ["makes video games", "trains athletes", "runs airlines"], "MCC has an office in Winnipeg."],
  ["UNICEF works to protect…", "children’s rights and well-being", ["only sports teams", "only airlines", "only banks"], "It is part of the United Nations."],
  ["Doctors Without Borders (Médecins Sans Frontières) provides…", "medical care to people in crises around the world", ["school supplies only", "food recipes only", "sports equipment only"], "Doctors and nurses work in conflict and disaster zones."],
  ["A humanitarian is a person who…", "works to improve the lives of others", ["collects stamps", "makes only money", "plays sports only"], "They help people in need."],
  ["The United Nations was founded in…", "1945", ["1845", "1915", "1995"], "It works for peace, security and human rights."],
  ["Discrimination means…", "treating people unfairly because of who they are", ["welcoming everyone", "sharing food", "listening to music"], "It harms individuals and communities."],
  ["Showing concern for people affected by injustice can include…", "speaking up, learning, and supporting fair treatment", ["ignoring it", "making fun", "doing nothing"], "Caring leads to action."],
  ["Which action shows a willingness to contribute to your community?", "volunteering to help at a food bank", ["staying away from everyone", "complaining only", "keeping all you have"], "Contributions can be big or small."],
  ["Which action supports quality of life for people around the world?", "donating to a reliable aid group or fundraising for clean water projects", ["refusing to learn about others", "throwing away food", "ignoring news"], "Even students can help."],
  ["A class could take action on global poverty by…", "organizing a fundraiser for a trusted charity", ["making fun of the issue", "ignoring it", "writing nothing"], "Choose a trustworthy group."],
  ["Studying history helps us understand today because…", "events in the past shape present-day societies", ["history has no link to today", "history never changes", "history is only dates"], "The past explains the present."],
  ["The Nobel Peace Prize honours…", "people and groups who work for peace", ["the fastest runners", "the best inventors of machines", "the tallest builders"], "It recognizes peacemakers and humanitarians.", true],
  ["The Nobel Peace Prize is awarded in…", "Oslo, Norway", ["Winnipeg, Canada", "Tokyo, Japan", "Nairobi, Kenya"], "Other Nobel Prizes are awarded in Stockholm, Sweden.", true],
  ["Greta Thunberg is known for…", "starting school strikes for action on climate change", ["curing diseases", "inventing the internet", "leading the Red Cross"], "She is from Sweden."],
  ["International agencies are valuable because they…", "can organize help across many countries", ["only help one town", "avoid people in need", "make laws for kids"], "They share resources and expertise."],
  ["Which statement shows appreciation for individuals who influence world affairs?", "Their actions can inspire others to help", ["They have no effect", "They should be ignored", "Only governments matter"], "Individuals can make a difference."],
  ["Respecting someone else’s right to express their view means…", "listening even when you disagree", ["shouting them down", "making fun", "walking away"], "A key part of democratic life."],
  ["Why are different points of view important in a global issue?", "They help us see the whole picture", ["They make it simpler", "They make it confusing", "They stop discussion"], "Understanding takes many views.", true],
  ["Which might be an example of appreciating the diversity of the global natural environment?", "learning how rainforests, deserts and tundra support different life", ["thinking all places are the same", "avoiding nature", "ignoring habitats"], "Different regions have different life."],
  ["Why do aid agencies often work in many countries at once?", "Disasters and needs can happen anywhere, so help must travel", ["Because they dislike home", "Because they sell products", "Because they only help tourists"], "International agencies share resources and expertise.", true],
  ["Taking part in a school food drive shows…", "willingness to contribute to a group or community", ["unwillingness to share", "a lack of interest", "a refusal to help"], "Small acts add up."],
];

export const globalCitizens = bankUnit({
  id: "mb-7-global-citizens",
  title: "Global Citizens",
  emoji: "🕊️",
  blurb: "People and groups that make the world better",
  parentNote: "Children learn about events, individuals and agencies that build understanding among nations and improve quality of life, and how they can contribute to their communities and the world.",
  standards: ["7-KG-033, 7-KP-042, 7-VC-003, 7-VC-004, 7-VG-011, 7-VH-010, 7-VP-013, 7-VP-014", "events that build understanding, individuals and agencies that influence world affairs, contributing to communities, concern for injustice and the value of history"],
  items: GLOBAL,
});

const RESEARCH: Q[] = [
  ["A primary source is…", "a record made by someone who was there at the time", ["a textbook written years later", "a summary of a summary", "a guess"], "Diaries, photographs and letters are primary sources."],
  ["Which is a primary source about the Red River Flood of 1997?", "a photograph taken during the flood", ["a school textbook", "an encyclopedia article", "a movie made years later"], "A photo taken at the time is a firsthand record."],
  ["A secondary source is…", "a source that describes or interprets events after they happened", ["a diary from the time", "an original photo", "a letter from the time"], "Textbooks and documentaries are secondary sources."],
  ["Which is a secondary source?", "an encyclopedia entry", ["a soldier’s diary", "a treaty document", "an original map from 1800"], "It summarizes information from other sources."],
  ["Which source is best for the population of a country this year?", "a recent government statistics website", ["a storybook", "a poster from 1950", "a joke"], "Use sources with accurate, current data."],
  ["An atlas is mainly used to find…", "maps and geographic information", ["recipes", "spellings", "poems"], "It shows places, features and boundaries."],
  ["A good way to start a research inquiry is to…", "write questions and plan what you need to find out", ["copy the first website", "begin writing the conclusion", "ask nobody"], "Plan topics, goals and methods."],
  ["Which research question is the most focused?", "How do monsoon rains affect farming in India?", ["Tell me about Asia.", "What is everything?", "Is Earth big?"], "A focused question guides your search."],
  ["Which step comes after you find information in a source?", "Record and organize it in notes or a chart", ["Forget it", "Copy the whole page", "Throw it away"], "Organizing helps you use what you found."],
  ["Which is a good way to organize information about three countries?", "a chart with columns for each country", ["one long paragraph", "a list of random words", "a picture only"], "Charts help compare."],
  ["A concept map shows…", "how ideas connect to each other", ["only dates", "only names", "only numbers"], "Boxes and lines link ideas."],
  ["A bibliography or reference list tells readers…", "which sources you used", ["how long you worked", "your favourite colour", "your age"], "It credits the people whose work you used."],
  ["Why should you give credit to your sources?", "It shows honesty and lets others check your facts", ["It makes the report longer", "It is not needed", "It hides where you found information"], "Referencing sources respects others’ work."],
  ["Which tool would help you make a map of your community?", "a mapping app or GIS", ["a thermometer", "a stopwatch", "a spring scale"], "GIS stands for geographic information system."],
  ["Which technology helps you search for information quickly?", "a search engine or online database", ["a hammer", "a paintbrush", "a compass"], "Choose tools that fit the job."],
  ["To draw a conclusion, you should base it on…", "the research and evidence you gathered", ["your guess", "what you wish were true", "a friend’s opinion only"], "Conclusions must be supported."],
  ["Which conclusion is supported by the evidence “The river flooded each spring, and farmers planted after the water went down”?", "Farmers adjusted their planting to the river’s seasons", ["The river never flooded", "Farmers did not plant", "The river dried up"], "The conclusion follows the evidence."],
  ["A photograph from 1920 shows a crowded city street. This is useful for…", "observing clothing, transport and buildings of that time", ["knowing today’s weather", "proving a story is false", "naming future leaders"], "Photographs are visual evidence."],
  ["When you analyze an artifact, you should ask…", "What is it, who made it, and what does it tell us?", ["How many pages does it have?", "What colour is the table?", "Is it for sale?"], "Observe and question evidence.", true],
  ["How can you tell if a website is a reliable source?", "Check who made it, why, and whether facts can be checked", ["See if it has many pictures", "See if it is colourful", "See if it is the first result"], "Check authenticity, purpose and evidence."],
  ["A website that ends in .gov is usually…", "run by a government", ["a game site", "a personal blog", "a store"], "Government sites often share official data."],
  ["Which source is most likely to be reliable about a scientific fact?", "a science museum or university website", ["an anonymous post", "an advertisement", "a rumour"], "Experts and evidence make a source reliable."],
  ["When you check if information is valid, which question helps?", "Who wrote this and what is their purpose?", ["What colour is the font?", "Is the title long?", "Does it have a picture?"], "Purpose and origin matter."],
  ["Objectivity in a source means it…", "presents information without letting personal feelings or interests distort it", ["is always short", "is always about science", "is always written by a child"], "Objective sources try to be fair.", true],
  ["A source is more reliable when…", "its facts are supported by evidence and can be checked elsewhere", ["it is the longest", "it uses the most exclamation marks", "it is the newest ever"], "Corroboration builds trust."],
  ["Interpreting a song or work of art from the past can help you understand…", "what people thought and felt at that time", ["only the cost of paint", "how to read a map", "tomorrow’s weather"], "Art and music are evidence."],
  ["A historical fiction novel can help you understand a time period, but you should remember it is…", "partly imagined, so check facts in other sources", ["always completely true", "a primary source", "a map"], "Fiction mixes real and invented details."],
  ["A drama or play can be a source for…", "ideas and feelings of the time it was written", ["exact statistics always", "map scales", "recipes only"], "Interpret ideas in media carefully.", true],
  ["Interpretations of history can change as…", "new information is found or acknowledged", ["old facts vanish for no reason", "people stop asking questions", "nothing is ever discovered"], "History is a conversation that grows.", true],
  ["Why might a history textbook written in 1950 differ from one written today?", "Historians have found new evidence and included more voices", ["The past changed", "Books are all the same", "There are no historians"], "Understanding of history develops.", true],
  ["An example of an interpretation changing is when…", "voices that were once left out are included in the story", ["a date is spelled wrong", "a book is printed on new paper", "the title is shortened"], "More perspectives give a fuller story.", true],
];

export const researchSkills = bankUnit({
  id: "mb-7-research-skills",
  title: "Research Skills",
  emoji: "🔎",
  blurb: "Find, check and organize good information",
  parentNote: "Children practise planning an inquiry, choosing and checking sources, telling primary from secondary sources, organizing information and drawing conclusions from evidence.",
  standards: ["7-S-200, 7-S-201, 7-S-202, 7-S-203, 7-S-300, 7-S-302, 7-S-305, 7-S-306, 7-S-309, 7-S-310", "selecting, recording and interpreting sources, tools and technologies, planning inquiry, drawing conclusions, evaluating sources and understanding that interpretations of history can change"],
  items: RESEARCH,
});

const BIAS: Q[] = [
  ["A fact is…", "a statement that can be proven true", ["a feeling", "a guess", "a rumour"], "Facts can be checked."],
  ["An opinion is…", "a belief or feeling that cannot be proven right or wrong", ["a proven number", "a date", "a measurement"], "Opinions depend on a person’s thoughts."],
  ["Which statement is a fact?", "Winnipeg is the capital of Manitoba.", ["Winnipeg is the prettiest city.", "Winnipeg has the best parks.", "Everyone loves winter in Winnipeg."], "You can check it in an atlas."],
  ["Which statement is an opinion?", "Soccer is the most exciting sport.", ["Soccer is played with a round ball.", "A soccer team has 11 players on the field.", "Soccer is played on a field."], "“Most exciting” is a judgement."],
  ["An interpretation is…", "an explanation of what evidence means", ["a number", "a map symbol", "a date"], "Interpretations can differ."],
  ["Bias is…", "a leaning for or against something that can make a view unfair", ["a kind of map", "a type of graph", "a measurement tool"], "Bias can be hard to notice."],
  ["Stereotyping means…", "applying a simple, fixed idea to everyone in a group", ["studying carefully", "writing a poem", "creating a map"], "Stereotypes ignore individual differences."],
  ["Prejudice is…", "an unfair opinion formed without enough knowledge", ["a proven fact", "a measurement", "a law"], "It means judging before knowing."],
  ["Racism is…", "treating people unfairly because of their race", ["a type of weather", "a form of art", "an economic term"], "It harms people and communities."],
  ["A news story calls one group “heroes” and another “thugs” without evidence. This shows…", "bias in word choice", ["balanced reporting", "a measurement error", "a map"], "Loaded words can show a one-sided view."],
  ["Which headline sounds more balanced?", "Residents and city council disagree on plan", ["Council ruins neighbourhood", "Residents lie about plan", "Council always right"], "Balanced headlines do not take a side."],
  ["A cartoon shows all members of a country as the same stereotype. What should you think?", "It might be unfair, so I should look for other sources", ["It must be true", "I should repeat it", "I should ignore all cartoons"], "Check for stereotypes in media."],
  ["To compare viewpoints on a global issue, you should…", "read or listen to several sources with different perspectives", ["use one source only", "ask one friend", "trust the first result"], "More perspectives give a fuller picture."],
  ["Two newspapers describe the same event differently. The best response is to…", "compare them and check other sources", ["pick the one you like", "ignore both", "decide immediately"], "Evaluate multiple views."],
  ["A solution is evaluated by weighing its…", "advantages and disadvantages", ["colour", "name", "length"], "Consider the pros and cons."],
  ["An advantage of a bike lane is that it…", "makes cycling safer", ["makes roads wider for cars only", "removes bike parking", "increases noise"], "Think about benefits."],
  ["A disadvantage of a new road could be that it…", "uses up natural habitat", ["makes travel faster", "connects towns", "creates jobs"], "Think about costs and trade-offs."],
  ["Evaluating personal assumptions means…", "checking whether your own beliefs are supported by evidence", ["never changing your mind", "ignoring facts", "agreeing with everyone"], "Be willing to think again."],
  ["You assumed a faraway place has no cities, then learn it has several large ones. A good response is to…", "change your assumption based on the new information", ["ignore the new fact", "argue", "say the facts are wrong"], "New information can change our ideas."],
  ["Which question helps you spot bias in a source?", "Who made it, and might they want me to think a certain way?", ["How long is it?", "Is it in colour?", "What page is it on?"], "Ask about the creator’s purpose."],
  ["Advertising is often biased because it…", "is designed to persuade you to buy something", ["is always false", "has no pictures", "is always scientific"], "Ads show a product in its best light."],
  ["A photograph can show bias if it…", "shows only one part of a scene", ["has colour", "is large", "is printed"], "What is left out matters.", true],
  ["Social media posts often show only…", "what the poster chooses to share", ["everything that happened", "every opinion", "official facts only"], "Check before trusting what you see.", true],
  ["Why is it important to analyze prejudice in the media?", "Unfair messages can shape how people see others", ["Media has no effect", "It is boring", "It makes media shorter"], "Media influences beliefs."],
  ["If you notice a stereotype in a movie, you can…", "talk about it and look for more accurate stories", ["accept it", "share it", "pretend it is true"], "Recognize and respond.", true],
  ["How can you propose solutions to discrimination at school?", "Learn about it, speak up and support fair rules", ["ignore it", "join in", "hide it"], "Solutions start with awareness and action."],
  ["Heterosexism, ageism and racism are all examples of…", "bias and discrimination", ["kinds of weather", "forms of art", "scientific tools"], "Each treats people unfairly because of who they are."],
  ["Ageism means…", "treating people unfairly because of their age", ["liking all ages", "measuring age", "counting birthdays"], "Both young and old people can face ageism."],
  ["A fair way to tell a story about a conflict is to…", "include the perspectives of all sides involved", ["only tell one side", "leave out facts", "use insults"], "Fair reporting respects all people."],
  ["Which sentence combines a fact with an interpretation?", "The village shrank by half in ten years, which suggests many people moved to cities.", ["The village is the best.", "I hate that village.", "Villages are boring."], "The interpretation is supported by the fact.", true],
  ["A history book from long ago leaves out the stories of women and Indigenous peoples. What can today’s readers do?", "look for newer sources that include more voices", ["assume nothing else happened", "ignore history", "trust the book fully"], "Search for perspectives that were missing.", true],
];

export const biasAndViewpoints = bankUnit({
  id: "mb-7-bias-viewpoints",
  title: "Bias & Viewpoints",
  emoji: "⚖️",
  blurb: "Fact, opinion, bias and comparing perspectives",
  parentNote: "Children practise telling fact from opinion, recognizing bias, prejudice and stereotypes in the media, comparing viewpoints and thinking about solutions.",
  standards: ["7-S-105, 7-S-301, 7-S-303, 7-S-304, 7-S-307, 7-S-308, 7-S-311", "recognizing bias and discrimination, evaluating solutions and assumptions, fact versus opinion, comparing viewpoints and analyzing media bias"],
  items: BIAS,
});

const TOGETHER: Q[] = [
  ["Two group members disagree about the topic. A fair first step is to…", "listen to each person’s reason", ["decide without asking", "ignore one person", "leave the group"], "Clarification comes before solutions."],
  ["Which sentence is a respectful way to disagree?", "I see it differently. Can I explain?", ["You’re wrong.", "That’s silly.", "I’m not listening."], "Disagree with the idea, not the person."],
  ["Negotiation means…", "talking to reach an agreement that works for everyone", ["demanding your own way", "ending the conversation", "giving up"], "Each person gives something."],
  ["Compromise means…", "each side gives up a little to find a solution", ["one side wins everything", "no one agrees", "nothing is decided"], "Both sides adjust."],
  ["Two groups both want the one computer. A fair compromise is…", "each group takes a time slot", ["the loudest group gets it", "no one uses it", "the teacher decides without talking"], "Sharing is fair."],
  ["Building consensus means…", "working toward an agreement most members can support", ["a vote that ignores people", "the leader decides alone", "the loudest person wins"], "Everyone’s views are considered."],
  ["Clarification in a conflict helps because it…", "makes sure each person understands the other’s point", ["adds confusion", "makes it longer", "avoids problems"], "Misunderstandings often cause conflict."],
  ["What should you do if you and a friend both want the same role in a group project?", "Talk it over and find a fair way, such as taking turns", ["Grab the role", "Quit the project", "Complain to everyone"], "Peaceful problem-solving."],
  ["Making a decision that reflects fairness means…", "considering everyone’s needs and treating people equally", ["choosing your friends", "choosing the easiest idea", "ignoring some people"], "Fairness is about equal treatment."],
  ["Which choice shows fairness in a game?", "Everyone gets a turn", ["Only the best players play", "Some players are left out", "Rules change for some"], "Fair games include everyone."],
  ["Collaboration means…", "working together toward shared goals", ["working alone", "competing against group members", "ignoring a team"], "Teams share responsibilities."],
  ["In a group, setting goals and responsibilities helps because…", "everyone knows what to do", ["it makes work longer", "it avoids work", "it removes choices"], "Clear roles help teams."],
  ["A group member is not doing their part. A respectful response is to…", "talk to them kindly and ask how the group can help", ["tell everyone about it", "do nothing", "shout"], "Address problems respectfully."],
  ["Listening to understand another’s perspective means…", "paying attention to what they think and why", ["thinking about what to say next", "interrupting", "looking away"], "Understanding comes first."],
  ["Which words are respectful of human diversity?", "people with disabilities", ["handicapped people", "those people", "weird people"], "People-first language respects individuals."],
  ["Which statement shows respectful language?", "Our class has students from many cultures.", ["Those foreign kids don’t belong.", "Everyone should be the same.", "Don’t talk like that."], "Respectful language includes everyone."],
  ["When you want to persuade others about an issue, you should…", "give clear reasons and evidence", ["shout", "insult them", "refuse to explain"], "Persuasive expression uses reasons."],
  ["A good argument for a school recycling program includes…", "facts about how much waste is produced and saved", ["only complaints", "only jokes", "no reasons"], "Evidence makes a view persuasive."],
  ["Presenting information in a poster, a talk or a slideshow are all ways to…", "share ideas with others", ["hide ideas", "avoid questions", "stop learning"], "Choose the way that fits your audience."],
  ["Which format is best to show a timeline of events?", "a labelled timeline", ["a pie chart of colours", "a poem only", "a blank page"], "Format should fit the information."],
  ["Which would be a good way to show where something is found in the world?", "a map", ["a recipe", "a clock", "a spelling list"], "Maps show location."],
  ["When you ask a question in a discussion, it helps to…", "make it clear and polite", ["whisper", "make it a trick", "ask about something else"], "Clarity helps the group."],
  ["What is a good way to clarify an idea you did not understand?", "Ask, “Could you give an example?”", ["Say “whatever.”", "Pretend to understand.", "Interrupt loudly."], "Examples help."],
  ["Expressing your beliefs and perspectives in a respectful way means…", "stating your view clearly while allowing others to speak", ["talking over others", "forcing others to agree", "avoiding the topic"], "Share and listen."],
  ["Respecting others’ rights to express their views means…", "letting them share, even if you disagree", ["silencing them", "laughing at them", "leaving the room"], "A cornerstone of democracy.", true],
  ["Being willing to contribute to a group means…", "taking part and doing your share", ["waiting for others", "letting others do it all", "refusing tasks"], "Contributions matter."],
  ["A group votes on a class trip destination and your choice loses. A respectful response is to…", "accept the decision and help with the plan", ["complain all day", "refuse to go", "ask for a new vote forever"], "Good teammates accept fair results.", true],
  ["Which strategy helps resolve a conflict peacefully?", "taking a break to calm down, then talking", ["yelling", "name-calling", "ignoring the problem forever"], "Calm talk works better.", true],
  ["Including a shy classmate in a group discussion shows…", "fairness and respect", ["bossiness", "unfairness", "boredom"], "Everyone should have a chance to speak."],
  ["After a conflict is resolved, what is a good next step?", "check that everyone feels the solution is fair", ["pretend it never happened", "blame someone", "forget the solution"], "Follow up to be sure.", true],
];

export const workingTogether = bankUnit({
  id: "mb-7-working-together",
  title: "Working Together Fairly",
  emoji: "🤝",
  blurb: "Fair decisions, respectful talk and peaceful solutions",
  parentNote: "Children practise group skills: setting goals, resolving conflicts peacefully, negotiating, listening to understand, using respectful language and sharing their views.",
  standards: ["7-S-100, 7-S-101, 7-S-102, 7-S-104, 7-S-400, 7-S-401, 7-S-402, 7-S-403, 7-S-404, 7-S-405, 7-VC-003, 7-VI-005", "working with others, resolving conflicts, fair decisions, listening, respectful language, persuasive expression, presenting and respecting others' points of view"],
  items: TOGETHER,
});

const LAND: Q[] = [
  ["A compass rose on a map shows…", "the directions", ["the scale", "the title", "the date"], "N, S, E and W."],
  ["The four cardinal directions are…", "north, south, east and west", ["up, down, left and right", "front, back, top and bottom", "inside, outside, over and under"], "They are the main directions on a compass."],
  ["Which direction is between north and east?", "northeast", ["southwest", "northwest", "southeast"], "Combine the two directions."],
  ["The needle of a magnetic compass points toward…", "magnetic north", ["south", "east", "the Sun"], "It lines up with Earth’s magnetic field."],
  ["At night in the Northern Hemisphere, the star Polaris (the North Star) helps people find…", "north", ["south", "the time of day", "the nearest city"], "It stays almost directly above the North Pole."],
  ["On a map, the legend (or key) explains…", "what the symbols mean", ["the weather", "the history", "the author’s age"], "Symbols stand for features."],
  ["A map scale shows…", "how distances on the map compare with real distances", ["the colours", "the direction", "the year"], "For example, 1 cm may equal 10 km."],
  ["If 1 cm on a map equals 10 km, how far is 3 cm?", "30 km", ["13 km", "3 km", "300 km"], "3 × 10 = 30."],
  ["Which should a map always have so people know what it shows?", "a title", ["a joke", "a signature", "a price"], "The title says what the map is about."],
  ["A thematic map focuses on…", "one topic, such as population or climate", ["only roads", "all topics at once", "only borders"], "It shows a theme."],
  ["GPS stands for…", "Global Positioning System", ["Great Planet Survey", "Grid Point Scale", "Geographic Print Sheet"], "It uses satellites to find a location."],
  ["GIS stands for…", "Geographic Information System", ["Global Image Service", "Grid Index Scale", "General Information Screen"], "It stores and analyzes map data."],
  ["A GPS device or phone map can tell you…", "where you are on Earth", ["what you will eat", "tomorrow’s test", "your grade"], "It uses satellites."],
  ["Observation as a way to make a map means…", "walking and noting what you see, such as landmarks and trails", ["guessing", "copying a friend", "using no information"], "Careful observation gives information."],
  ["Which would you use to orient yourself if you are lost in a forest and have a compass?", "check the direction and compare it with your map", ["spin around", "walk randomly", "climb a tree"], "Use tools and landmarks."],
  ["What helps you orient yourself in a city without a compass?", "street signs, landmarks and a map", ["closing your eyes", "guessing", "asking no one"], "Use what you can see."],
  ["The Sun rises in the…", "east", ["west", "north", "south"], "It sets in the west."],
  ["A landmark is…", "a notable feature that helps you find your way", ["a type of map", "a unit", "a symbol"], "Examples are hills, rivers and tall buildings."],
  ["Traditional Knowledge is…", "knowledge passed down in a community over many generations", ["a computer program", "a new invention", "a rumour"], "Knowledge Keepers share it with care."],
  ["Many First Nations, Métis and Inuit peoples today still use Traditional Knowledge to…", "observe the land, water and weather", ["avoid learning", "read computer code only", "ignore the seasons"], "These ways of knowing continue."],
  ["An inuksuk is a stone structure built by Inuit that can…", "mark a place or help people find their way", ["power machines", "make music", "measure temperature"], "Inuit have built inuksuit for guidance and other purposes."],
  ["To read the land, people can notice…", "tracks, plants, water, wind and the shape of the land", ["only the date", "only the radio", "only a clock"], "Close observation gives information."],
  ["Learning from the land is often done with…", "guidance from Elders and Knowledge Keepers", ["no one", "a stranger online", "a game"], "Respect those who hold knowledge.", true],
  ["When a Knowledge Keeper shares teachings, it is respectful to…", "listen carefully and ask permission before sharing them", ["record without asking", "share it as your own", "change it"], "Teachings belong to the people who share them.", true],
  ["A burial ground is a place that should be…", "treated with respect and not disturbed", ["dug up for fun", "used as a playground", "ignored"], "Some places are sacred or protected."],
  ["You find an old arrowhead on a trail. The respectful action is to…", "leave it where it is and tell an adult or local authority", ["take it home", "sell it", "break it"], "Artifacts tell stories that depend on where they are found.", true],
  ["Why should memorials be treated with respect?", "They honour people and events that matter to communities", ["They are just stones", "They are for decoration", "They have no meaning"], "Respect for places of significance."],
  ["Which is a respectful way to visit a historic site?", "staying on paths and not touching or removing objects", ["climbing on walls", "carving your name", "taking souvenirs"], "Protect places for others.", true],
  ["Why do museums handle artifacts carefully?", "Damage or loss can erase information about the past", ["to make them dirtier", "to hide them", "because artifacts are toys"], "Artifacts are fragile evidence.", true],
  ["When you create a map of your school, the first step is to…", "decide what you want the map to show", ["colour it", "name it", "frame it"], "Purpose guides the map.", true],
];

export const readingTheLand = bankUnit({
  id: "mb-7-reading-the-land",
  title: "Maps, Land & Respect",
  emoji: "🧭",
  blurb: "Make maps, find your way and respect special places",
  parentNote: "Children practise map-making and orientation with compasses, landmarks and GPS, learn that Traditional Knowledge is used to read the land, and show respect for places and objects of historical significance.",
  standards: ["7-S-106, 7-S-204, 7-S-207A, 7-S-208", "treating places of historical significance with respect, creating maps, using Traditional Knowledge to read the land, and orienting oneself"],
  items: LAND,
});
