import { bankUnit, type Q } from "../own";

// More Grade 7 English language arts (Manitoba): reading strategies, critical reading, the writing process and text
// forms, word choice and voice, capitals and formatting, multimodal design, and reflecting on learning.

const READING_STRATEGIES: Q[] = [
  ["Before reading an article titled “How Beavers Build Dams”, you think about a beaver lodge you once saw. This is…", "using prior knowledge", ["summarizing", "skimming for spelling", "proofreading"], "Prior knowledge is what you already know from experience."],
  ["Which is the best way to use prior knowledge before reading?", "Ask yourself what you already know about the topic", ["Skip to the last page", "Copy the first paragraph", "Count the words"], "Thinking about what you know helps new facts make sense."],
  ["A text about the Red River Flood is easier to follow if you first…", "recall what you know about floods", ["memorize the title", "read only the last line", "look for rhyming words"], "Background knowledge helps you understand new text."],
  ["You read the title “The Mystery of the Missing Map” and guess the story is about a search. This is…", "making a prediction", ["writing a summary", "finding the theme", "editing"], "A prediction is a smart guess based on clues."],
  ["Which clue best supports a prediction about what happens next?", "details and events already in the text", ["the page number", "the font size", "the length of the book"], "Predictions come from background knowledge plus text information."],
  ["While reading, you find out your prediction was wrong. What should you do?", "Change the prediction using the new information", ["Ignore the new information", "Stop reading", "Skip the chapter"], "Good readers change their predictions as they learn more."],
  ["Which question helps you check a prediction while you read?", "Does this match what I thought would happen?", ["How many pages are left?", "Who printed the book?", "What colour is the cover?"], "Ask questions that test your prediction."],
  ["After reading, you ask “Why did the character choose to stay?” This is…", "posing a question about the text", ["a prediction before reading", "a spelling check", "a heading"], "Readers ask questions before, during and after reading."],
  ["A story about moving to a new school reminds you of your own first day somewhere new. This is a…", "text-to-self connection", ["text-to-text connection", "text-to-world connection", "summary"], "You are linking the text to your own experience."],
  ["A novel about a flood reminds you of a news story about a real flood. This is a…", "text-to-world connection", ["text-to-self connection", "text-to-text connection", "rhyme"], "You are linking the text to events in the world."],
  ["Two stories both have a clever fox who tricks others. Noticing this is a…", "text-to-text connection", ["text-to-self connection", "text-to-world connection", "prediction"], "You are linking one text to another text."],
  ["Why do connections help you read?", "They help you understand and remember what you read", ["They make the text shorter", "They change the author’s words", "They fix spelling"], "Connecting new ideas to what you know builds understanding."],
  ["Watching a documentary about wolves before reading an article about them helps because it…", "builds background knowledge", ["replaces the article", "changes the facts", "ends your questions"], "Different kinds of text on one topic deepen understanding."],
  ["Which is a multimodal text?", "a website with text, photos and a video", ["a page of plain text", "a list of spelling words", "a single sentence"], "Multimodal text mixes words, images, sound or video."],
  ["Reading a magazine article and then viewing a video on the same topic helps you…", "see the topic in more than one way", ["avoid reading", "memorize both", "ignore the facts"], "Different kinds of text show different sides of a topic."],
  ["You finish an article and notice you still do not know how the bridge was built. What should you do?", "Find more information from another source", ["Guess and move on", "Stop thinking about it", "Copy the title"], "Noticing a gap means you need to look for more information."],
  ["A good summary of an article includes…", "the main ideas, without your opinions", ["every detail", "your opinion of the author", "only the title"], "A summary is short and sticks to the text."],
  ["Which sentence belongs in a summary and not in an opinion?", "The article explains how wetlands clean water.", ["I think wetlands are boring.", "Wetlands are the best places ever.", "The author should have written more."], "Summaries report what the text says."],
  ["When you use information from two articles in your report, you should…", "say which source each fact came from", ["hide where it came from", "copy whole paragraphs", "use only the longer one"], "Citing evidence from your sources shows where facts came from."],
  ["After learning about the Solar System, which is a good way to use discipline-specific vocabulary?", "Use words like orbit and gravity when you explain", ["Use only everyday words", "Avoid science words", "Make up new words"], "Subject words help you explain ideas precisely."],
  ["How can your own experiences shape the way you read a text?", "They can change which parts seem important to you", ["They change the words printed", "They change the author", "They cannot affect it"], "Two readers can notice different things.", true],
  ["Two readers read the same poem about winter. One loves skating and one dislikes the cold. Why might their interpretations differ?", "Their experiences are different", ["The poem changed", "One of them cannot read", "Poems have no meaning"], "Experiences shape interpretation.", true],
  ["Reading with expression, accurate words and a steady rate is called…", "fluency", ["plot", "theme", "setting"], "Fluent reading sounds smooth and natural."],
  ["Which helps build reading fluency?", "Rereading a passage aloud several times", ["Reading as fast as you can without looking", "Skipping hard words", "Reading only the headings"], "Practice with accuracy, expression and rate improves fluency."],
  ["A reader pauses at commas and periods and changes voice for a question. Which fluency skill is this?", "expression", ["rate only", "spelling", "handwriting"], "Expression follows the meaning and punctuation."],
  ["You come to an unfamiliar word in a paragraph. Which fluency strategy helps first?", "Break it into parts and reread the sentence", ["Skip the whole page", "Give up", "Guess a random word"], "Sounding out parts and rereading helps accuracy and meaning."],
  ["If you read too quickly and make many mistakes, you should…", "slow down so you read accurately", ["read even faster", "stop reading", "skip punctuation"], "Accuracy matters as much as speed."],
  ["A reader who stops after each paragraph to check “Does this make sense?” is…", "monitoring comprehension", ["proofreading", "brainstorming", "illustrating"], "Good readers check their understanding as they go.", true],
  ["Which question best builds a prediction before reading a non-fiction chapter?", "What do the headings and pictures suggest it will teach?", ["How many words does it have?", "Who sat beside me?", "What is the last word?"], "Text features give clues about what is coming.", true],
];

export const readingStrategies = bankUnit({
  id: "mb-7-reading-strategies",
  title: "Reading Strategies",
  emoji: "🔍",
  blurb: "Predict, connect, question and summarize",
  parentNote: "Children practise strategies good readers use: drawing on what they know, predicting, connecting, summarizing and reading fluently.",
  standards: ["ELA.7.A2.6, ELA.7.B1.1, ELA.7.B1.3, ELA.7.B1.4, ELA.7.B2.3, ELA.7.B2.4, ELA.7.B2.7", "fluency, prior knowledge, multimodal text, gathering and summarizing information, predictions, connections and new vocabulary"],
  items: READING_STRATEGIES,
});

const CRITICAL: Q[] = [
  ["A stereotype is…", "an oversimplified idea about a whole group of people", ["a true fact about one person", "a kind of rhyme", "a type of paragraph"], "Stereotypes treat everyone in a group as the same."],
  ["Which sentence is an example of a stereotype?", "All teenagers are lazy.", ["Mia plays hockey on Saturdays.", "Some teens volunteer at shelters.", "Leo likes science."], "“All” makes a claim about a whole group."],
  ["Why can stereotypes in a story be harmful?", "They give a false, unfair picture of people", ["They make the story longer", "They add rhyme", "They improve the plot"], "Unfair pictures can hurt people and spread wrong ideas."],
  ["You read a story where the only girl in the group is always scared. Your best response is…", "I notice this treats girls unfairly, and the text only shows one side", ["I agree because stories are always right", "I will skip all stories", "I will copy it in my own"], "Notice it, and use evidence from the text to explain."],
  ["Discriminatory language is language that…", "treats people unfairly because of who they are", ["uses long words", "uses rhyme", "describes the weather"], "It puts people down because of race, gender, ability or other traits."],
  ["Which word choice is more inclusive?", "firefighter", ["fireman", "fire guy", "fire boy"], "Words that fit everyone include everyone."],
  ["Which sentence uses inclusive language?", "Everyone is welcome at the assembly.", ["Only the best kids may come.", "Boys will be bored here.", "Girls can sit at the back."], "Inclusive language makes everyone feel they belong."],
  ["A one-sided view in an article means it…", "shows only one point of view", ["has too many facts", "is very short", "uses headings"], "A balanced text shows more than one side."],
  ["An article about a new park talks only about the benefits and never mentions the cost. This text is…", "one-sided", ["balanced", "a poem", "a recipe"], "It leaves out information that could change your opinion."],
  ["How can you show a response to unfair representation in a text?", "Point to the words that show it and explain why they are unfair", ["Say you dislike the font", "Change the title", "Ignore it"], "Support your response with evidence from the text."],
  ["An author’s purpose is…", "the reason the author wrote the text", ["the length of the text", "the title of the book", "the number of chapters"], "Authors write to inform, persuade, entertain or express."],
  ["A text about why everyone should recycle most likely has the purpose to…", "persuade", ["entertain with a joke", "describe a dream", "explain a recipe"], "It tries to convince readers to act."],
  ["A story that shows two characters being left out of a game because of their language might be about a broader issue of…", "fairness and inclusion", ["cooking", "weather", "maps"], "Social issues include race, gender, class and ability."],
  ["Which question helps you think about a social issue in a text?", "Who is treated fairly, and who is not?", ["How many words are in the title?", "Is there a map?", "What is the page number?"], "Ask about fairness and who has a voice."],
  ["Evidence from the text that shows tone includes…", "the words the author chooses", ["the cover colour", "the price", "the author’s age"], "Word choice shows how the author feels."],
  ["The author describes the playground as “cold, empty and silent”. The tone is…", "gloomy", ["cheerful", "silly", "excited"], "The words create a sad, quiet feeling."],
  ["Which structure helps an author show a social issue clearly?", "showing a problem and what happens because of it", ["a list of random words", "repeating one letter", "ending every line with a rhyme"], "Structure shows how ideas connect.", true],
  ["Two articles describe the same event. One calls the protest a “riot” and the other calls it a “peaceful gathering”. What does this show?", "Word choice can show the writer’s view", ["Only one is true", "Both are the same", "Neither is about the event"], "Loaded words reveal bias.", true],
  ["Whose voice is missing if a history text tells a story about a village only from the ruler’s point of view?", "the villagers’", ["the ruler’s", "the author’s", "the printer’s"], "Ask who is not heard.", true],
  ["What does it mean to “use text evidence”?", "Quote or point to words in the text that support your idea", ["Say what you feel without reading", "Copy the whole page", "Write the title again"], "Evidence comes from the text itself."],
  ["Respectful disagreement with a text sounds like…", "I see it differently because the text says…", ["That is dumb.", "Nobody should read this.", "I will not talk about it."], "Give reasons, and be kind."],
  ["How can the words we use shape a classroom?", "They can make people feel included or left out", ["They never matter", "They only matter in writing", "They only matter to teachers"], "Language shapes how people feel they belong."],
  ["A classmate says a game is “for boys only”. A fair response is…", "Suggest that anyone who wants to play can join", ["Agree and say nothing", "Laugh along", "Cancel the game for everyone"], "Gently speak up so everyone is included."],
  ["To change a group’s name in a poster so it includes everyone, you might change “guys” to…", "everyone", ["boys", "men", "gentlemen"], "A word that includes everyone fits all."],
  ["When you read a text with a view you disagree with, you should…", "read carefully and use evidence to explain your own view", ["stop reading", "change the text", "ignore the author"], "Understand first, then respond with reasons."],
  ["Which statement is a personal response backed by evidence?", "I felt upset because the text only shows one group speaking.", ["I did not like it.", "It is long.", "The author wrote it on a Tuesday."], "A good response names what in the text caused the feeling."],
  ["A poster shows only one kind of family. What question should you ask?", "Who is not shown here?", ["How big is the poster?", "Who printed it?", "Is the ink red?"], "Unfair representation leaves people out.", true],
  ["An advertisement says “Everyone knows our brand is best.” This is an example of…", "an unsupported claim", ["a fair comparison", "a proven fact", "a summary"], "“Everyone knows” gives no evidence.", true],
];

export const criticalReading = bankUnit({
  id: "mb-7-critical-reading",
  title: "Fair & Inclusive Texts",
  emoji: "🧐",
  blurb: "Spot stereotypes, one-sided views and inclusive language",
  parentNote: "Children practise noticing stereotypes, unfair or one-sided views and social issues in texts, responding with evidence, and choosing inclusive language.",
  standards: ["ELA.7.A1.3, ELA.7.B3.1, ELA.7.B3.4", "inclusive language, broader social issues in text and responding to stereotypes and one-sided views"],
  items: CRITICAL,
});

const WRITING: Q[] = [
  ["Which step usually comes first in the writing process?", "planning and gathering ideas", ["publishing", "proofreading", "printing"], "Writers plan before they draft."],
  ["Brainstorming is…", "listing many ideas quickly before you choose", ["fixing spelling", "making the final copy", "reading aloud"], "Brainstorming gets ideas flowing."],
  ["A graphic organizer helps a writer…", "sort and connect ideas before drafting", ["fix punctuation", "print the final copy", "choose a font"], "Organizers show how ideas fit together."],
  ["Which topic is focused enough for a one-page report?", "How honeybees make honey", ["Everything about animals", "The whole world", "All of science"], "A focused topic fits the size of the piece."],
  ["Why should a writer think about the audience?", "It helps choose words and details that fit readers", ["It decides the spelling", "It makes the text longer", "It chooses the paper"], "Writing for a younger audience sounds different from writing for a principal."],
  ["Which tool is best for planning a story with a beginning, middle and end?", "a story map", ["a Venn diagram", "a bar graph", "a calendar"], "A story map lays out characters, setting and events."],
  ["Which tool compares two things?", "a Venn diagram", ["a story map", "a timeline", "a web of one idea"], "Overlapping circles show how two things are alike and different."],
  ["Jot notes are…", "short notes of key words and facts", ["full paragraphs", "the final draft", "a list of titles"], "Jot notes save time while researching."],
  ["Which text form is best for telling a friend what happened on a trip in a personal, reflective way?", "a journal entry", ["a news report", "a recipe", "a poster"], "A journal records personal thoughts and events."],
  ["Which text form is meant to convince a reader to agree with you?", "a persuasive letter", ["a recipe", "a weather report", "a timetable"], "Persuasive forms use reasons to convince."],
  ["Which form usually answers who, what, where, when and why about an event?", "a news article", ["a poem", "a diary", "a menu"], "News articles report events."],
  ["A report is best used when you want to…", "give facts and information about a topic", ["tell a made-up story", "show a poem", "send a greeting"], "Reports inform readers."],
  ["A narrative is…", "a story with characters, setting and events", ["a list of facts", "a set of directions", "a chart"], "Narratives tell a story."],
  ["Which form would you use to explain how to make a paper airplane?", "procedural (how-to) writing", ["a poem", "a journal", "a narrative"], "How-to writing gives steps in order."],
  ["The conventions of a report include…", "headings and facts organized by topic", ["rhyme and verses", "dialogue only", "emojis only"], "Reports are organized by topic."],
  ["Which pattern of organization is a story told in time order?", "chronological sequence", ["cause and effect", "compare and contrast", "problem and solution"], "Chronological means in the order events happen."],
  ["Which organizational pattern explains why something happened and what resulted?", "cause and effect", ["chronological sequence", "description", "listing"], "Cause and effect links reasons to results."],
  ["Which signal words suggest a cause and effect pattern?", "because, as a result, therefore", ["first, next, then", "on the other hand, similarly", "for example, such as"], "These words connect causes to effects."],
  ["Which signal words suggest a time-order pattern?", "first, next, finally", ["because, so", "however, but", "in contrast"], "Time-order words show sequence."],
  ["Which pattern fits a paragraph that shows how two cities are alike and different?", "compare and contrast", ["chronological sequence", "problem and solution", "cause and effect"], "Compare and contrast looks at likenesses and differences."],
  ["Grouping ideas logically in a paragraph means…", "putting related details together", ["mixing all the details", "using one long sentence", "starting with the conclusion only"], "Each paragraph should stay on one idea."],
  ["Which sentence does not belong in a paragraph about how bees make honey?", "My cousin has a new bike.", ["Bees collect nectar from flowers.", "They store it in the hive.", "Fanning wings dries the nectar."], "It is off topic.", true],
  ["A multimodal form is one that…", "combines text with images, audio or other media", ["uses only words", "is handwritten", "has no title"], "Posters and digital stories are multimodal."],
  ["Which is a multimodal form?", "an infographic", ["a one-word note", "a plain list of sentences", "a spelling test"], "Infographics combine words and visuals."],
  ["Which tool would you use to explore layout, images and audio for a digital story?", "presentation or video software", ["a ruler", "a dictionary", "a calculator"], "Digital tools help you put media together."],
  ["Thinking maps help writers…", "organize ideas visually before drafting", ["check grammar", "print copies", "choose a title"], "Thinking maps show how ideas connect."],
  ["Which source would give the most up-to-date information about a recent event?", "a recent news website from a reliable outlet", ["a book from many years ago", "a rumour from a friend", "an old poster"], "Check how recent and reliable a source is.", true],
  ["To expand a short piece of writing, a writer can…", "add details from other sources or experts", ["delete the introduction", "repeat sentences", "shrink the font"], "More information can grow an idea.", true],
  ["Which mentor text would help you write a strong opening line?", "a published story with an exciting first line", ["a calendar", "a phone book", "a receipt"], "Reading how professionals write gives ideas for your own style.", true],
];

export const writingForms = bankUnit({
  id: "mb-7-writing-forms",
  title: "Plan & Organize Writing",
  emoji: "📝",
  blurb: "Topics, planning tools, text forms and organization",
  parentNote: "Children practise the steps before and while drafting: choosing a focused topic, planning tools, choosing a text form for the audience, and organizing ideas in a clear pattern.",
  standards: ["ELA.7.C1.1, ELA.7.C1.2, ELA.7.C1.3, ELA.7.C1.4, ELA.7.C1.5, ELA.7.C2.1", "generating ideas, gathering information, planning tools, text forms, multimodal forms and organizational patterns"],
  items: WRITING,
});

const VOICE: Q[] = [
  ["Which word is the most precise replacement for “nice” in “a nice meal”?", "delicious", ["good", "fine", "okay"], "Pick the word with the strongest, most exact picture."],
  ["Which sentence has the strongest descriptive words?", "The golden sunrise spilled across the quiet lake.", ["The sun came up over the lake.", "It was a nice morning.", "The morning was good."], "Specific, vivid words paint a clearer picture."],
  ["Which verb is stronger than “walked”?", "trudged", ["went", "moved", "did"], "Strong verbs show how someone moves."],
  ["Which word replaces “said” to show a quiet voice?", "whispered", ["shouted", "yelled", "bellowed"], "Choose a verb that matches how the words were spoken."],
  ["Which word is a discipline-specific word in science?", "habitat", ["pretty", "very", "thing"], "Subject words are used in one area of study."],
  ["Which pair uses discipline-specific words in a math explanation?", "perimeter and area", ["lovely and sunny", "yummy and soft", "run and jump"], "Math has its own vocabulary."],
  ["In a lab report, “the solution evaporated” is better than “the stuff went away” because it…", "uses precise science vocabulary", ["is shorter", "rhymes", "is a question"], "Precise words help readers understand exactly."],
  ["Writing for a younger audience, which word choice is best?", "big", ["enormous and cumbersome", "gargantuan", "colossal"], "Choose words your audience understands."],
  ["Which sentence sounds appropriate in a formal letter to the principal?", "I would like to request permission to hold a book fair.", ["Hey, can we do a book fair?", "Book fair now!!!", "OMG book fair"], "Formal writing uses a polite, respectful tone."],
  ["Which sentence sounds more like a text to a close friend?", "Hey, want to come over after school?", ["I request the pleasure of your company.", "It is hereby requested that you attend.", "Kindly confirm your availability."], "Informal writing uses a relaxed tone."],
  ["Voice in writing is…", "the writer’s own personality that shows in the words", ["the volume when reading aloud", "the font", "the spelling"], "Voice makes writing sound like a real person."],
  ["Which sentence shows more personal voice?", "I couldn’t stop smiling when I saw the puppy wag its tail.", ["The puppy was seen.", "There was a puppy.", "A puppy exists."], "Feelings and personal details create voice."],
  ["A persuasive speech for a skate park should use…", "a confident tone with strong reasons", ["a bored tone", "no reasons", "a joke in every sentence"], "Tone should fit the purpose."],
  ["A sentence style that adds variety is to…", "mix short and long sentences", ["use only short sentences", "use only long sentences", "repeat the same opening"], "Variety makes writing flow."],
  ["Which sentence starts differently from the others?", "Beside the creek, a deer drank quietly.", ["The deer drank water.", "The deer was thirsty.", "The deer was by the creek."], "Starting with a phrase adds variety."],
  ["Which choice best fits a story meant to entertain?", "lively action and dialogue", ["a table of numbers", "a list of rules", "a bibliography"], "Purpose guides the style."],
  ["Which choice best fits instructions for a science experiment?", "clear steps in order", ["a rhyming poem", "a made-up story", "jokes only"], "Instructions need clarity."],
  ["Which is the most appropriate tone for a thank-you note to a guest speaker?", "warm and respectful", ["angry", "bored", "sarcastic"], "Tone should match the audience and purpose."],
  ["A writer says “I have a lot of feelings about the first snow.” To add voice and detail, they could add…", "a specific memory or image", ["more punctuation", "a heading", "a longer title"], "Details show feelings."],
  ["Which words show an opinion in an editorial?", "should, believe, important", ["on, in, at", "one, two, three", "the, a, an"], "Opinion words show how the writer thinks."],
  ["Which revision makes the sentence more precise? “The thing was big.”", "The glacier was enormous.", ["It was big.", "Big thing.", "The big thing was big."], "Name the thing and use a strong word.", true],
  ["Which sentence suits an audience of experts about electricity?", "The circuit has a resistor in series.", ["The wire stuff has a thing on it.", "The line has a block.", "It zaps."], "Experts expect correct technical terms.", true],
  ["Which change best improves the tone of “Give me your pencil now”?", "May I please borrow your pencil?", ["Pencil.", "Hurry up.", "I need it, give it."], "Polite words change the tone."],
  ["A writer wants to create a sad mood. Which word best helps?", "lonely", ["bouncy", "bright", "snappy"], "Mood words show feeling."],
  ["Which is the best way to find a more exact word?", "Use a thesaurus and check the meaning in a dictionary", ["Pick any long word", "Choose the first word you see", "Use a rhyme"], "Check the shades of meaning before swapping.", true],
  ["The word “home” and the word “residence” have similar meanings. Which is best in a casual story?", "home", ["residence", "domicile", "dwelling"], "A casual story calls for a relaxed word."],
  ["Which sentence has the stronger voice?", "I stared at the tangled mess of wires and groaned.", ["The wires were there.", "There were wires on the table.", "Wires: yes."], "Action and feeling show voice."],
  ["Which form would use more discipline-specific words, a science report or a postcard?", "a science report", ["a postcard", "a birthday note", "a joke"], "Reports about a subject need the subject’s vocabulary."],
];

export const wordChoiceVoice = bankUnit({
  id: "mb-7-word-choice-voice",
  title: "Word Choice & Voice",
  emoji: "🎨",
  blurb: "Choose words and tone for your audience",
  parentNote: "Children practise choosing precise, descriptive and subject-specific words, and matching tone, sentence style and personal voice to the audience and purpose.",
  standards: ["ELA.7.C2.3, ELA.7.C2.4", "descriptive and discipline-specific words, personal voice, and tone and sentence style that fit purpose and audience"],
  items: VOICE,
});

const CAPITALS: Q[] = [
  ["Which sentence uses capital letters correctly?", "We visited Winnipeg in July.", ["we visited winnipeg in july.", "We visited winnipeg in July.", "We visited Winnipeg in july."], "Capitalize names of cities and months."],
  ["Which word needs a capital letter?", "tuesday", ["table", "river", "season"], "Days of the week are capitalized."],
  ["Which is correct?", "Mr. Chen and Dr. Okafor", ["mr. chen and dr. okafor", "Mr. chen and Dr. okafor", "mr. Chen and dr. Okafor"], "Titles before names and the names are capitalized."],
  ["Which names a specific place and needs capitals?", "Lake Winnipeg", ["a lake", "the lake near us", "some water"], "Specific place names are proper nouns."],
  ["Which common noun does NOT need a capital letter?", "mountain", ["Rocky Mountains", "Mount Everest", "Monday"], "Capitalize only specific names."],
  ["Which sentence is correct?", "My Aunt Priya lives in Brandon.", ["my aunt priya lives in brandon.", "My aunt priya lives in Brandon.", "My Aunt Priya lives in brandon."], "Aunt is capitalized when it is part of her name."],
  ["Which sentence is correct?", "My aunt lives in Brandon.", ["My Aunt lives in Brandon.", "my aunt lives in Brandon.", "My aunt lives in brandon."], "Aunt is not capitalized when it is a common noun."],
  ["In dialogue, which is correct?", "She said, “Let’s go.”", ["she said, “let’s go.”", "She said, “let’s go.”", "She said “Let’s go”."], "Capitalize the first word of the quotation."],
  ["Which book title is capitalized correctly?", "The Wind in the Willows", ["The wind in the willows", "the Wind In The Willows", "The Wind In the willows"], "Capitalize the first and last word and most major words, not small words like in, the or of."],
  ["Which movie title is capitalized correctly?", "Journey to the Centre of the Earth", ["journey to the centre of the earth", "Journey To The Centre Of The Earth", "Journey to the centre of the earth"], "Small words like to, the and of stay lowercase in the middle."],
  ["Which words in a title usually stay lowercase unless first or last?", "a, the, of, in", ["Journey, Lake, River", "Dragon, Magic", "Winnipeg, Canada"], "Short articles, prepositions and conjunctions stay lowercase."],
  ["Which abbreviation is capitalized correctly?", "Dr.", ["dr.", "DR.", "dR."], "Titles are abbreviated with a capital first letter."],
  ["Which is the correct abbreviation for Manitoba in the postal system?", "MB", ["Mb", "mb", "MN"], "Province codes are two capital letters."],
  ["Which abbreviation is capitalized correctly?", "Ave.", ["ave.", "AVE", "aVE."], "Street abbreviations start with a capital."],
  ["Which is correct?", "Canada Day is on July 1.", ["canada day is on july 1.", "Canada day is on July 1.", "Canada Day is on july 1."], "Holiday names are proper nouns."],
  ["Which is correct?", "Our class read a story about the Prairie Provinces.", ["Our Class read a story about the prairie provinces.", "our class read a story about the Prairie provinces.", "Our class read a Story about the Prairie Provinces."], "Capitalize proper nouns, not ordinary ones like class and story."],
  ["Which sentence needs a capital letter for a proper noun?", "we flew to toronto.", ["The cat slept.", "It was a warm day.", "We saw a bird."], "Toronto is a city name."],
  ["Which is correct?", "I study French and math.", ["i study french and math.", "I study french and Math", "I Study french and math."], "Languages such as French are capitalized, and a sentence starts with a capital and ends with a period."],
  ["Which is correct?", "We drove north for an hour.", ["we drove north for an hour.", "We drove North for an Hour.", "we Drove north for an hour."], "A direction word is not capitalized, but the first word of a sentence is."],
  ["Which is correct?", "She travelled to the Far North.", ["She travelled to the far north.", "she travelled to the Far north.", "She travelled To The Far North."], "A named region is capitalized.", true],
  ["Which sentence has an error?", "My Brother and I went to the Lake.", ["We went to Falcon Lake.", "My brother and I went to the lake.", "My brother and I went to Falcon Lake."], "Brother and lake are common nouns here.", true],
  ["Which formatting makes a heading stand out?", "bold text and a larger font", ["tiny faint text", "no spacing", "the same size as the paragraph"], "Basic formatting helps readers find sections."],
  ["Which spacing makes a paragraph easy to read?", "a blank line or indent between paragraphs", ["no space at all", "one very long block", "random spaces"], "Spacing separates ideas."],
  ["Italics are often used for…", "the title of a book or a word you want to stress", ["the first word of every sentence", "every noun", "page numbers only"], "Italics set a word apart."],
  ["When typing a paragraph, which is a good keyboarding habit?", "keep your fingers on the home row", ["look at the keys only", "type with one finger", "hit keys hard"], "Good technique increases speed and accuracy."],
  ["Which text alignment is most common for paragraphs of a report?", "left-aligned", ["centred for every line", "right-aligned", "justified only"], "Left alignment is easiest to read for long text."],
  ["Which is the best line spacing for a draft you want to mark up?", "double spacing", ["no spacing", "half spacing", "only one word per line"], "Extra space leaves room for edits.", true],
  ["Which is correct?", "“I’m ready,” said Ana. “Are you?”", ["“i’m ready,” said Ana. “are you?”", "“I’m ready,” said ana. “Are you?”", "“I’m ready,” Said Ana. “Are you?”"], "Capitalize the first word of each quotation; said is not capitalized.", true],
  ["Which abbreviation should be fully capitalized?", "CBC", ["Cbc", "cbc", "cBC"], "Abbreviations made of initials use all capitals."],
  ["Which sentence is correct?", "The Red River flows through Winnipeg.", ["The red river flows through winnipeg.", "The Red river flows through Winnipeg.", "the Red River flows through Winnipeg."], "Rivers and cities are proper nouns."],
];

export const capitalsFormatting = bankUnit({
  id: "mb-7-capitals-formatting",
  title: "Capitals & Formatting",
  emoji: "🔠",
  blurb: "Capitals, titles, abbreviations and tidy layout",
  parentNote: "Children practise capital letters for proper nouns, dialogue, titles and abbreviations, plus basic formatting and keyboarding habits.",
  standards: ["ELA.7.C3.1, ELA.7.C3.3", "legible, well-spaced and formatted writing, and capitals for proper nouns, dialogue, titles and abbreviations"],
  items: CAPITALS,
});

const DESIGN: Q[] = [
  ["An artifact in a presentation is…", "an object or image that supports your message", ["the final page", "a spelling list", "the title"], "Artifacts such as photos, models or charts help the audience understand."],
  ["Which visual aid best shows how the population of a town changed over 20 years?", "a line graph", ["a photo of a mountain", "a poem", "a cartoon"], "Choose a visual that fits the data."],
  ["Which visual aid best shows the steps of a water cycle?", "a labelled diagram", ["a random photo", "a long paragraph", "a joke"], "Diagrams show processes."],
  ["A slide has 200 words in tiny type. What is the best fix?", "Use short bullet points and larger type", ["Add more text", "Use a lighter font colour", "Add a second paragraph"], "Readable slides use few words."],
  ["Good contrast between text and background means…", "the text is easy to read against the background", ["the text matches the background", "the background is blank", "the text is hidden"], "Dark text on a light background is easy to read."],
  ["Which colour combination is hardest to read?", "light yellow text on a white background", ["black text on white", "navy text on yellow", "white text on dark blue"], "Low contrast is hard to read."],
  ["Which choice supports the audience’s understanding best?", "a picture that matches what you are saying", ["a funny picture that is unrelated", "a blurry picture", "a picture covering the words"], "Visuals should support the meaning."],
  ["Layout means…", "how text and images are arranged on a page", ["how long a sentence is", "how loud audio is", "how fast you speak"], "Layout guides the reader’s eye."],
  ["Why do posters use large headings?", "to catch attention and show the main idea", ["to fill space", "to hide details", "to confuse readers"], "Headings guide viewers."],
  ["Which sound would best fit a digital story about a quiet forest?", "gentle bird and wind sounds", ["loud sirens", "a car horn", "a drum solo"], "Sound should match the purpose and mood."],
  ["Before using a photo from the internet in your project, you should…", "check that you may use it and give credit", ["copy it without asking", "change the name", "hide where it came from"], "Respect other people’s work."],
  ["When you create a final copy of a poster, you should…", "proofread it and check the visuals", ["leave it as a rough draft", "remove all text", "skip checking"], "The final copy should be polished."],
  ["A good introduction for a presentation should…", "capture attention and tell what you will talk about", ["repeat the conclusion", "list every detail", "say nothing"], "The opening hooks the audience."],
  ["Which question is a good way to start a presentation about sleep?", "Did you know that students need about nine hours of sleep?", ["Okay, uh.", "Sleep.", "The end."], "A surprising fact or question grabs attention."],
  ["Which part of a presentation contains the main points and details?", "the body", ["the title only", "the introduction", "the credits"], "Introduction, body, conclusion."],
  ["A conclusion should…", "sum up the main idea and leave the audience with a final thought", ["add many new facts", "repeat the introduction word for word", "start a new topic"], "End with a clear closing."],
  ["Which order is the right structure for a presentation?", "introduction, body, conclusion", ["conclusion, introduction, body", "body, conclusion, introduction", "introduction, conclusion, body"], "Start, develop, end."],
  ["Which word choice would capture an audience’s attention in a talk about the stars?", "A billion suns shine in our galaxy.", ["Stars are there.", "There are stars.", "Stars: okay."], "Vivid language engages listeners."],
  ["A digital story is…", "a short story told with images, text and sound", ["a printed book", "a spelling list", "a chart of numbers"], "Digital stories combine media."],
  ["An infographic combines…", "information with images and graphics", ["only a long paragraph", "only sound", "only numbers"], "Infographics present facts visually."],
  ["Which layout choice makes a poster easier to read?", "leaving white space between sections", ["filling every inch with text", "overlapping pictures and words", "using five fonts"], "White space helps the eye rest.", true],
  ["Why limit a poster to two or three fonts?", "Too many fonts look messy and are hard to read", ["Fonts cost money", "Computers allow only three", "It makes text longer"], "Consistent design is clearer.", true],
  ["What does a caption do?", "explains a picture or graph", ["replaces the picture", "is always the title", "hides the picture"], "Captions tell the viewer what to notice."],
  ["Which design choice best helps a viewer find the key idea on a slide?", "putting it in a large, bold heading", ["hiding it at the bottom", "using tiny grey text", "writing it in a long paragraph"], "Emphasis shows importance."],
  ["For a speech to the whole school, which visual aid would be easiest for everyone to see?", "a large, clear slide on a screen", ["a small photo passed around", "a tiny sketch", "handwriting on a scrap"], "Think about the size of the audience.", true],
  ["Combining a clear photo with a short sentence on a slide helps the audience by…", "supporting the message in two ways", ["making it confusing", "removing the idea", "adding noise"], "Words and images work together."],
  ["When choosing music for a digital story, you should consider…", "the mood and purpose of your story", ["only your favourite song", "the loudest track", "any random track"], "Choose sound to fit the message."],
  ["Which is an example of a creative way to hook an audience?", "starting with a short story or surprising question", ["reading the notes quickly", "apologizing first", "mumbling the title"], "Creativity in the opening draws listeners in.", true],
];

export const presentingDesign = bankUnit({
  id: "mb-7-presenting-design",
  title: "Posters & Presentations",
  emoji: "🖼️",
  blurb: "Design choices and how to organize a talk",
  parentNote: "Children think about layout, visuals and sound that support a message, and how to organize a presentation with an introduction, body and conclusion.",
  standards: ["ELA.7.C1.5, ELA.7.C3.5, ELA.7.D1.2, ELA.7.D1.3", "multimodal forms and final copies, visual and audio aids, layout and design choices, and organizing a presentation"],
  items: DESIGN,
});

const REFLECT: Q[] = [
  ["Reflecting on your learning means…", "thinking about what you did well and what to improve", ["copying a friend’s work", "forgetting the lesson", "finishing quickly"], "Reflection helps you grow."],
  ["Which question helps you reflect after writing a story?", "What part was easiest for me, and what was hardest?", ["How many pencils do I have?", "Who sat beside me?", "What time is lunch?"], "Reflect on strategies you used."],
  ["A learning goal should be…", "specific, so you know what you are working toward", ["as big as possible", "secret", "the same as someone else’s"], "Specific goals can be tracked."],
  ["Which is the most specific learning goal?", "I will read for 15 minutes each night this week.", ["I will be better.", "I will do stuff.", "I will try."], "Specific goals have details and a time frame."],
  ["Which is a good first step toward the goal “improve my spelling”?", "Practise five tricky words each day", ["Skip all writing", "Never use a dictionary", "Write more slowly without checking"], "Plan steps to reach a goal."],
  ["Success criteria are…", "a list of what good work looks like", ["the date on the page", "a punishment", "a mark"], "Class criteria describe what to aim for."],
  ["Why is it helpful when the class helps write the criteria?", "Everyone understands what good work looks like", ["Teachers dislike marking", "It makes the work longer", "It replaces learning"], "Shared criteria make expectations clear."],
  ["A learning journal can be used to…", "record what you learned and how you feel about it", ["list your friends", "store recipes", "play games"], "Journals track thinking."],
  ["A digital portfolio is…", "a collection of your work saved on a computer", ["a school photo", "a paper bag", "a test"], "Portfolios show growth over time."],
  ["Descriptive feedback is…", "specific comments about what works and what to improve", ["only a smiley face", "only a mark", "silence"], "Useful feedback is specific."],
  ["Which comment is descriptive feedback?", "Your opening question hooks the reader. Add one more detail in the second paragraph.", ["Good job.", "Bad.", "Okay."], "Specific comments help you improve."],
  ["When a classmate gives you feedback, a helpful response is to…", "listen and think about how to use it", ["argue immediately", "ignore it", "tear up the work"], "Feedback helps you strengthen your skills."],
  ["After feedback says “Add more detail to your conclusion”, what should you do?", "Add a stronger final thought with specific details", ["Delete the conclusion", "Add a title only", "Change the font"], "Use feedback to revise."],
  ["Tracking progress means…", "collecting evidence to see how you are improving", ["guessing", "comparing yourself to others only", "avoiding checks"], "Evidence shows growth."],
  ["Which is evidence of growth in writing?", "two drafts of a piece that show your improvements", ["a blank page", "a cover only", "a reminder note"], "Keep samples that show your progress."],
  ["After reaching a goal, a good next step is to…", "set a new goal", ["stop learning", "erase your work", "forget your strategies"], "Learners keep growing."],
  ["A strategy for listening in class is…", "looking at the speaker and thinking about the message", ["looking out the window", "talking at the same time", "doodling only"], "Active listening is a strategy."],
  ["A strategy for writing when you are stuck is…", "reread what you have and brainstorm the next idea", ["quit", "copy a classmate’s work", "erase everything"], "Writers use strategies to keep going."],
  ["Which is a reading strategy?", "stop and reread when something does not make sense", ["read faster and faster", "skip hard parts", "look only at pictures"], "Monitoring your understanding is a strategy."],
  ["A viewer asks questions about who made an image and why. This is a strategy for…", "viewing", ["spelling", "typing", "handwriting"], "Viewers think about creators and purpose."],
  ["A learner says, “I improved because I planned my writing first.” This is…", "reflecting on a strategy that worked", ["blaming others", "making excuses", "skipping a task"], "Naming what worked helps you use it again.", true],
  ["Which goal is measurable?", "I will write three paragraphs with a clear topic sentence by Friday.", ["I will be a great writer.", "I will think more.", "I will try hard."], "You can check if it was done.", true],
  ["Why should you make a plan with steps for a goal?", "Small steps make a big goal reachable", ["Goals are impossible", "Steps make work longer", "Planning wastes time"], "Steps help you reach your goal.", true],
  ["Collecting evidence of learning could include…", "drafts, checklists and notes", ["only your name", "only the date", "a blank folder"], "Evidence shows what you can do."],
  ["Self-assessment is…", "judging your own work against the criteria", ["having someone else do your work", "ignoring the criteria", "waiting for the report card"], "You check your own progress."],
  ["Which statement shows a growth mindset?", "I can’t do it yet, but with practice I will.", ["I’m just bad at this.", "Why try?", "It’s impossible."], "“Yet” shows you are still growing."],
  ["If you notice you often forget punctuation, a good next goal is…", "to proofread with a punctuation checklist", ["to write shorter", "to stop writing", "to use no sentences"], "A goal can target a pattern you notice.", true],
  ["Feedback from a peer is most useful when it is…", "kind, specific and helpful", ["unkind and short", "vague", "about their own work only"], "Good feedback is kind, specific and useful."],
];

export const learningGoals = bankUnit({
  id: "mb-7-learning-goals",
  title: "Goals & Feedback",
  emoji: "🎯",
  blurb: "Reflect, set goals and use feedback",
  parentNote: "Children practise thinking about how they learn: describing strategies, using criteria and feedback, setting specific goals and tracking progress.",
  standards: ["ELA.7.D2.1, ELA.7.D2.2, ELA.7.D2.3, ELA.7.D2.4, ELA.7.D2.5", "strategies, class criteria and self-assessment, descriptive feedback, setting goals and tracking growth"],
  items: REFLECT,
});

const DISCUSSION: Q[] = [
  ["Paraphrasing means…", "saying someone’s main point in your own words", ["repeating every word", "changing the meaning", "interrupting"], "A paraphrase keeps the meaning but uses your words."],
  ["A classmate says, “Recycling saves energy because making new cans needs more power.” Which is a paraphrase?", "Recycling cans uses less power than making new ones.", ["Recycling is boring.", "Cans are heavy.", "I disagree."], "Keep the idea, change the words."],
  ["Listening critically means…", "thinking about whether the ideas make sense and are supported", ["agreeing with everything", "not listening", "looking away"], "Critical listeners ask questions about what they hear."],
  ["Wait time is…", "a pause that gives someone time to think before they speak", ["a clock", "a break from school", "a mistake"], "Pausing is a supportive non-verbal cue."],
  ["Which non-verbal cue shows you are listening?", "facing the speaker and nodding", ["looking at your phone", "rolling your eyes", "turning away"], "Body language shows respect."],
  ["Respecting communication differences means…", "giving others the time and support they need to share", ["finishing their sentences", "laughing", "talking over them"], "People communicate in different ways."],
  ["A multifaceted question usually…", "asks about many sides of an idea", ["has a yes or no answer only", "is a spelling question", "has no answer"], "It invites thinking and discussion."],
  ["Which is the better question to explore a problem?", "What are some ways we could reduce waste at our school?", ["Is school fun?", "Yes?", "Okay?"], "Open questions invite ideas."],
  ["If you do not understand what someone said, you should…", "ask them to clarify", ["pretend you understood", "interrupt rudely", "walk away"], "Asking helps both of you."],
  ["Which phrase asks for clarification?", "Could you explain what you meant by that?", ["That is silly.", "Nobody cares.", "Stop talking."], "Polite requests invite explanation."],
  ["When speaking to the class, you should use…", "clear sentences and verb tenses that fit your meaning", ["only slang", "a whisper", "single words"], "Oral language follows rules of grammar."],
  ["Which sentence uses the correct verb tense?", "Yesterday I walked to school.", ["Yesterday I walk to school.", "Yesterday I walking to school.", "Yesterday I will walked to school."], "Use past tense for past events."],
  ["For a speech to a school assembly, the best language is…", "clear and respectful, with a suitable tone", ["very casual slang", "rude jokes", "mumbling"], "Fit your words to the audience."],
  ["Which tone is appropriate for a speech asking for volunteers?", "friendly and positive", ["bored", "angry", "mocking"], "Tone should suit the purpose."],
  ["If a speaker uses too much slang with a new audience, you might adjust by…", "choosing words everyone understands", ["speaking faster", "speaking quietly", "using more slang"], "Adjust for your audience."],
  ["Respecting someone’s right to a different opinion means…", "listening even when you disagree", ["making fun of them", "ignoring them", "forcing them to agree"], "Everyone can share their view."],
  ["Which sentence is respectful when you disagree?", "I see it a different way. Here is why.", ["You’re wrong.", "That’s stupid.", "Be quiet."], "Disagree with ideas, not people."],
  ["Building on an idea you heard means…", "adding to it with your own thought", ["repeating it exactly", "ignoring it", "interrupting"], "Good discussions grow ideas."],
  ["Which phrase builds on another’s idea?", "To add to what Sam said, we could also…", ["I wasn’t listening.", "Anyway, my idea is better.", "That’s all wrong."], "Connect your comment to the speaker’s."],
  ["Which environment is inclusive?", "Everyone’s voice is welcomed", ["Only some talk", "Some are laughed at", "Rules apply to some"], "Inclusion means everyone belongs."],
  ["A classmate speaks slowly because they are learning English. A good response is to…", "give them time and listen patiently", ["finish their sentences for them", "tell them to hurry", "leave"], "Patience supports communication.", true],
  ["Which question is open-ended?", "Why do you think the author ended the story that way?", ["Did you read it?", "Is it long?", "Was it a book?"], "Open-ended questions need explanation.", true],
  ["Developing your own opinion while listening means…", "deciding what you think using the evidence you heard", ["adopting the loudest view", "choosing at random", "never deciding"], "Listen, weigh and decide.", true],
  ["Which is an example of an inclusive social convention?", "Taking turns and inviting quiet classmates to share", ["Talking over others", "Choosing teams of friends only", "Excluding someone"], "Conventions shape respectful talk."],
  ["Before a discussion, groups often agree on norms. A useful norm is…", "one person speaks at a time", ["everyone talks at once", "no one listens", "interrupt freely"], "Norms keep conversations respectful."],
  ["After listening to a debate, you can extend your understanding by…", "summarizing both sides in your own words", ["forgetting what you heard", "repeating one speaker", "ignoring evidence"], "Paraphrase key points."],
  ["Which sentence adjusts language for an audience of kindergarten students?", "Let’s look at how a seed grows into a plant.", ["Observe the germination of angiosperms.", "Behold the propagation process.", "Analyze seedling morphology."], "Use words they understand.", true],
  ["Which is a good way to seek clarification in a group project?", "Ask, “Can you tell me more about your part of the plan?”", ["Guess silently", "Do their part for them", "Say nothing"], "Asking helps the whole group."],
  ["A person who listens critically asks themselves…", "What evidence supports this idea?", ["How tall is the speaker?", "What time is it?", "What is for lunch?"], "Look for reasons and evidence."],
];

export const discussionSkills = bankUnit({
  id: "mb-7-discussion-skills",
  title: "Listening & Discussion",
  emoji: "💬",
  blurb: "Listen well, ask good questions and speak respectfully",
  parentNote: "Children practise skills for classroom talk: paraphrasing, asking and clarifying, respectful non-verbal cues, and matching language and tone to the audience.",
  standards: ["ELA.7.A1.1, ELA.7.A1.2, ELA.7.A1.4, ELA.7.A1.5, ELA.7.A1.6", "listening critically, supportive non-verbal cues, multifaceted questions, oral language rules and tone for audience"],
  items: DISCUSSION,
});
