import { bankUnit, type Q } from "../own";

// Grade 7 social studies, Canada in the Contemporary World (Manitoba): mapping the world, time zones, human rights,
// quality of life, and climate change and sustainability.

const LAT_LONG: Q[] = [
  ["Lines of latitude (parallels) run…", "east–west", ["north–south", "from pole to pole", "diagonally"], "Parallels circle Earth like rings, parallel to the equator."],
  ["Lines of longitude (meridians) run…", "from the North Pole to the South Pole", ["east–west around the middle", "only through Canada", "in circles around the poles"], "All meridians meet at the poles."],
  ["The equator is at…", "0° latitude", ["0° longitude", "90° N", "180° longitude"], "Latitude is measured in degrees north or south of the equator."],
  ["The prime meridian is at…", "0° longitude", ["0° latitude", "90° W", "180° latitude"], "It passes through Greenwich, England."],
  ["Which pair best gives Winnipeg’s location?", "50° N, 97° W", ["50° S, 97° W", "97° N, 50° W", "50° N, 97° E"], "Winnipeg is north of the equator and west of the prime meridian. Give latitude first."],
  ["Which place is farther north?", "60° N", ["20° N", "0°", "40° S"], "Latitude increases going north from the equator, up to 90° N at the North Pole."],
  ["Why are lines of latitude called parallels?", "They never meet, like parallel lines", ["They all meet at the poles", "They go through the prime meridian", "They only appear on globes"], "Meridians come together at the poles; parallels do not."],
  ["Which is the longest line of latitude?", "the equator", ["the Arctic Circle", "the Tropic of Cancer", "the line at 60° N"], "Parallels get shorter toward the poles."],
  ["Longitude is measured from 0° to…", "180° east and west", ["90° north and south", "360° only east", "100° only west"], "The 180° meridian is on the opposite side of Earth from the prime meridian."],
  ["Canada is in which hemispheres?", "Northern and Western", ["Southern and Eastern", "Northern and Eastern", "Southern and Western"], "It lies north of the equator and west of the prime meridian."],
  ["Earth turns 360° in 24 hours. About how wide is each time zone?", "15° of longitude", ["10° of longitude", "24° of longitude", "90° of longitude"], "360 ÷ 24 = 15."],
  ["About how many time zones are there around the world?", "24", ["12", "7", "60"], "One for each hour of the day."],
  ["Why do we have time zones?", "So noon is about when the Sun is highest everywhere", ["So everyone has the same time", "So that days are longer", "Because the Moon moves"], "Without them, noon would happen in the middle of the night in some places."],
  ["Local time is…", "the time in your own time zone", ["the time at the equator", "the time in Greenwich only", "the time on a clock tower"], "Local time depends on where you are."],
  ["Universal Time (UTC) is the time standard based on…", "the prime meridian", ["the International Date Line", "the North Pole", "the equator"], "Other zones are described by how many hours they differ from UTC."],
  ["The International Date Line is near…", "180° longitude", ["0° longitude", "0° latitude", "90° N"], "The date changes when you cross it."],
  ["A traveller flies west across the International Date Line. The calendar date…", "goes ahead by one day", ["goes back one day", "stays the same", "becomes zero"], "Going west across the line, you skip ahead a day. Going east, you repeat a day.", true],
  ["How many main time zones does Canada span?", "six", ["two", "four", "ten"], "Pacific, Mountain, Central, Eastern, Atlantic and Newfoundland."],
  ["Winnipeg is in the Central time zone (UTC−6 in standard time). Vancouver is UTC−8. When it is noon in Winnipeg in standard time, it is ___ in Vancouver.", "10 a.m.", ["2 p.m.", "11 a.m.", "noon"], "Places farther west have earlier times. Subtract 2 hours."],
  ["Halifax is UTC−4 in standard time. When it is noon in Winnipeg (UTC−6), it is ___ in Halifax.", "2 p.m.", ["10 a.m.", "1 p.m.", "noon"], "Places farther east have later times. Add 2 hours."],
  ["Toronto is UTC−5 in standard time. When it is noon in Winnipeg (UTC−6), it is ___ in Toronto.", "1 p.m.", ["11 a.m.", "2 p.m.", "noon"], "Toronto is 1 hour ahead of Winnipeg."],
  ["It is 9 a.m. in Winnipeg (UTC−6). What time is it in London, England in winter (UTC+0)?", "3 p.m.", ["3 a.m.", "9 a.m.", "6 p.m."], "London is 6 hours ahead. 9 a.m. + 6 hours.", true],
  ["Time zones to the east have times that are…", "later", ["earlier", "the same", "always noon"], "The Sun rises in the east first."],
  ["Which tool uses latitude and longitude to name an exact place on Earth?", "a grid of coordinates", ["a thermometer", "a bar graph", "a timeline"], "Latitude and longitude form a grid over Earth."],
  ["On a map, which should be shown so people can read distances?", "a scale", ["only a title", "only a compass", "only colours"], "A scale tells how map distance compares with real distance."],
  ["A compass rose on a map shows…", "directions", ["distances", "time zones", "population"], "It points out north, south, east and west."],
];

export const latLong = bankUnit({
  id: "mb-latitude-longitude",
  title: "Latitude, Longitude & Time",
  emoji: "🧭",
  blurb: "Locate places and tell time around the world",
  parentNote: "Children use latitude and longitude to describe where places are, and learn how time zones, Universal Time and the International Date Line work.",
  standards: ["7-KL-015, 7-KL-020, 7-KL-021, 7-S-205, 7-S-207", "latitude, longitude, parallels and meridians, time zones, and using coordinates on maps"],
  items: LAT_LONG,
});

const WORLD: Q[] = [
  ["How many continents are there?", "seven", ["five", "six", "nine"], "Africa, Antarctica, Asia, Australia (Oceania), Europe, North America and South America."],
  ["Which is the largest continent?", "Asia", ["Africa", "Europe", "North America"], "Asia is the largest in area and in population."],
  ["Which continent is Egypt on?", "Africa", ["Asia", "Europe", "South America"], "Egypt is in the north-east corner of Africa."],
  ["Which continent is Brazil on?", "South America", ["North America", "Africa", "Asia"], "Brazil is the largest country in South America."],
  ["Which continent has no permanent population?", "Antarctica", ["Australia", "Europe", "Africa"], "Only researchers stay there for part of the year."],
  ["Which is the largest ocean?", "Pacific Ocean", ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean"], "The Pacific Ocean covers about a third of Earth."],
  ["Which ocean lies between Canada and Europe?", "Atlantic Ocean", ["Pacific Ocean", "Indian Ocean", "Southern Ocean"], "Ships and planes cross the Atlantic from Halifax to London."],
  ["Canada’s northern coast borders the…", "Arctic Ocean", ["Atlantic Ocean", "Indian Ocean", "Gulf of Mexico"], "The Arctic Ocean is around the North Pole."],
  ["Manitoba’s northeast coast is on…", "Hudson Bay", ["the Pacific Ocean", "the Gulf of St. Lawrence", "Lake Superior"], "Churchill, Manitoba, is on Hudson Bay."],
  ["The Himalayas, which include Mount Everest, are in…", "Asia", ["Africa", "South America", "Europe"], "Mount Everest is the highest mountain above sea level."],
  ["The Amazon River flows through…", "South America", ["Africa", "Asia", "Europe"], "It carries more water than any other river."],
  ["The Sahara, a huge desert, is in…", "Africa", ["Asia", "Australia", "North America"], "It covers much of northern Africa."],
  ["Climate zones near the equator are generally…", "hot and wet or hot and dry", ["very cold", "always snowy", "cool and foggy"], "Sunlight strikes most directly there."],
  ["Which vegetation zone has trees that stay green all year and lies across northern Canada and Manitoba?", "boreal forest", ["tropical rainforest", "desert", "savanna"], "The boreal forest has spruce, pine and fir."],
  ["Which vegetation region lies on the coast of Hudson Bay, where it is too cold for trees?", "tundra", ["rainforest", "grassland", "desert"], "Tundra has low plants, mosses and permafrost."],
  ["Southern Manitoba was once covered by what kind of natural vegetation?", "grassland (prairie)", ["tropical rainforest", "desert", "tundra"], "Tall grasses grew on the prairie before farming."],
  ["Which climate zone is hot and gets very little rain?", "desert", ["tundra", "temperate forest", "rainforest"], "Deserts get less than about 250 mm of rain a year."],
  ["Most of the world’s people live…", "in a few crowded clusters, such as East Asia, South Asia and Europe", ["spread out evenly", "mostly near the poles", "in the deserts"], "Population is not evenly distributed."],
  ["Why do more people live along rivers and coasts?", "Fresh water, farmland and travel routes are available", ["It is always colder", "There are no storms", "It is closer to the poles"], "People settle where they can meet their needs."],
  ["Which two countries have the most people?", "India and China", ["Canada and Brazil", "France and Japan", "Mexico and Egypt"], "Each has more than a billion people."],
  ["A map projection is a way to…", "show the round Earth on a flat surface", ["measure time zones", "count population", "name oceans"], "You cannot flatten a sphere without stretching or tearing it."],
  ["Why does every flat map have some distortion?", "A sphere cannot be flattened without changing size or shape", ["Maps are drawn badly", "The Earth is flat in places", "Colours change sizes"], "Each projection keeps some things accurate and distorts others."],
  ["On a Mercator map, areas near the poles look…", "much larger than they are", ["much smaller than they are", "exactly the right size", "missing"], "Greenland looks as large as Africa, but Africa is about 14 times larger."],
  ["Which maps are designed to show the sizes of continents more accurately than Mercator?", "Peters and Robinson", ["Only street maps", "Mercator only", "Weather maps"], "Peters shows equal areas, and Robinson is a balance of shape and size.", true],
  ["Which of these countries is francophone, with French as an official language?", "Senegal", ["Kenya", "Egypt", "Nigeria"], "Senegal in West Africa uses French as its official language."],
  ["Which European country other than France has French as an official language?", "Belgium", ["Portugal", "Germany", "Norway"], "Belgium, Switzerland and Luxembourg also use French."],
  ["Haiti, where French is an official language, is in…", "the Caribbean", ["Europe", "Asia", "Australia"], "Haiti shares an island with the Dominican Republic."],
];

export const worldMap = bankUnit({
  id: "mb-world-map",
  title: "Mapping Our World",
  emoji: "🌍",
  blurb: "Continents, oceans, climates and people",
  parentNote: "Children locate continents, oceans, climate and vegetation zones and population clusters on a world map, and see how map projections change the way places look.",
  standards: ["7-KL-016, 7-KL-017, 7-KL-018, 7-KL-018F, 7-KP-038, 7-S-206", "continents and oceans, climate and vegetation zones, population clusters, francophone countries, and map projections"],
  items: WORLD,
});

const RIGHTS: Q[] = [
  ["Human rights are rights that…", "belong to every person", ["are earned by winning", "only adults have", "only some countries have"], "They are the same for everyone, everywhere."],
  ["Why are human rights called universal?", "They apply to everyone in the world", ["They are only for one country", "They cannot be taught", "They come from the Sun"], "Universal means for all."],
  ["The United Nations adopted the Universal Declaration of Human Rights in…", "1948", ["1867", "1982", "2005"], "It was written after the Second World War."],
  ["Which of these is a human right?", "an education", ["a new phone", "a holiday abroad", "winning every game"], "Education is named in the Declaration."],
  ["The UN Convention on the Rights of the Child says every child has the right to…", "an education and protection from harm", ["a bigger bedroom", "never go to school", "have any toy they want"], "It lists rights such as education, safety and health care."],
  ["The Canadian Charter of Rights and Freedoms became part of Canada’s Constitution in…", "1982", ["1867", "1948", "1999"], "The Charter protects the rights and freedoms of people in Canada."],
  ["Which is a fundamental freedom in the Charter?", "freedom of peaceful assembly", ["freedom to ignore laws", "freedom to take others’ property", "freedom from all rules"], "People can gather peacefully, share ideas and join groups."],
  ["Freedom of the press means…", "news media can report without government control", ["newspapers must print only good news", "everyone can print money", "no one can read news"], "A free press helps citizens make informed choices."],
  ["Universal suffrage means…", "all adult citizens can vote", ["only landowners can vote", "only men can vote", "children can vote"], "Many people had to struggle for this right."],
  ["In Canada, citizens can vote in federal elections at age…", "18", ["16", "21", "25"], "Voting is an important right of citizens."],
  ["Rights come with limits when…", "using a right would harm other people", ["someone feels like it", "it is Monday", "a country is small"], "Citizenship rights involve limits for the good of everyone."],
  ["Treating people with dignity means…", "respecting every person’s worth", ["ignoring their opinions", "only respecting friends", "judging by appearance"], "Everyone is worthy of respect."],
  ["Racism is…", "treating people unfairly because of their race", ["liking everyone equally", "learning about cultures", "making a new friend"], "It harms individuals and communities."],
  ["Prejudice is…", "an opinion formed about a person or group without knowing them", ["a law passed by a government", "a fair test", "a type of music"], "Prejudice can lead to discrimination."],
  ["Which is an example of discrimination?", "refusing to hire someone because of their religion", ["hiring the best-qualified person", "turning down a job applicant who lacks a needed licence", "choosing a team captain by vote"], "Discrimination is unfair treatment because of who someone is."],
  ["A stereotype is…", "an oversimplified idea about a group of people", ["a true fact about everyone", "a type of law", "a map symbol"], "Stereotypes ignore that individuals are different."],
  ["Which organization works to protect human rights and free people jailed for their beliefs?", "Amnesty International", ["Greenpeace", "the Red Cross", "UNICEF"], "Amnesty International campaigns for human rights."],
  ["Which organization works mainly to protect the environment?", "Greenpeace", ["Amnesty International", "UNICEF", "Doctors Without Borders"], "Greenpeace campaigns on issues like pollution and climate."],
  ["Doctors Without Borders (Médecins Sans Frontières) brings…", "medical care to people in crisis", ["entertainment to cities", "new laws to countries", "food stores to Canada"], "Its teams work in war zones and disasters."],
  ["UNICEF is a United Nations organization that helps…", "children around the world", ["only soldiers", "only scientists", "only farmers"], "UNICEF supports children’s health, education and safety."],
  ["The Canadian Museum for Human Rights is in…", "Winnipeg", ["Ottawa", "Brandon", "Regina"], "It opened in Winnipeg in 2014."],
  ["After an earthquake, many countries send rescue teams and supplies. This is…", "global cooperation", ["a trade war", "a competition", "a border dispute"], "Countries and organizations help each other in a disaster."],
  ["Which Canadian won the 1957 Nobel Peace Prize for his work on a UN peacekeeping force?", "Lester B. Pearson", ["Terry Fox", "John A. Macdonald", "Tommy Douglas"], "He later became prime minister."],
  ["Malala Yousafzai is known for speaking up for…", "girls’ right to education", ["space travel", "sports records", "building bridges"], "She won the Nobel Peace Prize in 2014."],
  ["Remembrance Day on November 11 commemorates…", "Canadians who served in wars", ["the founding of Canada", "the start of winter", "a national holiday for sports"], "People wear poppies and observe moments of silence.", true],
  ["A teen sees classmates making fun of a new student’s accent. Which response supports human rights?", "Include the new student and speak up kindly", ["Join in so you fit in", "Say nothing and look away", "Copy the accent"], "Respecting dignity means standing up for others.", true],
  ["Why can democracy improve quality of life?", "Citizens can speak, vote and take part in decisions", ["Leaders never change", "No laws are needed", "Everyone has the same opinions"], "Freedom of speech, assembly and the press help people shape their communities.", true],
];

export const humanRights = bankUnit({
  id: "mb-human-rights",
  title: "Human Rights & Citizenship",
  emoji: "🕊️",
  blurb: "Rights, freedoms and groups that help",
  parentNote: "Children learn about universal human rights, the Canadian Charter, discrimination, and organizations that work for people around the world.",
  standards: ["7-KC-001, 7-KC-003, 7-KC-005, 7-KI-007, 7-KG-035, 7-KG-036, 7-KG-037, 7-VC-001, 7-VC-002", "universal human rights, citizenship and democracy, the effects of discrimination, and international organizations"],
  items: RIGHTS,
});

const LIFE: Q[] = [
  ["Which is a main factor in quality of life?", "access to clean water", ["owning the newest phone", "living near a mall", "having many toys"], "People need water, food, shelter, health care and education."],
  ["Which is NOT a basic need for a good quality of life?", "the latest video game", ["clean water", "enough food", "safe shelter"], "Basic needs come first."],
  ["Quality of life means…", "how well people are able to meet their needs and live well", ["how much money a country prints", "how many cars are sold", "how large a city is"], "It includes health, education, safety, community and more."],
  ["Life expectancy is…", "the average number of years a person is expected to live", ["the longest time a person has lived", "the age of a country", "the number of birthdays"], "It is one way to compare health between countries."],
  ["Literacy rate is…", "the percent of people who can read and write", ["the number of libraries", "the number of books sold", "the percent who like reading"], "Literacy is a sign of access to education."],
  ["A more developed country usually has…", "higher incomes, stronger health care and more industry", ["no schools", "mostly farm work", "no cities"], "A less developed country has fewer of these resources."],
  ["GDP measures…", "the value of goods and services a country produces", ["how happy people are", "how many people live there", "how much rain falls"], "It does not show how wealth is shared."],
  ["Wealth and resources are unevenly distributed. This means…", "some places have much more than others", ["everyone has the same", "resources never move", "no country has any"], "This affects health, education and opportunities."],
  ["Globalization means…", "countries and people becoming more connected through trade, travel and communication", ["countries becoming smaller", "everyone speaking one language", "all borders closing"], "It can bring benefits and also problems."],
  ["Fair trade certification aims to…", "give farmers a fair price and safe working conditions", ["make goods cost more for no reason", "stop all trade", "close farms"], "It helps producers in developing countries."],
  ["Child labour is a problem because…", "it keeps children from school and can harm their health", ["it helps families go to school", "it makes goods safer", "it is always fun"], "Children have the right to learn and play."],
  ["Food security means…", "having enough safe, nutritious food all the time", ["having one big meal a year", "owning a farm", "buying imported food"], "Food insecurity affects health and learning."],
  ["Lack of clean water is likely to cause…", "more illness", ["better health", "more education", "cheaper homes"], "Dirty water spreads diseases."],
  ["Education improves quality of life because…", "it opens doors to better health and jobs", ["it makes people tired", "it lowers income", "it ends community"], "People with education often earn more and know how to stay healthy."],
  ["Which government decision affects quality of life?", "funding public schools and hospitals", ["a child choosing a bike colour", "a store’s sale price", "the weather forecast"], "Governments make decisions about services and rules."],
  ["A leader who holds power because of a law and an election has…", "legal (democratic) authority", ["authority by tradition only", "authority by force", "no authority"], "Citizens choose leaders in a democracy."],
  ["Power and access to wealth and resources are…", "often connected", ["never connected", "the same thing", "only about weather"], "People with more wealth can often influence decisions."],
  ["The Winnipeg-based Canadian Foodgrains Bank sends food to people facing hunger. This is an example of…", "Canadians helping to reduce hunger in other countries", ["a trade war", "a local bake sale", "a government border"], "Many organizations and people work together on global problems."],
  ["Which personal action could help people elsewhere in the world?", "buying fair trade products", ["wasting water", "ignoring the news", "throwing out clothes after one wear"], "Consumer choices can affect workers far away."],
  ["Two people talk about being poor. One counts only money; the other counts family and community. This shows…", "people have different perspectives on quality of life", ["there is only one meaning of poor", "one person is wrong", "money is irrelevant"], "Cultures and people value different things."],
  ["A good quality of life is…", "not only about wealth or technology", ["only about wealth", "only about technology", "impossible to measure"], "Relationships, community, health and meaning matter too."],
  ["Discrimination lowers quality of life when it…", "keeps people from jobs, services or respect", ["gives everyone equal chances", "makes laws fairer", "ends prejudice"], "Fair treatment is part of a good life."],
  ["Which is a way gender stereotypes can affect people’s lives?", "They can limit which jobs or activities people feel allowed to try", ["They give everyone equal chances", "They have no effect", "They make laws"], "Stereotypes narrow the choices people feel they have."],
  ["Which choice might make the world fairer for workers?", "learning where products come from before buying", ["buying whatever is cheapest without asking", "ignoring labels", "wasting what you buy"], "Informed choices can support better working conditions."],
  ["Do countries with high incomes always have the highest quality of life?", "No, because health, safety and community matter too", ["Yes, because money buys everything", "Yes, because poorer countries have no culture"], "A country’s income does not show how wealth is shared.", true],
  ["Why do people emigrate, or leave their home country?", "To find safety, work, or a better life", ["Because they dislike travel", "Because maps tell them to", "To avoid all change"], "Reasons can be environmental, economic, political or social.", true],
];

export const qualityOfLife = bankUnit({
  id: "mb-quality-of-life",
  title: "Quality of Life Worldwide",
  emoji: "🌐",
  blurb: "Needs, wealth, fairness and what we can do",
  parentNote: "Children compare quality of life in Canada and elsewhere, learn how wealth and resources are shared unevenly, and think about how their own choices can help.",
  standards: ["7-KC-002, 7-KC-004, 7-KI-006, 7-KI-008, 7-KG-032, 7-KG-034, 7-KP-039, 7-KP-040, 7-KP-041, 7-KE-045, 7-VE-016", "factors in quality of life, developed and less developed nations, uneven distribution of wealth, and personal actions"],
  items: LIFE,
});

const CLIMATE: Q[] = [
  ["Weather is…", "the conditions outside at a certain time and place", ["the average over many years", "a type of rock", "a kind of map"], "Climate is the pattern of weather over many years."],
  ["Climate is…", "the average weather in a place over many years", ["today’s temperature", "a storm", "the wind direction now"], "Winnipeg has a cold, snowy winter climate."],
  ["Which of these are greenhouse gases?", "carbon dioxide and methane", ["oxygen and nitrogen", "helium and neon", "water only"], "They trap heat in the atmosphere."],
  ["The greenhouse effect is…", "greenhouse gases trapping some of Earth’s heat", ["glass making plants grow", "plants making oxygen", "the Moon blocking the Sun"], "A natural greenhouse effect keeps Earth warm enough for life."],
  ["Which human activity adds the most carbon dioxide?", "burning coal, oil and gas", ["planting forests", "using solar panels", "walking to school"], "Fossil fuels release carbon stored for millions of years."],
  ["Cutting down forests adds to climate change because…", "trees that store carbon are removed", ["trees make carbon dioxide at night", "the soil gets warmer", "forests absorb all methane"], "Trees take in carbon dioxide."],
  ["Planting trees helps because trees…", "take in carbon dioxide", ["release it all", "make coal", "block rain"], "Healthy forests store carbon."],
  ["A consequence of warming oceans and melting ice is…", "rising sea levels", ["lower sea levels", "colder summers everywhere", "less rain in oceans"], "Melting glaciers and ice sheets add water to oceans."],
  ["Why is a warmer climate a concern for polar bears near Churchill?", "Hudson Bay sea ice melts earlier, leaving less time to hunt seals", ["Bears prefer warm weather", "There are more trees", "Seals are bigger"], "Polar bears hunt from the sea ice."],
  ["What is permafrost?", "ground that stays frozen all year", ["a type of tree", "a kind of ice cream", "water in a lake"], "Thawing permafrost can damage buildings and roads and release greenhouse gases."],
  ["Drought can harm prairie farmers by…", "reducing crop yields", ["increasing yields every year", "making fields wetter", "growing more rain"], "Climate change can bring more extreme weather."],
  ["Most of Manitoba’s electricity is made from…", "hydroelectric power", ["coal", "nuclear power", "natural gas only"], "Dams on rivers like the Nelson use falling water."],
  ["Hydroelectric dams can also have downsides, such as…", "flooding land and changing ecosystems and communities", ["producing no electricity", "using only coal", "stopping all rivers forever"], "Large projects can affect traditional territories and wildlife.", true],
  ["Which source of energy is renewable?", "wind", ["coal", "oil", "natural gas"], "Renewable resources are naturally replaced."],
  ["Which source of energy is non-renewable?", "coal", ["solar", "wind", "water"], "Coal took millions of years to form."],
  ["Sustainable development means…", "meeting today’s needs without harming future generations", ["using every resource now", "never building anything", "only helping one country"], "It balances people, the economy and nature."],
  ["A carbon footprint is…", "the amount of greenhouse gas caused by a person or activity", ["a shoe print", "a map symbol", "a kind of fossil"], "Using less energy shrinks it."],
  ["Which way of travelling makes the fewest greenhouse gases per person?", "walking or cycling", ["driving alone", "flying", "idling a truck"], "Human-powered travel produces none."],
  ["Which government decision can reduce pollution?", "setting limits on factory emissions", ["removing all laws", "building more coal plants everywhere", "banning bicycles"], "Laws and policies can protect the environment."],
  ["Riding Mountain National Park in Manitoba is an example of…", "protecting land and wildlife", ["building a mine", "clearing farmland", "creating a port"], "Parks help sustain natural environments."],
  ["Consumerism means…", "buying and using a lot of goods", ["selling only one thing", "making no waste", "trading nothing"], "Producing and throwing away goods affects the environment."],
  ["How can consumer choices help the environment?", "buying less, choosing durable items and repairing things", ["buying more new items", "throwing away working items", "wasting packaging"], "Think before you buy."],
  ["Which action reduces waste the most?", "reducing, by not buying things you do not need", ["recycling items you could have avoided", "burning garbage", "burying plastic"], "Reduce comes before reuse and recycle."],
  ["Climate change can lead to more…", "floods, droughts and extreme storms", ["perfect weather everywhere", "identical seasons", "deserts everywhere"], "Weather becomes less predictable.", true],
  ["“Net zero” emissions means…", "balancing the greenhouse gases put into the air with those taken out", ["making no energy", "stopping all travel", "having zero people"], "Forests and technology can remove some carbon.", true],
  ["Why do coastal cities and island nations worry about sea level rise?", "Their land and homes could flood", ["They will have no tides", "They will gain land", "They will have more sunlight"], "Many people live near coasts.", true],
];

export const climateChange = bankUnit({
  id: "mb-climate-change",
  title: "Climate Change & Sustainability",
  emoji: "🌡️",
  blurb: "Causes, effects and what can be done",
  parentNote: "Children learn what causes climate change, how it affects people and places including Manitoba, and what governments and individuals can do to live more sustainably.",
  standards: ["7-KL-026, 7-KL-027, 7-KP-044, 7-KE-053, 7-KE-054, 7-VL-009, 7-VE-017, 7-S-103", "causes and consequences of climate change, sustainable development, and environmental stewardship"],
  items: CLIMATE,
});
