import { bankUnit, type Q } from "../own";

// Grade 7 science units written for the Manitoba outcomes: gravity and tides (SCI.7.E.4 to E.7), the Solar System, the
// apparent motion of the sky, space exploration and latitude and longitude (SCI.7.E.12 to E.16), and photosynthesis (SCI.7.E.18).

const GRAVITY: Q[] = [
  ["Gravity is a force that…", "pulls objects toward each other", ["pushes objects apart", "only acts on the Moon", "only works in air"], "Every object with mass pulls on every other object."],
  ["Which force keeps you on the ground?", "gravity", ["magnetism", "friction", "static electricity"], "Earth’s gravity pulls you toward its centre."],
  ["Does gravity work in outer space?", "Yes, it reaches far out but gets weaker with distance", ["No, there is no gravity in space", "Only near planets with air", "Only on the Sun"], "Gravity extends infinitely, but its pull weakens as objects get farther apart."],
  ["As two objects move farther apart, the gravitational pull between them…", "gets weaker", ["gets stronger", "stays the same", "stops right away"], "Gravity decreases with distance."],
  ["Which has more gravitational force pulling on it from Earth?", "a 10 kg rock", ["a 2 kg rock", "a 1 kg rock", "a feather"], "The more mass an object has, the more force gravity puts on it."],
  ["Mass is…", "the amount of matter in an object", ["the pull of gravity on an object", "how big an object looks", "how fast an object moves"], "Mass is measured in kilograms."],
  ["Weight is…", "the force of gravity on an object", ["the amount of matter in an object", "the size of an object", "the speed of an object"], "Weight is a force, so it is measured in newtons."],
  ["Weight is measured in…", "newtons", ["kilograms", "metres", "litres"], "A newton (N) is the unit of force."],
  ["Which tool measures weight, the force of gravity?", "spring scale", ["ruler", "thermometer", "beaker"], "The spring stretches more when the pull is stronger."],
  ["Which tool measures mass?", "balance", ["thermometer", "ruler", "stopwatch"], "A balance compares masses."],
  ["An astronaut has a mass of 70 kg on Earth. What is her mass on the Moon?", "70 kg", ["12 kg", "420 kg", "0 kg"], "Mass does not change with place. Her weight is what changes."],
  ["On the Moon, a rock’s weight compared with its weight on Earth is…", "less", ["more", "the same", "zero"], "The Moon has less mass, so its gravity is weaker. It is about one sixth of Earth’s."],
  ["Why is gravity on the Moon weaker than on Earth?", "The Moon has less mass", ["The Moon is farther from the Sun", "The Moon has no air", "The Moon spins slower"], "The more mass a body has, the stronger its gravity."],
  ["On Earth, gravity pulls objects toward the…", "centre of Earth", ["North Pole", "Sun", "Moon"], "Down means toward the centre of Earth."],
  ["Which has the strongest gravity in our Solar System?", "the Sun", ["Earth", "Jupiter", "the Moon"], "The Sun has far more mass than anything else in the Solar System."],
  ["The Moon orbits Earth because…", "Earth’s gravity pulls on it", ["the Sun’s light pushes it", "Mars pulls it", "it is lighter than air"], "Gravity keeps the Moon curving around Earth."],
  ["Planets orbit the Sun because…", "the Sun’s gravity keeps pulling them into a curved path", ["the Sun blows them around", "they are pushed by wind", "they float on space"], "Without that pull a planet would travel in a straight line."],
  ["Which is the main force that holds the Solar System together?", "gravity", ["friction", "magnetism", "sound"], "The Sun’s gravity keeps the planets in orbit."],
  ["A tide is…", "the regular rise and fall of ocean water levels", ["a wave made by wind", "a kind of current in rivers", "a melting of ice"], "Most coasts have high tide and low tide each day."],
  ["Tides are mainly caused by the gravity of…", "the Moon, and also the Sun", ["Mars", "the wind", "the stars"], "The Moon’s pull on the oceans is the main cause."],
  ["About how many high tides do many coasts have each day?", "two", ["one every week", "twelve", "none"], "Most coasts have two high tides and two low tides about every 24 hours."],
  ["When the Sun, Moon and Earth line up, tides are…", "higher than usual", ["lower than usual", "stopped", "the same as always"], "The pulls add together, making spring tides."],
  ["Tidal turbines make electricity from…", "moving water", ["sunlight", "wind", "coal"], "Rising and falling tides push water through the turbines."],
  ["Which place is famous for some of the highest tides in the world?", "the Bay of Fundy", ["Lake Winnipeg", "Lake Manitoba", "Great Slave Lake"], "The Bay of Fundy, between New Brunswick and Nova Scotia, is open to the ocean and shaped like a funnel."],
  ["Churchill, Manitoba, on Hudson Bay, has ocean tides. Why not Lake Winnipeg?", "A small lake is too small for the Moon’s pull to make a noticeable difference", ["Lakes have no gravity", "The Moon cannot be seen from Manitoba", "The Sun cancels the Moon’s pull on lakes"], "The Moon’s pull changes very little across a small body of water.", true],
  ["Astronauts on the International Space Station float because…", "they and the station are falling around Earth together", ["there is no gravity there", "the station is very light", "air pushes them up"], "Gravity at that height is still strong. They are in constant free fall as they orbit.", true],
  ["A satellite orbits Earth. What would it do if gravity suddenly stopped?", "fly off in a straight line", ["fall straight down", "stop moving", "speed up in a circle"], "Gravity bends its path. Without it, the satellite would go straight.", true],
  ["A hammer and a feather are dropped on the Moon at the same time. What happens?", "They land together", ["The hammer lands much earlier", "The feather floats away", "Neither falls"], "With no air to slow the feather, gravity speeds them up equally.", true],
];

export const gravityTides = bankUnit({
  id: "mb-gravity-tides",
  title: "Gravity & Tides",
  emoji: "🌊",
  blurb: "A pull that holds the Moon, planets and oceans",
  parentNote: "Children learn that gravity is a pull between objects, tell mass from weight, and see how the Moon’s gravity causes ocean tides.",
  standards: ["SCI.7.E.4, SCI.7.E.5, SCI.7.E.6, SCI.7.E.7", "gravity, weight and mass, orbits, and tides"],
  items: GRAVITY,
});

const SOLAR: Q[] = [
  ["Which planet is closest to the Sun?", "Mercury", ["Venus", "Mars", "Neptune"], "Mercury orbits closest to the Sun."],
  ["Which is the largest planet?", "Jupiter", ["Earth", "Saturn", "Mars"], "Jupiter is larger than all the other planets together."],
  ["How many planets are in our Solar System?", "eight", ["seven", "nine", "ten"], "Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus and Neptune."],
  ["Which are the rocky inner planets?", "Mercury, Venus, Earth and Mars", ["Jupiter, Saturn, Uranus and Neptune", "Earth, Mars, Jupiter and Saturn", "Venus, Mars, Saturn and Neptune"], "The four planets closest to the Sun have solid surfaces."],
  ["Which two planets are gas giants?", "Jupiter and Saturn", ["Mercury and Venus", "Earth and Mars", "Mars and Neptune"], "They are made mostly of hydrogen and helium."],
  ["What lies between Mars and Jupiter?", "the asteroid belt", ["the Moon", "the Milky Way", "Saturn’s rings"], "Millions of rocky asteroids orbit in a belt there."],
  ["Pluto is classified as a…", "dwarf planet", ["star", "moon", "comet"], "Pluto is too small to clear its orbit, so it is called a dwarf planet."],
  ["The Sun is a…", "star", ["planet", "moon", "comet"], "The Sun is a star made of hot gases that gives off light and heat."],
  ["An astronomical unit (AU) is the average distance from…", "Earth to the Sun", ["Earth to the Moon", "the Sun to Jupiter", "Mars to Venus"], "1 AU is about 150 million kilometres."],
  ["Day and night happen because…", "Earth rotates on its axis", ["Earth orbits the Moon", "the Sun moves around Earth", "clouds cover the Sun"], "Earth spins once about every 24 hours."],
  ["Why does the Sun seem to rise in the east?", "Earth spins from west to east", ["The Sun moves around Earth each day", "The Moon pulls the Sun", "Earth’s orbit tilts every morning"], "As Earth turns toward the east, the Sun comes into view."],
  ["Why do stars appear to move across the night sky?", "Earth rotates", ["The stars orbit Earth", "The stars are falling", "The Moon pushes them"], "It is Earth that moves, but it looks as if the sky moves."],
  ["Over several nights, a planet is seen to…", "change position against the background stars", ["stay in exactly the same place", "disappear and never return", "twinkle faster"], "The word planet comes from a Greek word for wanderer."],
  ["Which is a long-tailed object that orbits the Sun and whose tail points away from it?", "a comet", ["a moon", "a dwarf planet", "a satellite"], "Sunlight and the solar wind push the comet’s gas and dust away from the Sun."],
  ["Lines of latitude run…", "east–west, parallel to the equator", ["north–south", "diagonally", "from pole to pole"], "Latitude lines are also called parallels."],
  ["Lines of longitude run from…", "pole to pole", ["east to west", "the equator to the Sun", "Canada to the equator"], "Longitude lines are also called meridians."],
  ["The equator is the line of…", "0° latitude", ["0° longitude", "90° latitude", "180° longitude"], "Latitude is measured north and south of the equator."],
  ["Why is it warmer near the equator?", "Sunlight strikes the ground more directly", ["It is closer to the Moon", "It has more oceans", "It is flatter"], "Near the poles, the same sunlight is spread over a larger slanted area."],
  ["Winnipeg is at about 50° N. Which is true?", "It is in the Northern Hemisphere, south of the Arctic Circle", ["It is in the Southern Hemisphere", "It is on the equator", "It is north of the Arctic Circle"], "The Arctic Circle is at about 66.5° N."],
  ["Who was the first person in space?", "Yuri Gagarin", ["Neil Armstrong", "Chris Hadfield", "Marc Garneau"], "Yuri Gagarin orbited Earth in 1961."],
  ["Who was the first Canadian in space?", "Marc Garneau", ["Chris Hadfield", "Roberta Bondar", "Jeremy Hansen"], "Marc Garneau flew on the space shuttle in 1984."],
  ["Canadarm2 is a robotic arm on the…", "International Space Station", ["Moon", "Hubble Space Telescope", "Mars rover"], "Canada built it to move equipment and help astronauts."],
  ["What is a rover?", "a vehicle that explores the surface of another world", ["a rocket that carries people", "a star that moves", "a telescope in orbit"], "Rovers have explored Mars and the Moon."],
  ["Why do some telescopes orbit above Earth’s atmosphere?", "Air blurs and blocks some of the light", ["There is more gravity there", "They stay cooler", "Stars are closer there"], "Above the air, pictures are much sharper."],
  ["Space probes such as Voyager…", "travel without people on board", ["carry astronauts", "stay on Earth", "orbit the Sun every day"], "Probes send back pictures and data."],
  ["Sometimes Mars seems to move backward against the stars. Why?", "Earth passes Mars in its orbit, changing our line of sight", ["Mars changes direction in space", "Mars is pushed by the Moon", "Clouds block the view"], "It is like passing a slower car on a highway: the other car seems to drift backward.", true],
  ["In midsummer north of the Arctic Circle, the Sun may…", "stay up for 24 hours", ["never rise", "set every hour", "turn red"], "Earth’s tilt means high latitudes get constant daylight in summer.", true],
  ["Why does the Moon show different phases?", "We see different amounts of its sunlit half as it orbits Earth", ["Earth’s shadow covers it more and more", "The Moon changes size", "Clouds block part of it"], "The Moon is always half lit by the Sun; our view of that half changes.", true],
];

export const solarSystem = bankUnit({
  id: "mb-solar-system",
  title: "Our Solar System",
  emoji: "🪐",
  blurb: "Planets, the changing sky and exploring space",
  parentNote: "Children learn the scale and members of the Solar System, why the Sun and stars appear to move, how latitude and longitude describe Earth’s place in space, and how people explore space.",
  standards: ["SCI.7.E.12, SCI.7.E.13, SCI.7.E.14, SCI.7.E.15, SCI.7.E.16", "the Solar System, the apparent motion of the sky, human space exploration, and latitude and longitude"],
  items: SOLAR,
});

const PHOTO: Q[] = [
  ["Photosynthesis is the process plants use to…", "make food from light, water and carbon dioxide", ["break food down into soil", "make light from heat", "drink water through leaves"], "Plants build their own food using the Sun’s energy."],
  ["Which gas do plants take in for photosynthesis?", "carbon dioxide", ["oxygen", "nitrogen", "helium"], "Carbon dioxide enters leaves through tiny openings."],
  ["Which gas do plants give off during photosynthesis?", "oxygen", ["carbon dioxide", "methane", "hydrogen"], "The oxygen we breathe comes mostly from photosynthesis."],
  ["What sugar do plants make in photosynthesis?", "glucose", ["salt", "starch only", "protein"], "Glucose stores the energy plants and animals use."],
  ["What is chlorophyll?", "the green substance that absorbs light energy", ["a gas in the air", "the sugar plants make", "a plant’s root"], "Chlorophyll is found in the leaves’ cells."],
  ["Why do most leaves look green?", "Chlorophyll reflects green light", ["The roots are green", "Leaves absorb only green light", "Water is green"], "Chlorophyll absorbs red and blue light and reflects green."],
  ["Which form of energy is needed for photosynthesis?", "light energy", ["sound energy", "wind energy", "heat from a fire only"], "Usually this comes from the Sun."],
  ["Where does the energy stored in glucose first come from?", "the Sun", ["the soil", "the air", "the roots"], "Photosynthesis changes light energy into stored chemical energy."],
  ["Which part of a plant takes in water?", "roots", ["flowers", "seeds", "petals"], "Water travels from the roots up to the leaves."],
  ["Stomata are tiny openings in leaves that let in…", "carbon dioxide", ["glucose", "sunlight", "soil"], "Stomata also let oxygen and water vapour out."],
  ["Which is NOT needed for photosynthesis?", "oxygen", ["water", "carbon dioxide", "light"], "Plants make oxygen during photosynthesis; they do not need it as an input."],
  ["Which is the word equation for photosynthesis?", "carbon dioxide + water + light → glucose + oxygen", ["glucose + oxygen → carbon dioxide + water", "oxygen + water → glucose + light", "carbon dioxide + glucose → water + light"], "The inputs are on the left; the products are on the right."],
  ["Plants that make their own food are called…", "producers", ["consumers", "decomposers", "predators"], "Producers start almost every food chain."],
  ["Which organism can do photosynthesis?", "algae", ["mushroom", "spider", "rabbit"], "Algae contain chlorophyll."],
  ["A plant is kept in a dark closet for two weeks. It will most likely…", "turn pale and weak because it cannot make glucose", ["grow twice as fast", "turn bright green", "make more oxygen"], "Without light, photosynthesis stops."],
  ["Grasses on the Manitoba prairie use sunlight to make glucose. They are…", "producers", ["consumers", "decomposers", "predators"], "They make their own food, so they are producers."],
  ["Trees that lose their leaves in fall make less glucose in winter because…", "there are no leaves to absorb light", ["roots stop working forever", "the air has no carbon dioxide", "the Sun stops shining"], "Leaves are where most photosynthesis happens."],
  ["Extra glucose that a plant does not use is stored as…", "starch", ["salt", "oxygen", "chlorophyll"], "Potatoes store starch in their underground stems."],
  ["Plants release the energy in glucose through…", "cellular respiration", ["photosynthesis", "pollination", "germination"], "Cells use oxygen to release energy from glucose."],
  ["Bubbles rise from a water plant in light but stop in the dark. Why?", "Photosynthesis, which makes the oxygen, stops without light", ["The plant has died", "The water has become heavier", "The plant is sleeping"], "The bubbles are oxygen from photosynthesis."],
  ["More light, up to a point, makes photosynthesis…", "faster", ["slower", "stop", "turn to respiration"], "More light energy lets the plant make glucose more quickly."],
  ["Why are plants the base of most food chains?", "They capture the Sun’s energy as food", ["They are the biggest living things", "They do not need energy", "They eat the soil"], "All other living things depend on that energy directly or indirectly."],
  ["Where in a plant cell does photosynthesis take place?", "chloroplasts", ["nucleus", "cell wall", "vacuole"], "Chloroplasts hold the chlorophyll."],
  ["Which statement is true?", "Plants make glucose by photosynthesis and release its energy by respiration", ["Plants only do respiration", "Plants only do photosynthesis", "Animals make glucose from light"], "Plants do both.", true],
  ["A greenhouse worker adds a lamp at night. This helps plants because…", "they get light energy to keep making glucose", ["they get more water", "they make less oxygen", "it stops respiration"], "More light time means more photosynthesis, as long as water and carbon dioxide are available.", true],
  ["Plants in a sealed jar in the light last a long time. Why?", "They use the carbon dioxide animals make and give back oxygen", ["They need no gas at all", "They eat the glass", "They make water from nothing"], "Matter cycles between photosynthesis and respiration.", true],
];

export const photosynthesis = bankUnit({
  id: "mb-photosynthesis",
  title: "Photosynthesis",
  emoji: "🌱",
  blurb: "How plants turn sunlight into food",
  parentNote: "Children learn that plants use light energy, water and carbon dioxide to make glucose and oxygen, and why that matters for every food chain.",
  standards: ["SCI.7.E.18", "photosynthesis, energy, chlorophyll and glucose"],
  items: PHOTO,
});
