import type { Unit } from "../../types";
import { bankUnit, type Q } from "../own";

// Grade 8 English language arts: inquiry and research (strand B1), planning and choosing forms (C1), organizing
// and word choice (C2, C3), fair and inclusive language (A1.3, B3.4) and reflecting on learning (D2). Oral
// presentation outcomes are not practised here.

const RESEARCH: Q[] = [
  ["Prior knowledge is…", "what you already know about a topic", ["a test you take at the end", "a list of sources", "a kind of poem"], "Start by asking what you already know."],
  ["Why is it useful to name your prior knowledge before you research?", "it shows what you still need to find out", ["it makes the research shorter", "it replaces reading", "it proves you are right"], "Gaps in what you know become your questions."],
  ["Which is an open-ended research question?", "How have schools changed over the last 100 years?", ["Did schools change?", "Is a school a building?", "What year did you start school?"], "Open-ended questions can't be answered with yes, no or one fact."],
  ["Which question is best for exploring several points of view?", "How do farmers and city planners see the use of farmland differently?", ["What is farmland?", "Is farmland flat?", "Where is the nearest farm?"], "Look for a question that invites different perspectives."],
  ["A misconception is…", "an idea that is believed but is not accurate", ["a type of source", "a summary", "a final draft"], "Good questions test misconceptions."],
  ["You find a fact in only one blog post. What should you do?", "check it against other sources", ["copy it right away", "ignore all other sources", "change it to sound better"], "Reliable facts show up in several trustworthy places."],
  ["Which source is usually the most reliable for facts about a science topic?", "a report by a university research team", ["an anonymous post", "an advertisement", "a joke website"], "Look for a named author with expertise."],
  ["Which clue suggests a website may be biased?", "it only shows one side and uses very emotional words", ["it lists the author and the date", "it gives references", "it shows several viewpoints"], "Bias means leaning strongly to one side."],
  ["A primary source is…", "a first-hand record from the time, such as a diary or photograph", ["a textbook written years later", "an encyclopedia summary", "a teacher's opinion"], "Primary means first-hand."],
  ["A secondary source is…", "an account written later that explains or interprets other sources", ["a letter written during the event", "a photo taken during the event", "a recording made during the event"], "Secondary sources are one step removed."],
  ["You are gathering information. What is a gap?", "something you still need to know", ["an error in spelling", "a blank page", "a type of graph"], "Reviewing your notes shows what is missing."],
  ["When you find a gap in your notes, you should…", "look for more information to fill it", ["write the report anyway and guess", "delete the whole topic", "stop researching"], "Locate and gather more information."],
  ["Which is the best way to record where an idea came from?", "write down the author, title and date of the source", ["write only the topic", "write nothing and trust your memory", "write the page colour"], "Citing sources lets readers check your evidence."],
  ["A good summary of an article…", "gives the main ideas in your own words", ["copies the whole article", "adds your opinions only", "lists every detail"], "A summary is short and keeps the key points."],
  ["Evidence from a text is…", "a detail or quote that supports your point", ["your feeling about the text", "the title of the text", "the number of pages"], "Evidence backs up an idea."],
  ["Which graphic organizer helps you compare two sources?", "a Venn diagram", ["a calendar", "a thermometer", "a map legend"], "A Venn diagram shows how things are alike and different."],
  ["What does skimming do?", "gets the main idea quickly by looking at headings and key words", ["reads every word slowly", "copies the text", "ignores the headings"], "Skimming is for a quick overview."],
  ["Which planning tool lets you show how ideas connect?", "a mind map", ["a ruler", "a spelling list", "a title page"], "A mind map has branches that link ideas."],
  ["Jot notes are…", "short notes that capture key words, not full sentences", ["a finished essay", "a final copy", "a table of contents"], "They save time while you gather facts."],
  ["Before you research in a group, which step helps most?", "agree on the question and who will find what", ["each person chooses a different topic secretly", "wait until the day it is due", "copy one member's notes"], "Planning makes group inquiry fair and focused."],
  ["Two sources give different dates for the same event. What is a good next step?", "check a third, reliable source", ["pick the one you like", "use both dates", "skip the date"], "Look for agreement among trustworthy sources."],
  ["An author is paid by a company to write about its product. How might this affect the writing?", "it may favour the company", ["it must be completely neutral", "it will contain no facts", "it can never be used"], "Consider who made the text and why.", true],
  ["Which statement shows peer discussion helping build knowledge?", "A classmate's question made me notice a detail I had missed.", ["I finished by myself and did not share.", "We all copied the first page we found.", "I ignored what the group said."], "Collaboration deepens understanding.", true],
  ["A question starts with “Why do some communities have more green space than others?” What kind of question is it?", "an open-ended question that invites multiple perspectives", ["a yes or no question", "a question with one right fact", "a question that can't be researched"], "Open-ended inquiry questions begin with how or why.", true],
  ["You read three sources: two say a sports drink helps athletes, the third (paid for by the maker) says it helps everyone. What should you notice?", "the third source may be biased", ["all three are exactly equal", "paid sources are always right", "nothing can be learned"], "Check who benefits from the claim.", true],
  ["Which note best cites evidence from multiple texts?", "Both Source A (2021) and Source B (2023) report that more students walk to school.", ["Everyone knows more students walk.", "I think more students walk.", "Students walk."], "Name the sources that support the claim.", true],
  ["After reading widely, which sentence shows a pattern across topics?", "In science, history and art, new technology changed how people worked.", ["I read one book.", "Art is fun.", "History has dates."], "A pattern shows up in more than one area.", true],
];

const WRITING_PLAN: Q[] = [
  ["Which text form is best for convincing a reader to take action?", "a persuasive letter", ["a recipe", "a weather report", "a timetable"], "Purpose helps you choose the form."],
  ["Which text form is best for telling what happened at an event today?", "a news article", ["a poem", "a list of rules", "a diary of a made-up character"], "News articles report events."],
  ["Which text form best explains how to do something step by step?", "instructions", ["a persuasive essay", "a poem", "a diary entry"], "Instructions use numbered steps and clear verbs."],
  ["A report is a text form that…", "presents facts about a topic in an organized way", ["tells a made-up story only", "persuades with strong feelings only", "rhymes in every line"], "Reports inform."],
  ["Which pair matches?", "journal – personal thoughts and experiences", ["report – rhyme and rhythm", "poem – timetable", "instructions – opinions"], "Journals are personal."],
  ["Audience means…", "the people who will read or see your work", ["the title", "the author", "the page number"], "Writers choose words for their audience."],
  ["You are writing a thank-you note to a close friend. Which tone is best?", "warm and friendly", ["cold and formal", "angry", "very technical"], "Tone matches audience and purpose."],
  ["You are writing a letter to the mayor. Which opening is best?", "Dear Mayor Singh, I am writing about a safety problem near my school.", ["Hey you, listen up!", "Whatever, here is my complaint.", "Yo, mayor!"], "A formal audience calls for a respectful tone."],
  ["Purpose is…", "the reason you are writing, such as to inform, persuade or entertain", ["the length of the piece", "the title only", "the spelling"], "Know your purpose before you draft."],
  ["Which organizational pattern shows how one event leads to another?", "cause and effect", ["compare and contrast", "description", "chronological order only"], "Cause and effect links reasons to results."],
  ["Which organizational pattern puts events in time order?", "chronological sequence", ["cause and effect", "problem and solution", "alphabetical order"], "First, next, then, finally."],
  ["Which words signal a cause-and-effect pattern?", "because, as a result, therefore", ["first, next, finally", "on the left, beside, above", "for example, such as"], "These words connect a cause to an effect."],
  ["Which words signal a compare-and-contrast pattern?", "similarly, however, in contrast", ["first, second, third", "because, so, thus", "yesterday, today, tomorrow"], "They point out likenesses and differences."],
  ["Which sentence is the better topic sentence for a paragraph about recycling?", "Recycling helps our community reduce waste.", ["Plastic is a thing.", "I like Tuesday.", "There are bins."], "A topic sentence states the main idea."],
  ["Grouping related ideas together in a paragraph helps the reader…", "follow your thinking", ["skip the text", "count the words", "find the spelling errors"], "Logical groups make text coherent."],
  ["Which sentence does NOT belong in a paragraph about the benefits of sleep?", "My favourite colour is green.", ["Sleep helps the brain store memories.", "Sleep gives the body time to repair.", "Tired students find it harder to focus."], "Cut the sentence that is off topic."],
  ["Which brainstorming tool helps you sketch the ideas for a story?", "a storyboard", ["an index", "a bibliography", "a dictionary"], "Sketching helps you plan a sequence."],
  ["A research planner helps you…", "organize questions, sources and deadlines", ["check your spelling", "make your handwriting neat", "choose a font"], "Plan before you write."],
  ["Voice in writing means…", "the writer's personality showing in the words", ["how loudly a person reads", "the font size", "the page margins"], "Voice makes a writer sound like themselves."],
  ["Which sentence has a humorous tone?", "My dog is so smart that he has started to correct my homework.", ["The report is due on Friday.", "Please close the door.", "The bus leaves at 8:15."], "Humour uses playful exaggeration."],
  ["Which sentence would suit an essay rather than a story?", "Public libraries give every community access to knowledge.", ["“Run!” she shouted, slamming the door.", "Once upon a time, a fox lived in a cave.", "The wind howled as the sun went down."], "Essays state and support ideas."],
  ["Sarcasm means…", "saying the opposite of what you mean, often to tease", ["saying exactly what you mean", "rhyming words", "using a dictionary"], "Sarcasm depends on tone, so use it carefully in writing."],
  ["Which poster element makes it easier to read from far away?", "large, high-contrast headings", ["tiny text in light grey", "many fonts in every line", "text over a busy photo"], "Layout and design help the audience.", true],
  ["An infographic is best for…", "showing data and key facts using images and short text", ["writing a long story", "copying a book", "listing only opinions"], "It combines visuals and words.", true],
  ["Which tool lets you add images and audio to tell a story digitally?", "a digital story or slideshow", ["a printed worksheet", "a pencil only", "a ruler"], "Multimodal means more than one mode, such as words, images and sound.", true],
  ["A student wants to show how the number of birds changed over 5 years. Which form works best?", "an infographic with a graph", ["a poem with no data", "a recipe", "a diary of one day"], "Choose a form that shows the data clearly.", true],
  ["Which tone fits a persuasive speech about reducing food waste?", "confident and respectful, with strong reasons", ["rude and angry", "silly with no facts", "so quiet nobody hears"], "Persuasion needs good reasons and a respectful voice.", true],
];

const WORDS: Q[] = [
  ["Which word is most precise for a science report?", "evaporate", ["go away", "disappear somehow", "turn into stuff"], "Discipline-specific words are exact."],
  ["Which pair is a base word and a derivative?", "help – helpful", ["help – hill", "help – hop", "help – hat"], "A derivative is built from a base."],
  ["Which word is the base of unhelpful?", "help", ["un", "ful", "lp"], "Remove the prefix un- and suffix -ful."],
  ["Which word is a derivative of act?", "action", ["acre", "apple", "after"], "Act + -ion."],
  ["Which suffix turns “care” into a word meaning “without care”?", "-less", ["-ful", "-ness", "-ing"], "Careless means without care."],
  ["Which prefix means “not”?", "un-", ["re-", "pre-", "inter-"], "Unhappy means not happy."],
  ["Which word is spelled correctly?", "necessary", ["neccessary", "necesary", "neccesary"], "One c and two s's: nec-es-sar-y."],
  ["Which word is spelled correctly?", "separate", ["seperate", "separete", "seperete"], "Remember “a rat” in sep-a-rate."],
  ["Which word is spelled correctly?", "definitely", ["definately", "definitly", "defanitely"], "It has finite inside."],
  ["Which word is spelled correctly?", "environment", ["enviroment", "envirenment", "enviornment"], "There is an n before the m: environ-ment."],
  ["Which word is spelled correctly?", "government", ["goverment", "govermment", "govenment"], "Govern + ment."],
  ["When adding -ing to “make”, you…", "drop the silent e: making", ["keep the e: makeing", "double the k: makking", "add a y: makying"], "Drop silent e before -ing."],
  ["When adding -ed to “stop”, you…", "double the final consonant: stopped", ["keep it: stoped", "add an e: stopeed", "drop the p: stoed"], "One-syllable CVC words double the last letter."],
  ["When adding -ly to “happy”, the y changes to…", "i: happily", ["e: happyly", "o: happoly", "nothing: happyly"], "Change y to i before most suffixes."],
  ["Which is a plural of “city”?", "cities", ["citys", "cityes", "citis"], "Consonant + y: change y to i and add -es."],
  ["Which is a plural of “knife”?", "knives", ["knifes", "knifs", "knivz"], "Change f/fe to v and add -es."],
  ["Which word means the opposite of “expand”?", "contract", ["extend", "grow", "stretch"], "Opposite in meaning is an antonym."],
  ["A synonym for “enormous” is…", "huge", ["tiny", "narrow", "average"], "Synonyms have a similar meaning."],
  ["Which word is the best fit: “The scientist ___ the results carefully.”", "analyzed", ["liked", "did", "got"], "Use a precise verb."],
  ["Which word completes the sentence? “___ going to the library after school.”", "They're", ["Their", "There", "Theyre"], "They're means they are."],
  ["Which spelling uses the root “photo” (light)?", "photograph", ["phonograph", "paragraph", "telegraph"], "Photo means light; graph means write."],
  ["Which word contains the prefix “trans-” meaning “across”?", "transport", ["trample", "trust", "train"], "Trans- + port (carry)."],
  ["In a word processor, which tool would you use to make a heading stand out?", "a heading style", ["the spacebar", "the Caps Lock key", "the backspace key"], "Formatting tools organize a document."],
  ["Headers and footers in a document are used for…", "text such as page numbers and titles at the top or bottom of each page", ["the main body only", "pictures only", "spelling checks"], "They repeat on every page.", true],
  ["Which formatting choice helps readers scan a report?", "headings and short paragraphs", ["one huge paragraph", "many colours and fonts", "text in all capitals"], "Formatting should help, not distract.", true],
  ["Which spelling strategy helps with “rhythm”?", "break it into syllables and use a memory trick", ["guess and move on", "skip it", "type it three different ways without checking"], "Rhythm helps your two hips move: r-h-y-t-h-m.", true],
  ["Which word comes from the Latin root “aud” (hear)?", "audience", ["adventure", "ancient", "animal"], "An audience is a group that hears.", true],
  ["The word “unbelievable” has how many parts?", "three: un-, believe, -able", ["one", "two", "four"], "Prefix + base + suffix.", true],
  ["Which sentence uses a discipline-specific word correctly?", "The photosynthesis in the leaves made glucose.", ["The photosynthesis ate the rain.", "The photosynthesis was a big building.", "The photosynthesis sang loudly."], "Technical words must fit their meaning.", true],
];

const INCLUSIVE: Q[] = [
  ["Inclusive language is language that…", "makes everyone feel respected and welcome", ["only uses long words", "leaves out some people", "is only used in books"], "Words can build or break belonging."],
  ["Which phrase is more inclusive?", "Hello, everyone", ["Hey, guys", "Hello, boys only", "Hey, you people"], "Choose words that include all."],
  ["A stereotype is…", "a fixed, oversimplified idea about a group of people", ["a fact checked by experts", "a type of poem", "a list of sources"], "Stereotypes ignore how different people are."],
  ["Which sentence is a stereotype?", "All teenagers are lazy.", ["Some teenagers volunteer.", "My cousin plays hockey.", "Many teenagers work part-time."], "“All” turns a trait into a label for everyone."],
  ["When you read a story that shows a group in an unfair way, a good first step is to…", "notice it and explain how it makes you feel, with evidence from the text", ["ignore it", "agree without thinking", "stop reading forever"], "Use text evidence to explain your reaction."],
  ["A one-sided view is…", "a view that shows only one perspective", ["a view that includes many viewpoints", "a map", "a graph"], "Look for who is missing."],
  ["Which question helps you spot an unfair representation?", "Whose voice is missing from this text?", ["How many pages are there?", "What is the font?", "Who printed it?"], "Check who is left out."],
  ["Discriminatory language is language that…", "treats people unfairly because of who they are", ["describes the weather", "explains a recipe", "gives directions"], "It harms and excludes."],
  ["A character in a book only speaks in a certain accent and is always the joke. This may be…", "an unfair representation", ["good humour for everyone", "a fact", "an index"], "Jokes at a group's expense are not fair."],
  ["You are confused by a text that says one group is “better” than another. What should you do?", "ask what evidence supports the claim", ["accept it", "repeat it", "hide it"], "Question claims that rank people."],
  ["Which statement shows agreement with a text, with a reason?", "I agree with the author because the survey included students from many schools.", ["I agree because it is good.", "I do not know.", "It was long."], "Give a reason from the text."],
  ["Which word choice is more respectful for a person who uses a wheelchair?", "a person who uses a wheelchair", ["a wheelchair-bound victim", "a cripple", "that poor person"], "Use language that focuses on the person."],
  ["Why do writers choose words carefully when writing about communities?", "to be accurate and respectful", ["to use as few words as possible", "to sound mysterious", "to avoid facts"], "Careful words avoid hurting or misleading."],
  ["Which sentence is NOT a stereotype?", "Some people in our town speak three languages.", ["Girls are bad at science.", "Old people cannot use computers.", "Boys never cry."], "It describes some people without a rule about a whole group."],
  ["You see an ad where only one kind of family is shown. What can you say?", "the ad leaves out many families", ["the ad shows everyone", "the ad is a map", "the ad is a poem"], "Notice who is shown and who is not."],
  ["What is a respectful way to disagree with a classmate?", "“I see it differently because…”", ["“That is stupid.”", "“You always get it wrong.”", "“Be quiet.”"], "State your view and your reason."],
  ["Words like “always” and “never” about a group are often a sign of…", "stereotyping", ["a fact", "a verb", "a plural"], "Real groups have many differences.", true],
  ["A news article about a town quotes only people who agree with the writer. This is…", "a one-sided view", ["a balanced report", "a primary source", "a poem"], "A fair article includes several viewpoints.", true],
  ["How can language shape an inclusive classroom?", "by using each person's name and pronouns correctly and avoiding put-downs", ["by teasing quietly", "by using nicknames people dislike", "by ignoring some students"], "Respectful words build belonging.", true],
  ["You notice a text uses “they” for a group and “we” for the writer's group in a way that sounds unfair. This is…", "language that separates people into “us” and “them”", ["neutral wording", "a title", "a table of contents"], "Pronouns can include or exclude.", true],
  ["Which revision is most inclusive?", "Firefighters work together to keep us safe.", ["Firemen work together to keep us safe.", "Fire guys work together to keep us safe.", "Men work together to keep us safe."], "Choose job names that don't assume gender.", true],
  ["After reading a biased article, what helps you decide whether it is fair?", "compare it with other sources", ["agree with the first sentence", "count the words", "ignore the author"], "Different sources show different viewpoints.", true],
  ["A speaker says, “That group is just like that.” Which question is best?", "“What evidence supports that?”", ["“Who cares?”", "“Is that your coat?”", "“Can you say it louder?”"], "Ask for evidence, not just reaction.", true],
  ["Why is asking questions kindly useful when exploring ideas in a group?", "it invites others to explain without feeling attacked", ["it ends the discussion", "it makes people leave", "it hides the topic"], "Kind, multifaceted questions open up discussion.", true],
  ["Which question is multifaceted and seeks clarification?", "“Can you explain what you mean, and how does that connect to the problem?”", ["“Yes?”", "“No?”", "“OK?”"], "Strong questions ask for reasons and connections.", true],
  ["You want the group to feel safe sharing ideas. Which action helps?", "listening without interrupting and thanking people for ideas", ["laughing at mistakes", "rolling your eyes", "talking over others"], "Respectful habits build inclusive environments.", true],
];

const REFLECT: Q[] = [
  ["Reflection means…", "thinking about what you did and how to improve", ["only getting a mark", "copying work", "finishing early"], "Reflection builds learning."],
  ["A learning goal is…", "something specific you want to get better at", ["a prize you win", "a school rule", "a type of test"], "Make the goal clear and doable."],
  ["Which is the most specific goal?", "I will check my work for capital letters before I hand it in.", ["I will do better.", "I will try hard.", "I will be good."], "Specific goals tell you exactly what to do."],
  ["Which goal can you measure?", "I will read for 20 minutes on four days this week.", ["I will read more.", "I will like reading.", "I will be smart."], "A measurable goal has numbers."],
  ["Descriptive feedback tells you…", "what you did well and what to work on next", ["only your mark", "that you are good or bad", "nothing at all"], "It names strengths and next steps."],
  ["Which is descriptive feedback?", "Your opening grabs attention. Add a detail about the setting in paragraph two.", ["Good job.", "Fine.", "Better next time."], "It is specific."],
  ["A classmate says your explanation is missing a step. What is the best response?", "think about how to add that step", ["argue that you are right", "ignore it", "tear up the page"], "Use feedback to strengthen your work."],
  ["An exit ticket is…", "a quick note at the end of a lesson about what you learned", ["a train ticket", "a final exam", "a library card"], "It helps you check your understanding."],
  ["A digital portfolio helps you…", "collect and show your work over time", ["lose your work", "hide your work", "erase your work"], "It shows growth."],
  ["Why do students help create class criteria?", "so everyone understands what good work looks like", ["so the teacher does less", "so there are no marks", "so the work is shorter"], "Clear criteria guide the work."],
  ["Which question helps you compare your strategies with others?", "How does my approach compare to others', and what could I try?", ["Who finished first?", "Who is best?", "Who is quiet?"], "Reflect on strategies, not on ranking."],
  ["Tracking your growth means…", "collecting evidence of what you have learned over time", ["counting your absences", "hiding your marks", "comparing yourself only to the top student"], "Evidence shows progress."],
  ["Which is good evidence of progress in writing?", "an earlier draft next to a revised draft", ["a blank page", "a title only", "a pencil case"], "Compare before and after."],
  ["After setting a goal, what is the next step?", "plan the steps to reach it", ["forget it", "wait for someone else", "change the subject"], "A plan makes a goal possible."],
  ["You set a goal to use more precise verbs. Which step helps?", "highlight vague verbs in a draft and swap them", ["add more pictures", "write longer paragraphs", "use a bigger font"], "A clear action step matches the goal."],
  ["Which statement is a strong self-reflection?", "I used my notes to write a clearer summary, and next time I'll check the order of events.", ["It was fine.", "I did it.", "I don't know."], "It names what worked and what to do next."],
  ["Reflecting on being a listener, which question is most useful?", "Did I wait for the speaker to finish before I responded?", ["Was the room warm?", "Was I first?", "Did I finish early?"], "Reflect on your own listening habits.", true],
  ["Your goal is to read more fluently. Which strategy supports it?", "reread a passage aloud, paying attention to expression and rate", ["skip the hard parts", "read as fast as you can", "avoid reading aloud"], "Fluency includes accuracy, expression and rate.", true],
  ["Why is it helpful to receive feedback while you are still working?", "you can change your work before it is final", ["it is too late to change anything", "it replaces the work", "it makes the work longer"], "Feedback during a project helps you improve.", true],
  ["Which is a good way to respond to feedback you disagree with?", "ask a question to understand it, then decide what to try", ["say it is wrong without listening", "stop working", "ask for a new teacher"], "Listen first, then decide.", true],
  ["A fluent reader reads with…", "accuracy, expression and a comfortable rate", ["the highest speed possible", "no pauses at all", "a robotic voice"], "Fluency helps comprehension.", true],
  ["Which sentence shows a student monitoring their progress?", "My quiz scores went from 5 to 8 out of 10 since I started reviewing my notes.", ["I like quizzes.", "Quizzes are on Fridays.", "I forgot my pencil."], "It uses evidence to track growth.", true],
  ["What should you do with a goal that is too big?", "break it into smaller steps", ["give up", "make it bigger", "hide it"], "Small steps are easier to reach.", true],
  ["Which is a supportive way to give feedback to a classmate?", "“I liked your opening. One thing to try is adding an example in your second paragraph.”", ["“This is bad.”", "“Everything is perfect.”", "“I stopped reading.”"], "Mention a strength and a next step.", true],
  ["After a unit, you compare how you learned in math and in language arts. This is…", "reflecting on your learning strategies", ["a spelling test", "a map exercise", "a copying task"], "Strategies can transfer between subjects.", true],
];

export const units: Unit[] = [
  bankUnit({
    id: "mb-research-8",
    title: "Research & Inquiry",
    emoji: "🔎",
    blurb: "Ask questions, check sources, gather evidence",
    parentNote: "Children practise asking open questions, using what they already know, judging whether sources are reliable or biased, and noting evidence from more than one source.",
    standards: ["ELA.8.B1.1, ELA.8.B1.2, ELA.8.B1.3, ELA.8.B1.4, ELA.8.C1.2", "prior knowledge, open-ended questions, working with others, evidence from multiple sources and judging reliability"],
    items: RESEARCH,
  }),
  bankUnit({
    id: "mb-planning-forms-8",
    title: "Plan, Form & Voice",
    emoji: "📝",
    blurb: "Pick a text form, organize ideas, find your voice",
    parentNote: "Children choose a text form for a purpose and audience, group ideas with patterns such as cause and effect, and match tone and voice to what they are writing.",
    standards: ["ELA.8.C1.1, ELA.8.C1.3, ELA.8.C1.4, ELA.8.C1.5, ELA.8.C2.1, ELA.8.C2.4, ELA.8.C3.5", "choosing a form for purpose and audience, planning tools, organizational patterns, voice and tone, and multimodal forms"],
    items: WRITING_PLAN,
  }),
  bankUnit({
    id: "mb-word-power-8",
    title: "Precise Words & Spelling",
    emoji: "🔤",
    blurb: "Spelling rules, word parts and exact vocabulary",
    parentNote: "Children use word families, prefixes, suffixes and spelling rules, choose precise words for a subject, and use word-processing tools to format a document.",
    standards: ["ELA.8.C2.3, ELA.8.C3.1, ELA.8.C3.2", "discipline-specific vocabulary, formatting a digital document and spelling strategies, derivatives and bases"],
    items: WORDS,
  }),
  bankUnit({
    id: "mb-fair-language-8",
    title: "Fair & Inclusive Language",
    emoji: "🤝",
    blurb: "Spot stereotypes and one-sided views",
    parentNote: "Children learn how word choice can include or leave people out, notice stereotypes and one-sided views in texts, and explain their reaction using evidence.",
    standards: ["ELA.8.A1.3, ELA.8.A1.4, ELA.8.B3.4", "language that shapes inclusive environments, asking multifaceted questions, and responding to stereotypes and unfair representations"],
    items: INCLUSIVE,
  }),
  bankUnit({
    id: "mb-reflect-8",
    title: "Goals & Feedback",
    emoji: "🎯",
    blurb: "Set goals, use feedback, track growth",
    parentNote: "Children practise setting specific learning goals, using feedback, tracking evidence of growth and thinking about reading fluency.",
    standards: ["ELA.8.A2.6, ELA.8.D2.1, ELA.8.D2.2, ELA.8.D2.3, ELA.8.D2.4, ELA.8.D2.5", "fluency, comparing strategies, class criteria, feedback, learning goals and tracking progress"],
    items: REFLECT,
  }),
];
