import type { Unit } from "../../types";
import { bankUnit, type Q } from "../own";

// Grade 8 science: water's properties and how water shapes Earth's surface (SCI.8.E.6, SCI.8.E.14), and the
// nature of science, technology and scientific skills (SCI.8.A to D).

const WATER: Q[] = [
  ["At normal pressure, water freezes at…", "0 °C", ["10 °C", "50 °C", "100 °C"], "Pure water turns to ice at 0 °C."],
  ["At normal pressure, water boils at…", "100 °C", ["0 °C", "50 °C", "212 °C"], "Boiling point is 100 °C (212 °F)."],
  ["Heat capacity is…", "how much heat a substance can absorb before its temperature rises a lot", ["how fast water flows", "the mass of water", "how clear water is"], "Water has a very high heat capacity."],
  ["Why do large lakes keep nearby summers cooler and winters milder?", "water heats up and cools down slowly", ["water makes its own heat", "water has no heat capacity", "lakes are always warm"], "High heat capacity moderates climate."],
  ["Ice floats on water because ice is…", "less dense than liquid water", ["more dense than liquid water", "heavier than water", "made of a different substance"], "Water expands as it freezes."],
  ["What happens to the volume of water as it freezes?", "it expands", ["it shrinks", "it stays the same", "it disappears"], "Frozen pipes can burst."],
  ["Why is it important that ice floats on lakes?", "fish and other living things survive in liquid water below", ["it makes the lake saltier", "it stops all rain", "it makes the lake deeper"], "Ice insulates the water underneath."],
  ["Water drops form round beads on a waxy leaf because of…", "surface tension", ["gravity only", "magnetism", "evaporation"], "Water particles attract one another."],
  ["Cohesion is…", "the attraction between particles of the same substance", ["the attraction between water and glass", "the melting of ice", "the boiling of water"], "Water particles stick together."],
  ["Adhesion is…", "the attraction between water and other substances", ["the attraction between water particles only", "the freezing of water", "the weight of water"], "Water climbs up a thin tube because of adhesion."],
  ["Water is called the “universal solvent” because…", "it can dissolve many substances", ["it dissolves everything", "it never dissolves anything", "it is the lightest liquid"], "Many, though not all, substances dissolve in water."],
  ["Which is a solution?", "salt dissolved in water", ["sand in water", "oil on water", "pebbles in a bucket"], "In a solution, the particles are mixed evenly."],
  ["About how much of Earth's surface is covered by water?", "about 70 percent", ["about 10 percent", "about 30 percent", "about 100 percent"], "Earth is called the blue planet."],
  ["Most of Earth's water is…", "salt water in the oceans", ["fresh water in lakes", "fresh water in rivers", "water in clouds"], "Only a small share is fresh water."],
  ["Most of Earth's fresh water is stored as…", "ice in glaciers and ice sheets", ["lake water", "river water", "rain in clouds"], "Frozen water holds more than two thirds of it."],
  ["Water changes from liquid to gas by…", "evaporation", ["condensation", "freezing", "erosion"], "Heat gives particles energy to escape."],
  ["Water vapour changing into liquid droplets is…", "condensation", ["evaporation", "deposition of soil", "melting"], "Clouds form by condensation."],
  ["Which is a stage of the water cycle?", "precipitation", ["combustion", "erosion only", "photosynthesis"], "Rain and snow are precipitation."],
  ["Erosion is…", "the wearing away and moving of rock and soil", ["the building of mountains", "the freezing of water", "the melting of rock inside Earth"], "Water, wind and ice erode."],
  ["Deposition is…", "the dropping of material that water, wind or ice carried", ["the wearing away of rock", "the freezing of water", "the heating of soil"], "Sediment settles where the water slows."],
  ["Where does a river usually deposit the most sediment?", "where it slows down, such as at its mouth", ["on a steep mountain", "in a waterfall", "at its source only"], "Slow water cannot carry as much."],
  ["A delta forms where…", "a river slows and drops sediment as it enters a larger body of water", ["a glacier melts", "wind blows sand", "a volcano erupts"], "Sediment builds up in a fan shape."],
  ["A watershed is…", "the land area that drains into a river, lake or ocean", ["a building for storing water", "a type of dam", "a kind of cloud"], "Everything that falls there flows to the same place."],
  ["Which is a possible cause of flooding?", "heavy rain or fast snowmelt that a river can't carry", ["too little rain", "a dry spring", "cold nights only"], "Floods happen when there is more water than the channel can hold."],
  ["The Red River in Manitoba floods in some springs because…", "snow melts and the river flows north over very flat land", ["the river runs uphill", "it never rains", "the river is frozen all year"], "The flat land and northward flow can cause ice jams and spreading water."],
  ["Which feature does a glacier shape?", "U-shaped valleys", ["volcanoes", "coral reefs", "dunes in a desert"], "Moving ice carves wide valleys."],
  ["An ice age is…", "a long period of colder climate with large ice sheets", ["a single cold week", "a winter storm", "a kind of flood"], "Ice ages last thousands of years.", true],
  ["Glacial Lake Agassiz, which once covered much of Manitoba, formed when…", "melting glaciers filled a basin with water", ["a volcano erupted", "a river dried up", "an asteroid hit"], "Meltwater from retreating ice ponded in front of the ice sheet.", true],
  ["Why does the fertile soil in Manitoba's Red River Valley owe much to the old lake?", "the lake left fine sediment on its bed", ["glaciers dissolved the rock", "wind carried it from far away only", "it was made by farmers"], "Deposition from Glacial Lake Agassiz created flat, rich land.", true],
  ["Which property of water explains why a sweating body cools?", "evaporation takes away heat", ["water is heavy", "water freezes", "water is clear"], "Evaporating water absorbs heat energy from skin.", true],
  ["When water freezes in rock cracks and thaws again and again, the rock…", "breaks apart over time", ["grows larger", "becomes a river", "turns into a glacier"], "Ice expands and pries rock apart.", true],
  ["A meander is…", "a winding bend in a river", ["a straight canal", "a type of lake", "a waterfall"], "Rivers erode the outer bank and deposit on the inner bank.", true],
];

const EVIDENCE: Q[] = [
  ["Empirical data is information gathered by…", "observation and measurement", ["guessing", "opinions alone", "wishing"], "Science relies on evidence."],
  ["Why do scientists collect data systematically?", "so others can check and repeat the results", ["so the data is hidden", "to make it longer", "to win a prize"], "Careful methods allow checking."],
  ["Peer review is when…", "other experts check a study before it is published", ["friends say it is nice", "the author reviews alone", "the study is ignored"], "Peers look for errors."],
  ["Why is peer review useful?", "it helps catch mistakes and weak reasoning", ["it makes studies secret", "it removes all data", "it guarantees a study is perfect"], "Reviewers ask hard questions."],
  ["Bias in an experiment is…", "something that unfairly pushes results in one direction", ["a measurement tool", "a unit of volume", "a lab coat"], "Scientists try to reduce bias."],
  ["Which is an example of bias in sampling?", "surveying only students on the basketball team about favourite sports", ["surveying a random mix of students", "using a large sample", "measuring with a calibrated tool"], "Sampling bias means the sample doesn't represent the group."],
  ["Confirmation bias is…", "paying attention only to evidence that agrees with what you already think", ["checking every result", "ignoring your own results", "measuring in metric"], "It's a trap for every thinker."],
  ["Which step helps reduce bias in an experiment?", "using a fair test with repeated trials", ["choosing results you like", "doing a test only once", "changing everything at once"], "Repeat trials and control variables."],
  ["Why is a conclusion reviewed after an experiment?", "to detect errors and check it matches the data", ["to change the data", "to hide the method", "to make it shorter"], "Conclusions must follow from the evidence."],
  ["A model in science is…", "a representation that helps explain or predict something", ["an exact copy of the real thing", "a final answer", "a belief with no evidence"], "Models are tools for understanding."],
  ["Which is a physical model?", "a globe of Earth", ["a story", "a poem", "a rumour"], "A physical model can be held or seen."],
  ["Which is a mathematical model?", "an equation that predicts how far a ball will travel", ["a toy car", "a diagram on a wall", "a sculpture"], "Maths can describe patterns."],
  ["A computer simulation is useful when…", "a real experiment is too dangerous, large or slow", ["you want no data", "you do not need to test", "the real thing is a toy"], "Simulations let scientists test ideas safely."],
  ["Why is a model like a metaphor?", "it represents something without being the thing itself", ["it is the real thing", "it is a type of unit", "it is always wrong"], "Models simplify reality."],
  ["Every model has limits. Which is a limit of a globe?", "it does not show Earth's real size", ["it shows places", "it has a legend", "it can be turned"], "Models leave some things out."],
  ["The Solar System model is…", "well established, supported by lots of evidence", ["tentative and unsupported", "a made-up story", "unchanged for all time"], "Many observations support it."],
  ["Which model is more tentative?", "a model of what happens inside a black hole", ["the model of the water cycle", "the model of Earth orbiting the Sun", "the model of day and night"], "Some ideas are still being tested."],
  ["When new evidence doesn't fit a model, scientists may…", "revise or replace the model", ["ignore the evidence", "stop doing science", "hide the evidence"], "Science changes as evidence changes."],
  ["Why can a well-established model still be improved?", "new tools and evidence can add detail", ["because it is always wrong", "because scientists dislike it", "because it was never tested"], "Models are refined over time."],
  ["Which of these shows a scientist treating evidence fairly?", "reporting results even when they surprise her", ["leaving out data that doesn't fit", "changing numbers", "stopping the study early"], "Honest reporting matters."],
  ["A claim is supported by evidence when…", "data from careful tests backs it up", ["many people repeat it", "it is on a poster", "someone famous says it"], "Evidence matters more than popularity."],
  ["Which question best tests a scientific claim?", "What evidence supports this?", ["Who said it first?", "Is it popular?", "Is it exciting?"], "Ask for the evidence."],
  ["Replication means…", "other scientists repeat a study and check if they get similar results", ["copying someone's data", "changing the question", "deleting results"], "Repeatable results are trusted more.", true],
  ["A researcher's funder would benefit from a certain result. What can help keep the research fair?", "independent peer review", ["hiding the data", "skipping the report", "using only one trial"], "Outside review reduces bias.", true],
  ["A weather model predicts rain, but it does not rain. What is the best conclusion?", "the model is useful but has limits and can be improved", ["models are useless", "the weather broke the rules", "the model was never needed"], "Models give likelihoods, not guarantees.", true],
  ["A graph in a report leaves out the first year of data that showed a decline. This may be…", "an example of bias", ["good practice", "required by science", "peer review"], "Leaving out data can mislead.", true],
  ["Which statement best describes how science handles an error found in a published study?", "the error is reported and the conclusions are corrected", ["the error is hidden", "science stops", "the study is always right"], "Correction is part of science.", true],
  ["Why do scientists share their methods and data publicly?", "so others can check, repeat and build on the work", ["to make the work harder", "to keep it secret", "to avoid review"], "Open sharing strengthens knowledge.", true],
];

const TECH: Q[] = [
  ["Technology is…", "tools and methods people design to solve problems", ["only computers", "only machines in factories", "only things made of metal"], "A pencil is technology too."],
  ["When choosing the best solution to a problem, which question should you ask?", "What materials, costs and effects on people and the environment are involved?", ["Which is the prettiest?", "Which is the loudest?", "Which is the newest?"], "Optimal solutions balance many factors."],
  ["Which factor is part of choosing a design for a bridge?", "the cost of materials", ["the colour of the designer's shirt", "the day of the week", "the designer's favourite song"], "Cost, strength and safety matter."],
  ["A new lake dock would harm local fish. What does this show?", "design should consider effects on animals and the environment", ["fish don't matter", "docks are never useful", "all design is the same"], "Environmental effects are part of the decision."],
  ["Engineers often test several ideas before choosing one. This shows that…", "solving problems often takes many strategies", ["the first idea is always best", "testing is a waste", "problems have one answer"], "Trying and improving is normal."],
  ["Which is a strategy for solving a design problem?", "making a drawing or model first", ["guessing and building at once", "ignoring the problem", "copying without thinking"], "Drawings and models help test ideas."],
  ["A prototype is…", "a first test version of a design", ["a final product", "a broken tool", "a rule"], "Testing prototypes finds problems early."],
  ["Mathematical modelling in design can help by…", "predicting how a design will perform before it is built", ["replacing every test", "hiding problems", "making it cost more"], "Calculations save time and materials."],
  ["Antibiotics help people recover from bacterial infections. A predictable benefit is…", "better health", ["more traffic", "more clouds", "taller buildings"], "Medicines are designed to improve life."],
  ["Overusing antibiotics can lead to…", "bacteria that resist the medicines", ["stronger bones", "faster plants", "colder weather"], "This is an unforeseen consequence."],
  ["An unforeseen consequence is…", "an effect nobody expected", ["an effect that was planned", "a type of prediction", "a test"], "Technologies can have effects their designers did not expect."],
  ["Plastic was invented to be light and strong. A later consequence is…", "plastic waste that lasts in the environment", ["no packaging", "fewer plants", "clean oceans"], "Long-lasting plastic can harm ecosystems."],
  ["Pesticides help protect crops. An unwanted effect can be…", "harm to insects like bees", ["cleaner rivers", "more rain", "stronger sunlight"], "Technology can have positive and negative effects."],
  ["Why do societies re-evaluate a technology?", "because new information shows its impacts", ["because the technology is old", "because it is fun", "because it is quiet"], "Decisions can change when we learn more."],
  ["When a technology is found to harm health, communities might…", "change, limit or stop using it", ["ignore the harm", "use more of it", "hide the study"], "Societies can modify or end a technology."],
  ["Leaded gasoline was phased out because…", "lead was found to harm people's health", ["it cost too little", "it was too clean", "cars no longer needed fuel"], "New evidence changed the decision."],
  ["Which is a way people can decide whether to keep using a technology?", "weigh the benefits and the risks", ["follow the loudest voice", "choose at random", "never review it"], "Good decisions consider evidence."],
  ["Which helps you decide if a new product is a good solution?", "testing it and asking who it helps and who it might harm", ["reading the ad only", "asking only the seller", "ignoring costs"], "Consider everyone affected."],
  ["Renewable energy such as wind power is attractive because it…", "does not burn fossil fuels to make electricity", ["costs nothing", "needs no materials", "has no effects at all"], "It has benefits, but also trade-offs such as land use."],
  ["Every technology has trade-offs. This means…", "it brings both benefits and costs", ["it is only good", "it is only bad", "it never changes"], "Weigh both sides."],
  ["A town wants to build a wind farm. Which is a factor to weigh?", "effects on birds, noise, cost and clean energy", ["only the colour of the turbines", "only the speed of the wind", "none of these"], "Optimal solutions weigh many factors.", true],
  ["A medicine works well but has a rare side effect. What is the best response?", "monitor the use and share what is learned", ["hide the side effect", "give it to everyone with no warning", "stop all research"], "Ongoing review is part of responsible use.", true],
  ["Which describes a predictable consequence of the invention of the car?", "people can travel farther in less time", ["more trees grow", "oceans freeze", "stars move"], "Faster travel was a designed benefit.", true],
  ["Which describes an unforeseen consequence of the invention of the car?", "increased air pollution in cities", ["faster travel", "easier trips", "a new way to travel"], "Early inventors didn't expect smog.", true],
  ["A group wants to decide whether to ban a pesticide. Which action is most scientific?", "review the research on its effects and consult experts", ["decide on feeling alone", "ask one person", "pick at random"], "Evidence guides decisions.", true],
];

const MEASURE: Q[] = [
  ["Which tool measures temperature?", "thermometer", ["pan balance", "ruler", "stopwatch"], "Thermometers measure in degrees Celsius."],
  ["Which tool measures mass?", "balance", ["thermometer", "graduated cylinder", "ruler"], "Mass is measured in grams or kilograms."],
  ["Which tool measures the volume of a liquid?", "graduated cylinder", ["metre stick", "thermometer", "pan balance"], "It has a scale in millilitres."],
  ["Which tool measures length?", "ruler", ["thermometer", "balance", "graduated cylinder"], "Metric units: mm, cm, m."],
  ["What unit is used for the volume of liquid in a graduated cylinder?", "millilitres (mL)", ["grams", "degrees", "kilometres"], "mL measures liquid volume."],
  ["What unit is used for mass in the lab?", "grams (g)", ["litres", "degrees Celsius", "newtons"], "Mass uses g and kg."],
  ["What unit is used for temperature in the lab?", "degrees Celsius (°C)", ["grams", "centimetres", "mL"], "Science uses the Celsius scale."],
  ["When reading a graduated cylinder, you should look at the liquid…", "at eye level at the bottom of the curve", ["from above", "from far away", "with your eyes closed"], "The curved surface is called the meniscus."],
  ["The curved top of a liquid in a tube is called the…", "meniscus", ["median", "mixture", "magnet"], "Read the bottom of the curve."],
  ["Before using a balance, you should…", "make sure it is zeroed", ["add extra weight", "tilt it", "press down on it"], "Zeroing makes the reading accurate."],
  ["Why do scientists repeat measurements?", "to check that results are reliable", ["to waste time", "to make the numbers bigger", "because one is never enough for any task"], "Repeated trials reduce error."],
  ["Which would be a safe way to carry a microscope?", "with two hands, one under the base", ["by the eyepiece only", "with one hand by the stage", "by its cord"], "Handle equipment with care."],
  ["What should you do first when using a microscope?", "start with the lowest power lens", ["start with the highest power lens", "touch the lens with your fingers", "shine the lamp in your eyes"], "Use the low power to find the specimen."],
  ["Which safety item protects your eyes in the lab?", "safety goggles", ["a hat", "sunglasses", "a scarf"], "Wear goggles with chemicals or heat."],
  ["Hot glassware should be handled with…", "tongs or heat-resistant gloves", ["bare hands", "wet fingers", "a cloth that is soaking wet"], "Use the right equipment."],
  ["If a chemical splashes on your skin, you should first…", "tell your teacher and rinse with water", ["wait to see what happens", "wipe it on your shirt", "hide it"], "Tell an adult right away."],
  ["Why should you never taste substances in the lab?", "they may be harmful", ["they are always sweet", "they have no taste", "it is polite"], "Chemicals are not food."],
  ["Which hazard symbol system tells you about dangerous chemicals in Canada?", "WHMIS", ["PIN code", "GPS", "ISBN"], "WHMIS stands for Workplace Hazardous Materials Information System."],
  ["A prism can be used to…", "split white light into colours", ["measure mass", "heat water", "cut glass"], "Light bends differently by colour."],
  ["A hot plate should be used…", "with adult supervision and heat-safe containers", ["alone with plastic", "without checking the cord", "with wet hands"], "Heat sources need extra care."],
  ["A scientist asks, “How does the temperature of water affect how fast sugar dissolves?” What is the variable she changes?", "the water temperature", ["the amount of sugar only", "the colour of the cup", "the day of the week"], "The changed variable is the independent variable."],
  ["In the same test, what is the variable she measures?", "the time the sugar takes to dissolve", ["the water temperature", "the cup size", "the room colour"], "The measured variable depends on what you change."],
  ["Which should be kept the same in a fair test?", "the amount of sugar and water", ["the variable you change", "the results", "the measurements"], "Controlled variables are kept constant."],
  ["Which is an observation (rather than an inference)?", "The solution turned blue.", ["The solution must be a base.", "The experiment failed.", "The chemical is old."], "Observations describe what you see, hear, measure.", true],
  ["Which practice helps you analyze data?", "make a table and a graph", ["delete the numbers", "round everything to zero", "write only a title"], "Organized data show patterns.", true],
  ["A measurement is recorded as 25. What is missing?", "the unit", ["the colour", "the date only", "the name of the school"], "Always record a number with its unit.", true],
  ["A line graph of water temperature against time rises and then levels off at 100 °C. What does the level part show?", "the water is boiling", ["the water froze", "the thermometer broke", "the water stopped being water"], "Temperature stays constant at the boiling point.", true],
  ["How should you measure the mass of a liquid in a beaker?", "find the mass of the empty beaker, then with liquid, and subtract", ["weigh the liquid in your hands", "guess", "use a ruler"], "Subtract the container's mass.", true],
];

const WORLD: Q[] = [
  ["Curiosity helps scientists because it…", "leads to new questions", ["stops research", "makes data disappear", "replaces testing"], "Questions are where science starts."],
  ["Which attitude is useful in science?", "being open-minded and willing to change your ideas with new evidence", ["refusing to listen", "always being sure", "never asking questions"], "Scientists update ideas."],
  ["Scientists show honesty by…", "reporting results accurately", ["picking only good results", "changing numbers", "hiding methods"], "Honesty builds trust."],
  ["Perseverance in science means…", "keeping going after a test does not work", ["quitting at the first problem", "avoiding mistakes", "skipping steps"], "Failed tests teach scientists."],
  ["Indigenous peoples in Manitoba and across Canada have observed the land, water, weather and animals closely for many generations. This knowledge is…", "a way of understanding the world, passed on over time", ["only a story with no use", "the same for every Nation", "no longer important"], "Many First Nations, Métis and Inuit communities hold their own knowledge, and it differs from place to place."],
  ["Which is an example of observing the natural world?", "noticing patterns in ice thickness, animal tracks or the stars over many seasons", ["guessing without looking", "reading only one book", "ignoring weather"], "Careful, repeated observation is shared by many ways of knowing."],
  ["Why is it respectful to learn from Elders and Knowledge Keepers with permission?", "their knowledge belongs to them and their communities", ["it is free to take", "they have no knowledge", "it is not needed"], "Ask first and give credit."],
  ["Which statement is most accurate?", "Many First Nations, Métis and Inuit communities have their own ways of knowing and of caring for the land.", ["All Indigenous peoples share one set of beliefs.", "Indigenous knowledge is only history.", "Science only comes from labs."], "Say “many” or “some”, not “all”."],
  ["Which job uses science to help people stay healthy?", "nurse", ["pilot only", "author only", "painter only"], "Many jobs link to science."],
  ["Which hobby uses science ideas?", "baking, since heat changes the ingredients", ["staring at a wall", "colouring only", "none of these"], "Science is part of everyday activities."],
  ["A solar energy technician uses science about…", "light, electricity and materials", ["only music", "only history", "only grammar"], "Careers connect to science ideas."],
  ["A mechanic uses science ideas such as…", "force, friction and energy", ["ancient languages", "poetry rhythm", "folk songs"], "Engines are full of physics."],
  ["A painter uses science when…", "mixing pigments that reflect light in different ways", ["avoiding colour", "never using a brush", "deciding the weather"], "Colour comes from how materials reflect light."],
  ["A group wants to reduce plastic waste in their school. This is an example of…", "taking action on a local STSE issue", ["a spelling test", "a map project", "a daydream"], "STSE stands for science, technology, society and the environment."],
  ["How could a class take action about the safety of too much screen time?", "research the effects and share tips with the school", ["ignore it", "tell everyone to stop with no reason", "hide the data"], "Action starts with evidence."],
  ["Which is a STSE issue that could be investigated at school?", "the energy used by lighting in the building", ["the colour of a pencil", "the page numbers in a book", "a favourite song"], "STSE issues connect science to society."],
  ["Which is a good first step before taking action on an issue?", "collect information from reliable sources", ["decide you already know", "ask nobody", "write a slogan only"], "Evidence comes first."],
  ["Why does it help to feel that science is for you?", "it builds confidence to ask questions and try things", ["it ends all questions", "it stops learning", "it means you are always right"], "A sense of belonging supports learning.", true],
  ["Which statement is a scientific attitude toward a mistake?", "“I'll look at what happened and try again.”", ["“I'm no good at this.”", "“Delete it.”", "“Don't tell anyone.”"], "Mistakes give information.", true],
  ["Someone says all knowledge must come from labs. A respectful reply is…", "many cultures observe and understand the world in their own ways", ["only labs matter", "be quiet", "that is silly"], "Different knowledge systems can each tell us something.", true],
  ["Which of these links science with a career in the community?", "an electric vehicle specialist who studies batteries and motors", ["a person who never uses tools", "a person who avoids reading", "no career does"], "Lots of careers use science.", true],
  ["Wearing a helmet when cycling is a science-based decision because…", "tests show helmets reduce head injuries", ["it looks nice", "it is a rule with no reason", "everyone does it"], "Evidence supports safety rules.", true],
  ["A community group studies how different forms of radiation exposure affect people (for example, UV light). What should the group use?", "reliable data and advice from experts", ["rumours", "one ad", "a guess"], "Link actions to evidence.", true],
  ["When two students investigate the same question and get different answers, a scientist would…", "compare their methods to find the difference", ["decide who is smarter", "ignore both", "throw out the data"], "Different methods can lead to different results.", true],
  ["Which skill is shared by scientists, artists and mechanics?", "careful observation", ["not paying attention", "avoiding questions", "never using tools"], "Observation is useful in many careers and hobbies.", true],
  ["Why do scientists share findings with the public?", "so people can make informed decisions", ["to hide results", "to avoid questions", "to confuse people"], "Science works best when shared.", true],
];

export const units: Unit[] = [
  bankUnit({
    id: "mb-water-8",
    title: "Water: Properties & Landforms",
    emoji: "💧",
    blurb: "Why water is special and how it shapes the land",
    parentNote: "Children learn why water's properties matter for climate and living things, and how water, ice and flooding shape Earth's surface, including Manitoba landforms.",
    standards: ["SCI.8.E.6, SCI.8.E.14", "the properties of water and the role of water in shaping Earth's surface"],
    items: WATER,
  }),
  bankUnit({
    id: "mb-evidence-models-8",
    title: "Evidence, Bias & Models",
    emoji: "🧪",
    blurb: "How scientists test, check and model ideas",
    parentNote: "Children practise how scientists collect evidence, reduce bias, use peer review and rely on models that can be well established or still tentative.",
    standards: ["SCI.8.D.1, SCI.8.D.3, SCI.8.D.4", "systematic data, peer review, bias, and well-established and tentative models"],
    items: EVIDENCE,
  }),
  bankUnit({
    id: "mb-tech-choices-8",
    title: "Technology Choices",
    emoji: "⚙️",
    blurb: "Weigh benefits, costs and surprises",
    parentNote: "Children think about how to find the best solution to a problem, why designers try several strategies, and how technologies can have expected and unexpected effects that societies review.",
    standards: ["SCI.8.D.5, SCI.8.D.6, SCI.8.D.7, SCI.8.D.8", "optimal solutions, design strategies, consequences of technology and re-evaluating technologies"],
    items: TECH,
  }),
  bankUnit({
    id: "mb-lab-skills-8",
    title: "Measuring & Lab Safety",
    emoji: "🥽",
    blurb: "Tools, units, fair tests and safe habits",
    parentNote: "Children practise choosing the right tool and unit, reading measurements, planning fair tests and working safely with lab equipment.",
    standards: ["SCI.8.C.2, SCI.8.C.3, SCI.8.C.4", "measuring with the right tools and units, scientific practices and using equipment safely"],
    items: MEASURE,
  }),
  bankUnit({
    id: "mb-science-world-8",
    title: "Science in Our World",
    emoji: "🌎",
    blurb: "Attitudes, careers and ways of knowing",
    parentNote: "Children think about scientific attitudes, careers and hobbies linked to science, taking action on local issues, and the ways many Indigenous communities observe and understand the world.",
    standards: ["SCI.8.A.1, SCI.8.B.1, SCI.8.C.1, SCI.8.C.5", "Indigenous ways of knowing, a sense of belonging in science, taking action on STSE issues and science careers"],
    items: WORLD,
  }),
];
