import type { Unit } from "../../types";
import { bankUnit, type Q } from "../own";

// Grade 8 social studies, part two: Vikings and the Crusades, medieval and early modern technology and events, the
// Industrial Revolution, and the skills of maps, evidence, perspectives and working together (8-K and 8-S outcomes).

const VIKINGS: Q[] = [
  ["The Vikings came from…", "Scandinavia (Norway, Sweden and Denmark)", ["Spain", "Egypt", "Italy"], "Their homeland was in northern Europe."],
  ["The Viking Age is usually dated…", "from the late 700s to the 1000s CE", ["500 to 100 BCE", "1500 to 1800 CE", "1900 to 2000 CE"], "Raids began in 793 CE."],
  ["The Viking raid on the monastery of Lindisfarne in 793 CE took place in…", "England", ["Iceland", "Greenland", "Russia"], "It is often seen as the start of the Viking Age."],
  ["The Vikings sailed in…", "longships", ["steamships", "canoes only", "airships"], "Longships were fast and shallow, good for rivers."],
  ["Why were longships useful for raids?", "they could sail on the sea and travel up rivers", ["they were slow", "they were too heavy for rivers", "they could not carry people"], "A shallow hull allowed landings on beaches."],
  ["Why did many Vikings leave Scandinavia?", "to find farmland, wealth and trade", ["to avoid the sea", "because there were no ships", "to build pyramids"], "Land was limited in the north."],
  ["Besides raiding, many Vikings were also…", "traders, farmers and settlers", ["only scribes", "only priests", "only miners"], "Vikings traded as far as Baghdad."],
  ["The Vikings settled Iceland in the…", "800s", ["200s", "1500s", "1900s"], "Settlers arrived about 870 CE."],
  ["Erik the Red is known for settling…", "Greenland", ["Iceland", "Africa", "India"], "He founded settlements around 985 CE."],
  ["Leif Erikson reached North America around…", "the year 1000", ["500 CE", "1492", "1600"], "He sailed west from Greenland."],
  ["The Norse site in Canada at L'Anse aux Meadows is in…", "Newfoundland", ["Manitoba", "British Columbia", "Nunavut"], "Archaeologists found it in the 1960s."],
  ["What does the L'Anse aux Meadows site show?", "Vikings reached North America about 500 years before Columbus", ["Vikings built pyramids", "Vikings never left Europe", "Vikings lived there for thousands of years"], "It is a UNESCO World Heritage Site."],
  ["The Danelaw was…", "an area of England under Viking control", ["a Viking ship", "a type of sword", "a Viking god"], "Danes ruled and settled parts of England."],
  ["The area of France called Normandy is named for…", "the Northmen (Norsemen)", ["a Roman governor", "a Greek city", "an Inuit word"], "A Viking leader, Rollo, was given land there in 911."],
  ["The Vikings' impact on Europe included…", "raids, settlement, new towns and trade routes", ["no change", "the end of farming", "the fall of Rome"], "They changed many places they reached."],
  ["Viking traders travelled along rivers in…", "eastern Europe and Russia", ["South America", "Australia", "Antarctica"], "They went as far as Constantinople."],
  ["What did Viking towns like Dublin and York become?", "important trading centres", ["ghost towns", "forts only", "temples only"], "They grew because of trade."],
  ["Archaeologists learn about Vikings from…", "ship burials, tools and runic stones", ["television", "the internet", "maps made yesterday"], "Objects and carvings are evidence."],
  ["Runes were…", "letters used by Norse peoples", ["Roman numbers", "Greek songs", "Maya glyphs"], "They were carved on wood, stone and metal."],
  ["Vikings governed local matters at an assembly called the…", "thing", ["senate", "forum", "council of kings only"], "Free men gathered to settle disputes.", true],
  ["A Viking saga is…", "a story of Viking heroes and history", ["a ship", "a weapon", "a law"], "Sagas were told orally, then written down.", true],
  ["Why did the Viking Age end?", "Scandinavian kingdoms grew and adopted Christianity and new ways", ["the Vikings disappeared", "Vikings only raided", "they sailed to the Moon"], "Raiding gave way to settled kingdoms.", true],
  ["The Norman Conquest of England in 1066 was led by…", "William, a descendant of Vikings", ["Erik the Red", "Charlemagne", "Julius Caesar"], "Normans were Norse descendants who spoke French.", true],
  ["In Viking society, which group had the most farmers and workers?", "free commoners", ["kings", "jarls", "none"], "Most people farmed or fished.", true],
  ["Why did people in Europe fear Viking raids?", "raiders arrived suddenly by ship and attacked towns and monasteries", ["raiders arrived in tanks", "raiders were invisible", "raiders warned first"], "Coastal places had little warning.", true],
  ["Viking ships could cross open ocean because they had…", "a sail and skilled navigators", ["engines", "radar", "GPS"], "They used the Sun and stars.", true],
];

const CRUSADES: Q[] = [
  ["The Crusades were…", "a series of religious wars between Christian Europe and Muslim lands", ["trade fairs", "sports contests", "royal weddings"], "Most took place between 1095 and 1291."],
  ["The First Crusade was called by…", "Pope Urban II in 1095", ["Charlemagne in 800", "Queen Victoria", "Julius Caesar"], "He spoke at Clermont, France."],
  ["The main goal of the First Crusade was to…", "take control of Jerusalem", ["conquer China", "reach America", "build the Great Wall"], "Jerusalem is holy to Christians, Muslims and Jews."],
  ["Why is Jerusalem important to three religions?", "it holds sacred places for Jews, Christians and Muslims", ["it is the capital of Europe", "it is the biggest city", "it was built by Vikings"], "It is a holy city for each."],
  ["What did some crusaders hope to gain?", "forgiveness of sins, land and wealth", ["new television", "railways", "printing presses"], "Motives were religious and personal."],
  ["Nobles joined the Crusades hoping for…", "land and glory", ["tea", "machines", "peace"], "Younger sons often had no land at home."],
  ["The Peasants' (People's) Crusade of 1096 was…", "a poorly organized march of ordinary people", ["a professional army", "a naval fleet", "a king's wedding"], "Many were killed before reaching Jerusalem."],
  ["Jerusalem was captured by crusaders in…", "1099", ["800", "1453", "1776"], "The First Crusade succeeded in taking it."],
  ["Saladin was…", "a Muslim leader who retook Jerusalem in 1187", ["a Christian king", "a Viking", "a Roman emperor"], "He was known for his chivalry."],
  ["Which king led part of the Third Crusade?", "Richard the Lionheart of England", ["Louis XIV", "Henry VIII", "Alexander the Great"], "He fought Saladin to a truce."],
  ["The Children's Crusade of 1212 was…", "a movement of young people, and many never returned", ["a school trip", "a tournament", "a market day"], "Historians still debate the details."],
  ["The Fourth Crusade in 1204 attacked…", "Constantinople, a Christian city", ["Rome", "Cairo", "Paris"], "It harmed relations between Western and Eastern Christians."],
  ["One consequence of the Crusades was…", "more trade between Europe and the Middle East", ["less trade", "no travel", "end of the Church"], "Italian cities grew rich from trade."],
  ["Which goods came to Europe through trade with the Middle East?", "spices, silk and sugar", ["potatoes", "tea and coffee only", "gasoline"], "New foods and goods arrived."],
  ["What ideas did Europeans bring back?", "knowledge from Muslim scholars in science and mathematics", ["the printing press", "electricity", "radio"], "Learning flowed both ways."],
  ["A long-term effect of the Crusades was…", "lasting mistrust between some Christians and Muslims", ["no effect", "permanent peace", "the end of religion"], "Memories of conflict lingered."],
  ["The Crusades ended in 1291 when…", "Acre, the last crusader city, fell", ["Rome fell", "London burned", "Paris was founded"], "Crusader states in the Middle East collapsed."],
  ["Which source would be a primary source about the Crusades?", "a letter written by a crusader", ["a modern textbook", "a movie", "a video game"], "Primary sources are from the time."],
  ["Crusaders wore a cross on their clothes. This showed…", "their religious purpose", ["their trade", "their country", "their age"], "The word Crusade comes from the Latin word for cross.", true],
  ["Why can historians' views about the Crusades differ?", "Christian, Muslim and Jewish sources tell different stories", ["all sources agree", "no sources exist", "only maps exist"], "Compare accounts from different perspectives.", true],
  ["Jewish communities in Europe during the First Crusade were often…", "attacked by crusaders", ["protected by all", "ignored", "made kings"], "These attacks are a sad part of the history.", true],
  ["How did the Crusades affect the power of the Church and kings?", "kings and the Church both gained and lost influence in different ways", ["no change at all", "kings disappeared", "the Church disappeared"], "The outcomes were mixed.", true],
  ["The Crusader states in the Middle East could not last because…", "they were far from Europe and surrounded by powerful neighbours", ["there was no land", "they had no army", "they were underwater"], "Support from home faded.", true],
  ["Trade at Venice and Genoa grew during the Crusades because…", "they shipped crusaders and goods", ["they were inland", "they were empty", "they banned ships"], "Merchant cities profited.", true],
  ["Which statement is a fair summary of the Crusades?", "a complex series of wars with religious, political and economic motives", ["simple wars about one thing only", "peaceful trade journeys", "a single battle"], "Many motives mixed together.", true],
  ["Why is it important to learn about the Crusades from several points of view?", "no single account gives the whole story", ["there is only one view", "it is not important", "it only confuses"], "Perspectives help us understand.", true],
];

const MEDIEVAL_TECH: Q[] = [
  ["The stirrup allowed mounted knights to…", "stay steady on a horse while fighting", ["swim", "fly", "ride faster than cars"], "It spread across Europe by the 700s."],
  ["The longbow was a powerful weapon used by…", "English archers", ["Roman legions", "Maya warriors", "Egyptian pharaohs"], "It could pierce armour at a distance."],
  ["Gunpowder was first invented in…", "China", ["Italy", "Canada", "Brazil"], "It was used there by the 800s CE."],
  ["Gunpowder changed warfare because…", "castle walls could be broken by cannon", ["it made castles taller", "it ended war", "it made soldiers fly"], "Stone walls lost their protection."],
  ["A catapult or trebuchet was used to…", "throw heavy stones at castle walls", ["pull water", "plant seeds", "weave cloth"], "Siege engines attacked castles."],
  ["A castle's thick walls and moat were for…", "defence", ["farming", "fishing only", "decoration only"], "They kept attackers out."],
  ["Wind power was first used in medieval times to…", "grind grain in windmills", ["make electricity", "power cars", "run computers"], "Windmills spread across Europe."],
  ["The heavy plough helped farmers because it…", "turned the thick, wet soil of northern Europe", ["flew", "planted by itself", "replaced animals"], "More food meant larger populations."],
  ["Gothic cathedrals were known for…", "pointed arches and tall stained-glass windows", ["flat roofs and no windows", "only wood", "pyramids"], "Flying buttresses supported the walls."],
  ["Mansa Musa was the ruler of the empire of…", "Mali", ["Rome", "Persia", "Sparta"], "His 1324 pilgrimage to Mecca was famous for its gold."],
  ["Timbuktu in Mali was famous for…", "its centre of learning and trade", ["pyramids", "glaciers", "ziggurats"], "Scholars and books gathered there."],
  ["Great Zimbabwe was…", "a large stone city in southern Africa", ["a Viking port", "a Roman fort", "a Maya temple"], "It grew rich on trade in gold and cattle."],
  ["Angkor Wat is a famous temple in…", "Cambodia", ["Peru", "Italy", "Egypt"], "It was built by the Khmer Empire in the 1100s."],
  ["The Alhambra is a palace in Spain built in…", "the Islamic style", ["Roman style", "Viking style", "Maya style"], "It has beautiful tilework and gardens."],
  ["Paper, printing and the compass were all first developed in…", "China", ["Greece", "Mali", "Spain"], "These inventions spread to other regions."],
  ["Medieval Islamic scholars made progress in…", "medicine, mathematics and astronomy", ["only sports", "only cooking", "only sailing"], "Ibn Sina and al-Khwarizmi are examples."],
  ["The word “algebra” comes from…", "an Arabic word", ["a Roman word", "a Maya word", "a Norse word"], "Al-Khwarizmi's work gave algebra its name."],
  ["Armour for knights was made of…", "metal plates or chain mail", ["paper", "silk", "plastic"], "It protected against swords and arrows."],
  ["Which medieval invention helped sailors find direction?", "the magnetic compass", ["the telescope", "the clock", "the radio"], "It spread from China.", true],
  ["Why do we say the world's societies each contributed to the modern world?", "ideas and technologies from many places were shared and combined", ["only one place invented things", "nothing was shared", "all were the same"], "Trade and travel exchanged knowledge.", true],
  ["Why are medieval cathedrals still admired today?", "they show great skill in architecture, art and engineering", ["they are small", "they are new", "they are made of plastic"], "Their beauty and craftsmanship last.", true],
  ["The Black Death in the 1300s reduced Europe's population by about…", "one third or more", ["almost none", "one tenth", "it increased"], "Plague killed millions.", true],
  ["How did new weapons such as the longbow affect knights?", "common soldiers could defeat knights from a distance", ["knights became stronger", "weapons did not matter", "armour became useless"], "Warfare changed.", true],
  ["Water mills and windmills made work easier by…", "using natural power to replace human or animal effort", ["using electricity", "using petrol", "using steam"], "Energy sources changed work.", true],
  ["Which of these shows an achievement in literature in the Middle Ages?", "The Tale of Genji from Japan, The Canterbury Tales from England", ["Harry Potter", "Moby Dick", "Hamlet"], "Writers in many places made lasting books.", true],
  ["A society's technology can change its way of life. For example, the stirrup led to…", "the rise of mounted knights and a feudal system", ["the end of horses", "an end to farming", "no change"], "Technology affected power.", true],
];

const TIMELINE: Q[] = [
  ["The Western Roman Empire ended in…", "476 CE", ["800 CE", "1066 CE", "1215 CE"], "Fifth century."],
  ["The Islamic calendar begins in 622 CE with the…", "Hijra, Muhammad's journey to Medina", ["fall of Rome", "Crusades", "voyage of Columbus"], "Islam spread widely after this."],
  ["Charlemagne was crowned emperor in…", "800 CE", ["476 CE", "1066 CE", "1492 CE"], "He united much of western Europe."],
  ["The Norman conquest of England occurred in…", "1066", ["800", "1215", "1492"], "William defeated King Harold."],
  ["The Magna Carta was signed in…", "1215", ["1066", "1492", "1789"], "It limited the power of the English king."],
  ["The Magna Carta is important because it…", "showed that even a king must obey the law", ["gave the king more power", "ended taxes", "created the Parliament of Canada"], "The rule of law developed."],
  ["The Black Death reached Europe in…", "the 1340s", ["the 500s", "the 1700s", "the 1900s"], "It spread along trade routes."],
  ["The Mongol Empire, under Genghis Khan, was founded in…", "1206", ["300 CE", "1500", "1800"], "It became the largest land empire."],
  ["Constantinople fell to the Ottoman Turks in…", "1453", ["476", "1066", "1215"], "It ended the Byzantine Empire."],
  ["Which empire flourished in West Africa in the 1300s?", "Mali", ["Rome", "Persia", "Inca"], "Mansa Musa ruled it."],
  ["Which empire flourished in the Americas in the 1400s?", "the Aztec and Inca", ["the Mali", "the Mongol", "the Ottoman"], "Tenochtitlan and Cusco were great cities."],
  ["Which Asian ruler led a large Chinese voyage to Africa in the early 1400s?", "Admiral Zheng He of Ming China", ["Kublai Khan", "Qin Shi Huang", "Cyrus"], "His fleets were huge."],
  ["The fifth to fifteenth centuries cover roughly…", "the years 400 to 1500 CE", ["1500 to 1900 CE", "3000 to 500 BCE", "1900 to 2000 CE"], "They are often called medieval times."],
  ["The Middle Ages is another name for…", "the medieval period", ["the ice age", "the space age", "the modern era"], "It is the time between ancient and modern."],
  ["Kublai Khan founded the Yuan dynasty in…", "China", ["Persia", "Egypt", "France"], "He was a grandson of Genghis Khan."],
  ["Marco Polo travelled from Venice to…", "China", ["Mexico", "Greenland", "Australia"], "His book described Asia for Europeans."],
  ["The Hundred Years' War was fought between…", "England and France", ["Rome and Persia", "Vikings and Saxons", "Aztecs and Inca"], "It lasted from 1337 to 1453."],
  ["The Inca Empire had its capital at…", "Cusco", ["Cairo", "Paris", "Athens"], "It stretched along the Andes.", true],
  ["Which came first?", "the Crusades", ["the Magna Carta", "the fall of Constantinople", "the Renaissance"], "They began in 1095.", true],
  ["Which came last?", "the fall of Constantinople", ["the Norman conquest", "the Magna Carta", "the Black Death"], "It happened in 1453.", true],
  ["Why do historians study events across continents in the same period?", "to see how places were connected and different", ["to prove one place was better", "to avoid detail", "to shorten history"], "Global history shows links.", true],
  ["Why is it useful to see world events side by side on a timeline?", "it shows what happened at the same time in different places", ["it removes dates", "it hides causes", "it shortens history"], "Timelines show relationships.", true],
  ["In the 1200s, the Mongol Empire helped connect Europe and Asia by…", "making the Silk Road safer for travellers and traders", ["blocking trade", "closing borders", "building the Great Wall"], "Ideas and goods moved more easily.", true],
  ["The “Pax Mongolica” means…", "a period of relative peace under Mongol rule", ["constant war", "famine", "plague"], "Trade increased across Asia.", true],
  ["Learning about world history helps us understand today's world by showing…", "how past events and connections shaped the present", ["nothing", "only dates", "only battles"], "The past explains the present.", true],
];

const EARLY_MODERN: Q[] = [
  ["The Renaissance began in…", "Italy", ["Egypt", "Canada", "Japan"], "It started in the 1300s in city-states like Florence."],
  ["Renaissance means…", "rebirth", ["war", "empire", "river"], "Interest in learning and art was reborn."],
  ["Leonardo da Vinci was an artist and…", "inventor and scientist", ["Viking king", "Roman emperor", "Greek philosopher"], "He painted the Mona Lisa."],
  ["Johannes Gutenberg's printing press, about 1450, made it easier to…", "make many copies of books", ["travel by sea", "grow wheat", "build bridges"], "Ideas spread faster."],
  ["Christopher Columbus reached the Americas in…", "1492", ["1066", "1215", "1776"], "He sailed for Spain."],
  ["Martin Luther's 95 Theses in 1517 began the…", "Protestant Reformation", ["Crusades", "Renaissance", "Black Death"], "He challenged some practices of the Church."],
  ["Hernán Cortés conquered the Aztec capital in…", "1521", ["1066", "1215", "1700"], "Tenochtitlan fell with help from local allies and disease."],
  ["Galileo used a telescope in 1609 to observe…", "moons around Jupiter", ["Viking ships", "Roman roads", "Egyptian pyramids"], "It supported the idea that Earth orbits the Sun."],
  ["The Scientific Revolution encouraged people to…", "test ideas with observation and experiments", ["accept all old ideas", "avoid questions", "stop writing"], "Evidence became more important."],
  ["The Columbian Exchange was the movement of…", "plants, animals, people and diseases between the Americas and the rest of the world", ["only gold", "only ships", "only books"], "It changed diets and populations."],
  ["Which food came from the Americas to Europe?", "potatoes and tomatoes", ["wheat and rice", "bananas only", "tea only"], "These crops changed European diets."],
  ["The Glorious Revolution of 1688 in England strengthened…", "the power of Parliament over the king", ["the power of the king alone", "the Church", "the army"], "It helped shape modern democracy."],
  ["The American Revolution began in…", "1775", ["1215", "1492", "1914"], "Colonies in North America declared independence in 1776."],
  ["The French Revolution began in…", "1789", ["1066", "1492", "1914"], "It challenged the king's power."],
  ["The Enlightenment was a movement that stressed…", "reason, science and individual rights", ["tradition only", "war only", "gold"], "Thinkers like John Locke and Voltaire wrote about rights."],
  ["Spain, Portugal, France and England explored and colonized the Americas, Africa and Asia to gain…", "wealth, land and power", ["peace", "equal partners", "no trade"], "Colonization often harmed Indigenous peoples."],
  ["The transatlantic slave trade forced millions of Africans to…", "work in the Americas", ["settle in Europe freely", "become kings", "stay home"], "It was a great injustice that shaped the modern world."],
  ["Why do we remember the struggles of people who worked for rights and freedoms?", "they helped create the rights people have today", ["they did nothing", "they were forgotten", "they changed nothing"], "Struggles shaped societies.", true],
  ["The Taj Mahal was built in India in the 1600s under…", "the Mughal Empire", ["the Roman Empire", "the Inca Empire", "the Viking Age"], "It is a famous Mughal monument.", true],
  ["Why were Indigenous peoples in the Americas harmed by European arrival?", "new diseases, loss of land and conflict", ["more trees", "a shorter winter", "new roads only"], "Many communities suffered, and they continue today.", true],
  ["Which statement about the Renaissance is accurate?", "it was a time of new interest in art, science and the ideas of ancient Greece and Rome", ["it ended all art", "it was only in Africa", "it was before the Crusades"], "Learning flourished.", true],
  ["A balance of power in a government between a king and Parliament shows…", "a limit on the ruler's power", ["absolute power", "no laws", "an empire"], "The rule of law grows.", true],
  ["Which source would help you understand daily life in the 1600s?", "a diary written by someone who lived then", ["a modern movie", "a comic book", "a rumour"], "Primary sources reveal daily life.", true],
  ["Why were the works of Shakespeare, Michelangelo and Bach considered enduring?", "people still study and enjoy them", ["they were forgotten", "they were poor", "they were small"], "Art and ideas last.", true],
  ["The first European settlements in the Americas often depended on…", "Indigenous knowledge and trade", ["no one's help", "machines", "airplanes"], "Many Indigenous nations traded and shared knowledge.", true],
  ["Why is the period 1450 to 1800 sometimes called the early modern period?", "it saw the start of many ideas and institutions of today", ["it was the future", "it was the Stone Age", "nothing happened"], "Printing, science and global trade began.", true],
];

const SCIENCE_INDUSTRY: Q[] = [
  ["The printing press made it easier to…", "spread ideas and knowledge", ["travel by sea", "farm", "mine coal"], "Books became cheaper."],
  ["The magnetic compass helped explorers…", "find direction at sea", ["tell time", "see far away", "talk to others"], "It was key for long voyages."],
  ["The telescope let people…", "see far-off objects in the sky", ["see tiny cells", "hear distant sounds", "measure time"], "Galileo used it in 1609."],
  ["The microscope let scientists…", "see tiny things such as cells", ["see stars", "measure temperature", "navigate"], "Early microscopes appeared in the 1600s."],
  ["The steam engine was improved by James Watt in the 1760s and powered…", "factories and trains", ["sailing ships only", "windmills", "horses"], "It changed work and travel."],
  ["The Industrial Revolution began in…", "Great Britain in the 1700s", ["Canada in the 1500s", "Egypt in 3000 BCE", "Japan in 500 CE"], "It then spread to other countries."],
  ["Before the Industrial Revolution, most goods were made…", "by hand at home or in small workshops", ["by robots", "in huge factories", "by computers"], "Workers used simple tools."],
  ["Factories changed work by…", "bringing many workers and machines together in one place", ["ending all work", "sending work home", "stopping production"], "Mass production grew."],
  ["Urbanization means…", "the growth of cities", ["the growth of farms", "the closing of schools", "the decline of trade"], "People moved from the country to find work."],
  ["Why did many people move to cities during the Industrial Revolution?", "to find jobs in factories", ["to farm", "to find mountains", "to avoid people"], "Cities grew fast."],
  ["Which was a problem in many early industrial cities?", "crowded housing and polluted air", ["empty streets", "too many parks", "clean rivers"], "Coal smoke and poor sanitation harmed health."],
  ["Many children in early factories were…", "working long hours in dangerous conditions", ["in school all day", "on holiday", "playing"], "Child labour was common until laws changed it."],
  ["Laws about working conditions were introduced because of…", "protests and reformers", ["lack of machines", "too many holidays", "no factories"], "People worked for change."],
  ["Education changed during the Industrial Revolution because…", "factories needed workers who could read and do arithmetic", ["schools closed", "no one needed learning", "children went to the Moon"], "Public schooling grew."],
  ["The railway made it possible to…", "carry goods and people quickly over long distances", ["stop trade", "slow travel", "end cities"], "Railways linked countries, including Canada."],
  ["The spinning jenny and power loom were machines for…", "making cloth", ["grinding grain", "building ships", "printing books"], "Textiles led the Industrial Revolution."],
  ["A benefit of the Industrial Revolution was…", "goods became cheaper and more plentiful", ["fewer goods", "no new jobs", "no change"], "Mass production lowered costs."],
  ["A cost of the Industrial Revolution was…", "pollution and unsafe working conditions", ["more clean air", "shorter workdays for all", "empty cities"], "Progress also had harm.", true],
  ["How do we still use ideas from the Scientific Revolution?", "we test ideas with experiments and evidence", ["we avoid testing", "we only guess", "we ignore data"], "It shaped modern science.", true],
  ["Coal was important to the Industrial Revolution because it…", "fuelled steam engines and factories", ["fed workers", "made cloth", "grew cotton"], "Burning coal released energy.", true],
  ["The cotton gin and slave labour on plantations helped supply cotton for British mills. This shows…", "industrial growth was linked to injustice elsewhere", ["it was fair to all", "no one was affected", "it ended slavery"], "Industry connected places across the world.", true],
  ["Which is a continuing influence of past inventions on your life today?", "reading printed books, using a compass app and riding on trains", ["nothing at all", "only castles", "only horses"], "Old technologies still matter.", true],
  ["Why do societies appreciate the ideas and technologies of the past?", "they made modern life possible", ["they are all gone", "they have no effect", "they were useless"], "We build on earlier ideas.", true],
  ["Women and children in early factories were often paid…", "less than men", ["more than men", "nothing at all always", "the same as managers"], "Wages were unequal.", true],
  ["How did the telegraph, invented in the 1830s and 1840s, change communication?", "messages could travel long distances almost instantly", ["messages took longer", "it ended writing", "it was a type of mail ship"], "Wires carried electrical signals.", true],
  ["The Industrial Revolution changed the family from a farm unit to…", "workers earning wages outside the home", ["farmers only", "a self-sufficient household", "traders"], "Work moved away from home.", true],
];

const MAPS: Q[] = [
  ["A map title tells you…", "what the map shows", ["how big the map is", "who drew it", "when it was printed"], "Always read the title first."],
  ["A legend (or key) explains…", "the symbols and colours on a map", ["the title", "the scale", "the borders"], "It is where you look up symbols."],
  ["A compass rose shows…", "directions", ["distance", "elevation", "population"], "North, south, east and west."],
  ["Which direction is opposite north?", "south", ["east", "west", "up"], "N-S, E-W are opposites."],
  ["A map scale lets you…", "work out real distances", ["see the colours", "read the title", "find the author"], "1 cm might equal 100 km."],
  ["If 1 cm on a map equals 50 km, what distance is 3 cm?", "150 km", ["50 km", "53 km", "300 km"], "Multiply: 3 × 50 = 150."],
  ["If 2 cm on a map equals 100 km, how far apart are two towns that are 5 cm apart on the map?", "250 km", ["100 km", "200 km", "500 km"], "1 cm equals 50 km; 5 × 50 = 250."],
  ["Lines of latitude run…", "east–west and measure distance north or south of the equator", ["north–south only", "diagonally", "in circles around the poles only"], "Latitude is measured in degrees."],
  ["Lines of longitude run…", "north–south and measure distance east or west of the prime meridian", ["east–west", "around the equator only", "diagonally"], "Longitude is measured in degrees."],
  ["The equator is at…", "0° latitude", ["90° latitude", "0° longitude", "180° longitude"], "It divides Earth into north and south."],
  ["The prime meridian is at…", "0° longitude", ["0° latitude", "90° north", "180° north"], "It passes through Greenwich, England."],
  ["Latitude and longitude together can…", "give the exact location of a place", ["tell the weather", "show the population", "name the rivers"], "They form a grid of coordinates."],
  ["A thematic map shows…", "one topic, such as population or climate", ["only roads", "only borders", "everything"], "Themes include rainfall or trade routes."],
  ["A historical map might show…", "how borders or empires looked in the past", ["only today's weather", "only today's cities", "no information"], "It helps us see change over time."],
  ["An atlas is…", "a collection of maps", ["a type of compass", "a measuring tool", "a story"], "It organizes maps by region or theme."],
  ["To construct a good map you should include…", "a title, legend, compass rose and scale", ["only a picture", "a story", "a joke"], "These parts make a map readable."],
  ["Which map would best show the route of Viking voyages?", "a historical map of the North Atlantic", ["a map of weather today", "a map of Canadian provinces", "a map of the Moon"], "Choose a map that matches the purpose."],
  ["A physical map mainly shows…", "landforms and bodies of water", ["languages", "trade goods", "population only"], "Mountains, rivers and lakes."],
  ["A compass uses…", "Earth's magnetic field to point north", ["the Sun's heat", "the Moon's light", "wind direction"], "The needle is a small magnet.", true],
  ["Traditional Knowledge in many Indigenous communities includes ways of reading the land, such as…", "noticing landmarks, waterways, animals and weather patterns", ["ignoring the land", "using only machines", "guessing"], "Elders and land users carry this knowledge. It differs among communities.", true],
  ["You can orient yourself without a compass by…", "using the Sun, stars or landmarks", ["closing your eyes", "turning in circles", "using the map upside down"], "The Sun rises in the east and sets in the west.", true],
  ["On a map, a larger scale such as 1:10 000 shows…", "a smaller area with more detail", ["a larger area with less detail", "no detail", "the whole world"], "Scale is a ratio of map distance to real distance.", true],
  ["A city is at 49° N, 97° W. 'N' and 'W' tell you it is…", "north of the equator and west of the prime meridian", ["south and east", "north and east", "south and west"], "Winnipeg is roughly at this location.", true],
  ["Why does a map of Earth on a flat page always have some distortion?", "a round surface cannot be flattened without stretching", ["Earth is flat", "maps are wrong on purpose", "the ink spreads"], "Different projections distort in different ways.", true],
  ["Which tool uses satellites to find your location today?", "GPS", ["a barometer", "a protractor", "a thermometer"], "It is a tool to find direction and position.", true],
  ["To find your way using only landmarks, you should…", "note features such as rivers, hills and buildings", ["ignore the surroundings", "follow strangers", "pick a path at random"], "Landmarks help you orient.", true],
];

const SOURCES: Q[] = [
  ["A primary source is…", "created by someone who was there at the time", ["written long after by someone else", "a summary", "a rumour"], "Letters, photos and artifacts are primary."],
  ["Which is a primary source?", "a diary of a medieval monk", ["a modern textbook", "a documentary", "an encyclopedia"], "It was written during the time."],
  ["A secondary source is…", "an account based on other sources, made later", ["a letter from the time", "a photo from the time", "a coin"], "Textbooks are secondary."],
  ["Which is a secondary source?", "a textbook about the Renaissance", ["a Renaissance painting", "a letter by Leonardo", "a Roman coin"], "It interprets the past."],
  ["An artifact is…", "an object made by people in the past", ["a story told today", "a map drawn today", "a rumour"], "Tools, pottery and coins are artifacts."],
  ["What can an old tool tell historians?", "how people lived and what they could make", ["the future", "today's weather", "nothing at all"], "Objects give evidence."],
  ["Historical fiction is…", "a made-up story set in a real time period", ["a primary source", "a diary", "a census"], "It can help imagine the past but is not evidence by itself."],
  ["Which question helps you judge a source?", "Who made it, when, and why?", ["How long is it?", "What colour is the cover?", "Is it heavy?"], "Context matters."],
  ["Considering the context of a source means…", "thinking about when, where and why it was made", ["reading only the title", "ignoring the author", "copying it"], "A source is shaped by its time."],
  ["Two accounts of the same battle disagree. A good historian would…", "compare them and ask why they differ", ["pick one at random", "ignore both", "make up a third"], "Different perspectives give different accounts."],
  ["An account written by a winner of a war may be…", "told from the winner's point of view", ["perfectly neutral", "always true", "the only account"], "Think about who is telling the story."],
  ["Historians' interpretations can change when…", "new evidence is discovered", ["old evidence is ignored", "nothing new is found", "everyone agrees"], "History is revised as we learn more."],
  ["Drawing a conclusion means…", "making a judgement based on evidence", ["guessing", "copying", "memorizing dates"], "Support conclusions with evidence."],
  ["Which statement is supported by evidence?", "Roman roads connected cities, as shown by surviving paved stones", ["Romans had cars", "Rome had no cities", "Romans never traded"], "Evidence supports claims."],
  ["Which is the best way to organize notes for research?", "a chart or concept map by topic", ["one long list of random facts", "scribbles", "memory only"], "Organized notes make research easier."],
  ["Why should you list the sources you use?", "so others can check your information", ["to make your work longer", "to hide your ideas", "because it is fun"], "Referencing sources is honest and useful."],
  ["Which research plan is the clearest?", "choose a topic, write questions, find sources, take notes, then draw conclusions", ["guess the answers first", "copy a website", "write the report before researching"], "Plan topics, goals and methods."],
  ["New information shows one of your assumptions was wrong. You should…", "change your idea and say why", ["ignore the information", "hide the evidence", "argue louder"], "Good thinkers update their ideas."],
  ["Which tool could you use to research a historical topic?", "an atlas, a library database or a museum website", ["a rumour", "a random post", "a guess"], "Pick tools that give reliable information.", true],
  ["A museum shows a photo of a street from 1900. What can you analyze?", "clothing, buildings and transportation", ["the weather in 2050", "what people thought in 2024", "nothing"], "Look closely at visual evidence.", true],
  ["A song written during a war tells you about…", "the feelings and ideas of people at that time", ["only the weather", "the cost of bread", "nothing"], "Music and art are sources.", true],
  ["A painting of a king is much bigger than the other people. What might the artist be showing?", "the king's importance", ["that he was taller", "that he was young", "nothing"], "Art can express ideas, not just facts.", true],
  ["A history book from 1920 may differ from one written in 2020 because…", "perspectives and evidence change over time", ["history is made up", "people changed the past", "books never change"], "Interpretations change.", true],
  ["Why is it important to consider whose voices are missing from a source?", "some groups were left out of the written record", ["all voices are always included", "missing voices are not important", "all records are complete"], "Oral history and artifacts can fill gaps.", true],
  ["Oral history from Elders can be a valuable source because it…", "records knowledge and experiences passed down in communities", ["is never accurate", "is a rumour", "has no value"], "Many cultures preserve history by telling it.", true],
  ["A conclusion that uses no evidence is…", "an opinion", ["a fact", "a primary source", "a map"], "Evidence turns an opinion into an argument.", true],
];

const PERSPECTIVES: Q[] = [
  ["A perspective is…", "a point of view shaped by experience and beliefs", ["a type of map", "a fact", "a date"], "People can see the same event differently."],
  ["Listening to others to understand their perspectives helps you…", "see more than one side of an issue", ["win every argument", "avoid hard topics", "stop learning"], "Listening comes before judging."],
  ["Which phrase is respectful of human diversity?", "people of many backgrounds", ["those people", "you people", "weird groups"], "Choose words that respect everyone."],
  ["Bias in the media means…", "showing information in a way that favours one side", ["showing every side equally", "never showing news", "printing maps"], "Bias can be strong or subtle."],
  ["Which clue suggests an article may be biased?", "it uses loaded words and leaves out other viewpoints", ["it gives sources and many views", "it is balanced", "it shows facts"], "Loaded words try to push feelings."],
  ["A stereotype is…", "an oversimplified idea about a group", ["a fact about one person", "a historical date", "a map symbol"], "It ignores individual differences."],
  ["Prejudice means…", "judging someone before knowing them", ["knowing someone well", "a kind of respect", "an agreement"], "Pre-judgement is unfair."],
  ["Racism is…", "treating people unfairly because of their race", ["liking all people", "an idea about maps", "a type of law"], "It harms individuals and communities."],
  ["What can you do when you see discrimination?", "speak up safely, support the person and tell a trusted adult", ["join in", "laugh", "pretend it did not happen"], "Propose solutions that help."],
  ["Ageism is…", "treating people unfairly because of their age", ["a respect for elders", "a kind of map", "a historical age"], "It can affect young people and older people."],
  ["Which is a way to compare perspectives in media?", "read or watch accounts from different sources", ["read only one source", "ignore the author", "look at the pictures only"], "Comparing reveals bias."],
  ["Two news stories describe the same protest. One says “crowd” and the other says “mob”. What does this show?", "word choice can shape how we feel about events", ["the stories are identical", "there was no event", "one is a map"], "Notice connotation."],
  ["A historical account that ignores women's roles may be…", "incomplete", ["complete", "a map", "perfect"], "Ask who is missing."],
  ["Which statement shows you are willing to consider differing world views?", "“Tell me why you see it that way.”", ["“Your view is wrong.”", "“I don't care.”", "“Only my view counts.”"], "Open-mindedness starts with curiosity."],
  ["To persuasively express a viewpoint, you should…", "give reasons and evidence and respect others", ["shout", "insult", "repeat the same claim"], "Persuasion uses reasons."],
  ["Which sentence expresses a belief about an issue clearly?", "I believe the town should plant more trees because they cool the streets.", ["Trees.", "I like green.", "Whatever."], "Say your belief and your reason."],
  ["A good discussion question is…", "open and invites different ideas", ["a yes/no trap", "an insult", "a joke"], "Elicit and clarify ideas."],
  ["When two people disagree in discussion, a good step is to…", "restate what the other said to check you understood", ["interrupt", "walk away", "ignore"], "Clarify before replying.", true],
  ["An image shows only wealthy people in a story about a city. What might be missing?", "the experiences of other groups", ["the weather", "the building", "the date"], "Representation matters.", true],
  ["Why do some history books portray Indigenous peoples in the past tense only?", "older accounts often ignored living communities, which is a bias", ["Indigenous peoples are gone", "it is accurate", "it is the law"], "Indigenous peoples are living communities today.", true],
  ["Which of these is a fair way to describe a group?", "using the group's own names for itself where possible", ["inventing a name for them", "using a joke", "using an old stereotype"], "Respect self-description.", true],
  ["A speaker says all members of a group act the same way. What is a good response?", "ask for evidence and point out differences within the group", ["agree", "repeat it", "laugh"], "Challenge generalizations.", true],
  ["How can you tell if media coverage is balanced?", "it presents several viewpoints and cites evidence", ["it uses only one voice", "it shows no data", "it mocks one side"], "Balance includes multiple voices.", true],
  ["Why might a cartoon from the past include stereotypes?", "it reflects the attitudes and biases of its time", ["it is always accurate", "stereotypes are facts", "it had no audience"], "We study sources in context and can criticize them today.", true],
  ["Hearing a viewpoint different from yours should lead you to…", "think about whether your own assumptions need to change", ["close your mind", "attack the speaker", "ignore the topic"], "New perspectives can change our minds.", true],
  ["Why is it important to speak about differences respectfully in a diverse community?", "it keeps everyone included and safe", ["it is unnecessary", "it causes conflict only", "it ends discussion"], "Respect supports belonging.", true],
];

const TEAMWORK: Q[] = [
  ["Which action shows collaboration?", "sharing tasks and listening to each other", ["doing everything alone", "ignoring the group", "taking all the credit"], "Group goals need group effort."],
  ["A group goal is best when…", "everyone understands it and agrees to it", ["one person decides secretly", "no one knows it", "it changes every minute"], "Clear goals help teams."],
  ["Which is a fair way to share group work?", "give each person a role that fits their strengths", ["one person does everything", "no roles", "choose roles by chance only"], "Responsibilities should be fair."],
  ["Two friends want different things. A peaceful solution is…", "compromise so each gets part of what they want", ["shout until one gives in", "stop talking", "take it by force"], "Compromise is a win-win."],
  ["Negotiation means…", "talking to reach an agreement that works for everyone", ["demanding", "walking away", "ordering others"], "Both sides listen and offer ideas."],
  ["Clarification means…", "explaining or asking questions to understand each other", ["interrupting", "arguing louder", "ignoring"], "Misunderstandings often cause conflict."],
  ["Building consensus means…", "working until the group agrees on a decision", ["voting without talking", "the leader decides alone", "ending the meeting"], "Everyone can accept the choice."],
  ["Which statement shows fairness?", "everyone gets a turn and equal respect", ["the strongest wins", "some people are skipped", "rules apply to some people only"], "Fairness treats people equitably."],
  ["Which choice is a good step toward environmental stewardship?", "reducing waste and protecting local water and wildlife", ["littering", "wasting water", "ignoring nature"], "Stewardship means caring for the land."],
  ["Indigenous peoples in many parts of Canada teach that people have a responsibility to care for the land. This is an example of…", "stewardship", ["trade", "empire", "taxation"], "Care for the land is a value in many cultures."],
  ["Why should we treat historical sites with respect?", "they are important to people's identity and history", ["they are free to take from", "they have no meaning", "they are toys"], "Burial grounds and memorials are special places."],
  ["What should you do if you find an artifact on a field trip?", "leave it where it is and tell a teacher or an expert", ["take it home", "break it", "sell it"], "Artifacts must be recorded and protected."],
  ["Burial grounds should be treated with…", "respect", ["noise", "play", "digging"], "They are sacred or deeply meaningful to many people."],
  ["A memorial is…", "a place or object that honours people or events", ["a sports field", "a type of map", "a game"], "Treat it with care."],
  ["A classmate is left out of a group. What helps?", "invite them and make room for their ideas", ["ignore them", "make a joke", "leave them out again"], "Inclusion builds a strong team."],
  ["Which decision shows fairness and equality?", "giving everyone the same chance to speak", ["letting the loudest talk", "ignoring quiet voices", "asking only friends"], "Everyone has a voice."],
  ["Which is an example of proposing a solution to discrimination?", "starting a class project to learn about and challenge stereotypes", ["laughing at jokes", "saying nothing", "joining in"], "Positive action helps.", true],
  ["When a team has a conflict, the first step is often to…", "listen to each person's side calmly", ["blame someone", "quit", "shout"], "Listening reduces tension.", true],
  ["A group of students must decide where to plant a school garden. Which method builds consensus?", "everyone shares ideas, discusses pros and cons, then agrees", ["the teacher chooses at random", "one student decides", "no one decides"], "Consensus uses discussion.", true],
  ["What is sustainability?", "meeting today's needs without harming future generations' ability to meet theirs", ["using everything now", "saving nothing", "ignoring the future"], "Think about long-term effects.", true],
  ["A fair rule in a game…", "applies equally to all players", ["favours a friend", "changes during play", "is secret"], "Fairness means equal rules.", true],
  ["What shows respect when someone presents an idea you disagree with?", "listening to the end and asking questions", ["rolling your eyes", "walking out", "mocking them"], "Respect keeps discussion productive.", true],
  ["Why is it important to take responsibility for your role in a group?", "others depend on you to finish your part", ["no one notices", "it is optional", "it does not matter"], "Teams rely on each member.", true],
  ["A river near a town is polluted. Which action best reflects stewardship?", "clean up, reduce pollution at the source and monitor the water", ["ignore it", "pour more waste in", "fence it off and forget it"], "Care for the environment is ongoing.", true],
  ["Which of these demonstrates peaceful conflict resolution?", "each side states its needs, and together they find a plan", ["a shouting match", "a fight", "silence forever"], "Talk and compromise.", true],
  ["What can you do to make your community fairer?", "treat others with respect and speak up when someone is treated unfairly", ["ignore problems", "only help friends", "make rules for others only"], "Fairness starts with everyday choices.", true],
];

export const units: Unit[] = [
  bankUnit({
    id: "mb-vikings-8",
    title: "The Vikings",
    emoji: "⛵",
    blurb: "Longships, raids, trade and settlement",
    parentNote: "Children learn where the Vikings came from, how they raided, traded and settled across Europe and the North Atlantic, and how they reached North America.",
    standards: ["8-KP-050", "the Viking invasions and their impact on Europe from the ninth to twelfth centuries"],
    items: VIKINGS,
  }),
  bankUnit({
    id: "mb-crusades-8",
    title: "The Crusades",
    emoji: "🏰",
    blurb: "Why they began and what changed",
    parentNote: "Children learn the motives for the Crusades, key events and people, and the effects on trade, learning and relations between peoples. The unit shows several points of view.",
    standards: ["8-KH-034", "motivations for and consequences of the Crusades"],
    items: CRUSADES,
  }),
  bankUnit({
    id: "mb-medieval-tech-8",
    title: "Medieval Technology & Achievements",
    emoji: "⚔️",
    blurb: "Stirrups, gunpowder, cathedrals and learning",
    parentNote: "Children explore technologies of the Middle Ages and achievements in art, architecture and science in societies across Europe, Africa and Asia.",
    standards: ["8-KE-058, 8-KG-042, 8-VG-014, 8-VH-012", "technological developments and achievements in art, architecture, literature and science from the fifth to fifteenth centuries"],
    items: MEDIEVAL_TECH,
  }),
  bankUnit({
    id: "mb-world-timeline-8",
    title: "The World, 400 to 1500",
    emoji: "🌍",
    blurb: "Big events on every continent",
    parentNote: "Children place major events from the fifth to fifteenth centuries on a timeline and see how places were connected.",
    standards: ["8-KG-040, 8-VG-015", "major events in Europe, the Middle East, Africa, Asia and the Americas from the fifth to fifteenth centuries"],
    items: TIMELINE,
  }),
  bankUnit({
    id: "mb-early-modern-8",
    title: "The World, 1450 to 1800",
    emoji: "⛵",
    blurb: "Printing, science, revolutions and exchange",
    parentNote: "Children learn major events from the fifteenth to eighteenth centuries, including the Scientific Revolution, the Columbian Exchange, and revolutions that changed governments.",
    standards: ["8-KG-043, 8-VC-003, 8-VI-007", "major events in the fifteenth to eighteenth centuries, the struggles of past societies and lasting art and ideas"],
    items: EARLY_MODERN,
  }),
  bankUnit({
    id: "mb-industry-8",
    title: "Science & the Industrial Revolution",
    emoji: "🏭",
    blurb: "Inventions that changed work and cities",
    parentNote: "Children learn how inventions such as the printing press, telescope and steam engine changed societies, and how the Industrial Revolution affected work, cities and education.",
    standards: ["8-KE-059, 8-KE-060, 8-VE-018, 8-VH-013", "the impact of science and technology, the Industrial Revolution and the contributions of past societies"],
    items: SCIENCE_INDUSTRY,
  }),
  bankUnit({
    id: "mb-maps-8",
    title: "Maps & Directions",
    emoji: "🧭",
    blurb: "Scales, coordinates and finding your way",
    parentNote: "Children read and build maps with a title, legend, compass rose and scale, use latitude and longitude, and learn ways to find direction, including reading the land.",
    standards: ["8-S-205, 8-S-206, 8-S-207A, 8-S-208", "constructing and interpreting maps, using Traditional Knowledge to read the land, and orienting using the landscape or a compass"],
    items: MAPS,
  }),
  bankUnit({
    id: "mb-evidence-8",
    title: "Sources & Evidence",
    emoji: "📜",
    blurb: "Primary and secondary sources, context and conclusions",
    parentNote: "Children practise choosing and judging sources, reading artifacts and art, comparing accounts and drawing conclusions from evidence.",
    standards: ["8-S-200, 8-S-201, 8-S-202, 8-S-203, 8-S-300, 8-S-301, 8-S-302, 8-S-303, 8-S-305, 8-S-307, 8-S-309, 8-S-310", "choosing, organizing and interpreting sources, planning research, context, evidence and changing interpretations"],
    items: SOURCES,
  }),
  bankUnit({
    id: "mb-perspectives-8",
    title: "Perspectives & Bias",
    emoji: "👀",
    blurb: "Spot bias and respect different views",
    parentNote: "Children practise listening to other points of view, recognizing bias and stereotyping, using respectful language and sharing their own beliefs with reasons.",
    standards: ["8-S-105, 8-S-308, 8-S-311, 8-S-400, 8-S-401, 8-S-402, 8-S-404, 8-S-405, 8-VI-006", "recognizing bias and discrimination, comparing perspectives in the media, listening, respectful language and expressing viewpoints"],
    items: PERSPECTIVES,
  }),
  bankUnit({
    id: "mb-teamwork-8",
    title: "Working Together Fairly",
    emoji: "🤲",
    blurb: "Group goals, fair decisions and caring for places",
    parentNote: "Children practise group roles, resolving conflict, building consensus, fairness, environmental stewardship and respect for places of historical importance.",
    standards: ["8-S-100, 8-S-101, 8-S-102, 8-S-103, 8-S-104, 8-S-106", "collaboration, peaceful conflict resolution, fairness, stewardship, consensus and respect for places of historical significance"],
    items: TEAMWORK,
  }),
];
