import type { Unit } from "../../types";
import { bankUnit, type Q } from "../own";

// Grade 8 social studies, part one: how societies begin, early societies of Mesopotamia, Egypt and the Indus Valley,
// world religions and civilizations of antiquity, and the lasting ideas of Greece and Rome (8-K and 8-V outcomes).

const BEGIN: Q[] = [
  ["Early humans who moved to find food, hunting animals and gathering plants, are called…", "hunter-gatherers", ["farmers", "merchants", "scribes"], "They followed the animals and the seasons."],
  ["The change to growing crops and raising animals is called the…", "agricultural revolution", ["industrial revolution", "printing revolution", "digital revolution"], "Farming began thousands of years ago in several parts of the world."],
  ["Why did farming let people settle in one place?", "they could grow food near their homes", ["they had no food", "they stopped needing water", "they stopped using tools"], "A steady food supply made villages possible."],
  ["A food surplus is…", "more food than people need right away", ["too little food", "food that is spoiled", "food for animals only"], "Surplus lets some people do other jobs."],
  ["Why did a food surplus lead to specialized jobs?", "not everyone needed to farm, so some became potters, builders or traders", ["everyone farmed more", "jobs were banned", "people stopped trading"], "Specialization means doing one kind of work."],
  ["Which of these is a way societies keep themselves going?", "teaching children skills and traditions", ["forgetting the past", "stopping all work", "ending all trade"], "Education and culture are passed on."],
  ["How did early societies meet their need for physical survival?", "by finding food, water and shelter", ["by building screens", "by writing novels", "by making coins first"], "Survival comes first."],
  ["Oral tradition is…", "passing stories and knowledge on by speaking", ["writing on tablets only", "painting only", "building monuments only"], "Many cultures pass history on by telling."],
  ["Why do cultures tell stories about how the world and people began?", "to explain where they come from and what matters to them", ["to avoid all questions", "to make maps", "because they have no ideas"], "Origin stories express values and world views."],
  ["Which statement about origin stories is accurate?", "Many cultures have their own stories, and they are different from one another.", ["All cultures tell the same story.", "Only one culture has a story.", "Stories are never important."], "Respect different stories and theories."],
  ["Scientists also study the origins of human life by examining…", "fossils and other physical evidence", ["only legends", "weather forecasts", "maps of today"], "Archaeology and biology give evidence."],
  ["Some Indigenous nations in Canada have origin stories connected to the land where they live. This shows…", "how a society's environment and its stories can be linked", ["that land does not matter", "that every nation is the same", "that stories are about weather only"], "Say “some” nations, not all."],
  ["Why did many early civilizations begin near rivers?", "rivers gave water, fertile soil and ways to travel", ["rivers were quiet", "rivers had no fish", "rivers were always dry"], "The environment shaped where people settled."],
  ["How does a cold climate affect the way people live?", "they need warm clothing and shelter", ["they need no shelter", "they do not need food", "they never travel"], "Natural environments shape lifestyles."],
  ["A society that lives near forests might use…", "wood for building and fuel", ["only stone from the sea", "sand for walls", "ice for floors"], "People use what is available."],
  ["How does the natural environment influence what crops grow?", "soil, rainfall and temperature decide what can grow", ["crops grow anywhere equally", "only wind decides", "the calendar decides"], "Climate matters for farming."],
  ["Mountains and deserts often kept some societies…", "separate from others", ["connected to all", "at sea", "in the sky"], "Landforms can be barriers."],
  ["Why is it important to sustain the natural environment?", "future societies depend on it too", ["it has no value", "people can live without it", "it is always replaced instantly"], "Stewardship keeps resources for the future."],
  ["Which action shows care for the environment for future societies?", "planting trees and using water carefully", ["wasting resources", "leaving garbage", "ignoring the problem"], "Small choices add up."],
  ["Being willing to consider differing world views means…", "listening to other ways of seeing the world with an open mind", ["agreeing with everyone", "ignoring others", "arguing at once"], "Open-mindedness helps understanding."],
  ["Two people explain the same event differently. A good response is to…", "ask about their reasons and compare", ["call one wrong straight away", "stop listening", "decide without evidence"], "Different views come from different experiences."],
  ["Who decided how early groups would share food and tasks?", "leaders, elders or the group together", ["only machines", "no one at all", "strangers far away"], "Societies organize themselves in different ways.", true],
  ["Which is an advantage of living in a large settled community?", "people can share work and protect each other", ["there is never any conflict", "everyone does the same job", "no one needs rules"], "Settlements bring benefits and new challenges.", true],
  ["Which is a challenge of living in a large settled community?", "sharing resources and settling disagreements", ["having too many empty fields", "never needing food", "not needing leaders"], "More people means more need for rules.", true],
  ["Why does the study of how societies began help us today?", "it shows why we have jobs, rules and traditions", ["it is not related to today", "it replaces maps", "it explains the weather"], "Many parts of modern life began long ago.", true],
  ["A drought lasted many years in an area where people farmed. What might happen?", "people may move or find new ways to get water", ["crops will grow faster", "rivers will rise", "nothing will change"], "Environmental change influences societies.", true],
];

const MESOPOTAMIA: Q[] = [
  ["Mesopotamia means “the land…”", "between the rivers", ["of the sun", "beside the sea", "on the mountain"], "Between the Tigris and Euphrates rivers."],
  ["Which two rivers shaped Mesopotamia?", "the Tigris and the Euphrates", ["the Nile and the Congo", "the Indus and the Ganges", "the Yellow and the Yangtze"], "They flow through present-day Iraq and neighbouring countries."],
  ["Today, most of ancient Mesopotamia is in…", "Iraq", ["Egypt", "Greece", "India"], "Look at a map of Southwest Asia."],
  ["The Fertile Crescent is…", "a curve of rich farmland in the Middle East", ["a mountain range", "a desert", "an ocean"], "Early farming began there."],
  ["Sumer was…", "an early civilization in southern Mesopotamia", ["a Greek island", "an Egyptian god", "a Roman road"], "Sumerians built the first city-states."],
  ["A city-state is…", "a city with its own ruler that controls the land around it", ["a nation of many cities", "a village without leaders", "a type of boat"], "Ur and Uruk were city-states."],
  ["What was used in Mesopotamia to control river water for farming?", "irrigation canals", ["snow plows", "wind turbines", "airplanes"], "Canals carried water from the rivers to the fields."],
  ["Mesopotamian writing was called…", "cuneiform", ["hieroglyphics", "the alphabet of Greece", "Braille"], "Wedge-shaped marks pressed into clay."],
  ["Cuneiform was written by pressing a reed into…", "wet clay", ["papyrus", "silk", "paper"], "The clay tablet dried hard."],
  ["Who were scribes?", "people trained to read and write", ["soldiers", "farmers", "sailors"], "Scribes kept records of trade and law."],
  ["Why was writing important in Mesopotamia?", "it let people keep records of trade, laws and stories", ["it replaced farming", "it made rivers flow", "it ended all wars"], "Writing helped societies organize."],
  ["A ziggurat was…", "a stepped temple tower", ["a boat", "a palace garden", "a marketplace"], "It rose in levels above the city."],
  ["Hammurabi was known for…", "his code of laws", ["building the pyramids", "inventing the alphabet", "discovering the Indus"], "He ruled Babylon about 3,700 years ago."],
  ["A law code carved on stone helped by…", "making the laws known to everyone", ["hiding the laws", "stopping all laws", "ending trade"], "Public laws are the same for all (though punishments often differed by rank)."],
  ["Which Mesopotamian invention helped move goods and make pottery?", "the wheel", ["the telescope", "the compass", "the steam engine"], "The wheel appeared in Sumer."],
  ["The Mesopotamians used a counting system based on 60. We still use it when we measure…", "time in minutes and angles", ["money in dollars", "weights in kilograms", "distance in metres"], "60 seconds and 60 minutes."],
  ["Which person would work in a Mesopotamian temple?", "a priest", ["a pilot", "a banker with a card", "a train conductor"], "Priests led worship and managed temple lands."],
  ["Most people in Mesopotamia were…", "farmers and workers", ["kings", "scribes", "priests"], "Farmers produced food for the cities."],
  ["Which statement about life in Mesopotamia is true?", "enslaved people also lived and worked there", ["no one worked", "everyone had the same job", "there were no cities"], "Some people were captured in war or in debt."],
  ["The Epic of Gilgamesh is…", "one of the oldest known stories, written in cuneiform", ["a modern novel", "a Roman law code", "an Egyptian map"], "It tells of a king and his friend.", true],
  ["Why did Mesopotamian farmers need irrigation even though they lived between two rivers?", "rainfall was low and floods were unpredictable", ["the rivers were frozen", "the soil was too wet", "there were mountains in the way"], "Floods could come late or too strongly.", true],
  ["The first empire in Mesopotamia is linked to Sargon of Akkad. An empire is…", "a large area ruled by one government that has conquered other lands", ["a small village", "a type of farm", "a law code"], "Empires join many peoples under one ruler.", true],
  ["Ziggurats were built with…", "mud bricks", ["steel beams", "wood only", "ice blocks"], "Little stone was available.", true],
  ["Which was a result of the flooding of the Tigris and Euphrates?", "both help and danger: new soil, but also damage", ["no effect", "only help", "only danger"], "Floods brought silt but could destroy homes.", true],
  ["Which clue shows a ruler in Mesopotamia held power?", "he commanded an army and collected taxes", ["he lived in a cave alone", "he had no followers", "he did not own land"], "Rulers organized armies and laws.", true],
  ["Mesopotamian cities traded goods such as grain, cloth and pottery with…", "distant lands, including the Indus Valley", ["the Americas", "Australia", "Antarctica"], "Seals and goods show long-distance trade.", true],
];

const EGYPT: Q[] = [
  ["Which river was the lifeline of ancient Egypt?", "the Nile", ["the Tigris", "the Indus", "the Yellow"], "Almost everyone lived near it."],
  ["The Nile flows…", "north into the Mediterranean Sea", ["south into the desert", "west into the Atlantic", "east into the Red Sea"], "It is one of the few rivers that flows north."],
  ["The Nile flooded every year and left…", "rich black soil called silt", ["a layer of sand only", "ice", "ash"], "The flood made farming possible."],
  ["Beyond the narrow Nile valley, Egypt was mostly…", "desert", ["rainforest", "tundra", "farmland"], "Deserts protected Egypt from invaders."],
  ["Where does the Nile form a fan-shaped area of rich land near the sea?", "the Nile Delta", ["the Sahara", "the Red Sea", "the Valley of Kings"], "Lower Egypt was the northern delta."],
  ["The ruler of ancient Egypt was called the…", "pharaoh", ["emperor of Rome", "consul", "sultan"], "Pharaohs were seen as both kings and gods."],
  ["Hieroglyphs are…", "Egyptian picture writing", ["Greek letters", "Roman numbers", "Chinese characters"], "Symbols stood for sounds and ideas."],
  ["Papyrus was…", "a paper-like material made from a river plant", ["a type of stone", "a kind of metal", "a boat sail"], "Scribes wrote on it with reed pens."],
  ["The Rosetta Stone helped scholars…", "read hieroglyphs", ["find the Nile", "build pyramids", "count days"], "It had the same text in three scripts."],
  ["Pyramids were built as…", "tombs for pharaohs", ["markets", "schools", "harbours"], "They protected the pharaoh's body and treasures."],
  ["The Great Pyramid at Giza was built for…", "Pharaoh Khufu", ["Julius Caesar", "Alexander the Great", "Hammurabi"], "It is about 4,500 years old."],
  ["Mummification was done to…", "preserve the body for the afterlife", ["make a statue", "make food last", "make perfume"], "Egyptians believed in life after death."],
  ["Who kept records, collected taxes and wrote letters?", "scribes", ["farmers", "slaves", "sailors"], "Scribes were highly valued."],
  ["Which group made up most Egyptians?", "farmers", ["priests", "nobles", "scribes"], "They worked the land along the river."],
  ["Which was a danger to Egyptian farmers if the Nile flood was too low?", "famine", ["too many trees", "too much snow", "too many roads"], "The flood supplied water and soil."],
  ["The Egyptians used a calendar of…", "365 days", ["100 days", "200 days", "400 days"], "It was based on the Nile's cycle."],
  ["Egyptians used boats on the Nile to…", "carry goods and people", ["only fish", "to cross mountains", "to cut stone only"], "The river was a highway."],
  ["Which tool helped Egyptians build large monuments?", "ramps and levers", ["cranes with engines", "bulldozers", "steam shovels"], "They used human labour and simple machines."],
  ["Upper and Lower Egypt were united about 5,000 years ago under…", "one pharaoh", ["a Roman consul", "a Greek council", "two kings forever"], "Narmer is often named."],
  ["Egyptian temples and tombs were decorated with…", "paintings and carved reliefs", ["neon lights", "glass windows", "photographs"], "Art told stories about gods and rulers."],
  ["Ra was…", "the Egyptian sun god", ["a river", "a pharaoh's servant", "a pyramid"], "Many gods were linked to nature.", true],
  ["Why did Egyptians build their tombs on the west bank of the Nile?", "the Sun sets in the west, linked to the land of the dead", ["it was cooler", "it was closer to Rome", "it was a desert only"], "Religion shaped where they built.", true],
  ["Who built the pyramids?", "skilled workers, many of them paid labourers", ["only aliens", "only enslaved foreign people", "no one knows at all"], "Archaeologists found workers' towns and records.", true],
  ["Egypt's geography protected it because it was bordered by…", "deserts and the sea", ["mountains of ice", "other empires", "deep forests"], "Natural barriers made invasion harder.", true],
  ["The Egyptians made advances in…", "medicine and mathematics for building and measuring land", ["radio and television", "electric lighting", "air travel"], "Papyrus texts describe treatments and calculations.", true],
  ["After each flood, farmers needed to re-measure fields. This led to progress in…", "geometry", ["music", "poetry", "painting only"], "Surveying skills grew from practical need.", true],
];

const INDUS: Q[] = [
  ["The Indus Valley civilization was in what is now…", "Pakistan and northwestern India", ["Greece", "Iraq", "Egypt"], "It grew along the Indus River."],
  ["The two best-known Indus cities are…", "Harappa and Mohenjo-daro", ["Ur and Uruk", "Athens and Sparta", "Memphis and Thebes"], "Harappa gives its name to the Harappan civilization."],
  ["The Indus cities were built about…", "4,500 to 5,000 years ago", ["500 years ago", "100 years ago", "2,000 years ago"], "They are as old as early Egypt."],
  ["Streets in Indus cities were laid out…", "in a grid", ["randomly", "in circles only", "in spirals"], "Planning shows organized government."],
  ["Indus houses were built with…", "baked mud bricks", ["wooden planks only", "glass", "concrete"], "Bricks were standard sizes."],
  ["Indus cities were famous for…", "drains and sewers", ["pyramids", "ziggurats", "aqueducts to Rome"], "Water was carried away under the streets."],
  ["The Great Bath at Mohenjo-daro may have been used for…", "washing rituals or public bathing", ["storing grain", "testing weapons", "training soldiers"], "Historians are not certain."],
  ["Why do we know less about Indus government than about Egypt's?", "their writing has not been deciphered", ["they had no cities", "they did not exist", "they only lived in tents"], "Seals show symbols we cannot yet read."],
  ["Small carved stones used to mark goods and trade are called…", "seals", ["scrolls", "mosaics", "coins"], "Indus seals show animals and symbols."],
  ["Indus traders used standard…", "weights and measures", ["alphabets only", "calendars only", "sails only"], "This made trade fair."],
  ["Indus merchants traded with…", "Mesopotamia", ["Canada", "Rome", "the Maya"], "Indus seals have been found in Mesopotamia."],
  ["Indus farmers grew crops such as…", "wheat, barley and cotton", ["potatoes only", "tea only", "corn only"], "Cotton was grown early in the Indus Valley."],
  ["What did the Indus River give people?", "water, fertile soil and a way to travel", ["ice", "gold", "a bridge to Egypt"], "Like the Nile, it flooded and refreshed farmland."],
  ["The Indus River's floods were linked to…", "monsoon rains and mountain snowmelt", ["volcanoes", "tides", "earthquakes only"], "Water came from the Himalayas."],
  ["Which feature suggests the Indus cities were well planned?", "drainage systems and straight streets", ["no roads", "houses on hills only", "no walls"], "Planning needs organization."],
  ["One reason the Indus cities declined may have been…", "a changing climate and shifting rivers", ["a meteor strike for sure", "the printing press", "the Roman army"], "Experts have several theories.", true],
  ["Which statement about the Indus script is true?", "scholars have not been able to read it", ["it was a Roman alphabet", "it is the same as hieroglyphs", "it is fully understood"], "More evidence is needed.", true],
  ["Evidence for Indus crafts includes…", "beads, pottery and bronze objects", ["television sets", "steel tools", "pyramids"], "Archaeologists have found them.", true],
  ["Why is it harder to know about the Indus leaders than Egypt's pharaohs?", "no large royal tombs or readable texts have been found", ["they had no leaders", "they ruled by machines", "their cities were on the sea"], "Fewer clues about rulers.", true],
  ["Indus cities had similar bricks across hundreds of kilometres. This suggests…", "a shared system of planning and trade", ["each city did something different", "the bricks came from Egypt", "no organization"], "Consistency shows coordination.", true],
  ["Why did Indus cities need drains?", "to keep water and waste away from homes", ["to bring in ocean water", "to make rain", "to store grain"], "Sanitation protected health.", true],
  ["The Indus civilization is sometimes called the Harappan civilization because…", "Harappa was one of its first excavated cities", ["Harappa is in Egypt", "its leader was Harappa", "its river was called Harappa"], "Archaeologists named it after a site.", true],
  ["Compared with Mesopotamian cities, Indus cities show…", "less evidence of temples towering over the city", ["many ziggurats", "huge palaces on every street", "big armies"], "Historians note differences.", true],
  ["Which is an advantage of a river valley for a civilization?", "rich soil and water for farming", ["no water", "poor soil", "no way to travel"], "Rivers supported the first civilizations.", true],
  ["Compared with Egypt's pyramids, what is a notable feature of Indus cities?", "city planning and drains", ["pharaoh tombs", "ziggurats", "hieroglyphs"], "Their strengths were urban design.", true],
  ["How do historians learn about the Indus Valley today?", "archaeology: digging and studying objects and buildings", ["interviewing the people", "watching videos", "reading Roman books"], "Without readable writing, objects tell the story.", true],
];

const COMPARE: Q[] = [
  ["Which was a defining characteristic of early civilizations?", "cities with organized government", ["only small camps", "no farming", "no trade"], "Civilizations had cities, leaders, writing and trade."],
  ["Which pair of rivers supported Egypt and the Indus Valley?", "the Nile and the Indus", ["the Tigris and the Danube", "the Yellow and the Nile", "the Rhine and the Seine"], "River valleys shaped each society."],
  ["Which early society grew along the Yellow River (Huang He) in China?", "the Shang", ["the Sumerians", "the Harappans", "the Romans"], "The Shang dynasty is the earliest in written records."],
  ["The Shang used oracle bones to…", "ask questions of ancestors and record the answers", ["cook food", "build bridges", "make coins"], "Early Chinese writing appears on them."],
  ["Which metal did the Shang cast into ritual vessels?", "bronze", ["steel", "aluminum", "plastic"], "Bronze is a mix of copper and tin."],
  ["Which early society used a writing system with wedge-shaped marks?", "Mesopotamia", ["Egypt", "China", "Indus"], "Cuneiform."],
  ["Which early society used hieroglyphs?", "Egypt", ["Mesopotamia", "China", "Indus"], "Picture-based writing."],
  ["Which early society is known for its planned grid-pattern cities?", "the Indus Valley", ["Egypt", "Mesopotamia", "the Shang"], "Mohenjo-daro and Harappa."],
  ["Which early society built pyramids as royal tombs?", "Egypt", ["Indus", "China", "Sumer"], "Stone pyramids at Giza."],
  ["Which defining characteristic did all four early societies share?", "farming made possible by a river", ["use of the printing press", "use of the telephone", "nuclear energy"], "Rivers supported agriculture."],
  ["In which time period did these early societies flourish?", "from about 3500 to 500 BCE", ["from 1500 to 1800 CE", "from 500 to 1500 CE", "from 1900 to 2000 CE"], "BCE means before the common era."],
  ["BCE years count…", "backwards toward 1 CE", ["upwards from 0 for ever", "in random order", "by moons"], "3000 BCE is earlier than 2000 BCE."],
  ["Which came first?", "3000 BCE", ["2000 BCE", "1000 BCE", "500 BCE"], "The bigger BCE number is earlier."],
  ["Societies need rulers and laws to…", "keep order and organize shared work", ["end farming", "stop trade", "avoid writing"], "Governance is part of civilization."],
  ["Why is it valuable to study early societies?", "to understand where our ideas and institutions began", ["to avoid all change", "because they are the same as today", "because there is nothing to learn"], "Many parts of modern life began long ago."],
  ["Which of these began in early societies and still matters today?", "writing", ["television", "email", "satellites"], "Writing helps us keep and share knowledge."],
  ["Which technology of early societies still helps us?", "the wheel", ["the microchip", "nuclear power", "the rocket"], "Wheels move people and goods."],
  ["Irrigation in early societies helped farmers…", "bring water to crops", ["remove water completely", "make ice", "stop floods for all time"], "It increased food supply."],
  ["Why were early societies' tools made of bronze rather than iron at first?", "bronze was easier to cast", ["iron was not found anywhere", "iron was too soft", "they had no fire"], "Iron working came later.", true],
  ["Why did early civilizations develop writing?", "to keep records of trade, taxes and laws", ["to send emails", "to win contests", "to make maps of space"], "Writing began as record-keeping.", true],
  ["Which is a way that Egypt and Mesopotamia were alike?", "both depended on rivers for farming", ["both built Great Walls", "both built ziggurats", "both used cuneiform"], "Rivers were central.", true],
  ["Which is a way that Egypt and Mesopotamia were different?", "Egypt's pharaoh united the kingdom; Mesopotamia had separate city-states", ["Egypt had no river", "Mesopotamia had no farming", "Egypt had no writing"], "Their governments were organized differently.", true],
  ["Which statement shows a lasting contribution from early societies?", "the 60-minute hour and the 365-day year", ["the telephone", "the car", "the internet"], "Mesopotamia and Egypt both left time-keeping ideas.", true],
  ["Why are early adaptations for survival an enduring human aspiration?", "people everywhere have looked for safe food, water and shelter", ["people stopped needing them", "these only mattered in Egypt", "no one needs shelter"], "Basic needs link us with the past.", true],
  ["What evidence do archaeologists use to study early technologies?", "tools, buildings and everyday objects", ["only Roman texts", "photos", "radio recordings"], "Objects can show how people lived.", true],
  ["A museum shows a Sumerian clay tablet and an Egyptian papyrus. What does this suggest?", "different societies used different materials for writing", ["they used the same", "neither used writing", "both used paper"], "Local materials shaped technology.", true],
];

const RELIGIONS: Q[] = [
  ["Hinduism developed in…", "the Indian subcontinent", ["Rome", "Mesopotamia", "Egypt"], "It is one of the oldest religions still practised."],
  ["Hindu teachings are found in sacred writings such as the…", "Vedas", ["Torah", "Analects", "Gospels"], "They were first recited orally."],
  ["Many Hindus believe in…", "the cycle of birth, death and rebirth", ["only one life", "no spirit", "nature spirits only"], "Karma and rebirth are important ideas."],
  ["Judaism teaches belief in…", "one God", ["many gods", "no god", "nature spirits only"], "It is one of the first monotheistic religions."],
  ["The Torah is…", "the central sacred text of Judaism", ["a Buddhist teaching", "a Roman law", "a Greek play"], "It contains the five books of Moses."],
  ["The word monotheism means belief in…", "one God", ["many gods", "no gods", "gods of nature only"], "Mono means one."],
  ["Buddhism began with the teachings of…", "Siddhartha Gautama, the Buddha", ["Confucius", "Moses", "Jesus"], "He taught in what is now Nepal and India."],
  ["The Buddha taught that suffering comes from…", "desire and attachment", ["the weather", "the Sun", "the sea"], "The Four Noble Truths describe it."],
  ["The Eightfold Path in Buddhism is…", "a guide to ethical living and wisdom", ["a map to a city", "a list of kings", "a calendar"], "It leads toward ending suffering."],
  ["Confucius was a thinker in…", "China", ["Greece", "Egypt", "India"], "He lived about 2,500 years ago."],
  ["Confucianism stresses…", "respect, family duty and good relationships", ["warfare", "wealth", "travel"], "Its teachings guide society."],
  ["Is Confucianism a religion, a philosophy, or both?", "scholars describe it as an ethical philosophy that also has religious aspects", ["only a calendar", "only a sport", "only a language"], "It focuses on how to live well with others."],
  ["Christianity began with the teachings of…", "Jesus of Nazareth", ["Buddha", "Confucius", "Zoroaster"], "It began in the Roman province of Judea."],
  ["The sacred book of Christianity is the…", "Bible", ["Analects", "Vedas", "Qur'an"], "It has the Old and New Testaments."],
  ["Christianity spread across the Roman Empire because of…", "roads, trade and the work of early followers", ["television", "machines", "the printing press"], "Ideas travelled with people."],
  ["Which of these religions began in India?", "Hinduism and Buddhism", ["Judaism and Christianity", "Confucianism and Hinduism", "Christianity and Buddhism"], "Both began on the Indian subcontinent."],
  ["Which religion began in Judea (modern Israel and Palestine) and is rooted in the Hebrew people's history?", "Judaism", ["Buddhism", "Hinduism", "Confucianism"], "Its history includes Abraham and Moses."],
  ["Which beliefs do many world religions share?", "teachings about how to live ethically and treat others", ["the same gods", "the same holidays", "the same calendar"], "Ethical teachings are common to many traditions."],
  ["Showing respect for others' beliefs means…", "learning about them and treating followers fairly", ["making fun of them", "ignoring them", "forcing them to change"], "Respect and open-mindedness go together."],
  ["Buddhism spread from India to…", "much of Asia", ["only Rome", "only Egypt", "only Greece"], "Monks and traders carried it along trade routes.", true],
  ["The Golden Rule, treating others as you want to be treated, appears in…", "many religions and ethical traditions", ["only one tradition", "no tradition", "Roman law only"], "Similar ideas appear in different places.", true],
  ["Why can religions be both a source of unity and conflict?", "they bring people together but disagreements can arise", ["they are always peaceful", "they are never important", "they are the same for all"], "History shows both.", true],
  ["Christianity was first banned in parts of the Roman Empire. Later it became…", "the main religion of the empire", ["forgotten", "the religion of China", "an Egyptian faith"], "Emperor Constantine ended the persecution.", true],
  ["Confucius's teachings were collected in a book called the…", "Analects", ["Vedas", "Torah", "Gospels"], "His students recorded his sayings.", true],
  ["Rites such as prayer, meditation or ceremonies help followers of a religion to…", "express beliefs and feel connected", ["avoid all learning", "stop thinking", "end community"], "Practices carry meaning.", true],
  ["The Hindu idea of dharma is closest to…", "duty or right conduct", ["wealth", "travel", "rain"], "It guides how to live.", true],
];

const CHINA_PERSIA_MAYA: Q[] = [
  ["The first emperor of unified China, Qin Shi Huang, ruled from…", "221 BCE", ["1000 CE", "500 CE", "1500 CE"], "He united warring states."],
  ["The Han dynasty of China is known for…", "paper, the Silk Road and a strong government", ["pyramids", "the printing press in Europe", "the telephone"], "Paper was invented in Han China."],
  ["The Silk Road was…", "a network of trade routes linking China to the West", ["one paved highway", "a river", "a type of cloth"], "Silk, spices and ideas travelled along it."],
  ["The Great Wall of China was built to…", "protect against invaders from the north", ["hold water", "mark a market", "grow crops"], "Walls were joined and extended over centuries."],
  ["The Terracotta Army was buried with…", "Emperor Qin Shi Huang", ["Cyrus the Great", "Julius Caesar", "Pharaoh Khufu"], "Thousands of clay soldiers guard his tomb."],
  ["Chinese philosophy such as Confucianism helped to…", "guide government and family life", ["end trade", "stop farming", "build pyramids"], "Ideas shaped society."],
  ["The Persian Empire was founded by…", "Cyrus the Great", ["Qin Shi Huang", "Augustus", "Pericles"], "He ruled in the 500s BCE."],
  ["Persia was known for tolerance because Cyrus…", "allowed people in conquered lands to keep their customs and religion", ["banned all religion", "burned books", "ended trade"], "The empire was very diverse."],
  ["The Royal Road in Persia was…", "a long road that sped up messages and trade", ["a river", "a wall", "a tower"], "Relay riders carried messages across it."],
  ["Persia divided its empire into provinces ruled by…", "governors called satraps", ["consuls", "pharaohs", "tribunes"], "This helped govern a huge empire."],
  ["The Persian Empire stretched from…", "Egypt to the Indus Valley", ["Canada to Mexico", "Spain to Britain only", "Japan to Australia"], "It was the largest the world had yet seen."],
  ["Persia fought wars with…", "Greek city-states", ["the Aztecs", "the Vikings", "the Inuit"], "The Persian Wars include Marathon and Salamis."],
  ["The Maya lived in…", "Mesoamerica (southern Mexico and Central America)", ["Mesopotamia", "Egypt", "Scandinavia"], "Their descendants live there today."],
  ["The Maya built…", "stone pyramids and temples", ["castles with moats", "skyscrapers", "railways"], "Cities like Tikal had great temples."],
  ["The Maya were skilled in…", "astronomy and a detailed calendar", ["steam power", "printing", "sailing across oceans"], "They tracked the Sun, Moon and Venus."],
  ["The Maya developed…", "a writing system of glyphs", ["the alphabet", "cuneiform", "hieroglyphs"], "Glyphs recorded history and kings."],
  ["Maya farmers grew…", "maize, beans and squash", ["wheat and rice only", "potatoes only", "tea and coffee only"], "Maize was central."],
  ["The Maya civilization reached its peak in the Classic Period around…", "250 to 900 CE", ["3000 BCE", "1500 CE", "1900 CE"], "Many cities were later abandoned or declined.", true],
  ["Maya people live today in…", "Mexico, Guatemala, Belize and nearby countries", ["only ruins", "nowhere", "Europe only"], "The Maya are a living people.", true],
  ["Which Chinese invention spread west along the Silk Road?", "paper and silk", ["printing in Rome", "the computer", "the radio"], "Later, papermaking reached the Islamic world.", true],
  ["How did Persia keep a huge empire together?", "roads, provinces and tolerance of local customs", ["only by war", "by ignoring distant lands", "by closing borders"], "Good administration helped.", true],
  ["Compared with Rome, Persia was often more…", "tolerant of local religions", ["isolated from trade", "democratic", "unknown"], "Both empires were large and diverse.", true],
  ["The Maya Long Count calendar was used to…", "record historical dates over long periods", ["tell the weather", "count money", "measure miles"], "It numbered days from a mythical start.", true],
  ["The Maya used a base-20 counting system with…", "a symbol for zero", ["no number zero", "only fractions", "Roman numerals"], "They were among the first to use zero.", true],
  ["What trade link joined China with Rome?", "the Silk Road", ["the Royal Road only", "the Nile only", "the Panama Canal"], "Silk travelled thousands of kilometres.", true],
  ["Which statement about the ancient civilizations of 500 BCE to 500 CE is accurate?", "they existed at the same time in different parts of the world", ["they all lived in one country", "they never traded", "they were the same"], "Parallel developments occurred globally.", true],
];

const LEGACY: Q[] = [
  ["Democracy comes from Greek words meaning…", "rule by the people", ["rule by one king", "rule by soldiers", "rule by priests"], "Demos means people."],
  ["Which Greek city-state is known for developing democracy?", "Athens", ["Sparta", "Troy", "Memphis"], "Athenian citizens voted on laws."],
  ["Which ancient city is known for lawmaking and the rule of law with the Twelve Tables?", "Rome", ["Athens", "Ur", "Mohenjo-daro"], "Roman law influenced many countries."],
  ["The rule of law means…", "everyone must follow the same laws, including leaders", ["only citizens obey", "leaders can break rules", "laws change daily"], "It is a basis for fair societies."],
  ["Why is the rule of law important today?", "it protects people's rights and treats them fairly", ["it removes all laws", "it is only for leaders", "it is only for judges"], "Fair laws help communities."],
  ["A benefit of living in a democracy is…", "citizens can take part in decisions", ["no laws exist", "one person decides all", "elections never happen"], "Voting and speaking up are citizens' rights."],
  ["Which modern idea began in ancient Greece?", "the Olympic Games", ["the internet", "railways", "the telephone"], "They began in Olympia in 776 BCE."],
  ["Which English words come from Greek?", "democracy and geography", ["tomato and canoe", "moose and igloo", "bungalow and shampoo"], "Many science and government terms are Greek."],
  ["Which language gave us many scientific and legal terms?", "Latin", ["Cree", "Hindi", "Swahili"], "Latin roots appear throughout English."],
  ["Roman roads and aqueducts show Rome's skill in…", "engineering", ["farming only", "singing", "weaving only"], "Some Roman structures still stand."],
  ["Greek theatre gave us the words and ideas of…", "tragedy and comedy", ["video games", "movies on screen", "novels"], "Plays were performed in open-air theatres."],
  ["Greek myths were stories about…", "gods, heroes and the natural world", ["tax rules", "road maps", "recipes"], "They explained life and taught values."],
  ["Why do we still read Greek myths?", "they show how people understood the world and what they valued", ["they are science textbooks", "they are laws", "they are maps"], "Stories are windows to the past."],
  ["Which architecture feature from Greece and Rome do we see in modern buildings?", "columns", ["glass walls", "steel frames", "elevators"], "Many banks and courts use columns."],
  ["Roman arches helped build…", "bridges, aqueducts and large buildings", ["only tents", "only boats", "only roads in the sea"], "Arches carry weight."],
  ["The Greek thinker Socrates is known for…", "asking probing questions", ["building the Colosseum", "ruling Rome", "founding Sparta"], "The Socratic method uses questions."],
  ["Aristotle and Plato were…", "Greek philosophers", ["Roman emperors", "Persian kings", "Egyptian pharaohs"], "They shaped Western philosophy."],
  ["Cement and concrete were used by the Romans to…", "build lasting structures like the Pantheon", ["write laws", "make wine", "paint portraits"], "Roman concrete is famous for lasting.", true],
  ["In ancient Athens, who could vote?", "adult male citizens, not women, enslaved people or foreigners", ["every person", "only soldiers", "only children"], "Democracy was limited by today's standards.", true],
  ["Modern democracies are different from Athenian democracy because they…", "include many more people, such as women and all adults", ["ban voting", "have a pharaoh", "have no laws"], "Rights have expanded over time.", true],
  ["Why is it important to appreciate the struggles of the past?", "they helped create rights and freedoms we have today", ["they were easy", "they did not matter", "no one remembers them"], "People worked hard for change.", true],
  ["The Roman Republic had two consuls to…", "share power so no one person ruled alone", ["collect taxes", "build roads only", "judge games"], "Power was divided.", true],
  ["Which Greek idea about government matters in Canada today?", "citizens should have a say in how they are governed", ["a king should rule for life", "only the rich decide", "voting is not allowed"], "Representative democracy has Greek roots.", true],
  ["A building with columns and a triangular roof piece follows the style of…", "Greek and Roman temples", ["Inuit shelters", "Maya pyramids", "Chinese pagodas"], "Classical style spread widely.", true],
  ["Which statement shows appreciation for the arts of the ancient world?", "people still study, perform and learn from them", ["they have been forgotten", "they were never made", "they have no meaning"], "Art lasts across generations.", true],
  ["Roman numerals are still used on…", "some clocks and for numbering events", ["all calculators", "all maps", "all money"], "X, V and I are examples.", true],
];

const ROME_TRADE: Q[] = [
  ["Roman roads helped trade because they…", "connected cities across the empire", ["blocked travel", "ended trade", "were only for soldiers"], "Goods and ideas travelled along them."],
  ["The Mediterranean Sea was important to Rome because it was…", "a highway for trade", ["a wall", "a desert", "a mountain"], "Rome called it “our sea”."],
  ["Which goods did Roman traders bring from far away?", "silk, spices and gems", ["televisions", "coffee machines", "gasoline"], "Silk came from China."],
  ["Latin spread across the empire partly because of…", "trade, the army and government", ["television", "printing press", "airplanes"], "Latin became the base of French, Spanish and Italian."],
  ["Trade between Rome and distant lands also carried…", "ideas, religions and technologies", ["only goods", "nothing else", "only gold"], "Exchange changed cultures."],
  ["Rome got grain from…", "Egypt and North Africa", ["Canada", "Australia", "Antarctica"], "Egypt was the breadbasket of Rome."],
  ["Roman coins helped trade by…", "providing a common money", ["ending barter", "making goods free", "ending taxes"], "Coins were accepted across the empire."],
  ["The Western Roman Empire fell in…", "476 CE", ["44 BCE", "1066 CE", "1492 CE"], "Rome's last western emperor was removed."],
  ["Which factor contributed to Rome's fall?", "invasions, weak leadership and economic trouble", ["too many roads", "too much trade only", "too few soldiers only"], "Several causes combined."],
  ["After the fall of the Western Roman Empire, Europe was divided into…", "many kingdoms", ["one republic", "one empire", "no kingdoms"], "Local rulers took control."],
  ["The Eastern Roman Empire, which lasted until 1453, was called the…", "Byzantine Empire", ["Persian Empire", "Mongol Empire", "Maya Empire"], "Its capital was Constantinople."],
  ["The period after Rome's fall is often called the…", "Middle Ages", ["Bronze Age", "Industrial Age", "Space Age"], "It lasted roughly 1,000 years."],
  ["Some call the early Middle Ages the “Dark Ages”. Why do many historians prefer not to use this name?", "there were many achievements in art, learning and trade", ["nothing happened", "it was always bright", "there were no people"], "The term is misleading.", true],
  ["Arab-Islamic culture expanded after the 600s CE. What did it bring?", "advances in science, mathematics and trade", ["the end of writing", "the end of cities", "the printing press"], "Scholars preserved and added to knowledge.", true],
  ["In Western Europe after Rome's fall, who preserved much learning?", "monks in monasteries", ["soldiers", "traders", "farmers only"], "They copied books by hand.", true],
  ["Roman roads in Europe still influence…", "the routes of some modern highways", ["no roads", "only canals", "only rivers"], "Many were built to last.", true],
  ["How did conquered peoples often take on Roman ways?", "they adopted Latin, law and building styles", ["all refused", "they were removed", "they kept nothing"], "Romanization spread culture.", true],
  ["The Pax Romana was a period of…", "relative peace and stability in the empire", ["constant war", "famine", "a plague"], "It lasted about 200 years.", true],
  ["The Romans also traded with India through…", "sea routes in the Indian Ocean", ["the Atlantic", "the Arctic", "no routes"], "Monsoon winds helped sailors.", true],
  ["Why can trade bring change to a society?", "it introduces new goods, ideas and ways of life", ["it keeps things the same", "it ends invention", "it removes culture"], "Exchange shapes cultures.", true],
  ["The Roman Empire was so big that it was hard to…", "defend and govern all its borders", ["build roads", "use coins", "speak Latin"], "Size added stress.", true],
  ["Which statement about the fall of the Western Roman Empire is accurate?", "it happened over time and not in one day", ["it happened in an hour", "it did not happen", "it was caused by one battle only"], "The empire declined across centuries.", true],
  ["The Byzantine Empire preserved…", "Greek and Roman law and learning", ["Viking ships", "Maya calendars", "the Silk Road"], "Constantinople became a centre of learning.", true],
  ["After 476 CE, which centre of trade connected Europe, Asia and Africa?", "Constantinople", ["Paris", "London", "Moscow"], "It sat between two continents.", true],
  ["Roman trade networks shared…", "foods, languages and technologies across regions", ["only coins", "only weapons", "nothing"], "Trade spreads culture.", true],
  ["The Western Roman Empire's fall led to…", "new societies forming in Europe", ["no change", "the end of people", "the end of language"], "Local kingdoms developed.", true],
];

export const units: Unit[] = [
  bankUnit({
    id: "mb-how-societies-begin",
    title: "How Societies Begin",
    emoji: "🌾",
    blurb: "Farming, surplus, stories and the environment",
    parentNote: "Children explore how people organized themselves to survive, how farming led to new jobs, how the natural environment shapes societies, and why different cultures have different origin stories.",
    standards: ["8-KI-009, 8-KI-010, 8-KL-022, 8-VI-004, 8-VL-008", "how societies organize and sustain themselves, origin stories and theories, the environment's influence and caring for it"],
    items: BEGIN,
  }),
  bankUnit({
    id: "mb-mesopotamia",
    title: "Mesopotamia",
    emoji: "🏺",
    blurb: "Cuneiform, ziggurats and the first city-states",
    parentNote: "Children learn about life between the Tigris and Euphrates rivers: city-states, irrigation, writing, laws and technology.",
    standards: ["8-KI-013, 8-KI-014, 8-KL-023, 8-KL-024, 8-KH-029, 8-KH-030, 8-KP-045, 8-KE-054", "life, art and science, geography, writing, governance and technology in Mesopotamia"],
    items: MESOPOTAMIA,
  }),
  bankUnit({
    id: "mb-egypt-8",
    title: "Ancient Egypt",
    emoji: "🔺",
    blurb: "The Nile, pharaohs, pyramids and hieroglyphs",
    parentNote: "Children learn how the Nile shaped life in Egypt, who held power, how writing and building worked, and what we know from archaeology.",
    standards: ["8-KI-013, 8-KI-014, 8-KL-023, 8-KL-024, 8-KH-029, 8-KH-030, 8-KP-045, 8-KE-054", "life, art and architecture, geography, writing, governance and technology in ancient Egypt"],
    items: EGYPT,
  }),
  bankUnit({
    id: "mb-indus-valley-8",
    title: "The Indus Valley",
    emoji: "🏙️",
    blurb: "Planned cities and a script still unread",
    parentNote: "Children learn about Harappa and Mohenjo-daro, how the Indus cities were planned, their trade, and what archaeologists can and cannot tell us.",
    standards: ["8-KI-013, 8-KI-014, 8-KL-023, 8-KL-024, 8-KH-029, 8-KH-030, 8-KP-045, 8-KE-054", "life, architecture, geography, writing, governance and technology in the Indus Valley"],
    items: INDUS,
  }),
  bankUnit({
    id: "mb-early-societies-8",
    title: "Early Societies Compared",
    emoji: "🗺️",
    blurb: "Mesopotamia, Egypt, Indus and China, 3500 to 500 BCE",
    parentNote: "Children compare four early river societies and think about why studying them helps us understand life today.",
    standards: ["8-KG-038, 8-VH-009, 8-VH-010, 8-VE-017", "defining characteristics of early societies, their historical significance and their technologies"],
    items: COMPARE,
  }),
  bankUnit({
    id: "mb-world-religions-8",
    title: "Religions & Ideas of Antiquity",
    emoji: "🕊️",
    blurb: "Hinduism, Judaism, Buddhism, Confucianism, Christianity",
    parentNote: "Children learn the main ideas, origins and sacred texts of five traditions that emerged in antiquity, with an emphasis on respect for different beliefs.",
    standards: ["8-KI-017, 8-VI-006", "defining characteristics of world religions that emerged in antiquity, and respect for others' beliefs"],
    items: RELIGIONS,
  }),
  bankUnit({
    id: "mb-china-persia-maya",
    title: "China, Persia & the Maya",
    emoji: "🐉",
    blurb: "Great empires and cities, 500 BCE to 500 CE",
    parentNote: "Children learn the defining features of ancient China, Persia and the Maya: governments, trade, building and learning.",
    standards: ["8-KG-039", "defining characteristics of the ancient civilizations of China, Persia and the Mayas"],
    items: CHINA_PERSIA_MAYA,
  }),
  bankUnit({
    id: "mb-greek-roman-legacy",
    title: "Lasting Ideas of Greece & Rome",
    emoji: "🏛️",
    blurb: "Democracy, law, language and building",
    parentNote: "Children connect democracy, the rule of law, language, art and engineering from Greece and Rome to life in Canada today.",
    standards: ["8-KE-061, 8-VC-001, 8-VC-002, 8-VI-005, 8-VP-016, 8-VH-011", "continuing influence of Greek and Roman ideas, democracy, the rule of law, the arts and myths"],
    items: LEGACY,
  }),
  bankUnit({
    id: "mb-rome-trade-fall",
    title: "Rome: Trade & Fall",
    emoji: "🛣️",
    blurb: "Roads, trade and what came after 476 CE",
    parentNote: "Children learn how trade carried goods and ideas around the Roman Empire, why the Western Roman Empire fell, and what followed.",
    standards: ["8-KE-055, 8-KH-033", "trade and the exchange of ideas in the Roman Empire, and the consequences of the fall of the Western Roman Empire"],
    items: ROME_TRADE,
  }),
];
