import type { Unit } from "../../types";
import { bankUnit, type Q } from "../own";

// Grade 8 science: Earth's energy balance, Earth's structure and the human circulatory system (SCI.8.E outcomes
// that no shared unit covers).

const ENERGY: Q[] = [
  ["What is the main source of energy for Earth's surface?", "the Sun", ["the Moon", "the oceans"], "Solar radiation heats Earth and drives weather."],
  ["Energy from the Sun reaches Earth as…", "radiation", ["sound waves", "ocean currents"], "Radiation can travel through empty space."],
  ["Albedo is a measure of…", "how much sunlight a surface reflects", ["how hot the Sun is", "how much rain falls", "how fast wind blows"], "Bright surfaces have a high albedo."],
  ["Which surface has the highest albedo?", "fresh snow", ["dark soil", "open water"], "Snow reflects most of the sunlight that hits it."],
  ["Which surface has the lowest albedo?", "dark asphalt", ["ice", "white clouds"], "Dark surfaces absorb more sunlight."],
  ["Why does a dark shirt feel hotter in the sun than a white shirt?", "it absorbs more radiation", ["it reflects more radiation", "it makes its own heat"], "Dark colours absorb more energy."],
  ["Earth's energy budget compares…", "the energy coming in with the energy going out", ["money spent on science", "the number of days in a year", "how much rain falls"], "In balance, Earth sends as much energy out as it takes in."],
  ["If Earth takes in more energy than it sends out, its temperature will…", "rise", ["fall", "stay exactly the same"], "Extra energy warms the planet."],
  ["Which gas is a greenhouse gas?", "carbon dioxide", ["oxygen", "nitrogen"], "Carbon dioxide traps heat in the atmosphere."],
  ["The greenhouse effect is…", "the trapping of heat by gases in the atmosphere", ["a way to grow vegetables only", "when Earth loses all its heat", "the formation of mountains"], "It is a natural process that keeps Earth warm."],
  ["Without any greenhouse effect, Earth would be…", "much colder", ["much hotter", "exactly the same"], "A natural greenhouse effect makes life possible."],
  ["Which of these adds extra greenhouse gases to the air?", "burning fossil fuels", ["planting trees", "riding a bike"], "Coal, oil and natural gas release carbon dioxide when burned."],
  ["Methane is a greenhouse gas released by…", "livestock, landfills and natural gas leaks", ["clean wind turbines", "solar panels", "snowfall"], "Methane traps heat very strongly."],
  ["Which type of radiation do greenhouse gases mostly trap?", "infrared", ["gamma rays", "radio waves"], "Earth gives off heat as infrared radiation."],
  ["Photosynthesis uses sunlight to make…", "glucose and oxygen", ["carbon dioxide and water", "salt and sand"], "Plants turn light energy into stored food energy."],
  ["Which green substance in plants absorbs light for photosynthesis?", "chlorophyll", ["glucose", "cellulose"], "Chlorophyll is in chloroplasts."],
  ["Which two things does a plant take in for photosynthesis?", "carbon dioxide and water", ["oxygen and glucose", "soil and wind"], "Plants take in carbon dioxide from the air and water from the soil."],
  ["In a food chain, the first source of energy is usually…", "the Sun, captured by plants", ["herbivores", "predators"], "Producers capture solar energy."],
  ["Producers in a food chain are…", "plants that make their own food", ["animals that hunt", "animals that eat plants", "fungi that break down waste"], "They form the base of the food pyramid."],
  ["In a food pyramid, which level has the most energy available?", "producers at the bottom", ["top predators", "second-level consumers"], "Energy is lost at each step up."],
  ["What happens to most of the Sun's energy that arrives at Earth?", "it is eventually radiated back to space", ["it stays forever", "it turns into rock", "it disappears from Earth entirely at once"], "In balance, energy in equals energy out."],
  ["Which would reduce greenhouse gas emissions?", "using public transit and renewable energy", ["burning more coal", "cutting down forests for fuel", "leaving lights on"], "Choices that burn less fossil fuel help."],
  ["Why do coastal areas often have milder weather than inland areas?", "water absorbs and releases heat slowly", ["water has no heat capacity", "land never warms up", "oceans reflect all sunlight"], "Water has a high heat capacity, so it warms and cools slowly.", true],
  ["Why does melting Arctic sea ice speed up warming?", "dark open water absorbs more sunlight than bright ice", ["water reflects more sunlight than ice", "ice makes heat", "open water has no effect"], "Less ice means a lower albedo.", true],
  ["Natural versus human greenhouse effect: what is different?", "human activity adds extra greenhouse gases", ["the natural effect uses no gases", "humans remove all gases", "there is no difference at all"], "People have increased the amount of carbon dioxide in the air.", true],
  ["Cutting down forests can raise carbon dioxide levels because trees…", "take in carbon dioxide during photosynthesis", ["make carbon dioxide only", "stop the Sun's light", "absorb infrared at night"], "Fewer trees means less carbon dioxide taken in.", true],
];

const EARTH: Q[] = [
  ["The outermost, thin, rocky layer of Earth is the…", "crust", ["mantle", "core"], "We live on the crust."],
  ["The layer under the crust is the…", "mantle", ["inner core", "atmosphere"], "The mantle is thick and mostly solid rock that can flow slowly."],
  ["Earth's outer core is…", "liquid metal", ["solid rock", "gas"], "It is mostly iron and nickel."],
  ["Earth's inner core is…", "a hot solid ball of metal", ["liquid water", "a gas cloud"], "Pressure keeps the inner core solid."],
  ["Which layer of Earth is the thickest?", "the mantle", ["the crust", "the outer core"], "The mantle makes up most of Earth's volume."],
  ["Which layer is the hottest?", "the inner core", ["the crust", "the mantle's top"], "Temperatures rise toward the centre."],
  ["Earth's internal heat comes partly from…", "radioactive decay and leftover heat from its formation", ["sunlight in the core", "ocean currents", "moonlight"], "Earth has been warm inside since it formed."],
  ["Tectonic plates are…", "large pieces of Earth's crust and upper mantle", ["moving clouds", "parts of the Sun", "layers of the ocean"], "They slowly move on the mantle."],
  ["Plates move at roughly the speed…", "your fingernails grow", ["of a car", "of a plane", "of a bicycle"], "Plates move a few centimetres each year."],
  ["Who proposed continental drift in 1912?", "Alfred Wegener", ["Albert Einstein", "Isaac Newton"], "Wegener noticed that continents seem to fit together."],
  ["What fossil evidence supported continental drift?", "the same fossils found on continents now far apart", ["fossils found only in Canada", "no fossils at all"], "Matching fossils suggest the land was once joined."],
  ["Where plates move apart, we find a…", "divergent boundary", ["convergent boundary", "fault of oceans"], "New crust forms at divergent boundaries."],
  ["Where plates push together, we find a…", "convergent boundary", ["divergent boundary", "lunar boundary"], "Mountains and volcanoes often form there."],
  ["Where plates slide past one another, we find a…", "transform boundary", ["divergent boundary", "volcanic island"], "Earthquakes are common at transform boundaries."],
  ["Most earthquakes happen…", "along faults near plate boundaries", ["in the middle of every plate", "only in the ocean", "only in summer"], "Stress builds up and releases suddenly."],
  ["A fault is…", "a crack in the crust where movement happens", ["a type of mountain", "a layer of the mantle", "a cloud"], "Rocks on each side of a fault can move."],
  ["Mountain ranges often form when plates…", "collide and push the crust upward", ["move apart quickly", "stop moving", "cool down"], "The Himalayas formed from a collision."],
  ["A volcano is…", "an opening where magma reaches the surface", ["a type of ocean", "a mountain made of ice", "a river"], "Magma that erupts is called lava."],
  ["Magma that flows out onto Earth's surface is called…", "lava", ["magma chamber", "ash"], "Magma becomes lava when it erupts."],
  ["The Ring of Fire is…", "a belt of many volcanoes and earthquakes around the Pacific Ocean", ["a hot desert", "a ring of mountains in Manitoba", "a set of moons"], "Many plate boundaries meet there."],
  ["Which tool detects and records earthquake waves?", "a seismograph", ["a thermometer", "a barometer"], "Seismographs measure ground shaking."],
  ["Convection currents in the mantle…", "help move the tectonic plates", ["make tides", "form clouds"], "Hot rock rises and cooler rock sinks.", true],
  ["Why does Manitoba have few earthquakes compared with the Pacific coast?", "it sits in the middle of a plate, far from the boundaries", ["it has no crust", "the mantle is missing", "the plates stopped moving"], "Most earthquakes occur near plate boundaries.", true],
  ["Which statement about a divergent boundary is correct?", "new crust forms as magma rises between the plates", ["plates crash into each other", "crust is destroyed", "plates stay the same"], "Mid-ocean ridges are examples.", true],
  ["Why are the crust and upper mantle together described as rigid plates?", "they are cool, solid rock that rides on softer mantle below", ["they are made of water", "they float on air", "they are hotter than the core"], "Below the plates the rock flows slowly.", true],
];

const BLOOD: Q[] = [
  ["The main job of the circulatory system is to…", "move blood carrying oxygen and nutrients around the body", ["digest food", "make bones", "see colours"], "Blood is the body's delivery system."],
  ["The organ that pumps blood is the…", "heart", ["lung", "liver"], "The heart is a muscle that squeezes."],
  ["How many chambers does a human heart have?", "four", ["two", "six"], "Two upper atria and two lower ventricles."],
  ["Blood vessels that carry blood away from the heart are called…", "arteries", ["veins", "capillaries"], "Arteries have thick, strong walls."],
  ["Blood vessels that return blood to the heart are called…", "veins", ["arteries", "bronchi"], "Veins have valves to keep blood moving one way."],
  ["The tiniest blood vessels, where oxygen and nutrients pass into cells, are the…", "capillaries", ["arteries", "chambers"], "Their walls are only one cell thick."],
  ["Red blood cells carry…", "oxygen", ["germs", "bones"], "Hemoglobin holds the oxygen."],
  ["White blood cells help the body…", "fight infection", ["carry oxygen", "digest food"], "They protect against germs."],
  ["Platelets help the body…", "clot blood and close cuts", ["carry oxygen", "fight viruses only"], "Platelets make a plug at a cut."],
  ["Plasma is…", "the liquid part of blood", ["a type of artery", "a heart valve"], "Most of blood is plasma, which is mostly water."],
  ["After blood travels through the body, it returns to the heart and is then pumped to the…", "lungs to pick up oxygen", ["stomach to eat", "brain to rest"], "The lungs add oxygen and remove carbon dioxide."],
  ["Which waste gas does blood carry to the lungs?", "carbon dioxide", ["oxygen", "helium"], "We breathe carbon dioxide out."],
  ["Homeostasis means…", "keeping the body's conditions steady", ["changing colour", "growing taller", "forgetting"], "The body works to keep temperature and other conditions stable."],
  ["When you exercise, your heart rate…", "goes up", ["goes down", "stops"], "Muscles need more oxygen, so the heart pumps faster."],
  ["Why do we feel warm after running?", "the body makes heat and blood carries it to the skin", ["the Sun is nearer", "blood stops moving", "bones make heat"], "Blood helps control temperature."],
  ["When you are too hot, the vessels near the skin…", "widen so more heat can escape", ["close so no heat leaves", "disappear", "become bone"], "This is part of temperature regulation."],
  ["A pulse is…", "the beat of blood in the arteries as the heart pumps", ["the sound of breathing", "a muscle in the leg", "a type of cell"], "You can feel it at your wrist or neck."],
  ["Which choice helps keep the heart healthy?", "regular exercise", ["never moving", "skipping all meals"], "A strong heart pumps blood well."],
  ["Which is a healthy habit for the circulatory system?", "eating a balanced diet", ["smoking", "avoiding all water"], "A healthy diet helps keep vessels clear."],
  ["What does blood take away from cells?", "waste such as carbon dioxide", ["bones", "toys"], "Cells release waste to the blood."],
  ["Valves in the heart and veins…", "keep blood flowing in one direction", ["make blood", "store oxygen"], "They prevent backflow."],
  ["Diffusion helps oxygen move from…", "the blood into body cells where there is less oxygen", ["cells into the blood only", "bones to muscles", "the air into the stomach"], "Substances move from high to low amounts.", true],
  ["Why is the left side of the heart more muscular?", "it pumps blood to the whole body", ["it holds bones", "it makes air", "it digests"], "The left ventricle sends blood far.", true],
  ["Why do athletes often have a lower resting heart rate?", "a stronger heart pumps more blood with each beat", ["their blood is thicker", "they have fewer vessels", "the heart is smaller"], "Efficient hearts need fewer beats.", true],
  ["Cells need a steady supply of blood because they…", "need oxygen and nutrients to make energy through cellular respiration", ["cannot use water", "do not make waste", "are made of blood"], "Cellular respiration uses oxygen and glucose.", true],
];

export const units: Unit[] = [
  bankUnit({
    id: "mb-earth-energy-8",
    title: "The Sun, Energy & Climate",
    emoji: "🌞",
    blurb: "Sunlight, albedo and the greenhouse effect",
    parentNote: "How sunlight warms Earth, why dark and bright surfaces differ, Earth's energy budget, the greenhouse effect, and photosynthesis at the start of every food chain.",
    standards: ["SCI.8.E.13, SCI.8.E.15, SCI.8.E.16, SCI.8.E.17", "solar energy, albedo, the energy budget, photosynthesis and the greenhouse effect"],
    items: ENERGY,
  }),
  bankUnit({
    id: "mb-earth-structure-8",
    title: "Inside Earth",
    emoji: "🌋",
    blurb: "Layers, plates, earthquakes and volcanoes",
    parentNote: "The layers of Earth, where Earth's heat comes from, how tectonic plates move, and why earthquakes, volcanoes and mountains form where they do.",
    standards: ["SCI.8.E.10, SCI.8.E.11, SCI.8.E.12", "the structure of Earth, its internal heat and tectonic activity"],
    items: EARTH,
  }),
  bankUnit({
    id: "mb-circulatory-8",
    title: "Heart & Blood",
    emoji: "❤️",
    blurb: "How blood keeps the body in balance",
    parentNote: "The heart, blood vessels and blood, how the circulatory system delivers oxygen and removes waste, and how it helps the body stay in balance.",
    standards: ["SCI.8.E.22, SCI.8.E.23", "homeostasis and the structure and function of the circulatory system"],
    items: BLOOD,
  }),
];
