import type { Unit } from "../../types";
import { bankUnit, type Q } from "../own";

// Grade 8 social studies, Origins of Western Society: early societies, ancient Greece and Rome, and how historians
// work (8-KI, 8-KC, 8-KH, 8-KL, 8-KP, 8-KE, 8-S outcomes). The medieval, Renaissance and exploration units are shared.

const WORLD_VIEWS: Q[] = [
  ["A world view is…", "the way a person or group understands the world and their place in it", ["a type of map", "a list of rulers"], "A world view shapes beliefs, values and choices."],
  ["Which of these can shape a person's world view?", "culture, religion and experience", ["only the weather", "only their age"], "Many influences shape how people see the world."],
  ["Two people see the same event very differently. This is most likely because of…", "different world views", ["a mistake in the calendar", "the colour of the paper"], "Different backgrounds lead to different views."],
  ["A civilization is a society that usually has…", "cities, government, writing and a way to grow food in surplus", ["only small camps", "no laws or leaders", "only one family"], "Civilizations are larger and more complex than small groups."],
  ["Which is a feature of a civilization?", "a system of writing", ["a single hut", "a travelling band with no leaders", "a short story told once"], "Writing helps record laws, trade and history."],
  ["A hunter-gatherer society gets food mostly by…", "hunting animals and gathering wild plants", ["farming large fields", "trading in big markets", "building factories"], "Hunter-gatherers move with the seasons to find food."],
  ["An advantage of a hunter-gatherer way of life is…", "a deep knowledge of the land and its plants and animals", ["large stores of grain", "permanent big cities", "writing on clay tablets"], "Hunter-gatherers know their lands very well."],
  ["A disadvantage of a hunter-gatherer way of life is that…", "food supplies depend on the seasons and on finding game", ["people never move", "there are no tools", "everyone farms"], "Food can be hard to find when seasons change."],
  ["Agrarian societies are based on…", "farming", ["hunting only", "fishing only", "trading only"], "Agrarian means connected with farming and the land."],
  ["What did the development of farming let people do?", "settle in one place and grow more food", ["stop eating", "avoid all tools", "forget their stories"], "Surplus food allowed villages and cities to grow."],
  ["A food surplus is…", "more food than people need right away", ["a lack of food", "a kind of tool", "a type of map"], "Surplus food can be stored or traded."],
  ["Why did early cities grow near rivers?", "rivers gave water, fertile soil and ways to travel", ["rivers stopped all floods", "rivers made deserts", "there were no other places"], "The natural environment shaped where people lived."],
  ["Which river valley was home to the early society of Egypt?", "the Nile", ["the Rhine", "the Red River"], "Yearly Nile floods left rich soil for farming."],
  ["Which early society lived between the Tigris and Euphrates rivers?", "Mesopotamia", ["Egypt", "Rome"], "Mesopotamia means “land between the rivers.”"],
  ["Which early writing was made by pressing a stylus into wet clay?", "cuneiform", ["hieroglyphics on papyrus", "the Latin alphabet"], "Cuneiform came from Mesopotamia."],
  ["Why was the development of writing so important?", "people could record laws, trade and stories", ["it ended farming", "it removed the need for leaders", "it stopped change"], "Writing helped societies keep records and pass on knowledge."],
  ["Societies pass on their beliefs, customs and knowledge through…", "stories, teaching and traditions", ["only machines", "only coins", "weather"], "Oral teaching and writing both pass on culture."],
  ["A society that changes slowly over time might do so because of…", "new ideas, new technology or contact with other peoples", ["nothing at all", "only one person's wishes", "the moon's colour"], "Societies change for many reasons."],
  ["Why might a society choose to stay the same?", "people value their traditions", ["they cannot learn", "they have no history", "they have no language"], "Traditions help people feel connected to their past."],
  ["Which of these is a reason for societies to change?", "contact and trade with other peoples", ["always being isolated", "never moving", "never speaking"], "New ideas spread along trade routes."],
  ["Many First Nations, Métis and Inuit peoples teach about their origins through…", "their own traditional stories and teachings", ["one story shared by all Nations", "only written textbooks", "the stories of Rome"], "Each Nation has its own teachings and stories."],
  ["Why is it important to learn that people have different stories of how the world began?", "it helps us respect different world views", ["so we pick the shortest story", "it proves nobody is right", "so we ignore science"], "Stories show what people value."],
  ["Being open to other world views means…", "being willing to listen and think about other ideas", ["agreeing with everyone always", "ignoring other people", "never asking questions"], "Respect starts with listening.", true],
  ["Why might two societies describe the same land differently?", "they use it in different ways and value different things", ["the land is changing colour", "maps cannot be used", "land has no meaning"], "Needs and values shape how people see a place.", true],
  ["A civilization depends on farming surplus because it lets some people…", "do work other than growing food, such as building or ruling", ["avoid eating", "skip all rules", "live without tools"], "With extra food, people can specialize.", true],
  ["Which statement best compares society and civilization?", "every civilization is a society, but not every society is a civilization", ["they are exactly the same", "a civilization has no people", "a society must have cities"], "Civilization is one kind of complex society.", true],
];

const HISTORY_SKILLS: Q[] = [
  ["A primary source is…", "created at the time of an event by someone who was there", ["written long afterward by a textbook author", "a guess about the past", "a modern movie"], "Letters, diaries and artifacts are primary sources."],
  ["Which is a primary source about ancient Greece?", "a pot painted in ancient Greece", ["a modern textbook", "a modern movie about Greece"], "An object from the time is a primary source."],
  ["A secondary source is…", "made later by someone who studied the past", ["a letter from the time", "an artifact dug up from the ground", "a coin from the era"], "Textbooks and documentaries are secondary sources."],
  ["Which is a secondary source?", "an encyclopedia article on Rome", ["a Roman coin", "a Roman letter"], "It was written later, using other sources."],
  ["An artifact is…", "an object made by people in the past", ["a story told today", "a weather report", "a rule of grammar"], "Tools, coins and pottery are artifacts."],
  ["An archaeologist learns about the past by…", "studying objects and sites left behind", ["voting in elections", "making new maps only", "predicting the weather"], "Digging carefully reveals how people lived."],
  ["Why is it important to know the past?", "it helps us understand how the world today came to be", ["so we can ignore the present", "because the past never changes", "it is only for games"], "History explains where we come from."],
  ["A timeline shows…", "events in the order they happened", ["only places", "only people's names", "random facts"], "Timelines help us see sequence and change."],
  ["On a timeline, which comes first?", "500 BCE", ["100 BCE", "100 CE"], "BCE years count down toward year 1."],
  ["BCE means…", "before the common era", ["big city era", "before Canadian events"], "Years BCE count backward from year 1."],
  ["A century is…", "100 years", ["10 years", "1000 years"], "The 5th century covers the years 401 to 500."],
  ["Which of these is a fact?", "Athens was a city in ancient Greece.", ["Athens was the best city.", "Everyone should visit Athens."], "A fact can be checked; an opinion is a belief."],
  ["Which of these is an opinion?", "The Roman roads were the most impressive achievement.", ["Rome built roads.", "Roman roads connected cities."], "“Most impressive” is a judgment."],
  ["Bias is…", "an unfair leaning toward one side", ["a kind of map", "a Roman coin", "a tool for digging"], "Bias can change how a story is told."],
  ["Why should you ask who wrote a source?", "the writer's purpose and point of view can affect what they say", ["it never matters", "all writers know everything", "to see how long it is"], "Check the writer's purpose and context."],
  ["Two historians tell different accounts of the same event. What should you do?", "compare the accounts and look at the evidence", ["throw both away", "choose the shorter one", "believe the first one you read"], "Comparing accounts helps check them."],
  ["Interpretations of history can change when…", "new evidence is found", ["nothing new is learned", "people forget everything", "the calendar changes"], "New discoveries can change what we understand."],
  ["A good historical question is…", "open, so it needs research to answer", ["answered with yes or no only", "a single date", "already answered by the question"], "Open questions start inquiry."],
  ["Which scale on a map shows how distances are measured?", "the scale bar", ["the compass rose", "the title"], "A scale bar compares the map to real distances."],
  ["A compass rose on a map shows…", "directions", ["the date", "the map's author", "the scale"], "North, south, east and west."],
  ["Latitude lines run…", "east and west and measure distance north or south of the equator", ["north and south", "only through cities", "diagonally"], "Latitude lines are parallel, like rungs of a ladder."],
  ["Longitude lines measure distance…", "east or west of the prime meridian", ["north of the equator", "above the ground", "from the sea floor"], "Longitude lines run from pole to pole."],
  ["Which would be the best way to check if a website about Rome is reliable?", "see if it names its authors and sources", ["check if it has colourful pictures", "see if it is the first result", "check how long the page is"], "Reliable sources show where information comes from.", true],
  ["Why do we treat historical sites with respect?", "they hold evidence about the past that cannot be replaced", ["so they stay empty", "because rules are fun", "to keep the weather away"], "Damaged sites lose their stories.", true],
  ["A museum shows a statue made by a Greek sculptor. This is useful evidence because…", "it shows what people made and valued at the time", ["it proves every Greek was an artist", "it tells the exact weather", "it shows nothing about the time"], "Material evidence tells us about everyday life and beliefs.", true],
];

const GREECE: Q[] = [
  ["Ancient Greece was made up of many…", "city-states", ["provinces", "colonies of Canada"], "Each city-state, called a polis, ran its own affairs."],
  ["A polis was…", "a Greek city-state", ["a type of boat", "a Roman road", "a pottery style"], "Athens and Sparta were two famous city-states."],
  ["The word democracy comes from Greek words meaning…", "rule by the people", ["rule by one king", "rule by soldiers", "rule by priests"], "Demos means people; kratos means power."],
  ["Which Greek city-state is known as the birthplace of democracy?", "Athens", ["Sparta", "Troy"], "Athens developed a government where citizens voted."],
  ["Which city-state was known for its strong, disciplined army?", "Sparta", ["Athens", "Corinth's theatre"], "Spartans trained for war from a young age."],
  ["In Athens, who could vote in the Assembly?", "adult male citizens", ["women and children", "enslaved people and foreigners", "everyone who lived there"], "Citizenship was limited to some people."],
  ["Which groups could NOT vote in Athenian democracy?", "women, enslaved people and foreigners", ["wealthy men only", "all adult men", "only generals"], "Athenian democracy included only a small part of the people."],
  ["Compared with Athens, Spartan society was more focused on…", "military training", ["theatre and philosophy", "sea trade only", "painting"], "Spartan boys were trained as soldiers."],
  ["How is modern Canadian citizenship different from Athenian citizenship?", "adults of all genders can vote", ["only men can vote", "nobody votes", "only the rich vote"], "Citizenship has grown to include more people."],
  ["In ancient Greece, enslaved people were…", "not citizens and had no say in government", ["voting members of the Assembly", "generals", "kings"], "Slavery was part of Greek society."],
  ["Which of these was a Greek god?", "Zeus", ["Odin", "Ra"], "Zeus was the ruler of the Greek gods on Mount Olympus."],
  ["Greek myths helped people…", "explain nature and teach values", ["pay taxes", "build roads", "write laws"], "Myths were important in Greek culture."],
  ["Where did the Greeks believe the gods lived?", "Mount Olympus", ["Mount Everest", "the Nile"], "Mount Olympus is a real mountain in Greece."],
  ["The Olympic Games began in ancient Greece to honour…", "Zeus", ["the Roman emperor", "a king of Egypt"], "They were held at Olympia."],
  ["Which Greek thinker taught by asking questions?", "Socrates", ["Julius Caesar", "Alexander of Rome"], "The Socratic method uses questions to examine ideas."],
  ["Which Greek is called the father of medicine?", "Hippocrates", ["Pythagoras", "Homer"], "Doctors still reflect his ideas about careful observation."],
  ["Homer is remembered for…", "epic poems such as the Iliad and the Odyssey", ["building the Parthenon", "ruling Athens", "teaching geometry"], "The poems tell of heroes and the Trojan War."],
  ["The Parthenon is a temple in…", "Athens", ["Sparta", "Rome"], "It honours the goddess Athena."],
  ["Which Greek idea do we still use in government today?", "citizens voting on laws and leaders", ["rule by one all-powerful king", "no laws", "no elections"], "Modern democracy grew from Greek ideas."],
  ["Which words did English borrow from Greek?", "democracy and theatre", ["moose and toboggan", "bannock and muskeg"], "Many English words have Greek roots."],
  ["Geographically, ancient Greece had many islands and mountains, which…", "made travel by sea important and kept city-states separate", ["made it a desert", "joined all the cities", "stopped all trade"], "The environment influenced how Greeks lived."],
  ["The Greek city-states joined together to fight the Persian Empire. This shows…", "they could cooperate against a common enemy", ["they never fought", "they never traded", "they were ruled by Rome"], "Athens and Sparta united against Persia."],
  ["Alexander the Great spread Greek culture by…", "conquering lands from Greece to India", ["building the Great Wall", "founding Rome", "inventing writing"], "Greek ideas then spread across a huge area.", true],
  ["Why was Athenian democracy called a direct democracy?", "citizens voted on laws themselves instead of choosing representatives", ["it had no laws", "a king decided", "only generals voted"], "Canada has a representative democracy.", true],
  ["What weakened the Greek city-states?", "long wars among themselves", ["a lack of sunlight", "too many roads", "an excess of writing"], "The Peloponnesian War between Athens and Sparta wore them out.", true],
];

const ROME: Q[] = [
  ["According to legend, Rome was founded in…", "753 BCE", ["1867 CE", "1500 CE"], "Rome began as a small city in Italy."],
  ["Rome first grew as a…", "city on the Tiber River in Italy", ["village in Egypt", "island near Greece"], "It sat on a river that helped trade."],
  ["Before the empire, Rome was a…", "republic", ["monarchy only", "democracy of everyone"], "In a republic, citizens elect leaders."],
  ["In the Roman Republic, the Senate was…", "a council of powerful leaders who advised the government", ["a group of gladiators", "a school", "a type of army"], "Senators came from wealthy families."],
  ["Who was the first Roman emperor?", "Augustus", ["Zeus", "Hippocrates"], "He began the Roman Empire in 27 BCE."],
  ["Which Roman leader was a general who became dictator before he was killed in 44 BCE?", "Julius Caesar", ["Hippocrates", "Socrates"], "Caesar's death led to civil wars."],
  ["The Roman Empire expanded mainly through…", "war and conquest", ["only trading", "only farming", "only marriage"], "Roman armies conquered lands around the Mediterranean Sea."],
  ["The Roman army was successful partly because it was…", "well trained and organized", ["very small", "unpaid and unprepared", "made of children"], "Legions were disciplined units."],
  ["The Mediterranean Sea was important to Rome because…", "it connected the empire for trade and travel", ["it was frozen", "it was a desert", "no one could cross it"], "Rome called it “our sea.”"],
  ["Which was a famous Roman invention?", "concrete", ["the printing press", "the compass"], "Concrete helped them build large lasting structures."],
  ["Roman roads helped the empire by…", "moving soldiers, goods and messages quickly", ["slowing down travel", "blocking trade", "dividing cities"], "“All roads lead to Rome.”"],
  ["Aqueducts were built to…", "carry water to cities", ["store grain", "hold soldiers", "play games"], "Aqueducts used gravity to move water."],
  ["The Colosseum was used for…", "public games and shows", ["growing food", "storing water", "writing laws"], "Gladiator fights were held there."],
  ["Which language did the Romans speak?", "Latin", ["Greek only", "Cuneiform"], "Latin is the root of French, Spanish and Italian."],
  ["Which modern language developed from Latin?", "French", ["Cree", "Mandarin"], "French, Spanish and Italian are Romance languages."],
  ["In Rome, who made up the lowest class and had no freedom?", "enslaved people", ["senators", "generals"], "Slavery was common in the Roman world."],
  ["The Twelve Tables were…", "Rome's first written laws", ["a set of maps", "a temple", "a poem"], "They made laws public, so all could see them."],
  ["Roman law is important today because…", "ideas such as being innocent until proven guilty influence modern law", ["it is still in Latin everywhere", "it ended all crime", "it has no influence"], "The rule of law has deep roots."],
  ["Which religion became the official religion of the Roman Empire in the fourth century?", "Christianity", ["Norse myth", "the cult of Zeus"], "It began as a small group, then grew."],
  ["The Western Roman Empire fell in…", "476 CE", ["44 BCE", "1492 CE"], "The last western emperor was removed."],
  ["One cause of the fall of the Western Roman Empire was…", "invasions and weak rule", ["too much rain", "too many ships", "a shortage of Latin"], "Many forces weakened Rome."],
  ["Which of these shows Greek influence on Rome?", "Romans copied Greek art and gods", ["Romans banned Greek", "Romans never met Greeks", "Romans spoke Cree"], "Rome borrowed much from Greece."],
  ["Why did Rome build forts and cities across conquered lands?", "to control the lands and spread Roman ways", ["to hide from armies", "to avoid trade", "to end taxes"], "Roman towns brought roads, baths and law.", true],
  ["Compared with Athens, Rome's republic was a…", "representative system where elected officials governed", ["direct democracy where all voted on everything", "rule by one god", "council of children"], "Rome elected officials to rule.", true],
  ["Which difference between a republic and an empire is correct?", "an emperor holds most of the power in an empire", ["there is no government in a republic", "an empire has no army", "a republic has a king"], "Rome changed from republic to empire.", true],
];

export const units: Unit[] = [
  bankUnit({
    id: "mb-world-views-8",
    title: "World Views & Early Societies",
    emoji: "🌍",
    blurb: "How people see the world and build societies",
    parentNote: "What a world view is, how hunter-gatherer and farming societies differ, what makes a civilization, and why writing and farming changed early societies.",
    standards: ["8-KI-005, 8-KI-006, 8-KI-007, 8-KI-008, 8-KI-011, 8-KI-012", "world views, society and civilization, hunter-gatherer and farming societies"],
    items: WORLD_VIEWS,
  }),
  bankUnit({
    id: "mb-history-skills-8",
    title: "Being a Historian",
    emoji: "🔎",
    blurb: "Sources, evidence, timelines and maps",
    parentNote: "Telling primary from secondary sources, fact from opinion and bias, reading timelines and maps, and checking where information comes from.",
    standards: ["8-KH-027, 8-KH-028, 8-S-204, 8-S-207, 8-S-304, 8-S-306", "historical sources and evidence, timelines, maps, and fact from opinion"],
    items: HISTORY_SKILLS,
  }),
  bankUnit({
    id: "mb-ancient-greece",
    title: "Ancient Greece",
    emoji: "🏛️",
    blurb: "City-states, democracy and myths",
    parentNote: "Athens and Sparta, how democracy began and who could take part, Greek myths and thinkers, and the Greek ideas still used today.",
    standards: ["8-KC-001, 8-KC-002, 8-KC-003, 8-KI-015, 8-KI-016, 8-KH-031, 8-KH-032", "Greek social order, the rise of democracy, Athens and Sparta, myths and lasting ideas"],
    items: GREECE,
  }),
  bankUnit({
    id: "mb-ancient-rome",
    title: "Ancient Rome",
    emoji: "🏺",
    blurb: "Republic, empire, roads and law",
    parentNote: "How Rome grew from a republic to an empire, the army, roads and aqueducts, the rule of law, and why the Western Roman Empire fell.",
    standards: ["8-KC-004, 8-KL-025, 8-KP-046, 8-KP-047, 8-KP-048, 8-KE-056", "Roman government, expansion, technology, the rule of law and the empire's decline"],
    items: ROME,
  }),
];
