import { bankUnit, type Q } from "../own";

// Grade 9 social studies, Canada in the Contemporary World: citizenship, maps, Canada's place in the world,
// conflict and cooperation, poverty and sustainability, and inquiry skills.

const CITIZEN: Q[] = [
  ["Who is the elected head of a provincial government in Canada?", "the premier", ["the governor general", "the chief justice"], "The premier leads the party with the most seats."],
  ["Who leads the federal government?", "the prime minister", ["the premier", "the mayor"], "The prime minister usually leads the party with the most seats in the House of Commons."],
  ["The elected leader of a First Nation is called a…", "Chief", ["premier", "senator"], "Chiefs and councils are elected by community members."],
  ["Who leads the municipal government of a city such as Winnipeg?", "the mayor", ["the governor general", "the prime minister"], "Mayors and councillors are elected locally."],
  ["Manitoba elects how many members to the Legislative Assembly?", "57", ["14", "338"], "They are called MLAs."],
  ["Manitoba elects how many Members of Parliament to the House of Commons?", "14", ["57", "105"], "MPs represent federal ridings."],
  ["The rule of law means that…", "everyone, including the government, must follow the law", ["only citizens follow laws", "leaders are above laws"], "It is a democratic ideal."],
  ["Which is a democratic ideal?", "equality before the law", ["rule by one person", "no elections"], "Others include freedom, diversity and citizen participation."],
  ["Citizens help government by…", "voting, giving opinions and volunteering", ["ignoring elections", "never reading news"], "Participation keeps democracy strong."],
  ["Which is a way to influence a political decision?", "writing to your MLA or MP", ["staying silent", "waiting for others"], "Citizens can also sign petitions and join groups."],
  ["A petition is…", "a formal request signed by many people", ["a type of tax", "a court"], "Petitions can be presented to a legislature."],
  ["A political party is a…", "group of people who share ideas about how to govern", ["type of law", "kind of court"], "Parties choose candidates."],
  ["A labour union is an organization of…", "workers who bargain together for fair pay and conditions", ["owners only", "judges"], "Unions are one way people influence society."],
  ["The right to vote in federal and provincial elections starts at age…", "18", ["16", "21"], "You also need to be a Canadian citizen."],
  ["A responsibility of a citizen is to…", "obey the law and respect the rights of others", ["avoid paying taxes", "ignore jury duty"], "Rights come with responsibilities."],
  ["Which is a right of Canadian citizens?", "to vote and to run for office", ["to ignore laws", "to change the Charter alone"], "Democratic rights are in the Charter."],
  ["The notwithstanding clause (section 33) lets a legislature…", "override some Charter rights for up to five years", ["add a right", "cancel elections"], "It is a debated feature of the Charter.", true],
  ["The Charter has changed Canada because courts…", "can strike down laws that go against rights", ["write the laws", "run elections"], "Cases have shaped issues such as language and equality rights.", true],
  ["A challenge that has come with the Charter is that…", "people disagree about how to balance rights", ["rights were ended", "no one can use courts"], "Balancing rights is part of democracy."],
  ["An opportunity from the Charter is that…", "individuals and groups can protect their rights in court", ["laws never change", "elections stop"], "People can challenge unfair laws."],
  ["Which statement shows being an informed citizen?", "reading reliable news and learning about candidates", ["voting without any information", "sharing rumours"], "Informed choices make for a stronger democracy."],
  ["Citizens of the world also have responsibilities, such as…", "caring for the environment and human rights beyond Canada", ["ignoring other countries", "avoiding all travel"], "Global citizenship goes beyond borders."],
  ["Debate about citizenship is healthy when…", "people listen respectfully and use evidence", ["people shout", "only one view is allowed"], "Democracy needs respectful debate.", true],
  ["In a democracy, a government ruled only by the majority could…", "overlook the rights of minorities, which is why rights are protected", ["never make mistakes", "end elections"], "Constitutional rights protect minorities.", true],
  ["Which current issue relates to citizenship in Canada?", "who can vote, and how newcomers become citizens", ["the colour of the flag", "the price of a pencil"], "Citizenship is a topic of ongoing discussion."],
];

const MAPS: Q[] = [
  ["What is the capital of Canada?", "Ottawa", ["Toronto", "Winnipeg"], "It is in Ontario."],
  ["What is the capital of Manitoba?", "Winnipeg", ["Brandon", "Churchill"], "It is at the meeting of the Red and Assiniboine Rivers."],
  ["What is the capital of British Columbia?", "Victoria", ["Vancouver", "Kelowna"], "It is on Vancouver Island."],
  ["What is the capital of Saskatchewan?", "Regina", ["Saskatoon", "Moose Jaw"], "Regina is Saskatchewan's capital."],
  ["What is the capital of Nunavut?", "Iqaluit", ["Yellowknife", "Whitehorse"], "Iqaluit is on Baffin Island."],
  ["What is the capital of the Northwest Territories?", "Yellowknife", ["Iqaluit", "Whitehorse"], "It is on Great Slave Lake."],
  ["What is the capital of Quebec?", "Quebec City", ["Montreal", "Ottawa"], "It is on the St. Lawrence River."],
  ["What is the capital of Nova Scotia?", "Halifax", ["Sydney", "Fredericton"], "Halifax is on the Atlantic coast."],
  ["How many provinces and territories does Canada have?", "10 provinces and 3 territories", ["8 provinces and 5 territories", "13 provinces"], "The territories are Yukon, Northwest Territories and Nunavut."],
  ["Which body of water is on the northeast border of Manitoba?", "Hudson Bay", ["Lake Superior", "Pacific Ocean"], "Churchill is on Hudson Bay."],
  ["Which province lies directly to the west of Manitoba?", "Saskatchewan", ["Ontario", "Alberta"], "Ontario is to the east."],
  ["Which region covers most of northern Manitoba and about half of Canada?", "the Canadian Shield", ["the Appalachians", "the Cordillera"], "It is mostly rocky, with lakes and forest."],
  ["Southern Manitoba is mostly part of the…", "Interior Plains", ["Western Cordillera", "Appalachian region"], "The flat, fertile land is good for farming."],
  ["Which region is home to the Rocky Mountains?", "the Western Cordillera", ["the Canadian Shield", "the Interior Plains"], "It stretches across British Columbia and into Alberta."],
  ["Most Canadians live…", "in the southern part of the country, near the U.S. border", ["in the Arctic", "in the middle of the Shield"], "The south has milder climate and more farmland."],
  ["Which of these is a population cluster in Canada?", "the Windsor to Quebec City corridor", ["Baffin Island", "Hudson Bay Lowlands"], "It includes Toronto, Ottawa and Montreal."],
  ["On a map, the legend (key) tells you…", "what the symbols and colours mean", ["who drew it", "the age of the map"], "Always check it."],
  ["A map scale of 1:50 000 means 1 cm on the map is…", "500 m on the ground", ["50 m", "5 km"], "50 000 cm = 500 m."],
  ["Lines of latitude measure distance…", "north and south of the equator", ["east and west of the equator", "above sea level"], "They run east-west."],
  ["Lines of longitude measure distance…", "east and west of the prime meridian", ["north of the equator", "above sea level"], "The prime meridian is 0°."],
  ["A map that shows population density by colour is a…", "thematic map", ["compass", "globe"], "It focuses on one theme."],
  ["A tool that layers many kinds of map data on a computer is…", "GIS (geographic information system)", ["GPS clock", "a legend"], "Planners use GIS to compare maps."],
  ["GPS uses signals from…", "satellites", ["pigeons", "mountains"], "A receiver finds its location."],
  ["Traditional Knowledge can help make a map by…", "recording place names, trails and seasonal uses that Elders know", ["replacing every scale", "avoiding all places"], "Many communities map their lands.", true],
  ["On a world map, Ukraine is located in…", "Europe", ["South America", "Africa"], "It is in eastern Europe."],
  ["On a world map, Brazil is in…", "South America", ["Asia", "Europe"], "It is the largest country there."],
  ["On a world map, Sudan is in…", "Africa", ["Asia", "North America"], "It lies south of Egypt."],
];

const WORLD: Q[] = [
  ["In 1957 Lester B. Pearson won the Nobel Peace Prize for…", "proposing a United Nations peacekeeping force during the Suez Crisis", ["inventing the telegraph", "winning a war"], "Peacekeeping became a symbol of Canada's role."],
  ["Canada was a founding member of NATO in…", "1949", ["1849", "1989"], "NATO is a military alliance."],
  ["Canadian soldiers served in Afghanistan from 2001 to…", "2014", ["1951", "2024"], "Canada's combat mission ended in 2011 and training continued until 2014."],
  ["What is a peacekeeper?", "a soldier or officer who helps keep the peace after a conflict", ["a judge", "a diplomat who writes laws"], "Peacekeepers work under UN missions."],
  ["Remembrance Day is observed on…", "November 11", ["July 1", "May 24"], "It marks the end of the First World War in 1918."],
  ["The red poppy is worn to…", "remember those who served and died in wars", ["celebrate a holiday", "support a team"], "It is a symbol of remembrance."],
  ["“In Flanders Fields” is a poem written by…", "John McCrae", ["Pauline Johnson", "Robert Munsch"], "He was a Canadian doctor and soldier."],
  ["The Battle of Vimy Ridge in 1917 is remembered as…", "a moment when Canadian forces fought together as a force", ["the start of Confederation", "a hockey game"], "It is a symbol for many Canadians."],
  ["Canadians Frederick Banting and Charles Best are known for…", "the discovery of insulin", ["inventing the telephone", "building a satellite"], "Insulin helps people with diabetes."],
  ["Alexander Graham Bell is credited with…", "inventing the telephone", ["inventing insulin", "building the Canadarm"], "He worked in Brantford, Ontario, in the 1870s."],
  ["The Canadarm is a…", "robotic arm used on space shuttles", ["farm tool", "kind of boat"], "Canada built it for the space program."],
  ["Terry Fox's Marathon of Hope raised money for…", "cancer research", ["a sports stadium", "new highways"], "The Terry Fox Run now takes place around the world."],
  ["Margaret Atwood is a Canadian…", "author known around the world", ["prime minister", "hockey goalie"], "Arts are one way Canadians contribute globally."],
  ["Cirque du Soleil, a global performance company, began in…", "Quebec", ["Manitoba", "Nunavut"], "It is known for its circus arts."],
  ["Canada's private sponsorship of refugees means…", "groups of Canadians can sponsor and support refugees", ["only the government can help", "refugees cannot enter"], "The program began in 1979."],
  ["A refugee is a person who…", "leaves their country because of danger or persecution", ["travels for holidays", "moves for a job offer"], "Refugees need protection."],
  ["International development means…", "helping other countries improve health, education and economies", ["taking over a country", "building a border"], "Canada gives development aid."],
  ["The longest undefended border between two countries in the world is between Canada and the…", "United States", ["Mexico", "Russia"], "It is about 8900 km long."],
  ["CUSMA (also called USMCA) is a…", "trade agreement among Canada, the United States and Mexico", ["peace treaty", "sports league"], "It replaced NAFTA in 2020."],
  ["NORAD is a…", "joint Canada–U.S. organization that defends North American airspace", ["fishing treaty", "language law"], "It began in 1958."],
  ["A challenge in Canada–U.S. relations is…", "balancing trade with protecting Canada's own decisions and culture", ["having no shared border", "speaking different alphabets"], "Sovereignty and trade are linked."],
  ["Canada can show leadership on global issues by…", "joining international agreements and supporting those in need", ["ignoring other countries", "leaving the UN"], "Leadership can be diplomatic, humanitarian or environmental."],
  ["An example of Canada's role in a conflict is…", "sending peacekeepers or supporting a UN mission", ["building a wall", "closing all embassies"], "Canada's role has changed over time.", true],
  ["The United Nations was founded in 1945 to…", "keep peace and support human rights and cooperation", ["run sports teams", "collect Canadian taxes"], "Canada is a member."],
  ["When making decisions, it helps to consider local, national and global interests, because…", "choices in one place can affect people elsewhere", ["no one else is affected", "only one view is valid"], "Global citizens think beyond borders.", true],
];

const CONFLICT: Q[] = [
  ["Which is a peaceful way to resolve a conflict?", "negotiation", ["name-calling", "ignoring the problem forever"], "Negotiation means talking to find a solution."],
  ["In mediation, a neutral person…", "helps both sides reach an agreement", ["decides who wins", "takes sides"], "Mediators do not decide."],
  ["Compromise means…", "each side gives up something to find a solution", ["one side wins everything", "no one speaks"], "Both sides adjust."],
  ["Consensus means…", "everyone agrees to a decision they can support", ["a bare majority vote", "one person decides"], "It is used in many groups, including some Indigenous councils."],
  ["Which listening skill helps in a conflict?", "asking questions to understand the other side", ["interrupting", "rolling your eyes"], "Listening shows respect."],
  ["Restorative justice circles bring together…", "those harmed, those who caused harm and the community to repair relationships", ["only lawyers", "only police"], "They focus on healing."],
  ["Many Indigenous legal traditions use circles and Elders to…", "support talking, understanding and healing", ["decide by force", "avoid talking"], "Practices vary across Nations."],
  ["A treaty is…", "an agreement between nations or governments", ["a school rule", "a kind of tax"], "Treaties are a way to resolve differences."],
  ["The United Nations Security Council works to…", "maintain international peace and security", ["set hockey rules", "run Canadian elections"], "It can send peacekeepers."],
  ["Which statement shows a non-violent approach to a conflict?", "marching peacefully and speaking up for change", ["breaking property", "hurting people"], "Peaceful protest is a protected freedom."],
  ["A good way to start resolving a disagreement is to…", "stay calm and state how you feel without blaming", ["yell", "walk away without a word"], "“I” statements help."],
  ["When working with a group to solve a problem, it is helpful to…", "share jobs fairly and listen to each person's ideas", ["do it all yourself", "ignore others"], "Collaboration helps the group reach goals."],
  ["Fairness in a group means…", "everyone has an equal chance to be heard and treated well", ["the loudest voice wins", "only friends are included"], "Fair decisions respect everyone."],
  ["Taking a stand against discrimination can include…", "speaking up, reporting and supporting the person harmed", ["joining the group that is unfair", "staying silent"], "Allies act safely and respectfully."],
  ["A genocide is…", "the deliberate attempt to destroy a group of people because of who they are", ["a type of election", "an accident"], "It is a crime under international law."],
  ["The UN Genocide Convention was adopted in…", "1948", ["1848", "2008"], "It followed the Holocaust."],
  ["Which of these can help create the conditions for crimes against humanity?", "scapegoating, propaganda and the loss of rights", ["friendly neighbours", "strong, fair courts"], "These conditions can grow in times of turmoil."],
  ["Propaganda is…", "information used to push a view, often by spreading hate or fear", ["a balanced news report", "a weather forecast"], "It can dehumanize groups."],
  ["Which is a way to help prevent genocide?", "education, early action and holding offenders responsible", ["denial", "silence"], "Remembering history helps us act."],
  ["The International Criminal Court, in The Hague, tries people accused of…", "genocide, war crimes and crimes against humanity", ["traffic violations", "tax fraud"], "It was set up in 2002."],
  ["In what year did the genocide in Rwanda take place?", "1994", ["1894", "2014"], "Canadian General Roméo Dallaire led a UN mission there.", true],
  ["Lieutenant-General Roméo Dallaire is remembered for…", "his role with the UN in Rwanda and his advocacy for peace", ["Canada's Confederation", "the Red River Resistance"], "He later became a senator and author.", true],
  ["The Holodomor was a famine in 1932 and 1933 in…", "Ukraine", ["Manitoba", "Brazil"], "Canada recognizes it as a genocide.", true],
  ["Why is it important to learn about past genocides?", "to recognize warning signs and honour those who suffered", ["to take revenge", "to forget"], "Remembering helps prevent repetition."],
];

const POVERTY: Q[] = [
  ["Poverty means…", "not having enough resources to meet basic needs", ["owning a big house", "living in a city"], "Housing, food and clothing are examples."],
  ["Homelessness is when a person…", "has no stable, permanent place to live", ["lives with friends happily", "rents a home"], "It is an issue in cities and rural areas."],
  ["A food bank helps people by…", "providing food for those in need", ["selling expensive meals", "growing crops for sale"], "Many are run by volunteers and donations."],
  ["Which of these can help reduce poverty?", "affordable housing and good jobs", ["fewer schools", "less health care"], "Many solutions work together."],
  ["Which is a factor that can lead to child poverty?", "low family income and high costs of living", ["a big backyard", "a nearby park"], "Policies can help families."],
  ["Social programs, such as the Canada Child Benefit, are…", "government payments or services that help people meet needs", ["private gifts", "taxes only"], "They are funded by taxes."],
  ["Equity means…", "giving people what they need to have a fair chance", ["giving everyone the same thing", "ignoring differences"], "Different people may need different supports."],
  ["Why is nutrition important in schools?", "children learn better when they are fed", ["it makes lessons shorter", "it replaces teachers"], "School breakfast programs help."],
  ["Environmental stewardship means…", "taking care of the land, water and air for the future", ["using up all resources", "ignoring pollution"], "Stewards protect resources."],
  ["Sustainability means meeting today's needs…", "without harming the ability of future generations to meet theirs", ["by using everything now", "at no cost"], "It balances people, planet and economy."],
  ["Which Manitoba lake suffers from algae blooms caused by extra nutrients?", "Lake Winnipeg", ["Lake Superior", "Great Slave Lake"], "Phosphorus from farms, cities and other sources feeds the algae."],
  ["The Paris Agreement (2015) is an agreement among countries to…", "limit global warming", ["end all trade", "ban cars"], "Canada ratified it in 2016."],
  ["Most of Manitoba's electricity comes from…", "hydroelectric power", ["coal", "nuclear power"], "It is a low-emission source, though dams affect rivers."],
  ["Which choice supports sustainable development?", "using public transit and reducing waste", ["leaving lights on", "littering"], "Small choices add up."],
  ["A consumer's choices can affect the world because…", "what people buy affects workers, the environment and companies", ["no one is affected", "shops decide everything"], "Fair trade and local goods are examples."],
  ["A fair trade label tells you that…", "producers were paid a fair price and followed set standards", ["the product is free", "it was made by a robot"], "It supports workers."],
  ["Which statement shows ethical thinking about sharing resources?", "Everyone should have access to clean water and food", ["Only some deserve food", "Resources never need sharing"], "Ethics asks what is fair."],
  ["Respecting how First Nations, Métis and Inuit peoples relate to the land includes…", "listening to their voices on land and water decisions", ["ignoring their rights", "taking land without asking"], "Many communities lead conservation work today."],
  ["Which action helps the environment at home?", "recycling and composting", ["dumping paint in drains", "idling the car"], "Reduce, reuse, recycle."],
  ["Churchill, Manitoba, is known as…", "the polar bear capital of the world", ["the wheat capital", "the hockey capital"], "Climate change affects the sea ice that bears use.", true],
  ["Canada has made commitments to protect more land and water, such as…", "creating protected areas and parks", ["building only highways", "removing all parks"], "Protected areas help wildlife."],
  ["Which statement describes a sustainable community?", "It uses resources carefully and plans for the future", ["It ignores waste", "It never changes"], "Planning keeps resources for later."],
  ["Why might poverty be called a community issue and not just a personal one?", "it affects health, education and safety for everyone", ["it affects no one else", "it is always chosen"], "Systems and supports matter.", true],
  ["A proposal to make a more equitable society could include…", "raising access to housing, food and education", ["cutting every service", "ignoring evidence"], "Ideas should be backed by evidence.", true],
  ["Which is an example of promoting sustainable development in a school?", "starting a recycling and composting program", ["leaving taps on", "using more paper"], "Students can lead projects."],
];

const INQUIRY: Q[] = [
  ["A primary source is…", "created at the time of an event by someone who was there", ["written long after by a historian", "a textbook"], "Diaries, letters and photographs are primary sources."],
  ["A secondary source is…", "an account written later that interprets primary sources", ["a diary from the event", "a photograph taken at the time"], "Textbooks and documentaries are examples."],
  ["Which is the best first step in an inquiry project?", "plan your topic, goals and questions", ["write your conclusion", "print the result"], "Planning guides your research."],
  ["A good research question is…", "open and can be answered with evidence", ["answered by yes or no", "too broad to answer"], "It starts with how, why or to what extent."],
  ["Which source is likely most reliable for election results?", "Elections Canada", ["an anonymous post", "a rumour"], "Use official or expert sources."],
  ["To judge whether a source is reliable, ask…", "who made it, why, and how they know", ["how colourful it is", "how long it is"], "Check author, purpose and evidence."],
  ["Bias in a source means…", "it shows a one-sided point of view", ["it is always correct", "it has pictures"], "Compare sources to find bias."],
  ["Comparing news stories from several sources helps you to…", "see different perspectives and check facts", ["avoid reading", "decide the first one is right"], "Corroborate."],
  ["A political cartoon uses…", "images, symbols and humour to make a point", ["only facts", "only statistics"], "Look at the symbols and the message."],
  ["What is an effective way to organize information on a topic?", "a table, concept map or timeline", ["a random list", "a blank page"], "Choose a format that suits the information."],
  ["When you use someone else's ideas in a report, you should…", "give them credit by citing the source", ["pretend they are yours", "leave out the title"], "Referencing sources shows honesty."],
  ["A map is a better tool than a table for showing…", "where things are located", ["exact ages", "a list of laws"], "Choose tools that match the task."],
  ["A bar graph is useful for…", "comparing quantities among groups", ["showing a route", "telling a story"], "Match graph to data."],
  ["A timeline is useful for…", "showing events in order", ["comparing populations", "showing climate"], "It shows sequence."],
  ["Respectful language about people avoids…", "stereotypes and insulting terms", ["facts", "evidence"], "Use words that respect human diversity."],
  ["When someone expresses a different view, a good response is to…", "listen and ask clarifying questions", ["interrupt", "ignore them"], "Understanding comes first."],
  ["An informed opinion is based on…", "evidence and reasoning", ["guesswork", "a feeling alone"], "Support your claim with facts."],
  ["Which statement is an opinion?", "Canada's winters are too long.", ["Winnipeg is the capital of Manitoba.", "Canada has ten provinces."], "An opinion cannot be proven true or false."],
  ["Which statement is a fact?", "Manitoba joined Confederation in 1870.", ["Manitoba is the best province.", "Winter is the best season."], "Facts can be checked."],
  ["Reconsidering your assumptions after new information shows…", "open-mindedness", ["weakness", "poor planning"], "Good thinkers update their ideas."],
  ["In a debate, a strong argument has…", "a clear claim, evidence and a response to the other side", ["only loud speech", "personal insults"], "Debate means reasoning, not fighting.", true],
  ["A good presentation for an audience of younger students would use…", "simple words, images and short sentences", ["heavy jargon", "long paragraphs on slides"], "Match the format to the audience."],
  ["Analyzing context means…", "considering the time, place and people involved in an event", ["ignoring the date", "reading only the title"], "Context explains why people acted as they did."],
  ["Learner-gathered data, such as a class survey, should be checked for…", "reliability, such as a fair sample and clear questions", ["only colour", "popularity"], "Sample size and wording matter.", true],
  ["Which tool would you use to propose a new solution to a community problem?", "a plan with clear steps, supports and an expected outcome", ["a rumour", "a vague wish"], "Innovative options must be explained and defended.", true],
];

export const units = [
  bankUnit({
    id: "mb-citizens-and-democracy",
    title: "Citizens & Democracy Today",
    emoji: "🗳️",
    blurb: "Leaders, democratic ideals, rights, responsibilities and taking part.",
    parentNote: "Practises contemporary political leaders at each level, democratic ideals, the rights and responsibilities of citizens, the effects of the Charter, and ways to take part in Canada's political system.",
    standards: ["9-KC-009, 9-KC-011, 9-KC-013, 9-KC-014, 9-KC-015, 9-KP-046, 9-VC-001, 9-VC-002, 9-VC-003, 9-VP-015", "political leaders, democratic ideals, citizenship rights and responsibilities and participation"],
    items: CITIZEN,
  }),
  bankUnit({
    id: "mb-canada-on-the-map",
    title: "Canada on the Map",
    emoji: "🗺️",
    blurb: "Capitals, regions, population clusters and map skills.",
    parentNote: "Practises locating Canada's capitals, regions and population clusters, finding world locations, and using map tools such as scale, legends, latitude and longitude, GPS and GIS.",
    standards: ["9-KL-024, 9-KL-025, 9-S-203, 9-S-204", "Canada's physical and human geography, world locations and using maps"],
    items: MAPS,
  }),
  bankUnit({
    id: "mb-canada-and-the-world",
    title: "Canada & the World",
    emoji: "🌍",
    blurb: "Peacekeeping, Remembrance Day, contributions and neighbours.",
    parentNote: "Practises Canada's military and peacekeeping role, Remembrance Day, contributions of Canadians to the global community, refugees and development, and relations with the United States.",
    standards: ["9-KG-040, 9-KG-041, 9-KG-042, 9-KP-047, 9-VG-011, 9-VG-012, 9-VG-013", "Canada's role in global conflict, contributions to the global community and Canadian-American relationships"],
    items: WORLD,
  }),
  bankUnit({
    id: "mb-conflict-and-cooperation",
    title: "Conflict & Cooperation",
    emoji: "🕊️",
    blurb: "Resolving conflict, working together and preventing crimes against humanity.",
    parentNote: "Practises peaceful approaches to conflict, fairness and collaboration, and an age-appropriate look at the conditions that allow genocide and crimes against humanity and how they can be prevented.",
    standards: ["9-KG-035, 9-KP-043, 9-VP-014, 9-S-100, 9-S-101, 9-S-102, 9-S-104, 9-S-107", "conflict resolution, collaboration, fairness and global crimes against humanity"],
    items: CONFLICT,
  }),
  bankUnit({
    id: "mb-poverty-and-sustainability",
    title: "Poverty & Sustainability",
    emoji: "🌱",
    blurb: "Fair sharing, stewardship and choices that last.",
    parentNote: "Practises poverty issues in Canada and ideas for a more equitable society, environmental stewardship and sustainability, and the effect of consumer choices.",
    standards: ["9-KE-052, 9-KL-028, 9-VE-017, 9-VE-018, 9-VL-007, 9-S-103", "poverty, environmental stewardship, consumer choices and sustainable development"],
    items: POVERTY,
  }),
  bankUnit({
    id: "mb-social-studies-inquiry",
    title: "Inquiry & Sources",
    emoji: "🧭",
    blurb: "Sources, bias, evidence and respectful debate.",
    parentNote: "Practises social studies inquiry skills: choosing and judging sources, spotting bias, organizing information, supporting an opinion with evidence and discussing issues respectfully.",
    standards: ["9-S-200, 9-S-201, 9-S-202, 9-S-300, 9-S-301, 9-S-302, 9-S-303, 9-S-304, 9-S-305, 9-S-306, 9-S-307, 9-S-308, 9-S-400, 9-S-401, 9-S-402, 9-S-403, 9-S-404, 9-S-405, 9-S-406", "researching with sources, judging reliability and bias, and communicating reasoned views"],
    items: INQUIRY,
  }),
];
