import { bankUnit, type Q } from "../own";

// More Grade 9 math units written for Manitoba outcomes that the shared BC and Ontario units do not cover:
// circle properties (9.SS.1), composite surface area (9.SS.2), line and rotation symmetry (9.SS.5) and the role of
// probability in society (9.SP.4).

const CIRCLES: Q[] = [
  ["A line from the centre of a circle that meets a chord at a right angle…", "cuts the chord into two equal parts", ["makes the chord twice as long", "always passes through the tangent"], "The perpendicular from the centre bisects the chord."],
  ["A chord is 16 cm long. A perpendicular from the centre meets it. How long is each part?", "8 cm", ["16 cm", "4 cm"], "Bisect means cut in half: 16 ÷ 2."],
  ["A chord is 30 cm long and a perpendicular from the centre meets it. How far is that point from one end of the chord?", "15 cm", ["30 cm", "60 cm"], "The point is the midpoint of the chord."],
  ["A tangent touches a circle at point P. The angle between the tangent and the radius to P is…", "90°", ["45°", "180°"], "A tangent is perpendicular to the radius at the point of tangency."],
  ["An inscribed angle is 35°. The central angle on the same arc is…", "70°", ["35°", "17.5°"], "The central angle is twice the inscribed angle."],
  ["A central angle is 100°. The inscribed angle on the same arc is…", "50°", ["200°", "100°"], "The inscribed angle is half the central angle."],
  ["Two inscribed angles are drawn on the same arc. One measures 42°. The other measures…", "42°", ["84°", "21°"], "Inscribed angles on the same arc are equal."],
  ["An inscribed angle is 28°. What is the central angle on the same arc?", "56°", ["14°", "28°"], "Double it."],
  ["A central angle is 140°. What is an inscribed angle on the same arc?", "70°", ["280°", "140°"], "Halve it."],
  ["An inscribed angle stands on a diameter. How big is it?", "90°", ["180°", "45°"], "The central angle on a diameter is 180°, and half of 180° is 90°."],
  ["Which of these is true for inscribed angles on the same arc?", "They are congruent", ["They add to 90°", "They are each twice the radius"], "Congruent means equal in measure."],
  ["A radius is 5 cm and a chord is 8 cm long. How far is the chord from the centre?", "3 cm", ["4 cm", "5 cm"], "Half the chord is 4 cm. Then 3, 4, 5 is a right triangle.", true],
  ["A radius is 13 cm and a chord is 24 cm long. How far is the chord from the centre?", "5 cm", ["12 cm", "11 cm"], "Half the chord is 12 cm. Use 5² + 12² = 13².", true],
  ["A radius is 10 cm and the perpendicular distance from the centre to a chord is 6 cm. How long is the chord?", "16 cm", ["8 cm", "12 cm"], "Half the chord is √(10² − 6²) = 8 cm, so the chord is 16 cm.", true],
  ["A radius is 17 cm. A chord is 8 cm from the centre. How long is the chord?", "30 cm", ["15 cm", "25 cm"], "Half the chord is √(17² − 8²) = 15 cm.", true],
  ["A circle has a radius of 6 cm. A tangent segment runs from an outside point to the circle, and that point is 10 cm from the centre. How long is the tangent segment?", "8 cm", ["4 cm", "16 cm"], "The tangent meets the radius at 90°, so 6² + t² = 10².", true],
  ["The angle between a radius and a line from the centre to an outside point is 50°. The tangent from that point meets the radius at 90°. What is the third angle of the triangle?", "40°", ["90°", "130°"], "Angles in a triangle add to 180°: 180 − 90 − 50.", true],
  ["An inscribed angle measures x and the central angle on the same arc is 84°. What is x?", "42°", ["84°", "168°"], "The inscribed angle is half the central angle.", true],
  ["Why is a tangent to a circle never a chord?", "It touches the circle at only one point", ["It is always shorter than a radius", "It passes through the centre"], "A chord joins two points on the circle."],
  ["A diameter is a chord that…", "passes through the centre", ["touches the circle once", "is shorter than the radius"], "It is the longest possible chord."],
  ["Two chords are the same distance from the centre of a circle. What do you know about them?", "They have the same length", ["One is a tangent", "They cross at 90°"], "Equal distances from the centre mean equal chords."],
  ["Which statement about the central angle is true?", "Its vertex is at the centre of the circle", ["Its vertex is on the circle", "It is always 90°"], "An inscribed angle has its vertex on the circle."],
  ["A central angle is 180°. The inscribed angle on the same arc measures…", "90°", ["180°", "45°"], "Half of 180° is 90°."],
  ["To justify that a triangle with a diameter as one side is a right triangle, you could use…", "the inscribed angle on a diameter is 90°", ["all triangles have a 90° angle", "a tangent is a chord"], "A diameter makes a 180° central angle, so the inscribed angle is 90°."],
  ["Which line is perpendicular to the radius where it touches the circle?", "the tangent", ["the chord", "the arc"], "The tangent and the radius meet at 90°."],
];

const COMPOSITE: Q[] = [
  ["What is the surface area of a rectangular prism that is 6 cm by 4 cm by 3 cm?", "108 cm²", ["72 cm²", "54 cm²"], "2(6 × 4 + 6 × 3 + 4 × 3) = 2(24 + 18 + 12)."],
  ["Two cubes with 2 cm edges are glued face to face. What is the surface area of the new object?", "40 cm²", ["48 cm²", "24 cm²"], "Two cubes have 48 cm². Subtract the two faces that are now hidden, 4 cm² each."],
  ["Surface area is measured in…", "square units, such as cm²", ["cubic units, such as cm³", "units of length, such as cm"], "Surface area covers a surface, so it is in square units."],
  ["When two solids are glued together, the surface area of the composite object is…", "the total of both, minus the hidden faces", ["the total of both, plus the hidden faces", "the volume of both"], "The faces that touch are no longer on the outside."],
  ["A right triangular prism has a triangle with legs 3 cm and 4 cm and a hypotenuse of 5 cm. Its length is 10 cm. What is its surface area?", "132 cm²", ["120 cm²", "72 cm²"], "Two triangles: 2 × 6 = 12. Rectangles: (3 + 4 + 5) × 10 = 120."],
  ["A cylinder has a radius of 3 cm and a height of 10 cm. What is its surface area, to the nearest cm²?", "245 cm²", ["188 cm²", "283 cm²"], "2πr² + 2πrh = 18π + 60π = 78π."],
  ["A closed can has a radius of 4 cm and a height of 9 cm. What is its surface area, to the nearest cm²?", "327 cm²", ["226 cm²", "452 cm²"], "2π(4)² + 2π(4)(9) = 32π + 72π = 104π."],
  ["An open pail has a radius of 10 cm and a height of 24 cm and no lid. What is its outside surface area, to the nearest cm²?", "1822 cm²", ["1885 cm²", "1508 cm²"], "Bottom πr² = 100π plus side 2πrh = 480π, so 580π.", true],
  ["A 3 cm cube sits in the centre of the top of a 5 cm cube. What is the surface area of the combined object?", "186 cm²", ["150 cm²", "204 cm²"], "Big cube 150 cm². The small cube adds its four sides, 4 × 9 = 36. Its top replaces the covered part of the big cube's top.", true],
  ["A 2 cm cube sits on top of a box that is 8 cm by 5 cm by 2 cm. What is the surface area of the combined object?", "148 cm²", ["132 cm²", "164 cm²"], "The box is 132 cm². The cube adds its four sides, 4 × 4 = 16.", true],
  ["A house shape has a box 8 m long, 6 m wide and 4 m high with a triangular prism roof. The roof's triangles have a base of 6 m, a height of 4 m and slanted sides of 5 m. What is the surface area to paint (all outside faces except the floor)?", "216 m²", ["264 m²", "312 m²"], "Walls 112 m². Roof triangles 24 m². Roof slopes 2 × 5 × 8 = 80 m². Total 216 m².", true],
  ["A 4 cm cube has a 1 cm cube cut out of one corner. Compared with the full cube, the surface area is…", "the same, 96 cm²", ["smaller by 3 cm²", "larger by 6 cm²"], "Three faces lose 1 cm² each and three new faces of 1 cm² appear.", true],
  ["Three 1 cm cubes are glued in a row. What is the surface area?", "14 cm²", ["18 cm²", "10 cm²"], "Three cubes have 18 cm². Two joins hide 4 faces."],
  ["Four 1 cm cubes are glued in a 2 by 2 square layer. What is the surface area?", "16 cm²", ["24 cm²", "20 cm²"], "Four cubes have 24 cm². Four joins hide 8 faces."],
  ["Two identical 2 cm by 3 cm by 4 cm blocks are glued on their 3 cm by 4 cm faces. What is the surface area?", "80 cm²", ["104 cm²", "52 cm²"], "Each block has 52 cm². Together 104 cm². Subtract two 12 cm² faces."],
  ["Which faces are NOT counted in a composite surface area?", "faces that are glued together inside", ["the top faces", "the curved faces"], "Only the outside surface counts."],
  ["Two cubes of 2 cm edges are stacked to make a tower 2 cm by 2 cm by 4 cm. Which formula gives its surface area?", "2(2 × 2 + 2 × 4 + 2 × 4)", ["2(2 × 2) + 4", "2 × 2 × 4"], "Treat the tower as one rectangular prism."],
  ["A tower of three 2 cm cubes is 2 cm by 2 cm by 6 cm. What is its surface area?", "56 cm²", ["72 cm²", "48 cm²"], "2(4 + 12 + 12)."],
  ["One litre of paint covers 8 m². A composite object has a surface area of 40 m². How many litres cover it once?", "5 L", ["8 L", "320 L"], "40 ÷ 8."],
  ["A 10 cm by 10 cm by 3 cm box has a cylinder with a radius of 2 cm and a height of 5 cm standing on top. What is the surface area, to the nearest cm²?", "383 cm²", ["320 cm²", "446 cm²"], "Box 320 cm² plus the cylinder's curved side, 2π(2)(5) = 20π ≈ 63 cm². The cylinder's top replaces the covered circle.", true],
  ["A cube with a 5 cm edge has a 2 cm cube removed from one corner. What is the surface area?", "150 cm²", ["138 cm²", "162 cm²"], "Removing a corner cube leaves the surface area unchanged.", true],
  ["Which solids may a composite object in Grade 9 be made from?", "right cylinders, rectangular prisms and triangular prisms", ["spheres and cones only", "pyramids only"], "These are the three types named in the outcome."],
  ["The lateral (curved) surface of a cylinder, laid flat, is a…", "rectangle", ["triangle", "circle"], "Its length is the circumference, 2πr, and its height is h."],
  ["A tent is a triangular prism with no floor. The triangles have an area of 3 m² each, and the slanted rectangles are 2 m by 3 m each. What is the surface area of the cloth?", "18 m²", ["24 m²", "12 m²"], "Two triangles: 6 m². Two rectangles: 12 m². Total 18 m².", true],
];

const SYMMETRY: Q[] = [
  ["How many lines of symmetry does a square have?", "4", ["2", "8"], "Two through opposite corners and two through the midpoints of opposite sides."],
  ["How many lines of symmetry does a rectangle that is not a square have?", "2", ["4", "1"], "Only the two lines through midpoints of opposite sides."],
  ["How many lines of symmetry does an equilateral triangle have?", "3", ["1", "6"], "One from each vertex to the opposite side."],
  ["How many lines of symmetry does a regular pentagon have?", "5", ["10", "1"], "A regular polygon has as many lines as it has sides."],
  ["How many lines of symmetry does a regular hexagon have?", "6", ["3", "12"], "A regular polygon has one line for each side."],
  ["How many lines of symmetry does a scalene triangle have?", "0", ["1", "3"], "No two sides are equal, so no fold fits."],
  ["How many lines of symmetry does an isosceles triangle with exactly two equal sides have?", "1", ["2", "3"], "It folds along the line from the top vertex to the base."],
  ["How many lines of symmetry does a parallelogram (not a rectangle or rhombus) have?", "0", ["2", "4"], "It has rotation symmetry, but no line symmetry."],
  ["How many lines of symmetry does a rhombus (not a square) have?", "2", ["4", "0"], "The two diagonals."],
  ["How many lines of symmetry does a circle have?", "infinitely many", ["1", "360"], "Any line through the centre works."],
  ["A shape has rotation symmetry if it…", "fits onto itself in a turn of less than 360°", ["can be folded in half", "has four sides"], "A full turn always fits, so only smaller turns count."],
  ["What is the order of rotation symmetry of a square?", "4", ["2", "8"], "It fits on itself four times in one full turn."],
  ["What is the smallest angle of rotation that turns a square onto itself?", "90°", ["45°", "180°"], "360° ÷ 4."],
  ["What is the smallest angle of rotation for an equilateral triangle?", "120°", ["60°", "90°"], "360° ÷ 3."],
  ["What is the order of rotation symmetry of a regular hexagon?", "6", ["3", "12"], "A regular polygon's order equals its number of sides."],
  ["What is the smallest turn angle for a regular pentagon?", "72°", ["60°", "108°"], "360° ÷ 5."],
  ["What is the smallest turn angle for a regular octagon?", "45°", ["60°", "90°"], "360° ÷ 8."],
  ["What is the order of rotation symmetry of a rectangle that is not a square?", "2", ["4", "1"], "It fits after a 180° turn."],
  ["A parallelogram that is not a rectangle has rotation symmetry of order…", "2", ["4", "0"], "A half-turn (180°) fits it on itself."],
  ["A shape that fits onto itself only after a full 360° turn has rotation symmetry of order…", "1", ["0", "2"], "Order 1 is the same as no rotation symmetry."],
  ["Which letter has both line symmetry and rotation symmetry (in a plain font)?", "H", ["F", "P"], "H has two lines of symmetry and a half-turn symmetry."],
  ["Which letter has rotation symmetry but no line symmetry (in a plain font)?", "S", ["A", "T"], "S looks the same after a 180° turn."],
  ["Which letter has a line of symmetry but no rotation symmetry (in a plain font)?", "T", ["N", "Z"], "T folds along a vertical line but is upside down after a half-turn."],
  ["The point a shape turns around is called the…", "centre of rotation", ["line of reflection", "tangent"], "It stays in place while the shape turns."],
  ["A design has 3 equal arms around a centre point. What is its angle of rotation?", "120°", ["60°", "90°"], "360° ÷ 3.", true],
  ["A pattern has rotation symmetry with a smallest angle of 40°. What is its order?", "9", ["4", "40"], "360° ÷ 40°.", true],
  ["A shape has order 5 rotation symmetry and 5 lines of symmetry. Which shape could it be?", "a regular pentagon", ["a rectangle", "an isosceles triangle"], "A regular n-gon has n lines and order n.", true],
];

const CHANCE: Q[] = [
  ["The forecast says there is a 30% chance of rain. What is the chance that it does not rain?", "70%", ["30%", "130%"], "The two chances add to 100%."],
  ["A probability of 0 means the event is…", "impossible", ["certain", "unlikely"], "0 is the lowest probability."],
  ["A probability of 1 means the event is…", "certain", ["impossible", "even"], "1 is the highest probability."],
  ["What is the probability of tossing two heads in a row with a fair coin?", "1/4", ["1/2", "2/3"], "1/2 × 1/2."],
  ["A bag has 3 red and 5 blue marbles. What is the probability of picking red?", "3/8", ["3/5", "5/8"], "Red marbles out of all 8."],
  ["Two fair dice are rolled. What is the probability that the sum is 7?", "1/6", ["1/12", "7/36"], "6 of the 36 outcomes make a sum of 7.", true],
  ["A fair coin is flipped twice. What is the probability of at least one head?", "3/4", ["1/2", "1/4"], "Only tails twice misses: 1 − 1/4.", true],
  ["A coin lands heads five times in a row. What is the chance of heads on the next flip?", "1/2", ["less than 1/2", "more than 1/2"], "Each flip is independent. The coin has no memory."],
  ["Thinking that a number is “due” because it has not come up lately is called the…", "gambler's fallacy", ["law of large numbers", "theory of gravity"], "Past results of independent events do not change the next one."],
  ["A raffle ticket costs $2. There is a 1 in 100 chance to win $100. What is the average prize per ticket?", "$1", ["$2", "$100"], "$100 × 1/100.", true],
  ["In the raffle above, a ticket costs $2 and is worth $1 on average. Over many tickets, a player will…", "lose money on average", ["win money on average", "break even exactly"], "The average prize is less than the cost.", true],
  ["A game is fair when the average prize equals…", "the cost to play", ["zero", "the highest prize"], "Then nobody has an advantage over many plays."],
  ["Why do insurance companies use probability?", "to estimate how often claims will happen so they can set prices", ["to decide which houses will burn", "to avoid paying anyone"], "They look at large groups of people over many years."],
  ["A lottery has a 1 in 14 000 000 chance of winning. This means winning is…", "extremely unlikely", ["likely", "about even"], "A very small probability."],
  ["Why can a weather forecast of 70% still be wrong?", "70% is a chance, not a promise", ["forecasters never use data", "a 70% chance means it will rain for 70% of the day"], "A 30% chance of no rain can still happen."],
  ["A medical test is right 95 times in 100. If 1000 people take it, about how many results are wrong?", "50", ["5", "95"], "5% of 1000.", true],
  ["Flipping a coin 10 times gives 7 heads. What is this result called?", "an experimental result", ["the theoretical probability", "a sample space"], "It comes from doing the experiment."],
  ["The theoretical probability of heads on a fair coin is…", "1/2", ["7/10", "1"], "There are two equally likely outcomes."],
  ["As you repeat an experiment many more times, the experimental probability usually gets…", "closer to the theoretical probability", ["further from it", "equal to zero"], "This is the law of large numbers."],
  ["What is the list of all possible outcomes of an experiment called?", "the sample space", ["the tree", "the mean"], "For a coin it is heads and tails."],
  ["A spinner has 4 equal sections and a coin is tossed. How many outcomes are in the sample space?", "8", ["6", "4"], "4 × 2."],
  ["Which statement is a good use of probability?", "a city planning how many snowplows it needs", ["knowing exactly who will win a coin toss", "proving one die is lucky"], "Probability helps plan for what is likely, not certain."],
  ["Why might a person lose money by gambling over a long time?", "the games are designed so the average return is less than the cost", ["luck always runs out on day ten", "probabilities change when you lose"], "The average return to the player is below what they pay."],
  ["The chance of a certain flu shot preventing illness is 60%. If 200 people get it, about how many are protected?", "120", ["60", "140"], "60% of 200.", true],
  ["Two events cannot both happen at once, such as rolling a 2 and a 5 on one die. They are called…", "mutually exclusive", ["independent", "certain"], "If one happens, the other cannot."],
  ["A bag has 4 red and 6 blue marbles. One red is drawn and not put back. What is the probability that the next marble is red?", "3/9", ["4/10", "4/9"], "3 red marbles are left among 9.", true],
];

export const units = [
  bankUnit({
    id: "mb-circle-properties",
    title: "Circle Properties",
    emoji: "⭕",
    blurb: "Chords, tangents, and inscribed and central angles.",
    parentNote: "Practises circle properties: the perpendicular from the centre bisects a chord, central angles are twice inscribed angles on the same arc, inscribed angles on the same arc are equal, and a tangent is perpendicular to the radius.",
    standards: ["9.SS.1", "circle properties: chords, central and inscribed angles, and tangents"],
    items: CIRCLES,
  }),
  bankUnit({
    id: "mb-composite-surface-area",
    title: "Composite Surface Area",
    emoji: "🧱",
    blurb: "Find the surface area of objects made from prisms and cylinders.",
    parentNote: "Practises the surface area of composite 3-D objects made from right cylinders, rectangular prisms and triangular prisms, including subtracting the faces that are hidden.",
    standards: ["9.SS.2", "surface area of composite 3-D objects"],
    items: COMPOSITE,
  }),
  bankUnit({
    id: "mb-line-rotation-symmetry",
    title: "Line & Rotation Symmetry",
    emoji: "🦋",
    blurb: "Fold lines, turns and the order of symmetry.",
    parentNote: "Practises lines of symmetry and rotation symmetry (order and angle of rotation) in polygons, letters and designs.",
    standards: ["9.SS.5", "line and rotation symmetry"],
    items: SYMMETRY,
  }),
  bankUnit({
    id: "mb-probability-in-society",
    title: "Probability in Society",
    emoji: "🎲",
    blurb: "Chance, fair games, forecasts and risk.",
    parentNote: "Practises how probability is used in everyday life: forecasts, fair games and expected value, insurance, independent events and experimental versus theoretical probability.",
    standards: ["9.SP.4", "the role of probability in society"],
    items: CHANCE,
  }),
];
