import { bankUnit, type Q } from "../own";

// More Grade 9 science units written for Manitoba outcomes that the shared units do not cover: infectious disease
// (SCI.9.E.22), the human reproductive system (E.17), energy and magnetism (E.9, E.11), how science works
// (D.1 to D.4), science, technology and society (D.5 to D.8, C.1, C.5), measuring and lab safety (C.2 to C.4) and
// Indigenous ways of knowing (A.1, B.1). Indigenous content is light and needs partner review.

const DISEASE: Q[] = [
  ["Which of these can cause an infectious disease?", "bacteria and viruses", ["sunshine and sleep", "magnets and wires"], "Pathogens are germs that cause disease."],
  ["A pathogen is…", "an organism or virus that causes disease", ["a kind of vitamin", "a type of antibody"], "Bacteria, viruses, fungi and parasites can be pathogens."],
  ["Antibiotics are used to treat infections caused by…", "bacteria", ["viruses", "stress"], "Antibiotics do not work against viruses, such as the ones that cause colds and flu."],
  ["Why will antibiotics not help with a cold?", "a cold is caused by a virus", ["a cold is not an infection", "antibiotics are only for cuts"], "Antibiotics target bacteria."],
  ["A vaccine works by…", "preparing the body's immune system to recognize a pathogen", ["killing all germs in the air", "making the body warmer"], "The immune system learns to respond quickly."],
  ["Preventative medicine includes…", "vaccines and hand washing", ["waiting to get sick", "only taking medicine after symptoms"], "Preventing illness is better than treating it."],
  ["Which public health measure helps to stop a disease from spreading?", "washing hands and staying home when sick", ["sharing drinks", "ignoring symptoms"], "These steps lower the chance of passing germs on."],
  ["A strain of a pathogen is…", "a version with small genetic differences", ["a type of vaccine", "a human cell"], "Strains of the same virus can behave differently."],
  ["Mutations in a virus can lead to…", "new strains", ["fewer genes", "a vaccine becoming a bacterium"], "A mutation is a change in genetic material."],
  ["Why do people get a new flu shot each year?", "flu viruses mutate and new strains appear", ["the old shot turns into water", "the flu is caused by bacteria"], "Each year's vaccine is updated for the strains likely to spread."],
  ["Antibiotic resistance happens when…", "bacteria survive an antibiotic and pass on their resistance", ["people stop being allergic", "antibiotics become stronger by themselves"], "Natural selection favours the bacteria that survive."],
  ["Which action helps to prevent antibiotic resistance?", "finishing a prescription exactly as directed", ["sharing leftover antibiotics", "taking antibiotics for every cold"], "Use antibiotics only when needed and as prescribed."],
  ["Waning immunity means…", "protection from a vaccine or past infection fades over time", ["immunity is always permanent", "germs get stronger every year"], "Booster shots can restore protection."],
  ["A booster dose is given to…", "increase protection that has faded", ["cure a bacterial infection", "treat a sprained ankle"], "It reminds the immune system."],
  ["Herd (community) immunity occurs when…", "enough people are protected that the disease spreads poorly", ["everyone gets sick at once", "a disease becomes bacteria"], "It helps protect those who cannot be vaccinated.", true],
  ["Why is high vaccination coverage important for babies who are too young to be vaccinated?", "it lowers the chance they meet the disease", ["it makes them older", "it replaces breastmilk"], "Community immunity protects the vulnerable.", true],
  ["Smallpox was eliminated worldwide mainly through…", "vaccination", ["antibiotics", "quarantine of animals only"], "It is the only human disease declared eradicated by vaccination."],
  ["Which of these is a virus-caused disease?", "influenza", ["strep throat", "tuberculosis"], "Strep throat and tuberculosis are bacterial."],
  ["Which of these is a bacterial disease?", "strep throat", ["influenza", "measles"], "Antibiotics can treat strep throat."],
  ["Public health nurses and doctors track outbreaks to…", "find where a disease is spreading and respond", ["decide what to eat", "write recipes"], "Surveillance and contact tracing are public health tools."],
  ["Quarantine and isolation are used to…", "keep people who may spread an infection away from others", ["make people feel hot", "grow more bacteria"], "They reduce the spread of disease."],
  ["Which of these slows the spread of a respiratory virus?", "covering coughs and sneezes", ["sharing cups", "skipping handwashing"], "Droplets carry viruses."],
  ["Why do some diseases come back in a population even after being rare?", "fewer people are protected, or the pathogen changes", ["the pathogen forgets", "weather controls viruses"], "Lower coverage and mutation are two reasons.", true],
  ["An antibiotic kills most bacteria in an infection, but a few survive. What will the next generation of bacteria contain?", "more of the resistant bacteria", ["no bacteria", "only weak bacteria"], "The survivors reproduce.", true],
  ["The immune system's “memory” after a vaccine is why…", "a later infection is usually milder or prevented", ["vaccines cure all illness", "you can never be reinfected"], "Memory cells respond faster."],
  ["Which statement describes a vaccine best?", "It protects against a disease but does not treat everyone already sick", ["It is an antibiotic", "It is a vitamin"], "Vaccines prevent, antibiotics treat bacterial infections."],
];

const BODY: Q[] = [
  ["Sperm are made in the…", "testes", ["ovaries", "uterus"], "The testes are part of the male reproductive system."],
  ["Eggs (ova) are released from the…", "ovaries", ["testes", "bladder"], "The ovaries are part of the female reproductive system."],
  ["The uterus is where…", "a fertilized egg can implant and a fetus develops", ["sperm are made", "eggs are made"], "It is a muscular organ."],
  ["Fertilization usually happens in the…", "fallopian tube (oviduct)", ["uterus wall", "bladder"], "Egg and sperm meet in the tube."],
  ["Fertilization is when…", "a sperm cell joins an egg cell", ["an egg leaves the body", "the uterus lining sheds"], "It forms a zygote."],
  ["The main male sex hormone is…", "testosterone", ["estrogen", "insulin"], "It is produced mostly in the testes."],
  ["A main female sex hormone is…", "estrogen", ["testosterone", "adrenaline"], "It is produced mostly in the ovaries."],
  ["Hormones are…", "chemical messengers carried in the blood", ["tiny muscles", "types of bone"], "They help control growth and development."],
  ["Puberty begins when…", "hormones signal the body to develop adult features", ["a person turns exactly 10", "the body stops growing"], "The timing varies from person to person."],
  ["The structure that delivers food and oxygen to a developing fetus is the…", "placenta", ["ovary", "vas deferens"], "The umbilical cord connects the fetus to the placenta."],
  ["How long is a typical human pregnancy?", "about 40 weeks", ["about 4 weeks", "about 2 years"], "That is about nine months."],
  ["The menstrual cycle is a monthly pattern in which…", "the uterus lining builds up and is shed if no egg is fertilized", ["sperm are released", "hair stops growing"], "It averages around 28 days but varies."],
  ["Ovulation is the release of…", "an egg from an ovary", ["a sperm from a testis", "a hormone from the brain"], "It happens about once in each cycle."],
  ["The pituitary gland in the brain…", "releases hormones that signal the ovaries or testes", ["makes sperm", "makes eggs"], "It helps control the reproductive system."],
  ["A tube that carries sperm out of the male body is the…", "urethra (through the penis)", ["fallopian tube", "umbilical cord"], "Sperm travel from the testes through the vas deferens to the urethra."],
  ["Why are the testes found outside the body?", "sperm develop best slightly cooler than body temperature", ["to protect them from water", "they do not need blood"], "The scrotum helps to regulate temperature.", true],
  ["A fertilized egg that divides and attaches to the uterus lining is called…", "an embryo", ["a pathogen", "a hormone"], "Implantation happens about a week after fertilization.", true],
  ["Which structure is NOT part of the female reproductive system?", "testis", ["ovary", "uterus"], "The testis is part of the male system."],
  ["Which structure is NOT part of the male reproductive system?", "uterus", ["testis", "vas deferens"], "The uterus is part of the female system."],
  ["Identical twins develop from…", "one fertilized egg that splits", ["two eggs and two sperm", "one egg and no sperm"], "They share the same genes."],
  ["Fraternal twins develop from…", "two eggs fertilized by two sperm", ["one egg that splits", "one sperm"], "They are as alike as any siblings."],
  ["Why is the menstrual cycle different for different people?", "bodies vary in hormones and timing", ["it is the same for everyone", "it depends on the weather only"], "Differences are normal."],
  ["A health care provider is a good person to ask about…", "changes in your body during puberty", ["how to fix a bike", "what is on TV"], "Trusted adults, such as a doctor, nurse or family member, can help."],
  ["The body system that makes and controls hormones is the…", "endocrine system", ["digestive system", "skeletal system"], "It includes the pituitary, ovaries and testes.", true],
  ["The main purpose of the reproductive system is to…", "produce offspring", ["pump blood", "digest food"], "It makes the sex cells and supports development."],
  ["During pregnancy, the fetus is surrounded by fluid in the…", "amniotic sac", ["stomach", "lung"], "It cushions and protects.", true],
];

const ENERGY: Q[] = [
  ["The law of conservation of energy says that energy…", "cannot be created or destroyed, only changed from one form to another", ["can be made from nothing", "disappears when used"], "The total amount stays the same."],
  ["Energy stored in a stretched spring is…", "potential energy", ["kinetic energy", "sound energy"], "Stored energy is potential."],
  ["Energy of motion is…", "kinetic energy", ["potential energy", "chemical energy"], "Moving objects have kinetic energy."],
  ["A roller coaster at its highest point has the most…", "gravitational potential energy", ["kinetic energy", "sound energy"], "Height gives more stored energy."],
  ["As a roller coaster speeds down a hill, potential energy is changing into…", "kinetic energy", ["magnetic energy", "nuclear energy"], "Height is traded for speed."],
  ["A light bulb changes electrical energy into light and…", "heat", ["sound only", "mass"], "Some energy is always given off as heat."],
  ["Efficiency is the…", "percentage of input energy that becomes useful output", ["total input energy", "amount of wasted energy"], "Useful output ÷ total input × 100."],
  ["A device takes in 200 J and gives out 50 J of useful energy. What is its efficiency?", "25%", ["50%", "75%"], "50 ÷ 200 × 100."],
  ["A device takes in 500 J and gives 400 J of useful energy. What is its efficiency?", "80%", ["20%", "125%"], "400 ÷ 500 × 100."],
  ["An LED bulb is more efficient than an old incandescent bulb because it…", "wastes less energy as heat", ["uses no electricity", "makes no light"], "More of the input becomes light."],
  ["Where does the wasted energy of a car engine mostly go?", "heat", ["it vanishes", "it becomes new gasoline"], "Energy dissipates as heat and sound."],
  ["Which energy source is renewable?", "wind", ["coal", "natural gas"], "Wind is naturally replaced."],
  ["Which energy source is non-renewable?", "natural gas", ["solar", "hydro"], "It forms over millions of years."],
  ["A battery stores energy as…", "chemical potential energy", ["kinetic energy", "light"], "Chemical reactions release it as electrical energy."],
  ["When you rub your hands together, kinetic energy changes to…", "thermal energy (heat)", ["chemical energy", "nuclear energy"], "Friction produces heat."],
  ["A magnet is surrounded by a…", "magnetic field", ["wire", "battery"], "The field is the region where magnetic forces act."],
  ["Wrapping a wire into a coil and sending a current through it makes an…", "electromagnet", ["permanent magnet", "insulator"], "The current creates a magnetic field."],
  ["Which change makes an electromagnet stronger?", "adding more turns of wire", ["using a shorter battery life", "removing the iron core"], "More turns or more current give a stronger field."],
  ["A moving electric charge produces a…", "magnetic field", ["a sound wave", "a shadow"], "This link is called electromagnetism."],
  ["An electrical generator works by moving a coil of wire in a…", "magnetic field", ["pool of water", "heated oil"], "Motion in a magnetic field makes a current."],
  ["The kind of magnet that keeps its magnetism without a current is a…", "permanent magnet", ["electromagnet", "battery"], "An electromagnet needs a current."],
  ["A bar magnet has how many poles?", "2, a north and a south", ["1", "4"], "Opposite poles attract, like poles repel."],
  ["How can an electromagnet be switched off?", "turn off the current", ["cool the magnet in water", "paint the wire"], "No current, no magnetic field.", true],
  ["Which statement shows conservation of energy?", "A ball's lost kinetic energy shows up as heat and sound after it lands", ["A ball makes new energy when it bounces", "A ball has no energy at the top of a throw"], "The total energy stays the same.", true],
  ["In a hydroelectric station, water stored high behind a dam is released. What happens first?", "water falling and gaining kinetic energy", ["wires making heat", "a lamp lighting up"], "Potential changes to kinetic, then the turbine and generator.", true],
];

const METHOD: Q[] = [
  ["A hypothesis is…", "a testable prediction that explains something", ["a proven fact", "a conclusion"], "It is tested by an experiment."],
  ["Which is a testable hypothesis?", "If a plant gets more light, it will grow taller.", ["Plants are beautiful.", "Light is the best."], "A good hypothesis can be tested by measuring."],
  ["In an experiment, the variable that you change on purpose is the…", "independent variable", ["dependent variable", "control variable"], "It is the one you manipulate."],
  ["The variable that you measure is the…", "dependent variable", ["independent variable", "control variable"], "It depends on the change you made."],
  ["Variables kept the same in a fair test are the…", "controlled variables", ["responding variables", "hypotheses"], "Only one variable changes at a time."],
  ["In a test of how sunlight affects plants, the amount of water should be…", "the same for all plants", ["different for each plant", "zero"], "Control all other variables."],
  ["Peer review means…", "other scientists check the work before it is published", ["a friend copies it", "the author reviews it twice"], "It helps find errors and bias."],
  ["Bias in an experiment is…", "something that unfairly pushes results one way", ["a type of measurement", "a graph"], "Scientists try to reduce it."],
  ["Which practice reduces bias?", "repeating trials and using a large sample", ["testing only once", "choosing data that fit your guess"], "More data and fair methods reduce bias."],
  ["Collecting data carefully matters because…", "conclusions must be based on evidence", ["graphs must be colourful", "it shortens the lab"], "Reliable data support reliable conclusions."],
  ["A scientific theory is…", "a well-tested explanation supported by lots of evidence", ["a guess", "an opinion"], "It is the best fit for the evidence at the time."],
  ["Scientific explanations can change when…", "new evidence is found", ["people are bored", "a vote is taken"], "Science is open to revision."],
  ["A model is…", "a representation that helps explain a phenomenon", ["a fact that cannot change", "the same as the real thing"], "Models can be physical, mathematical or computer-based."],
  ["A computer simulation of climate is an example of…", "a model", ["a hypothesis", "a control"], "It represents a system to help understand it."],
  ["Which is a well-established scientific model?", "the Solar System model", ["the rainbow is a bridge", "a model with no evidence"], "It has been tested for centuries."],
  ["A model that is more tentative is one that…", "has less evidence and may change soon", ["has been proven forever", "is not based on data"], "Some models are still being tested.", true],
  ["If an experiment does not support your hypothesis, you should…", "report the results and revise your hypothesis", ["change the data", "hide the results"], "Honest reporting is part of science."],
  ["Which statement is a conclusion?", "The data show that plants in more light grew taller.", ["Plants need light.", "Measure the height with a ruler."], "A conclusion says what the evidence shows."],
  ["Which is an observation?", "The plant grew 4 cm in a week.", ["I think plants like music.", "The plant is happy."], "Observations are measured or sensed."],
  ["Which is an inference?", "The soil was dry, so the plant probably wilted from lack of water.", ["The plant is 10 cm tall.", "The pot is red."], "An inference is an explanation based on observations."],
  ["Why do scientists repeat trials?", "to check results are reliable", ["to make the experiment longer", "to hide mistakes"], "Results should be repeatable."],
  ["A line graph is the best choice to show…", "how a measurement changes over time", ["the parts of a whole", "the names of variables"], "Choose a graph to match the data."],
  ["Where should the independent variable go on a graph?", "on the horizontal axis", ["on the vertical axis", "outside the graph"], "The dependent variable goes on the vertical axis.", true],
  ["Which question can science answer?", "How does temperature affect how fast sugar dissolves?", ["Which flavour is best?", "Is it right to like winter?"], "Science answers questions that can be tested."],
  ["Sharing results in a report with methods allows other scientists to…", "repeat the work and check it", ["avoid reading it", "change the results"], "Clear methods make science trustworthy.", true],
];

const SOCIETY: Q[] = [
  ["Which factor should be considered when choosing a solution to an engineering problem?", "cost, materials and environmental effects", ["only how it looks", "only the name"], "Many factors affect the best solution."],
  ["A solution that is cheap but harms a river is…", "not likely the best solution overall", ["always the best", "perfect"], "Environmental effects matter."],
  ["Engineers often try several designs because…", "the first idea is rarely the best", ["they enjoy delays", "there is only one answer"], "Testing models helps to find a good solution."],
  ["Technology designed to help people can sometimes have…", "unforeseen consequences", ["no effect", "only good effects"], "Designers cannot predict everything."],
  ["Antibiotics improved health, but their overuse led to…", "antibiotic resistance", ["fewer germs forever", "weaker people"], "This is an example of a consequence of technology."],
  ["A new farming technology increases food supply but can also…", "reduce biodiversity", ["stop the sun", "freeze water"], "Monocultures can harm local species."],
  ["Plastic makes many goods cheaper but it can also…", "create pollution", ["clean the water", "make food"], "Waste plastic harms ecosystems."],
  ["When new information shows a technology harms the environment, a community may decide to…", "modify, redesign or replace it", ["ignore the evidence", "do nothing forever"], "Technologies are re-evaluated."],
  ["Taking class action on a local environmental issue is an example of…", "applying science to your community", ["avoiding the issue", "copying a lab report"], "Students can plan a clean-up or recycling project."],
  ["A medical lab technician uses science to…", "test samples and help diagnose illness", ["write novels", "drive a bus"], "Many careers use science."],
  ["Which of these jobs uses ideas about electricity?", "electrician", ["baker", "tour guide"], "Electricians install and repair circuits."],
  ["A farmer might use science to…", "choose crops, manage soil and control pests", ["design software only", "write laws"], "Agriculture uses biology and chemistry."],
  ["A paleontologist studies…", "fossils", ["stars", "computers"], "Fossils give evidence of life long ago."],
  ["A geneticist studies…", "genes and heredity", ["rocks", "weather"], "Genetics is about traits and inheritance."],
  ["An HVAC technician works with…", "heating, ventilation and air conditioning", ["bones", "plants"], "It involves energy and heat transfer."],
  ["Which hobby uses science ideas?", "baking, because heat and ingredients change", ["staring at a wall", "ignoring the recipe"], "Cooking uses chemistry."],
  ["Which is an advantage of electric vehicles?", "they produce no exhaust while driving", ["they need no electricity", "they need no batteries"], "Their overall impact also depends on how the electricity is made."],
  ["A disadvantage of some electric vehicle batteries is that…", "they need metals that must be mined", ["they use no energy", "they are made of air"], "Mining and recycling are challenges.", true],
  ["Wind farms produce electricity without burning fuel. A concern they can raise is…", "effects on birds, bats or local views", ["too much hydrogen", "no wind energy"], "Every technology has trade-offs.", true],
  ["Which question would help evaluate a new technology?", "Who benefits, and who might be harmed?", ["What colour is it?", "Is it new?"], "Consider ethical, social and economic effects."],
  ["Nuclear energy produces electricity with low greenhouse gas emissions, but it must also deal with…", "radioactive waste", ["too much wind", "no heat"], "Safe long-term storage is a challenge.", true],
  ["Changing a design after testing shows a flaw is…", "a normal part of problem solving", ["a mistake to hide", "cheating"], "Designs improve through testing."],
  ["Which of these is an ethical question about technology?", "Is it fair if only some communities get the benefits?", ["Is the box blue?", "How heavy is it?"], "Ethics asks what is right and fair.", true],
  ["Using a model of a bridge before building the real one helps to…", "test the design cheaply and safely", ["avoid all testing", "make it more expensive"], "Prototypes reveal problems early."],
  ["A cost-benefit analysis compares…", "the costs of a choice with its benefits", ["two colours", "two unrelated numbers"], "It helps decision-makers weigh a choice.", true],
];

const LAB: Q[] = [
  ["Which tool measures mass?", "a balance", ["a ruler", "a voltmeter"], "Mass is measured in grams or kilograms."],
  ["Which tool measures the volume of a liquid?", "a graduated cylinder", ["a balance", "an ammeter"], "Volume is measured in millilitres (mL)."],
  ["Which tool measures electric current?", "an ammeter", ["a voltmeter", "a caliper"], "Current is measured in amperes (amps)."],
  ["Which tool measures electric potential difference?", "a voltmeter", ["an ammeter", "a balance"], "Voltage is measured in volts."],
  ["Which unit measures electric current?", "ampere (A)", ["volt (V)", "joule (J)"], "The amp is the unit of current."],
  ["Which unit measures electric potential difference?", "volt (V)", ["ampere (A)", "gram (g)"], "Voltage is in volts."],
  ["Which unit is used for energy?", "joule (J)", ["litre (L)", "metre (m)"], "The joule is the SI unit of energy."],
  ["A caliper is best for measuring…", "the small width or diameter of an object", ["the temperature of a room", "the time of a reaction"], "It measures lengths very precisely."],
  ["To read the volume of liquid in a graduated cylinder, you should…", "read at eye level at the bottom of the meniscus", ["read from above", "read from the top of the liquid edge"], "A meniscus is the curve of the liquid surface."],
  ["An ammeter is connected…", "in series with the part of the circuit measured", ["in parallel across a component", "outside the circuit"], "Current must flow through the meter."],
  ["A voltmeter is connected…", "in parallel across the component", ["in series with the battery only", "in a separate circuit"], "It measures the difference across two points."],
  ["Which of these should you wear when heating chemicals?", "safety goggles", ["sunglasses", "a scarf"], "Eye protection is essential."],
  ["Before using a Bunsen burner, you should…", "tie back long hair and check the equipment", ["lean over it", "leave it on"], "Be careful with open flames."],
  ["If you spill a chemical in the lab, you should first…", "tell your teacher right away", ["wipe it with your sleeve", "ignore it"], "Report spills immediately."],
  ["Chemicals are labelled with hazard symbols from…", "WHMIS", ["a menu", "a map"], "WHMIS is a workplace hazard communication system used in schools."],
  ["Glassware that is cracked should be…", "reported and not used", ["used carefully", "hidden from the teacher"], "It can break and injure you."],
  ["You should never taste…", "anything in a science lab", ["a snack outside the lab", "water from a fountain"], "Chemicals and equipment are not food."],
  ["The correct way to smell a chemical, when your teacher allows it, is to…", "waft the vapour gently toward your nose", ["sniff deeply from the container", "hold it under your nose"], "Never inhale directly."],
  ["A digital scale reads 52.3 g. Which unit does it measure?", "mass", ["volume", "temperature"], "The gram is a unit of mass."],
  ["How many millilitres are in 1 litre?", "1000", ["100", "10"], "Milli means one thousandth."],
  ["How many grams are in 2.5 kg?", "2500 g", ["250 g", "25 g"], "Multiply by 1000."],
  ["How many millimetres are in 4.2 cm?", "42 mm", ["0.42 mm", "420 mm"], "Multiply by 10."],
  ["Hot glassware should be handled with…", "tongs or heat-resistant gloves", ["bare hands", "wet paper"], "Hot glass looks like cold glass."],
  ["A multimeter can be set to measure…", "voltage and current", ["only mass", "only volume"], "It combines the functions of a voltmeter and an ammeter.", true],
  ["For electrical experiments in class, you should use…", "low-voltage direct current from batteries", ["wall outlets", "power lines"], "Low-voltage DC is much safer.", true],
];

const KNOWING: Q[] = [
  ["Traditional Knowledge in many First Nations, Métis and Inuit communities is…", "knowledge built through close observation of the land over many generations", ["only found in textbooks", "only about the past"], "It is living knowledge that is shared and used today."],
  ["Many First Nations, Métis and Inuit communities teach that people are…", "in respectful relationship with the land, water and living things", ["separate from nature", "owners of all species"], "Reciprocity and respect are important values in many communities."],
  ["Who often shares Traditional Knowledge in a community?", "Elders and Knowledge Keepers", ["only tourists", "only machines"], "They teach through stories, land and practice."],
  ["Observing the weather, the animals and the plants through the seasons is part of…", "learning from the land", ["guessing", "a video game"], "Careful observation is part of many knowledge systems."],
  ["Indigenous peoples developed technologies that fit their local environments, such as…", "the Inuit qamutik (sled) and kayak", ["the telephone", "the typewriter"], "These are designs made for ice and water."],
  ["The Red River cart, used by Métis in the 1800s, was built mostly from…", "wood and leather", ["steel and rubber", "plastic"], "It was designed for the Prairies and could cross rivers."],
  ["Manoomin (wild rice) is harvested by some Anishinaabe communities…", "from lakes and rivers, with respect for the plants and the water", ["from rooftops", "in factories only"], "It is a food that is part of the culture in northern Manitoba and Ontario."],
  ["“Two-Eyed Seeing” is a way of…", "using strengths of both Indigenous and Western ways of knowing", ["using only one eye", "avoiding science"], "The idea was shared by Mi'kmaw Elder Albert Marshall."],
  ["Many Indigenous communities today use science and technology, such as…", "solar and wind power projects", ["no technology", "only tools from the past"], "Knowledge and technology both continue to grow."],
  ["Land-based learning means…", "learning outdoors and from the land and its people", ["only learning in a laboratory", "only learning on a screen"], "It is used in many schools and communities."],
  ["Which statement is respectful?", "First Nations, Métis and Inuit peoples are diverse, with many different languages and cultures", ["All Indigenous peoples are the same", "Indigenous cultures belong only in the past"], "Use words like “many” and “some.”"],
  ["Science curiosity grows when you…", "ask questions about the world around you", ["stop asking", "avoid nature"], "Curiosity is a key science attitude."],
  ["A sense of belonging in science means…", "everyone can contribute to science", ["only a few people can do science", "science is only for experts"], "People from many backgrounds contribute."],
  ["Making a personal connection to nature can include…", "noticing the plants and animals near your home", ["ignoring weather", "staying indoors always"], "Observation builds understanding."],
  ["Which of these is a science skill?", "measuring and recording observations", ["guessing", "skipping notes"], "Skills grow with practice."],
  ["A scientific attitude includes…", "being curious, open-minded and honest", ["thinking you know it all", "hiding data"], "Attitudes guide how we do science."],
  ["Building on science experiences from your own life helps you to…", "link ideas to what you already know", ["avoid new ideas", "stop learning"], "Personal experience supports concepts."],
  ["Who can contribute to science?", "anyone with curiosity and care", ["only adults", "only people in labs"], "Citizen scientists contribute data, too."],
  ["Community science projects, such as counting birds or tracking lake ice, show that…", "people of many ages can help collect data", ["only experts can look at birds", "data must be secret"], "Observations by many people add up."],
  ["“Reciprocal” relationships means…", "giving back as well as taking", ["only taking", "avoiding others"], "Reciprocity is a value in many ways of knowing.", true],
  ["Wholistic ways of knowing look at…", "how everything is connected", ["only one small part", "only numbers"], "Many knowledge systems see connections among living things and places.", true],
  ["Traditional ecological knowledge can help scientists by…", "adding long-term observations of a place", ["replacing every study", "ending research"], "Knowledge from long experience of a place adds to understanding.", true],
  ["Learning about the land from the people who live on it shows…", "respect for local knowledge", ["that science has no use", "that books are banned"], "Listening is part of learning."],
  ["Which of these is part of sustainable living?", "using only what you need and caring for resources", ["wasting water", "dumping waste in rivers"], "Sustainable means able to continue for the future."],
  ["Science can include learning through stories because stories can…", "record careful observations and share them across generations", ["replace measurements", "make facts disappear"], "Oral traditions carry knowledge in many cultures.", true],
];

export const units = [
  bankUnit({
    id: "mb-infectious-disease",
    title: "Infectious Disease",
    emoji: "🦠",
    blurb: "Germs, vaccines, antibiotics and how diseases change.",
    parentNote: "Practises pathogens, vaccines, antibiotics and antibiotic resistance, mutations and strains, waning immunity, and public health measures that limit the spread of disease.",
    standards: ["SCI.9.E.22", "adaptation in infectious diseases and related public health measures"],
    items: DISEASE,
  }),
  bankUnit({
    id: "mb-human-reproductive-system",
    title: "Human Reproductive System",
    emoji: "🧬",
    blurb: "Structures, functions and hormones, explained simply.",
    parentNote: "Practises the structure and function of the human reproductive system and the role of hormones, in plain scientific terms. Families may wish to read it together.",
    standards: ["SCI.9.E.17", "structure, function and hormonal regulation of the human reproductive system"],
    items: BODY,
  }),
  bankUnit({
    id: "mb-energy-and-magnetism",
    title: "Energy & Magnetism",
    emoji: "🧲",
    blurb: "Conservation of energy, efficiency and electromagnets.",
    parentNote: "Practises the law of conservation of energy, potential and kinetic energy, efficiency, and the link between electric current and magnetic fields in electromagnets and generators.",
    standards: ["SCI.9.E.9, SCI.9.E.11", "conservation of energy, efficiency and electromagnetism"],
    items: ENERGY,
  }),
  bankUnit({
    id: "mb-how-science-works",
    title: "How Science Works",
    emoji: "🔬",
    blurb: "Hypotheses, variables, bias, peer review and models.",
    parentNote: "Practises how scientists test predictions: hypotheses, variables, fair tests, bias, peer review, and how models and theories change with evidence.",
    standards: ["SCI.9.D.1, SCI.9.D.2, SCI.9.D.3, SCI.9.D.4, SCI.9.C.3", "systematic data collection, hypotheses, experiments, bias, peer review and models"],
    items: METHOD,
  }),
  bankUnit({
    id: "mb-science-and-society",
    title: "Science & Society",
    emoji: "🌎",
    blurb: "Trade-offs, unexpected effects and science careers.",
    parentNote: "Practises weighing the costs and benefits of technologies, spotting unforeseen consequences, taking action on science issues, and linking science to careers and hobbies.",
    standards: ["SCI.9.D.5, SCI.9.D.6, SCI.9.D.7, SCI.9.D.8, SCI.9.C.1, SCI.9.C.5", "solving problems, implications of technology, taking action and science careers"],
    items: SOCIETY,
  }),
  bankUnit({
    id: "mb-measure-and-lab-safety",
    title: "Measuring & Lab Safety",
    emoji: "🥽",
    blurb: "Choose tools and units, and work safely.",
    parentNote: "Practises choosing measuring tools and units (balance, graduated cylinder, voltmeter, ammeter, caliper), reading them correctly and following lab safety rules.",
    standards: ["SCI.9.C.2, SCI.9.C.4", "measuring with appropriate tools and units, and using equipment safely"],
    items: LAB,
  }),
  bankUnit({
    id: "mb-ways-of-knowing",
    title: "Ways of Knowing",
    emoji: "🌿",
    blurb: "Science, curiosity and Indigenous ways of knowing today.",
    parentNote: "Practises ideas about scientific attitudes and belonging in science, and introduces how many First Nations, Métis and Inuit communities observe and care for the land today. This content is light and still needs review with Indigenous partners.",
    standards: ["SCI.9.A.1, SCI.9.B.1", "Indigenous ways of knowing, being and doing, and a sense of belonging in science"],
    items: KNOWING,
  }),
];
