import { bankUnit, type Q } from "../own";

// Grade 9 social studies, Canada in the Contemporary World: items for the second set of units
// (francophone communities, First Nations, Métis and Inuit today, injustices and change, people and population).
// First Nations, Métis and Inuit content is light, in the present tense, and needs review with partners.

const FRANCOPHONE: Q[] = [
  ["Article 23 of the Canadian Charter of Rights and Freedoms protects…", "minority-language education rights", ["the right to vote", "freedom of the press"], "It covers French and English minority communities in each province."],
  ["Which two languages did the Manitoba Act of 1870 recognize in the legislature and courts?", "English and French", ["English and Cree", "French and Michif"], "It guaranteed both English and French."],
  ["In 1890 Manitoba passed a law that…", "made English the only official language", ["made French the only language", "created a bilingual school law"], "The law was later ruled unconstitutional."],
  ["The Supreme Court ruling in 1979 (the Forest case) said that Manitoba's 1890 language law was…", "unconstitutional", ["fair", "a federal law"], "The Court said Manitoba had to respect the Manitoba Act's language rights."],
  ["Francophone students in Manitoba can attend French-language schools run by the…", "Division scolaire franco-manitobaine (DSFM)", ["Winnipeg Blue Bombers", "Manitoba Hydro"], "The DSFM was created in 1994."],
  ["Which Winnipeg neighbourhood is the heart of Manitoba's francophone community?", "Saint-Boniface", ["Transcona", "The Forks"], "It is home to the Franco-Manitoban Cultural Centre."],
  ["Which winter festival in Saint-Boniface celebrates Franco-Manitoban and Métis history?", "the Festival du Voyageur", ["Folklorama", "the Stampede"], "It is held each February."],
  ["La Liberté is a…", "French-language newspaper in Manitoba", ["hockey team", "type of bread"], "It has served French readers since 1913."],
  ["A linguistic minority is a group that…", "speaks the official language that fewer people in a region speak", ["has no language", "speaks only a foreign language"], "In Manitoba, francophones are a linguistic minority."],
  ["Laws and programs that limit a language in schools can lead to…", "language loss, called assimilation", ["more speakers", "equal rights"], "Assimilation is when a group gradually loses its own language and culture."],
  ["Which choice helps a minority language stay strong?", "French-language schools, media and cultural events", ["removing all signs", "banning books"], "Daily use keeps a language alive."],
  ["Canada's Official Languages Act (1969) made English and French the official languages of…", "the federal government", ["only Quebec", "only Manitoba"], "It applies to federal institutions."],
  ["Mass media such as TV, music and streaming in English can affect a francophone teen's identity by…", "making French harder to see and hear unless the teen seeks it out", ["removing the need for French", "teaching French automatically"], "Media can strengthen or weaken a culture."],
  ["Which is a French-language public broadcaster in Canada?", "Radio-Canada", ["CBC Sports", "APTN"], "ICI Radio-Canada broadcasts in French."],
  ["A teen who streams music in French, reads French books and joins a francophone club is…", "supporting the vitality of French", ["making French disappear", "dividing Canada"], "Using a language builds its future."],
  ["The Charter's Article 23 applies where…", "numbers of children warrant a minority-language school", ["only in Ottawa", "only in cities with 100 000 people"], "It depends on the number of eligible students.", true],
  ["Why is it important for the courts to enforce language rights?", "rights on paper only matter if they can be used", ["laws are optional", "only governments have rights"], "Courts protect rights from being ignored.", true],
  ["Francophones in Manitoba trace their roots to…", "French-Canadian, Métis, and more recent immigrants from many countries", ["only one village in France", "no one before 1900"], "The community is diverse.", true],
  ["Which statement shows respect for Canada's cultural pluralism?", "Canada includes many cultures and languages, and each adds to the country", ["only one culture is correct", "cultures should hide"], "Pluralism means many groups living together with respect."],
  ["Bilingual road signs and service in French at some Manitoba offices are examples of…", "language rights in action", ["ads", "tourism taxes"], "They are provided under language laws and policies."],
  ["Which is a right of francophone citizens of Canada?", "to use French in federal courts and receive federal services in French", ["to avoid English in all places", "to ignore the Charter"], "The Charter and the Official Languages Act protect this."],
  ["A responsibility of citizens who care about minority languages is to…", "support their use in schools, communities and daily life", ["wait for others to act", "criticize speakers"], "Rights and responsibilities go together."],
  ["Which of these is part of francophone culture in Manitoba?", "festivals, music and food such as tourtière", ["only winter sports", "only traditions from one country"], "The culture is living and changing."],
  ["In 1985 the Supreme Court ruled that Manitoba had to…", "translate its laws into French and respect language rights", ["stop using French", "ignore the 1870 Act"], "The ruling gave time for translation.", true],
  ["A language is more likely to survive if it is…", "used at home, at school and in the community", ["spoken only at festivals", "used only in textbooks"], "Daily use matters most."],
];

const FNMI_TODAY: Q[] = [
  ["Residential schools were government-funded, church-run schools that…", "removed First Nations, Métis and Inuit children from their families", ["were chosen by families", "taught only in Indigenous languages"], "They harmed children, families and communities."],
  ["When did the last federally run residential school close?", "1996", ["1896", "1946"], "The effects continue today."],
  ["Which group of survivors' stories and records is kept at the National Centre for Truth and Reconciliation in Winnipeg?", "residential school survivors", ["fur traders", "railway workers"], "The centre is at the University of Manitoba."],
  ["The Truth and Reconciliation Commission of Canada issued…", "94 Calls to Action", ["10 rules", "a new treaty"], "They suggest ways governments and people can work towards reconciliation."],
  ["Canada marks the National Day for Truth and Reconciliation on…", "September 30", ["July 1", "November 11"], "It honours survivors and remembers children who did not come home."],
  ["A common effect of residential schools on communities was the loss of…", "language and cultural teaching passed between generations", ["roads", "all rivers"], "Many communities are renewing their languages today."],
  ["Many communities today are working to…", "revitalize their languages and cultures", ["end their languages", "close all schools"], "Language camps and immersion programs are examples."],
  ["The Indian Act of 1876 is a federal law that…", "controls many parts of life for First Nations people with status", ["gives everyone the vote", "applies to every Canadian equally"], "It has been changed many times and is still debated."],
  ["APTN is…", "a national television network that tells Indigenous stories", ["a hockey league", "a bank"], "The Aboriginal Peoples Television Network is based in Winnipeg."],
  ["Which kind of media is led by First Nations, Métis and Inuit people today?", "radio, film, music and news by and for Indigenous communities", ["no media", "only old newspapers"], "Indigenous creators share their own stories."],
  ["When media show only stereotypes of Indigenous peoples, this can…", "harm how people see themselves and others", ["help understanding", "change nothing"], "Accurate and varied portrayals matter."],
  ["Pop culture can support identity when artists…", "share their own cultures in their own voices", ["copy someone else's stories", "use a culture as a costume"], "Indigenous artists reach audiences through music and film."],
  ["The Métis are a distinct Indigenous people whose homeland includes…", "the Red River region of Manitoba", ["Iceland", "the Arctic only"], "Michif is a Métis language."],
  ["The Manitoba Métis Federation represents…", "Métis citizens in Manitoba", ["all Canadians", "only city governments"], "It is the government of the Manitoba Métis community."],
  ["Inuit homelands in Canada, called Inuit Nunangat, include…", "Nunavut, Nunavik, Nunatsiavut and the Inuvialuit Settlement Region", ["only Manitoba", "southern Ontario"], "Inuit also live in cities such as Winnipeg."],
  ["Responsibilities of First Nations, Métis and Inuit citizens include…", "taking part in their Nation or community as well as in Canada", ["leaving Canada", "giving up their rights"], "Many people belong to a community and to Canada."],
  ["Which statement is respectful and accurate?", "First Nations, Métis and Inuit peoples are diverse, with many languages and Nations", ["All Indigenous peoples have one culture", "Indigenous cultures exist only in the past"], "Use words like “many” and “some.”"],
  ["Respecting the relationship Indigenous peoples have with the land includes…", "listening to their voices on how the land is used and cared for", ["ignoring treaties", "removing access to the land"], "Many communities see the land as a relative and teacher."],
  ["Reconciliation means…", "building respectful relationships and acting on past wrongs", ["forgetting the past", "ending treaties"], "It takes the work of governments and people."],
  ["A person can support the vitality of Indigenous languages by…", "learning from language programs, listening and using words respectfully", ["teasing speakers", "avoiding the topic"], "Allies support community-led efforts."],
  ["The apology to residential school survivors was made by the Prime Minister in…", "2008", ["1908", "1968"], "The federal government apologized in the House of Commons."],
  ["Bill C-31 (1985) changed the Indian Act so that…", "women who had lost status by marrying a man without status could regain it", ["all status ended", "treaties were cancelled"], "It ended a discriminatory rule.", true],
  ["Indigenous Languages Act (2019) supports…", "the reclaiming and strengthening of Indigenous languages", ["banning languages", "English-only schools"], "It is a federal law.", true],
  ["Which action shows an understanding of residential school history?", "listening to survivors and learning from reliable sources", ["making jokes", "avoiding the topic"], "Learning with care is respectful.", true],
  ["Truth must come before reconciliation because…", "people need to understand what happened to move forward together", ["history should be ignored", "reconciliation is optional"], "Facts build understanding.", true],
];

const INJUSTICES: Q[] = [
  ["From 1885 to 1923, Chinese immigrants to Canada had to pay…", "a head tax", ["a school fee", "a ticket tax"], "The tax was meant to keep Chinese people from settling in Canada."],
  ["The federal government apologized for the Chinese head tax in…", "2006", ["1906", "1966"], "An apology acknowledges a past wrong."],
  ["During the Second World War, the government forced Japanese Canadians living on the West Coast to…", "leave their homes and live in internment camps", ["serve as police", "move to Europe"], "Many lost homes and property. Canada apologized in 1988."],
  ["In 1914 the ship Komagata Maru was turned away from Vancouver. Most passengers were…", "from India, mainly Sikh", ["from Iceland", "Canadian-born"], "Laws at the time excluded many immigrants because of race."],
  ["During the First World War, thousands of Ukrainian Canadians and other Europeans were…", "interned as “enemy aliens”", ["given free land", "elected to office"], "Many were held in camps and forced to work."],
  ["In 1939 the ship MS St. Louis carried Jewish refugees who were refused by Canada. This shows…", "how discrimination affected immigration policy", ["good border control", "a rule for steamships"], "Canada's policies were shaped by prejudice."],
  ["Discrimination is…", "treating people unfairly because of who they are", ["treating people the same", "a kind of law"], "It can be based on race, religion, gender, language or other things."],
  ["Prejudice means…", "forming a negative opinion about people without knowing them", ["a respected opinion", "a legal process"], "It often leads to discrimination."],
  ["A stereotype is…", "an oversimplified idea about a group", ["a fact about each person", "a historic law"], "It ignores the differences among people."],
  ["Systemic racism is when…", "policies, laws or practices disadvantage a group, even without individual hate", ["only one person is unkind", "everyone has the same experiences"], "It is built into systems."],
  ["Antisemitism is…", "prejudice or hatred against Jewish people", ["a type of law", "a school subject"], "It is a form of discrimination."],
  ["Which action can help respond to racism?", "speaking up safely and supporting those who are targeted", ["joining the teasing", "pretending not to see"], "Allies make a difference."],
  ["Which is a way to address social injustice in Canada?", "changing unfair laws and policies, and educating people", ["ignoring it", "blaming the victims"], "Governments, groups and individuals each have a role."],
  ["The Winnipeg General Strike of 1919 was about workers seeking…", "better wages, working conditions and the right to bargain together", ["a new flag", "more holidays for kings"], "About 30 000 workers went on strike."],
  ["When people make decisions by majority rule, minorities may be…", "left out unless their rights are protected", ["always treated better", "never affected"], "Rights protect minorities."],
  ["Which action shows being sensitive to minorities?", "listening to their concerns before a vote", ["ignoring them", "silencing them"], "Considering everyone makes better decisions."],
  ["Nellie McClung and others worked for women's rights in Manitoba. This is an example of…", "Canadians who helped to promote human rights", ["opponents of democracy", "foreign rulers"], "Many people and groups have worked for rights."],
  ["Which of these is an example of a Canadian who promoted human rights?", "Viola Desmond, who challenged segregation in a Nova Scotia theatre", ["a historical king", "a fictional character"], "Her stand in 1946 is remembered today."],
  ["Terry Fox, born in Winnipeg, raised money for cancer research. He is remembered for…", "his courage and the Marathon of Hope", ["winning an election", "writing a treaty"], "He ran across Canada in 1980 on one leg."],
  ["Knowing the past helps us to…", "understand the present and prepare for the future", ["avoid change", "repeat the same mistakes"], "History explains where issues come from."],
  ["Being willing to consider diverse perspectives means…", "listening to different viewpoints with an open mind", ["agreeing with everyone", "refusing new ideas"], "You can still disagree after you listen."],
  ["Canadian cultural pluralism means that…", "many cultures live together and are valued", ["only one culture counts", "cultures are kept apart"], "Pluralism is part of Canadian identity."],
  ["Which source would best show the experience of someone who faced discrimination?", "a first-hand interview or diary", ["a guess", "a rumour"], "Primary sources give personal views.", true],
  ["Removing injustices requires…", "action by governments, communities and individuals", ["only one group", "waiting without acting"], "Change takes many hands.", true],
  ["Why do apologies matter?", "they acknowledge harm, but action must follow", ["they replace all action", "they erase history"], "An apology is one step.", true],
];

const POPULATION: Q[] = [
  ["Since 1900, much of Canada's population growth has come from…", "immigration", ["no births", "moving to the Arctic"], "Immigration is the main source of growth today."],
  ["A country's birth rate that is below the replacement level of about 2.1 children per woman means…", "population would shrink without immigration", ["rapid growth", "no aging"], "Canada's birth rate is below that level."],
  ["Life expectancy in Canada has…", "increased over the last century", ["stayed the same", "dropped to 50"], "Medicine, nutrition and public health have helped."],
  ["Urbanization is the…", "movement of people from rural areas to cities", ["building of farms", "growth of forests"], "More than 80% of Canadians live in urban areas."],
  ["The baby boom in Canada happened…", "after the Second World War, 1946 to 1965", ["around 1800", "in the 1990s"], "A large generation was born."],
  ["As the baby boomers get older, Canada's population is…", "aging", ["getting younger", "staying the same"], "More seniors need services such as health care."],
  ["A population pyramid shows…", "the number of people at each age", ["road maps", "weather"], "A wide top means many older people."],
  ["Which factor can lead to the movement of people to Manitoba?", "jobs, family, education and safety", ["no reason", "random chance only"], "Push and pull factors affect migration."],
  ["Winnipeg is home to a large community with roots in…", "the Philippines, among many other countries", ["only one European country", "no other countries"], "Winnipeg's population is very diverse."],
  ["Canada's population is expected to grow mostly through…", "immigration", ["new provinces", "sports"], "Immigration helps meet labour needs."],
  ["Manitoba was the first province to give some women the vote in", "1916", ["1816", "1966"], "Women in Manitoba could vote and run for office."],
  ["Most women could vote in federal elections starting in…", "1918", ["1818", "1988"], "Many Indigenous women and others were still excluded."],
  ["First Nations people with status could vote federally without giving up their status starting in…", "1960", ["1860", "1930"], "Earlier, they had to give up status to vote."],
  ["The Persons Case of 1929 decided that women are…", "“persons” who can be appointed to the Senate", ["not allowed to vote", "only for provinces"], "The “Famous Five” helped win the case."],
  ["Agnes Macphail was the first woman elected to Canada's…", "House of Commons", ["Senate", "Supreme Court"], "She was elected in 1921."],
  ["Bill C-31 (1985) mattered to First Nations women because it…", "restored status that many had lost", ["ended the Indian Act", "banned elections"], "Before 1985, women lost status by marrying a man without status."],
  ["Changes since the 1900s that have improved life for many women include…", "voting rights, access to higher education and equal-pay laws", ["less schooling", "no jobs"], "Work on equality continues."],
  ["Medicare, introduced across Canada by the 1960s, is an example of a…", "social program", ["sports team", "tax haven"], "It provides health care coverage."],
  ["Which technology changed communication in Canada the most in the past 30 years?", "the internet", ["the printing press", "the telegraph"], "It connects people instantly."],
  ["Public education changed Canadian society by…", "raising literacy and opening more job opportunities", ["limiting jobs", "ending libraries"], "Schooling is a major quality-of-life factor."],
  ["Predicting future trends in demographics means…", "using data about births, deaths and migration to estimate changes", ["guessing without data", "ignoring population"], "Trends help governments plan.", true],
  ["If a region's average age rises over many years, planners may need to build more…", "seniors' care and health services", ["playgrounds only", "ski hills"], "Services must match who lives there.", true],
  ["Which statement shows that diverse groups add to Canada?", "Newcomers and long-time residents share skills, food, art and ideas", ["Only one group adds to society", "Groups should stay apart"], "Contributions come from everyone."],
  ["Which of these is a demographic characteristic?", "age, income and place of birth", ["the colour of a sweater", "the weather today"], "Demographics describe a population."],
  ["A technology that changed farming in Manitoba is…", "the tractor and modern machinery", ["the spinning wheel", "the sundial"], "Machines changed how many farmers are needed.", true],
];

export const units = [
  bankUnit({
    id: "mb-francophone-communities",
    title: "Francophone Communities",
    emoji: "⚜️",
    blurb: "Language rights, Article 23 and francophone life in Manitoba.",
    parentNote: "Practises Article 23 of the Charter, the history of French language rights in Manitoba, the effects of language and education laws, and how media and community support francophone identity.",
    standards: ["9-KC-002F, 9-KC-013F, 9-KI-018F, 9-KI-020F, 9-VI-005, 9-VI-005F", "minority-language rights, francophone identity, media and cultural pluralism"],
    items: FRANCOPHONE,
  }),
  bankUnit({
    id: "mb-first-nations-metis-inuit-today",
    title: "First Nations, Métis & Inuit Today",
    emoji: "🪶",
    blurb: "Residential schools, media, rights and renewal in communities today.",
    parentNote: "Practises the effects of residential schools, the influence of media and pop culture on Indigenous identities, rights and responsibilities, and language renewal. This content is light and still needs review with First Nations, Métis and Inuit partners.",
    standards: ["9-KC-013A, 9-KI-018A, 9-KI-020A, 9-VI-005A, 9-VL-006", "residential school effects, media influence, rights and responsibilities, and respect for relationships with the land"],
    items: FNMI_TODAY,
  }),
  bankUnit({
    id: "mb-injustices-and-change",
    title: "Injustices & Change",
    emoji: "⚖️",
    blurb: "Past injustices, discrimination and the people who worked for rights.",
    parentNote: "Practises injustices in Canada's past, prejudice, stereotypes and systemic racism, ways to respond, and Canadians who have promoted human rights.",
    standards: ["9-KH-030, 9-KI-022, 9-KI-023, 9-VI-004, 9-VH-008, 9-VH-010, 9-VP-016, 9-S-105", "injustices and discrimination in Canada's past, responding to racism and recognizing those who promoted human rights"],
    items: INJUSTICES,
  }),
  bankUnit({
    id: "mb-people-and-population",
    title: "People & Population",
    emoji: "👥",
    blurb: "Demographics, women's rights and changes in quality of life.",
    parentNote: "Practises factors that shape Canada's population (immigration, birth rate, life expectancy, urbanization), changes in the status of women, and social and technological changes that affect quality of life.",
    standards: ["9-KH-029, 9-KH-032, 9-KH-033, 9-KL-026, 9-VH-009", "demographic patterns, the status of women, quality of life and the contributions of diverse groups"],
    items: POPULATION,
  }),
];
