import { bankUnit, type Q } from "../own";

// More Grade 9 English language arts units written for Manitoba outcomes that the shared units do not cover:
// reading with a purpose (ELA.9.B1, B2.2, B2.4, B4.1), summarizing (B2.5), planning and research (C1.1 to C1.4),
// choosing a form and composing (C1.5 to C1.7, C2.1, C3.4), feedback and goals (D2) and specialized vocabulary (A2).
// Passages are original. Speaking and listening outcomes are not practised here.

const PURPOSE: Q[] = [
  ["Before reading an article on volcanoes, you recall a news story about an eruption. You are using your…", "prior knowledge", ["final draft", "table of contents"], "What you already know helps you understand new texts."],
  ["Which is a clear purpose for reading?", "to find three causes of the Dust Bowl for a report", ["because it was on the shelf", "to finish quickly"], "A purpose names what you want from the text."],
  ["You read a recipe before cooking. Your purpose is most likely to…", "follow steps", ["enjoy a poem", "compare two stories"], "Purpose and text type go together."],
  ["Which question would help you focus your reading of an article about wolves in Riding Mountain National Park?", "How do wolves affect the park's ecosystem?", ["Is the font nice?", "How many pages are there?"], "A focused question guides what you look for."],
  ["Which is a good way to choose a text for a project on climate change?", "check that it is recent, reliable and related to your question", ["pick the shortest one", "choose the one with the most pictures"], "Matching the text to your purpose saves time."],
  ["A connection between a story's character and your own experience is a…", "text-to-self connection", ["text-to-world connection", "text-to-text connection"], "Text to self links a text to your life."],
  ["Comparing a novel's theme with a news report about the same issue is a…", "text-to-text connection", ["text-to-self connection", "text-to-sound connection"], "Two texts are connected."],
  ["You link a story about a flood to what you know about the 1997 Red River flood. That is a…", "text-to-world connection", ["text-to-self connection", "text-to-title connection"], "It connects the text to events in the world."],
  ["Making a connection to a text helps you…", "build meaning and interpret what you read", ["skip hard words", "avoid questions"], "Connections deepen understanding."],
  ["After reading, you realize you changed your mind about a topic. This is an example of…", "gaining a new understanding from a text", ["ignoring the author", "retelling the plot"], "Reflecting on new learning is part of responding."],
  ["Which sentence best reflects on new learning?", "I used to think that all insects were pests, but now I know many help crops grow.", ["The article had six paragraphs.", "I read it on Tuesday."], "Reflection says how your thinking changed."],
  ["You finish a chapter and cannot explain what happened. A good strategy is to…", "reread and ask questions about the confusing parts", ["move to the next chapter", "stop reading"], "Monitoring means noticing when meaning is lost."],
  ["Reading with fluency means reading with…", "appropriate pace, accuracy and expression", ["the loudest voice", "the fastest speed possible"], "Fluency supports comprehension."],
  ["When you read a suspenseful scene aloud, you should…", "slow down and use expression to match the mood", ["read as fast as you can", "read in a flat tone"], "Expression (prosody) shows meaning."],
  ["A question that helps you refine your purpose while reading is…", "What do I still need to know?", ["How long is this?", "Who printed this?"], "Refining a question focuses your next steps.", true],
  ["Your knowledge about soccer helps you read a sports article. This shows that…", "prior knowledge supports understanding", ["background never matters", "only experts can read it"], "Prior knowledge fills gaps in a text."],
  ["Which reading purpose fits a science textbook chapter before a test?", "to learn and remember key ideas", ["to relax with a story", "to find a funny quote"], "A study purpose affects how you read."],
  ["Which reading speed fits a dense article with new terms?", "slower and with pauses to check meaning", ["as fast as possible", "only reading headings"], "Pacing should fit the text's demands."],
  ["Two readers give different interpretations of a poem. This can happen because…", "their experiences and knowledge differ", ["only one has read the poem", "poems have no meaning"], "Readers bring different background to a text.", true],
  ["Which is the best evidence-based interpretation?", "The speaker feels lonely, as shown by “empty chairs lined the hall.”", ["The poem is about chairs.", "I just don't like it."], "Support an interpretation with words from the text.", true],
  ["Before reading, a preview of headings, images and captions helps you to…", "predict what the text is about", ["skip the text", "find the author's age"], "Previewing builds a plan for reading."],
  ["A learner writes questions in the margin while reading. This is a way to…", "stay active and track understanding", ["avoid thinking", "make the text longer"], "Questions keep your mind on the meaning."],
  ["A KWL chart lists what you Know, what you Want to know and what you…", "Learned", ["Lost", "Listed"], "It tracks learning before, during and after reading."],
  ["If a text is too hard and you have a purpose, you can…", "look for a text on the same topic at an easier level first", ["give up on the topic", "copy the hard text"], "Build background, then return to harder texts.", true],
  ["Which is a text-to-self connection?", "This character moves to a new school, just as I did.", ["This book is the same length as another.", "The author lives in Canada."], "The link is to the reader's own life."],
];

const SUMMARY: Q[] = [
  ["A good summary of a text includes…", "the main ideas in your own words", ["every detail", "your opinion of the author"], "A summary is short and keeps the author's message."],
  ["Which of these is the most important in a summary?", "main ideas", ["minor examples", "the page numbers"], "Group related ideas and keep the important ones."],
  ["A summary should be…", "shorter than the original", ["longer than the original", "exactly as long"], "It condenses the text."],
  ["Which sentence is the best summary of this passage? “Honeybees dance to tell the hive where flowers are. A longer wiggle means a farther flower. The angle shows the direction.”", "Honeybees use dance to share the location of food.", ["Honeybees are insects.", "Flowers grow in many places."], "It captures the key idea."],
  ["When you summarize, you should keep the author's…", "message", ["spelling mistakes", "font"], "Do not change what the author means."],
  ["Which belongs in a summary of a news story about a flood?", "what happened, where, and the main effects", ["the reporter's lunch", "every quote word for word"], "Choose important information."],
  ["Which is a less important detail to leave out of a summary?", "the colour of a minor character's coat", ["the main conflict", "the solution"], "Leave out minor details."],
  ["Copying sentences straight from a text and calling it a summary is…", "plagiarism", ["paraphrasing", "inferring"], "Use your own words."],
  ["Putting an idea in your own words while keeping its meaning is…", "paraphrasing", ["quoting", "summarizing a title"], "Paraphrase and summarize both use your own words."],
  ["What is the best first step before summarizing a long article?", "identify the main idea of each section", ["count the words", "read only the last line"], "Group related ideas first."],
  ["A good summary of a story names…", "the characters, setting, main problem and outcome", ["only the first scene", "every line of dialogue"], "These parts show the story's shape."],
  ["Which signal word would start a summary of an article?", "The article explains that…", ["Once upon a time…", "In my opinion…"], "Summaries restate what the author says."],
  ["A summary of an opinion piece should…", "report the author's position fairly, without adding your own", ["argue against it", "skip the main claim"], "Keep your own opinion for your response."],
  ["Which would be a poor summary of a three-paragraph article about recycling?", "Recycling is good.", ["Recycling reduces waste, saves energy and starts with sorting at home.", "The article says recycling reduces waste and saves energy."], "A good summary is specific enough to show the key ideas.", true],
  ["Summaries can be used to…", "clarify meaning and support interpretation", ["replace the original text in a research essay", "avoid reading"], "Writing a summary shows what you understood."],
  ["Which strategy helps find important information?", "highlight topic sentences and key terms", ["highlight every line", "highlight only the title"], "Topic sentences give each paragraph's main idea."],
  ["After reading two paragraphs about the Red River Cart, you write: “The cart was built from wood and carried goods across the Prairies.” This is a…", "summary", ["question", "prediction"], "It states key ideas in a short form."],
  ["A graphic organizer for a summary can be used to…", "group ideas under headings", ["add extra detail", "replace the text"], "Grouping shows how ideas are related."],
  ["A text says the same idea three times with different examples. In a summary you should…", "state the idea once, with one example at most", ["list all the examples", "leave the idea out"], "Condense repeated information.", true],
  ["A summary of a science article should keep which kind of information?", "the key findings and why they matter", ["the title font", "all the numbers in the tables"], "Highlight the findings."],
  ["Which pair of words signals an important idea in a text?", "in conclusion", ["by the way", "meanwhile"], "Conclusion words often introduce the big idea.", true],
  ["Which is an effective way to check your summary?", "see if someone who has not read the text understands the main points", ["count adjectives", "make it twice as long"], "A good summary stands on its own."],
  ["A reader's summary changes the author's message. What should the reader do?", "reread and revise the summary to match the text", ["keep it as is", "delete the text"], "The author's message must be kept."],
  ["Which sentence is a summary, not a detail?", "The story shows how a community works together after a storm.", ["The storm began at 6 p.m.", "Mr. Lee wore a red scarf."], "A summary states a big idea.", true],
  ["In a summary, a quotation should be used…", "rarely, and only when the exact words matter", ["for every sentence", "instead of the main idea"], "Your own words show understanding."],
];

const RESEARCH: Q[] = [
  ["Which topic is narrow enough for a one-page report?", "How a hydroelectric generating station makes electricity", ["Energy", "Everything about Canada"], "A narrow topic is easier to research well."],
  ["Brainstorming is used to…", "generate ideas for a topic", ["check spelling", "publish a final copy"], "It is the first stage of the writing process."],
  ["Which source is a primary source?", "a diary written during the 1919 Winnipeg General Strike", ["a textbook chapter about it", "an encyclopedia entry about it"], "A primary source comes from the time or person directly involved."],
  ["Which source is a secondary source?", "a history book that explains the Red River Resistance", ["a letter written in 1869", "a photograph taken in 1870"], "A secondary source analyzes or describes primary sources."],
  ["A good reason to use more than one source is to…", "compare perspectives and check facts", ["make the report longer", "avoid writing in your own words"], "Several sources give a fuller picture."],
  ["Which website is most likely to be reliable for health information?", "a public health agency", ["an anonymous blog", "a social media post"], "Look for expert authors and clear sources."],
  ["When judging a web page, which question helps most?", "Who wrote this and why?", ["How colourful is it?", "How long is the page?"], "Author and purpose affect reliability."],
  ["A graphic organizer for research notes helps you…", "record and sort information by idea", ["copy whole pages", "avoid sources"], "Organized notes make drafting easier."],
  ["When taking notes from a source, you should write…", "key ideas in your own words and note the source", ["whole paragraphs word for word", "only the title"], "Record where each fact came from."],
  ["Why do researchers record their sources?", "to give credit and let readers check the information", ["so the text looks longer", "because spelling requires it"], "Citing sources shows honesty."],
  ["Two sources disagree about a date. What should you do?", "check a third reliable source", ["pick the one you like", "leave out the topic"], "Cross-check facts."],
  ["Which key words would best help search for information on the water cycle in Manitoba?", "water cycle Manitoba lakes rivers", ["water", "the cycle of things in a place"], "Specific key words give better search results."],
  ["An outline is used to…", "plan the order of ideas before drafting", ["check commas", "publish a text"], "It sets main points and details."],
  ["Which is the best research question?", "How did the railway change life for Prairie communities?", ["Trains?", "Yes or no: were there trains?"], "Open questions lead to deeper research."],
  ["A text with no author, no date and no sources is…", "less reliable", ["more reliable", "always a primary source"], "Reliable sources show where information comes from."],
  ["Which type of planning tool shows the cause and effect of an event?", "a cause-and-effect chart", ["a Venn diagram", "a timeline"], "Choose the tool that matches the purpose."],
  ["Which planning tool best compares two different sources?", "a Venn diagram", ["a timeline", "a table of contents"], "It shows what is alike and different."],
  ["Which planning tool best shows events in order?", "a timeline", ["a Venn diagram", "a glossary"], "Timelines show sequence."],
  ["An idea for an essay can come from…", "experiences, current events, literature and other subjects", ["only the teacher", "only the dictionary"], "Ideas come from many places."],
  ["Which topic fits an audience of Grade 3 students best?", "How seeds grow into plants", ["The economics of grain futures", "Plant genetics and DNA sequencing"], "Pick a topic that matches your audience.", true],
  ["Two articles describe the same event from different viewpoints. This helps you…", "understand how perspective shapes what is told", ["decide that one is always false", "stop researching"], "Notice how each source frames the event.", true],
  ["A source that is trying to sell you a product may be…", "biased", ["always neutral", "a primary source"], "Check the purpose of a source."],
  ["Which source type shows images and data together?", "an infographic", ["a table of contents", "a footnote"], "Different media provide information in different ways."],
  ["After collecting information, the next stage in the writing process is usually to…", "organize your ideas and plan a draft", ["publish", "stop"], "Plan, draft, revise, edit, publish."],
  ["Which would you highlight as a key step in a plan for a persuasive text?", "state your claim, give evidence, answer the other side", ["write your name", "choose a font"], "Plan according to the genre.", true],
];

const COMPOSE: Q[] = [
  ["Which form would best invite readers to a community cleanup?", "a poster or flyer", ["a lab report", "a poem about clouds"], "Choose a form that suits the purpose."],
  ["Which form best explains the steps for building a bird feeder?", "a how-to guide", ["a diary entry", "a sonnet"], "Procedures are written in order."],
  ["Which form would best share your opinion on a school rule?", "an editorial or letter to the editor", ["a recipe", "a timeline"], "Persuasive forms state and support a position."],
  ["Which form best tells a made-up story?", "a short story", ["a news report", "an instruction manual"], "Narratives tell events with characters."],
  ["A news article uses an “inverted pyramid”, which means…", "the most important facts come first", ["the story ends with a surprise", "the title comes last"], "Readers get the key facts early."],
  ["Which feature helps a reader find information quickly in a long report?", "headings", ["a longer title", "a bigger font on every page"], "Headings organize ideas."],
  ["Combining text with a chart and a photo in a digital report is an example of…", "using multiple modes to strengthen ideas", ["making the text longer", "avoiding research"], "Visual and digital elements can add meaning."],
  ["When writing for a Grade 3 audience, you should use…", "simple words and short sentences", ["technical terms without explanation", "very long paragraphs"], "Match language to the audience."],
  ["When writing for a formal audience such as a principal, you should use…", "polite, precise language", ["slang and text-message spellings", "only pictures"], "Context affects tone."],
  ["Which sentence has the most formal tone?", "I would like to request permission to use the gym on Friday.", ["Hey, can we use the gym Friday?", "Gym Friday?? Pls!!"], "Formal writing avoids slang."],
  ["The organization of a text should…", "put ideas in an order that makes sense for the purpose", ["be random", "put the conclusion first in an essay"], "Structure helps readers."],
  ["During the “revise” step of the writing process, you…", "improve the ideas, organization and wording", ["only fix commas", "choose the title font"], "Revising is about big changes."],
  ["Reorganizing paragraphs so the strongest point comes first in a persuasive text is part of…", "re-evaluating the organization", ["proofreading", "brainstorming"], "Check that the sequence fits your purpose."],
  ["A paragraph jumps from soccer to volcanoes. The best fix is to…", "keep paragraphs focused on one main idea", ["join it with the next paragraph", "delete the conclusion"], "One main idea per paragraph."],
  ["Which transition word shows contrast?", "however", ["therefore", "also"], "However signals a different idea."],
  ["Which transition word shows a result?", "consequently", ["although", "in addition"], "Consequently signals a result."],
  ["The best way to start a persuasive essay is usually with…", "a clear claim or thesis", ["a list of sources", "a conclusion"], "Tell readers your position."],
  ["Which text feature would you add to a science report to show data clearly?", "a labelled graph", ["a joke", "a decorative border"], "Features should support meaning."],
  ["Publishing a text means…", "sharing a final version with an audience", ["starting a draft", "taking notes"], "The last stage of the process."],
  ["Which of these is part of mechanics in writing?", "capital letters and punctuation", ["the main idea", "the topic"], "Mechanics are the conventions."],
  ["Clear handwriting and consistent keyboarding help readers by…", "keeping the text readable", ["making the text longer", "hiding mistakes"], "Readability matters for communication."],
  ["A good web page for a school project uses…", "a clear layout with headings and short paragraphs", ["a different font in every line", "no images or titles"], "Design choices affect clarity.", true],
  ["Which form best suits a personal reflection on a hockey season?", "a journal entry", ["a lab report", "a legal contract"], "Reflection is personal and thoughtful."],
  ["When writing a research report, you should include…", "an introduction, body paragraphs and a conclusion", ["only a conclusion", "only a title"], "Reports have a clear structure."],
  ["A poem's line breaks and white space are examples of…", "design choices that shape meaning", ["spelling errors", "research"], "Poets use layout on purpose.", true],
];

const FEEDBACK: Q[] = [
  ["Which comment is the most useful feedback on a draft?", "Your second paragraph needs an example to support your claim.", ["Good job.", "I don't like it."], "Useful feedback is specific."],
  ["Descriptive feedback tells you…", "what is working and what to do next", ["only your mark", "who wrote the best draft"], "It guides improvement."],
  ["Criteria (a rubric) help you to…", "know what a strong piece of work looks like", ["guess what the teacher likes", "skip the planning"], "Use criteria to check your work."],
  ["After getting feedback, a good next step is to…", "decide which suggestions to use and revise", ["ignore it", "throw away the draft"], "Reflect on feedback, then act."],
  ["Which is a SMART-style learning goal?", "I will add evidence to each paragraph of my next essay.", ["I will be better.", "I will try."], "A goal should be clear and measurable."],
  ["Which goal is easiest to check?", "Write three paragraphs, each with one quotation, by Friday.", ["Write well.", "Do more writing."], "Measurable goals have a count or a date."],
  ["Evidence of learning can be…", "drafts, notes and finished pieces over time", ["only a final test", "only the teacher's memory"], "Collect work to show growth."],
  ["A learner notices that her comma use improved between two drafts. She is…", "monitoring progress", ["ignoring criteria", "losing a goal"], "Compare work over time."],
  ["A friend says, “Your opening is strong, but the ending feels rushed.” Which is a strength?", "the opening", ["the ending", "nothing"], "Identify what is working."],
  ["Which area for growth does that comment name?", "the ending", ["the opening", "the title"], "It names what to improve next."],
  ["When you get feedback you disagree with, you should…", "consider it, ask questions and decide thoughtfully", ["argue until they agree", "never write again"], "Feedback is information, not an attack."],
  ["A learning goal should be reviewed…", "regularly, using evidence", ["never", "only at the end of the year"], "Check progress along the way."],
  ["Which question helps with reflection?", "What strategy helped me most this week?", ["Who got a better mark?", "What was the room temperature?"], "Reflection connects strategies to results."],
  ["A learner makes a checklist from the criteria. The checklist is useful for…", "checking a draft before handing it in", ["avoiding revising", "replacing the criteria"], "A self-check supports quality."],
  ["Peer feedback works best when it is…", "kind, specific and focused on the criteria", ["only about spelling", "very short"], "Respectful and helpful."],
  ["Which strategy supports a goal to read more fluently?", "reading aloud a short passage each day", ["reading nothing", "skipping hard texts"], "Practice that matches the goal."],
  ["Which is evidence of growth in a writing goal about organization?", "a draft with clear paragraphs after a draft with mixed ideas", ["a longer title", "a new pen"], "Evidence shows the change."],
  ["Feedback and criteria help you to identify…", "strengths and areas for growth", ["only mistakes", "only your marks"], "Both are important."],
  ["After revising, you should…", "compare the new draft to the criteria", ["stop checking", "start over"], "Check against the criteria.", true],
  ["Setting a new goal after reaching one shows…", "ongoing progress", ["failure", "that you did not learn"], "Learning keeps going."],
  ["A good goal for improving a persuasive essay is…", "to give two reasons, each with evidence", ["to be more persuasive somehow", "to have a longer title"], "Specific goals lead to action."],
  ["Self-assessment means…", "judging your own work against the criteria", ["avoiding feedback", "letting others write for you"], "You reflect on your own learning."],
  ["Which statement shows a growth mindset?", "I can improve this draft with revision.", ["I'm just bad at writing.", "There's no point in trying."], "Skills grow with practice.", true],
  ["A learner keeps a portfolio of work over a term. This helps by…", "showing progress and evidence of learning", ["hiding mistakes", "making the work heavier"], "Portfolios collect evidence over time."],
  ["When feedback says “vary your sentence beginnings,” you could…", "start some sentences with a phrase instead of the subject", ["start every sentence with “The”", "write only short sentences"], "Variety adds fluency.", true],
];

const VOCAB: Q[] = [
  ["In the word “unpredictable,” the prefix “un-” means…", "not", ["again", "before"], "Un- usually means not."],
  ["The suffix “-able” in “readable” means…", "able to be", ["without", "before"], "-able means capable of."],
  ["The Greek root “bio” means…", "life", ["earth", "water"], "Biology is the study of life."],
  ["The root “geo” in “geography” means…", "earth", ["sky", "write"], "Geo comes from Greek for earth."],
  ["The root “aud” in “audience” means…", "hear", ["see", "speak"], "Audio, auditorium and audible share the root."],
  ["The Latin root “port” in “transport” means…", "carry", ["push", "plan"], "Import, export and portable share it."],
  ["The word “specialized” in “specialized vocabulary” means…", "specific to a subject", ["very old", "from another language only"], "Each subject has its own terms."],
  ["In science, the word “mass” means…", "the amount of matter in an object", ["a church service", "a large crowd"], "Words can have subject-specific meanings."],
  ["In math, a “plane” is…", "a flat surface that goes on forever", ["an aircraft", "a tool for smoothing wood"], "Context decides which meaning."],
  ["Which word is spelled correctly?", "necessary", ["neccessary", "necesary"], "One c and two s's: ne-ces-sa-ry."],
  ["Which word is spelled correctly?", "separate", ["seperate", "separete"], "Remember “a rat” in sep-a-rate."],
  ["Which word is spelled correctly?", "environment", ["enviroment", "envirnoment"], "Notice the “n” before “m.”"],
  ["Which word is spelled correctly?", "government", ["goverment", "govenment"], "Govern + ment."],
  ["Which word is spelled correctly in Canadian English?", "colour", ["color", "colur"], "Canadian spelling keeps the “u.”"],
  ["Which is the Canadian spelling?", "centre", ["center", "centar"], "Canadian spelling uses -re."],
  ["Which is the correct form for the verb in Canadian English?", "practise", ["practize", "practyse"], "Practice is the noun; practise is the verb."],
  ["The word “biodegradable” combines “bio-” (life) and “degrade” (break down). It means…", "able to be broken down by living things", ["able to make life", "able to travel"], "Use the word parts to work out the meaning."],
  ["The prefix “re-” in “rewrite” means…", "again", ["not", "under"], "Re- means again or back."],
  ["The word “photosynthesis” has “photo” meaning…", "light", ["water", "plant"], "Photo is the Greek root for light."],
  ["The word “autobiography” means…", "the story of a person's life written by that person", ["a book about cars", "a type of map"], "Auto = self, bio = life, graph = write."],
  ["Which context clue helps with “arid”? “The arid desert had almost no rain.”", "almost no rain", ["desert", "had"], "The clue explains the word."],
  ["An antonym of “ancient” is…", "modern", ["old", "historic"], "An antonym means the opposite."],
  ["“Meticulous” means…", "very careful about details", ["quickly done", "loud"], "A meticulous editor checks every comma.", true],
  ["A word that comes from Latin “scribere” (to write) is…", "describe", ["destroy", "dismiss"], "Scribe-type words relate to writing.", true],
  ["Which spelling pattern is correct?", "believe", ["beleive", "beleave"], "There is no c here, so it is i before e.", true],
  ["Specialized words in social studies, like “federal,” are best learned by…", "using them in context and checking meanings", ["skipping them", "guessing without checking"], "Practice builds a working vocabulary."],
];

export const units = [
  bankUnit({
    id: "mb-reading-with-purpose",
    title: "Reading with a Purpose",
    emoji: "🔖",
    blurb: "Prior knowledge, connections, questions and reflecting on what you learn.",
    parentNote: "Practises setting a purpose for reading, using prior knowledge and making connections, monitoring understanding, fluency and reflecting on new learning.",
    standards: ["ELA.9.B1.1, ELA.9.B1.2, ELA.9.B2.2, ELA.9.B2.4, ELA.9.B4.1", "purpose, prior knowledge, connections, fluency and reflecting on new learning"],
    items: PURPOSE,
  }),
  bankUnit({
    id: "mb-summarizing",
    title: "Summarizing Texts",
    emoji: "📝",
    blurb: "Find the main ideas and put them in your own words.",
    parentNote: "Practises summarizing: grouping related ideas, separating important from less important information, paraphrasing and keeping the author's message.",
    standards: ["ELA.9.B2.5", "summarizing key ideas while keeping the author's message"],
    items: SUMMARY,
  }),
  bankUnit({
    id: "mb-plan-and-research",
    title: "Plan & Research",
    emoji: "🔎",
    blurb: "Choose topics, find reliable sources and plan before you write.",
    parentNote: "Practises generating and narrowing topics, using multiple sources, judging reliability, taking notes, citing sources and choosing planning tools.",
    standards: ["ELA.9.C1.1, ELA.9.C1.2, ELA.9.C1.4", "generating ideas, using sources and planning texts"],
    items: RESEARCH,
  }),
  bankUnit({
    id: "mb-choose-form-and-compose",
    title: "Form & Composing",
    emoji: "✍️",
    blurb: "Pick the right form for your audience and shape a clear text.",
    parentNote: "Practises choosing a form for purpose and audience, tone, organization, transitions, text features and design choices when composing and publishing.",
    standards: ["ELA.9.C1.5, ELA.9.C1.6, ELA.9.C1.7, ELA.9.C2.1, ELA.9.C3.4", "choosing form, composing, reorganizing and publishing texts"],
    items: COMPOSE,
  }),
  bankUnit({
    id: "mb-feedback-and-goals",
    title: "Feedback & Goals",
    emoji: "🎯",
    blurb: "Use feedback, set goals and show your growth as a learner.",
    parentNote: "Practises applying descriptive feedback, using criteria, setting clear learning goals and tracking progress with evidence.",
    standards: ["ELA.9.D2.1, ELA.9.D2.2", "using feedback, setting goals and monitoring progress"],
    items: FEEDBACK,
  }),
  bankUnit({
    id: "mb-vocabulary-and-spelling",
    title: "Vocabulary & Spelling",
    emoji: "🔤",
    blurb: "Word parts, subject words and tricky spellings.",
    parentNote: "Practises specialized vocabulary, Greek and Latin word parts, context clues and commonly misspelled words, using Canadian spelling.",
    standards: ["ELA.9.A2.1, ELA.9.A2.2, ELA.9.A2.3, ELA.9.A2.4", "foundational word knowledge applied to specialized vocabulary and spelling"],
    items: VOCAB,
  }),
];
