import { bankUnit, type Q } from "../own";

// Grade 9 social studies, Canada in the Contemporary World. Units are written for the Manitoba outcomes
// (9-KC, 9-KI, 9-KG, 9-KE, 9-KL, 9-KP, 9-KH). Treaty, residential school and Métis content is light and
// needs partner review before launch.

const RIGHTS: Q[] = [
  ["Which document did the United Nations adopt in 1948 to list the rights every person has?", "The Universal Declaration of Human Rights", ["The Canadian Charter of Rights and Freedoms", "The Constitution Act, 1867"], "The UN adopted the Universal Declaration of Human Rights in 1948."],
  ["The Canadian Charter of Rights and Freedoms became part of Canada's Constitution in…", "1982", ["1867", "1948"], "The Charter is part of the Constitution Act, 1982."],
  ["Freedom of peaceful assembly is a…", "fundamental freedom in the Charter", ["right found only in the Criminal Code", "duty of every voter"], "Fundamental freedoms include conscience, religion, expression, peaceful assembly and association."],
  ["Which of these is a fundamental freedom in the Charter?", "freedom of expression", ["the right to a free car", "the right to skip school"], "People may share their thoughts and opinions, within reasonable limits."],
  ["Being presumed innocent until proven guilty is a…", "legal right", ["mobility right", "language right"], "Legal rights protect people who deal with police and courts."],
  ["The right of a citizen to vote at 18 is a…", "democratic right", ["legal right", "mobility right"], "Democratic rights let citizens vote and run for office."],
  ["A Canadian citizen moving from Manitoba to Nova Scotia to live and work is using a…", "mobility right", ["legal right", "language right"], "Mobility rights let citizens live and work anywhere in Canada."],
  ["Section 15 of the Charter says that every individual is…", "equal before and under the law", ["richer than others", "free from all rules"], "Equality rights protect people from unfair discrimination."],
  ["Having food, clean water and shelter is an example of a…", "basic human right", ["voting right", "mobility right"], "Basic rights are the things people need to live with dignity."],
  ["Article 23 of the Charter protects the right of…", "minority-language education", ["free travel", "free speech on the internet"], "It lets francophone and anglophone minorities educate their children in their own language where numbers warrant."],
  ["Who is able to apply for Canadian citizenship?", "A permanent resident who has lived in Canada long enough", ["Anyone who has visited for a week", "Only people born in Canada"], "Adults must be permanent residents who have lived in Canada for at least three of the last five years."],
  ["How long must most adult applicants have lived in Canada in the five years before applying for citizenship?", "at least three years", ["at least one month", "at least twenty years"], "The residence rule is three years (1,095 days) out of the last five."],
  ["Most adult citizenship applicants must show they can communicate in…", "English or French", ["English and Spanish", "Cree or Dakota"], "Canada's two official languages are English and French."],
  ["Most applicants aged 18 to 54 must pass a…", "citizenship test", ["driving test", "spelling bee"], "The test covers Canada's history, government, rights and responsibilities."],
  ["Which Manitoba woman helped win the vote for women in the Prairies and was a member of the Persons Case “Famous Five”?", "Nellie McClung", ["Laura Secord", "Viola Desmond"], "Nellie McClung lived in Manitoba and campaigned for women's right to vote."],
  ["In 1916 Manitoba became the first province to…", "give some women the right to vote and run for office", ["ban the vote for everyone", "create a national anthem"], "Manitoba was the first province to give women the vote in provincial elections."],
  ["Which Nova Scotia businesswoman challenged racial segregation by sitting in a whites-only section of a theatre in 1946?", "Viola Desmond", ["Nellie McClung", "Rosa Parks"], "Viola Desmond's act became a symbol of the fight against racial discrimination in Canada."],
  ["The Canadian Museum for Human Rights is in which Manitoba city?", "Winnipeg", ["Brandon", "Thompson"], "The museum opened in Winnipeg in 2014."],
  ["Canadian John Humphrey is remembered for helping…", "write the first draft of the Universal Declaration of Human Rights", ["write “O Canada”", "design the Canadian flag"], "Humphrey was a Montreal lawyer who directed the UN's human rights division."],
  ["The Chinese head tax, charged to Chinese immigrants, is remembered today as…", "a past injustice that Canada has formally apologized for", ["a fair tax on all immigrants", "a law that protected workers"], "It unfairly targeted one group; the federal government apologized in 2006."],
  ["Why do human rights protections matter in a democracy?", "They protect minorities from being treated unfairly by a majority", ["They let the majority decide everything", "They stop people from voting"], "Rights keep the powerful from taking away the freedoms of others."],
  ["Which pair of rights shows that rights come with limits?", "Freedom of expression does not allow spreading hatred", ["Freedom of expression allows any act", "Legal rights do not apply to adults"], "Section 1 of the Charter allows reasonable limits that a free and democratic society can justify.", true],
  ["Which is a responsibility that goes along with the right to vote?", "learning about candidates and issues", ["choosing a candidate only because of a flyer", "ignoring election results"], "Citizens are most helpful when they are informed.", true],
  ["Residential schools, Japanese Canadian internment and the head tax are all examples of…", "past injustices that took away rights of groups of people", ["policies that protected equality", "examples of the Charter at work"], "Studying them helps Canadians understand the present and work toward fairness.", true],
  ["The Canadian Bill of Rights, passed in 1960, was…", "an earlier federal law that protected rights before the Charter", ["the same document as the Charter", "a United Nations treaty"], "The Charter later became part of the Constitution, giving it more weight.", true],
  ["First Nations people with status gained the right to vote in federal elections without giving up their status in…", "1960", ["1867", "1982"], "Before 1960 many First Nations people had to give up status to vote federally.", true],
  ["A person is told why they are being arrested and can speak with a lawyer. Which kind of right is that?", "legal right", ["democratic right", "language right"], "The Charter protects people when they are detained or arrested.", true],
];

const GOVERNMENT: Q[] = [
  ["Canada's system of government is a…", "parliamentary democracy and constitutional monarchy", ["republic led by a president", "dictatorship"], "The monarch is head of state, but elected people make the laws."],
  ["Who is Canada's head of government?", "the Prime Minister", ["the Governor General", "the Chief Justice"], "The Prime Minister leads the government and cabinet."],
  ["Who represents the monarch in Manitoba?", "the Lieutenant Governor", ["the Premier", "the Mayor of Winnipeg"], "Each province has a Lieutenant Governor."],
  ["Who leads the Manitoba government?", "the Premier", ["the Governor General", "the Clerk"], "The Premier is the leader of the party that governs in the province."],
  ["The legislative branch of government…", "makes laws", ["interprets laws in court", "arrests people"], "Parliament and legislatures debate and pass laws."],
  ["The executive branch of government…", "carries out the laws and runs government programs", ["writes the Charter", "chooses judges for each case"], "The Prime Minister and cabinet are part of the executive."],
  ["The judicial branch of government…", "interprets laws and decides cases in courts", ["collects taxes", "writes budgets"], "Judges are independent of the other branches."],
  ["Manitoba's laws are passed in the Legislative Building, which is in…", "Winnipeg", ["Brandon", "Portage la Prairie"], "Winnipeg is the capital of Manitoba."],
  ["An elected member of Manitoba's legislature is called an…", "MLA", ["MP", "senator"], "MLA stands for Member of the Legislative Assembly."],
  ["An elected member of the federal House of Commons is called an…", "MP", ["MLA", "mayor"], "MP stands for Member of Parliament."],
  ["Which level of government is mainly responsible for local roads, garbage pickup and city parks?", "municipal", ["federal", "monarchy"], "Cities, towns and rural municipalities look after local services."],
  ["Which level of government is mainly responsible for national defence?", "federal", ["municipal", "school division"], "Defence, currency and the post office are federal."],
  ["Which level of government is mainly responsible for most education?", "provincial", ["federal", "United Nations"], "Provinces set school systems and curriculum."],
  ["The idea of federalism means that…", "power is shared between a central government and provincial governments", ["only one government exists", "all power belongs to the monarch"], "Canada divides responsibilities between the federal and provincial governments."],
  ["In a federal election, voters in each riding choose…", "one Member of Parliament", ["the Prime Minister directly", "the judges of the Supreme Court"], "The leader of the party that wins the most seats usually becomes Prime Minister."],
  ["The party with the second-most seats forms the…", "Official Opposition", ["Senate", "cabinet"], "The Official Opposition questions and challenges the government."],
  ["A minority government happens when…", "no party has more than half the seats", ["only women are elected", "the monarch rules"], "A minority government needs support from other parties to pass laws."],
  ["The senators in Canada's Senate are…", "appointed, not elected", ["chosen by a school vote", "elected in every riding"], "Senators are appointed on the advice of the Prime Minister."],
  ["To be eligible to vote in a Canadian federal election, a person must be a Canadian citizen and at least…", "18 years old", ["10 years old", "25 years old"], "Voting is a democratic right for citizens aged 18 and over."],
  ["A secret ballot protects voters by…", "keeping their choice private", ["telling everyone their choice", "letting them vote twice"], "No one can pressure a voter, because no one knows how they voted."],
  ["The highest court in Canada is the…", "Supreme Court of Canada", ["Court of Appeal of Manitoba", "House of Commons"], "It sits in Ottawa and has nine judges."],
  ["Political parties help democracy by…", "offering voters different plans and ideas", ["deciding court cases", "collecting garbage"], "Parties organize candidates and policies."],
  ["Which is an advantage of majority rule?", "decisions can be made clearly and quickly", ["minorities are always protected", "no one ever disagrees"], "Majority rule is simple, but minorities can feel left out.", true],
  ["Which is a disadvantage of majority rule?", "the needs of minorities can be overlooked", ["every voice gets a veto", "elections cannot happen"], "That is why rights protect minorities.", true],
  ["A bill becomes law after it passes through readings and then receives…", "Royal Assent", ["a school vote", "a mayor's signature"], "Royal Assent is given by the Governor General or Lieutenant Governor.", true],
  ["First Nations governments, such as a Chief and council, make decisions for…", "their own communities", ["only the federal Parliament", "other provinces"], "They are one of the levels of government that share power in Canada.", true],
  ["Citizens can influence government by…", "writing letters, voting and joining peaceful groups", ["breaking laws on purpose", "staying silent"], "Citizens have many peaceful ways to speak up.", true],
];

const IDENTITY: Q[] = [
  ["Which of these can help shape a person's identity?", "family, culture, language and community", ["only the weather", "only what they eat"], "Many things together shape who we are."],
  ["Canada has two official languages. They are…", "English and French", ["English and Cree", "French and German"], "The Official Languages Act of 1969 made them official."],
  ["Canada's policy of multiculturalism means…", "people can keep and share their cultures", ["everyone must act the same", "only one culture is allowed"], "Canada has had a multiculturalism policy since 1971."],
  ["The Manitoba Act of 1870 is connected to which leader?", "Louis Riel", ["John A. Macdonald only", "Samuel de Champlain"], "Louis Riel and the Métis negotiated the creation of Manitoba as a province."],
  ["Which language is traditionally spoken by the Métis in Manitoba?", "Michif", ["Latin", "Inuktitut"], "Michif blends French and Cree and other languages."],
  ["Which of these Indigenous languages is spoken in Manitoba?", "Cree", ["Inuktitut", "Mohawk"], "Cree, Ojibwe, Dakota, Oji-Cree, Dene and Michif are spoken in Manitoba."],
  ["Residential schools were run by the federal government and…", "churches", ["school divisions", "the United Nations"], "Children were taken from their families, and their languages and cultures were suppressed."],
  ["Many Indigenous communities are working to bring back their languages by…", "teaching them in schools and with Elders", ["banning them", "avoiding them"], "Language revitalization helps cultures stay strong."],
  ["The Truth and Reconciliation Commission of Canada released how many Calls to Action in 2015?", "94", ["10", "200"], "The Calls to Action ask governments and all Canadians to work toward reconciliation."],
  ["In 2008 the Prime Minister of Canada…", "apologized in Parliament for residential schools", ["opened the first residential school", "named a new capital"], "The apology acknowledged the harm done to Indigenous children, families and communities."],
  ["The National Centre for Truth and Reconciliation is located at which Manitoba university?", "University of Manitoba", ["Brandon University", "University of Winnipeg"], "It cares for statements and records about residential schools."],
  ["Assimilative policies tried to…", "make cultural groups give up their own ways and become like the majority", ["protect minority languages", "give every group the vote"], "They harmed many communities and are criticized today."],
  ["Stereotyping means…", "believing everyone in a group is the same", ["getting to know individuals", "voting in an election"], "Stereotypes are unfair because people are individuals."],
  ["Discrimination happens when someone is…", "treated unfairly because of a group they belong to", ["given a fair turn", "asked to share"], "Discrimination can be directly harmful and is against human rights law."],
  ["Which action best fights a stereotype?", "Get to know people as individuals", ["Repeat a joke about a group", "Avoid people who look different"], "Learning real stories breaks down stereotypes."],
  ["Which law protects the rights of English and French speakers across Canada?", "the Official Languages Act", ["the Weather Act", "the Highway Traffic Act"], "Federal services must be offered in both official languages."],
  ["Francophone communities in Manitoba, such as Saint-Boniface, work to protect…", "their French language and culture", ["English only", "trade routes"], "Saint-Boniface is a French-speaking community in Winnipeg."],
  ["Mass media such as movies and social media can influence identity by…", "showing images and ideas about what is normal", ["having no effect at all", "deciding the law"], "People should think critically about media messages."],
  ["Canadian content rules for radio and TV exist to…", "help Canadian music and stories be heard", ["stop all foreign shows", "make stations pay more taxes"], "They support Canadian artists and cultures."],
  ["Which statement shows critical thinking about popular culture?", "Ask who made a message and why", ["Believe everything online", "Share it before reading it"], "Thinking about the source helps you judge the message."],
  ["Which factor shapes a regional identity in Manitoba?", "prairie landscape, history and local traditions", ["tropical weather", "a single national language"], "Regions feel different because of land, people and history."],
  ["How does the Charter help protect cultural diversity?", "It protects equality and multicultural heritage", ["It requires everyone to share one culture", "It bans festivals"], "Section 27 says the Charter is to be interpreted in a way that preserves Canada's multicultural heritage.", true],
  ["Which of these is a way to respect cultural pluralism?", "Learn about and welcome many cultures", ["Expect newcomers to hide their culture", "Allow only one holiday"], "Cultural pluralism means many cultures living together.", true],
  ["Why is it important not to treat all First Nations, Métis and Inuit as one group?", "They have different languages, histories and cultures", ["They all speak one language", "They live in the same place"], "Many distinct Nations live across Canada.", true],
  ["The Sixties Scoop refers to…", "children being taken from Indigenous families and adopted into non-Indigenous homes", ["a snow-clearing program", "a school sports league"], "It was another policy that damaged families and identity.", true],
  ["Reconciliation means…", "building respectful relationships and acting to make things right", ["forgetting the past", "ending all treaties"], "It involves learning, listening and action.", true],
  ["A current issue about Canadian identity is how to…", "include newcomers and Indigenous peoples fairly in a shared Canada", ["avoid all change", "ban all media"], "People in Canada continue to discuss this question.", true],
];

const GLOBAL: Q[] = [
  ["Canada was a founding member of which international organization in 1945?", "the United Nations", ["the Olympic Committee", "the European Union"], "Canada has helped the UN since it began."],
  ["NATO is…", "a military alliance of countries", ["a sports league", "a trade union"], "Canada helped found NATO in 1949."],
  ["The Commonwealth is…", "a group of countries with historic ties to the British Empire", ["a Canadian province", "a trade tax"], "Canada is one of its member countries."],
  ["Canada's biggest trading partner is the…", "United States", ["Brazil", "Japan"], "Most Canadian exports go to the U.S."],
  ["Which Canadian won a Nobel Peace Prize in 1957 for ideas that led to UN peacekeeping?", "Lester B. Pearson", ["Terry Fox", "Tommy Douglas"], "Pearson suggested a UN peacekeeping force during the Suez Crisis."],
  ["Peacekeeping means…", "helping to keep peace where fighting has stopped", ["starting a war", "taking over a country"], "Peacekeepers help protect people while peace talks continue."],
  ["Foreign aid from Canada is used to…", "help people in other countries with needs like health and food", ["pay for hockey arenas", "lower taxes at home"], "Canada gives development assistance through government and non-profit groups."],
  ["An example of global citizenship is…", "supporting a fair trade or relief campaign", ["ignoring a crisis", "wasting resources on purpose"], "Global citizens think about people beyond their own community."],
  ["Globalization means…", "countries are becoming more connected through trade, travel and communication", ["countries are closing all borders", "people stop using money"], "It affects what we buy, hear and share."],
  ["An advantage of globalization is…", "greater variety of goods and ideas", ["fewer ways to communicate", "higher taxes for everyone"], "People can connect and trade over long distances."],
  ["A disadvantage of globalization can be…", "local businesses having trouble competing", ["too many languages", "too much sunlight"], "Cheaper imports can make competition difficult."],
  ["Canada is called an industrialized nation because it…", "produces goods and services using machines and technology", ["has no cities", "has no factories"], "Industries and services are a large part of the economy."],
  ["Most jobs in Canada today are in the…", "service sector", ["farming sector only", "fishing sector only"], "Services include teaching, health care and retail."],
  ["Which Manitoba industry is a major source of electricity?", "hydroelectricity", ["coal mining", "whale oil"], "Manitoba Hydro produces most of its power from flowing water."],
  ["A consumer-based economy depends on…", "people buying goods and services", ["people growing all their own food", "no one spending money"], "What people choose to buy affects jobs and the environment."],
  ["Advertising tries to…", "influence what people want to buy", ["teach the Charter", "balance a budget"], "Understanding ads helps you make informed choices."],
  ["Which consumer choice may help the environment?", "buying durable goods and reusing or repairing them", ["throwing items away after one use", "buying more than you need"], "Less waste means a smaller ecological footprint."],
  ["An ecological footprint measures…", "how much nature a person or group uses", ["a person's shoe size", "the size of a park"], "A smaller footprint is easier on the Earth."],
  ["Fair trade products are made so that…", "producers are paid fairly and treated safely", ["prices are as low as possible", "no one is paid"], "Fair trade labels show a commitment to fair treatment."],
  ["Sustainable development means meeting present needs without…", "harming the ability of future generations to meet theirs", ["building anything", "using any energy"], "It balances people, economy and environment."],
  ["The 2015 Paris Agreement is about…", "limiting climate change", ["trading hockey cards", "sharing satellites"], "Many countries agreed to cut greenhouse gas emissions."],
  ["Remembrance Day on November 11 honours…", "people who served in wars and peacekeeping", ["the founding of Manitoba", "the Prime Minister"], "Canadians wear poppies and observe two minutes of silence."],
  ["To compare how two news sources report the same event, you should…", "look at who wrote it, what they include and what they leave out", ["believe the first one you read", "count the number of pictures"], "Different media can portray events differently.", true],
  ["A fair-minded global citizen tries to…", "consider local, national and global interests together", ["think only of themselves", "ignore other countries"], "Decisions can affect people far away.", true],
  ["Canada's military is sometimes asked to help in other countries. A question to ask is…", "what the costs and benefits are for everyone affected", ["whether it is exciting", "what colour the uniforms are"], "Citizens can weigh the implications of military decisions.", true],
  ["Which of these is an example of Canadians contributing to the global community?", "arts, sciences and humanitarian aid", ["building walls", "ignoring other countries"], "Many Canadians have shared inventions, art and help abroad.", true],
  ["Under CUSMA (the Canada–United States–Mexico Agreement), the three countries…", "agree on rules for trade", ["share one government", "use the same flag"], "It guides how goods can cross the borders.", true],
];

const TREATIES: Q[] = [
  ["A treaty is…", "an agreement between nations or governments", ["a type of tax", "a school rule"], "Treaties in Canada are agreements between First Nations and the Crown."],
  ["Treaty 1, signed in 1871, was the first of the…", "numbered treaties", ["trade agreements with Europe", "provincial laws"], "Several numbered treaties cover Manitoba."],
  ["Treaty 1 was signed at which historic site near Winnipeg?", "Lower Fort Garry", ["Fort Whoop-Up", "Lower Fort Langley"], "Treaty 1 was signed in August 1871 at Lower Fort Garry."],
  ["The phrase “We are all treaty people” means…", "everyone living in Canada has responsibilities connected to treaties", ["only First Nations people have treaties", "treaties no longer exist"], "Treaties are agreements that all Canadians benefit from and must honour."],
  ["Treaty land entitlement is…", "a process of giving First Nations land owed to them under treaties", ["a plan to build parks", "a vote on a mayor"], "Some First Nations in Manitoba are still receiving land owed under treaty."],
  ["First Nations self-government means…", "First Nations make decisions about their own communities", ["the provinces make all decisions", "no one makes decisions"], "Self-government is part of self-determination."],
  ["Self-determination for First Nations, Métis and Inuit means…", "having the power to make decisions that affect their own futures", ["leaving Canada", "giving up their cultures"], "It is about choice and control over their own lives."],
  ["Which group was recognized as having Aboriginal rights in the Constitution Act, 1982?", "First Nations, Inuit and Métis peoples", ["Only First Nations", "Only Inuit"], "Section 35 recognizes and affirms existing Aboriginal and treaty rights."],
  ["In 2013 the Supreme Court of Canada ruled in a case involving the Manitoba Métis Federation that…", "the federal government had not kept its promise about Métis land in the Manitoba Act", ["the Métis had no rights", "Manitoba should not exist"], "The ruling said the Crown failed to act honourably.", true],
  ["Restorative justice focuses on…", "repairing harm and bringing people together", ["punishing as harshly as possible", "ignoring the victim"], "It often includes the person who caused harm, the victim and the community."],
  ["A sentencing circle is…", "a gathering where community members help decide how to repair harm", ["a type of dance", "a school game"], "Courts sometimes use circles with Indigenous communities."],
  ["Indigenous justice systems often emphasize…", "healing and the strength of relationships", ["fines only", "closing courts"], "Many communities have their own laws and ways of resolving conflict."],
  ["In Manitoba, a lawyer who works for the government and presents the case against an accused person is a…", "Crown attorney", ["school principal", "senator"], "Crown attorneys prosecute criminal charges."],
  ["The Youth Criminal Justice Act covers young people aged…", "12 to 17", ["5 to 8", "25 to 30"], "It treats youth differently from adults and focuses on rehabilitation."],
  ["Which court is the highest in Manitoba?", "Court of Appeal", ["Provincial Court", "Municipal court"], "The Court of Appeal hears appeals from lower courts."],
  ["Which of these provides police services in many Manitoba communities?", "RCMP and municipal police services", ["the Senate", "the school board"], "The Winnipeg Police Service, for example, serves Winnipeg."],
  ["Legal Aid Manitoba helps people who…", "cannot afford a lawyer", ["want to avoid taxes", "need a passport"], "Everyone deserves access to justice."],
  ["Which statement shows respect for Indigenous peoples?", "Learn from communities and listen to their voices", ["Assume all Nations are the same", "Treat treaties as old stories only"], "Respect means learning that Nations are distinct and living."],
  ["First Nations, Métis and Inuit people today are…", "living, diverse communities with their own governments and cultures", ["only part of the past", "one single group"], "Their histories and futures are part of Canada now."],
  ["Land claims agreements settle questions about…", "who has rights to land and resources", ["school hours", "highway speeds"], "They are one way governments and Indigenous peoples reach agreements."],
  ["A challenge in Canada today is that some First Nations communities…", "still lack safe drinking water or housing", ["have too many roads", "have no history"], "Governments and communities are working on these needs."],
  ["An opportunity from treaty relationships is…", "partnerships in education, business and caring for the land", ["ending all agreements", "ignoring each other"], "Respectful partnerships can strengthen communities."],
  ["Truth and reconciliation requires first…", "learning the truth about the past", ["forgetting the past", "deciding nothing needs to change"], "Truth-telling comes before real reconciliation."],
  ["Why is a fair justice system important to democracy?", "Everyone is treated equally under the law", ["Only some people follow laws", "Judges decide without evidence"], "The rule of law applies to everyone, including governments."],
  ["A person accused of a crime in Canada has the right to…", "a fair trial", ["no trial", "a trial without a lawyer being allowed"], "This is a legal right protected by the Charter.", true],
  ["The Constitution Act, 1982 recognizes which three Indigenous groups?", "First Nations, Inuit and Métis", ["Cree, Ojibwe and Dakota only", "Prairie, Arctic and Coastal"], "They are named as the Aboriginal peoples of Canada.", true],
];

const common = { emoji: "🍁" };

export const units = [
  bankUnit({
    ...common,
    id: "mb-rights-and-citizenship",
    title: "Rights & Citizenship",
    emoji: "⚖️",
    blurb: "The Charter, human rights and becoming a citizen.",
    parentNote: "Practises the rights listed in the Universal Declaration of Human Rights and the Canadian Charter of Rights and Freedoms, the requirements for citizenship, and Canadians such as Nellie McClung and Viola Desmond who worked for human rights.",
    standards: ["9-KC-001, 9-KC-002, 9-KC-003, 9-KC-004, 9-KH-031", "human rights, the Charter, citizenship and the development of human rights in Canada"],
    items: RIGHTS,
  }),
  bankUnit({
    ...common,
    id: "mb-government-and-democracy",
    title: "Government & Democracy",
    emoji: "🏛️",
    blurb: "Parliament, elections, courts and who decides what.",
    parentNote: "Practises Canadian parliamentary democracy: the three branches of government, the federal, provincial, First Nations and municipal levels, how elections work and the strengths and weaknesses of majority rule.",
    standards: ["9-KC-005, 9-KC-006, 9-KC-007, 9-KC-008, 9-KC-012, 9-KP-044", "parliamentary democracy, branches and levels of government, elections and majority rule"],
    items: GOVERNMENT,
  }),
  bankUnit({
    ...common,
    id: "mb-identity-and-diversity",
    title: "Identity & Diversity",
    emoji: "🌈",
    blurb: "What shapes who we are, and how Canada protects culture.",
    parentNote: "Practises the factors that shape personal and national identity, the effects of assimilative policies and discrimination, the influence of media, and how identity, language and culture are protected in Canada.",
    standards: ["9-KI-016, 9-KI-017, 9-KI-018, 9-KI-019, 9-KI-020, 9-KI-021", "identity, assimilation, stereotyping, media influence and the protection of culture"],
    items: IDENTITY,
  }),
  bankUnit({
    ...common,
    id: "mb-global-citizenship-and-economy",
    title: "Global Citizens & Our Economy",
    emoji: "🌍",
    blurb: "Canada in the world, trade and the choices consumers make.",
    parentNote: "Practises Canada's connections with other nations, its place in international organizations, characteristics of an industrialized economy, globalization and the effects of consumer choices.",
    standards: ["9-KG-034, 9-KG-036, 9-KG-037, 9-KG-038, 9-KG-039, 9-KE-048, 9-KE-049, 9-KE-050, 9-KE-051", "global citizenship, international organizations, the Canadian economy, globalization and consumer choices"],
    items: GLOBAL,
  }),
  bankUnit({
    ...common,
    id: "mb-treaties-and-justice",
    title: "Treaties & Justice",
    emoji: "🤝",
    blurb: "Treaties, self-determination and the justice system in Manitoba.",
    parentNote: "Practises how treaties, self-government and land agreements connect First Nations, Métis and Inuit peoples with Canada, and how the justice system in Manitoba works, including Indigenous approaches to justice. This content is light and still needs review with Indigenous partners.",
    standards: ["9-KC-010, 9-KC-010A, 9-KL-027, 9-KP-045", "the justice system in Manitoba, Indigenous perspectives on justice, treaties and self-determination"],
    items: TREATIES,
  }),
];
