import { bankUnit, type Q } from "../own";

// Kindergarten social studies, outcomes not covered elsewhere: responsibilities and rules (0-KC-001, 0-VP-006, 0-VE-007,
// 0-VE-008, 0-VC-001, 0-KP-023), Canada and celebrations (0-KC-005, 0-KC-006, 0-KH-017, 0-KI-011), time and stories of the past
// (0-KH-018, 0-KH-019, 0-VH-004, 0-S-202, 0-S-404), ways to communicate (0-KI-010, 0-KI-010A, 0-S-400 to 0-S-403), maps and
// the wider world (0-KL-014, 0-KL-016, 0-KG-021, 0-VG-005, 0-KL-013), working together (0-S-100 to 0-S-102, 0-VI-002,
// 0-VI-002A, 0-S-301) and finding out (0-S-200, 0-S-201, 0-S-203, 0-S-300).

const RESPONSIBLE: Q[] = [
  ["Which is a job you might do at home?", "Put away your toys", ["Drive the car", "Cook a feast alone"], "Children can help at home with small jobs."],
  ["Which is a job you might do at school?", "Hang up your coat", ["Mark the tests", "Teach the class"], "You are responsible for your own things."],
  ["A responsibility is…", "a job you should do", ["a game", "a snack"], "Responsibilities are things we should do."],
  ["Who feeds a class pet?", "Students who take turns", ["Nobody", "A stranger"], "Classes share jobs."],
  ["Which is a classroom rule?", "Walk in the hallway", ["Run in the hallway", "Yell in the hall"], "Rules help keep us safe."],
  ["Why do we have rules at school?", "To keep everyone safe and fair", ["To make school boring", "To trick people"], "Rules help everyone."],
  ["Which is a good playground rule?", "Take turns on the slide", ["Push on the slide", "Climb up the slide at the same time"], "Taking turns keeps everyone safe."],
  ["You respect the rules when you…", "follow them", ["break them", "ignore them"], "Respect means following the rules."],
  ["Which shows respect for school property?", "Putting books back on the shelf", ["Drawing on the wall", "Ripping pages"], "Property means things that belong to someone or to the school."],
  ["A friend's crayons fall on the floor. A respectful thing to do is…", "pick them up for your friend", ["take them", "stomp on them"], "We respect others' property."],
  ["Before using a friend's toy you should…", "ask first", ["grab it", "hide it"], "Asking shows respect for their things."],
  ["Which is the right thing to do with a library book?", "Take care of it and return it", ["Draw in it", "Lose it on purpose"], "Library books belong to everyone."],
  ["Sharing means…", "letting others use things too", ["keeping all of it", "hiding it"], "Sharing is a way to work together."],
  ["There is one set of blocks and two friends. What can you do?", "Share the blocks", ["Hold them all", "Break them"], "Sharing work and resources helps everyone."],
  ["Which shows you are willing to help your class?", "Helping tidy up", ["Walking away", "Making more mess"], "Willing means you want to help."],
  ["Which shows you contribute to your family?", "Setting the table", ["Hiding", "Making a mess on purpose"], "Contribute means to give help."],
  ["Who makes rules at school?", "The principal and teachers", ["Only the youngest", "Nobody"], "People who lead the school make school rules."],
  ["Who makes decisions for a family?", "The adults who care for you", ["The family pet", "A stranger"], "Caregivers make many family decisions."],
  ["Who helps make decisions for a city or town?", "The mayor and council", ["The bus driver only", "A kitten"], "Leaders make decisions that affect the people there."],
  ["Who helps keep traffic safe at a crosswalk?", "A crossing guard", ["A librarian", "A baker"], "A crossing guard makes a decision to stop traffic."],
  ["If you share your snack, you are…", "being kind", ["being greedy", "being late"], "Sharing is kind."],
  ["Which is a way to be a good friend at school?", "Invite someone to play", ["Say no to everyone", "Hide from everyone"], "We help others feel they belong."],
  ["Which belongs to you?", "your own backpack", ["a friend's lunch", "the teacher's pen"], "Respect what is yours and others'."],
  ["What can you say if you borrowed a pencil?", "Thank you!", ["Mine!", "Boo!"], "We say thanks."],
  ["You see someone drop litter. A good choice is…", "pick it up and put it in a bin", ["laugh", "walk on"], "Caring for the school is everyone's job.", true],
  ["Who in your community makes decisions that touch your life?", "The mayor and the council", ["A kitten", "A kite"], "Leaders in your community choose things like roads and parks.", true],
];

const CANADA_DAYS: Q[] = [
  ["What country do you live in?", "Canada", ["Mexico", "Japan"], "We live in Canada."],
  ["Canada is a…", "country", ["province", "town"], "A country is bigger than a province."],
  ["Which flag is the flag of Canada?", "red and white with a maple leaf", ["blue with a star", "green with a moon"], "The Canadian flag has a red maple leaf."],
  ["Canada's birthday is on…", "July 1", ["December 25", "January 2"], "Canada Day is July 1."],
  ["On Canada Day, many people…", "celebrate with parades and fireworks", ["stay silent", "go to bed at noon"], "Canada Day is a day to celebrate."],
  ["Remembrance Day is a time to think about…", "peace and war", ["snow days", "birthdays"], "We remember people who have served."],
  ["On Remembrance Day many people wear…", "a red poppy", ["a green hat", "a blue mask"], "The poppy reminds us to remember."],
  ["When is Remembrance Day?", "November 11", ["July 1", "March 3"], "We pause on the 11th of November."],
  ["On Remembrance Day we can be…", "quiet and respectful", ["loud and silly", "asleep"], "Respect and quiet show we remember."],
  ["Earth Day is a day to…", "take care of the Earth", ["eat candy", "sleep in"], "Earth Day is about caring for our planet."],
  ["Which day comes the same time every year?", "a birthday", ["a surprise storm", "a lost mitten"], "A repeating day or event is a pattern."],
  ["Which is a repeating event in a school?", "the morning song", ["a once-only rainbow", "a lost hat"], "We do it each day."],
  ["Which of these is a class routine?", "circle time every morning", ["a one-time fire drill that never happens", "a surprise visitor"], "A routine is something done the same way again and again."],
  ["Many families celebrate in different ways. This means celebrations are…", "diverse", ["boring", "the same for everyone"], "People celebrate many different things in many ways."],
  ["Which is a celebration some families have?", "a birthday party", ["a flat tire", "a rainy Monday"], "Birthdays are celebrated by many people."],
  ["Some families celebrate Diwali, Eid, Christmas or Lunar New Year. This shows…", "people celebrate in different ways", ["everyone celebrates the same", "nobody celebrates"], "Canada has many cultures and celebrations."],
  ["Is it okay if a friend's family celebrates something yours doesn't?", "Yes, people have different celebrations", ["No, it is wrong", "Only teachers can say"], "We can be curious and respectful."],
  ["What can you do when a friend tells you about their celebration?", "Listen and ask kind questions", ["Make fun of it", "Leave"], "Learning about others helps us all belong."],
  ["What do many people do on Canada Day?", "wear red and white", ["wear all black", "stay inside all day"], "Red and white are Canada's colours."],
  ["The maple leaf is a symbol of…", "Canada", ["Mexico", "the Moon"], "It is on Canada's flag."],
  ["Which is a Canadian animal?", "beaver", ["kangaroo", "panda"], "The beaver is a symbol of Canada."],
  ["Which tells you that you live in Canada?", "The flag has a maple leaf", ["There is a kangaroo", "You see a pyramid"], "Canada's flag and symbols tell us."],
  ["Which words go with Canada Day?", "birthday of Canada", ["Groundhog", "Valentine"], "Canada Day is Canada's birthday."],
  ["Which sentence is true?", "I live in Canada.", ["Canada lives in me.", "Canada is a person."], "Canada is a country, and we live in it.", true],
  ["Why is a poppy red?", "to help us remember", ["to match a flag", "just because"], "People wear a red poppy as a sign of remembering.", true],
  ["Which tells about both Canada Day and Remembrance Day?", "Both are days we mark every year", ["Both are in winter", "Both are the same"], "They repeat each year.", true],
];

const TIME_PAST: Q[] = [
  ["If today is Tuesday, yesterday was…", "Monday", ["Wednesday", "Friday"], "Yesterday is the day before."],
  ["If today is Tuesday, tomorrow will be…", "Wednesday", ["Monday", "Sunday"], "Tomorrow is the day after."],
  ["When you wake up it is…", "morning", ["midnight", "evening"], "Mornings are early in the day."],
  ["You have dinner in the…", "evening", ["morning", "night time only"], "Dinner is often in the evening."],
  ["Which word means the day before today?", "yesterday", ["tomorrow", "someday"], "Yesterday has already happened."],
  ["Which word means the day after today?", "tomorrow", ["yesterday", "last year"], "Tomorrow comes next."],
  ["Which is about today?", "I am at school today.", ["I was a baby long ago.", "I will be old someday."], "Today is now."],
  ["Which happened in the past?", "I had breakfast this morning.", ["I will go to sleep tonight.", "I am tying my shoes."], "The past is over."],
  ["Which will happen in the future?", "I will have lunch later.", ["I had lunch.", "I ate my snack."], "The future has not happened yet."],
  ["Put in order: wake up, eat breakfast, go to school. What comes first?", "wake up", ["go to school", "eat breakfast"], "Waking up comes first."],
  ["Put in order: first, next, last. Which word is the end?", "last", ["first", "next"], "Last is at the end."],
  ["Which word tells what comes before?", "first", ["last", "later"], "First is the start."],
  ["Which word tells what comes after?", "then", ["first", "start"], "Then comes next."],
  ["Which word tells a long time ago?", "past", ["future", "now"], "The past is before now."],
  ["Which word tells what is happening now?", "present", ["past", "future"], "Present means now."],
  ["Grandparents can tell us what life was like…", "a long time ago", ["tomorrow", "never"], "Grandparents and Elders share stories of the past."],
  ["An Elder tells you a story about the past. You can…", "listen and learn", ["cover your ears", "walk away"], "We can learn from stories of the past."],
  ["Why do people tell stories of the past?", "So we can learn from them", ["To make us sleepy", "Because they forgot"], "Stories help us remember and learn."],
  ["You can learn about the past from…", "stories, photos and old things", ["only the future", "nothing"], "People share the past in many ways."],
  ["An old photo shows your family long ago. It is…", "from the past", ["from tomorrow", "from the future"], "Photos help us remember."],
  ["You are interested in the past when you…", "ask about old times", ["don't want to know", "say it's boring"], "Curiosity about stories is a good thing."],
  ["Which is a kind way to show interest in a story of the past?", "Ask a question", ["Interrupt", "Look away"], "Listening and asking show you care."],
  ["Tell a story in order: the dog woke up, he ate, he went out. Which was last?", "he went out", ["the dog woke up", "he ate"], "Say what happened in order."],
  ["What can you say to tell about your day in order?", "First I got up. Then I got dressed.", ["Dressed then up first.", "I the day."], "Tell it in the order it happened."],
  ["Which words tell time?", "morning, noon, night", ["blue, red, green", "dog, cat, bird"], "These are words for parts of the day.", true],
  ["Your birthday was last week. It is in the…", "past", ["future", "present"], "It already happened.", true],
  ["Your field trip is next week. It is in the…", "future", ["past", "yesterday"], "It has not happened yet.", true],
];

const COMMUNICATE: Q[] = [
  ["Which is a way to communicate with a smile?", "with your face", ["with your feet", "with a spoon"], "A smile tells how you feel."],
  ["A song can tell…", "a feeling or story", ["the time", "your height"], "Songs are a way to communicate."],
  ["Dancing is a way to…", "show an idea or feeling", ["fill a cup", "tie a shoe"], "People dance to tell a story or share feelings."],
  ["Drawing is a way to…", "share an idea", ["stop talking", "turn off lights"], "Pictures can share ideas."],
  ["Waving hello is…", "body language", ["a song", "a story"], "Our bodies can say hello."],
  ["Crossed arms and a frown might mean someone is…", "upset", ["very happy", "sleeping"], "Faces and bodies give clues."],
  ["A big smile and open arms might mean someone is…", "welcoming", ["scared", "angry"], "Body language can be friendly."],
  ["Some people communicate with their hands. This is called…", "sign language", ["tying knots", "clapping"], "Sign language uses hands and faces."],
  ["Which is a way to say “thank you” without words?", "Smile and nod", ["Frown", "Turn away"], "A nod and smile can say thanks."],
  ["A nod usually means…", "yes", ["no", "maybe snow"], "In many places, nodding means yes."],
  ["Shaking your head usually means…", "no", ["yes", "hello"], "Shaking your head means no."],
  ["A thumbs up usually means…", "good", ["bad", "go away"], "Thumbs up means “good”."],
  ["To listen well you can…", "look at the person and be quiet", ["talk loudly", "cover your ears"], "Active listening is calm and focused."],
  ["When a friend tells you something, you show you're listening by…", "nodding and looking at them", ["playing with your shoe", "singing"], "Listening is more than hearing."],
  ["Which is a respectful way to speak?", "Please can I have a turn?", ["Gimme that!", "Move it!"], "Respectful language is kind."],
  ["Which is a respectful thing to say if you disagree?", "I think something different.", ["You are silly.", "That's dumb."], "We disagree without being unkind."],
  ["Which words are unkind?", "You can't play.", ["Want to play?", "Come join us."], "Kind words invite people in."],
  ["If you want a friend to let you play, you can say…", "Can I play with you?", ["I'm taking it.", "Get out of my way."], "Ask nicely."],
  ["Why do we give reasons for our ideas?", "So people understand them", ["To confuse people", "Because we have to shout"], "A reason tells why."],
  ["Which is a reason?", "I like the park because it has swings.", ["I like the park.", "Swings."], "A reason uses “because”."],
  ["Why do you wear mittens in winter? A good reason is…", "to keep my hands warm", ["because", "to be loud"], "Reasons explain why."],
  ["You can share information with a picture. This is…", "visual", ["a smell", "a taste"], "We see pictures."],
  ["You can tell a story with puppets. This is a way to share…", "ideas in a fun way", ["only numbers", "only maps"], "Puppets can show ideas with objects."],
  ["Gestures, stories and art can share messages without words. This is…", "non-verbal communication", ["a lost language", "a machine"], "Communication can happen without words.", true],
  ["Which does not use words?", "a smile", ["a story book", "a song with words"], "Smiles use face, not words.", true],
  ["You want to tell your class about your pet. You can…", "show a picture and talk", ["whisper to a wall", "hide"], "Visuals help your talk.", true],
];

const MAPS: Q[] = [
  ["A map shows…", "where places are", ["what you ate", "how old you are"], "A map is a picture of a place from above."],
  ["A globe is shaped like a…", "ball", ["box", "can"], "A globe is a model of the Earth."],
  ["A globe shows the whole…", "Earth", ["house", "playground only"], "A globe is a small model of the Earth."],
  ["Which is a model of a real place?", "a toy farm", ["a real farm", "a cloud"], "Models, maps and globes represent actual places."],
  ["A map of your classroom can show…", "where the desks are", ["what lunch is", "the Moon"], "A map shows where things are."],
  ["Which of these is a map?", "a picture of streets from above", ["a song", "a clock"], "A map shows places seen from above."],
  ["I live near the park. The park is a…", "landmark", ["moon", "toy"], "A landmark is a place you know that helps you find your way."],
  ["Which is a landmark in your town?", "a school", ["a cloud", "a daydream"], "Landmarks are easy-to-find places."],
  ["Your home is near the school. The school helps you tell…", "where your home is", ["what time it is", "what to eat"], "Landmarks help us describe where we live."],
  ["Which tells where you live?", "the name of your town", ["the name of your pet", "your age"], "Your community has a name."],
  ["Which words describe where you live?", "next to the library", ["quickly and loudly", "blue and green"], "Say what is near your home."],
  ["The place you live might be a village, a town, a city or a…", "First Nation community", ["pond", "planet"], "People live in many kinds of communities."],
  ["People in other parts of the world live in homes that are…", "not all the same", ["all identical", "only igloos"], "Homes can be different around the world."],
  ["All people need food, water and a place to live. Some meet needs in…", "different ways", ["the same way", "no way"], "People around the world meet needs differently."],
  ["In some places people get water from a well. In others they get it from a…", "tap", ["rainbow", "mailbox"], "People get water in different ways."],
  ["It is cold where some people live, so they wear…", "warm coats", ["swimsuits", "sandals only"], "The place affects what we wear."],
  ["In a hot place, people might wear…", "light clothes", ["snow pants", "winter boots"], "The weather changes our clothes."],
  ["In winter in Manitoba we often wear…", "warm boots and mittens", ["swim trunks", "sandals"], "The natural environment affects what we wear."],
  ["When it rains we might…", "wear a raincoat", ["wear a snow hat in July", "go skiing"], "Weather affects what we do."],
  ["When the lake freezes, some people can…", "go ice fishing or skating", ["swim", "sail"], "The environment changes what we do in a season."],
  ["On the prairie, a lot of people work in…", "farming", ["deep sea diving", "mountain skiing"], "Farming is a big part of life on the prairie."],
  ["Wanting to learn about people far away shows you are…", "curious about the world", ["bored", "angry"], "Interest in the wider world is great."],
  ["Which helps you learn about a place far away?", "a book or a map", ["a pillow", "a ball"], "Maps and books can show faraway places."],
  ["A faraway friend lives in another country. How can you meet?", "a video call or a letter", ["by tapping your toes", "never"], "People stay in touch from far away.", true],
  ["In your bedroom, where is your bed?", "against the wall", ["on the roof", "outside"], "A map of a room shows where things are.", true],
  ["Which is the best use of a globe?", "To see countries and oceans", ["To tell time", "To eat lunch"], "A globe shows the shapes of land and water.", true],
];

const TOGETHER: Q[] = [
  ["Taking turns is a way to…", "work together", ["fight", "hide"], "Taking turns is fair."],
  ["Two children want the same swing. A fair idea is to…", "take turns", ["fight", "break it"], "Taking turns is fair."],
  ["Sharing a table with a friend means…", "making space for them", ["taking all of it", "leaving"], "Sharing space is cooperation."],
  ["Which shows cooperation?", "building a tower together", ["knocking a friend's tower", "walking away"], "Cooperation means working together."],
  ["Which is how to include a new friend?", "Invite them to play", ["Ignore them", "Tell them to go"], "Including people helps them belong."],
  ["A friend is crying. What could you do?", "Ask if they are okay", ["Laugh", "Run away"], "Consider others' needs."],
  ["A friend is hungry and you have an extra snack. You might…", "offer to share", ["hide it", "eat it quickly"], "Sharing helps."],
  ["Your friend can't reach the shelf. You can…", "help get the book", ["tease them", "ignore them"], "Helping is kind."],
  ["What does it mean to be fair?", "Treat everyone the same way", ["Only help your best friend", "Let only some people play"], "Fair means everyone gets a turn."],
  ["Which is fair?", "Everyone gets a turn", ["Only the loudest gets a turn", "Only tall kids play"], "Fairness means everyone."],
  ["Which is respectful?", "Using polite words", ["Name calling", "Pushing"], "Be respectful."],
  ["Everyone is good at different things. Your friend is a great runner. You can…", "cheer for them", ["call them names", "ignore them"], "We value others' talents."],
  ["You are good at drawing. That is a…", "talent or strength", ["problem", "mistake"], "Everyone has special strengths."],
  ["A special talent might be…", "singing, drawing or running fast", ["being rude", "being lost"], "Talents are things we do well."],
  ["It is okay if your friend likes something different. This is…", "respecting differences", ["a rule", "a mistake"], "People have different interests."],
  ["Valuing others' interests means…", "being glad they like their own things", ["telling them they're wrong", "making them stop"], "Different interests make our class interesting."],
  ["If you push a friend, what might happen?", "They might get hurt or upset", ["Nothing ever", "They'll give you a prize"], "Our actions have consequences."],
  ["If you tidy up your toys, what happens?", "Others can walk safely", ["They vanish", "Nothing at all"], "Good choices make good results."],
  ["If you share a toy, how might your friend feel?", "happy", ["sad and angry", "tired"], "Sharing leads to good feelings."],
  ["If you don't wear a coat in the cold, you might…", "feel cold", ["feel warm", "float away"], "A choice has a consequence."],
  ["You said “I'm sorry” after bumping a friend. This is…", "a kind choice", ["a rule", "a punishment"], "An apology can make things better."],
  ["Which is the best thing to do after you hurt someone's feelings?", "Say sorry and try to help", ["Run off", "Say it was funny"], "Fix it with kindness."],
  ["Who makes sure everyone gets a turn when you play a game?", "all of us", ["only the loudest", "nobody"], "Fair play is everyone's job."],
  ["Which words make others feel welcome?", "Come play with us!", ["No way.", "Go away."], "Kind words matter."],
  ["Working together means…", "everyone helps", ["one person does it all", "nobody helps"], "Teamwork shares the work.", true],
  ["If you break a rule, what is a good choice afterward?", "Tell the truth and fix it", ["Hide it", "Blame someone else"], "Being honest helps you do better.", true],
  ["Which is a good choice when two children want different games?", "Take turns choosing", ["Argue until one gives up", "Stop playing"], "Taking turns solves it.", true],
];

const FIND_OUT: Q[] = [
  ["How can you learn about a bird?", "Watch it and look at books", ["Cover your eyes", "Sleep"], "Gather information by looking, listening and reading."],
  ["Which source can tell you about animals?", "a book with pictures", ["a pillow", "a ball"], "Books give us information."],
  ["Which is a place to find information?", "a library", ["a sandbox only", "a closet only"], "Libraries have many books."],
  ["An Elder can tell you…", "stories and what they know", ["nothing", "only the time"], "People are sources of information too."],
  ["You can listen to a story. This is an…", "oral source", ["silent source", "smell"], "Oral means spoken."],
  ["A picture is a…", "visual source", ["sound source", "smell source"], "Visual means you can see it."],
  ["A toy plane is a…", "material source", ["story", "song"], "A real object can tell us how things look and work."],
  ["Printed words in a book are a…", "print source", ["sound source", "tasty source"], "Print means words on paper."],
  ["Sorting means putting things into…", "groups", ["pockets only", "holes"], "Group things that go together."],
  ["Sort these: apple, banana, hammer. What does NOT belong?", "hammer", ["apple", "banana"], "Apples and bananas are fruit."],
  ["How could you sort buttons?", "by colour or by size", ["by taste", "by noise"], "Pick something to sort by."],
  ["Sort these: dog, cat, car. Which does NOT belong with animals?", "car", ["dog", "cat"], "Dogs and cats are animals."],
  ["You sort shoes by who wears them. Which group is for you?", "Kids' shoes", ["Grown-ups' shoes", "Pets' shoes"], "Choose the rule and sort."],
  ["A tool is something that…", "helps you do a job", ["makes noise only", "is a toy only"], "Tools help us work."],
  ["Which tool is used to look at something small?", "a magnifying glass", ["a spoon", "a bell"], "It helps us see details."],
  ["Which tool shows pictures of faraway places?", "a computer or tablet", ["a pillow", "a fork"], "Technologies can show information."],
  ["Which tool helps to measure how long a table is?", "a ruler", ["a tissue", "a clock"], "A ruler measures length."],
  ["Which tool helps you take a picture?", "a camera", ["a cup", "a mop"], "A camera captures pictures."],
  ["To compare two things you…", "look at how they are the same and different", ["only look at one", "ignore them"], "Comparing means noticing."],
  ["Compare a cat and a dog. How are they alike?", "Both are animals with fur", ["Both can fly", "Both are plants"], "Look for what they share."],
  ["Compare a ball and a box. One difference is…", "the ball rolls", ["both roll", "both are the same shape"], "Compare shapes."],
  ["Compare summer and winter. One difference is…", "winter is colder", ["winter is hotter", "winter has no days"], "Winter is usually colder."],
  ["Which question can help you find out about a pond?", "What lives in the pond?", ["What is 2 + 2?", "Where's my lunch?"], "A good question helps you investigate."],
  ["Which question uses comparing?", "Which is bigger?", ["What is your name?", "When is lunch?"], "Bigger and smaller are comparisons."],
  ["After looking at a picture, you can tell your class…", "what you found out", ["nothing", "to be quiet"], "Share what you learned.", true],
  ["You want to know what a robin eats. The best way to find out is to…", "watch robins and read a book", ["guess", "ask a rock"], "Use sources.", true],
  ["You have 3 coloured blocks: 2 red, 1 blue. Sorting by colour makes…", "two groups", ["one group", "five groups"], "Red go together, blue goes alone.", true],
];

export const socialUnits = [
  bankUnit({
    id: "mb-k-jobs-and-rules",
    title: "My Jobs, Rules & Leaders",
    emoji: "🧹",
    blurb: "Jobs at home and school, rules, sharing and leaders.",
    parentNote:
      "Practises responsibilities at home and in school, respecting the rules of the classroom and playground, respecting property, sharing, helping, and who makes decisions that affect our lives.",
    standards: ["0-KC-001, 0-VP-006, 0-VE-007, 0-VE-008, 0-VC-001, 0-KP-023", "responsibilities, rules, respect for property, sharing, contributing and decision makers"],
    items: RESPONSIBLE,
  }),
  bankUnit({
    id: "mb-k-canada-and-celebrations",
    title: "Canada & Celebrations",
    emoji: "🎉",
    blurb: "Our country, repeating days and many ways to celebrate.",
    parentNote:
      "Practises that we live in Canada, Remembrance Day as a time to think about peace and war, repeating events such as Canada Day and Earth Day, and the many different ways families celebrate. Encourage curiosity and respect about other families' celebrations.",
    standards: ["0-KC-005, 0-KC-006, 0-KH-017, 0-KI-011", "living in Canada, Remembrance Day, repeating events and diverse celebrations"],
    items: CANADA_DAYS,
  }),
  bankUnit({
    id: "mb-k-yesterday-today-tomorrow",
    title: "Yesterday, Today, Tomorrow",
    emoji: "📅",
    blurb: "Time words, putting events in order and stories of the past.",
    parentNote:
      "Practises yesterday, today and tomorrow, words that describe parts of a day or order of events (first, then, last), telling events in order, and learning from stories of the past told by family and Elders.",
    standards: ["0-KH-018, 0-KH-019, 0-VH-004, 0-S-202, 0-S-404", "yesterday, today and tomorrow, time words, stories of the past and telling events in order"],
    items: TIME_PAST,
  }),
  bankUnit({
    id: "mb-k-ways-to-communicate",
    title: "Ways to Communicate",
    emoji: "💬",
    blurb: "Words, faces, art and kind ways to speak and listen.",
    parentNote:
      "Practises the many ways people communicate (art, song, dance, facial expression, body language, sign language), active listening, respectful language, giving reasons, and sharing information with pictures or objects. Indigenous cultures have many different ways to communicate, and this unit only names the idea.",
    standards: ["0-KI-010, 0-KI-010A, 0-S-400, 0-S-401, 0-S-402, 0-S-403", "ways people communicate, listening, respectful language, giving reasons and sharing ideas"],
    items: COMMUNICATE,
  }),
  bankUnit({
    id: "mb-k-maps-and-the-world",
    title: "Maps, Places & the World",
    emoji: "🗺️",
    blurb: "Maps, globes, landmarks and life in different places.",
    parentNote:
      "Practises maps, globes and models as pictures of real places, describing where home is using landmarks, how the natural environment (weather, seasons, land) shapes what we wear and do, and that people around the world meet their needs in different ways.",
    standards: ["0-KL-013, 0-KL-014, 0-KL-016, 0-KG-021, 0-VG-005", "maps and globes, where we live, how the environment affects daily life and life in other parts of the world"],
    items: MAPS,
  }),
  bankUnit({
    id: "mb-k-working-together",
    title: "Working & Playing Together",
    emoji: "🤝",
    blurb: "Turns, fairness, strengths and good choices.",
    parentNote:
      "Practises cooperating, taking turns, including others, considering others' needs, valuing each person's talents and interests, and noticing the results of our choices.",
    standards: ["0-S-100, 0-S-101, 0-S-102, 0-S-301, 0-VI-002, 0-VI-002A", "cooperation, fairness, respect for others' interests and strengths, and the results of our choices"],
    items: TOGETHER,
  }),
  bankUnit({
    id: "mb-k-find-out",
    title: "Find Out & Sort",
    emoji: "🔎",
    blurb: "Find information, sort it and compare.",
    parentNote:
      "Practises finding information in spoken, picture, object and print sources, sorting things by one rule, using tools such as a ruler or magnifying glass, and comparing things by how they are alike and different.",
    standards: ["0-S-200, 0-S-201, 0-S-203, 0-S-300", "gathering information from sources, sorting, using tools and comparing"],
    items: FIND_OUT,
  }),
];
