import { bankUnit, type Q } from "../own";

// Kindergarten science, outcomes not covered elsewhere: measuring (SCI.K.C.2), patterns of the Sun and Moon (SCI.K.E.3),
// technologies and careers (SCI.K.D.2, SCI.K.C.5, SCI.K.B.1) and caring for nature (SCI.K.C.1, SCI.K.A.1).

const MEASURE: Q[] = [
  ["Which pencil is longer?", "the one that reaches farther", ["the one that is hidden", "the one that is red"], "Longer means it stretches farther."],
  ["A snake is long. A worm is…", "shorter", ["longer", "heavier"], "Compare how far each one stretches."],
  ["You measure a book with paper clips. You count how many fit in a…", "row", ["circle", "cloud"], "Place the clips end to end in a row."],
  ["A book is 6 paper clips long. A pencil is 4 paper clips long. Which is longer?", "the book", ["the pencil", "they are the same"], "Six is more than four."],
  ["Which tool can you use to measure the length of a desk?", "your hands", ["a spoon of water", "a clock"], "Hands are a non-standard measure."],
  ["Which is heavier?", "a rock", ["a feather", "a leaf"], "Hold them in your hands. The rock feels like more."],
  ["Which is lighter?", "a feather", ["a rock", "a brick"], "Lighter means it weighs less."],
  ["Which one is the heaviest?", "a big book", ["a crayon", "a leaf"], "Think of which would be hardest to lift."],
  ["On a balance, the side that goes down is…", "heavier", ["lighter", "empty"], "The heavier side goes down."],
  ["On a balance, the side that goes up is…", "lighter", ["heavier", "the longest"], "The lighter side goes up."],
  ["Which of these is a tool to tell time?", "a clock", ["a spoon", "a ruler of snow"], "A clock shows the time."],
  ["Which tool helps you see the days of the month?", "a calendar", ["a scale", "a cup"], "A calendar lists days and months."],
  ["Which takes a longer time?", "growing a plant", ["clapping once", "blinking"], "Plants take days or weeks to grow."],
  ["Which takes a shorter time?", "a sneeze", ["a bike ride", "a sleep"], "A sneeze is over fast."],
  ["Which takes longer?", "walking to school", ["blinking", "clapping once"], "Walking takes minutes."],
  ["Which words compare how long things are?", "longer and shorter", ["louder and softer", "warmer and cooler"], "Longer and shorter tell about length."],
  ["Which words compare how heavy things are?", "heavier and lighter", ["longer and shorter", "faster and slower"], "Heavier and lighter tell about mass."],
  ["Shortest to longest: crayon, ruler, broom. Which is last?", "broom", ["crayon", "ruler"], "The broom is the longest."],
  ["Lightest to heaviest: feather, book, rock. Which is first?", "a feather", ["a rock", "a book"], "The feather is lightest."],
  ["You use coins to measure the width of a book. You count the…", "coins", ["colours", "sounds"], "Count how many coins fit across."],
  ["Which sorts things by just one attribute?", "all the long ones in a group", ["long, red and heavy ones all together", "any three things"], "Sort by one thing, such as length."],
  ["Which is a way to compare a block and a cup?", "Hold one in each hand", ["Close your eyes", "Walk away"], "Hands help you feel which is heavier."],
  ["A ribbon is 5 hands long. A rope is 8 hands long. Which is shorter?", "the ribbon", ["the rope", "they are the same"], "Five is less than eight."],
  ["Which is the best word: a tall tree is…", "longer than a shrub", ["lighter than a shrub", "quieter than a shrub"], "Tall and long both talk about length."],
  ["You use your senses to measure. Which sense tells you how heavy something feels?", "touch", ["smell", "hearing"], "You feel weight with your hands.", true],
  ["Which unit could you use to measure a short time?", "claps", ["paper clips", "coins"], "You can count claps to compare time.", true],
  ["Two ropes are both measured with coins. A has 5 coins, B has 7. Which is longer?", "B", ["A", "same"], "Seven is more than five.", true],
];

const SUN_MOON: Q[] = [
  ["When do we see the Sun in the sky?", "In the daytime", ["At midnight", "Only at night"], "The Sun shines in the day."],
  ["Where is the Sun in the morning?", "Low in the sky", ["Straight overhead", "Below your feet"], "The Sun rises early in the morning."],
  ["Where is the Sun at noon?", "High in the sky", ["Not visible", "Under the ground"], "The Sun is highest in the middle of the day."],
  ["Where is the Sun in the evening?", "Going down", ["Rising", "Right above you"], "The Sun sets at the end of the day."],
  ["The Sun seems to move across the sky from…", "morning to evening", ["night to night", "evening to night only"], "It rises and sets each day."],
  ["Your shadow is longest when the Sun is…", "low in the sky", ["high in the sky", "behind a cloud"], "Low Sun makes long shadows."],
  ["Your shadow is shortest when the Sun is…", "high in the sky", ["low in the sky", "going down"], "High Sun makes short shadows."],
  ["What do we see in the sky at night?", "the Moon and stars", ["the Sun", "a rainbow"], "The Moon and stars are seen at night."],
  ["The Moon looks like it changes…", "shape", ["colour to purple", "its name"], "We see different parts of the Moon lit up."],
  ["A full Moon looks like…", "a bright circle", ["a thin curve", "nothing at all"], "A full Moon is round."],
  ["A new Moon is…", "hard to see", ["very bright", "a big circle"], "At new Moon we can't see the lit side."],
  ["A thin curved Moon is called a…", "crescent", ["circle", "cone"], "A crescent is thin and curved."],
  ["The Moon's shape changes over…", "many days", ["one hour", "one second"], "It takes about a month to go through the shapes."],
  ["How often does a full Moon happen?", "about once a month", ["every day", "once in ten years"], "About every 29 days."],
  ["Which happens every day?", "The Sun rises and sets", ["It snows", "A full Moon"], "The Sun rises and sets daily."],
  ["A pattern is something that…", "repeats", ["never happens", "happens once"], "Patterns repeat."],
  ["The Sun going up and down is a…", "pattern", ["mistake", "surprise"], "It happens again each day."],
  ["Day and night happen in a…", "cycle", ["line", "square"], "A cycle goes round and round."],
  ["What do you see in the sky at 3 o'clock in the afternoon?", "the Sun", ["a full Moon only", "stars only"], "The Sun is up in the afternoon."],
  ["Which is a safe thing to do when the Sun is bright?", "Wear a hat", ["Look at the Sun", "Stare at it with a telescope"], "Never look straight at the Sun."],
  ["When the Sun is out in the middle of the day, you might…", "find shade", ["wear a snowsuit", "turn on a lamp"], "Shade keeps you cool."],
  ["In the morning your shadow points…", "away from the Sun", ["toward the Sun", "straight up"], "Shadows fall opposite the Sun."],
  ["Which comes first in a day?", "sunrise", ["sunset", "midnight"], "A day starts with sunrise."],
  ["Which comes after sunset?", "night", ["morning", "noon"], "Night follows evening."],
  ["The Moon does not make its own light. It…", "reflects light from the Sun", ["is a lamp", "is on fire"], "We see the Moon because sunlight bounces off it.", true],
  ["Which is the right order in a day: noon, sunrise, sunset?", "sunrise, noon, sunset", ["noon, sunrise, sunset", "sunset, sunrise, noon"], "The Sun goes up, stays high, then sets.", true],
];

const PEOPLE_SCIENCE: Q[] = [
  ["Who studies animals?", "a biologist", ["a baker", "a pilot"], "A biologist learns about living things."],
  ["Who studies the stars and planets?", "an astronomer", ["a farmer", "a nurse"], "Astronomers look at the sky."],
  ["Who grows food on a farm?", "a farmer", ["a firefighter", "a dentist"], "Farmers use science to grow plants and raise animals."],
  ["Who helps sick people feel better?", "a doctor", ["an astronomer", "a baker"], "Doctors use science to help us stay healthy."],
  ["Who puts out fires?", "a firefighter", ["a farmer", "a teacher"], "Firefighters know about fire and safety."],
  ["Who studies rocks?", "a geoscientist", ["a baker", "a singer"], "Geoscientists study Earth and rocks."],
  ["Who might look for rocks and gems?", "a rock collector", ["a dancer", "a swimmer"], "Rock collecting is a hobby with science in it."],
  ["Gardening is a hobby that uses…", "science", ["nothing", "only luck"], "Gardeners learn about soil, sun and water."],
  ["Birdwatching is a way to…", "learn about birds", ["build a nest", "fix a car"], "Watching helps us notice birds."],
  ["A teacher can help you learn…", "science ideas", ["only maths", "nothing"], "Teachers share science too."],
  ["A technology is something people…", "made to help", ["found in a cave", "wished for"], "People create tools and technologies."],
  ["Which is a technology?", "scissors", ["a rock", "a tree"], "Scissors were made by people to cut."],
  ["Which helps you see far away?", "binoculars", ["a spoon", "a cup"], "Binoculars make faraway things look closer."],
  ["Which helps you see tiny things?", "a magnifying glass", ["a hammer", "a drum"], "A magnifying glass makes things look bigger."],
  ["Which tool did people make to keep food cold?", "a fridge", ["a stone", "a stick"], "A fridge is a technology we use every day."],
  ["Which tool did people make to help us write?", "a pencil", ["a leaf", "a cloud"], "A pencil is a tool for writing."],
  ["A wheel helps people…", "move things easily", ["swim", "sleep"], "Wheels roll."],
  ["Which was made to help us tell time?", "a clock", ["a puddle", "a pebble"], "A clock is a technology."],
  ["Which was made to keep us dry in rain?", "an umbrella", ["a feather", "a banana"], "An umbrella is a technology."],
  ["Why do people create new tools?", "To meet a need", ["For no reason", "To make things worse"], "Technologies give us things that are needed or useful."],
  ["A ramp helps people…", "roll a wheelchair up", ["bake bread", "grow flowers"], "A ramp is a technology that helps."],
  ["Which of these is NOT made by people?", "a pinecone", ["a spoon", "a bicycle"], "A pinecone grows on a tree."],
  ["Which is a toy that was made by people?", "a kite", ["a puddle", "a cloud"], "Kites were made for fun."],
  ["Everyone can do science. This means…", "you can ask questions and find out", ["only grown-ups can", "only people with labs can"], "Anyone can be curious.", true],
  ["Wondering why the sky is blue is…", "being a curious scientist", ["silly", "not allowed"], "Curious questions help us learn.", true],
  ["You can be a scientist when you…", "watch and ask questions", ["never look", "only read"], "Science begins with noticing.", true],
];

const NATURE: Q[] = [
  ["Which action takes care of a small habitat?", "Don't trample the plants", ["Pull up all the plants", "Throw trash there"], "Keep habitats safe for the animals that live there."],
  ["A habitat is…", "a place where living things live", ["a place for cars", "a kind of toy"], "A habitat gives plants and animals what they need."],
  ["How can you cut down on snack waste?", "Bring a reusable container", ["Throw snacks on the ground", "Use extra bags"], "Reusable containers make less garbage."],
  ["Where does litter belong?", "In a bin", ["In a pond", "On the grass"], "Bins keep nature clean."],
  ["Which helps a plant grow?", "Water and light", ["Loud music only", "Nothing"], "Plants need water and light."],
  ["How can you care for a classroom plant?", "Give it water", ["Hide it in a drawer", "Pull its leaves"], "Watering helps the plant live."],
  ["How do you treat a classroom pet?", "Gently and with food and water", ["Roughly", "Never feed it"], "Caring means gentle, kind choices."],
  ["Observing the Sun's path can help you choose…", "shade or a hat", ["a snowsuit", "a swimsuit in a blizzard"], "On a bright day, shade helps."],
  ["You find an old toy. What could you do?", "Reuse it or give it to someone", ["Break it", "Throw it in the lake"], "Reusing keeps things out of the garbage."],
  ["Sorting objects by their properties helps us decide…", "how to reuse them", ["how to lose them", "how loud they are"], "Sorting shows what each can be used for."],
  ["Which is a good way to save paper?", "Use both sides", ["Rip it up", "Use new sheets for every dot"], "Reusing paper helps the Earth."],
  ["Which keeps water clean?", "Keep litter out of it", ["Throw trash in", "Pour paint in"], "Clean water is important for living things."],
  ["Which is a way to help birds in winter?", "Put out a bird feeder", ["Scare them", "Take their nests"], "Feeders can help birds in cold weather."],
  ["Which is a good thing to do in a park?", "Leave it clean", ["Drop wrappers", "Break branches"], "Take your trash with you."],
  ["Saving water is good because…", "all living things need water", ["it is fun to waste", "no one uses it"], "Water is precious for plants and animals."],
  ["Turning off a tap while brushing teeth…", "saves water", ["wastes water", "makes noise"], "Less water goes down the drain."],
  ["Which of these is a living thing to protect?", "a tree", ["a plastic bag", "a soda can"], "Trees are living things."],
  ["What can you do with a leaf you find?", "Look at it and put it back", ["Crush every one", "Throw it at a bird"], "We can enjoy nature and leave it be."],
  ["Many First Nations, Métis and Inuit people learn on the land. This is…", "land-based learning", ["screen learning", "bus learning"], "Learning from the land can be done by watching, listening and doing."],
  ["Learning outdoors can help us notice…", "plants, animals and weather", ["only TV shows", "only desks"], "Outside learning uses our senses."],
  ["Some Indigenous peoples watch the seasons to know when to…", "gather food and plants", ["play video games", "go to the moon"], "Watching the seasons is a way of learning from nature."],
  ["Today, many communities teach children to care for the land. This is…", "something that continues now", ["only in the past", "only in books"], "These ways of knowing are alive today."],
  ["Which is a way to listen to nature?", "Sit quietly outside", ["Shout at it", "Cover your ears"], "Quiet listening helps you notice sounds."],
  ["What can you notice when you slow down outside?", "bugs, birds and plants", ["only cars", "only walls"], "There is lots to notice in nature."],
  ["How can a school help the Earth?", "Recycle and reuse", ["Waste more", "Cut down all the trees"], "Small actions add up.", true],
  ["A puddle dries up on a sunny day. Where did the water go?", "into the air", ["into the Sun", "into the ground and gone forever"], "Warm air takes water up as vapour.", true],
  ["Caring for nature is a way to show…", "respect", ["boredom", "anger"], "Respect means caring for things around us.", true],
];

export const scienceUnits = [
  bankUnit({
    id: "mb-k-measure-it",
    title: "Measure It!",
    emoji: "📏",
    blurb: "Longer, shorter, heavier, lighter.",
    parentNote:
      "Practises comparing and ordering objects by length, mass and time using words such as longer, shorter, heavier and lighter, and using hands, paper clips or coins as measuring tools. Try measuring a table with your hands at home.",
    standards: ["SCI.K.C.2", "measuring with senses and non-standard tools, and comparing, sorting and sequencing by one attribute"],
    items: MEASURE,
  }),
  bankUnit({
    id: "mb-k-sun-and-moon",
    title: "Sun & Moon Patterns",
    emoji: "🌙",
    blurb: "How the Sun and Moon change in the sky.",
    parentNote:
      "Practises the pattern of the Sun's position through the day, how shadows change, and how the Moon seems to change shape over about a month. Remind your child never to look straight at the Sun.",
    standards: ["SCI.K.E.3", "patterns and cycles in the Sun's position and the shape of the Moon"],
    items: SUN_MOON,
  }),
  bankUnit({
    id: "mb-k-science-helpers",
    title: "Tools & Science Jobs",
    emoji: "🔭",
    blurb: "Things people make and people who use science.",
    parentNote:
      "Practises linking science to jobs and hobbies (farmer, firefighter, doctor, astronomer, rock collecting, gardening), to technologies people have made to meet needs, and to the idea that everyone can be curious and contribute to science.",
    standards: ["SCI.K.D.2, SCI.K.C.5, SCI.K.B.1", "technologies people create, careers and hobbies that use science, and belonging in science"],
    items: PEOPLE_SCIENCE,
  }),
  bankUnit({
    id: "mb-k-care-for-nature",
    title: "Caring for Nature",
    emoji: "🌱",
    blurb: "Small actions that help plants, animals and the land.",
    parentNote:
      "Practises simple actions that care for nature, such as protecting a habitat, reducing waste, reusing and caring for plants and animals, and the idea that many First Nations, Métis and Inuit communities today learn from the land. First Nations, Métis and Inuit ways of knowing differ among Nations, and this unit only introduces the idea.",
    standards: ["SCI.K.C.1, SCI.K.A.1", "taking action on a local environmental issue, and ways of learning from the land"],
    items: NATURE,
  }),
];
