import { bankUnit, type Q } from "../own";

// Kindergarten English language arts, outcomes not covered elsewhere: listening and talking (A1, D1), word parts and
// vocabulary (A2.4, A2.5, B2.7), before, during and after reading (B1, B2, B3), planning and making text (C1, C2, C3)
// and noticing our own learning (D2). Purely oral or performance outcomes are practised through "what would you do" questions.

const TALK: Q[] = [
  ["When a friend is talking, what should your ears do?", "Listen", ["Rest", "Wiggle"], "Good listeners keep their ears ready for the speaker."],
  ["When someone is talking, where should your eyes look?", "At the speaker", ["At the floor", "At the ceiling"], "Looking at the speaker shows you are listening."],
  ["A friend says, “I like red apples.” What can you say back?", "You like red apples.", ["I have a dog.", "Let's go home."], "Saying back what you heard shows you listened."],
  ["Which is a good listening body?", "Still and calm, facing the speaker", ["Turned away and wiggling", "Jumping up and down"], "A calm body helps you listen."],
  ["Your teacher is talking. What do you do if you have something to say?", "Wait for your turn", ["Shout right away", "Walk away"], "We wait until the speaker is finished."],
  ["Which word starts a question?", "Where", ["Because", "Yes"], "Where, who and what start questions."],
  ["Which is a question?", "Where is my hat?", ["My hat is red.", "I like my hat."], "A question asks something."],
  ["You want to know who is at the door. You ask…", "Who is there?", ["The door is big.", "I like doors."], "Who asks about a person."],
  ["You want to know what a bug is called. You ask…", "What is it?", ["It is a bug.", "I see it."], "What asks about a thing."],
  ["You want to find your boots. You ask…", "Where are my boots?", ["Who is my boots?", "What is my boots?"], "Where asks about a place."],
  ["Which is a whole sentence?", "I like to play.", ["like to", "play I"], "A sentence tells a whole idea."],
  ["Which sentence tells a feeling?", "I am happy.", ["The sky.", "Run fast."], "I am happy tells how you feel."],
  ["How do you ask for a turn nicely?", "May I have a turn, please?", ["Give it to me!", "It is mine!"], "Kind words and “please” are good manners."],
  ["To start a chat with a new friend you can say…", "Hi, what is your name?", ["Go away.", "Look at the floor."], "A friendly hello starts a conversation."],
  ["A friend asks, “Do you like cats?” What is a good answer?", "Yes, I like cats.", ["The bus is big.", "Blue."], "An answer should match the question."],
  ["Which feeling goes with a smile?", "happy", ["sad", "sleepy"], "A smile often shows we feel happy."],
  ["Which face shows listening?", "Calm face looking at the speaker", ["Looking at your shoes", "Making silly faces"], "Facial expressions can show we are listening."],
  ["Why is it good to share your ideas in a group?", "Everyone can learn from them", ["So nobody else can talk", "It is not good"], "Your ideas matter and help the group."],
  ["You have something to say in the circle. What do you do?", "Put up your hand quietly", ["Shout it out", "Say nothing ever"], "Everyone has a voice, and we take turns."],
  ["You are talking to a baby. Your voice should be…", "soft and gentle", ["very loud", "angry"], "We change how we talk for different people."],
  ["You are talking to an Elder or your teacher. You should…", "speak politely", ["yell", "turn your back"], "We show respect when we talk to others."],
  ["You are on the playground and a friend is far away. Your voice should be…", "louder, but friendly", ["a whisper", "silent"], "We use a bigger voice for far away, outdoors."],
  ["In the library you use…", "a quiet voice", ["a shouting voice", "a singing voice"], "We keep our voices low in a library."],
  ["Which is a good way to tell about your day?", "First I ate. Then I played.", ["Ate played first then", "Yesterday. Cat."], "Tell things in order, using words like first and then.", true],
  ["Which sentence is the clearest?", "I see a big red ball.", ["Ball see red.", "Big I ball."], "Words in a good order make an idea clear.", true],
  ["A friend looks sad. What can you say?", "Are you okay?", ["Ha ha!", "Go away."], "Listening to feelings is part of talking kindly.", true],
];

const WORDS: Q[] = [
  ["Add -s to “cat”. What word do you get?", "cats", ["cat", "cating"], "-s tells us there is more than one."],
  ["Add -s to “dog”. What word do you get?", "dogs", ["dog", "doging"], "One dog, two dogs."],
  ["Which word means more than one?", "books", ["book", "boot"], "The -s at the end means more than one."],
  ["Which word means only one?", "tree", ["trees", "treed"], "No -s means just one."],
  ["Add -ing to “jump”. What word do you get?", "jumping", ["jumps", "jumped"], "-ing means it is happening now."],
  ["Add -ing to “play”. What word do you get?", "playing", ["plays", "played"], "Play plus -ing is playing."],
  ["Which word means it is happening right now?", "walking", ["walk", "walks"], "-ing at the end tells us it is happening now."],
  ["Add un- to “happy”. What word do you get?", "unhappy", ["happily", "happy"], "Un- at the start means not."],
  ["Add un- to “lock”. What word do you get?", "unlock", ["lock", "locks"], "Unlock is the opposite of lock."],
  ["Which word means “not kind”?", "unkind", ["kinder", "kindly"], "Un- means not."],
  ["The word “unsafe” means…", "not safe", ["very safe", "safe again"], "Un- means not."],
  ["What is the small part at the end of “cats”?", "-s", ["un-", "-ing"], "The -s changes the word."],
  ["What is the small part at the start of “undo”?", "un-", ["-s", "-ing"], "Un- is at the front of the word."],
  ["Which is a fruit word?", "apple", ["chair", "truck"], "An apple is a fruit."],
  ["Which is an animal word?", "rabbit", ["pencil", "spoon"], "A rabbit is an animal."],
  ["Which is a colour word?", "yellow", ["jump", "table"], "Yellow is a colour."],
  ["Which word names a place at school?", "gym", ["kitten", "pizza"], "The gym is a place at school."],
  ["Which word does NOT belong with doctor, teacher, farmer?", "table", ["baker", "nurse"], "A table is not a person with a job."],
  ["A word for a very big dog is…", "huge", ["tiny", "quiet"], "Huge means very big."],
  ["Which word means the same as “big”?", "large", ["small", "wet"], "Large and big mean about the same."],
  ["Which word is the opposite of “hot”?", "cold", ["warm", "red"], "Hot and cold are opposites."],
  ["On a drawing, a label says “sun”. What does it tell you?", "What the picture is", ["How loud it is", "How old you are"], "A label is a word that names part of a picture."],
  ["Which word names a day of the week?", "Monday", ["April", "winter"], "Monday is a day."],
  ["A topic word for plants is…", "seed", ["wheel", "pillow"], "Seeds grow into plants."],
  ["Which words are about the weather?", "rain and wind", ["fork and plate", "chair and desk"], "Rain and wind are weather words.", true],
  ["Which word names something that grows from a seed?", "flower", ["rock", "cup"], "Flowers grow from seeds.", true],
  ["Which word is a body part?", "elbow", ["pillow", "carrot"], "Your elbow bends your arm.", true],
  ["Add -s to “fox”. Which word means more than one?", "foxes", ["foxs", "fox"], "After x we add -es.", true],
];

const BEFORE_AFTER: Q[] = [
  ["Before you read a book, what can you do?", "Look at the cover", ["Close your eyes", "Leave the room"], "The cover gives clues about the book."],
  ["The cover shows a dog and a bone. The book is probably about…", "a dog", ["a rocket", "the ocean"], "We use clues to predict."],
  ["To predict means to…", "guess what will happen", ["tear the page", "forget the story"], "A prediction is a good guess from clues."],
  ["A book has a picture of a snowy hill. What might happen?", "Someone goes sledding", ["Someone goes swimming", "A cactus grows"], "Use the clues in the picture."],
  ["What do you do when you are about to read about a farm?", "Think about what you know about farms", ["Wonder about a spaceship", "Hide the book"], "What we already know helps us understand."],
  ["You visited a farm. A book about farms is easier because…", "you already know some things", ["it has no words", "it is very short"], "Knowing something already helps."],
  ["A story has a girl who loses her mitten. You lost a mitten too. You are…", "making a connection", ["finding a mistake", "ending the story"], "A connection is when a story matches your life."],
  ["“I have a dog like that!” is a…", "connection", ["prediction", "title"], "It connects the book to your own life."],
  ["Which is a question you can ask about a book?", "Why did the bear hide?", ["The bear is brown.", "I like bears."], "Questions help us understand."],
  ["You don't understand a word in the story. What can you do?", "Ask a question", ["Stop reading forever", "Pretend you know"], "Asking helps us understand."],
  ["Which helps you choose a book you like?", "Think about what you are curious about", ["Pick the heaviest one", "Pick the dirtiest one"], "Pick books about things you want to know."],
  ["You want to learn about frogs. Which book is best?", "A book about frogs", ["A book about trucks", "A book about hats"], "Pick a book that matches your question."],
  ["A video, a book and a poster can all tell us…", "new information", ["nothing", "only a joke"], "Many kinds of texts can teach us."],
  ["After reading you can share…", "what you learned", ["nothing at all", "a secret code"], "Telling what you learned helps you remember."],
  ["Which sentence shares what you learned?", "I learned that frogs start as eggs.", ["Frogs.", "I have shoes."], "A good share says something you learned."],
  ["You see a girl in a book who looks like you. That is called…", "seeing yourself in a book", ["a mistake", "a spelling test"], "Books should have people like you in them."],
  ["A book shows many different families. Why is that good?", "Every child can see someone like them", ["It is a rule", "It makes books heavier"], "Books should include all kinds of people."],
  ["You love the book. A friend does not. Is that okay?", "Yes, people think differently", ["No, you must agree", "Only teachers can decide"], "Everyone has their own thoughts."],
  ["Which is an opinion about a story?", "I liked the ending.", ["The book has a cover.", "The story is on a page."], "An opinion tells how you feel."],
  ["“My favourite part was the funny frog” tells…", "an opinion", ["a title", "the author"], "It tells what you like."],
  ["A book has 12 pages. You've read 6. How far along are you?", "Halfway", ["Finished", "Just starting"], "Six is half of twelve."],
  ["What can the title of a book tell you?", "What the book might be about", ["How many pages it has", "What time it is"], "The title is a clue."],
  ["You see a squirrel hiding nuts on a page. What might happen next?", "Winter is coming", ["A shark swims by", "It is bedtime on the moon"], "Use what you know about squirrels."],
  ["How do you feel when a character is sad? You might feel…", "sad for them", ["angry for no reason", "nothing"], "Feelings in a story can match ours."],
  ["How can a friend see a story differently than you?", "They notice other parts", ["They see the same thing", "They cannot read"], "People have different thoughts and experiences.", true],
  ["Your friend says the story was scary. You say it was funny. Both are…", "personal responses", ["wrong", "answers to a spelling test"], "Feelings about a story can differ.", true],
];

const WRITE: Q[] = [
  ["Which letter starts a name?", "a capital letter", ["a number", "a full stop"], "Names start with a capital, like Mia."],
  ["Which name is written correctly?", "Sam", ["sam", "sAM"], "A name starts with a capital letter."],
  ["Which word is always a capital?", "I", ["i", "and"], "The word “I” is always a capital."],
  ["Which is written correctly?", "I like jam.", ["i like jam.", "i Like Jam."], "I is a capital, and the sentence starts with a capital."],
  ["A sentence begins with…", "a capital letter", ["a small letter", "a number"], "The first letter is a capital."],
  ["Which sentence starts the right way?", "The dog ran.", ["the dog ran.", "tHe dog ran."], "Start with a capital."],
  ["What goes at the end of a telling sentence?", "a period", ["a heart", "a plus"], "A period is a dot that says stop."],
  ["Which sentence ends correctly?", "I see a bus.", ["I see a bus", "I see a bus,"], "Finish it with a period."],
  ["What mark shows a big feeling or surprise?", "an exclamation mark", ["a period", "a comma"], "An exclamation mark looks like !"],
  ["Which sentence shows a big feeling?", "Wow, look at that!", ["It is a dog.", "Here is a hat."], "Wow and ! go together."],
  ["Which is a period?", ".", ["!", "?"], "A period is a small dot."],
  ["Which is an exclamation mark?", "!", [".", ","], "It has a line and a dot."],
  ["A sentence has about how many words?", "five or six", ["one hundred", "none"], "Short sentences of five or six words are great."],
  ["Which is a sentence of five words?", "The cat sat on mats.", ["Cat.", "Cat sat."], "Count the words."],
  ["Before you write a story, you can…", "draw a picture of it", ["throw away your pencil", "not think"], "Drawing and talking help plan writing."],
  ["Which helps you plan what to write?", "Talk about it with a friend", ["Do nothing", "Sleep"], "Talking helps ideas grow."],
  ["Which is a label on a drawing?", "cat", ["Once upon a time a cat went home.", "Yesterday."], "A label is a word or two that names something."],
  ["Which would tell how to bake a cake?", "information text", ["a poem about a dog", "a funny joke"], "Informational text tells facts or how to do things."],
  ["Which tells a made-up story?", "a story with characters", ["a list of rules", "a grocery list"], "A story has characters and things that happen."],
  ["Which text form is a list?", "milk, eggs, bread", ["Once upon a time…", "Dear Grandma,"], "A list is words or things written one under another."],
  ["Which tells a friend about yourself?", "a letter", ["a map", "a clock"], "A letter says things to a person."],
  ["Place the pictures: seed, plant, flower. What comes first?", "seed", ["flower", "plant"], "A seed comes before a plant."],
  ["A story sequence: First, then, last. Which word comes first?", "First", ["Last", "Then"], "First is at the start."],
  ["Which word goes last in order words?", "Last", ["First", "Next"], "Last means at the end."],
  ["Which has the words in order?", "I wake up. I eat. I go to school.", ["I go to school. I wake up. I eat.", "I eat. I go to school. I wake up."], "Morning tasks follow an order that makes sense.", true],
  ["You add a colourful picture with details. Why?", "To show your idea better", ["To hide your idea", "To make it plain"], "Colour and details make your idea clearer.", true],
  ["A friend says, “Add a word for the sound.” What do you do?", "Think about it and maybe add it", ["Never change anything", "Stop writing"], "Writers can change their ideas after feedback.", true],
  ["Writers can change their work after…", "hearing feedback", ["never", "falling asleep"], "Good writers listen to help.", true],
];

const REFLECT: Q[] = [
  ["You don't understand something. What can you notice?", "I am confused", ["I know everything", "I am a robot"], "Noticing is the first step."],
  ["If you don't understand, what can you do?", "Ask for help", ["Hide", "Give up"], "Asking for help is smart."],
  ["Which face shows you understand?", "Smiling face", ["Frowning face", "Sleeping face"], "A smile shows you got it."],
  ["Which thumb shows “I get it!”?", "Thumbs up", ["Thumbs down", "Wiggling thumb"], "Thumbs up means yes."],
  ["Which thumb shows “I need help”?", "Thumbs down", ["Thumbs up", "Two thumbs up"], "Thumbs down can show you need more help."],
  ["A sticker chart can show…", "how you are doing", ["what is for lunch", "the weather"], "Stickers can show our progress."],
  ["Your teacher says, “You tried hard!” You can think…", "I am learning", ["I never learn", "I do not care"], "Feedback tells us how we are growing."],
  ["Your teacher asks, “What went well?” You say…", "I read a whole page.", ["I sat down.", "Yes."], "Name a thing you did well."],
  ["Your teacher asks, “What are you learning about?” You say…", "I am learning about sounds.", ["Nothing.", "My shoes."], "Tell what you are working on."],
  ["Which is a learning goal?", "I want to read more words.", ["I want a cookie.", "I want a nap."], "A goal is something you want to learn."],
  ["Which is a good goal for this week?", "Learn to write my name", ["Never go to school", "Take over the world"], "Goals should be learning goals you can reach."],
  ["You wrote your name by yourself! You can say…", "I did it!", ["I can't.", "Not me."], "Celebrate what you can do."],
  ["Yesterday you could not tie a shoe. Today you can. You say…", "I can do this now!", ["I never could", "It is not for me"], "Notice your progress."],
  ["A progress chart shows…", "how far you have come", ["what to eat", "how loud you are"], "Charts track our growth."],
  ["You read at home every night. A sticker chart helps you…", "see how often you read", ["forget", "go to sleep"], "A chart tracks home reading."],
  ["It is hard to read a word. What is a helpful thing to say?", "I can try again", ["I'm no good", "I won't"], "Trying again is how we learn."],
  ["You made a mistake. What can you say?", "I can learn from that.", ["I'll never try.", "It's not my fault."], "Mistakes help us learn."],
  ["Which is a way to check how well you understand?", "Show a thumb or smiley", ["Cover your eyes", "Count clouds"], "Smileys and thumbs tell how you feel about your learning."],
  ["Which face means “I'm not sure yet”?", "A wavy mouth", ["A big grin", "A big yell"], "A wavy mouth can mean not sure."],
  ["Which helps you know you're growing?", "Looking at your old and new work", ["Throwing away your work", "Not looking"], "Compare your work to see growth."],
  ["Your teacher shows you a chart with stars. You can tell…", "how many things you've learned", ["what colour is blue", "how tall the teacher is"], "Stars show progress."],
  ["After a lesson, a good thing to think is…", "What did I learn today?", ["Nothing happened.", "Who is at the zoo?"], "Think about what you learned."],
  ["Which is a way to remember what you learned?", "Tell someone about it", ["Forget it", "Hide it"], "Sharing helps you remember."],
  ["When you finish something hard you can feel…", "proud", ["ashamed", "afraid of it"], "It is good to be proud of your work."],
  ["If a goal is too big, you can…", "make it smaller", ["give up", "pretend"], "Small steps get you there.", true],
  ["Which sentence is a kind way to think about learning?", "I can't do it yet.", ["I can't ever do it.", "I'm bad at it."], "“Yet” means you are still learning.", true],
  ["Your friend reached a goal. What can you say?", "Good job!", ["That's easy.", "I don't care."], "Kind words help everyone.", true],
];

export const languageUnits = [
  bankUnit({
    id: "mb-k-listening-and-talking",
    title: "Listening & Talking",
    emoji: "👂",
    blurb: "Good listening, kind questions and clear sentences.",
    parentNote:
      "Practises what a good listener looks like, asking who, what and where questions, speaking in whole sentences, and choosing a voice and words that suit the listener. Take turns chatting with your child and ask them to say back what they heard.",
    standards: ["ELA.K.A1.1, ELA.K.A1.2, ELA.K.A1.3, ELA.K.A1.4, ELA.K.A1.5, ELA.K.A1.6, ELA.K.D1.1", "listening, asking questions, speaking in simple sentences and talking to different audiences"],
    items: TALK,
  }),
  bankUnit({
    id: "mb-k-word-parts-and-meanings",
    title: "Word Parts & Meanings",
    emoji: "🧩",
    blurb: "-s, -ing, un- and groups of words.",
    parentNote:
      "Practises how a small word part changes a word (-s for more than one, -ing for happening now, un- for not), grouping words by topic, opposites and same-meaning words, and naming picture parts with labels.",
    standards: ["ELA.K.A2.4, ELA.K.A2.5, ELA.K.B2.7, ELA.K.C2.3", "word parts that change meaning, a growing vocabulary and topic words"],
    items: WORDS,
  }),
  bankUnit({
    id: "mb-k-before-during-after-reading",
    title: "Think About a Book",
    emoji: "📖",
    blurb: "Predict, connect, wonder and share what you think.",
    parentNote:
      "Practises what readers do before, during and after a book: using the cover and what they already know to predict, making connections to their own lives, asking questions, seeing themselves in books, and noticing that people can respond differently to the same text.",
    standards: [
      "ELA.K.B1.1, ELA.K.B1.2, ELA.K.B1.3, ELA.K.B1.4, ELA.K.B2.3, ELA.K.B2.4, ELA.K.B2.5, ELA.K.B3.1, ELA.K.B3.3, ELA.K.B3.4",
      "using what we know to predict, connecting, asking questions and responding to texts",
    ],
    items: BEFORE_AFTER,
  }),
  bankUnit({
    id: "mb-k-make-a-text",
    title: "Capitals, Periods & Planning",
    emoji: "✏️",
    blurb: "Write with capitals, periods and a plan.",
    parentNote:
      "Practises capital letters for names, I and the start of a sentence, periods and exclamation marks, five- or six-word sentences, planning a piece of writing by drawing or talking, putting ideas in order, simple text forms such as lists, letters, stories and information, and changing a piece after feedback.",
    standards: [
      "ELA.K.C1.1, ELA.K.C1.2, ELA.K.C1.3, ELA.K.C1.4, ELA.K.C1.5, ELA.K.C2.1, ELA.K.C2.2, ELA.K.C2.4, ELA.K.C2.5, ELA.K.C3.1, ELA.K.C3.3, ELA.K.C3.4, ELA.K.C3.5",
      "planning and making simple texts, capital letters, periods and exclamation marks",
    ],
    items: WRITE,
  }),
  bankUnit({
    id: "mb-k-i-can-learn",
    title: "I Can Do It!",
    emoji: "🌟",
    blurb: "Notice what you know and what you are learning.",
    parentNote:
      "Practises noticing when something is confusing, asking for help, using a smiley or thumb to show understanding, talking about what went well, and setting small learning goals. It builds a kind, growing way of thinking about learning.",
    standards: ["ELA.K.D2.1, ELA.K.D2.2, ELA.K.D2.3, ELA.K.D2.4, ELA.K.D2.5", "noticing understanding, listening to feedback, simple goals and recognizing progress"],
    items: REFLECT,
  }),
];
