import { bankUnit, type Q } from "../own";

// Kindergarten to Grade 2, New Brunswick. Science and social studies are part of Explore Your World, so these units practise
// its skill descriptors with New Brunswick examples. Prompts stay short and choices few for young readers.

const K_NATURE: Q[] = [
  ["Which animal lives in a New Brunswick forest?", "moose", ["penguin", "camel", "lion"], "Moose are very tall."],
  ["Which animal builds a dam?", "beaver", ["bird", "fish", "frog"], "Beavers use sticks and mud."],
  ["Which bird stays all winter in New Brunswick?", "chickadee", ["penguin", "parrot", "flamingo"], "It is the provincial bird."],
  ["What do plants need to grow?", "water and light", ["toys", "snow boots", "candy"], "Plants drink water through roots."],
  ["Which season is the coldest?", "winter", ["summer", "spring", "autumn"], "Snow falls in winter."],
  ["Which season has the warmest days?", "summer", ["winter", "spring", "autumn"], "We swim in summer."],
  ["In which season do leaves fall?", "autumn", ["winter", "spring", "summer"], "Leaves turn red and orange."],
  ["In which season do flowers start to grow?", "spring", ["winter", "autumn", "summer"], "Spring is warmer after winter."],
  ["What falls from clouds on a rainy day?", "rain", ["leaves", "sand", "balls"], "Wear a raincoat."],
  ["What do you wear on a snowy day?", "a warm coat", ["a swimsuit", "sandals", "shorts"], "Snow is cold."],
  ["Which one is a tree?", "a maple", ["a rock", "a fish", "a boat"], "Maple leaves turn red."],
  ["Which sense do we use with our nose?", "smell", ["sight", "hearing", "taste"], "Flowers have a smell."],
  ["Which sense do we use with our ears?", "hearing", ["smell", "taste", "sight"], "We hear birds."],
  ["Which sense do we use with our eyes?", "sight", ["smell", "hearing", "touch"], "We see colours."],
  ["Which sense do we use with our hands?", "touch", ["smell", "hearing", "taste"], "Soft things feel nice."],
  ["Which animal swims in the Bay of Fundy?", "whale", ["bear", "deer", "rabbit"], "Whales are big."],
  ["Which animal has fur?", "a fox", ["a fish", "a bird", "a frog"], "Foxes live in forests."],
  ["Which animal has feathers?", "a bird", ["a cat", "a dog", "a cow"], "Birds can fly."],
  ["Which animal lives in water?", "a fish", ["a dog", "a cat", "a horse"], "Fish have fins."],
  ["Which food comes from a plant?", "an apple", ["milk", "an egg", "cheese"], "Apples grow on trees."],
  ["What can you do to help nature?", "pick up litter", ["throw trash", "break branches", "pick every flower"], "Keep nature clean."],
  ["Where should we put recycling?", "in the recycling bin", ["on the ground", "in a river", "in the woods"], "Bins keep places clean."],
  ["Which is a safe way to look at a bug?", "watch it gently", ["squash it", "throw it", "take its home"], "Be kind to bugs."],
  ["What do we call the big, round, bright star in the day sky?", "the Sun", ["the Moon", "a cloud", "a bird"], "The Sun keeps us warm."],
  ["What do we see in the sky at night?", "the Moon and stars", ["the Sun", "rainbows", "kites"], "Stars twinkle."],
  ["What can a magnet pick up?", "a paper clip", ["a leaf", "a feather", "a sock"], "Magnets stick to some metals."],
];

const K_PROVINCE: Q[] = [
  ["What is our province called?", "New Brunswick", ["Ontario", "Alberta", "Manitoba"], "We live in New Brunswick."],
  ["What is our country called?", "Canada", ["Mexico", "France", "Japan"], "Canada has ten provinces."],
  ["What colours are in the Canadian flag?", "red and white", ["blue and green", "yellow and pink", "black and brown"], "It has a maple leaf."],
  ["What is on the Canadian flag?", "a maple leaf", ["a star", "a moon", "a fish"], "The leaf is red."],
  ["Which two languages do many people speak in New Brunswick?", "English and French", ["Spanish and Italian", "German and Greek", "Hindi and Arabic"], "Both are official languages."],
  ["What is the capital city of New Brunswick?", "Fredericton", ["Halifax", "Toronto", "Calgary"], "It is on the Saint John River."],
  ["Which river is in New Brunswick?", "the Saint John River", ["the Nile", "the Amazon", "the Red River"], "It is long and wide."],
  ["Which body of water has very high tides?", "the Bay of Fundy", ["Lake Superior", "a pond", "a puddle"], "The water goes up and down a lot."],
  ["Who helps us when we are sick?", "a doctor", ["a baker", "a pilot", "a painter"], "Doctors and nurses help us."],
  ["Who helps put out fires?", "a firefighter", ["a teacher", "a farmer", "a dentist"], "They drive a big fire truck."],
  ["Who helps us learn at school?", "a teacher", ["a firefighter", "a pilot", "a baker"], "Teachers help us read and count."],
  ["Who keeps us safe on the road?", "a police officer", ["a baker", "a farmer", "an artist"], "Police officers help people."],
  ["Who makes bread?", "a baker", ["a pilot", "a doctor", "a farmer"], "Bakers use an oven."],
  ["What should we do when we meet someone new?", "say hello kindly", ["look away", "say nothing", "frown"], "Kind words make friends."],
  ["What is a rule?", "something that helps keep us safe", ["a toy", "a snack", "a game piece"], "Rules help everyone."],
  ["What can you say when you want something?", "please", ["now", "give", "mine"], "Polite words are kind."],
  ["What can you say after someone helps you?", "thank you", ["go away", "no", "mine"], "Saying thanks is kind."],
  ["Who lives in your family?", "people who love and care for you", ["only strangers", "only pets", "no one"], "Families can be big or small."],
  ["Which is a way to share?", "take turns", ["grab", "hide it", "yell"], "Sharing is kind."],
  ["Which place has many books to borrow?", "a library", ["a bakery", "a gas station", "a park"], "Libraries are free to use."],
  ["Where do we play and run outside?", "a park", ["a bank", "a library", "a post office"], "Parks have swings."],
  ["Which is a need?", "food", ["a toy", "a game", "a sticker"], "We need food to live."],
  ["Which is a want?", "a toy", ["water", "food", "a bed"], "We can live without a toy."],
  ["What does the Wolastoq mean in Wolastoqey?", "beautiful river", ["tall tree", "cold lake", "big city"], "It is the Saint John River.", true],
  ["Wabanaki people have lived here for…", "a very long time", ["one day", "one week", "one year"], "They are still here today.", true],
  ["Why do we say please and thank you?", "it is polite and kind", ["it is a secret", "it is a game", "it is a trick"], "Kind words help everyone."],
];

const G1_NATURE: Q[] = [
  ["Which animal is the symbol of New Brunswick's wildlife and lives in the forest?", "the moose", ["the penguin", "the camel", "the kangaroo"], "Moose eat plants."],
  ["What is a habitat?", "the place where an animal lives", ["a kind of food", "a weather type", "a toy"], "A forest is a habitat."],
  ["What do animals need from their habitat?", "food, water and shelter", ["toys and games", "coats and hats", "books"], "These keep them alive."],
  ["Where does a beaver live?", "in a lodge by water", ["in a desert", "in a tree top", "in a cave on the Moon"], "Beavers build lodges with sticks."],
  ["Why do bears sleep in winter?", "there is little food", ["they are bored", "they are sad", "they love snow"], "This is called hibernation."],
  ["Why do some birds fly south in autumn?", "to find food and warmth", ["to find snow", "to play", "to learn songs"], "This trip is called migration."],
  ["Which animal turns white in winter?", "the snowshoe hare", ["the beaver", "the moose", "the crow"], "White fur hides it in snow."],
  ["What is a baby frog called?", "a tadpole", ["a puppy", "a kitten", "a cub"], "Tadpoles live in water."],
  ["What does a caterpillar become?", "a butterfly", ["a bee", "a bird", "a frog"], "It first rests in a chrysalis."],
  ["What do trees give us?", "air, shade and wood", ["TV and games", "sand and glass", "snow only"], "Trees are important."],
  ["Which tree keeps its needles all year?", "a spruce", ["a maple", "a birch", "an oak"], "Spruce trees are evergreens."],
  ["What is the weather like on a snowy day?", "cold", ["hot", "dry", "sunny and warm"], "Snow falls when it is very cold."],
  ["What does a thermometer measure?", "how hot or cold it is", ["how heavy it is", "how long it is", "how loud it is"], "It shows the temperature."],
  ["What does a rain gauge measure?", "how much rain falls", ["the wind", "the temperature", "the clouds"], "It collects water."],
  ["What makes the wind move a flag?", "moving air", ["the Moon", "the Sun's light only", "a magnet"], "Wind is air that moves."],
  ["What is a shadow?", "a dark shape made when light is blocked", ["a kind of light", "a kind of sound", "a kind of colour"], "Shadows change through the day."],
  ["When is your shadow the longest?", "in the morning or evening", ["at noon", "at midnight", "never"], "The Sun is low then."],
  ["Which of these makes sound?", "a drum", ["a rock", "a sock", "a bowl of rice"], "Hit it and it vibrates."],
  ["Which sound is loud?", "a fire truck siren", ["a whisper", "a leaf falling", "a sleeping cat"], "Sirens are meant to be heard."],
  ["Which material is hard?", "a rock", ["a cotton ball", "a feather", "a sponge"], "Rocks do not squish."],
  ["Which material is soft?", "a blanket", ["a rock", "a brick", "a spoon"], "Blankets are cosy."],
  ["Which floats in water?", "a cork", ["a rock", "a coin", "a key"], "Light things float."],
  ["How can we help our planet?", "recycle and save water", ["waste water", "litter", "leave lights on"], "Small actions help."],
  ["What can we do with a plastic bottle?", "recycle it", ["bury it in a river", "throw it in the forest", "burn it"], "Recycling saves resources."],
  ["What does a plant need to make food?", "light, water and air", ["music", "toys", "candy"], "Plants use sunlight."],
  ["Where do Wabanaki families find fish?", "in rivers and the sea", ["in a desert", "on a mountain top", "in the sky"], "Fish are an important food.", true],
];

const G1_COMMUNITY: Q[] = [
  ["What is a community?", "a group of people who live and work in the same area", ["a kind of animal", "a type of weather", "a toy"], "Towns and cities are communities."],
  ["Which of these is a community in New Brunswick?", "Moncton", ["Winnipeg", "Vancouver", "Calgary"], "Moncton is a city."],
  ["Which city is the capital of New Brunswick?", "Fredericton", ["Moncton", "Saint John", "Bathurst"], "Many government workers are there."],
  ["Which service helps keep our streets clean?", "garbage collection", ["a movie theatre", "a toy store", "a candy shop"], "Workers pick up garbage."],
  ["Which service keeps us safe from fires?", "the fire department", ["the library", "the museum", "the bakery"], "Firefighters rescue people."],
  ["Which place helps us borrow books?", "a library", ["a gas station", "a bank", "a post office"], "A library card is free."],
  ["Which place helps us when we are sick?", "a hospital", ["a bakery", "a library", "a gym"], "Nurses and doctors work there."],
  ["How do people travel between New Brunswick towns?", "by car, bus or bike", ["by rocket only", "by submarine only", "by magic"], "Roads connect communities."],
  ["Which of these is a rule in a community?", "stop at a red light", ["run through a red light", "skip school", "litter"], "Rules keep us safe."],
  ["Who is the leader of a town?", "the mayor", ["the premier", "the principal", "the doctor"], "The mayor leads a town council."],
  ["Who leads our province?", "the premier", ["the mayor", "the teacher", "the principal"], "The premier works in Fredericton."],
  ["Which is a way to be a good neighbour?", "help someone carry groceries", ["make loud noise at night", "leave litter", "ignore people"], "Neighbours help each other."],
  ["Which is a way to be fair?", "take turns", ["cut in line", "keep the toy", "say it's mine"], "Fair means everyone gets a turn."],
  ["Which is a way to include someone?", "invite them to play", ["leave them out", "laugh at them", "ignore them"], "Everyone belongs."],
  ["Which two languages are official in New Brunswick?", "English and French", ["Spanish and German", "English and Italian", "French and Greek"], "We can read signs in both."],
  ["Acadian people celebrate their culture on…", "August 15", ["February 1", "October 31", "March 17"], "There are parades and music.", true],
  ["Wabanaki people have lived in New Brunswick for…", "thousands of years", ["10 years", "50 years", "100 years"], "They live here today too."],
  ["Which holiday is on July 1?", "Canada Day", ["Halloween", "New Year's Day", "Thanksgiving"], "We celebrate Canada."],
  ["What does a map show?", "where places are", ["how hot it is", "what time it is", "how loud it is"], "Maps help us find our way."],
  ["What does a compass rose show?", "directions", ["colours", "numbers", "animals"], "It shows north, south, east and west."],
  ["Which direction is up on most maps?", "north", ["south", "east", "west"], "North is at the top."],
  ["Which of these is natural?", "a river", ["a bridge", "a road", "a building"], "People did not make rivers."],
  ["Which of these is made by people?", "a bridge", ["a lake", "a mountain", "a tree"], "People build bridges."],
  ["Why do we have community helpers?", "they do jobs that help everyone", ["to make noise", "to waste time", "to be funny"], "Each helper has a job."],
  ["What does it mean to belong?", "to feel welcome in a group", ["to be alone", "to be lost", "to be left out"], "Everyone should feel they belong."],
  ["What can you do if someone feels left out?", "ask them to join in", ["walk away", "tease them", "say nothing"], "Kindness includes others."],
];

const G2_NATURE: Q[] = [
  ["Which is a living thing?", "a tree", ["a rock", "a chair", "a cloud"], "Living things grow, need food and make more of themselves."],
  ["What is a life cycle?", "the stages in a living thing's life", ["a bicycle ride", "a weather chart", "a song"], "A butterfly goes from egg to adult."],
  ["What are the stages of a butterfly's life cycle in order?", "egg, caterpillar, chrysalis, butterfly", ["butterfly, egg, chrysalis, caterpillar", "chrysalis, egg, butterfly, caterpillar", "caterpillar, butterfly, egg, chrysalis"], "Each stage looks different."],
  ["Which animal lays eggs?", "a robin", ["a bear", "a moose", "a deer"], "Birds lay eggs."],
  ["Which animal gives birth to live young and feeds milk?", "a moose", ["a robin", "a salmon", "a frog"], "Mammals feed their babies milk."],
  ["Atlantic salmon are born in…", "rivers", ["deserts", "forests", "mountains"], "They swim to the sea and return."],
  ["What is an adaptation?", "a part or behaviour that helps a living thing survive", ["a kind of food", "a weather type", "a toy"], "Thick fur helps a bear stay warm."],
  ["How does a snowshoe hare's colour help it?", "it blends in with snow in winter", ["it makes it sing", "it helps it swim", "it makes it faster"], "This is called camouflage."],
  ["What is a solid?", "something that keeps its shape", ["something that flows", "something you cannot see", "a gas"], "A rock is a solid."],
  ["What is a liquid?", "something that flows and takes the shape of its container", ["something hard", "something invisible", "a block of ice"], "Water is a liquid."],
  ["What happens to ice when it gets warm?", "it melts", ["it grows", "it turns to rock", "nothing"], "Melting turns a solid into a liquid."],
  ["What happens to water when it gets very cold?", "it freezes", ["it burns", "it grows", "it floats away"], "Water freezes at 0 °C."],
  ["Which is a push?", "kicking a ball", ["pulling a wagon", "pulling a rope", "tugging a sled"], "A push moves something away."],
  ["Which is a pull?", "pulling a wagon", ["kicking a ball", "pushing a swing", "throwing a ball"], "A pull moves something toward you."],
  ["What can change how fast something moves?", "a push or a pull", ["a name", "a colour", "a smell"], "Forces change motion."],
  ["Which uses a simple machine?", "a ramp", ["a feather", "a cloud", "a sock"], "Ramps make lifting easier."],
  ["Water covers about how much of Earth?", "most of it", ["none", "a tiny bit", "none, it's all land"], "Oceans are huge."],
  ["Which water is safe to drink?", "clean tap water", ["puddle water", "ocean water", "pond water"], "Clean water keeps us healthy."],
  ["Where does rain come from?", "clouds", ["the ground", "the Moon", "the wind alone"], "Water vapour makes clouds."],
  ["What does the Sun give us?", "light and heat", ["rain and snow", "wind and waves", "sound"], "Plants need sunlight."],
  ["What is the Bay of Fundy known for?", "very high tides", ["tall mountains", "volcanoes", "deserts"], "The water moves a lot each day."],
  ["Which of these is a way to save water?", "turn off the tap while brushing teeth", ["leave the hose on", "take longer showers", "let taps drip"], "Saving water helps the planet."],
  ["What can we do to care for animals' homes?", "keep parks and forests clean", ["cut trees for fun", "leave trash", "dig up plants"], "Habitats need care."],
  ["Where do the Wolastoqiyik travel by canoe?", "on the Wolastoq (Saint John River)", ["on a mountain", "on a desert", "on a glacier"], "Canoes are made of birchbark.", true],
  ["Why do Wabanaki teachings say we should care for the land and water?", "all living things are connected", ["land does not matter", "water is not needed", "animals are not important"], "Respect for nature is a value.", true],
  ["What do we call animals that eat only plants?", "herbivores", ["carnivores", "omnivores", "predators"], "Deer are herbivores."],
];

const G2_COMMUNITY: Q[] = [
  ["What is a community?", "people who live and work together in a place", ["a kind of tree", "a weather type", "a school subject"], "Communities can be big or small."],
  ["Which kind of community has fewer people and more farms or forests?", "rural", ["urban", "busy", "industrial"], "Rural means countryside."],
  ["Which kind of community has many people and tall buildings?", "urban", ["rural", "wild", "forested"], "Cities are urban."],
  ["Which two languages are official in Canada?", "English and French", ["English and Spanish", "French and German", "English and Italian"], "Federal services are in both."],
  ["Which Nations have homelands in New Brunswick?", "Wolastoqiyik, Mi’kmaq and Peskotomuhkatiyik", ["Cree, Dene and Inuit", "Haida and Nisga’a", "Mohawk and Oneida"], "They are Wabanaki Nations."],
  ["Acadians are people who speak…", "French and have a rich culture in the Atlantic region", ["only English", "only Spanish", "only Mi’kmaw"], "National Acadian Day is August 15."],
  ["Which item might be a tradition in your family?", "a special meal on a holiday", ["a car", "a pencil", "a shoe"], "Traditions are shared practices."],
  ["Why do people celebrate festivals?", "to share culture and enjoy time together", ["to avoid friends", "to stay home", "to be alone"], "Festivals bring communities together."],
  ["What does it mean to respect someone's culture?", "listen and learn without making fun", ["laugh at it", "copy it as a costume", "tell them to change"], "Respect makes people feel welcome."],
  ["What is a need?", "something we must have to live", ["a toy", "a treat", "a game"], "Food, water and shelter are needs."],
  ["What is a want?", "something we would like but can live without", ["food", "water", "a house"], "A video game is a want."],
  ["What is a choice?", "picking one thing instead of another", ["a kind of weather", "a type of map", "a small tool"], "We make choices every day."],
  ["What is a citizen's responsibility?", "to follow rules and help others", ["to break rules", "to ignore neighbours", "to litter"], "Caring citizens make communities better."],
  ["What does a mayor do?", "leads a town or city council", ["builds ships", "teaches class", "grows crops"], "The mayor helps make local decisions."],
  ["Who makes laws for the province?", "the Legislative Assembly in Fredericton", ["the school principal", "the mayor only", "the hockey team"], "Members are elected by voters.", true],
  ["How can children help their community?", "pick up litter and help neighbours", ["break things", "make a mess", "stay indoors only"], "Volunteers help communities."],
  ["Long ago, how did people in New Brunswick travel along rivers?", "by canoe", ["by plane", "by car", "by train only"], "Rivers were roads.", true],
  ["How is life now different from long ago?", "we have cars, phones and electricity", ["we have no schools", "we have no food", "we have no houses"], "Technology changes how we live."],
  ["What is an old photograph a source of?", "information about the past", ["weather for tomorrow", "a recipe", "a map of the future"], "It shows how things used to look."],
  ["Which of these shows how people lived in the past?", "a museum", ["a video game", "a toy store", "a gym"], "Museums keep objects and stories."],
  ["What is a map key?", "it shows what symbols on a map mean", ["a house key", "a car key", "a kind of lock"], "Symbols stand for places."],
  ["Which direction is opposite to east?", "west", ["north", "south", "up"], "East and west are opposite."],
  ["Why is it good to include everyone in a game?", "everyone feels they belong", ["it makes the game shorter", "it makes people leave", "it is the rule of the moon"], "Inclusion is kind."],
  ["What does fairness mean?", "everyone gets what they need and a chance to take part", ["everyone gets the same toy", "the strongest wins always", "only some get a turn"], "Fair is not always the same for everyone.", true],
  ["How can we show we care about the Wolastoq?", "keep it clean and not dump garbage", ["throw trash in", "ignore it", "dig it up"], "Clean water is for everyone.", true],
];

const mk = (id: string, title: string, emoji: string, blurb: string, parentNote: string, std: readonly [string, string], items: Q[]) =>
  bankUnit({ id, title, emoji, blurb, parentNote, standards: std, items });

export const kNature = mk("nb-nature-k", "Nature Around Us", "🍁", "Animals, trees, seasons and our senses.",
  "Practises noticing patterns in nature, the seasons and the senses, with New Brunswick animals and trees. It follows the Explore Your World skill descriptors on sustainable futures in the New Brunswick curriculum.",
  ["Diversity and Social Responsibility: Sustainable Futures", "noticing patterns in nature, seasons and living things"], K_NATURE);
export const kProvince = mk("nb-my-province-k", "My Province & Community", "🏠", "New Brunswick, Canada and the people who help us.",
  "Practises our province, country and community helpers, and being kind and fair. It follows the Explore Your World skill descriptors on belonging and community in the New Brunswick curriculum.",
  ["Well-Being: Belonging and Interconnectedness", "belonging to a province, country and community, and helping others"], K_PROVINCE);
export const g1Nature = mk("nb-nature-1", "Animals, Weather & Materials", "🦌", "Habitats, weather tools, sound and materials.",
  "Practises habitats, animals, weather tools, sound, and materials, and caring for the planet. It follows the Explore Your World skill descriptors on exploring and problem solving in the New Brunswick curriculum.",
  ["Play and Playfulness: Exploration and Problem Solving", "exploring habitats, weather, sound and materials"], G1_NATURE);
export const g1Community = mk("nb-community-1", "My Community", "🏘️", "Places, helpers, maps and getting along.",
  "Practises communities, services, maps and being fair and inclusive. It follows the Explore Your World skill descriptors on belonging and inclusion in the New Brunswick curriculum.",
  ["Well-Being: Belonging and Interconnectedness", "communities, services, maps, and belonging"], G1_COMMUNITY);
export const g2Nature = mk("nb-nature-2", "Life Cycles, Matter & Forces", "🦋", "Life cycles, solids and liquids, pushes and pulls.",
  "Practises life cycles, adaptations, states of matter, forces and water, with local examples. It follows the Explore Your World skill descriptors on sustainable futures and exploration in the New Brunswick curriculum.",
  ["Diversity and Social Responsibility: Sustainable Futures", "recognizing patterns in life cycles, matter, forces and water"], G2_NATURE);
export const g2Community = mk("nb-community-2", "Communities Then & Now", "🛶", "Cultures, needs and wants, and how life changes.",
  "Practises communities in Canada, cultures including Wabanaki and Acadian, needs and wants, citizenship and how life changes over time. It follows the Explore Your World skill descriptors on inclusion and democratic practices in the New Brunswick curriculum.",
  ["Diversity and Social Responsibility: Inclusiveness and Equity", "communities, cultures, citizenship and change over time"], G2_COMMUNITY);
