import { bankUnit, type Q } from "../own";

// Grade 3 social studies, New Brunswick: My Province. Wabanaki content is light, in the present tense for living
// communities, and needs review by Wolastoqey, Mi'kmaq and Peskotomuhkati partners before launch.

const PROVINCE: Q[] = [
  ["What is the capital city of New Brunswick?", "Fredericton", ["Moncton", "Saint John", "Miramichi"], "Fredericton is on the Wolastoq (Saint John River)."],
  ["New Brunswick is part of which region of Canada?", "the Atlantic region", ["the Prairies", "the Pacific coast", "the Arctic"], "New Brunswick, Nova Scotia, Prince Edward Island and Newfoundland and Labrador make up the Atlantic region."],
  ["Which province is next to New Brunswick on the west side?", "Quebec", ["Ontario", "Manitoba", "Alberta"], "Quebec is to the northwest, and the state of Maine is to the west."],
  ["Which province is across the Northumberland Strait from New Brunswick?", "Prince Edward Island", ["Newfoundland and Labrador", "Ontario", "Saskatchewan"], "A long bridge called the Confederation Bridge crosses the strait."],
  ["Which province is joined to New Brunswick by a narrow strip of land called the Isthmus of Chignecto?", "Nova Scotia", ["Quebec", "Manitoba", "Prince Edward Island"], "The isthmus connects New Brunswick to Nova Scotia."],
  ["Which country is on New Brunswick's western border?", "the United States", ["Mexico", "France", "Greenland"], "The state of Maine borders New Brunswick."],
  ["Which large body of water is on New Brunswick's south coast?", "the Bay of Fundy", ["Hudson Bay", "Lake Superior", "the Arctic Ocean"], "The Bay of Fundy is famous for its very high tides."],
  ["The Bay of Fundy is known for having…", "some of the highest tides in the world", ["the warmest water in Canada", "no waves at all", "the longest river"], "The water rises and falls many metres twice a day."],
  ["Which bay is on New Brunswick's north coast?", "Chaleur Bay", ["Fundy Bay", "James Bay", "Georgian Bay"], "Chaleur Bay is between New Brunswick and the Gaspé in Quebec."],
  ["What is the Wolastoq?", "the Saint John River", ["a mountain", "a kind of tree", "a city"], "Wolastoq is the Wolastoqey name for the Saint John River. It means “beautiful river”."],
  ["Which of these is a major river in New Brunswick?", "the Miramichi River", ["the Fraser River", "the Red River", "the Mackenzie River"], "The Miramichi is famous for Atlantic salmon fishing."],
  ["Which famous covered bridge in Hartland is the longest in the world?", "the Hartland Covered Bridge", ["the Confederation Bridge", "Lions Gate Bridge", "the Golden Gate Bridge"], "It is about 391 metres long and crosses the Saint John River."],
  ["At the Hopewell Rocks, visitors can walk on the ocean floor at…", "low tide", ["high tide", "midnight only", "no time of day"], "The tide goes out so far that people can walk between the rocks."],
  ["Which natural landmark is known for its “flowerpot” rock formations?", "the Hopewell Rocks", ["Niagara Falls", "Mount Carleton", "the Magnetic Hill"], "The rocks were shaped by tides over a very long time."],
  ["Which city is famous for a hill where cars seem to roll uphill?", "Moncton", ["Fredericton", "Bathurst", "Edmundston"], "Magnetic Hill in Moncton is an optical illusion."],
  ["What is the highest mountain in New Brunswick?", "Mount Carleton", ["Mount Logan", "Mount Everest", "Mount Robson"], "It is in Mount Carleton Provincial Park in the north."],
  ["Most of New Brunswick is covered by…", "forest", ["desert", "ice", "glaciers"], "About four fifths of the province is forest."],
  ["Which tree is the provincial tree of New Brunswick?", "the balsam fir", ["the palm", "the cactus", "the baobab"], "The balsam fir is a softwood tree that grows across the province."],
  ["The black-capped chickadee is New Brunswick's provincial…", "bird", ["tree", "flower", "river"], "Chickadees stay in New Brunswick all winter."],
  ["New Brunswick's weather in winter is usually…", "cold and snowy", ["hot and dry", "warm and rainy", "the same as summer"], "Winters bring snow, and summers are warm."],
  ["How does the ocean affect the weather near the coast?", "It can make winters a little milder and summers cooler", ["It makes it snow every day", "It stops all rain", "It makes the days longer"], "Large bodies of water change temperatures nearby."],
  ["A place with few people and lots of farms or forests is called…", "rural", ["urban", "a harbour", "a capital"], "Rural areas are in the country. Urban areas are cities and towns."],
  ["A place with many people, buildings and roads is called…", "urban", ["rural", "wild", "forested"], "Cities such as Moncton, Saint John and Fredericton are urban."],
  ["Which is a city in New Brunswick?", "Saint John", ["Winnipeg", "Halifax", "Regina"], "Saint John is on the Bay of Fundy."],
  ["Which island in the Bay of Fundy can people reach by ferry?", "Grand Manan", ["Vancouver Island", "Baffin Island", "Cape Breton Island"], "Grand Manan is known for seabirds and whales.", true],
  ["Which sea animals can visitors sometimes see in the Bay of Fundy?", "whales", ["elephants", "penguins", "camels"], "Many whales visit the Bay of Fundy to feed.", true],
  ["On a map, what does the symbol N usually show?", "north", ["nearest", "new", "narrow"], "A compass rose shows north, south, east and west.", true],
  ["New Brunswick is the only province in Canada that is officially…", "bilingual, in English and French", ["unilingual in English", "unilingual in French", "trilingual"], "Both English and French are official languages in New Brunswick.", true],
  ["Which of these is a human-made landmark in New Brunswick?", "the Hartland Covered Bridge", ["the Bay of Fundy", "Mount Carleton", "the Saint John River"], "People built the bridge. The other places are natural landmarks.", true],
];

const NATIONS: Q[] = [
  ["The Wabanaki Peoples have lived in New Brunswick for…", "thousands of years", ["about 20 years", "since the year 1900", "only in winter"], "Wabanaki means “People of the Dawn”."],
  ["Which three Nations have homelands in what is now New Brunswick?", "Wolastoqey, Mi’kmaq and Peskotomuhkati", ["Cree, Blackfoot and Dene", "Haida, Squamish and Nisga’a", "Inuit, Cree and Innu"], "They are all part of the Wabanaki Confederacy."],
  ["What does Wolastoqey mean?", "people of the beautiful river", ["people of the mountains", "people of the sea", "people of the prairie"], "It comes from Wolastoq, the Saint John River."],
  ["The Wolastoqey have a close connection with which river?", "the Wolastoq (Saint John River)", ["the Fraser River", "the Nile", "the Red River"], "Their homeland is along the Wolastoq and its tributaries."],
  ["Which Nation has homelands on the Miramichi River and along the north and east coasts of New Brunswick?", "the Mi’kmaq", ["the Haida", "the Inuit", "the Métis"], "The Mi’kmaq homeland is called Mi’kma’ki."],
  ["What is the name of the Mi’kmaw homeland?", "Mi’kma’ki", ["Wolastoq", "Nunavut", "Haida Gwaii"], "Mi’kma’ki includes parts of New Brunswick, Nova Scotia, Prince Edward Island and more."],
  ["The Peskotomuhkati homeland is near the…", "St. Croix River and Passamaquoddy Bay", ["Hudson Bay", "Great Lakes", "Rocky Mountains"], "Peskotomuhkati means “people of the place where pollock are plentiful”."],
  ["The Wolastoqey, Mi’kmaq and Peskotomuhkati are all part of the…", "Wabanaki Confederacy", ["Roman Empire", "Hudson’s Bay Company", "Canadian Senate"], "The Confederacy is an alliance of Nations."],
  ["Wabanaki Peoples in New Brunswick today…", "are living communities with leaders, languages and traditions", ["no longer live here", "live only in museums", "speak only English"], "Wabanaki cultures and languages are alive today."],
  ["Which of these is a Wabanaki language spoken in New Brunswick?", "Mi’kmaw", ["Latin", "Japanese", "Spanish"], "Wolastoqey and Peskotomuhkati are also spoken."],
  ["Many Wabanaki Peoples have always cared for the land and water and see themselves as…", "part of the natural world", ["owners who can use it up", "visitors who must leave", "separate from the animals"], "Respect for the land and all living things is part of many teachings."],
  ["Long ago, Wabanaki families moved with the seasons so they could…", "fish, hunt and gather food when it was plentiful", ["avoid ever seeing the water", "stay in one house all year", "stay away from the forest"], "Different foods were available at different times of year."],
  ["Birchbark canoes were useful for travel because they were…", "light and good on rivers and lakes", ["very heavy and slow", "made of metal", "too big to carry"], "People could carry a canoe around rapids."],
  ["The Wolastoq flows through which city today?", "Fredericton", ["Winnipeg", "Toronto", "Calgary"], "Fredericton is on the Wolastoq."],
  ["Where can you find a Wabanaki community in New Brunswick today?", "in places such as Elsipogtog, Madawaska Maliseet and Tobique", ["only in the Arctic", "only in other countries", "nowhere"], "Many Wabanaki communities are in New Brunswick, and each has its own leaders."],
  ["Ash trees are important to many Wabanaki basket makers because the wood can be…", "split into thin strips for weaving", ["used as a canoe paddle only", "eaten as food", "melted into glass"], "Basket making is a living art in many communities."],
  ["Why is it respectful to ask a community how to say its name for itself?", "It shows we care about how people describe themselves", ["It makes the name longer", "It is a game", "It is against the law"], "Using the names people choose for themselves is respectful."],
  ["Which of these is a Wolastoqey word?", "Wolastoq", ["Fundy", "Chaleur", "Miramichi"], "Fundy and Chaleur are not Wolastoqey words, and Miramichi comes from Mi’kmaw.", true],
  ["Which foods did Wabanaki Peoples traditionally harvest from the ocean and rivers?", "fish and shellfish", ["bananas and pineapples", "rice and peanuts", "cocoa and coffee"], "Salmon, eel and clams were important foods.", true],
  ["A guardian of the water might say we should…", "leave rivers and lakes clean for the future", ["use them up fast", "fill them with garbage", "ignore them"], "Many teachings say to look after the water for those who come next.", true],
  ["On a map of New Brunswick, where would you look for the Bay of Fundy?", "the south coast", ["the northwest corner", "the centre of the province", "the northern border with Quebec"], "The south coast faces the Bay of Fundy.", true],
  ["Why do many places in New Brunswick have Wabanaki names?", "Wabanaki Peoples named them long ago", ["Visitors picked them from a book", "A computer made the names", "They are names of ships"], "Names such as Miramichi and Wolastoq come from Wabanaki languages.", true],
  ["Learning about the Wabanaki Nations helps us…", "understand the history of the place we live", ["forget the past", "avoid learning new things", "stop talking to others"], "Knowing the past helps us understand today.", true],
  ["Which statement is true about the three Nations of New Brunswick?", "Each Nation has its own history, language and leaders", ["They are all exactly the same", "They have the same language", "They have no leaders"], "It is respectful not to treat all Nations as one.", true],
  ["Skutik is a Peskotomuhkati place near…", "the St. Croix River", ["Mount Carleton", "the Miramichi River", "Grand Falls"], "Peskotomuhkati territory includes the St. Croix River area.", true],
];

const PEOPLES: Q[] = [
  ["Who were the first peoples to live in what is now New Brunswick?", "the Wabanaki Peoples", ["Vikings", "Romans", "Pilgrims"], "Wabanaki Peoples have lived here for thousands of years."],
  ["The Acadians are French-speaking people whose ancestors came to the region in the…", "1600s", ["1990s", "1950s", "1800s only"], "French settlers began arriving in the early 1600s."],
  ["Which language do many Acadians in New Brunswick speak?", "French", ["Latin", "Greek", "Russian"], "French is an official language of New Brunswick."],
  ["The Loyalists were people who…", "stayed loyal to Britain after the American Revolution", ["were sailors from France", "built the first railway", "were the first people to live here"], "Many moved north to British land in 1783."],
  ["Which city was founded by Loyalists in 1783 and became Canada’s first incorporated city?", "Saint John", ["Fredericton", "Moncton", "Bathurst"], "Saint John was incorporated in 1785."],
  ["New Brunswick became its own colony in which year?", "1784", ["1604", "1867", "1999"], "It was split from Nova Scotia so Loyalists could have their own government."],
  ["New Brunswick joined Confederation in which year?", "1867", ["1784", "1900", "1949"], "It was one of the first four provinces."],
  ["Many Irish families came to New Brunswick in the 1840s to escape…", "a famine", ["a flood", "a snowstorm", "a war in Asia"], "The Great Famine in Ireland caused many to leave."],
  ["Partridge Island near Saint John was where many Irish immigrants were…", "checked for illness before coming ashore", ["given a school", "given a free house", "taught French"], "It was a quarantine station."],
  ["Danish settlers started a community in New Brunswick called…", "New Denmark", ["New Spain", "New Sweden", "New Zealand"], "New Denmark was founded in 1872."],
  ["Black Loyalists came to the region after the American Revolution because they…", "had been promised freedom for supporting Britain", ["wanted to mine gold", "were looking for a train", "were visiting for the summer"], "Many were given little land and faced unfair treatment."],
  ["What does it mean when a province is diverse?", "People of many backgrounds live there", ["Everyone is the same", "It has no people", "It has only one town"], "Diversity means many different people and cultures."],
  ["Which two groups are sometimes called the first and founding peoples of what became Canada?", "Indigenous Peoples and the French and British settlers", ["tourists and sailors", "robots and astronauts", "Vikings and Romans"], "The curriculum looks at the first and founding peoples and others who came later.", true],
  ["Which of these shows how New Brunswick has become more diverse over time?", "People have come from many countries", ["Fewer languages are spoken", "Everyone speaks the same language", "No new people arrived"], "Newcomers continue to arrive and make communities richer."],
  ["Which of these is a reason people may move to New Brunswick today?", "to work, study or join family", ["to see a volcano", "to ride a subway", "to see a desert"], "Newcomers choose New Brunswick for many reasons."],
  ["Which words are on New Brunswick’s motto, Spem reduxit?", "“Hope was restored”", ["“Be kind to all”", "“Ship at sea”", "“Land and sky”"], "The Latin motto was chosen after the Loyalists arrived."],
  ["Why do we put events in order on a timeline?", "to see what happened first and next", ["to guess the weather", "to count the stars", "to draw a map"], "A timeline shows how things changed.", true],
  ["Which came first in New Brunswick?", "Wabanaki Peoples", ["Loyalists", "Confederation", "the Confederation Bridge"], "Wabanaki Peoples lived here long before others arrived.", true],
  ["Acadian Day in New Brunswick is celebrated on…", "August 15", ["December 25", "July 1", "April 1"], "National Acadian Day celebrates Acadian culture.", true],
  ["Which community in northern New Brunswick has a historic Acadian village museum?", "Caraquet", ["Fredericton", "Hartland", "Sussex"], "Village Historique Acadien shows how Acadians lived long ago.", true],
  ["Which of these shows respect for people from different cultures?", "listening and learning about their traditions", ["making fun of them", "ignoring them", "refusing to share"], "Respect means being curious and kind."],
  ["Many streets, towns and rivers in New Brunswick have names from…", "Wabanaki, French and English words", ["only Latin", "only Greek", "a computer"], "Place names tell stories about the people who lived here.", true],
  ["Diverse communities can help each other by…", "sharing food, stories and skills", ["keeping everything secret", "never talking", "building walls"], "Sharing helps people learn from one another."],
  ["A family that came from another country to live in New Brunswick are called…", "immigrants", ["explorers", "glaciers", "tides"], "Immigrants move to a new country to live."],
  ["Which of these is one way diversity has changed New Brunswick?", "More foods, festivals and languages", ["Fewer festivals", "No foods", "Less music"], "Newcomers bring traditions that others can enjoy."],
];

const GOVERNMENT: Q[] = [
  ["What is a government?", "a group that makes decisions and rules for a community", ["a type of store", "a school bus", "a TV show"], "Governments decide how a community will be run."],
  ["Which level of government leads a city or town?", "municipal", ["federal", "provincial", "global"], "A mayor and council lead a city or town."],
  ["Who is the head of a municipal government?", "the mayor", ["the prime minister", "the premier", "the principal"], "A mayor and councillors make decisions for a town or city."],
  ["Which level of government looks after a whole province?", "provincial", ["municipal", "school", "neighbourhood"], "The province makes laws about schools, health and roads."],
  ["Who is the leader of the provincial government in New Brunswick?", "the premier", ["the mayor", "the prime minister", "the governor of Maine"], "The premier leads the government of New Brunswick."],
  ["Where does the provincial government meet in New Brunswick?", "the Legislative Assembly in Fredericton", ["the Parliament in Moncton", "the Legislature in Halifax", "city hall in Saint John"], "Members meet in the Legislative Building in Fredericton."],
  ["What is an MLA?", "a person elected to speak for people in the provincial legislature", ["a kind of boat", "a school subject", "a city worker"], "MLA means Member of the Legislative Assembly."],
  ["Who is the leader of the federal government of Canada?", "the prime minister", ["the premier", "the mayor", "the principal"], "The prime minister leads the government of Canada."],
  ["Where does the federal government meet?", "Ottawa", ["Fredericton", "Halifax", "Toronto"], "Canada’s Parliament is in Ottawa."],
  ["Which of these is a job of a government?", "making and enforcing laws", ["selling toys", "growing apples only", "building boats only"], "Governments also provide services such as roads and schools."],
  ["Which service do local governments often provide?", "garbage pickup and snow clearing", ["printing money", "choosing the prime minister", "making treaties with other countries"], "Municipal governments handle local services."],
  ["Which service does a provincial government often provide?", "schools and hospitals", ["nothing at all", "weather", "the ocean tides"], "Provinces are responsible for education and health care."],
  ["What is a law?", "a rule that everyone must follow", ["a kind of game", "an optional idea", "a school prize"], "Laws help keep people safe and treat them fairly."],
  ["Who must follow the law?", "everyone, including leaders", ["only children", "only visitors", "only people over 100"], "Laws apply to everybody in the community."],
  ["A citizen is a person who…", "belongs to a country and has rights and responsibilities", ["only visits a country", "is a king", "is an animal"], "Citizens take part in their communities."],
  ["Which of these is a right of citizens in Canada?", "the right to speak freely", ["the right to skip every law", "the right to take anything", "the right to be rude"], "The Charter of Rights and Freedoms protects free expression."],
  ["Which of these is a responsibility of a citizen?", "following the laws", ["breaking the law", "ignoring others", "hiding from neighbours"], "Responsibilities are things we should do."],
  ["Which is a way for adult citizens to take part in choosing leaders?", "voting in an election", ["building a tower", "writing a recipe", "sleeping early"], "In an election, citizens choose who will lead."],
  ["How might a student take part in making decisions at school?", "by joining a student council", ["by skipping class", "by staying quiet forever", "by hiding the lunch"], "Students can share ideas and vote."],
  ["How can a citizen show care for their community?", "by volunteering to help", ["by littering", "by being unkind", "by ignoring rules"], "Volunteers help make communities better.", true],
  ["Why does a community need rules?", "to keep people safe and treat them fairly", ["to make life boring", "to stop everyone from playing", "to hide things"], "Rules help people live together.", true],
  ["Which of these is an example of a citizen taking part in public decisions?", "writing a letter to the mayor about a new park", ["throwing trash on the ground", "ignoring the news", "hiding from neighbours"], "Citizens can share ideas with leaders.", true],
  ["In an election, a ballot is used to…", "mark your choice", ["buy snacks", "learn a song", "measure rainfall"], "Ballots are kept secret so people can choose freely.", true],
  ["The Crown is represented in New Brunswick by the…", "Lieutenant Governor", ["mayor of Saint John", "school principal", "weather forecaster"], "The Lieutenant Governor is the King’s representative in the province.", true],
  ["How many levels of government do people in Canada usually have?", "three: municipal, provincial and federal", ["only one", "ten", "none"], "Each level has different jobs.", true],
  ["Respecting others’ rights means…", "treating people fairly and kindly", ["taking their things", "teasing them", "ignoring them"], "Rights and responsibilities go together.", true],
];

const TREATIES: Q[] = [
  ["What is a treaty?", "a formal agreement between groups", ["a type of boat", "a kind of tree", "a school rule"], "Treaties set out promises people make to one another."],
  ["The Peace and Friendship treaties were agreements between the Wabanaki Nations and…", "the British Crown", ["the Vikings", "the Roman Empire", "the Canadian Senate"], "The treaties were made between 1725 and 1779."],
  ["Which Wabanaki Nations signed Peace and Friendship treaties in what is now New Brunswick?", "the Wolastoqiyik, Mi’kmaq and Peskotomuhkatiyik", ["the Haida and Nisga’a", "the Cree and Dene", "the Inuit and Innu"], "Each Nation made agreements with the Crown."],
  ["Between which years were the Peace and Friendship treaties made?", "1725 and 1779", ["1000 and 1100", "1900 and 1950", "2000 and 2020"], "They were made over about fifty years."],
  ["The Peace and Friendship treaties were mainly about…", "peace, trade and living side by side", ["selling all the land", "building a railway", "making a new flag"], "They did not give up the land."],
  ["Wabanaki Nations today say the treaties…", "are still important promises", ["were long forgotten", "ended in 1800", "were only a game"], "Treaty rights are protected by Canada’s Constitution."],
  ["Many Wabanaki people see the treaties as promises to share the land rather than to…", "give it away", ["make music", "name rivers", "grow food"], "Different groups may understand the same agreement in different ways."],
  ["A promise is kept when people…", "do what they said they would do", ["forget about it", "change it without telling", "break it on purpose"], "Trust grows when people keep promises."],
  ["What does the word “reconciliation” mean?", "working to repair relationships and build respect", ["winning a race", "building a bridge", "drawing a map"], "Reconciliation takes time and effort."],
  ["The Truth and Reconciliation Commission of Canada made 94…", "Calls to Action", ["new holidays", "bridges", "songs"], "The Calls to Action are steps to repair relationships with Indigenous Peoples."],
  ["The Truth and Reconciliation Commission listened to the experiences of people who attended…", "residential schools", ["music festivals", "farm fairs", "sailing camps"], "Residential schools took children from their families."],
  ["September 30 is the National Day for…", "Truth and Reconciliation", ["Sailing", "Maple syrup", "Winter sports"], "It honours the children who never returned home and the survivors."],
  ["Many people wear an orange shirt on September 30 to remember…", "children who were taken to residential schools", ["a hockey game", "a sunny day", "a sale"], "Orange Shirt Day began from the story of Phyllis Webstad."],
  ["Which action is a way to practise reconciliation?", "listening to and learning from Indigenous Peoples", ["laughing at stories", "ignoring history", "refusing to learn names"], "Learning with respect is a first step."],
  ["Why is it important to learn about treaties?", "to understand history and how to treat others fairly", ["to win a quiz", "to get a prize", "to avoid reading"], "Treaties still affect people’s lives today.", true],
  ["A treaty is more trustworthy when each group…", "understands and agrees to the same promises", ["is forced to sign", "is not told what it says", "has no say"], "A fair agreement needs understanding.", true],
  ["Which of these can help repair a relationship?", "an honest apology and actions to make things right", ["saying nothing", "blaming someone else", "ignoring the problem"], "Words and actions both matter.", true],
  ["If someone tells a story from their own point of view, you should…", "listen carefully and respectfully", ["interrupt them", "walk away", "say it is wrong"], "Listening helps us understand different views.", true],
  ["Who signed the Peace and Friendship treaties on behalf of the Crown?", "British officials", ["Canadian astronauts", "French explorers in 2020", "school students"], "Canada did not exist until 1867.", true],
  ["Treaty rights are rights that…", "come from agreements between Indigenous Nations and the Crown", ["come from a store", "are made up each day", "belong to no one"], "They are part of Canada’s law.", true],
  ["Which statement about the treaties is best?", "They are agreements that matter today", ["They are only old stories", "They have been cancelled", "They are only about hockey"], "Treaties are living agreements.", true],
  ["Which is a respectful way to talk about Wabanaki Peoples?", "in the present tense, as living Nations", ["as if they all disappeared", "as if they are one group only", "as if they are in a story only"], "Wabanaki Nations are here today.", true],
  ["A group of leaders who speak for their community are called…", "a council", ["a canoe", "a tide", "a glacier"], "Many Nations have chiefs and councils.", true],
  ["Why do we honour survivors of residential schools?", "they showed courage and strength", ["they won a contest", "they built the first school", "they are famous actors"], "Survivors help teach all Canadians.", true],
  ["A fair agreement is one where…", "everyone’s needs are respected", ["one side decides everything", "nobody speaks", "no one reads it"], "Fairness means everyone is heard.", true],
  ["The Wabanaki Confederacy is…", "an alliance of Nations", ["a kind of canoe", "a fish", "a type of store"], "Wabanaki means “People of the Dawn”.", true],
];

const RESOURCES: Q[] = [
  ["What is a natural resource?", "something from nature that people use", ["a toy from a store", "a TV show", "a video game"], "Forests, fish and water are natural resources."],
  ["Which natural resource covers most of New Brunswick?", "forests", ["deserts", "glaciers", "volcanoes"], "Forests give wood, paper and homes for animals."],
  ["Which product do we get from trees?", "paper", ["glass", "plastic", "cheese"], "Wood is made into paper, lumber and more."],
  ["Which seafood is a very important catch in New Brunswick?", "lobster", ["tuna from the Pacific", "mangoes", "chocolate"], "Fishers catch lobster in the Northumberland Strait and the Bay of Fundy."],
  ["Fishing is an important job in which part of New Brunswick?", "along the coast", ["in the middle of the desert", "only in the mountains", "at the North Pole"], "The ocean provides fish and shellfish."],
  ["Which crop is grown on many New Brunswick farms in the Saint John River valley?", "potatoes", ["bananas", "rice", "coffee"], "The soil and climate suit potatoes."],
  ["Which of these tasty foods comes from maple trees?", "maple syrup", ["honey", "jam", "ketchup"], "Sap is boiled to make maple syrup."],
  ["Mining in New Brunswick takes things such as…", "zinc and potash from the ground", ["apples from trees", "fish from rivers", "wool from sheep"], "Mines dig for minerals."],
  ["What does a hydroelectric dam use to make electricity?", "moving water", ["wind", "the Sun", "coal"], "The Mactaquac Dam is on the Saint John River."],
  ["A renewable resource is one that…", "can grow back or be replaced", ["cannot be used", "is always rock", "disappears forever"], "Trees can regrow if forests are looked after."],
  ["A non-renewable resource is one that…", "cannot be replaced quickly once it is used", ["always grows back", "falls from the sky", "grows in a day"], "Minerals take millions of years to form."],
  ["Which is a renewable resource?", "a well-managed forest", ["a mineral deposit", "a lump of coal", "an oil well"], "Planting new trees helps forests grow back."],
  ["Which is a non-renewable resource?", "a metal ore", ["wind", "sunlight", "a well-managed forest"], "Once removed, it does not come back quickly."],
  ["Why do people plant new trees after cutting a forest?", "so the forest can grow back", ["to make it look empty", "to stop rain", "to save paper"], "Replanting is part of looking after forests."],
  ["Which job might someone have in the forest industry?", "forester", ["astronaut", "airline pilot", "ice-cream maker"], "Foresters care for and manage forests."],
  ["How can people use resources wisely?", "by taking only what they need and caring for the land", ["by using as much as possible", "by ignoring the future", "by wasting water"], "Sustainability means meeting needs without harming the future."],
  ["What does sustainability mean?", "using resources in a way that will last", ["using everything quickly", "ignoring the environment", "closing all businesses"], "Sustainable choices protect nature for the future."],
  ["Which action helps sustain our resources?", "recycling paper and plastics", ["throwing waste in the river", "leaving taps running", "cutting down every tree"], "Recycling reduces how much we need to take from nature."],
  ["Fish need clean water. What can people do to help?", "keep garbage out of rivers and the ocean", ["pour oil into streams", "dump trash in lakes", "ignore pollution"], "Healthy water means healthy fish."],
  ["Why is fishing a challenge if too many fish are caught?", "there may not be enough left for the future", ["fish will learn to fly", "the sea will dry up", "boats will sink"], "Fisheries have limits so fish populations can recover.", true],
  ["Which product is made in New Brunswick from the wood of trees?", "pulp and paper", ["ice cream", "cars", "computers"], "Mills turn wood into paper products.", true],
  ["A farm is a good example of how people use…", "land and soil", ["only the Moon", "only the sky", "only snow"], "Farmers use land to grow crops and raise animals.", true],
  ["Where do many people in New Brunswick work to make electricity?", "dams and power stations", ["airports", "bakeries", "shoe stores"], "Electricity comes from a few sources, such as hydro, wind and nuclear.", true],
  ["Why do people value the Saint John River?", "it gives water, food, travel and power", ["it has no use", "it is too far away", "it is not wet"], "People depend on rivers in many ways.", true],
  ["If people use too much of a resource, what could happen?", "it may become scarce", ["there will be more of it", "nothing changes", "it will grow faster"], "Scarce means hard to find.", true],
  ["Which of these is good stewardship of a forest?", "planting trees and protecting wildlife homes", ["leaving garbage in the woods", "cutting every tree", "lighting fires near dry trees"], "Stewards look after the land.", true],
];

const CITIZENS: Q[] = [
  ["Which of these is a responsibility of a citizen at school?", "treating others with respect", ["breaking classroom rules", "ignoring teachers", "throwing litter"], "Responsibilities are things we should do."],
  ["Which of these is a right every child has?", "the right to learn", ["the right to take anything", "the right to ignore rules", "the right to be mean"], "Children have rights, such as being safe and learning."],
  ["What does fairness mean?", "everyone is treated in a just way", ["only some get a turn", "one person always wins", "no one gets to speak"], "Fair rules work for everyone."],
  ["How can you help make a decision in your class?", "by voting or sharing your ideas", ["by shouting", "by hiding", "by taking over"], "Sharing ideas is a way to take part."],
  ["Voting is a way to…", "show your choice in a group decision", ["win a trophy", "draw a map", "bake a cake"], "Votes are counted to see what most people want."],
  ["If most people vote for option A, which option is chosen in a simple vote?", "option A", ["option B", "none", "the loudest one"], "The choice with the most votes wins in a majority vote."],
  ["Who can speak up for a fair rule at school?", "any student", ["only teachers", "only visitors", "only the principal"], "Everyone can share ideas."],
  ["A petition is…", "a request signed by many people", ["a type of pie", "a school bus", "a small boat"], "People sign a petition to ask leaders to do something."],
  ["Why is it important to respect other people’s opinions?", "they may help us learn something new", ["so we never disagree", "so no one speaks", "so everyone is the same"], "We can disagree and still be respectful."],
  ["Which is a good way to solve a disagreement?", "listen to each person and look for a fair solution", ["yell louder", "ignore the problem", "take things away"], "Listening helps people find answers together."],
  ["Which of these is a way to help your community?", "joining a clean-up", ["leaving garbage", "damaging a playground", "ignoring neighbours"], "Many hands make a community cleaner."],
  ["A volunteer is someone who…", "gives their time to help without pay", ["sells things", "gets a big prize", "takes a vacation"], "Volunteers help in many places."],
  ["Which community helper keeps people safe on the roads?", "police officer", ["baker", "mail carrier", "author"], "Helpers and workers serve the community."],
  ["Why do we have rules about crossing roads safely?", "to keep people safe", ["to be silly", "to waste time", "to make traffic slower"], "Rules protect people."],
  ["Which statement shows respect for the environment?", "I will recycle and not litter.", ["I will drop my trash.", "I will waste water.", "I will break branches."], "Respecting nature is part of being a good citizen."],
  ["If you see someone being left out, you could…", "invite them to join", ["laugh at them", "walk away", "pretend not to see"], "Kindness helps everyone belong."],
  ["Which choice shows responsibility?", "putting your things away", ["leaving a mess for others", "losing your homework on purpose", "ignoring chores"], "Responsible people look after their things and spaces."],
  ["Why do citizens pay taxes?", "to help pay for services such as roads and schools", ["to buy toys for children", "to pay for candy", "to build snowmen"], "Taxes pay for services everyone shares.", true],
  ["What is a Charter of Rights and Freedoms?", "a document that protects the rights of people in Canada", ["a cookbook", "a map", "a storybook"], "It is part of Canada’s Constitution.", true],
  ["Which is an example of free speech?", "sharing your ideas respectfully", ["shouting hurtful words", "spreading rumours", "taking someone’s voice"], "Free speech comes with a duty to respect others.", true],
  ["Why do leaders need to listen to citizens?", "to understand what people need", ["to make the day longer", "to find lost items", "to stop the rain"], "Leaders make better decisions when they listen.", true],
  ["How can people share their ideas with a mayor?", "by writing a letter or speaking at a council meeting", ["by hiding", "by sending a boat", "by ringing a bell and leaving"], "Citizens can take part in public decisions.", true],
  ["An election is when…", "citizens choose their leaders", ["trees choose their leaves", "dogs choose a bed", "birds choose a song"], "Adult citizens vote in elections.", true],
  ["Which is a fair rule for taking turns?", "everyone gets a turn in order", ["the strongest goes first every time", "no one goes", "only friends go"], "Fair turn-taking helps groups work together.", true],
  ["A responsible citizen online would…", "be kind and think before sharing", ["post mean comments", "share private information", "pretend to be someone else"], "Good citizenship applies online too.", true],
  ["Which sentence states a responsibility?", "I should return the books I borrow.", ["I can do whatever I want.", "Books belong to me.", "I never have to share."], "Responsibilities are duties we owe to others.", true],
];

export const ourProvince = bankUnit({
  id: "nb-our-province-3",
  title: "My Province: New Brunswick",
  emoji: "🗺️",
  blurb: "Rivers, bays, forests and famous places!",
  parentNote:
    "Practises where New Brunswick is in the Atlantic region and Canada, its major physical features, climate and vegetation, landmarks, and the ideas of urban and rural. It follows the Grade 3 social studies skill descriptors on places and regions in the New Brunswick curriculum.",
  standards: ["Geography: Places and Regions", "New Brunswick's location, physical features, climate, vegetation and landmarks, and urban and rural places"],
  items: PROVINCE,
});

export const wabanakiNations = bankUnit({
  id: "nb-wabanaki-nations-3",
  title: "Wabanaki Nations of New Brunswick",
  emoji: "🛶",
  blurb: "The Wolastoqey, Mi'kmaq and Peskotomuhkati Nations.",
  parentNote:
    "Practises where the Wolastoqey, Mi'kmaq and Peskotomuhkati nations have their homelands in New Brunswick and how Wabanaki Peoples relate to the natural environment. The content is light, in the present tense, and needs review by Wabanaki partners.",
  standards: ["Geography: Human Systems and Interactions", "Wabanaki Peoples' homelands in New Brunswick and their relationships with the natural environment"],
  items: NATIONS,
});

export const peoplesOfNb = bankUnit({
  id: "nb-peoples-3",
  title: "The Peoples of New Brunswick",
  emoji: "🧭",
  blurb: "First peoples, Acadians, Loyalists and newcomers.",
  parentNote:
    "Practises the diverse peoples of New Brunswick, including the first and founding peoples, and how the province's diversity has changed over time. It follows the Grade 3 social studies skill descriptors on events and peoples and on sources and methods.",
  standards: ["History: Events and Peoples", "the diverse peoples of New Brunswick, including first and founding peoples, and how diversity has changed over time"],
  items: PEOPLES,
});

export const governmentNb = bankUnit({
  id: "nb-government-3",
  title: "Governments in New Brunswick",
  emoji: "🏛️",
  blurb: "Mayors, premiers and the prime minister.",
  parentNote:
    "Practises the purpose, function and structure of municipal, provincial and federal governments. It follows the Grade 3 social studies skill descriptor on power and governance in the New Brunswick curriculum.",
  standards: ["Civics: Power and Governance", "the purpose, function and structure of governments"],
  items: GOVERNMENT,
});

export const citizens = bankUnit({
  id: "nb-citizens-3",
  title: "Citizens Take Part",
  emoji: "🗳️",
  blurb: "Rights, responsibilities and having a say.",
  parentNote:
    "Practises the rights and responsibilities of citizens and how citizens take part in public decisions. It follows the Grade 3 social studies skill descriptors on rights and responsibilities and on civic engagement in the New Brunswick curriculum.",
  standards: ["Civics: Rights and Responsibilities", "the rights and responsibilities of citizens, and how citizens take part in decisions"],
  items: CITIZENS,
});

export const treaties = bankUnit({
  id: "nb-treaties-3",
  title: "Treaties & Reconciliation",
  emoji: "🤝",
  blurb: "Promises, peace and friendship.",
  parentNote:
    "Practises the Peace and Friendship treaties between the Wabanaki Nations and the Crown and the Truth and Reconciliation Commission's Calls to Action. The content is light, in the present tense, and needs review by Wabanaki partners.",
  standards: ["Wabanaki: Treaty Education", "the Peace and Friendship treaties and why they matter, and the Truth and Reconciliation Commission's Calls to Action"],
  items: TREATIES,
});

export const resources = bankUnit({
  id: "nb-resources-3",
  title: "Natural Resources of New Brunswick",
  emoji: "🌲",
  blurb: "Forests, fish, farms and rivers.",
  parentNote:
    "Practises New Brunswick's natural resources, such as forests, fish, farmland, minerals and water power, and what renewable and sustainable mean. It follows the Grade 3 social studies skill descriptor on economics and sustainability in the New Brunswick curriculum.",
  standards: ["Economics: Sustainability", "New Brunswick's natural resources, renewable and non-renewable resources, and using them sustainably"],
  items: RESOURCES,
});
