import type { Unit } from "../types";
import { pick } from "../random";
import { on } from "./kit";
import { e, order, q, sorter, unitOf, type Item } from "./k-g2-kit";

// Ontario Grade 2 science and technology (2022): Life Systems (growth and changes in animals),
// Matter and Energy (properties of liquids and solids), Structures and Mechanisms (simple machines
// and movement) and Earth and Space Systems (air and water in the environment). BC's solids and
// liquids, push and pull, and water units are shared (see g2.ts). BC's life-cycles unit is not,
// because it names BC salmon; Ontario has its own animal life-cycle unit.

// ---------- Think Like a Scientist ----------

const SKILLS: Item[] = [
  q("A scientist tests one thing at a time. Why?", "So they know what caused the result", ["So it takes longer", "So the room is quiet"], "A fair test changes only one thing so we know what made the difference."),
  q("Which tool measures the temperature of water?", e("thermometer", "🌡️"), [e("ruler", "📏"), e("clock", "⏰")], "A thermometer measures how hot or cold something is."),
  q("Which tool would you use to measure how much juice is in a jug?", e("measuring cup", "🥛"), [e("thermometer", "🌡️"), e("ruler", "📏")], "A measuring cup measures liquids."),
  q("What should you do before starting an experiment?", "Read the safety rules", ["Taste the materials", "Run to the sink"], "Health and safety rules come first in every investigation."),
  q("What is an algorithm?", "A set of clear steps", ["A kind of plant", "A loud noise"], "An algorithm is the exact steps a computer or person follows.", { d: 2 }),
  q("A robot's code says: forward, forward, turn right, forward. How many times does it move forward?", "3", ["2", "4"], "Count each “forward”: two, then one more after the turn.", { d: 2 }),
  q("A robot must repeat “step, step” three times. How many steps in all?", "6", ["3", "5"], "Three times 2 is 6.", { d: 2 }),
  q("Your code has a mistake and the robot bumps the wall. What do you do?", "Find and fix the mistake", ["Delete everything", "Hope it works next time"], "Coders test, find bugs and fix them.", { emoji: "🤖" }),
  q("Which one is an emerging technology that changes how we live?", "A robot that vacuums the floor", ["A wooden spoon", "A rock"], "New technologies like robots and smart devices change daily life.", { d: 2 }),
  q("A map app uses coding to…", "find the best way to go", ["grow plants", "make rain"], "Code lets apps work out routes, times and distances.", { d: 2 }),
  q("An engineer builds a bridge model. It breaks. What next?", "Redesign it and test again", ["Say the idea is bad", "Hide the bridge"], "The engineering design process: plan, build, test and improve."),
  q("Which job uses science to solve a real problem?", "A doctor finding out why someone is sick", ["A cloud floating", "A coin falling"], "Science and technology help solve real-world problems.", { d: 2 }),
  q("How can you share what you found in an investigation?", "With a chart, drawing or short talk", ["Keep it secret", "Only whisper it to a rock"], "Scientists tell others in ways that suit the audience.", { d: 2 }),
  q("You are using a hot plate with a grown-up. What should you wear?", "safety goggles and tie back long hair", ["a scarf over your face", "flip-flops only"], "Protect your eyes, hair and clothes around heat.", { d: 3 }),
  q("Which is a good way to use science at home?", "Using a thermometer to check if soup is cool", ["Guessing", "Tasting it hot right away"], "Measuring helps us be safe and accurate.", { d: 3 }),
  q("Different people have invented tools. Why is it good to hear many ideas?", "Different people see different solutions", ["It is faster to copy one", "It is quieter"], "Contributions from many people help science and technology grow.", { d: 3 }),
  q("Which tool would you use to find how long a pencil is?", e("ruler", "📏"), [e("thermometer", "🌡️"), e("measuring cup", "🥛")], "A ruler measures length."),
  q("Which tool helps you see tiny things up close?", e("magnifying glass", "🔍"), [e("ruler", "📏"), e("clock", "⏰")], "A magnifying glass makes small things look bigger."),
  q("Which tool would you use to find how much time a plant takes to sprout?", e("calendar", "📅"), [e("thermometer", "🌡️"), e("ruler", "📏")], "A calendar helps us count days."),
  q("You tested three paper planes. What should you do with your results?", "Write or draw them in a chart", ["Throw the planes away", "Forget them"], "Recording results lets us compare and share what we found.", { d: 2 }),
  q("A robot's code says: turn left, forward, forward. How many moves is that?", "3", ["2", "4"], "Count each instruction: turn, forward, forward.", { d: 2 }),
  q("A robot must repeat “turn, step” four times. How many steps will it take?", "4", ["2", "8"], "It takes one step each time, and it repeats four times.", { d: 2 }),
  q("What should you do if you spill water during an experiment?", "Tell your teacher and wipe it up", ["Leave it", "Hide it under paper"], "Spills can make the floor slippery, so clean them up safely."),
  q("Why do scientists ask questions?", "To find out more about the world", ["To make people stop talking", "Because they must"], "Good questions start an investigation."),
  q("Which one is a good question for an investigation?", "Which paper towel soaks up the most water?", ["What is your favourite colour?", "Who is the tallest person?"], "A good investigation question can be tested with materials.", { d: 2 }),
  q("An engineer wants a bridge to hold more toy cars. What could they do?", "Change the design and test it again", ["Give up", "Paint it"], "Engineers test, improve and test again.", { d: 2 }),
  q("Your code tells a game character to jump, but it walks instead. What is the problem?", "A bug in the code", ["The screen is too big", "The game is sleepy"], "A bug is a mistake in code that we can fix.", { d: 3 }),
  q("Why is it good to work with a partner in an investigation?", "You can share ideas and help each other", ["You can skip the safety rules", "It is always quieter"], "Teams of scientists share different ideas.", { d: 3 }),
];

// ---------- Animal Life Cycles ----------

const BUTTERFLY = order("Put the butterfly's life cycle in order.", "Egg, then a caterpillar (larva), then a chrysalis (pupa), then a butterfly.", [
  ["egg", "🥚"],
  ["caterpillar", "🐛"],
  ["chrysalis"],
  ["butterfly", "🦋"],
]);

const FROG = order("Put the frog's life cycle in order.", "Frog eggs hatch into tadpoles. Tadpoles grow legs and become frogs.", [
  ["frog eggs", "🫧"],
  ["tadpole"],
  ["tadpole with legs"],
  ["adult frog", "🐸"],
]);

const CHICKEN = order("Put the chicken's life cycle in order.", "A hen lays an egg. A chick hatches, grows up and becomes a hen or rooster.", [
  ["egg", "🥚"],
  ["chick", "🐣"],
  ["young chicken"],
  ["adult chicken", "🐔"],
]);

const LIFE: Item[] = [
  q("What does a caterpillar turn into?", e("a butterfly", "🦋"), [e("a bee", "🐝"), e("a spider", "🕷️")], "A caterpillar makes a chrysalis and becomes a butterfly."),
  q("What does a tadpole turn into?", e("a frog", "🐸"), [e("a fish", "🐟"), e("a snake", "🐍")], "Tadpoles grow legs and lose their tails."),
  q("A puppy grows up to be a…", e("dog", "🐕"), [e("cat", "🐈"), e("horse", "🐎")], "Mammals look like smaller versions of their parents."),
  q("Which animal hatches from an egg?", e("a robin", "🐦"), [e("a puppy", "🐶"), e("a calf", "🐮")], "Birds lay eggs. Most mammals are born alive."),
  q("Which animal is born alive and drinks its mother's milk?", e("a kitten", "🐱"), [e("a chick", "🐥"), "a tadpole"], "Mammals feed their young with milk."),
  q("A bird looks very different from its egg. What do we call the baby bird?", "a chick or hatchling", ["a larva", "a tadpole"], "Baby birds hatch from eggs and are often called chicks.", { d: 2 }),
  q("A butterfly's first stage is a…", "egg", ["chrysalis", "adult"], "A butterfly starts as an egg on a leaf.", { d: 2 }),
  q("Which animal changes its shape a lot as it grows up?", "a frog", ["a dog", "a rabbit"], "A frog begins as a tadpole in water and ends up a land-and-water animal.", { d: 2 }),
  q("A caterpillar eats leaves and a butterfly sips nectar. What is different?", "their food and body", ["nothing", "only their name"], "Animals can change in looks and behaviour as they grow.", { d: 2 }),
  q("Which stage of a butterfly cannot fly yet and rests inside a case?", "chrysalis (pupa)", ["egg", "adult"], "The chrysalis is the resting stage before the adult.", { d: 3 }),
  q("A ladybug starts as an egg, becomes a larva, then a pupa, then…", "an adult ladybug", ["a tadpole", "a chick"], "Insects like ladybugs also go through stages.", { emoji: "🐞", d: 3 }),
  q("Which two animals start life in water?", "a frog and a fish", ["a robin and a dog", "a cat and a horse"], "Frogs and most fish begin as eggs in water.", { d: 3 }),
  q("A baby mammal looks like its parents but smaller. Which one is that?", "a kitten", ["a tadpole", "a caterpillar"], "Some animals look like small adults. Others change a lot.", { d: 2 }),
  q("What does a baby frog hatch from?", e("an egg", "🥚"), [e("a seed", "🌱"), e("a nest of twigs", "🪺")], "Frogs lay eggs in water."),
  q("What does a chick come out of?", e("an egg", "🥚"), [e("a cocoon", "🐛"), e("a seed", "🌱")], "Birds lay eggs, and chicks hatch from them."),
  q("A kitten grows up to be a…", e("cat", "🐈"), [e("dog", "🐕"), e("rabbit", "🐇")], "Mammals grow into bigger versions of their parents."),
  q("Which animal has a tail when it is young but not when it is an adult?", e("a frog", "🐸"), [e("a dog", "🐕"), e("a cat", "🐈")], "A tadpole has a tail. The adult frog does not.", { d: 2 }),
  q("A caterpillar is the young stage of a…", "butterfly or moth", ["tadpole", "chick"], "Caterpillars grow, then change inside a chrysalis or cocoon.", { d: 2 }),
  q("What is the next stage in a frog's life cycle? Egg, tadpole, tadpole with legs, then…", "adult frog", ["chrysalis", "chick"], "Tadpoles with legs become frogs.", { d: 2 }),
  q("Which animal drinks milk from its mother when it is young?", e("a calf", "🐮"), [e("a tadpole", "🐸"), e("a chick", "🐥")], "Calves are baby cows. Cows are mammals."),
  q("Which of these animals changes shape the most as it grows?", "a butterfly", ["a rabbit", "a cow"], "A butterfly goes from egg to caterpillar to chrysalis to adult.", { d: 2 }),
  q("Which animal does NOT hatch from an egg?", "a puppy", ["a robin", "a butterfly"], "Puppies are born alive. Birds and insects lay eggs.", { d: 2 }),
  q("How are baby mammals like their parents?", "They look like smaller versions", ["They have wings", "They live in eggs"], "Young mammals look similar to the adults.", { d: 3 }),
  q("Which animal begins its life with gills to breathe underwater?", "a tadpole", ["a puppy", "a robin"], "A tadpole breathes with gills and later grows lungs.", { d: 3 }),
  q("A hen sits on her eggs to keep them…", "warm", ["cold", "wet"], "The warmth helps the chicks grow inside the eggs.", { d: 3 }),
];

// ---------- How Animals Move ----------

const MOVE: Item[] = [
  q("How does a fish move?", "It swims", ["It flies", "It hops"], "Fish use fins and tails to swim.", { emoji: "🐟" }),
  q("How does a bird usually move?", "It flies", ["It swims underground", "It slithers"], "Many birds fly with wings.", { emoji: "🐦" }),
  q("How does a snake move?", "It slithers", ["It hops", "It flies"], "A snake moves its long body in curves.", { emoji: "🐍" }),
  q("How does a frog move on land?", "It hops", ["It slithers", "It glides"], "Frogs use strong back legs to hop.", { emoji: "🐸" }),
  q("How does a snail move?", "It glides slowly on one foot", ["It gallops", "It flies"], "A snail slides on a muscle called a foot.", { emoji: "🐌" }),
  q("Which animal gallops?", e("a horse", "🐎"), [e("a snail", "🐌"), e("a fish", "🐟")], "Horses gallop on four legs."),
  q("Which animal walks on two legs?", e("a person", "🚶"), [e("a dog", "🐕"), e("a cat", "🐈")], "People and many birds walk on two legs.", { d: 2 }),
  q("Which animal swings from branch to branch?", e("a monkey", "🐒"), [e("a fish", "🐟"), e("a snail", "🐌")], "Monkeys climb and swing with arms and tails.", { d: 2 }),
  q("A worm moves by…", "wriggling", ["flying", "galloping"], "Worms stretch and squeeze their bodies to move.", { emoji: "🪱", d: 2 }),
  q("Which body part helps a duck swim?", "webbed feet", ["long ears", "sharp claws"], "Webbed feet push water like paddles.", { emoji: "🦆" }),
  q("A bat can…", "fly", ["gallop", "slither"], "A bat is a mammal with wings made of skin.", { emoji: "🦇", d: 2 }),
  q("An animal that has fins and a tail moves by…", "swimming", ["hopping", "climbing trees"], "Fins and tails push water to swim.", { d: 2 }),
  q("Which animals can both swim and walk?", "ducks and frogs", ["fish and whales", "worms only"], "Ducks and frogs move well in water and on land.", { d: 3 }),
  q("A caterpillar and a butterfly move in different ways. How?", "The caterpillar crawls and the butterfly flies", ["Both swim", "Both gallop"], "An animal can move in different ways at different stages of its life.", { d: 3 }),
  q("How does a rabbit move?", "It hops", ["It slithers", "It swims"], "Rabbits push off with strong back legs.", { emoji: "🐇" }),
  q("How does a whale move?", "It swims", ["It flies", "It gallops"], "Whales are mammals that live in water and swim with their tails.", { emoji: "🐋" }),
  q("How does a spider move?", "It crawls on eight legs", ["It swims", "It flies with wings"], "Spiders walk and climb with eight legs.", { emoji: "🕷️" }),
  q("How does a kangaroo move?", "It hops", ["It slithers", "It swims"], "Kangaroos hop on their strong back legs.", { emoji: "🦘" }),
  q("How does a turtle move on land?", "It walks slowly", ["It flies", "It gallops"], "Turtles walk on four short legs.", { emoji: "🐢" }),
  q("Which animal glides through the air from tree to tree?", e("a flying squirrel", "🐿️"), [e("a snail", "🐌"), e("a fish", "🐟")], "Flying squirrels have skin flaps that let them glide.", { d: 2 }),
  q("Which animal uses wings to fly?", e("a butterfly", "🦋"), [e("a worm", "🪱"), e("a frog", "🐸")], "Butterflies, birds and bats fly."),
  q("Which body part helps a fish swim?", "fins", ["wings", "hooves"], "Fins and tails push a fish through water.", { emoji: "🐟" }),
  q("Which animal wriggles along the ground with no legs?", e("a snake", "🐍"), [e("a horse", "🐎"), e("a bird", "🐦")], "Snakes slither with their long bodies.", { d: 2 }),
  q("An eagle has strong wings. They help it…", "fly", ["swim", "dig"], "Wings let birds fly.", { emoji: "🦅" }),
  q("A seal has flippers. They help it…", "swim", ["fly", "climb trees"], "Flippers push through water.", { emoji: "🦭", d: 2 }),
  q("Which animal crawls along the ground and climbs plants on six legs?", e("a beetle", "🪲"), [e("a dolphin", "🐬"), e("an eagle", "🦅")], "Insects have six legs and many of them crawl.", { d: 3 }),
  q("A deer runs fast to escape danger. What helps it?", "long, strong legs", ["wings", "fins"], "Strong legs help it run.", { emoji: "🦌", d: 3 }),
];

const MOVE_SORT = sorter({
  prompt: "How does it move? Tap an animal, then its basket.",
  hint: "Think about where it moves and what body parts it uses.",
  bins: [
    { id: "swim", label: "Swims", emoji: "🌊" },
    { id: "fly", label: "Flies", emoji: "☁️" },
    { id: "crawl", label: "Crawls or slithers", emoji: "🐛" },
  ],
  items: [
    { label: "salmon", emoji: "🐟", bin: "swim" },
    { label: "dolphin", emoji: "🐬", bin: "swim" },
    { label: "eagle", emoji: "🦅", bin: "fly" },
    { label: "owl", emoji: "🦉", bin: "fly" },
    { label: "snake", emoji: "🐍", bin: "crawl" },
    { label: "caterpillar", emoji: "🐛", bin: "crawl" },
  ],
});

// ---------- Animal Adaptations ----------

const ADAPT: Item[] = [
  q("A polar bear has thick fur and fat. This helps it…", "stay warm in the cold", ["swim in a hot spring", "hide in a green forest"], "An adaptation is a body feature or behaviour that helps an animal survive.", { emoji: "🐻‍❄️" }),
  q("A rabbit has long ears. What does this help it do?", "hear danger", ["swim faster", "dig for fish"], "Long ears help a rabbit hear predators.", { emoji: "🐇" }),
  q("A duck's webbed feet help it…", "swim", ["climb trees", "dig tunnels"], "Webbed feet work like paddles.", { emoji: "🦆" }),
  q("An owl has big eyes. This helps it…", "see in the dark", ["hear underwater", "dig"], "Big eyes let in more light for night hunting.", { emoji: "🦉" }),
  q("A porcupine has sharp quills. They help it…", "stay safe from predators", ["fly", "swim"], "Quills are a defence.", { emoji: "🦔" }),
  q("A beaver has big front teeth. They help it…", "cut down trees", ["fly", "swim underground only"], "Beavers gnaw wood to build dams and lodges.", { emoji: "🦫" }),
  q("A tree frog is green and sits on a leaf. Why is it hard to see?", "Its colour matches the leaf", ["It is invisible", "It is very tiny"], "Camouflage is a colour or pattern that matches the surroundings.", { d: 2 }),
  q("A snowshoe hare turns white in winter. This is…", "camouflage in snow", ["a way to swim", "a way to climb"], "A white coat matches snow so predators cannot see it as easily.", { d: 2 }),
  q("Many bears sleep through much of the winter. This behaviour is called…", "hibernating", ["migrating", "hunting"], "Hibernating saves energy when food is hard to find.", { d: 2 }),
  q("Geese fly south in the fall. This behaviour is called…", "migrating", ["hibernating", "swimming"], "Migrating means moving to find better weather or food.", { d: 2 }),
  q("Which is a physical adaptation (a body part)?", "A bird's beak", ["A bird flying south", "A squirrel burying nuts"], "A physical adaptation is part of an animal's body. A behaviour is something an animal does.", { d: 2 }),
  q("Which is a behavioural adaptation (something an animal does)?", "A squirrel burying nuts", ["A moose's antlers", "A fish's scales"], "Hiding food for later is something an animal does.", { d: 2 }),
  q("Which of these does an animal keep its whole life (constant)?", "Its number of legs", ["Its baby fur", "Its egg shell"], "Some features stay the same and others change as an animal grows.", { d: 3 }),
  q("A cub grows from small to big. This is a feature that…", "changes", ["never changes", "is the same as a rabbit's"], "Size changes as animals grow. Many features such as the number of legs stay the same.", { d: 3 }),
  q("A moose has long legs. How could this help it live in a snowy forest?", "It can walk through deep snow", ["It can swim like a fish", "It can fly"], "Long legs help a moose step over snow and logs.", { d: 3 }),
  q("A skunk sprays a bad smell. This helps it…", "keep predators away", ["find food", "build a nest"], "A smell like this is a defence.", { emoji: "🦨" }),
  q("A woodpecker has a strong, sharp beak. It helps the bird…", "peck into trees to find insects", ["swim in lakes", "carry fish"], "The beak is the right shape for the job.", { emoji: "🐦" }),
  q("A fish has gills. They help it…", "breathe underwater", ["fly", "dig tunnels"], "Gills take oxygen from water.", { emoji: "🐟" }),
  q("A turtle has a hard shell. It helps the turtle…", "stay safe", ["fly", "dig tunnels"], "The shell protects the turtle.", { emoji: "🐢" }),
  q("A giraffe has a long neck. It helps the giraffe…", "reach leaves high in the trees", ["swim", "dig"], "A long neck reaches food other animals cannot reach.", { emoji: "🦒" }),
  q("A caribou has wide hooves. They help it…", "walk on snow without sinking", ["swim underwater", "climb trees"], "Wide hooves spread out the weight, like snowshoes.", { d: 2 }),
  q("An arctic fox has a white coat in winter. This helps it…", "blend in with the snow", ["swim in lakes", "fly"], "Camouflage helps hide from predators and from prey.", { d: 2 }),
  q("A chipmunk stores seeds for winter. This is a…", "behaviour", ["body part", "food"], "Storing food is something an animal does.", { d: 2 }),
  q("Which is a physical adaptation (a body part)?", "A deer's fur coat", ["A goose flying south", "A bear sleeping"], "Fur is part of the animal's body.", { d: 2 }),
  q("Which is a behavioural adaptation (something an animal does)?", "A bird building a nest", ["A fish's fins", "A turtle's shell"], "Building a nest is something a bird does.", { d: 2 }),
  q("Many frogs burrow in mud and sleep through winter. Why?", "To stay safe from the cold", ["To catch fish", "To fly"], "Sleeping through winter saves energy when it is cold.", { d: 3 }),
  q("A fish has a smooth shape. How does this help it?", "It slips through water easily", ["It can climb", "It can fly"], "The shape of its body helps it move.", { d: 3 }),
  q("A bird's feathers keep it warm. Feathers are a…", "physical adaptation", ["behaviour", "habitat"], "Feathers are part of the bird's body.", { d: 3 }),
  q("A hawk has sharp claws. They help it…", "grab food", ["swim", "dig tunnels"], "Claws help hawks catch prey."),
  q("A mole has big front paws. They help it…", "dig tunnels", ["fly", "swim fast"], "Strong paws are good for digging.", { d: 2 }),
];

// ---------- Animals and People ----------

const ANIMALS_PEOPLE: Item[] = [
  q("Bees visit flowers and help plants make seeds and fruit. This is a…", "positive impact", ["negative impact", "no impact"], "Bees carry pollen from flower to flower, which helps food crops grow.", { emoji: "🐝" }),
  q("Mosquito bites can make people itchy. This is a…", "negative impact", ["positive impact", "kind of food"], "Some animals bother people. Wearing long sleeves can help.", { d: 2 }),
  q("A guide dog helps a person who cannot see. This is a…", "positive impact", ["negative impact", "weather"], "Animals can help people in many ways.", { emoji: "🦮" }),
  q("Raccoons get into garbage bins. How can people help prevent this?", "Use bins with tight lids", ["Leave bins open", "Feed the raccoons"], "Securing garbage keeps wild animals safe and our streets clean.", { emoji: "🦝" }),
  q("A new road is built through a forest. What might happen to animals?", "They may lose their homes", ["Nothing", "They get taller"], "Building can take away places where animals live.", { d: 2 }),
  q("Some roads have a wildlife crossing. Why?", "So animals can cross safely", ["To grow flowers", "To park trucks"], "Bridges and tunnels help animals cross roads without being hit.", { d: 2 }),
  q("Which action helps animals that live near a pond?", "Keep the water clean", ["Throw garbage in", "Pour oil in"], "Clean water keeps animals healthy."),
  q("Which action can harm birds?", "Leaving litter such as fishing line", ["Putting up a bird house", "Planting native flowers"], "Litter can tangle or hurt birds.", { emoji: "🐦" }),
  q("A wetland is a home to frogs and birds. Why should we protect it?", "Many animals need it to live", ["It is a place to dump trash", "It is useless"], "Wetlands also help clean water and hold floods.", { d: 3 }),
  q("People feed ducks bread. Why is it not a good idea?", "It is not healthy food for ducks", ["Ducks do not eat", "Bread is too heavy"], "Wild animals do best with the natural food they eat.", { d: 2 }),
  q("A farm raises cows and chickens. How do people depend on them?", "for food such as milk and eggs", ["for flying", "for building bridges"], "Farm animals give food and other materials.", { d: 2 }),
  q("Bats eat many insects, including mosquitoes. How can bats help people?", "by eating insects that bother us", ["by making honey", "by growing trees"], "Bats eat large numbers of insects each night.", { emoji: "🦇", d: 3 }),
  q("Why is it better to watch wild animals from far away?", "It keeps them and us safe", ["They cannot see us", "It makes them sleepy"], "Getting too close can scare or hurt wild animals.", { d: 2 }),
  q("Cutting down forests can lead to…", "animals needing new homes", ["more animals right away", "no change at all"], "Habitat loss affects many kinds of animals.", { d: 3 }),
  q("Earthworms mix up the soil in a garden. This is a…", "positive impact", ["negative impact", "kind of weather"], "Worms help soil stay healthy for plants.", { emoji: "🪱" }),
  q("Deer eat the plants in a garden. For the gardener, this is a…", "negative impact", ["positive impact", "kind of food for people"], "Animals can sometimes damage crops or flowers.", { d: 2 }),
  q("A bird eats insects that harm the plants in a garden. This is a…", "positive impact", ["negative impact", "no impact"], "Birds can help gardeners.", { d: 2 }),
  q("Which action helps a bird that lives in your yard?", "Putting up a nesting box", ["Cutting down all the trees", "Leaving litter"], "Giving animals safe homes helps them.", { emoji: "🐦" }),
  q("Pet cats can hurt wild birds. How can owners help?", "Keep cats indoors or on a leash", ["Let them roam at night", "Feed the birds to the cats"], "Keeping cats close protects wildlife.", { d: 2 }),
  q("How can you help animals when you go camping?", "Take your garbage home", ["Leave food on the ground", "Feed the wild animals"], "Animals can get sick or hurt from garbage and human food.", { d: 2 }),
  q("People build a pond for frogs. What will it help?", "Frogs and other animals to have a home", ["Frogs to fly", "The road to be longer"], "A clean pond gives animals a place to live.", { d: 2 }),
  q("A farmer's cows give us…", "milk", ["wool", "honey"], "Animals can give us food.", { emoji: "🐄" }),
  q("Sheep give us wool. How can wool help people?", "It can be made into warm clothes", ["It can be made into a boat", "It can be eaten as an apple"], "People use wool for hats, mittens and blankets.", { emoji: "🐑", d: 2 }),
  q("Which of these is a way that an animal helps people?", "A sled dog pulls a sled", ["A wasp sting hurts", "A mouse chews wires"], "Some animals do work for people.", { d: 2 }),
  q("When trees are cut down, which animals may need to find a new home?", "Squirrels and birds that live in them", ["Fish in the ocean", "Animals in a zoo"], "Animals depend on their habitat for food and shelter.", { d: 3 }),
  q("Why do we use a recycling bin?", "It keeps litter out of animal homes", ["It feeds animals", "It makes litter fun"], "Recycling helps keep the places where animals live clean.", { d: 2 }),
  q("Some people plant flowers for butterflies. This helps butterflies to…", "find food", ["swim", "dig"], "Flowers give butterflies nectar.", { emoji: "🦋", d: 2 }),
  q("A beaver builds a dam that floods a road. This is a…", "negative impact for people", ["positive impact for people", "no impact on anything"], "Animals can change the land in ways that cause problems for people.", { d: 3 }),
  q("A beaver dam makes a pond where frogs and ducks live. This is a…", "positive impact for other animals", ["negative impact for ducks", "no impact on any animal"], "A beaver changes the land and creates homes for many animals.", { d: 3 }),
];

// ---------- Mixtures and Materials ----------

const MIXTURES: Item[] = [
  q("Salt is stirred into water. What happens?", "It dissolves and seems to disappear", ["It turns into a rock", "It stays in a lump and never mixes"], "Dissolving means the salt mixes in with the water.", { emoji: "🧂" }),
  q("Which one makes a mixture of a liquid and a solid?", "Orange juice with pulp", ["Plain water only", "An empty cup"], "A mixture has more than one kind of matter.", { d: 2 }),
  q("When oil and water are mixed, what happens?", "They stay separate", ["They become one smooth liquid", "They turn solid"], "Oil floats on top of water."),
  q("Which will sink in water?", e("a rock", "🪨"), ["a cork", "a leaf"], "Heavy, dense solids sink. Light ones float."),
  q("Which will float in water?", e("a wooden stick", "🪵"), [e("a rock", "🪨"), e("a coin", "🪙")], "Wood is less dense than water, so it floats."),
  q("Which absorbs water?", e("a sponge", "🧽"), [e("a plastic cup", "🥤"), e("a rain boot", "🥾")], "Absorb means to soak up."),
  q("Which one repels water (water rolls off)?", e("a raincoat", "🧥"), [e("a sponge", "🧽"), e("a paper towel", "🧻")], "Repel means to push away. Raincoats keep you dry."),
  q("A liquid always takes the shape of…", "its container", ["a cube", "nothing"], "Liquids flow and fill the shape of the container.", { d: 2 }),
  q("A solid, like a block, keeps its…", "own shape", ["container's shape", "sound"], "Solids have their own shape.", { d: 2 }),
  q("Why does a boat made of heavy steel float?", "Its shape holds a lot of air", ["Steel is very light", "Because of its colour"], "The big hollow shape spreads out its weight.", { d: 3 }),
  q("You want to dry a spill. Which is best?", "a paper towel", ["a plastic bag", "a metal spoon"], "Paper towels absorb liquids.", { d: 2 }),
  q("Which keeps your feet dry in a puddle?", "rubber boots", ["cotton socks", "paper shoes"], "Rubber repels water.", { emoji: "🥾" }),
  q("Lemonade is made from water, lemon juice and sugar. It is a…", "mixture", ["solid", "rock"], "Mixtures are made when different things are combined.", { emoji: "🍋", d: 2 }),
  q("Which mixture can you separate with a strainer?", "pasta and water", ["salt dissolved in water", "juice and water"], "A strainer catches solid pieces and lets liquid through.", { d: 3 }),
  q("When you add cereal to milk, you make…", "a mixture", ["a new kind of animal", "a solid block"], "A mixture is useful for foods and drinks.", { d: 2 }),
  q("Sugar is stirred into warm water. What happens?", "It dissolves into the water", ["It turns into ice", "It floats on top forever"], "Dissolving means the sugar mixes in so we cannot see the pieces.", { emoji: "🍬" }),
  q("Which will sink in water?", e("a metal key", "🔑"), [e("a wooden spoon", "🥄"), e("a leaf", "🍃")], "A key is heavy for its size, so it sinks."),
  q("Which will float in water?", e("a rubber duck", "🦆"), [e("a rock", "🪨"), e("a coin", "🪙")], "Light, hollow things float."),
  q("Which material absorbs water best?", e("a cotton towel", "🛁"), [e("a plastic bag", "🛍️"), e("a glass cup", "🥛")], "Absorb means to soak up."),
  q("Which material repels water?", e("a plastic bag", "🛍️"), [e("a paper towel", "🧻"), e("a sponge", "🧽")], "Repel means water runs off instead of soaking in."),
  q("A fruit salad has apples, grapes and melon. It is a…", "mixture", ["solid block", "gas"], "A mixture is made of different things put together.", { emoji: "🍉", d: 2 }),
  q("Which mixture can you separate by picking the pieces out by hand?", "trail mix", ["salt in water", "juice"], "You can pick out the nuts, raisins and seeds.", { d: 2 }),
  q("You add sand to water and stir. What happens when you stop?", "The sand sinks to the bottom", ["The sand dissolves", "The sand turns to salt"], "Sand does not dissolve, so it settles at the bottom.", { d: 2 }),
  q("A liquid is poured from a tall glass into a short bowl. What changes?", "its shape", ["the kind of liquid", "its colour"], "A liquid takes the shape of its container.", { d: 2 }),
  q("Which one is a liquid?", e("milk", "🥛"), [e("a brick", "🧱"), e("a block of wood", "🪵")], "Liquids flow and can be poured."),
  q("Which one is a solid?", e("a brick", "🧱"), [e("juice", "🧃"), e("rain", "🌧️")], "Solids keep their own shape."),
  q("A snow boot should keep your feet dry. What property should it have?", "It should repel water", ["It should absorb water", "It should dissolve"], "Boots that repel water keep snow and puddles out.", { d: 3 }),
  q("Which job needs a material that absorbs water?", "wiping up a spill", ["making a raincoat", "building a boat"], "Sponges and cloths soak up liquid.", { d: 2 }),
  q("Why is a life jacket made to float?", "It keeps a person up in the water", ["It makes a person sink", "It is for decoration"], "Floating materials help keep people safe near water.", { d: 3 }),
  q("When you stir cocoa powder into milk, you make…", "a mixture", ["a rock", "a new animal"], "Cocoa and milk are combined, so it is a mixture.", { d: 2 }),
];

// ---------- Safety Symbols ----------

const SAFETY: Item[] = [
  q("A bottle has a skull and crossbones. What does it mean?", "Poison. Do not eat or drink it.", ["Safe to drink", "Food"], "The skull and crossbones means poison.", { emoji: "☠️" }),
  q("A container has a flame symbol. What does it mean?", "It can catch fire easily", ["It is cold", "It is food"], "The flame symbol means flammable.", { emoji: "🔥" }),
  q("A container shows a burst or explosion. What does it mean?", "It can explode", ["It is a toy", "It is a rainbow"], "An explosive symbol warns the container can burst.", { emoji: "💥" }),
  q("A bottle shows a liquid eating a hand and metal. What does it mean?", "It can burn skin or damage things", ["It is a juice", "It is soap for toys"], "That symbol means corrosive.", { d: 2 }),
  q("Why do we need safety symbols on products?", "To warn us about danger", ["To decorate them", "To make them heavy"], "Symbols give information even to people who cannot read the words."),
  q("You find a bottle with a poison symbol. What do you do?", "Do not touch it and tell an adult", ["Open it", "Taste it"], "Leave it alone and tell a grown-up."),
  q("Where should household cleaners be kept?", "Up high or locked away, closed tightly", ["Open on the floor", "In a lunch box"], "Store dangerous liquids safely out of reach of young children.", { d: 2 }),
  q("A bottle of paint thinner has a flame symbol. Keep it away from…", "heat and fire", ["ice cubes", "paper"], "Flammable things can catch fire from heat or sparks.", { d: 2 }),
  q("Why do we not mix cleaning products?", "They can make dangerous fumes", ["They taste bad", "It takes too long"], "Mixing chemicals can be harmful.", { d: 3 }),
  q("What should you do with an old can of paint?", "Take it to a household hazardous waste drop-off", ["Pour it down the drain", "Throw it in a river"], "Some liquids need special disposal so they do not harm water and living things.", { d: 3 }),
  q("Which liquid is safe to drink?", "water from a clean tap", ["window cleaner", "gasoline"], "Never drink products from cleaning or car supplies.", { emoji: "🚰" }),
  q("Safe or not? A bottle that looks like juice has a poison symbol.", "Not safe", ["Safe", "Maybe safe"], "A bottle that looks like a drink can still be dangerous. Always check the symbol.", { d: 2 }),
  q("A bottle has a symbol of a hand with a drop eating into it. What should you do?", "Keep away and let an adult handle it", ["Touch the liquid", "Pour it in a cup"], "That symbol warns that it can burn skin.", { d: 2 }),
  q("A spray can has a flame symbol. Where should you NOT use it?", "Near a candle or stove", ["Outside in the open air", "Where there is no heat"], "Flammable things can catch fire near a flame.", { d: 2 }),
  q("A bottle with a poison symbol is on the kitchen floor. What should you do?", "Tell an adult right away", ["Open it", "Pour it into a bowl"], "Poison is dangerous, so get a grown-up to help."),
  q("The poison symbol on a container tells us that…", "it is not safe to eat or drink", ["it is good for the garden", "it is a sweet drink"], "The skull and crossbones is a warning.", { emoji: "☠️" }),
  q("What does a warning symbol on a product help us do?", "Keep ourselves and others safe", ["Make it taste better", "Make it look brighter"], "Symbols warn us about hazards before we get hurt."),
  q("Why is a symbol useful on a bottle?", "People who cannot read yet can still understand it", ["It makes the bottle taller", "It makes the lid easier to open"], "Pictures can warn us even if we cannot read the words."),
  q("Where is the safest place for a cleaning spray?", "A high shelf or a locked cupboard", ["On the bedroom floor", "In a toy box"], "Keep dangerous products out of reach of young children.", { d: 2 }),
  q("A container is marked with the flame symbol. What should you keep it away from?", "heat, sparks and fire", ["cold water", "paper"], "Flammable liquids can catch fire easily.", { d: 2 }),
  q("You see a liquid in an unlabelled bottle. What should you do?", "Do not touch it and ask an adult", ["Smell it closely", "Taste a tiny drop"], "If you do not know what it is, do not use it.", { d: 2 }),
  q("Why do we put the lid back on a bottle of cleaner?", "To keep it from spilling or being swallowed", ["To make it louder", "To save the lid"], "A closed lid is safer.", { d: 2 }),
  q("Used batteries and paint should go…", "to a special drop-off", ["down the drain", "into a lake"], "Some things can harm water, soil and living things if thrown out the wrong way.", { d: 3 }),
  q("Which of these is a safe way to use a product with a hazard symbol?", "Follow the directions with an adult", ["Mix it with other cleaners", "Let a baby play with it"], "Always follow the directions and ask for help.", { d: 3 }),
  q("A bottle shows a symbol of a burst. What might happen if it is heated?", "It could explode", ["It would turn into juice", "It would get quieter"], "That symbol warns about a container that can burst.", { d: 3 }),
  q("Why should household cleaner never be put into a drink bottle?", "Someone might drink it by mistake", ["It would taste sweet", "The bottle would break"], "Always keep products in their own labelled containers.", { d: 3 }),
];

// ---------- Simple Machines ----------

const MACHINES: Item[] = [
  q("A seesaw is a…", "lever", ["pulley", "screw"], "A lever is a bar that turns on a point.", { emoji: "⚖️" }),
  q("A ramp is an…", "inclined plane", ["wheel and axle", "pulley"], "An inclined plane is a slope that helps move things up or down.", { emoji: "🛝" }),
  q("A wheel on a wagon is a…", "wheel and axle", ["wedge", "lever"], "A wheel turns around an axle.", { emoji: "🛞" }),
  q("A flagpole uses a…", "pulley", ["wedge", "lever"], "A pulley uses a wheel and rope to lift things.", { emoji: "🚩" }),
  q("An axe or a knife is a…", "wedge", ["pulley", "wheel and axle"], "A wedge cuts or splits things.", { emoji: "🪓" }),
  q("A jar lid turns on a…", "screw", ["wedge", "pulley"], "A screw is an inclined plane wrapped around a post.", { d: 2 }),
  q("Which one is NOT one of the six simple machines?", "a battery", ["a lever", "a wedge"], "The six: lever, inclined plane, wedge, pulley, wheel and axle, screw."),
  q("Why is it easier to roll a heavy box up a ramp than to lift it?", "A ramp takes less force", ["The ramp is magic", "It gets lighter"], "An inclined plane makes you push over a longer distance with less force.", { d: 2 }),
  q("A child uses a wheelbarrow to move soil. What does the wheel do?", "makes it easier to move", ["makes it heavier", "makes it float"], "A wheel and axle makes moving heavy things easier.", { emoji: "🛒", d: 2 }),
  q("A bottle opener is a…", "lever", ["screw", "wedge"], "A bottle opener is a lever that pries off the cap.", { d: 2 }),
  q("Which machine would you use to raise a bucket from a well?", "pulley", ["wedge", "screw"], "A rope over a wheel lets you pull down to lift.", { d: 2 }),
  q("A doorstop is a…", "wedge", ["lever", "wheel and axle"], "A wedge is thick at one end and thin at the other.", { d: 3 }),
  q("Why do simple machines help?", "They make jobs easier", ["They make jobs harder", "They make noise"], "A machine can reduce the effort needed or change the direction of a force."),
  q("A bike has wheels. Which simple machine is this?", "wheel and axle", ["wedge", "screw"], "Wheels turn around axles.", { emoji: "🚲", d: 2 }),
  q("People use ramps at buildings. Who do ramps help the most?", "a person using a wheelchair or a stroller", ["only birds", "no one"], "Ramps make buildings easier for many people to enter.", { d: 3 }),
  q("A pair of scissors uses two…", "levers and wedges", ["pulleys", "ramps only"], "The blades are wedges that cut, and the handles work as levers.", { d: 3 }),
  q("A playground slide is an…", "inclined plane", ["wedge", "pulley"], "A slide is a slope.", { emoji: "🛝" }),
  q("A screw holds things together. It is a simple machine called a…", "screw", ["lever", "pulley"], "A screw is a slope wrapped around a post.", { d: 2 }),
  q("A crowbar is used to pry things open. It is a…", "lever", ["wedge", "screw"], "A crowbar is a lever.", { d: 2 }),
  q("A fork pushed into food is a type of…", "wedge", ["pulley", "wheel and axle"], "The tines work like wedges.", { d: 3 }),
  q("An elevator in a tall building moves up and down on ropes over wheels. Which machine does this use?", "pulley", ["wedge", "screw"], "Ropes over wheels are pulleys.", { d: 3 }),
  q("A doorknob turns on a…", "wheel and axle", ["wedge", "inclined plane"], "Turning the knob turns an axle.", { d: 3 }),
  q("A wheelchair ramp is a…", "inclined plane", ["screw", "lever"], "A ramp is a slope that makes it easier to go up.", { d: 2 }),
  q("A zipper uses small…", "wedges", ["pulleys", "levers"], "The slider is a wedge that moves the teeth together.", { d: 3 }),
  q("Which simple machine is a wheel with a groove and a rope?", "pulley", ["screw", "wedge"], "A pulley lifts by pulling a rope over a wheel."),
  q("A swing set seesaw is a lever. Where is the turning point called?", "the fulcrum", ["the ramp", "the wheel"], "A lever turns on a point called a fulcrum.", { d: 3 }),
  q("A pencil sharpener blade is a…", "wedge", ["pulley", "wheel and axle"], "A wedge cuts or splits.", { d: 2 }),
  q("A skateboard has wheels that turn on…", "axles", ["wedges", "ramps"], "Wheels turn around axles.", { emoji: "🛹", d: 2 }),
  q("A bottle cap that twists on is a…", "screw", ["lever", "pulley"], "Threads on a bottle are a kind of screw.", { d: 2 }),
  q("Which one makes moving a heavy box up to a truck easier?", "a ramp", ["a feather", "a puddle"], "A ramp is an inclined plane.", { d: 2 }),
];

// ---------- Air and Water ----------

const AIRWATER: Item[] = [
  q("Which one is true about air?", "It takes up space", ["It has no effect on anything", "It is a solid"], "A balloon fills up and gets bigger because air takes up space.", { emoji: "🎈" }),
  q("Can you see air?", "No, but you can feel wind", ["Yes, always blue", "Yes, always white"], "Air is invisible, but we feel it move as wind."),
  q("What do all living things need?", "air and water", ["only toys", "only sand"], "People, plants and animals depend on air and water."),
  q("Which is a state of water?", "ice, liquid and vapour (gas)", ["rock and metal", "red and blue"], "Water can be a solid (ice), a liquid, or a gas (water vapour).", { d: 2 }),
  q("What happens to water when it gets very cold?", "It freezes into ice", ["It turns to sand", "It disappears forever"], "Below 0 °C, water freezes."),
  q("What happens to puddle water on a hot day?", "It evaporates into the air", ["It turns to stone", "It moves to the Moon"], "Heat turns liquid water into water vapour.", { d: 2 }),
  q("Which one is a source of fresh water?", "a lake", ["the ocean", "a sandbox"], "Lakes, rivers and groundwater are mostly fresh water.", { d: 2 }),
  q("Which action wastes water?", "Leaving the tap running", ["Turning off the tap", "Using a rain barrel"], "Using less water is a good habit.", { d: 2 }),
  q("Which action uses less water?", "A short shower", ["A very long shower", "Leaving the hose on"], "Short showers save water.", { emoji: "🚿" }),
  q("Trees and plants take in carbon dioxide and give out…", "oxygen", ["smoke", "sand"], "Plants help make the air healthy to breathe.", { d: 3 }),
  q("Smoke from a factory or car fumes can make air…", "dirty", ["cleaner", "colder than ice"], "Pollution affects air quality and our health.", { d: 2 }),
  q("In some places people must carry water from a well or river. Why?", "They may not have water pipes at home", ["They like carrying", "Water is not needed there"], "Clean drinking water is not available everywhere in the world.", { d: 3 }),
  q("Which is NOT a way people use water at home?", "to build a rocket", ["to drink", "to wash"], "People use water for drinking, cooking, washing and more.", { d: 2 }),
  q("Why do we need to keep rivers and lakes clean?", "People, plants and animals need clean water", ["To keep fish out", "To make it freeze"], "Pollution in water can harm every living thing that uses it.", { d: 2 }),
  q("How much of Earth's water is fresh water we can drink?", "A small amount", ["All of it", "None"], "Most of Earth's water is salty ocean water.", { d: 3 }),
  q("What is wind?", "moving air", ["moving water", "falling snow"], "We cannot see air, but we can feel it move.", { d: 2 }),
  q("Which one needs air to work?", "a campfire", ["a rock", "a puddle"], "Fire needs air to burn.", { d: 3 }),
  q("When water gets very warm and turns into a gas, it becomes…", "water vapour", ["ice", "sand"], "Water vapour is water in the form of a gas.", { d: 2 }),
  q("Frost on a window is water in the form of…", "ice", ["gas", "air"], "Cold air can freeze water into ice.", { d: 2 }),
  q("Where does rain come from?", "clouds", ["rocks", "grass"], "Water in clouds falls as rain.", { emoji: "🌧️" }),
  q("What happens to puddles after the sun comes out?", "They dry up", ["They get bigger", "They turn into ice"], "Heat makes the water evaporate.", { d: 2 }),
  q("Which one is a good way to save water?", "Turn off the tap while you brush your teeth", ["Run the tap all day", "Wash the car every hour"], "Small habits save a lot of water.", { emoji: "🪥" }),
  q("A fish lives in a pond. What does it need from the water?", "clean water to live in", ["to be on land", "snow"], "Fish need clean water to breathe and live.", { emoji: "🐟" }),
  q("Why do we hang wet clothes out to dry?", "The water evaporates into the air", ["The water goes into the ground only", "The clothes make water"], "Heat and moving air dry the clothes.", { d: 2 }),
  q("A balloon is blown up. What does the balloon show?", "Air takes up space", ["Air has no weight and no space", "Air is a liquid"], "The balloon gets bigger because air fills it.", { emoji: "🎈" }),
  q("Which one is dirty air?", "smoke from a fire", ["a breeze in a forest", "a spring wind"], "Smoke and fumes make air unhealthy to breathe.", { d: 2 }),
  q("How can people help keep the air clean?", "Walk or bike instead of riding in a car", ["Burn garbage", "Leave a car running"], "Fewer fumes mean cleaner air.", { d: 3 }),
  q("Most of the water on Earth is…", "salt water in the oceans", ["fresh water in puddles", "ice cream"], "Only a small part is fresh water.", { d: 3 }),
  q("When water freezes it turns from a liquid to a…", "solid", ["gas", "cloud"], "Ice is the solid form of water.", { d: 2 }),
  q("When ice melts it turns from a solid to a…", "liquid", ["gas", "rock"], "Melting changes ice back into liquid water.", { d: 2 }),
];

// ---------- Units ----------

export const units: Unit[] = [
  {
    id: "think-like-a-scientist",
    title: "Think Like a Scientist",
    emoji: "🔬",
    blurb: "Tools, fair tests, safety and code",
    standards: on("A1.1–A1.5, A2.1, A2.2, A3.1", "investigation skills, fair tests, safety, sharing findings, simple code and how science helps us"),
    parentNote: "How scientists and engineers work: tools for measuring, fair tests, safety, sharing results, simple algorithms and how new technology changes everyday life.",
    generate: unitOf(SKILLS),
  },
  {
    id: "animal-life-cycles",
    title: "Animal Life Cycles",
    emoji: "🦋",
    blurb: "Eggs, larvae, tadpoles and chicks",
    standards: on("B2.3, B2.4", "life cycles of insects, amphibians, birds and mammals, and how appearance and behaviour change"),
    parentNote: "Life cycles of butterflies, frogs, chickens and mammals, and how some animals change a lot while others look like small adults.",
    generate: unitOf(LIFE, [(d) => pick([BUTTERFLY, FROG, CHICKEN])(d)]),
  },
  {
    id: "how-animals-move",
    title: "How Animals Move",
    emoji: "🐍",
    blurb: "Swim, fly, hop, slither",
    standards: on("B2.2", "the ways different animals move (locomotion)"),
    parentNote: "How animals swim, fly, hop, slither, crawl and gallop, and the body parts that help them move.",
    generate: unitOf(MOVE, [MOVE_SORT]),
  },
  {
    id: "animal-adaptations",
    title: "Animal Adaptations",
    emoji: "🦉",
    blurb: "Features and behaviours that help",
    standards: on("B2.1, B2.5", "features that stay the same or change, and adaptations that help animals survive"),
    parentNote: "Body features (fur, quills, beaks, camouflage) and behaviours (hibernating, migrating, storing food) that help animals survive, and which features change as animals grow.",
    generate: unitOf(ADAPT),
  },
  {
    id: "animals-and-people",
    title: "Animals & People",
    emoji: "🐝",
    blurb: "How we affect each other",
    standards: on("B1.1, B1.2", "impacts animals have on people and the environment, and human activities that affect animals and their homes"),
    parentNote: "Helpful and bothersome ways animals affect us, and how building, litter and clean water affect animals and the places they live.",
    generate: unitOf(ANIMALS_PEOPLE),
  },
  {
    id: "mixtures-and-materials",
    title: "Mixtures & Materials",
    emoji: "🧪",
    blurb: "Dissolve, sink, float, absorb",
    standards: on("C2.2, C2.5, C2.6", "properties of liquids and solids, useful mixtures, and whether solids sink, float, absorb or repel water"),
    parentNote: "Mixing liquids and solids (dissolving, separating), what sinks or floats, and which materials soak up or push away water.",
    generate: unitOf(MIXTURES),
  },
  {
    id: "safety-symbols",
    title: "Safety Symbols",
    emoji: "☠️",
    blurb: "Warnings on everyday products",
    standards: on("C1.1, C2.7", "using, storing and disposing of liquids at home safely, and the meaning of international safety symbols"),
    parentNote: "Reading hazard symbols (poison, flammable, explosive, corrosive) on household products, and storing and throwing out dangerous liquids safely.",
    generate: unitOf(SAFETY),
  },
  {
    id: "simple-machines",
    title: "Simple Machines",
    emoji: "⚙️",
    blurb: "Levers, ramps, wedges and more",
    standards: on("D1.1, D2.3–D2.5", "the six simple machines, where we use them, and how they make jobs easier"),
    parentNote: "The six simple machines (lever, inclined plane, wedge, pulley, wheel and axle, screw), where we see them every day, and how they make a job take less effort.",
    generate: unitOf(MACHINES),
  },
  {
    id: "air-and-water-for-life",
    title: "Air & Water for Life",
    emoji: "💧",
    blurb: "Properties, states and using wisely",
    standards: on("E1.1, E1.3, E2.1, E2.4, E2.5", "properties of air and water, states of water, how living things depend on them, and using clean water wisely"),
    parentNote: "Air takes up space, the three states of water, why all living things need clean air and water, and how people can protect and share water.",
    generate: unitOf(AIRWATER),
  },
];
