import { bankUnit, type Q } from "../own";

// Grade 7 social studies, the Maritimes and Mi’kma’ki: treaties, settlement, political change, changing society,
// World War I and Maritime communities today. Indigenous, African Nova Scotian and Acadian content is factual,
// in the present tense for living communities, and needs partner review.

const TREATIES: Q[] = [
  ["What is the name of the Mi’kmaw homeland?", "Mi’kma’ki", ["Acadia", "Rupert’s Land"], "Mi’kma’ki is the territory the Mi’kmaq have lived in for thousands of years."],
  ["Which of these places are part of Mi’kma’ki?", "Nova Scotia and Prince Edward Island", ["Alberta and Manitoba", "Yukon and Nunavut"], "Mi’kma’ki includes Nova Scotia, Prince Edward Island and much of New Brunswick, plus parts of Quebec, Newfoundland and Maine."],
  ["Which word is used for the people, the Mi’kmaq, as an adjective, as in “the ___ language”?", "Mi’kmaw", ["Mi’kmaqs", "Mikmak"], "Mi’kmaq names the people. Mi’kmaw describes things, such as the Mi’kmaw language."],
  ["The Peace and Friendship Treaties between the Mi’kmaq and the British Crown were made between about 1725 and…", "1779", ["1867", "1920"], "The treaties date from 1725 to 1779, long before Confederation."],
  ["What did the Peace and Friendship Treaties mainly promise?", "Peace, and respect for each side’s way of life", ["That the Mi’kmaq gave up their land", "That all Mi’kmaw people would move to reserves"], "These treaties were about keeping peace and friendship. They did not hand over the land."],
  ["Netukulimk is the Mi’kmaw approach to…", "taking what you need from the land and sea in a way that sustains them", ["selling as many fish as possible", "keeping people out of the forest"], "Netukulimk means using resources in a way that keeps the land, the sea and the people well."],
  ["On what date is Treaty Day marked in Nova Scotia?", "October 1", ["July 1", "December 6"], "Treaty Day on October 1 honours the treaties and the relationship they made."],
  ["The Indian Act, first passed in 1876, gave the federal government…", "control over many parts of the lives of First Nations people", ["a way for First Nations to run Canada", "no power at all over First Nations"], "The Act let the government make rules about reserves, membership and daily life, often without asking First Nations."],
  ["What is a reserve?", "Land set aside for a First Nation under the Indian Act", ["A national park for tourists", "A farm owned by the province"], "Reserves were often small compared with the land the Mi’kmaq had lived on and used."],
  ["Many Mi’kmaw communities lost land as settlers arrived. A main reason was that…", "settlers and governments took land without honouring the treaties", ["the Mi’kmaq chose to leave Mi’kma’ki", "no one lived there before"], "The Mi’kmaq were already living on and caring for the land. Settlement pushed them off much of it."],
  ["The residential school system took Indigenous children away from their families in order to…", "teach them to leave their languages and cultures behind", ["give them a free holiday", "train them as teachers for their own Nation"], "This was harmful. Children were punished for speaking their own languages."],
  ["Where was the residential school in Nova Scotia located?", "Shubenacadie", ["Yarmouth", "Sydney"], "The Shubenacadie Indian Residential School opened in 1930 and closed in 1967."],
  ["How did residential schools affect Mi’kmaw language?", "Many children lost chances to learn and use it", ["It spread faster", "Nothing changed"], "Being kept from family and punished for speaking the language made it harder to pass on."],
  ["Today, how is the Mi’kmaw language being kept strong?", "It is taught in Mi’kmaw schools and communities", ["It is no longer spoken anywhere", "It is only found in old books"], "Mi’kmaw language teachers and communities are working hard to keep the language alive."],
  ["Who are the Mi’kmaq today?", "Living communities across Mi’kma’ki", ["A people who lived only long ago", "A single family"], "The Mi’kmaq are many communities, living and working in Nova Scotia and beyond."],
  ["September 30 is the National Day for Truth and Reconciliation. What is it for?", "Remembering residential school survivors and those who did not come home", ["Celebrating Confederation", "Honouring the first European ships"], "The day asks Canadians to learn about residential schools and to honour survivors and their families."],
  ["In 1999 the Supreme Court of Canada’s Marshall decision said that Mi’kmaw people have a treaty right to…", "fish and trade for a moderate livelihood", ["fish without any limits", "keep all of the province’s fish"], "The ruling said the old treaties still count, and the right is to earn a moderate livelihood, not unlimited.", true],
  ["Why did the Marshall decision matter so much to Mi’kmaw communities?", "It confirmed that the treaties still apply today", ["It ended all treaties", "It set the Treaty Day date"], "Courts recognized that treaties made in the 1700s are still valid.", true],
  ["A treaty right is different from a rule made later by a government because the treaty…", "was an agreement between nations", ["was a rule written by one side alone", "only lasted one year"], "Treaties were agreements. Policies like the Indian Act were laws the government made on its own.", true],
  ["A government policy ended a community’s practice of fishing. What is a fair way to describe the effect?", "It could cut a community off from food, income and culture", ["It had no effect on anyone", "It only helped the community"], "When a right to fish is denied, people lose food, work and a way of life.", true],
  ["Which action best supports reconciliation?", "Learning the truth and honouring the treaties", ["Pretending the past never happened", "Telling survivors to move on"], "Reconciliation starts with listening, learning and keeping promises.", true],
  ["The 1725 treaty was written down by the British. Why is it important to also listen to Mi’kmaw oral history?", "It shares the Mi’kmaw understanding of the agreements", ["Oral history is never accurate", "The written treaties do not exist"], "Different people can remember and understand an agreement differently, so both views matter.", true],
  ["Who made the Peace and Friendship Treaties with the Mi’kmaq?", "the British Crown", ["the United States Congress", "the Hudson’s Bay Company"], "The treaties were agreements between the Mi’kmaq and the British Crown."],
  ["Membertou, a Mi’kmaw community, is in which part of Nova Scotia?", "Cape Breton", ["the South Shore", "the Annapolis Valley"], "Membertou is in Sydney, on Cape Breton Island."],
  ["How many Mi’kmaw communities are there in Nova Scotia?", "13", ["30", "8"], "Thirteen Mi’kmaw communities are found across the province."],
  ["People wear an orange shirt on September 30 to remember…", "children who went to residential schools", ["a hockey team", "a harvest festival"], "Orange Shirt Day honours survivors and the children who did not come home."],
  ["The Mi’kmaq have lived in Mi’kma’ki for…", "thousands of years", ["about 150 years", "about 20 years"], "Mi’kmaw people were here long before any Europeans arrived."],
  ["A government says a treaty is too old to count. Which fact best answers this?", "Canadian courts, as in the Marshall decision, have said the treaties still apply", ["Old agreements always expire after 100 years", "Treaties only count if they are printed in colour"], "Treaties made in the 1700s are still valid today.", true],
];

const MARITIMES: Q[] = [
  ["Which year was Port-Royal, an early French settlement, founded?", "1605", ["1755", "1867"], "Port-Royal was founded in 1605 in what is now Nova Scotia."],
  ["Who were the Acadians?", "French-speaking settlers who made homes in Mi’kma’ki", ["Scottish fishers", "British soldiers"], "Acadians came from France and built farming communities, often near the Mi’kmaq."],
  ["How did Acadian farmers get good farmland from salt marshes?", "They built dykes with gates to keep the tide out", ["They cut down tall mountains", "They dug mines under the marsh"], "Dykes and wooden gates called aboiteaux kept out the salt water so crops could grow."],
  ["What was the Expulsion of the Acadians?", "The forced removal of Acadians from their homes by the British", ["A holiday for Acadian farmers", "A treaty between two kingdoms"], "Starting in 1755, thousands of Acadians were sent away from their land."],
  ["The Expulsion of the Acadians took place from 1755 to…", "1764", ["1812", "1900"], "It went on for about nine years."],
  ["What happened to many Acadian farms after the Expulsion?", "They were given to new settlers", ["They were left alone for 100 years", "They became national parks"], "Newcomers, including New England Planters, were invited to take over the cleared land."],
  ["After the Expulsion, some Acadians returned to the Maritimes. What did many find?", "Their old farms belonged to others", ["Everything just as they left it", "A new city built for them"], "Many returned to other parts of the region and built new communities."],
  ["The New England Planters came to Nova Scotia in the 1760s mainly to…", "farm the empty Acadian land", ["fight in a war", "find gold"], "They were invited by the colony to take up farmland, including dyked marshland."],
  ["Black Loyalists came to Nova Scotia in the 1780s after the…", "American Revolution", ["Halifax Explosion", "Confederation debates"], "They had been promised freedom and land for supporting the British side."],
  ["Which Nova Scotia community was once the largest free Black settlement in North America?", "Birchtown", ["Pictou", "Baddeck"], "Birchtown, near Shelburne, was settled by Black Loyalists."],
  ["Many Black Loyalists were promised land but waited years or got poor land. What does this show?", "A promise made to them was not fully kept", ["They all got large farms", "They did not want land"], "Black Loyalists faced unfair treatment even though they had been promised equal treatment.", true],
  ["In 1773 the ship Hector brought settlers from Scotland to which Nova Scotia town?", "Pictou", ["Lunenburg", "Truro"], "The Hector sailed to Pictou with Scottish Highlanders, many of whom spoke Gaelic."],
  ["Why did many Scottish Highlanders leave Scotland?", "Poor land and few chances to make a living", ["To find the Northwest Passage", "To join the Acadians"], "Hard times at home made them look for new land overseas."],
  ["The Maroons arrived in Halifax in 1796. They had come from…", "Jamaica", ["Newfoundland", "Quebec"], "The Maroons were people of African descent who were sent from Jamaica to Nova Scotia."],
  ["After the War of 1812, Black refugees from the United States came to Nova Scotia. What did they hope to find?", "Freedom and a new start", ["Gold to mine", "Free cars"], "Many settled around Halifax in communities such as Hammonds Plains and Preston."],
  ["Which of these was a major early industry in the Maritimes?", "Fishing", ["Making computer chips", "Oil drilling in the desert"], "The cod fishery and the sea have long fed and employed people here."],
  ["Why did wooden shipbuilding grow in the Maritimes in the 1800s?", "There was plenty of timber, and ships were in demand", ["Metal was cheaper than wood", "Ships were banned from the sea"], "Forests supplied timber, and trade across the ocean needed ships."],
  ["Why is a dyked marsh a good place to farm?", "The soil is rich", ["The tide covers it every day", "It is always frozen"], "Marsh soil is rich, and dykes keep the sea out of the fields."],
  ["Who benefitted most when the Acadian land was handed over to the Planters?", "The new settlers", ["The Acadians who had farmed it", "The Mi’kmaq who lived nearby"], "The Planters gained farms while the Acadians lost theirs.", true],
  ["Which statement best describes the Black Loyalists’ experience?", "They helped build communities despite unequal treatment", ["They were given everything they needed", "They quickly became the richest people in the colony"], "Black Loyalists worked hard, but often received poorer land and less support.", true],
  ["Why might the same event, such as the arrival of settlers, look different to the Mi’kmaq than to the settlers?", "The settlers gained land while the Mi’kmaq lost access to it", ["Everyone gained the same things", "The Mi’kmaq were not present"], "History looks different depending on who is telling it and what they gained or lost.", true],
  ["Compare the Acadians and the Planters. What is true about both groups?", "Both farmed the same marshland at different times", ["Both arrived on the Hector", "Both fought in the War of 1812"], "The Acadians farmed the dyked marsh first, and the Planters took it over after the Expulsion.", true],
  ["Lunenburg was founded in 1753 by settlers called Foreign Protestants. Many came from…", "German-speaking parts of Europe", ["Jamaica", "Japan"], "Many of these settlers came from areas where German was spoken."],
  ["Halifax was founded in 1749 by the…", "British, on Mi’kmaw land", ["Spanish", "Russians"], "Halifax was built in Mi’kma’ki as a British base."],
  ["Which language did many Highland Scots bring to Cape Breton?", "Scottish Gaelic", ["Latin", "Portuguese"], "Gaelic songs and stories are still shared in Cape Breton today."],
  ["Where were some Acadians sent after being expelled?", "Britain, France and the British colonies to the south", ["Alberta and Saskatchewan", "The Pacific coast"], "Families were scattered to many places and were often separated."],
  ["Dykes took many years to build. What does this show about Acadian farmers?", "They planned and worked together over a long time", ["They hurried and quit", "They used modern machines"], "Building dykes took teamwork and patience.", true],
  ["Why do historians read several sources about the Expulsion?", "Different people recorded different views of the same events", ["All sources say the same thing", "Sources are always wrong"], "Comparing sources gives a fuller picture of what happened.", true],
];

const POLITICAL: Q[] = [
  ["In 1758 Nova Scotia held the first elected House of Assembly in…", "what is now Canada", ["North America’s largest city", "the British Isles"], "Nova Scotia’s House of Assembly was the first elected assembly in what became Canada."],
  ["What is representative government?", "People elect others to make laws on their behalf", ["A king decides everything", "Anyone can vote on every rule"], "Voters choose representatives who speak for them."],
  ["Which Nova Scotian is known for defending freedom of the press in 1835?", "Joseph Howe", ["Samuel Cunard", "Alexander Graham Bell"], "Howe published articles criticizing local officials and was found not guilty at his libel trial."],
  ["Freedom of the press means newspapers can…", "report and criticize without being punished for telling the truth", ["print whatever the government tells them", "never print opinions"], "A free press helps people stay informed about their government."],
  ["Responsible government means the governing group must…", "have the support of the elected assembly", ["be chosen by the monarch alone", "never change"], "The cabinet had to keep the support of the elected representatives."],
  ["Which colony first won responsible government in the British Empire, in 1848?", "Nova Scotia", ["Quebec", "Newfoundland"], "Joseph Howe and others worked for it, and Nova Scotia was first in 1848."],
  ["Before responsible government, who held much of the power in a colony?", "A governor sent from Britain", ["The voters directly", "The railway companies"], "The governor and appointed councillors could ignore the elected assembly."],
  ["The 1864 conference in Charlottetown was first planned to talk about…", "joining the Maritime colonies together", ["building the Halifax Citadel", "ending the fur trade"], "Delegates from Canada asked to join, which led to talk of a bigger union."],
  ["What was the Quebec Conference of 1864 for?", "Planning the details of a new country", ["Choosing a new queen", "Ending a war"], "Delegates wrote resolutions that became the plan for Confederation."],
  ["Which four colonies became the first provinces of Canada in 1867?", "Nova Scotia, New Brunswick, Ontario and Quebec", ["Nova Scotia, PEI, Manitoba and Alberta", "Ontario, Quebec, Newfoundland and British Columbia"], "The new Dominion of Canada began with four provinces."],
  ["Confederation happened in which year?", "1867", ["1758", "1918"], "Canada became a country on July 1, 1867."],
  ["Some Nova Scotians opposed Confederation. One reason was that they feared…", "losing control over their own taxes and trade", ["there would be too many railways", "the colony would be too small"], "Many thought that decisions would be made far away in Canada, to their disadvantage."],
  ["Which Nova Scotian leader spoke against Confederation?", "Joseph Howe", ["Sir John A. Macdonald", "Samuel de Champlain"], "Howe believed Nova Scotia was not getting a fair deal.", true],
  ["Which province joined Canada in 1873?", "Prince Edward Island", ["Newfoundland", "Alberta"], "PEI joined after Charlottetown had hosted the conference in 1864."],
  ["Prince Edward Island first hesitated to join Confederation. Which reason is most likely?", "It worried about debt and about being a small voice in a big country", ["It had no coast", "It wanted to join the United States only"], "Small colonies feared they would have little influence.", true],
  ["Early voting rules in the Maritimes usually favoured…", "men who owned property", ["every adult", "only children"], "Many people, including women and most poor men, could not vote."],
  ["In which year did women in Nova Scotia win the right to vote in provincial elections?", "1918", ["1867", "1948"], "Nova Scotia gave women the provincial vote in 1918."],
  ["Why did it take so long for women to win the vote?", "Many people believed women should not take part in politics", ["Women did not want to vote", "Voting had not been invented"], "Women and their supporters campaigned for years to change the law.", true],
  ["How does having the right to vote help a community?", "More people have a say in decisions", ["It stops all disagreements", "It makes laws unnecessary"], "When more people can vote, leaders must listen to more voices.", true],
  ["Why did Confederation need the support of the Maritime colonies?", "A railway link and a larger market were hoped for", ["The colonies owned all the gold", "They controlled the Rocky Mountains"], "Leaders hoped for a stronger country with trade and a railway between the colonies.", true],
  ["Who can vote in Canadian federal elections today?", "Citizens aged 18 or older", ["Only landowners", "Only men"], "Voting is a right of Canadian citizens who are 18 or older."],
  ["A person elected to the Nova Scotia legislature is called an…", "MLA", ["admiral", "auditor"], "MLA stands for Member of the Legislative Assembly."],
  ["The leader of a provincial government is called the…", "premier", ["mayor", "principal"], "Each province has a premier."],
  ["Province House in Halifax is where the Nova Scotia…", "legislature meets", ["fish market opens", "steel is made"], "Province House is the home of the provincial law-making body."],
  ["Joseph Howe's 1835 trial was about…", "a letter his newspaper printed that criticized local officials", ["a ship collision", "a mine accident"], "His not-guilty verdict became a landmark for freedom of the press."],
  ["Before 1867, Nova Scotia was…", "a British colony", ["part of the United States", "an independent country"], "Nova Scotia joined Confederation in 1867."],
  ["Why can a law passed by an elected assembly be fairer than a rule made by one governor?", "More voices have a chance to shape it", ["It is always faster", "It never changes"], "Assemblies debate and vote, so many views are heard.", true],
  ["Mi’kmaw people were not part of the Confederation talks. Why does that matter today?", "Decisions were made about their homeland without their voice", ["They had no homeland", "They wrote the plan"], "Leaving people out of decisions can have lasting effects.", true],
];

const SOCIETY: Q[] = [
  ["Which fuel was mined in Cape Breton and Pictou County?", "Coal", ["Uranium", "Diamonds"], "Coal mines were a major source of jobs in these areas."],
  ["In the late 1800s, steel was made in which Cape Breton city?", "Sydney", ["Yarmouth", "Truro"], "The steel plant in Sydney was a large employer for many years."],
  ["What did the railway change for Maritime communities?", "It carried goods and people faster across the region", ["It stopped all shipping", "It ended coal mining"], "Railways such as the Intercolonial linked the Maritimes to other parts of Canada."],
  ["The Bluenose, a famous wooden schooner, was built in which Nova Scotia town?", "Lunenburg", ["Antigonish", "Windsor"], "The Bluenose was launched in Lunenburg in 1921."],
  ["Industrialization means…", "work shifting toward factories and machines", ["everyone returning to farms", "ships being banned"], "As factories and mines grew, many people moved to towns for work."],
  ["Why did many people leave the Maritimes for places like Boston or Ontario in the early 1900s?", "To find work and better pay", ["Because the sea dried up", "Because it was against the law to stay"], "When jobs were scarce, many moved away."],
  ["Why did workers start forming unions?", "To bargain together for safer work and fair pay", ["To ban all machines", "To help bosses pay less"], "Workers had more power together than alone."],
  ["Why were mines dangerous for the people who worked in them?", "Cave-ins and gas could hurt workers", ["The tunnels were too bright", "Workers had to swim"], "Accidents showed why safety rules mattered."],
  ["Africville was a community in which city?", "Halifax", ["Sydney", "Moncton"], "Africville was a Black community on the Bedford Basin."],
  ["When did Black families begin settling in Africville?", "In the 1800s", ["In the 1960s", "In 2010"], "The community grew over many decades before it was demolished."],
  ["In the 1960s, what happened to Africville?", "The City of Halifax demolished it and moved the people", ["It became a national park", "It merged with Dartmouth"], "Families lost their homes and a community they had built."],
  ["In 2010 the City of Halifax did what about Africville?", "It officially apologized", ["It rebuilt every house", "It changed its name"], "The apology acknowledged the harm done to the families."],
  ["Viola Desmond is remembered for…", "refusing to leave the main floor of a theatre in New Glasgow", ["building a ship", "leading a mining strike"], "In 1946 she took a stand against racial segregation. She is on the Canadian $10 bill."],
  ["Viola Desmond’s action helped show that…", "unfair rules based on race should be challenged", ["theatres should be bigger", "movies should be cheaper"], "Her story helped Canadians think about equality."],
  ["Why were women’s jobs often limited in the early 1900s?", "Many employers and laws expected women to stay home", ["Women were not allowed to read", "There were no schools"], "Women worked in homes, canneries, schools and shops, but had fewer choices.", true],
  ["A coal mine in a town closes. What is one helpful response for the community?", "Train workers for new jobs and attract new businesses", ["Pretend nothing happened", "Close all the schools"], "Communities can plan new work and learning."],
  ["A fishery shrinks because there are fewer fish. What is a good step for a fishing community?", "Support new ways to earn a living while protecting the fish", ["Fish even more", "Tell everyone to leave"], "Protecting fish helps the fishery return.", true],
  ["Which statement is a fair way to describe why Africville was demolished?", "The city made a decision that hurt a community that had little say", ["The families all asked to leave", "There were no houses at all"], "Many residents were not treated fairly and did not want to leave.", true],
  ["Why is it important for a town to listen to the people affected by a big change?", "They know best what they need", ["They always make mistakes", "It takes less time not to ask"], "Good decisions include those who live with the results.", true],
  ["Why might a community be sad when an old industry closes?", "It is tied to jobs, pride and history", ["Nobody cares about work", "The building is too tall"], "Industries shape how a community sees itself, so change can feel big.", true],
  ["A schooner is a…", "sailing ship", ["coal car", "fishing net"], "The Bluenose was a schooner."],
  ["Why did towns grow near coal mines and steel plants?", "Jobs drew workers and their families", ["Mines made the weather warmer", "Laws banned farms"], "People move where there is work."],
  ["A strike is when workers…", "stop working together to ask for change", ["start a new job", "move abroad"], "Workers use strikes to ask for safer conditions or fair pay."],
  ["Which Nova Scotian appears on the Canadian $10 bill?", "Viola Desmond", ["Joseph Howe", "Rita Joe"], "Her portrait appears on the bill."],
  ["The Antigonish Movement helped people in Maritime communities by…", "teaching adults to work together through co-operatives", ["building steel mills", "banning unions"], "It brought adult education and co-operatives to fishing and farming communities.", true],
  ["Why did the railway help industries grow?", "Goods could reach faraway markets", ["It made coal disappear", "It closed ports"], "Trains carried coal, steel and fish to buyers."],
  ["Before cars and planes, how did most goods travel between Maritime ports?", "By ship", ["By rocket", "By submarine tunnel"], "Coastal shipping was a main way to move goods."],
  ["Which question helps a community respond well to change?", "Who is affected, and what do they need?", ["Who can we blame?", "How can we ignore it?"], "Starting with people's needs leads to better responses.", true],
];

const WW1: Q[] = [
  ["Why was Halifax so important during World War I?", "It was a major port and a base where ships formed convoys", ["It was the national capital", "It was far from the sea"], "Ships carrying soldiers and supplies gathered in Halifax Harbour and the Bedford Basin."],
  ["What is a convoy?", "A group of ships that travel together for safety", ["A kind of ship repair", "A festival"], "Travelling together protected ships from enemy submarines."],
  ["When was the Halifax Explosion?", "December 6, 1917", ["July 1, 1867", "October 1, 1999"], "It happened on the morning of December 6, 1917."],
  ["What caused the Halifax Explosion?", "Two ships collided in the harbour, and one was full of explosives", ["A volcano erupted", "A mine collapsed"], "The Mont-Blanc, carrying munitions, and the Imo collided in the Narrows."],
  ["About how many people died in the Halifax Explosion?", "About 2000", ["About 20", "About 200 000"], "Roughly 2000 people died and many thousands were hurt."],
  ["Which city sent help quickly after the Halifax Explosion?", "Boston", ["Vancouver", "Paris"], "Trains and ships from Boston and other places brought doctors, nurses and supplies."],
  ["Each year Nova Scotia sends a Christmas tree to Boston to say…", "thank you for the help in 1917", ["welcome to the city", "we are sorry"], "The tree is a thank you for the help Boston sent."],
  ["Who lived near the explosion and suffered the most?", "People in the north end of Halifax", ["People in Toronto", "People in Winnipeg"], "Homes and workplaces in Richmond and the north end were destroyed."],
  ["What was the No. 2 Construction Battalion?", "A battalion of Black Canadian volunteers", ["A fishing fleet", "A team of nurses"], "It was formed in 1916 after many Black volunteers were turned away from other units."],
  ["Where was the headquarters of the No. 2 Construction Battalion?", "Pictou, Nova Scotia", ["Winnipeg, Manitoba", "Vancouver, B.C."], "Pictou was the headquarters, and the unit recruited across Canada."],
  ["Why was the No. 2 Construction Battalion formed separately?", "Because of racism that kept Black men out of many units", ["Because Black men did not want to fight", "Because there were too many ships"], "Black volunteers faced unfair barriers in 1914 to 1916."],
  ["What did the No. 2 Construction Battalion do in France?", "Forestry and construction work", ["Flew planes", "Ran the railways"], "They cut timber and built things that the army needed."],
  ["Conscription means…", "the government can require people to serve in the military", ["people volunteer to join", "soldiers leave the army"], "Conscription began in 1917 and many people were divided about it."],
  ["Why was conscription controversial?", "Some people did not want to be forced to fight", ["It was a new sport", "It was a new tax on ships"], "Canadians disagreed deeply about whether people should be made to serve."],
  ["How did the war change life for families at home?", "Many worried about loved ones and women took on more work", ["Nothing changed", "Everyone moved to Halifax"], "Women worked in factories and offices while men were away."],
  ["During the war, what happened to demand for ships and goods from Maritime industries?", "It grew", ["It disappeared", "It stayed exactly the same"], "Shipyards, steel and coal supplied the war effort."],
  ["After the Halifax Explosion, many people needed shelter in winter. Which help was most urgent?", "Housing, food and medical care", ["New theatres", "Tourist maps"], "A blizzard followed the explosion, which made it worse.", true],
  ["How did the explosion change Halifax over the long term?", "The city rebuilt and planned new housing", ["Halifax was never rebuilt", "The harbour became a lake"], "The Hydrostone district was built to rebuild after the disaster.", true],
  ["What does the story of Boston’s help show?", "People from far away can help a community in a crisis", ["Nobody helps strangers", "Only soldiers can help"], "Aid came from many places.", true],
  ["World War I ended on November 11 in which year?", "1918", ["1914", "1945"], "The war ended with the armistice on November 11, 1918.", true],
  ["The war was far from the Maritimes, so why did it affect them so much?", "Ports, ships, industries and young volunteers were part of the war effort", ["No one from the Maritimes joined", "The Maritimes were taken over"], "The region’s seaports and workers supported the war.", true],
  ["Which two ships collided in the Halifax Explosion?", "The Mont-Blanc and the Imo", ["The Bluenose and the Hector", "The Titanic and the Atlantic"], "Mont-Blanc was carrying explosives."],
  ["A munitions ship carries…", "explosives and ammunition", ["apples", "lumber"], "Munitions are supplies used for fighting."],
  ["Many Canadians wear a poppy in the days before…", "Remembrance Day", ["Canada Day", "Treaty Day"], "The poppy is worn to remember those who died in war."],
  ["Governments asked people to buy Victory Bonds to…", "lend money to help pay for the war", ["pay for new schools only", "give gifts to soldiers"], "The money was paid back later with interest."],
  ["Train dispatcher Vince Coleman is remembered for sending a message that…", "warned incoming trains to stop", ["announced the end of the war", "named the Mont-Blanc"], "His warning helped save lives after the explosion.", true],
  ["Why was it dangerous for ships to cross the Atlantic in World War I?", "Enemy submarines attacked ships", ["Icebergs were banned", "There were no ports"], "This is why ships travelled in convoys."],
  ["Why might a historian use diaries and photographs about the Explosion?", "They show what people saw and felt at the time", ["They replace all other sources", "They are never real"], "First-hand sources add detail that reports may miss.", true],
];

const TODAY: Q[] = [
  ["Which of these is one of Nova Scotia’s most valuable catches today?", "Lobster", ["Moose", "Bison"], "Lobster is one of the province’s most valuable catches."],
  ["What is aquaculture?", "Raising fish or shellfish in the water", ["Mining under the sea", "Painting boats"], "Mussels, oysters and salmon are raised in farms along the coast."],
  ["Why is the ocean important to Maritime communities?", "It provides jobs, food and trade", ["It is only for swimming", "It has no effect on people"], "The ocean supports fishing, shipping and tourism."],
  ["Which is a popular place for tourists to see in Nova Scotia?", "The Cabot Trail", ["The Rocky Mountains", "Niagara Falls"], "The Cabot Trail winds around the coast of Cape Breton."],
  ["The Annapolis Valley is best known for…", "growing apples and other crops", ["mining diamonds", "building airplanes"], "Orchards and farms fill this fertile valley."],
  ["The Bay of Fundy has very high tides. How could tides help make energy?", "Moving water can turn turbines", ["Tides make rocks hotter", "Tides burn fuel"], "Tidal turbines are tested in the Bay of Fundy.", true],
  ["Which of these is a form of renewable energy?", "Wind", ["Coal", "Oil"], "Wind and tides renew themselves, but coal and oil do not."],
  ["Why do some young people leave rural communities?", "To find work or study elsewhere", ["Because rural towns are not allowed to have schools", "Because there is no ocean"], "Fewer jobs and services can lead people to leave."],
  ["What could a rural town do to encourage young people to stay or return?", "Create jobs, housing and internet access", ["Close its schools", "Raise the price of everything"], "Jobs and services give people a reason to settle."],
  ["Why do many Maritime communities welcome newcomers?", "Newcomers bring skills, workers and new ideas", ["Because the region has no room", "Because they are told to"], "Immigrants help communities grow and fill needed jobs."],
  ["A new family from another country moves to town. What is a welcoming thing to do?", "Say hello and invite them to a community event", ["Avoid them", "Ask them to leave"], "Small acts of kindness help newcomers feel at home."],
  ["Which languages are being revitalized in the Maritimes?", "Mi’kmaw, Acadian French and Gaelic", ["Latin and Greek", "Only English"], "Communities teach and celebrate these languages today."],
  ["Where in Nova Scotia can people learn Gaelic language and music at the Gaelic College?", "St. Ann’s, Cape Breton", ["Digby", "Yarmouth"], "The Gaelic College in St. Ann’s teaches Gaelic songs, language and arts."],
  ["Why is it important to keep a language alive?", "It carries a community’s stories and ways of seeing the world", ["Languages have no purpose", "It costs nothing to forget it"], "Language connects people to their history and identity."],
  ["What does climate change mean for coastal communities?", "Rising seas and stronger storms can harm homes and roads", ["Fewer waves", "No more fog"], "Higher seas can flood low land.", true],
  ["In 2022 a strong storm called Hurricane Fiona struck Atlantic Canada. What did it show?", "Communities need to be ready for severe storms", ["Storms never reach Nova Scotia", "Storms only happen in winter"], "Fiona brought high winds and damage to many coastal communities.", true],
  ["A village on the coast has more flooding each year. Which response is helpful?", "Plan for the water with stronger shorelines or moving buildings", ["Ignore it", "Build homes closer to the shore"], "Planning ahead protects people and property.", true],
  ["Why is housing a challenge in many Maritime communities today?", "Homes can cost too much for many families", ["Everyone owns three houses", "There are no builders"], "When prices climb, it is hard for families to find a place to live."],
  ["Which helps a community make more homes available?", "Building more homes that people can afford", ["Tearing down homes", "Stopping all construction"], "More affordable homes give families more choices.", true],
  ["Why is it sensible to protect fish stocks?", "So the fishery can last for future generations", ["Because fish are expensive", "Because fish cannot swim"], "Taking only what the ocean can replace keeps the fishery alive.", true],
  ["A town depends on tourism, but a storm damages its main beach. What is a good community response?", "Repair the area and also build other ways to earn a living", ["Give up on tourism forever", "Blame visitors"], "Several sources of income make a community stronger.", true],
  ["A person who moves to a new country to live is an…", "immigrant", ["astronaut", "anthropologist"], "Immigrants bring skills and ideas to their new communities."],
  ["Which industry brings visitors to see the Cabot Trail, lighthouses and beaches?", "tourism", ["mining", "forestry"], "Tourists spend money on food, places to stay and local crafts."],
  ["Why can a ferry matter to a Maritime community?", "It links islands and coasts for people and goods", ["It makes tides stop", "It creates fish"], "Ferries connect places that roads do not reach."],
  ["National Acadian Day, celebrated by Acadian communities, is on…", "August 15", ["October 1", "July 1"], "Acadian communities mark the day with music and a tintamarre parade."],
  ["Wind farms and solar panels help communities by…", "making electricity without burning fossil fuels", ["using more coal", "stopping the tides"], "Renewable energy produces fewer emissions."],
  ["A mill closes in a small town. Which response looks at both now and later?", "Help workers now and plan new industries for later", ["Wait and see", "Move all the workers out"], "Good plans meet short-term needs and build for the future.", true],
  ["Why do some communities protect a salt marsh instead of building on it?", "It guards against floods and is home to wildlife", ["Marshes are made of concrete", "Building is illegal everywhere"], "Marshes soak up water and protect the shore.", true],
];

export const mikmawTreaties = bankUnit({
  id: "ns-mikmaw-treaties-7",
  title: "Mi’kma’ki & Treaty Rights",
  emoji: "📜",
  blurb: "Learn about Mi’kma’ki, the treaties and what happened when promises were not kept.",
  parentNote:
    "Practises Grade 7 social studies about Mi’kma’ki, the Peace and Friendship Treaties and the impact of government policies on Mi’kmaw communities. Content is factual and needs review with Mi’kmaw partners.",
  standards: [
    "Reflect on the impact of government policies and the denial of treaty rights on Mi’kmaw communities and individuals in Mi’kma’ki",
    "Mi’kma’ki, the treaties and how policies affected Mi’kmaw communities",
  ],
  items: TREATIES,
});

export const maritimesHistory = bankUnit({
  id: "ns-maritimes-history-7",
  title: "Opportunities & Challenges, Long Ago",
  emoji: "⛵",
  blurb: "Who came to the Maritimes, what they hoped for and what they faced.",
  parentNote:
    "Practises Grade 7 social studies about settlement in the Maritimes: Acadians, Planters, Black Loyalists, Scottish Highlanders and others, and who gained or lost. Ties to the Nova Scotia Grade 7 history of the Maritimes.",
  standards: [
    "Reflect on historical opportunities and challenges in the Maritimes",
    "Early settlement and the chances and hardships groups faced",
  ],
  items: MARITIMES,
});

export const politicalChange = bankUnit({
  id: "ns-political-change-7",
  title: "Political Change in the Maritimes",
  emoji: "🏛️",
  blurb: "From the first assembly to Confederation and the right to vote.",
  parentNote:
    "Practises Grade 7 social studies on representative and responsible government, Confederation and voting rights, as taught in the Nova Scotia curriculum.",
  standards: [
    "Evaluate the impacts of political changes in the Maritimes up to the early 20th century",
    "Government, Confederation and who could vote",
  ],
  items: POLITICAL,
});

export const changingSociety = bankUnit({
  id: "ns-changing-society-7",
  title: "Changing Times in the Maritimes",
  emoji: "🏭",
  blurb: "Mines, mills, ships and how communities respond to change.",
  parentNote:
    "Practises Grade 7 social studies on industrialization, work, Africville and how communities respond to change. Ties to the Nova Scotia curriculum.",
  standards: [
    "Create a response to changing societal conditions in the Maritimes",
    "Industry, work, Africville and community responses to change",
  ],
  items: SOCIETY,
});

export const worldWarOne = bankUnit({
  id: "ns-world-war-1-7",
  title: "World War I & the Maritimes",
  emoji: "⚓",
  blurb: "Halifax, the Explosion and how the war touched the Maritimes.",
  parentNote:
    "Practises Grade 7 social studies on the impact of World War I on the Maritimes, including the Halifax Explosion and the No. 2 Construction Battalion. Ties to the Nova Scotia curriculum.",
  standards: [
    "Evaluate the impacts of World War I on the Maritimes",
    "Halifax in wartime, the Explosion and life at home",
  ],
  items: WW1,
});

export const maritimeCommunitiesToday = bankUnit({
  id: "ns-communities-today-7",
  title: "Maritime Communities Today",
  emoji: "🏘️",
  blurb: "Opportunities and challenges in Maritime communities now, and what they can do.",
  parentNote:
    "Practises Grade 7 social studies on present-day opportunities and challenges, such as the ocean economy, newcomers, language revitalization and climate change. Ties to the Nova Scotia curriculum.",
  standards: [
    "Create responses to opportunities and challenges in present-day Maritime communities",
    "Ocean economy, newcomers, languages, climate and community responses",
  ],
  items: TODAY,
});
