import { bankUnit, type Q } from "../own";

// Grade 9 social studies, Citizenship 9: service learning, rights and responsibilities, financial, digital,
// governance and global citizenship. Balanced and non-partisan: no party is named and platform examples are generic.
// Indigenous content is light, in the present tense, and needs partner review.

const ENGAGED: Q[] = [
  ["A service learning project is best described as…", "learning by helping meet a real community need", ["a school test about volunteering", "a fundraiser where only adults take part"], "Service learning joins real service to the community with thinking about what you learn from it."],
  ["Which is the strongest reason to choose a project?", "A group in the community has told us it needs this help", ["It is the quickest idea we thought of", "It would look good on a poster"], "A real need that people have named gives a project meaning."],
  ["Before choosing a need, a team should first…", "ask community members what they need", ["decide on a solution and then find a need", "pick the idea that costs the least"], "Listening first keeps the project from solving a problem nobody has."],
  ["Which goal is clear and measurable?", "Collect 100 jars of food for the food bank by 15 March", ["Help hungry people somehow", "Do something good soon"], "A good goal says what, how much and by when."],
  ["Why do students think about their own skills and interests when planning?", "A project goes better when people can use their strengths", ["Everyone must do exactly the same job", "Interests do not matter if the cause is good"], "Matching jobs to strengths helps a team do good work and stay keen."],
  ["Alex is good at drawing and shy about speaking. Which team role fits Alex well?", "designing posters for the project", ["leading every phone call", "doing every job alone"], "Strengths guide roles, though people can also choose to stretch and try something new."],
  ["Which step usually comes first in planning a project?", "identifying a need and checking it is real", ["handing out thank-you cards", "writing the final reflection"], "Planning starts by understanding the need, and reflection comes at the end."],
  ["A timeline helps a team because it…", "shows who does what, and by when", ["guarantees there will be no problems", "replaces the need to communicate"], "Dates and roles let everyone see how their part fits."],
  ["A team wants to help at a seniors' residence. What is a respectful first step?", "contact the staff and ask what would help", ["show up unannounced with a plan", "post about it online before asking anyone"], "Partners know their own needs, so ask before acting."],
  ["Why partner with a community group such as a local food bank?", "They know the need well and can guide the work", ["It means students do not have to do anything", "It makes the goal less important"], "Community groups bring experience, contacts and a view of what helps."],
  ["After a project, a good reflection asks…", "What did we learn about being a citizen, and what would we change?", ["Who was to blame for the problems?", "How soon can we forget about it?"], "Reflection turns the experience into learning for next time."],
  ["Which message about a project is clear and respectful?", "We are collecting winter coats on Friday. Please drop them at the school office.", ["Coats needed, whenever, somewhere", "Give us your coats or you do not care"], "Good communication says what, when and where, and it invites rather than pressures."],
  ["A team compares two ideas. Idea A helps 5 people once. Idea B builds a garden that feeds a neighbourhood for years. What question helps them judge merit?", "Which idea meets the need better over time?", ["Which idea is more fun to say?", "Which idea needs less thinking?"], "Weighing the benefit, effort and lasting effect helps a team judge merit.", true],
  ["A team's idea needs $2000 and they only have six weeks. What is the wisest response?", "adjust the goal to fit the time and money they can reach", ["keep the plan and hope it works out", "give up on the idea completely"], "Realistic goals are still ambitious. Adjusting is part of good planning.", true],
  ["A group member keeps missing meetings. What is the best first step?", "talk with them kindly to find out what is getting in the way", ["tell the teacher they are lazy", "do their job and say nothing"], "Honest, kind conversation often fixes problems and keeps the team together.", true],
  ["A partner asks for something your team cannot finish in time. What is a thoughtful reply?", "Say what you can do, and agree on a plan together", ["Agree to everything and hope it works", "Refuse without giving a reason"], "Clear communication about limits builds trust with partners.", true],
  ["Which project shows the weakest link to a real need?", "Making cards nobody asked for and handing them out at random", ["Planting a community garden requested by neighbours", "Running a coat drive for a shelter that asked for coats"], "A project needs evidence that people want or need the help.", true],
  ["Which citizenship skill is MOST clearly practised when a team listens to a community partner and changes its plan?", "respect for others' views and being willing to adapt", ["winning every argument", "working alone to stay in control"], "Citizenship includes listening, cooperating and adjusting.", true],
  ["Which question best starts service learning?", "What does our community need?", ["What is the easiest thing to do?", "What will get the most likes?"], "Start with a real need."],
  ["A stakeholder in a project is…", "someone affected by or interested in the project", ["a tool used to build it", "a prize for finishing"], "Stakeholders can include neighbours, partners and the team."],
  ["To check whether a project worked, a team can…", "compare results with the goal they set", ["count how tired they were", "ask nobody"], "A clear goal makes results easy to judge."],
  ["A team aims to raise $500 and raises $400. What fraction of the goal did they reach?", "80%", ["40%", "125%"], "400 divided by 500 is 0.8, or 80%."],
  ["Which is a barrier to participation?", "a meeting held where some members cannot get a ride", ["a clear agenda", "a snack"], "Teams can plan to include everyone."],
  ["Service learning differs from simple volunteering because it also includes…", "planned reflection on what was learned", ["being paid", "only adults taking part"], "Reflection turns service into learning."],
  ["Which source gives the strongest evidence that a need is real?", "a survey of those affected plus a request from a community group", ["a guess from the team", "a video of a different town"], "Evidence from the community shows the need is real.", true],
  ["A project helps a few people but ignores others who also need help. Which question reflects better planning?", "Who else might be affected, and how can we include them?", ["How can we finish faster?", "How can we avoid asking?"], "Good planning considers everyone affected.", true],
  ["Which action best shows accountability?", "Doing your part and telling the team early if you cannot", ["Blaming others", "Hoping nobody notices"], "Accountability means owning your responsibilities.", true],
];

const RIGHTS: Q[] = [
  ["Which is a responsibility of a citizen?", "obeying laws and respecting others' rights", ["only thinking about what is best for yourself", "ignoring decisions that affect others"], "Rights come with responsibilities to others."],
  ["Which is a right Canadian citizens have?", "the right to vote when they are 18 or older", ["the right to ignore all laws", "the right to choose the Prime Minister alone"], "Voting is a right of Canadian citizens aged 18 and over."],
  ["What does a person's worldview mean?", "how they understand and see the world, shaped by experience and culture", ["the map hanging on their wall", "the news they saw this morning only"], "Family, culture, experience and beliefs all shape a worldview."],
  ["Two people see the same law differently. A likely reason is…", "their experiences and worldviews differ", ["only one of them can read", "one of them is not a citizen"], "Our experiences influence what we notice and value."],
  ["The Canadian Charter of Rights and Freedoms became part of the Constitution in…", "1982", ["1867", "1960"], "The Charter came with the Constitution Act of 1982."],
  ["Which of these is a freedom the Charter protects?", "freedom of peaceful assembly", ["freedom from all taxes", "freedom to pick your own grades"], "The Charter lists fundamental freedoms such as expression, religion and peaceful assembly."],
  ["In 1960, a change to the Indian Act meant status First Nations people could…", "vote in federal elections without giving up their status", ["vote only if they left their community", "vote only in provincial elections"], "Before 1960, many had to give up their status to vote federally."],
  ["Before the 1960 change, many status First Nations people were shut out of federal voting. This shows that…", "citizenship rights have not always been shared equally", ["voting was always open to everyone", "rights never change"], "Rights have grown over time as people worked for fairness."],
  ["Which statement about women and voting in Canada is true?", "Women won the right to vote in federal elections in the late 1910s", ["Women have always been able to vote", "Women were first allowed to vote in 1982"], "Many Canadian women gained the federal vote in 1918, and the rules widened in the years after."],
  ["Chinese Canadians could vote federally from…", "1947", ["1867", "1982"], "Laws that shut Chinese Canadians out of the vote were changed in 1947."],
  ["The Peace and Friendship Treaties between the Mi’kmaq and the Crown were made…", "between 1725 and 1779", ["in 1982 only", "after 1900"], "These treaties are still part of Nova Scotia's story today."],
  ["Treaties are part of citizenship because they…", "set out shared promises, rights and responsibilities that still matter", ["are old stories with no meaning today", "only matter to people who lived long ago"], "Treaty promises are agreements that people today are still responsible to honour."],
  ["Viola Desmond challenged racial segregation at a theatre in New Glasgow in 1946. What does her story show?", "A citizen can stand up for fairness and change can follow", ["Segregation was never an issue in Nova Scotia", "Laws never need to change"], "Her courage helped begin conversations about equal rights.", true],
  ["Reconciliation is best described as…", "building respectful relationships and acting on past wrongs", ["forgetting the past so no one is upset", "a job only governments do"], "Reconciliation takes learning and action from everyone.", true],
  ["Which is a way any citizen can support reconciliation?", "learn the true history and listen to Indigenous voices", ["stay away from the topic", "say the past does not matter"], "Learning and listening are first steps anyone can take.", true],
  ["Which sentence about rights and responsibilities is best?", "Using my rights should not take away someone else's", ["Rights matter, but responsibilities do not", "Only adults have responsibilities"], "My freedom ends where it would harm another person's rights.", true],
  ["Why might rights feel different to two groups in the same country?", "their history with laws and fairness may be different", ["rights depend on a person's age", "laws are written for only one group"], "A group that was shut out before may experience rights differently today.", true],
  ["Mi’kmaw people live in Mi’kma’ki today. Which statement is respectful and accurate?", "The Mi’kmaq are a living Nation with their own governments and communities", ["The Mi’kmaq are only a part of history", "All First Nations in Canada share exactly one culture"], "Nations are distinct, and the Mi’kmaq are here today.", true],
  ["The Charter's equality rights mean…", "every person is equal before and under the law", ["no one needs laws", "only citizens have rights"], "Equality before the law is a core Charter protection."],
  ["Mobility rights let Canadian citizens…", "live and work in any province", ["travel only by plane", "vote at age 12"], "Citizens can move freely within Canada."],
  ["Canada's official languages at the federal level are…", "English and French", ["French and Gaelic", "English and Spanish"], "Federal services are offered in both."],
  ["Freedom of expression means people can…", "share their opinions, within the limits of the law", ["say anything with no limits", "only agree with the government"], "Freedoms have reasonable limits."],
  ["A responsibility of citizens in a democracy is to…", "stay informed and vote", ["avoid learning about issues", "let others always decide"], "Informed voting strengthens democracy."],
  ["A person accused of a crime in Canada has the right to…", "be presumed innocent until proven guilty", ["be punished first", "avoid a trial"], "The Charter protects this right."],
  ["The Charter says rights can have reasonable limits. This means…", "a right may be limited when the limit can be justified in a free and democratic society", ["rights can be removed at any time", "rights apply only on weekdays"], "Limits must be justified.", true],
  ["Acadian families can have children taught in French in schools run by the Conseil scolaire acadien provincial. Which Charter right supports this?", "minority language education rights", ["mobility rights", "voting rights"], "The Charter protects schooling in the minority official language.", true],
  ["Why might a person be treated unfairly even when the law says all are equal?", "Biases and old habits can affect how laws are used", ["Laws are always applied perfectly", "Fairness is not possible"], "Equal laws need fair practice too.", true],
];

const FINANCIAL: Q[] = [
  ["Which is a NEED?", "clean drinking water", ["a new video game", "brand-new shoes you already have a pair of"], "Needs are things people must have to live and be healthy."],
  ["Which is a WANT?", "the newest phone when yours works", ["a safe place to live", "food to eat"], "A want is nice to have but not required to live."],
  ["People in different cultures may value things differently. This means…", "what is worth a lot to one group may not be to another", ["everyone values the same things", "value is just the price"], "Value can come from culture, community and beliefs, not only money."],
  ["Income tax is…", "money people pay to governments from what they earn", ["money the government pays you for working", "a fee for using only the internet"], "Governments use taxes to pay for shared services."],
  ["Sales tax is paid…", "when you buy many goods and services", ["only when you are paid", "only by people who own a business"], "Sales tax is added to the price at the till."],
  ["Which is usually paid for with tax money?", "public schools and roads", ["a friend's birthday gift", "a private home's groceries"], "Tax pays for services we share, such as schools, health care and roads."],
  ["Taxes in Nova Scotia are collected by…", "both the provincial and federal governments", ["only the school", "only the municipal garbage truck"], "Both levels of government collect taxes for different services."],
  ["A budget is…", "a plan for how to spend and save your money", ["a record of what you spent last year only", "a type of credit card"], "A budget compares what comes in with what goes out."],
  ["Sam earns $60 and spends $40. How much is left to save?", "$20", ["$40", "$100"], "Subtract spending from income: 60 − 40 = 20."],
  ["Which is a good saving goal?", "Save $50 for a bike helmet in 10 weeks, $5 a week", ["Save some money someday", "Spend less if possible"], "A clear goal has an amount, a date and a plan."],
  ["Interest on a loan is…", "an extra amount you pay for borrowing money", ["a bonus the lender gives you", "a type of tax"], "Borrowing costs money, and interest is the cost."],
  ["Which is a scam warning sign?", "a stranger asks for your password to give you a prize", ["a store posting its hours", "a bank statement from your own account"], "Real businesses do not ask for your password.", true],
  ["Economic fairness is about…", "people having what they need to take part, even if they start in different places", ["everyone getting exactly the same amount", "only those who earn the most deciding"], "Fairness looks at what people need, while equality gives everyone the same.", true],
  ["Giving every student the same size shoe is…", "equal, but not necessarily fair", ["fair because it is equal", "unfair because it is equal"], "Fairness fits what each person needs, while equality treats everyone the same.", true],
  ["A family chooses cheap goods made far away because they cost less. A thoughtful consumer might also ask…", "How were these goods made, and who may be affected?", ["Will this make me popular?", "Can I forget where it came from?"], "Informed choices consider effects on people and the planet.", true],
  ["You borrow $100 and pay back $110 later. The extra $10 is…", "interest", ["a tax refund", "a savings bonus"], "Interest is what you pay the lender for the use of their money.", true],
  ["Which is an external factor that can change your budget?", "prices of groceries going up", ["your own decision to skip a movie", "your feelings about shopping"], "External factors are things outside your control, such as prices, income and interest rates.", true],
  ["Why can groups end up with unequal financial outcomes?", "different access to jobs, schooling and past opportunities", ["because some people simply do not try", "because everyone starts equally"], "Systems and history can limit or open opportunities.", true],
  ["Saving money is helpful because it…", "prepares you for goals and surprises", ["makes prices drop", "is required by law"], "Savings give you choices later."],
  ["Net pay is…", "the money you take home after deductions", ["pay before anything is taken off", "a tax on credit"], "Gross pay is before deductions and net pay is after."],
  ["A credit card is…", "a way to borrow money that must be paid back", ["free money", "a savings account"], "Unpaid balances can grow with interest."],
  ["Maya earns $200 and spends 25% on transport. How much is that?", "$50", ["$25", "$75"], "25% of 200 is 50."],
  ["A $40 item is 25% off. What is the sale price?", "$30", ["$10", "$35"], "25% of 40 is 10, and 40 minus 10 is 30."],
  ["A co-operative is a business…", "owned and run by its members", ["owned by one person only", "run by no one"], "Credit unions and many farm and fish co-ops work this way."],
  ["Why do people buy insurance?", "to share the risk of a big, unexpected cost", ["to avoid paying ever", "to earn interest daily"], "Many people pay a little so a few can be covered.", true],
  ["Simple interest: $100 at 5% a year for 2 years earns…", "$10", ["$5", "$25"], "5% of 100 is 5 each year, so 10 in two years.", true],
  ["A deal promises huge returns with no risk. What should you suspect?", "It may be a scam, since high returns come with risk", ["It is surely safe", "It is the best deal ever"], "If it sounds too good to be true, check carefully.", true],
];

const DIGITAL: Q[] = [
  ["Your digital footprint is…", "the trail of information you leave online", ["a drawing of your phone", "a game about walking"], "Posts, searches and photos can all add to it."],
  ["Before posting a photo with a friend in it, you should…", "ask if they are okay with it being shared", ["post it, then ask later", "assume they will not mind"], "Consent means asking first. People decide if their picture is shared."],
  ["Cyberbullying is…", "using technology to hurt or embarrass someone on purpose", ["disagreeing politely in a group chat", "posting a recipe online"], "Bullying online can reach someone anywhere, any time."],
  ["If someone is bullied online, a good first step is to…", "save the evidence and tell a trusted adult", ["reply with a mean message", "delete everything and say nothing"], "Evidence plus a trusted adult makes it easier to get help."],
  ["Your best friend asks for your account password. What is the safest choice?", "keep it private and offer another way to help", ["share it if you trust them", "share it just this once"], "Passwords are for you only, even with close friends."],
  ["An algorithm in a social media app is…", "a set of steps that picks what to show you", ["a person who reads your mail", "a cable that connects your phone"], "Apps often use algorithms to choose which posts you see."],
  ["A feed shows you more of the posts you spend time on. This can mean you…", "see a narrower mix of ideas", ["see every idea equally", "never see any posts"], "Algorithms can make it easier to get stuck in one viewpoint."],
  ["Misinformation is…", "false or misleading information, sometimes shared without bad intent", ["only jokes", "news that is true but boring"], "Even honest people can pass on wrong information."],
  ["Which step helps check if a claim is true?", "look for the same story from several trusted sources", ["share it quickly if it feels true", "trust the post with the most likes"], "Likes do not prove something is true."],
  ["Copyright means…", "the creator of a work has rights to how it is used", ["anyone can copy anything online", "only websites have rights"], "Creators own their work, so ask or give credit when you use it."],
  ["Which is respectful online behaviour?", "disagreeing with ideas without insulting people", ["posting a mean comment as a joke", "sharing a classmate's private message"], "Respect means being kind even when you disagree."],
  ["A website photo shows only one kind of family. What question helps you think about this?", "Who might be left out of this picture?", ["Is the picture sharp?", "What time was it taken?"], "Media choose what to show, and sometimes groups are left out."],
  ["Posting anonymously can make some people…", "act more harshly because no one knows who they are", ["always kinder", "unable to read the comments"], "Anonymity can reduce a person's sense of responsibility.", true],
  ["A news story uses only one person's view of an issue. A thoughtful reader would…", "look for other perspectives too", ["accept it as the whole story", "stop reading anything about it"], "Several views give a more complete picture.", true],
  ["Why can an old post be a problem years later?", "It can be saved or shared, and it may still be found", ["Posts always disappear in a week", "Only the person who posted it can see it"], "Your digital footprint can last longer than you expect.", true],
  ["A classmate sends you an embarrassing picture of someone else. What is the best choice?", "do not share it, and tell a trusted adult if it is hurting someone", ["send it to a few friends only", "post it to see who reacts"], "Sharing it would add to the harm.", true],
  ["Which is an opportunity of being connected online?", "learning from people and communities far away", ["never needing to check a source", "avoiding all disagreement"], "Being connected opens doors, and it also brings risks that need care.", true],
  ["You want to use a photo from the internet in a school project. What is the best practice?", "check who owns it and give credit or ask permission", ["use it, since it was online", "remove the credit so it looks like yours"], "Respecting creators means giving credit and following the rules for use.", true],
  ["A strong password is…", "long and hard to guess, with a mix of characters", ["your name and birthday", "1234"], "Long, unique passwords are harder to crack."],
  ["Two-step verification means…", "you need a second proof, like a code, as well as your password", ["no password is needed", "you share your password twice"], "A second step protects your account."],
  ["A phishing message tries to…", "trick you into giving personal information", ["send you a free book", "update your phone"], "Check the sender before you click."],
  ["Privacy settings let you…", "choose who can see what you share", ["delete the internet", "make posts permanent"], "Review settings regularly."],
  ["Which should you keep private online?", "your home address", ["a public book review", "a fact about animals"], "Personal details can be misused."],
  ["Plagiarism is…", "presenting someone else's work as your own", ["quoting with credit", "writing your own summary"], "Give credit to the creator."],
  ["A deepfake is…", "media altered by technology to make something look real that did not happen", ["a photo filter that is always safe", "a type of password"], "Be careful with surprising videos.", true],
  ["Why check the date on an online article?", "old information may be out of date or misleading", ["dates are decoration", "newer is always wrong"], "Facts and situations change over time.", true],
  ["A free app asks for your contacts and location it does not need. A smart response is to…", "think about whether it is worth sharing and consider saying no", ["accept everything", "share it twice"], "Share only what is needed.", true],
];

const GOVERNANCE: Q[] = [
  ["Which level of government is mainly responsible for local garbage collection and parks?", "municipal", ["federal", "provincial"], "Municipal governments look after local services."],
  ["Which level of government is mainly responsible for national defence?", "federal", ["municipal", "provincial"], "The federal government handles defence and citizenship."],
  ["Which level of government is mainly responsible for health care and education?", "provincial", ["municipal", "federal"], "Provinces run most health and school services."],
  ["Nova Scotia's House of Assembly meets in…", "Halifax", ["Ottawa", "Sydney"], "The House of Assembly meets at Province House in Halifax."],
  ["The leader of the Nova Scotia government is called the…", "Premier", ["Prime Minister", "Governor General"], "Provinces have Premiers. Canada has a Prime Minister."],
  ["A person elected to the Nova Scotia House of Assembly is called an…", "MLA", ["MP", "Senator"], "MLA stands for Member of the Legislative Assembly."],
  ["The leader of Canada's federal government is the…", "Prime Minister", ["Premier", "Mayor"], "The Prime Minister leads the federal government."],
  ["A person elected to the House of Commons in Ottawa is called an…", "MP", ["MLA", "Mayor"], "MP stands for Member of Parliament."],
  ["The voting age in Canadian federal elections is…", "18", ["16", "21"], "Canadians 18 or older can vote."],
  ["Why is voting done by secret ballot?", "so no one can pressure you about your choice", ["so no one can count the votes", "so only some people can vote"], "A secret ballot protects each person's free choice."],
  ["A party platform is…", "a list of the ideas and plans a party promises to follow", ["a stage for speeches only", "a rule that voters must obey"], "Voters read platforms to compare plans. Any party writes its own."],
  ["Which is one way a citizen can take part in government between elections?", "sign a petition or contact their representative", ["wait until the next election only", "avoid all issues"], "Citizens can speak up at any time.", true],
  ["Public opinion matters to governments because…", "leaders pay attention to what many citizens care about", ["it replaces the law", "it chooses the judges"], "Issues can become priorities when many people speak up.", true],
  ["An advocacy group makes a campaign for safer bike lanes. What is it trying to do?", "persuade decision makers to act on an issue", ["avoid public debate", "change the voting age"], "Advocacy means speaking up for a cause.", true],
  ["The Governor General represents…", "the Crown in Canada", ["the Premier of Nova Scotia", "the Senate's voters"], "The Governor General carries out many of the Crown's duties in Canada.", true],
  ["Members of the Senate are…", "appointed, not elected", ["elected by voters in every town", "chosen by the Premier of each province"], "Senators are appointed to the Senate.", true],
  ["Many First Nations, including Mi’kmaw communities, are led by their own…", "chiefs and councils", ["Premiers", "Senators"], "Indigenous governments are part of Canada's governance today.", true],
  ["A newspaper reports often on an issue and more people start to care. This shows that…", "media can help an issue become a priority", ["issues never change", "only the Prime Minister can start a conversation"], "Media coverage can influence what society values.", true],
  ["Which level of government is mainly responsible for the Canadian currency?", "federal", ["municipal", "provincial"], "The federal government handles currency and the post."],
  ["Which level of government mainly sets zoning rules for where buildings can go in a town?", "municipal", ["federal", "provincial"], "Local councils decide how land in town is used."],
  ["In a federal election, voters in each riding elect…", "one MP", ["a Premier", "a Senator"], "MP stands for Member of Parliament."],
  ["A riding is…", "an area whose voters elect one representative", ["a horse trail", "a type of tax"], "Ridings are also called electoral districts."],
  ["A majority government happens when…", "one party wins more than half of the seats", ["no party wins any seats", "the monarch decides"], "A majority can pass laws more easily."],
  ["A by-election happens when…", "a seat becomes empty between general elections", ["everyone votes at once", "the prime minister cancels voting"], "Voters in that riding choose a new member."],
  ["A town's municipal government is usually led by a…", "mayor", ["Senator", "Prime Minister"], "Councillors work with the mayor."],
  ["Why do bills pass more than one reading in a legislature?", "Members have time to debate and improve them", ["To delay for no reason", "To avoid votes"], "Readings allow careful review.", true],
  ["Why should courts be independent from the government?", "so laws are applied fairly, even to governments", ["so judges can write laws", "so courts can run elections"], "Independence protects fairness.", true],
];

const GLOBAL: Q[] = [
  ["Which is a global issue?", "climate change", ["the school lunch menu", "a local hockey score"], "Climate change affects people and places everywhere."],
  ["A global issue is one that…", "affects people in many parts of the world", ["only happens in one town", "no one can change"], "Global issues cross borders."],
  ["The United Nations (UN) is…", "an organization where countries work together on world issues", ["a single country", "a company that sells goods"], "Countries join the UN to cooperate on peace, rights and development."],
  ["The Sustainable Development Goals are…", "goals the world has set for a better future for people and the planet", ["a list of games", "a type of tax"], "They cover things like clean water, health and fair work."],
  ["Which is a basic human need that many people still lack?", "access to clean water", ["a bigger television", "a new game"], "Clean water is one of the world's most important needs."],
  ["A refugee is someone who…", "has left their country to be safe from danger", ["travels for fun", "is a tourist"], "Refugees flee war or persecution and need protection."],
  ["Many things we buy are made in other countries. This shows that our choices…", "connect us to people far away", ["affect no one but ourselves", "only matter to the shopkeeper"], "What we buy is connected to people around the world."],
  ["Which choice helps reduce your carbon emissions?", "walking or taking the bus instead of the car", ["leaving lights on", "driving short trips"], "Using less fossil fuel lowers emissions."],
  ["A pandemic is a disease that…", "spreads across many countries", ["stays in one house", "only affects animals"], "Pandemics need people to cooperate around the world."],
  ["Short-term consequences happen…", "soon after a choice", ["many years later only", "never"], "Short-term effects happen quickly, and long-term effects take years."],
  ["Which is an informed way to take action on a global issue?", "learn the facts, then support a group working on it", ["share the first thing you see", "do nothing and hope"], "Informed action starts with reliable information.", true],
  ["Inaction on a problem such as hunger can mean…", "people continue to suffer when we could have helped", ["the problem goes away on its own", "nothing has changed at all"], "Choosing to do nothing is also a choice with consequences.", true],
  ["A government cuts a program for short-term savings, but the problem gets worse over years. This shows…", "short-term gains can cause long-term costs", ["long-term effects do not matter", "savings are always bad"], "Weighing both time spans helps leaders decide.", true],
  ["Malala Yousafzai spoke out for girls' education and became the youngest Nobel Peace Prize winner. What does this show?", "one person's voice can bring attention to a global issue", ["only governments can make a difference", "young people cannot take action"], "People of all ages have worked for change.", true],
  ["Which statement shows a global citizen's attitude?", "My choices can affect people far away, so I try to act fairly", ["Problems far away are not my business", "Only experts can make a difference"], "Global citizens think about the effects of their choices on others.", true],
  ["Which best weighs short-term and long-term effects?", "building a school that costs more now but helps for decades", ["spending all funds on a one-day party", "ignoring the cost completely"], "Long-term benefits can justify a larger short-term cost.", true],
  ["Why do countries cooperate on climate change?", "carbon emissions affect the whole world, no matter where they come from", ["emissions stay in the country that makes them", "only large countries are affected"], "The air and oceans are shared, so the effects are shared too.", true],
  ["Which is a reliable way to learn about a world issue?", "read reports from respected organizations and several news sources", ["rely on one post from a stranger", "believe whatever is shared most"], "Cross-checking trusted sources helps you find accurate facts.", true],
  ["Fair trade products aim to…", "give producers a fair price for their work", ["make goods free", "hide where goods are made"], "Fair trade supports workers."],
  ["Which is a human rights document?", "the Universal Declaration of Human Rights", ["a menu", "a bus schedule"], "The UN adopted it in 1948."],
  ["Recycling and reusing help global sustainability by…", "using fewer new resources", ["making more waste", "raising emissions"], "Less new material means less energy and waste."],
  ["Humanitarian aid is help given to…", "people in need after a crisis", ["companies only", "countries starting wars"], "Aid can include food and shelter."],
  ["Biodiversity means…", "the variety of living things in an ecosystem", ["the size of a country", "the amount of money"], "Many kinds of life keep ecosystems healthy."],
  ["Learning a second language can help global citizens…", "communicate with and understand more people", ["avoid others", "stop learning"], "Languages connect people."],
  ["Which source of energy helps lower emissions?", "wind and solar power", ["burning more coal", "using more oil"], "Renewable sources release far less carbon."],
  ["Why can the same global issue look different in different countries?", "their history, resources and daily lives differ", ["everyone has the same experience", "issues exist in one place only"], "Understanding many views helps solve problems.", true],
  ["A company moves a factory to save money. One town loses jobs and another gains them. This shows…", "choices can help some people and harm others", ["everyone benefits equally", "nothing is connected"], "Global choices have mixed effects.", true],
];

export const engagedCitizenship = bankUnit({
  id: "ns-engaged-citizenship-9",
  title: "Service Learning Projects",
  emoji: "🤝",
  blurb: "Plan a project that helps your community.",
  parentNote: "Practises choosing a real community need, setting goals, planning roles and timelines, working with community partners and reflecting on citizenship, as in the Engaged Citizenship strand of Nova Scotia's Citizenship 9 course.",
  standards: ["Engaged Citizenship", "plan, carry out and reflect on a service learning project"],
  items: ENGAGED,
});

export const citizenRights = bankUnit({
  id: "ns-citizen-rights-9",
  title: "Who Am I as a Citizen?",
  emoji: "🪪",
  blurb: "Rights, responsibilities and how they have grown.",
  parentNote: "Practises citizens' rights and responsibilities, worldview, how rights have changed for groups once shut out, treaties, the Charter and reconciliation, as in Nova Scotia's Citizenship 9 course. Indigenous content is light and is to be reviewed with community partners.",
  standards: ["Who Am I as a Citizen?", "rights and responsibilities, worldview, treaties, the Charter and reconciliation"],
  items: RIGHTS,
});

export const financialCitizenship = bankUnit({
  id: "ns-financial-citizenship-9",
  title: "Financial Citizenship",
  emoji: "💰",
  blurb: "Needs, wants, taxes and smart money choices.",
  parentNote: "Practises needs and wants, taxes and what they pay for, economic fairness, budgets, saving, credit, interest and scams, as in the Financial Citizenship strand of Nova Scotia's Citizenship 9 course.",
  standards: ["Financial Citizenship", "needs, wants and value, taxes, fairness, budgets, credit and informed financial choices"],
  items: FINANCIAL,
});

export const digitalCitizenship = bankUnit({
  id: "ns-digital-citizenship-9",
  title: "Digital Citizenship",
  emoji: "📱",
  blurb: "Be a kind, careful and smart citizen online.",
  parentNote: "Practises how media represent groups, bias and misinformation, algorithms, digital footprints, privacy, consent, cyberbullying, copyright and respectful online behaviour, as in the Digital Citizenship strand of Nova Scotia's Citizenship 9 course.",
  standards: ["Digital Citizenship", "media, bias, misinformation, privacy, consent and respectful online behaviour"],
  items: DIGITAL,
});

export const governance = bankUnit({
  id: "ns-governance-9",
  title: "Governance",
  emoji: "🏛️",
  blurb: "How governments work and how you can take part.",
  parentNote: "Practises federal, provincial, municipal and Indigenous governments, Nova Scotia's House of Assembly, Canada's Parliament, elections and ways to take part, as in the Governance strand of Nova Scotia's Citizenship 9 course. Questions are non-partisan and name no party.",
  standards: ["Governance", "levels of government, elections, platforms and ways citizens engage"],
  items: GOVERNANCE,
});

export const globalCitizenship = bankUnit({
  id: "ns-global-citizenship-9",
  title: "Global Citizenship",
  emoji: "🌍",
  blurb: "How our choices connect us to the world.",
  parentNote: "Practises global issues such as climate change, clean water, refugees and pandemics, the United Nations and Sustainable Development Goals, and weighing short-term and long-term consequences, as in the Global Citizenship strand of Nova Scotia's Citizenship 9 course.",
  standards: ["Global Citizenship", "global issues, consequences of action and inaction, and informed action"],
  items: GLOBAL,
});
