import { frQuestions, type FrItem } from "../../french";
import type { Course } from "../../types";

const FR = { lang: "fr" } as const;

// ---------- Les verbes pronominaux ----------

const REFLEXIVE_HINT = "With verbs like “se laver”, the little word before the verb matches the person: je me, tu te, il/elle se, nous nous, vous vous, ils/elles se.";

const REFLEXIVE: FrItem[] = [
  ["Complète : Je ___ lave les mains.", "me", ["te", "se", "nous"], REFLEXIVE_HINT],
  ["Complète : Tu ___ brosses les dents.", "te", ["me", "se", "vous"], REFLEXIVE_HINT],
  ["Complète : Léa ___ réveille tôt.", "se", ["me", "te", "nous"], REFLEXIVE_HINT],
  ["Complète : Nous ___ habillons vite.", "nous", ["me", "te", "se"], REFLEXIVE_HINT],
  ["Complète : Vous ___ couchez tard.", "vous", ["me", "te", "se"], REFLEXIVE_HINT],
  ["Complète : Les enfants ___ lavent les mains.", "se", ["me", "te", "nous"], REFLEXIVE_HINT],
  ["Complète : Je ___ repose après l'école.", "me", ["te", "se", "vous"], REFLEXIVE_HINT],
  ["Complète : Tu ___ lèves à sept heures.", "te", ["me", "se", "nous"], REFLEXIVE_HINT],
  ["Complète : Amir ___ peigne les cheveux.", "se", ["me", "te", "vous"], REFLEXIVE_HINT],
  ["Complète : Nous ___ promenons au parc.", "nous", ["me", "te", "se"], REFLEXIVE_HINT],
  ["Complète : Je ___ brosse les cheveux.", "me", ["te", "se", "vous"], REFLEXIVE_HINT],
  ["Complète : Tu ___ laves le visage.", "te", ["me", "se", "nous"], REFLEXIVE_HINT],
  ["Complète : Zoé ___ lave avant le dîner.", "se", ["me", "te", "vous"], REFLEXIVE_HINT],
  ["Complète : Nous ___ couchons tôt.", "nous", ["me", "te", "se"], REFLEXIVE_HINT],
  ["Complète : Vous ___ levez à huit heures.", "vous", ["me", "te", "se"], REFLEXIVE_HINT],
  ["Complète : Ils ___ lèvent à sept heures.", "se", ["me", "te", "nous"], REFLEXIVE_HINT],
  ["Complète : Elles ___ peignent avant l'école.", "se", ["me", "te", "vous"], REFLEXIVE_HINT],
  ["Complète : Je ___ couche à huit heures.", "me", ["te", "se", "nous"], REFLEXIVE_HINT],
  ["Complète : Tu ___ reposes un peu.", "te", ["me", "se", "vous"], REFLEXIVE_HINT],
  ["Complète : Kenji ___ brosse les dents.", "se", ["me", "te", "nous"], REFLEXIVE_HINT],
  ["Complète : Nous ___ réveillons de bonne heure.", "nous", ["me", "te", "se"], REFLEXIVE_HINT],
  ["Complète : Vous ___ habillez vite.", "vous", ["me", "te", "se"], REFLEXIVE_HINT],
  ["Complète : Maya et Léo ___ promènent.", "se", ["me", "te", "nous"], REFLEXIVE_HINT],
  ["Complète : Je ___ lève avec le soleil.", "me", ["te", "se", "vous"], REFLEXIVE_HINT],
];

// ---------- Et, mais, ou, avec ----------

const LINK_HINT = "“Et” adds, “mais” shows a surprise or a problem, “ou” gives a choice and “avec” means together with.";

const LINKS: FrItem[] = [
  ["Complète : Nous mangeons des pommes ___ des poires. Les deux!", "et", ["mais", "ou", "avec"], LINK_HINT],
  ["Complète : Je voudrais sortir, ___ il pleut.", "mais", ["et", "ou", "avec"], LINK_HINT],
  ["Complète : Tu choisis le rouge ___ le bleu. Un seul!", "ou", ["et", "mais", "avec"], LINK_HINT],
  ["Complète : Je joue ___ mon frère.", "avec", ["mais", "ou", "et"], LINK_HINT],
  ["Complète : Léa lit un livre ___ Maya dessine.", "et", ["avec", "ou", "mais"], LINK_HINT],
  ["Complète : Il est petit, ___ il est très fort.", "mais", ["et", "ou", "avec"], LINK_HINT],
  ["Complète : Veux-tu du lait ___ du jus?", "ou", ["et", "mais", "avec"], LINK_HINT],
  ["Complète : J'ai faim, ___ je n'ai plus de pain.", "mais", ["et", "ou", "avec"], LINK_HINT],
  ["Complète : Amir va au parc ___ sa sœur.", "avec", ["mais", "ou", "et"], LINK_HINT],
  ["Complète : Le chat dort ___ le chien mange.", "et", ["avec", "ou", "mais"], LINK_HINT],
  ["Complète : Tu veux du thé ___ du chocolat chaud? Un seul!", "ou", ["et", "mais", "avec"], LINK_HINT],
  ["Complète : Je mange une pomme ___ une banane. Les deux!", "et", ["mais", "ou", "avec"], LINK_HINT],
  ["Complète : Il fait beau, ___ il fait très froid.", "mais", ["et", "ou", "avec"], LINK_HINT],
  ["Complète : Maya va au parc ___ son chien.", "avec", ["mais", "ou", "et"], LINK_HINT],
  ["Complète : Léo veut jouer, ___ il doit finir ses devoirs.", "mais", ["et", "ou", "avec"], LINK_HINT],
  ["Complète : Veux-tu aller à la piscine ___ au cinéma? Choisis.", "ou", ["et", "mais", "avec"], LINK_HINT],
  ["Complète : Zoé chante ___ Amir danse.", "et", ["avec", "ou", "mais"], LINK_HINT],
  ["Complète : Nous lisons ___ notre enseignante.", "avec", ["mais", "ou", "et"], LINK_HINT],
  ["Complète : Il est fatigué, ___ il joue encore.", "mais", ["et", "ou", "avec"], LINK_HINT],
  ["Complète : Prends-tu le bus ___ le train? Un seul!", "ou", ["et", "mais", "avec"], LINK_HINT],
  ["Complète : J'ai un chat ___ un chien. J'ai les deux.", "et", ["mais", "ou", "avec"], LINK_HINT],
  ["Complète : Je veux un biscuit, ___ la boîte est vide.", "mais", ["et", "ou", "avec"], LINK_HINT],
  ["Complète : Ana mange ___ ses amis à la cafétéria.", "avec", ["mais", "ou", "et"], LINK_HINT],
  ["Complète : Le matin, je bois du lait ___ je mange des céréales.", "et", ["avec", "ou", "mais"], LINK_HINT],
  ["Complète : Tu veux courir ___ marcher? Choisis.", "ou", ["et", "mais", "avec"], LINK_HINT],
];

// ---------- Ne… pas ----------

const NEG_HINT = "To say no in French, put “ne” before the verb and “pas” after it: je ne mange pas. Before a vowel, “ne” becomes “n'”: elle n'aime pas.";

const NEGATIVES: FrItem[] = [
  ["Quelle phrase dit le contraire de « Je mange »?", "Je ne mange pas.", ["Je mange pas.", "Ne je mange pas.", "Je pas mange."], NEG_HINT],
  ["Quelle phrase dit le contraire de « Il joue »?", "Il ne joue pas.", ["Il joue ne pas.", "Ne il joue pas.", "Il pas joue."], NEG_HINT],
  ["Quelle phrase dit le contraire de « Tu chantes »?", "Tu ne chantes pas.", ["Tu chantes ne pas.", "Ne tu chantes pas.", "Tu pas chantes."], NEG_HINT],
  ["Quelle phrase dit le contraire de « Elle aime »?", "Elle n'aime pas.", ["Elle ne aime pas.", "Elle aime ne pas.", "Elle pas aime."], NEG_HINT],
  ["Quelle phrase dit le contraire de « Nous dansons »?", "Nous ne dansons pas.", ["Nous dansons ne pas.", "Ne nous dansons pas.", "Nous pas dansons."], NEG_HINT],
  ["Quelle phrase dit le contraire de « J'habite ici »?", "Je n'habite pas ici.", ["Je ne habite pas ici.", "J'habite ne pas ici.", "Je pas habite ici."], NEG_HINT],
  ["Quelle phrase dit le contraire de « Ils courent »?", "Ils ne courent pas.", ["Ils courent ne pas.", "Ne ils courent pas.", "Ils pas courent."], NEG_HINT],
  ["Quelle phrase dit le contraire de « Léa dort »?", "Léa ne dort pas.", ["Léa dort ne pas.", "Ne Léa dort pas.", "Léa pas dort."], NEG_HINT],
  ["Quelle phrase dit le contraire de « Vous parlez »?", "Vous ne parlez pas.", ["Vous parlez ne pas.", "Ne vous parlez pas.", "Vous pas parlez."], NEG_HINT],
  ["Quelle phrase dit le contraire de « Il écoute »?", "Il n'écoute pas.", ["Il ne écoute pas.", "Il écoute ne pas.", "Il pas écoute."], NEG_HINT],
  ["Quelle phrase dit le contraire de « Nous mangeons »?", "Nous ne mangeons pas.", ["Nous mangeons ne pas.", "Ne nous mangeons pas.", "Nous pas mangeons."], NEG_HINT],
  ["Quelle phrase dit le contraire de « Elle chante »?", "Elle ne chante pas.", ["Elle chante ne pas.", "Ne elle chante pas.", "Elle pas chante."], NEG_HINT],
  ["Quelle phrase dit le contraire de « Je regarde »?", "Je ne regarde pas.", ["Je regarde ne pas.", "Ne je regarde pas.", "Je pas regarde."], NEG_HINT],
  ["Quelle phrase dit le contraire de « Tu lis »?", "Tu ne lis pas.", ["Tu lis ne pas.", "Ne tu lis pas.", "Tu pas lis."], NEG_HINT],
  ["Quelle phrase dit le contraire de « Ils jouent »?", "Ils ne jouent pas.", ["Ils jouent ne pas.", "Ne ils jouent pas.", "Ils pas jouent."], NEG_HINT],
  ["Quelle phrase dit le contraire de « Vous dansez »?", "Vous ne dansez pas.", ["Vous dansez ne pas.", "Ne vous dansez pas.", "Vous pas dansez."], NEG_HINT],
  ["Quelle phrase dit le contraire de « Maya lit »?", "Maya ne lit pas.", ["Maya lit ne pas.", "Ne Maya lit pas.", "Maya pas lit."], NEG_HINT],
  ["Quelle phrase dit le contraire de « Nous travaillons »?", "Nous ne travaillons pas.", ["Nous travaillons ne pas.", "Ne nous travaillons pas.", "Nous pas travaillons."], NEG_HINT],
  ["Quelle phrase dit le contraire de « Je saute »?", "Je ne saute pas.", ["Je saute ne pas.", "Ne je saute pas.", "Je pas saute."], NEG_HINT],
  ["Quelle phrase dit le contraire de « Kenji nage »?", "Kenji ne nage pas.", ["Kenji nage ne pas.", "Ne Kenji nage pas.", "Kenji pas nage."], NEG_HINT],
  ["Quelle phrase dit le contraire de « Il aide »?", "Il n'aide pas.", ["Il ne aide pas.", "Il aide ne pas.", "Il pas aide."], NEG_HINT],
  ["Quelle phrase dit le contraire de « Tu écoutes »?", "Tu n'écoutes pas.", ["Tu ne écoutes pas.", "Tu écoutes ne pas.", "Tu pas écoutes."], NEG_HINT],
  ["Quelle phrase dit le contraire de « Ils habitent »?", "Ils n'habitent pas.", ["Ils ne habitent pas.", "Ils habitent ne pas.", "Ils pas habitent."], NEG_HINT],
  ["Quelle phrase dit le contraire de « Elle étudie »?", "Elle n'étudie pas.", ["Elle ne étudie pas.", "Elle étudie ne pas.", "Elle pas étudie."], NEG_HINT],
  ["Quelle phrase dit le contraire de « J'aime »?", "Je n'aime pas.", ["Je ne aime pas.", "J'aime ne pas.", "Je pas aime."], NEG_HINT],
];

// ---------- Le futur proche ----------

const FUTURE_HINT = "The near future is “aller” + a verb: je vais manger, tu vas manger, il va manger, nous allons manger, vous allez manger, ils vont manger.";

const FUTURE: FrItem[] = [
  ["Complète : Demain, je ___ jouer.", "vais", ["vas", "va", "vont"], FUTURE_HINT],
  ["Complète : Nous ___ manger bientôt.", "allons", ["allez", "vont", "vais"], FUTURE_HINT],
  ["Complète : Tu ___ chanter ce soir.", "vas", ["vais", "va", "allez"], FUTURE_HINT],
  ["Complète : Ils ___ partir demain.", "vont", ["va", "allons", "vais"], FUTURE_HINT],
  ["Complète : Elle ___ lire un livre.", "va", ["vas", "vais", "vont"], FUTURE_HINT],
  ["Complète : Vous ___ danser avec nous.", "allez", ["allons", "vont", "va"], FUTURE_HINT],
  ["Quelle phrase parle de demain?", "Je vais manger.", ["Je mange.", "J'ai mangé."], "Look for “aller” + a verb: it tells what will happen soon.", "📅"],
  ["Quelle phrase parle de ce qui est déjà arrivé?", "J'ai mangé.", ["Je vais manger.", "Je vais jouer."], "“J'ai mangé” is the past: it already happened.", "⏪"],
  ["Quelle phrase parle de ce qui va arriver?", "Nous allons nager.", ["Nous avons nagé.", "Nous nagions."], "“Aller” + a verb tells about the near future.", "🏊"],
  ["Quelle phrase parle du passé?", "Hier, Léa a joué.", ["Demain, Léa va jouer.", "Bientôt, Léa va jouer."], "Hier means yesterday. Yesterday is the past.", "🗓️"],
  ["Complète : Demain, tu ___ lire.", "vas", ["vais", "va", "vont"], FUTURE_HINT],
  ["Complète : Ce soir, nous ___ cuisiner.", "allons", ["allez", "vont", "vais"], FUTURE_HINT],
  ["Complète : Bientôt, il ___ pleuvoir.", "va", ["vas", "vais", "vont"], FUTURE_HINT],
  ["Complète : Dans une heure, elles ___ arriver.", "vont", ["va", "allons", "vas"], FUTURE_HINT],
  ["Complète : Vous ___ gagner!", "allez", ["allons", "vont", "vas"], FUTURE_HINT],
  ["Complète : Je ___ dormir.", "vais", ["vas", "va", "vont"], FUTURE_HINT],
  ["Complète : Maya ___ dessiner un chat.", "va", ["vas", "vais", "allons"], FUTURE_HINT],
  ["Complète : Les élèves ___ sortir.", "vont", ["va", "allons", "allez"], FUTURE_HINT],
  ["Complète : Tu ___ voir un film.", "vas", ["vais", "va", "allez"], FUTURE_HINT],
  ["Complète : Nous ___ nager au lac.", "allons", ["allez", "vont", "va"], FUTURE_HINT],
  ["Quelle phrase parle de la semaine prochaine?", "La semaine prochaine, je vais voyager.", ["La semaine passée, j'ai voyagé.", "Hier, j'ai voyagé."], "Look for “aller” + a verb: it tells what will happen soon.", "🧳"],
  ["Quelle phrase parle d'hier?", "Hier, j'ai lu un livre.", ["Demain, je vais lire un livre.", "Bientôt, je vais lire."], "Hier means yesterday. Yesterday is the past.", "📖"],
  ["Quelle phrase parle de demain?", "Demain, Zoé va chanter.", ["Hier, Zoé a chanté.", "Zoé a chanté."], "Demain means tomorrow. Look for “va” + a verb.", "🎤"],
  ["Quelle phrase est au futur proche?", "Ils vont courir.", ["Ils ont couru.", "Hier, ils ont couru."], "The near future is “aller” + a verb.", "🏃"],
];

// ---------- Les pluriels en x ----------

const PLURAL_HINT = "Many words that end in -eau, -eu or -ou add an “x” in the plural (un bateau → des bateaux). Words ending in -al change to -aux (un cheval → des chevaux).";

const PLURALS: FrItem[] = [
  ["Un bateau, deux ___", "bateaux", ["bateaus", "bateau"], PLURAL_HINT, "⛵"],
  ["Un gâteau, trois ___", "gâteaux", ["gâteaus", "gâteau"], PLURAL_HINT, "🎂"],
  ["Un chapeau, deux ___", "chapeaux", ["chapeaus", "chapeau"], PLURAL_HINT, "🎩"],
  ["Un oiseau, quatre ___", "oiseaux", ["oiseaus", "oiseau"], PLURAL_HINT, "🐦"],
  ["Un cheval, deux ___", "chevaux", ["chevals", "cheval"], PLURAL_HINT, "🐴"],
  ["Un animal, des ___", "animaux", ["animals", "animal"], PLURAL_HINT, "🐾"],
  ["Un journal, des ___", "journaux", ["journals", "journal"], PLURAL_HINT, "📰"],
  ["Un jeu, des ___", "jeux", ["jeus", "jeu"], PLURAL_HINT, "🎲"],
  ["Un feu, des ___", "feux", ["feus", "feu"], PLURAL_HINT, "🔥"],
  ["Un chou, des ___", "choux", ["chous", "chou"], PLURAL_HINT, "🥬"],
  ["Un bijou, des ___", "bijoux", ["bijous", "bijou"], PLURAL_HINT, "💍"],
  ["Un couteau, des ___", "couteaux", ["couteaus", "couteau"], PLURAL_HINT, "🍴"],
  ["Un manteau, des ___", "manteaux", ["manteaus", "manteau"], PLURAL_HINT, "🧥"],
  ["Un château, des ___", "châteaux", ["châteaus", "château"], PLURAL_HINT, "🏰"],
  ["Un tableau, des ___", "tableaux", ["tableaus", "tableau"], PLURAL_HINT, "🖼️"],
  ["Un rideau, des ___", "rideaux", ["rideaus", "rideau"], PLURAL_HINT, "🪟"],
  ["Un cadeau, des ___", "cadeaux", ["cadeaus", "cadeau"], PLURAL_HINT, "🎁"],
  ["Un chameau, des ___", "chameaux", ["chameaus", "chameau"], PLURAL_HINT, "🐪"],
  ["Un agneau, des ___", "agneaux", ["agneaus", "agneau"], PLURAL_HINT, "🐑"],
  ["Un cheveu, des ___", "cheveux", ["cheveus", "cheveu"], PLURAL_HINT, "💇"],
  ["Un genou, des ___", "genoux", ["genous", "genou"], PLURAL_HINT, "🦵"],
  ["Un hibou, des ___", "hiboux", ["hibous", "hibou"], PLURAL_HINT, "🦉"],
  ["Un caillou, des ___", "cailloux", ["caillous", "caillou"], PLURAL_HINT, "🪨"],
  ["Un bureau, des ___", "bureaux", ["bureaus", "bureau"], PLURAL_HINT, "🗄️"],
  ["Un hôpital, des ___", "hôpitaux", ["hôpitals", "hôpital"], PLURAL_HINT, "🏥"],
  ["Un canal, des ___", "canaux", ["canals", "canal"], PLURAL_HINT, "🚤"],
];

// ---------- Préfixes et suffixes ----------

const AFFIXES: FrItem[] = [
  ["Que veut dire « relire »?", "lire de nouveau", ["lire très vite", "ne pas lire"], "The prefix “re-” means again.", "📖"],
  ["Que veut dire « refaire »?", "faire de nouveau", ["ne pas faire", "faire très bien"], "The prefix “re-” means again.", "🔁"],
  ["Que veut dire « recommencer »?", "commencer de nouveau", ["finir", "commencer trop tard"], "The prefix “re-” means again.", "🔁"],
  ["Que veut dire « défaire »?", "défaire ce qui est fait", ["faire de nouveau", "faire très vite"], "The prefix “dé-” often means the opposite.", "🧶"],
  ["Que veut dire « impossible »?", "pas possible", ["très possible", "possible demain"], "The prefix “im-” (or “in-”) often means not.", "🚫"],
  ["Que veut dire « inutile »?", "pas utile", ["très utile", "utile demain"], "The prefix “in-” often means not.", "🚫"],
  ["Que veut dire « malheureux »?", "pas heureux", ["très heureux", "heureux demain"], "The prefix “mal-” means badly or not.", "😢"],
  ["Que veut dire « invisible »?", "qu'on ne peut pas voir", ["qu'on voit très bien", "qu'on voit demain"], "The prefix “in-” often means not.", "👻"],
  ["Une maisonnette est…", "une petite maison", ["une grande maison", "une vieille maison"], "The ending “-ette” means small.", "🏡"],
  ["Une fillette est…", "une petite fille", ["une grande fille", "une vieille fille"], "The ending “-ette” means small.", "👧"],
  ["Un chanteur est une personne qui…", "chante", ["lit", "court"], "The ending “-eur” names the person who does the action.", "🎤"],
  ["Un pommier est…", "un arbre qui donne des pommes", ["une sorte de pomme", "un panier de pommes"], "The ending “-ier” can name the tree that gives a fruit.", "🌳"],
  ["Que veut dire « replanter »?", "planter de nouveau", ["ne pas planter", "planter très vite"], "The prefix “re-” means again.", "🌱"],
  ["Que veut dire « relancer »?", "lancer de nouveau", ["ne pas lancer", "lancer très loin"], "The prefix “re-” means again.", "🥏"],
  ["Que veut dire « redire »?", "dire de nouveau", ["ne pas dire", "dire très fort"], "The prefix “re-” means again.", "🗣️"],
  ["Que veut dire « déplier »?", "ouvrir ce qui est plié", ["plier de nouveau", "plier très bien"], "The prefix “dé-” often means the opposite.", "🗺️"],
  ["Que veut dire « déboutonner »?", "ouvrir les boutons", ["fermer les boutons", "coudre des boutons"], "The prefix “dé-” often means the opposite.", "👔"],
  ["Que veut dire « impatient »?", "pas patient", ["très patient", "patient demain"], "The prefix “im-” (or “in-”) often means not.", "⏳"],
  ["Que veut dire « incorrect »?", "pas correct", ["très correct", "correct demain"], "The prefix “in-” often means not.", "❌"],
  ["Que veut dire « inconnu »?", "qu'on ne connaît pas", ["qu'on connaît bien", "qu'on voit demain"], "The prefix “in-” often means not.", "❓"],
  ["Que veut dire « maladroit »?", "pas adroit", ["très adroit", "adroit demain"], "The prefix “mal-” means badly or not.", "🥴"],
  ["Un cerisier est…", "un arbre qui donne des cerises", ["une sorte de cerise", "un panier de cerises"], "The ending “-ier” can name the tree that gives a fruit.", "🍒"],
  ["Une danseuse est une personne qui…", "danse", ["lit", "court"], "The ending “-euse” names the person who does the action.", "💃"],
  ["Un nageur est une personne qui…", "nage", ["chante", "écrit"], "The ending “-eur” names the person who does the action.", "🏊"],
  ["Un jardinier est une personne qui…", "s'occupe d'un jardin", ["conduit un autobus", "fait des gâteaux"], "The ending “-ier” can name a person with a job, here the one who works in a garden.", "🧑‍🌾"],
];

// ---------- L'idée principale ----------

const MAIN_HINT = "The main idea is what the whole text is about. Details are smaller facts that support it.";

const MAIN_IDEA: FrItem[] = [
  [
    "Quelle est l'idée principale?",
    "Les chats dorment beaucoup.",
    ["Les chats aiment les boîtes.", "Les chats mangent du poisson."],
    MAIN_HINT,
    { type: "passage", title: "Les chats", paragraphs: ["Les chats aiment dormir. Ils dorment douze heures par jour. Ils dorment au soleil, sur un lit ou dans une boîte."] },
  ],
  [
    "Quelle est l'idée principale?",
    "Les abeilles travaillent en équipe.",
    ["Les abeilles mangent des fleurs.", "Le miel est très sucré."],
    MAIN_HINT,
    { type: "passage", title: "Les abeilles", paragraphs: ["Les abeilles travaillent ensemble. Certaines cherchent des fleurs. D'autres fabriquent du miel. Chacune a son rôle dans la ruche."] },
  ],
  [
    "Quelle est l'idée principale?",
    "Je m'habille et je joue sous la pluie.",
    ["J'ai perdu mon parapluie.", "Il pleut toute la semaine."],
    MAIN_HINT,
    { type: "passage", title: "Jour de pluie", paragraphs: ["Quand il pleut, je mets mon imperméable et mes bottes. Je prends mon parapluie. Je saute dans les flaques."] },
  ],
  [
    "Quelle est l'idée principale?",
    "On peut faire plusieurs choses à la bibliothèque.",
    ["On doit se taire à la bibliothèque.", "Les livres sont rangés par couleur."],
    MAIN_HINT,
    { type: "passage", title: "La bibliothèque", paragraphs: ["À la bibliothèque, on peut emprunter des livres. On peut aussi lire sur place ou écouter une histoire. Tout le monde est le bienvenu."] },
  ],
  [
    "Quelle est l'idée principale?",
    "Les légumes ont besoin de soin pour pousser.",
    ["Les carottes sont orange.", "Le soleil est chaud."],
    MAIN_HINT,
    { type: "passage", title: "Le potager", paragraphs: ["Pour faire pousser des légumes, il faut de la terre, de l'eau et du soleil. Il faut aussi de la patience."] },
  ],
  [
    "Quelle est l'idée principale?",
    "Maya aide Kenji à se faire un ami.",
    ["Kenji est triste.", "La récréation est longue."],
    MAIN_HINT,
    { type: "passage", title: "Un nouvel élève", paragraphs: ["Kenji est nouveau à l'école. Maya lui montre la classe. Ils jouent ensemble à la récréation. Kenji se sent bien."] },
  ],
  [
    "Quelle est l'idée principale?",
    "Les chiens aident les gens.",
    ["Les chiens aiment courir.", "Les chiens ont quatre pattes."],
    MAIN_HINT,
    { type: "passage", title: "Les chiens", paragraphs: ["Les chiens aident les gens de plusieurs façons. Certains guident les personnes aveugles. D'autres cherchent des gens perdus. D'autres encore tiennent compagnie."] },
  ],
  [
    "Quelle est l'idée principale?",
    "Le recyclage aide à garder la planète propre.",
    ["Le verre est fragile.", "Le plastique est léger."],
    MAIN_HINT,
    { type: "passage", title: "Le recyclage", paragraphs: ["On peut recycler le papier, le verre et le plastique. Chaque matière va dans un bac différent. Ainsi, on garde la planète propre."] },
  ],
  [
    "Quelle est l'idée principale?",
    "En automne, les feuilles changent et tombent.",
    ["Les arbres sont très hauts.", "Il pleut toujours en automne."],
    MAIN_HINT,
    { type: "passage", title: "L'automne", paragraphs: ["En automne, les feuilles changent de couleur. Elles deviennent rouges, jaunes et orange. Puis elles tombent des arbres."] },
  ],
  [
    "Quelle est l'idée principale?",
    "La grenouille change beaucoup en grandissant.",
    ["Les têtards nagent vite.", "Les grenouilles aiment les lacs."],
    MAIN_HINT,
    { type: "passage", title: "Les grenouilles", paragraphs: ["Une grenouille commence sa vie comme un œuf. Puis elle devient un têtard. Enfin, ses pattes poussent et elle sort de l'eau."] },
  ],
  [
    "Quelle est l'idée principale?",
    "Ana et son père font des achats au marché.",
    ["Ana aime les fleurs.", "Le pain est chaud."],
    MAIN_HINT,
    { type: "passage", title: "Au marché", paragraphs: ["Samedi, Ana et son père vont au marché. Ils achètent des pommes, du pain et des fleurs. Ana porte le sac."] },
  ],
  [
    "Quelle est l'idée principale?",
    "Se brosser les dents garde les dents en santé.",
    ["Le dentifrice a bon goût.", "Les dents sont blanches."],
    MAIN_HINT,
    { type: "passage", title: "Les dents", paragraphs: ["Il faut se brosser les dents deux fois par jour. On utilise du dentifrice et une brosse. Des dents propres restent en santé."] },
  ],
  [
    "Quelle est l'idée principale?",
    "Le vent est de l'air qui fait bouger des choses.",
    ["Les cerfs-volants sont colorés.", "Les moulins sont grands."],
    MAIN_HINT,
    { type: "passage", title: "Le vent", paragraphs: ["Le vent est de l'air qui bouge. Il fait tourner les moulins et voler les cerfs-volants. Parfois, il fait danser les arbres."] },
  ],
  [
    "Quelle est l'idée principale?",
    "Ravi apprend à nager avec de la pratique.",
    ["Ravi aime la piscine.", "Le moniteur est gentil."],
    MAIN_HINT,
    { type: "passage", title: "Apprendre à nager", paragraphs: ["Ravi veut apprendre à nager. Chaque samedi, il va à la piscine avec son moniteur. Après un mois, il nage sans aide."] },
  ],
  [
    "Quelle est l'idée principale?",
    "L'année a quatre saisons.",
    ["L'hiver est froid.", "L'été est chaud."],
    MAIN_HINT,
    { type: "passage", title: "Les saisons", paragraphs: ["Il y a quatre saisons : le printemps, l'été, l'automne et l'hiver. Elles reviennent chaque année dans le même ordre."] },
  ],
  [
    "Quelle est l'idée principale?",
    "Les castors construisent des barrages pour créer un étang.",
    ["Les castors ont de grandes dents.", "Les castors aiment la boue."],
    MAIN_HINT,
    { type: "passage", title: "Les castors", paragraphs: ["Les castors construisent des barrages avec des branches et de la boue. Ces barrages créent un étang. Dans l'étang, les castors sont en sécurité."] },
  ],
  [
    "Quelle est l'idée principale?",
    "Dormir est important pour les enfants.",
    ["Les lits sont doux.", "Les enfants aiment jouer."],
    MAIN_HINT,
    { type: "passage", title: "Le sommeil", paragraphs: ["Les enfants ont besoin de dormir environ dix heures. Le sommeil donne de l'énergie. Il aide aussi à bien apprendre."] },
  ],
  [
    "Quelle est l'idée principale?",
    "La classe s'occupe d'un jardin.",
    ["Nous aimons les légumes.", "L'automne est une belle saison."],
    MAIN_HINT,
    { type: "passage", title: "Le jardin de l'école", paragraphs: ["Notre classe a un jardin. Nous semons des graines au printemps. Nous arrosons les plantes et nous mangeons les légumes en automne."] },
  ],
  [
    "Quelle est l'idée principale?",
    "Les baleines sont de grands animaux marins.",
    ["Les bébés aiment le lait.", "La mer est salée."],
    MAIN_HINT,
    { type: "passage", title: "Les baleines", paragraphs: ["Les baleines sont les plus grands animaux de la mer. Elles respirent de l'air à la surface. Les bébés boivent le lait de leur mère."] },
  ],
  [
    "Quelle est l'idée principale?",
    "Léa et Jay s'amusent dans la neige.",
    ["Il fait très froid.", "Léa aime le chocolat."],
    MAIN_HINT,
    { type: "passage", title: "Dans la neige", paragraphs: ["Quand il neige, Léa et Jay font un bonhomme de neige. Ensuite, ils glissent sur une colline. À la fin, ils boivent du chocolat chaud."] },
  ],
  [
    "Quelle est l'idée principale?",
    "Les pompiers aident et protègent les gens.",
    ["Les camions sont rouges.", "Les pompiers portent un casque."],
    MAIN_HINT,
    { type: "passage", title: "Les pompiers", paragraphs: ["Les pompiers éteignent les feux. Ils aident aussi les gens en danger. Ils s'entraînent chaque jour."] },
  ],
  [
    "Quelle est l'idée principale?",
    "Un arc-en-ciel se forme avec la pluie et le soleil.",
    ["Les gouttes sont petites.", "Le ciel est gris."],
    MAIN_HINT,
    { type: "passage", title: "L'arc-en-ciel", paragraphs: ["Un arc-en-ciel apparaît quand il pleut et qu'il y a du soleil. La lumière traverse les gouttes d'eau. Elle se sépare en plusieurs couleurs."] },
  ],
  [
    "Quelle est l'idée principale?",
    "Priya fait une carte pour sa grand-maman.",
    ["Priya aime peindre.", "Grand-maman a une maison."],
    MAIN_HINT,
    { type: "passage", title: "Une carte spéciale", paragraphs: ["Priya veut faire un cadeau. Elle peint une carte et la décore avec des étoiles. Grand-maman sourit en la voyant."] },
  ],
  [
    "Quelle est l'idée principale?",
    "Il faut faire attention pour rouler en vélo en sécurité.",
    ["Les vélos ont deux roues.", "Le casque est bleu."],
    MAIN_HINT,
    { type: "passage", title: "Le vélo", paragraphs: ["Pour rouler en sécurité, on porte un casque. On regarde bien avant de traverser. On s'arrête quand la rue est occupée."] },
  ],
  [
    "Quelle est l'idée principale?",
    "La Lune a des formes différentes.",
    ["La Lune est loin.", "Le ciel est noir la nuit."],
    MAIN_HINT,
    { type: "passage", title: "La Lune", paragraphs: ["La Lune change de forme dans le ciel. Parfois, on voit un croissant. D'autres soirs, on voit un cercle complet."] },
  ],
];

export const course: Course = {
  grade: "3",
  subject: "immersion",
  bigIdeas: {
    "ca-bc": [
      "Making connections between personal experiences and the experiences of others can help us to better understand and respond to a message.",
      "Texts present cultural elements that allow us to experience or understand different viewpoints.",
      "The structure and textual cues, as well as the words, all help to convey the message.",
      "Fairy and folk tales illustrate universal aspects of human life.",
      "Every language has a system of rules that distinguishes it from other languages.",
    ],
  },
  units: [
    {
      id: "verbes-pronominaux",
      title: "Je me, tu te, il se",
      emoji: "🪥",
      blurb: "Les verbes pronominaux",
      parentNote: "Reflexive pronouns (me, te, se, nous, vous) with everyday routines like se laver and se coucher.",
      standards: { "ca-bc": "Language elements: reflexive personal pronouns" },
      generate: (o) => frQuestions(REFLEXIVE, o, 8, FR),
    },
    {
      id: "et-mais-ou-avec",
      title: "Et, mais, ou, avec",
      emoji: "🔗",
      blurb: "Relier des idées",
      parentNote: "Joining ideas into longer sentences with coordinating conjunctions and simple prepositions.",
      standards: { "ca-bc": "Language elements: complex sentences joined by coordinating conjunctions and simple prepositions (et, mais, ou, avec)" },
      generate: (o) => frQuestions(LINKS, o, 8, FR),
    },
    {
      id: "ne-pas",
      title: "Ne… pas",
      emoji: "🚫",
      blurb: "Dire non",
      parentNote: "The negative form ne… pas, including n' before a vowel sound.",
      standards: { "ca-bc": "Language elements: affirmative and negative forms, including ne… pas" },
      generate: (o) => frQuestions(NEGATIVES, o, 8, FR),
    },
    {
      id: "futur-proche",
      title: "Le futur proche",
      emoji: "🔮",
      blurb: "Je vais jouer",
      parentNote: "Talking about what is about to happen with aller + a verb, and telling past from future.",
      standards: { "ca-bc": "Language elements: verb moods and tenses (present, near future, introduction to past tenses)" },
      generate: (o) => frQuestions(FUTURE, o, 8, FR),
    },
    {
      id: "pluriels-en-x",
      title: "Les pluriels en -x",
      emoji: "✖️",
      blurb: "Bateaux et chevaux",
      parentNote: "Plural spellings: -eau/-eu/-ou nouns add an x, and -al nouns become -aux.",
      standards: { "ca-bc": "Spelling conventions: plural nouns ending in “x”" },
      generate: (o) => frQuestions(PLURALS, o, 8, FR),
    },
    {
      id: "prefixes-et-suffixes",
      title: "Préfixes et suffixes",
      emoji: "🧱",
      blurb: "Les morceaux des mots",
      parentNote: "Using prefixes and suffixes (re-, dé-, in-, -ette, -eur, -ier) to work out the meaning of new words.",
      standards: { "ca-bc": "Language elements: word roots, prefixes and suffixes" },
      generate: (o) => frQuestions(AFFIXES, o, 8, FR),
    },
    {
      id: "idee-principale",
      title: "L'idée principale",
      emoji: "💡",
      blurb: "De quoi parle le texte?",
      parentNote: "Reading a short text and telling the main idea apart from smaller details.",
      standards: { "ca-bc": "Identify the main idea in oral, written or visual texts" },
      generate: (o) => frQuestions(MAIN_IDEA, o, 6, FR),
    },
  ],
};
